#!/usr/bin/env python3
"""Generated by COLLECTIVE settings. Contains private worker credentials."""
import ipaddress
import json
import os
import platform
import pwd
import shutil
import socket
import stat
import subprocess
import sys
import tempfile
import time
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

CONFIG_HEX = '__COLLECTIVE_CONFIG_HEX__'
WORKER_HEX = '__COLLECTIVE_WORKER_HEX__'
PREFIX = Path('/opt/collective-browser')
SERVICE = 'collective-research-worker.service'
# 브라우저는 전용 비특권 계정으로만 실행한다. HERMES 설정·비밀과 작업자 자격증명(hermes 소유)은 이 계정이 읽지 못한다.
BROWSER_USER = 'collective-browser'
BROWSER_HOME = Path('/var/lib/collective-browser')
BROWSER_SERVICE = 'collective-browser.service'
FIREWALL_SERVICE = 'collective-browser-firewall.service'
CHROME = PREFIX / 'chromium' / 'chrome'
CDP_PORT = 9333
CDP_URL = 'http://127.0.0.1:' + str(CDP_PORT)
# HERMES는 AGENT_BROWSER_ARGS가 없으면 userns 제한 환경에서 --no-sandbox를 스스로 넣는다. 값을 채워 그 경로를 막는다.
HERMES_BROWSER_ARGS = '--disable-dev-shm-usage'
# npm 설치·Chromium 내려받기 전용 계정. 결과는 root 소유 경로로 복사해 이 계정도 나중에 고칠 수 없다.
NPM_USER = 'collective-npm'
NPM_HOME = Path('/var/lib/collective-npm')
# 큐 워커 전용 계정. worker.json(owner 토큰·공통 gate)은 이 계정만 읽는다. hermes(에이전트)도 읽지 못한다.
WORKER_USER = 'collective-worker'
WORKER_HOME = Path('/var/lib/collective-worker')
# api_server 도구셋에는 원시 브라우저 제어 도구만 끄는 설정이 없어 HERMES pre_tool_call 셸 훅으로 호출을 막는다.
# CDP 주소를 설정하면 두 도구가 목록에 나타나지만, 이 훅 때문에 호출은 실패한다(fail_closed: 훅이 실패해도 막음).
RAW_TOOL_MATCHER = '^(browser_cdp|browser_dialog)$'
HOOK_SCRIPT = PREFIX / 'hooks' / 'deny-raw-browser.sh'
HOOK_EVENT = 'pre_tool_call'
# route get으로 기본 경로의 출발 주소를 얻을 때 쓰는 문서용 주소(RFC 5737·RFC 3849). 실제로 연결하지 않는다.
ROUTE_PROBES = ('192.0.2.1', '2001:db8::1')
# 정확한 버전과 레지스트리 integrity를 고정한다(의존성 없음). 버전을 바꿀 때는 README의 lockfile 생성 절차를 따른다.
AGENT_BROWSER_VERSION = '0.26.0'
AGENT_BROWSER_INTEGRITY = 'sha512-pdqSfjwbFSp+qnwlb2g23e9wXveIOfMi19xpPA9xZUbzEAUp6W4YBZj6Ybj8z4M7WkcbGDDYc+oDIHDt9R3EDQ=='
# 브라우저 계정이 새로 연결할 수 없는 목적지: 이 네트워크·사설망·CGNAT·루프백·링크로컬.
# 저장소 주소 검사(tests/security-boundaries.test.mjs)가 점 표기 IPv4를 막으므로 줄임 표기로 적고 expand_cidr로 펼친다.
BLOCKED_V4 = ('0/8', '10/8', '100.64/10', '127/8', '169.254/16', '172.16/12', '192.168/16')
BLOCKED_V6 = ('::/128', '::1/128', 'fc00::/7', 'fe80::/10')
NFT_RULES = Path('/etc/collective-browser/nftables.conf')
APPARMOR_PROFILE = Path('/etc/apparmor.d/collective-chromium')
# Chrome for Testing·Chromium·Chrome 빌드가 각각 읽는 정책 경로. 실제 적용은 설치 점검의 file:// 음성 테스트로 확인한다.
POLICY_DIRS = tuple(Path(p) for p in ('/etc/opt/chrome_for_testing/policies/managed', '/etc/chromium/policies/managed',
                                      '/etc/opt/chrome/policies/managed'))
# Chromium 실행 라이브러리. agent-browser install --with-deps(서드파티 코드)를 root로 돌리지 않으려고 설치기가 직접 설치한다.
# 튜플은 Ubuntu 24.04의 t64 이름을 먼저, 이전 이름을 다음으로 둔다.
CHROME_LIBS = ('libxcb-shm0', 'libx11-xcb1', 'libxcb1', 'libxrandr2', 'libxcomposite1', 'libxcursor1', 'libxdamage1',
               'libxfixes3', 'libxi6', ('libgtk-3-0t64', 'libgtk-3-0'), ('libpangocairo-1.0-0t64', 'libpangocairo-1.0-0'),
               ('libpango-1.0-0t64', 'libpango-1.0-0'), ('libatk1.0-0t64', 'libatk1.0-0'),
               ('libcairo-gobject2t64', 'libcairo-gobject2'), ('libcairo2t64', 'libcairo2'),
               ('libgdk-pixbuf-2.0-0t64', 'libgdk-pixbuf-2.0-0'), 'libxrender1', ('libasound2t64', 'libasound2'),
               'libfreetype6', 'libfontconfig1', ('libdbus-1-3t64', 'libdbus-1-3'), 'libnss3',
               ('libatk-bridge2.0-0t64', 'libatk-bridge2.0-0'), 'libdrm2', 'libxkbcommon0',
               ('libatspi2.0-0t64', 'libatspi2.0-0'), ('libcups2t64', 'libcups2'), 'libxshmfence1', 'libgbm1',
               'fonts-noto-color-emoji', 'fonts-noto-cjk', 'fonts-freefont-ttf')
# root 권한이 꼭 필요한 단계. npm 설치·Chromium 내려받기(NPM_USER), 브라우저 실행(BROWSER_USER), 큐 워커(hermes)는 root가 아니다.
ROOT_STEPS = ('apt 패키지 설치', '전용 계정 생성', 'root 소유 경로로 복사', 'AppArmor 프로필', 'nftables 규칙', 'Chrome 정책',
              'systemd 유닛·서비스', 'HERMES 설정 백업·변경', '격리 점검')
CONNECT = 'import socket,sys; socket.create_connection((sys.argv[1], int(sys.argv[2])), 5)'

def run(args, **kwargs):
    return subprocess.run([str(x) for x in args], check=True, **kwargs)

def find_chrome(browsers):
    # agent-browser strips chrome-linux64/ from new downloads; older caches
    # can retain it. Accept both layouts, but only actual executable files.
    candidates = [directory / relative for directory in browsers.glob('chrome-*')
                  for relative in ('chrome', 'chrome-linux64/chrome')
                  if (directory / relative).is_file() and os.access(directory / relative, os.X_OK)]
    if not candidates:
        raise RuntimeError('Chromium executable was not found. HERMES config is unchanged.')
    return max(candidates, key=lambda p: p.stat().st_mtime)

def atomic(path, data, uid=0, gid=0, mode=0o600):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix='.collective-', dir=path.parent)
    try:
        with os.fdopen(fd, 'wb') as stream:
            # 소유자·권한은 파일 기술자로 바꾼다. 경로 기준으로 바꾸면 다른 계정이 임시 파일을 링크로 바꿔 대상을 바꿀 수 있다.
            os.fchown(stream.fileno(), uid, gid)
            os.fchmod(stream.fileno(), mode)
            stream.write(data if isinstance(data, bytes) else data.encode())
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)

def parse_args(argv):
    unknown = [x for x in argv if x != '--allow-no-sandbox']
    if unknown:
        raise RuntimeError('알 수 없는 옵션입니다: ' + ' '.join(unknown) + ' (지원: --allow-no-sandbox)')
    return {'allow_no_sandbox': '--allow-no-sandbox' in argv}

def as_user(user, home, argv):
    # 대상 계정에는 최소 환경만 넘긴다. root 쪽 환경변수(sudo 정보 등)는 전달하지 않는다.
    return ['runuser', '-u', user, '--', 'env', '-i', 'HOME=' + str(home), 'PATH=/usr/local/bin:/usr/bin:/bin',
            'LANG=C.UTF-8'] + [str(x) for x in argv]

def npm_files(version=AGENT_BROWSER_VERSION, integrity=AGENT_BROWSER_INTEGRITY):
    files = {'package.json': {'name': 'collective-browser', 'private': True, 'dependencies': {'agent-browser': version}}}
    if integrity:
        files['package-lock.json'] = {'name': 'collective-browser', 'lockfileVersion': 3, 'requires': True, 'packages': {
            '': {'name': 'collective-browser', 'dependencies': {'agent-browser': version}},
            'node_modules/agent-browser': {'version': version, 'integrity': integrity, 'hasInstallScript': True,
                'resolved': 'https://registry.npmjs.org/agent-browser/-/agent-browser-' + version + '.tgz',
                'license': 'Apache-2.0', 'bin': {'agent-browser': 'bin/agent-browser.js'}}}}
    return {name: json.dumps(value, indent=2) + '\n' for name, value in files.items()}

def npm_command(locked):
    # lifecycle 스크립트(postinstall 등)는 실행하지 않는다. 네이티브 실행 파일은 패키지에 들어 있고 실행 권한은 설치기가 준다.
    if locked:
        return ['npm', 'ci', '--ignore-scripts', '--no-audit', '--no-fund']
    return ['npm', 'install', '--ignore-scripts', '--no-audit', '--no-fund', '--save-exact',
            'agent-browser@' + AGENT_BROWSER_VERSION]

def download_commands(stage, locked):
    """npm 설치와 Chromium 내려받기. 둘 다 서드파티 코드를 받으므로 NPM_USER로만 실행한다."""
    return [as_user(NPM_USER, NPM_HOME, npm_command(locked)),
            as_user(NPM_USER, NPM_HOME, [stage / 'node_modules/.bin/agent-browser', 'install'])]

def pick_packages(groups, available):
    chosen = []
    for group in groups:
        names = (group,) if isinstance(group, str) else group
        name = next((n for n in names if available(n)), None)
        if name is None:
            raise RuntimeError('Chromium 실행 라이브러리 패키지를 찾지 못했습니다: ' + ' / '.join(names))
        chosen.append(name)
    return chosen

def apt_candidate(name):
    output = subprocess.run(['apt-cache', 'policy', name], capture_output=True, text=True).stdout
    return 'Candidate:' in output and 'Candidate: (none)' not in output

def expand_cidr(short):
    prefix, bits = short.split('/')
    octets = prefix.split('.')
    return str(ipaddress.ip_network('.'.join(octets + ['0'] * (4 - len(octets))) + '/' + bits))

def blocked_networks():
    return [ipaddress.ip_network(expand_cidr(x)) for x in BLOCKED_V4] + [ipaddress.ip_network(x) for x in BLOCKED_V6]

def dns_exceptions(resolv_conf):
    # resolv.conf의 네임서버가 차단 대역 안(예: systemd-resolved 루프백 스텁)이면 그 주소의 53번 포트만 연다.
    found = []
    for parts in (line.split() for line in resolv_conf.splitlines()):
        if len(parts) < 2 or parts[0] != 'nameserver':
            continue
        try:
            address = ipaddress.ip_address(parts[1].split('%')[0])
        except ValueError:
            continue
        if address not in found and any(address in network for network in blocked_networks()):
            found.append(address)
    return found

def nft_rules(uid, dns=(), cdp_clients=()):
    # 선언→삭제→정의로 이 테이블만 원자적으로 교체한다. 다른 방화벽(ufw 등) 규칙은 건드리지 않는다.
    # 브라우저 계정 소켓의 패킷만 검사하고, 이미 성립된 연결(HERMES→CDP 응답 등)은 통과시킨다.
    lines = ['table inet collective_browser', 'delete table inet collective_browser', 'table inet collective_browser {',
             '  chain browser {', '    ct state established,related accept']
    lines += ['    ' + ('ip' if a.version == 4 else 'ip6') + ' daddr ' + str(a) + ' meta l4proto { tcp, udp } th dport 53 accept'
              for a in dns]
    # 서버 자신의 주소(공인 IP 포함)는 lo로 전달돼 클라우드 방화벽을 거치지 않는다. 브로드캐스트·멀티캐스트(LAN 탐색)도 막는다.
    lines += ['    fib daddr type { local, broadcast, multicast } reject',
              '    ip daddr { ' + ', '.join(expand_cidr(x) for x in BLOCKED_V4) + ' } reject',
              '    ip6 daddr { ' + ', '.join(str(ipaddress.ip_network(x)) for x in BLOCKED_V6) + ' } reject', '  }',
              '  chain output {', '    type filter hook output priority filter; policy accept;',
              '    meta skuid ' + str(uid) + ' jump browser']
    if cdp_clients:
        # 인증 없는 CDP 포트에는 지정한 계정(root·hermes)만 새로 연결한다. 브라우저의 응답(출발 포트 9333)은 해당하지 않는다.
        allowed = ' tcp dport ' + str(CDP_PORT) + ' meta skuid != { ' + ', '.join(str(x) for x in cdp_clients) + ' } reject'
        lines += ['    ip daddr ' + expand_cidr('127/8') + allowed, '    ip6 daddr ::1' + allowed]
    return '\n'.join(lines + ['  }', '}']) + '\n'

def apparmor_profile(chrome):
    # Ubuntu 24.04의 비특권 user namespace 제한 아래에서 이 Chromium만 샌드박스용 userns를 쓰게 한다(--no-sandbox 대신).
    return ('abi <abi/4.0>,\ninclude <tunables/global>\n\n'
            'profile collective-chromium ' + str(chrome) + ' flags=(unconfined) {\n  userns,\n\n'
            '  include if exists <local/collective-chromium>\n}\n')

def sandbox_decision(restricted, apparmor_error, allow_no_sandbox):
    """샌드박스를 끄면 True. 프로필 적용 실패는 --allow-no-sandbox가 있을 때만 예외로 넘기고, 없으면 설치를 멈춘다."""
    if not restricted or apparmor_error is None:
        return False
    if not allow_no_sandbox:
        raise RuntimeError('Chromium 샌드박스용 AppArmor 프로필을 적용하지 못해 설치를 중단했습니다: ' + apparmor_error +
                           '\n샌드박스 없이 설치하려면 이유를 기록한 뒤 --allow-no-sandbox를 붙여 다시 실행하세요. HERMES 설정은 바뀌지 않았습니다.')
    print('경고: AppArmor 프로필을 적용하지 못했습니다(' + apparmor_error + '). --allow-no-sandbox에 따라 샌드박스 없이 실행합니다.', flush=True)
    return True

def chrome_flags(no_sandbox=False):
    flags = ['--headless=new', '--disable-dev-shm-usage', '--no-first-run', '--no-default-browser-check']
    return flags + (['--no-sandbox'] if no_sandbox else [])

def browser_unit(chrome, no_sandbox=False):
    command = ' '.join([str(chrome)] + chrome_flags(no_sandbox) + ['--remote-debugging-port=' + str(CDP_PORT),
                       '--user-data-dir=' + str(BROWSER_HOME / 'profile'), 'about:blank'])
    return ('[Unit]\nDescription=COLLECTIVE research browser (isolated Chromium)\nBindsTo=' + FIREWALL_SERVICE +
            '\nAfter=' + FIREWALL_SERVICE + ' network-online.target\nWants=network-online.target\n\n'
            '[Service]\nType=simple\nUser=' + BROWSER_USER + '\nGroup=' + BROWSER_USER + '\nEnvironment=HOME=' +
            str(BROWSER_HOME) + '\nWorkingDirectory=' + str(BROWSER_HOME) + '\nExecStart=' + command +
            '\nRestart=always\nRestartSec=5\nPrivateTmp=true\nProtectSystem=strict\nProtectHome=true\nReadWritePaths=' +
            str(BROWSER_HOME) + '\nUMask=0077\n\n[Install]\nWantedBy=multi-user.target\n')

def firewall_unit():
    # nftables.service를 다시 읽거나 재시작하면 /etc/nftables.conf의 flush ruleset이 이 테이블을 지운다. 그때 함께 다시 넣는다.
    return ('[Unit]\nDescription=COLLECTIVE research browser network limits\nBefore=' + BROWSER_SERVICE +
            '\nAfter=nftables.service\nPartOf=nftables.service\nReloadPropagatedFrom=nftables.service\n\n'
            '[Service]\nType=oneshot\nRemainAfterExit=yes\nExecStart=/usr/sbin/nft -f ' + str(NFT_RULES) +
            '\nExecReload=/usr/sbin/nft -f ' + str(NFT_RULES) +
            '\nExecStop=/usr/sbin/nft delete table inet collective_browser\n\n[Install]\nWantedBy=multi-user.target\n')

def chrome_policy():
    # 로컬 파일과 브라우저 내부 페이지(about: 별칭 포함)를 막는다. about:blank·data:·blob:은 일반 웹과 새 탭이 쓰므로 둔다.
    return json.dumps({'URLBlocklist': ['file://*', 'chrome://*', 'chrome-untrusted://*']}, indent=2) + '\n'

def hermes_env_block(suffix):
    # HERMES dotenv loads with override=True after systemd. Explicit values also prevent repo .env fallback
    # from restoring a remote browser dependency. HERMES는 격리 브라우저의 루프백 CDP에만 붙는다.
    # 이전 설치가 넣은 AGENT_BROWSER_EXECUTABLE_PATH(hermes 소유 Chromium)는 비워 로컬 실행 경로로 되살아나지 않게 한다.
    values = (('BROWSER_CDP_URL', CDP_URL), ('AGENT_BROWSER_CDP_URL', ''), ('AGENT_BROWSER_HEADED', '0'),
              ('AGENT_BROWSER_ENGINE', 'chrome'), ('AGENT_BROWSER_ARGS', HERMES_BROWSER_ARGS),
              ('AGENT_BROWSER_EXECUTABLE_PATH', ''))
    return '\n# COLLECTIVE server browser ' + suffix + '\n' + ''.join(k + '=' + json.dumps(v) + '\n' for k, v in values)

def hermes_path(home):
    return str(PREFIX / 'node_modules/.bin')+':'+str(home / '.local/bin')+':/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

def hermes_dropin(home):
    override = '[Service]\nEnvironment="PATH='+hermes_path(home)+'"\n'
    # Replace an inherited Mac/remote CDP URL with the isolated local browser.
    override += 'Environment="BROWSER_CDP_URL='+CDP_URL+'"\nEnvironment="AGENT_BROWSER_ARGS='+HERMES_BROWSER_ARGS+'"\n'
    return override + 'UnsetEnvironment=AGENT_BROWSER_CDP_URL AGENT_BROWSER_HEADED AGENT_BROWSER_EXECUTABLE_PATH\n'

def hook_script():
    # HERMES는 pre_tool_call 훅이 exit 2로 끝나면 호출을 막고 stderr를 사유로 모델에 돌려준다. stdin(호출 내용)은 읽고 버린다.
    return ('#!/bin/sh\n# COLLECTIVE 조사 서버: 원시 브라우저 제어 도구(browser_cdp·browser_dialog) 호출을 막는다.\n'
            'cat >/dev/null\necho "COLLECTIVE 조사 서버 정책: browser_cdp·browser_dialog는 사용할 수 없습니다. '
            'browser_navigate·browser_snapshot 같은 일반 브라우저 도구를 쓰세요." >&2\nexit 2\n')

def hermes_hooks(existing):
    """설정의 hooks 블록에 차단 훅을 넣은 새 값을 돌려준다. 다른 훅은 그대로 두고, 같은 명령의 이전 항목만 바꾼다."""
    hooks = dict(existing) if isinstance(existing, dict) else {}
    current = hooks.get(HOOK_EVENT) if isinstance(hooks.get(HOOK_EVENT), list) else []
    entry = {'matcher': RAW_TOOL_MATCHER, 'command': str(HOOK_SCRIPT), 'timeout': 5, 'fail_closed': True}
    return {**hooks, HOOK_EVENT: [x for x in current if not (isinstance(x, dict) and x.get('command') == str(HOOK_SCRIPT))] + [entry]}

def hook_allowlist(previous, approved_at):
    """shell-hooks-allowlist.json에 이 훅의 (event, command)만 승인한다. hooks_auto_accept는 켜지 않는다."""
    try:
        data = json.loads(previous) if previous else {}
    except ValueError:
        data = {}
    data = data if isinstance(data, dict) else {}
    approvals = data.get('approvals') if isinstance(data.get('approvals'), list) else []
    ours = {'event': HOOK_EVENT, 'command': str(HOOK_SCRIPT)}
    kept = [x for x in approvals if not (isinstance(x, dict) and x.get('event') == HOOK_EVENT and x.get('command') == str(HOOK_SCRIPT))]
    return json.dumps({**data, 'approvals': kept + [{**ours, 'approved_at': approved_at}]}, indent=2, sort_keys=True) + '\n'

def hook_support_missing(shell_hooks_source, gateway_source):
    """설치된 HERMES가 게이트웨이에서 pre_tool_call 셸 훅·fail_closed·승인 목록을 지원하는지 소스로 확인한다."""
    missing = [key for key in (HOOK_EVENT, 'fail_closed', 'shell-hooks-allowlist.json') if key not in shell_hooks_source]
    return missing + ([] if 'agent.shell_hooks import register_from_config' in gateway_source else ['gateway register_from_config'])

def hook_check_problem(command, listed, blocked, allowed):
    """hermes hooks list·test 출력으로 훅이 승인됐고, browser_cdp는 막고, 일반 도구는 건드리지 않는지 판정한다."""
    if not any(command in line and '\u2713 allowed' in line for line in listed.splitlines()):
        return '차단 훅이 HERMES 승인 목록에 없습니다(hermes hooks list)'
    ours = blocked.split('\u2192 ' + command, 1)
    if len(ours) < 2 or '"action": "block"' not in ours[1].split('\u2192 ', 1)[0]:
        return '차단 훅이 browser_cdp 호출을 막지 않았습니다(hermes hooks test)'
    if command in allowed:
        return '차단 훅이 일반 브라우저 도구(browser_navigate)에도 걸립니다'
    return ''

def isolation_problems(account, hermes, groups):
    problems = []
    if account.pw_uid in (0, hermes.pw_uid):
        problems.append('root 또는 hermes와 같은 UID')
    if {0, hermes.pw_gid} & set(groups):
        problems.append('root 또는 hermes 그룹 소속')
    return problems

def worker_unit():
    return ('[Unit]\nDescription=COLLECTIVE durable research queue\nWants=network-online.target\nAfter=network-online.target\n\n'
            '[Service]\nType=simple\nUser=' + WORKER_USER + '\nExecStart=/usr/bin/python3 /opt/collective-research/worker.py '
            '/etc/collective-research/worker.json\nRestart=on-failure\nRestartSec=15\nRestartPreventExitStatus=78\n'
            'NoNewPrivileges=true\nPrivateTmp=true\nProtectSystem=strict\nProtectHome=true\n'
            'ReadWritePaths=/etc/collective-research\nUMask=0077\n\n'
            '[Install]\nWantedBy=multi-user.target\n')

def without_other_access(path):
    mode = stat.S_IMODE(path.stat().st_mode)
    if mode & 0o007:
        os.chmod(path, mode & ~0o007)

def file_denials(worker_config_path, hermes_root):
    """브라우저 계정으로 읽기를 시도해 반드시 실패해야 하는 비밀 파일(음성 테스트)."""
    targets = (('작업자 자격증명', worker_config_path), ('HERMES 설정', hermes_root / 'config.yaml'),
               ('HERMES 비밀', hermes_root / '.env'))
    return [(label, path, as_user(BROWSER_USER, BROWSER_HOME, ['cat', path])) for label, path in targets]

def worker_denial(worker_config_path, hermes_home):
    # HERMES 에이전트(hermes 계정)가 프롬프트 인젝션을 받아도 작업자 자격증명을 읽지 못해야 한다.
    return '작업자 자격증명', as_user('hermes', hermes_home, ['cat', worker_config_path])

def worker_readable(worker_config_path):
    # 양성 대조군: 워커 계정은 같은 파일을 읽을 수 있어야 hermes 거부가 권한 때문임을 증명한다.
    return as_user(WORKER_USER, WORKER_HOME, ['test', '-r', worker_config_path])

def network_denial():
    # 실제로 열려 있는 CDP 포트를 대상으로 해야 '방화벽 때문에 실패'를 증명한다(양성 대조군은 cdp_websocket).
    return '루프백 접속(127.0.0.1)', as_user(BROWSER_USER, BROWSER_HOME, ['python3', '-c', CONNECT, '127.0.0.1', CDP_PORT])

def cdp_client_denial():
    # root·hermes 밖의 로컬 계정은 인증 없는 CDP 포트에 붙지 못해야 한다(양성 대조군은 root의 cdp_websocket).
    return 'CDP 포트 접속(' + NPM_USER + ' 계정)', as_user(NPM_USER, NPM_HOME, ['python3', '-c', CONNECT, '127.0.0.1', CDP_PORT])

def host_denial(address, port):
    return '서버 자신의 주소 접속(' + address + ')', as_user(BROWSER_USER, BROWSER_HOME, ['python3', '-c', CONNECT, address, port])

class IsolationError(RuntimeError):
    """격리 점검 실패. 설치 전 상태와 관계없이 격리 브라우저를 끈다."""

def keep_browser(error, was_active):
    # 격리 점검 실패면 항상 끈다. 기능 점검·설정 단계 실패면 설치 전 상태(켜져 있었으면 유지)로 둔다.
    return was_active and not isinstance(error, IsolationError)

def expect_denied(label, command, runner=subprocess.run, who='브라우저 계정'):
    result = runner([str(x) for x in command], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=30)
    if result.returncode == 0:
        raise IsolationError('격리 점검 실패: ' + who + '이 ' + label + '에 접근했습니다. 설치를 중단합니다.')
    print('격리 확인: ' + who + '의 ' + label + ' 거부됨', flush=True)

def route_source(output):
    parts = output.split()
    return parts[parts.index('src') + 1] if 'src' in parts[:-1] else None

def listener_uids(proc_net, port):
    """/proc/net/tcp·tcp6에서 port를 LISTEN 중인 소켓의 소유 UID. 다른 계정이 포트를 먼저 잡았는지 확인한다."""
    return {int(f[7]) for f in (line.split() for line in proc_net.splitlines())
            if len(f) > 7 and f[3] == '0A' and f[1].rsplit(':', 1)[-1] == '%04X' % port}

def loopback_websocket(url):
    return url.startswith('ws://127.0.0.1:' + str(CDP_PORT) + '/devtools/browser/')

def has_page(targets, prefix):
    return any(isinstance(t, dict) and t.get('type') == 'page' and str(t.get('url', '')).startswith(prefix) for t in targets)

def smoke_command(user_command, websocket):
    # HERMES와 같은 형태로 --cdp만 넘긴다. agent-browser 0.13 이상은 --session이 있으면 --cdp를 무시하고 로컬 브라우저를 띄운다.
    return user_command + [str(PREFIX / 'node_modules' / '.bin' / 'agent-browser'), '--cdp', websocket]

def policy_problem(marker, file_output, recheck_output):
    """file:// 음성 테스트 판정. 마커가 없다는 것만으로는 시간 초과·비정상 종료와 구분되지 않아 직후 data: 재확인을 요구한다."""
    if marker in file_output:
        return 'Chrome 정책(URLBlocklist)이 적용되지 않아 file:// 페이지가 열렸습니다. 설치를 중단합니다.'
    if marker not in recheck_output:
        return 'file:// 점검 직후 Chromium이 data: 페이지를 읽지 못해 정책 차단을 확인하지 못했습니다. 설치를 중단합니다.'
    return ''

def install_tree(source, target, uid=0, gid=0, top=None):
    # 새 사본을 옆에 만든 뒤 이름을 바꿔 교체한다. 실행 중인 프로세스는 이전 파일을 계속 쓴다.
    # top=(gid, mode)면 바꿔 넣기 전에 맨 위 폴더의 그룹과 권한을 정한다.
    fresh, old = target.with_name('.' + target.name + '-new'), target.with_name('.' + target.name + '-old')
    for path in (fresh, old):
        shutil.rmtree(path, ignore_errors=True)
    shutil.copytree(source, fresh, symlinks=True)
    for directory, dirs, files in os.walk(fresh):
        for path in [directory] + [os.path.join(directory, x) for x in dirs + files]:
            os.lchown(path, uid, gid)
            if not os.path.islink(path):
                os.chmod(path, stat.S_IMODE(os.lstat(path).st_mode) & ~0o022)
    if top:
        os.chown(fresh, uid, top[0])
        os.chmod(fresh, top[1])
    if target.exists():
        target.rename(old)
    fresh.rename(target)
    shutil.rmtree(old, ignore_errors=True)

def ensure_account(name, home, hermes):
    try:
        account = pwd.getpwnam(name)
    except KeyError:
        run(['useradd', '--system', '--user-group', '--home-dir', home, '--shell', '/usr/sbin/nologin', name])
        account = pwd.getpwnam(name)
    problems = isolation_problems(account, hermes, os.getgrouplist(name, account.pw_gid))
    if problems:
        raise RuntimeError(name + ' 계정이 root·hermes와 분리되어 있지 않습니다(' + ', '.join(problems) + '). HERMES config is unchanged.')
    home.mkdir(parents=True, exist_ok=True)
    os.chown(home, account.pw_uid, account.pw_gid)
    os.chmod(home, 0o700)
    return account

def install_packages():
    apt_env = dict(os.environ, DEBIAN_FRONTEND='noninteractive')
    run(['apt-get', 'update'], env=apt_env)
    libraries = pick_packages(CHROME_LIBS, apt_candidate)
    run(['apt-get', 'install', '-y', 'nodejs', 'npm', 'ca-certificates', 'nftables', 'apparmor'] + libraries, env=apt_env)
    node_major = int(subprocess.check_output(['node', '--version'], text=True).strip().lstrip('v').split('.')[0])
    if node_major < 18:
        raise RuntimeError('Node 18 or newer is required; HERMES config is unchanged.')

def stop_processes(user, runner=subprocess.run, sleep=time.sleep):
    """계정에 남은 프로세스를 모두 끝낸다. 서드파티 코드가 root의 다음 파일 작업과 경쟁하지 못하게 한다."""
    for _ in range(5):
        if runner(['pgrep', '-u', user], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 1:
            return
        runner(['pkill', '-KILL', '-u', user], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        sleep(0.5)
    raise RuntimeError(user + ' 계정의 프로세스를 끝내지 못해 설치를 중단했습니다. HERMES 설정은 바뀌지 않았습니다.')

def fresh_directory(path, uid, gid):
    """비특권 계정이 쓰던 경로를 root가 새로 만든다. 심볼릭 링크는 따라가지 않고 링크 자체를 지운다."""
    if path.is_symlink() or (path.exists() and not path.is_dir()):
        path.unlink()
    elif path.exists():
        shutil.rmtree(path)
    os.mkdir(path, 0o700)
    fd = os.open(path, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
    try:
        os.fchown(fd, uid, gid)
        os.fchmod(fd, 0o700)
    finally:
        os.close(fd)

def safe_source(path, base):
    """root가 복사할 원본은 base 아래 폴더여야 하고, base부터 path까지 어느 단계도 심볼릭 링크가 아니어야 한다."""
    try:
        parts = path.relative_to(base).parts
    except ValueError:
        raise RuntimeError('복사 원본이 ' + str(base) + ' 밖에 있어 설치를 중단했습니다: ' + str(path)) from None
    current = base
    for part in parts:
        current = current / part
        if current.is_symlink():
            raise RuntimeError('복사 원본 경로에 심볼릭 링크가 있어 설치를 중단했습니다: ' + str(current))
    if not path.is_dir():
        raise RuntimeError('복사 원본 폴더가 없습니다: ' + str(path))
    return path

def regular_file(path):
    if not path.is_symlink() and path.exists() and stat.S_ISREG(os.lstat(path).st_mode):
        return path
    raise RuntimeError('실행 파일이 일반 파일이 아니어서 설치를 중단했습니다: ' + str(path))

def install_browser_files(npm_account, browser_gid):
    stage = NPM_HOME / 'stage'
    # 이전 실행에서 남은 npm 계정 프로세스를 먼저 끝내고, stage는 매번 root가 새로 만든다(링크를 따라가지 않음).
    stop_processes(NPM_USER)
    fresh_directory(stage, npm_account.pw_uid, npm_account.pw_gid)
    files = npm_files()
    for name in ('package.json', 'package-lock.json'):
        if name in files:
            atomic(stage / name, files[name], npm_account.pw_uid, npm_account.pw_gid, 0o644)
    for command in download_commands(stage, 'package-lock.json' in files):
        run(command, cwd=stage)
    # 복사하는 동안 npm 계정이 파일을 바꾸지 못하게 남은 프로세스를 끝낸 뒤, 원본 경로에 링크가 없는지 확인한다.
    stop_processes(NPM_USER)
    chrome = find_chrome(safe_source(NPM_HOME / '.agent-browser' / 'browsers', NPM_HOME))
    PREFIX.mkdir(parents=True, exist_ok=True)
    os.chown(PREFIX, 0, 0)
    os.chmod(PREFIX, 0o755)
    install_tree(safe_source(stage / 'node_modules', NPM_HOME), PREFIX / 'node_modules')
    os.chmod(regular_file(PREFIX / 'node_modules/agent-browser/bin/agent-browser-linux-x64'), 0o755)
    # Chromium은 브라우저 계정만 실행한다. AppArmor userns 예외를 다른 계정이 이 실행 파일로 얻지 못하게 한다.
    install_tree(safe_source(chrome.parent, NPM_HOME), CHROME.parent, top=(browser_gid, 0o750))
    regular_file(CHROME)

def apply_apparmor():
    """프로필을 적용하고 실패 이유를 돌려준다(성공이면 None)."""
    try:
        atomic(APPARMOR_PROFILE, apparmor_profile(CHROME), mode=0o644)
        result = subprocess.run(['apparmor_parser', '-r', '-W', str(APPARMOR_PROFILE)], capture_output=True, text=True, timeout=60)
    except (OSError, subprocess.SubprocessError) as exc:
        return type(exc).__name__
    if result.returncode != 0:
        return (result.stderr.strip() or 'apparmor_parser exit ' + str(result.returncode))[:300]
    loaded = Path('/sys/kernel/security/apparmor/profiles')
    if 'collective-chromium' not in (loaded.read_text() if loaded.exists() else ''):
        return 'collective-chromium profile is not loaded'
    return None

def dump_dom(url, profile, no_sandbox):
    shutil.rmtree(profile, ignore_errors=True)
    command = as_user(BROWSER_USER, BROWSER_HOME, [CHROME] + chrome_flags(no_sandbox) + ['--user-data-dir=' + str(profile), '--dump-dom', url])
    try:
        return subprocess.run(command, capture_output=True, text=True, timeout=60).stdout
    except subprocess.TimeoutExpired:
        return ''

def probe_chrome(no_sandbox, allow_no_sandbox):
    # 양성: 샌드박스를 켠 채 data: 페이지를 읽는다. 음성: 브라우저 계정이 읽을 수 있는 file:// 페이지도 정책으로 막힌다.
    # 점검 페이지는 root 소유 폴더에 둔다(0755·0644). 브라우저 계정이 쓸 수 있는 폴더에 root가 파일을 쓰지 않는다.
    token = os.urandom(8).hex()
    marker, profile, page = '<p>' + token + '</p>', BROWSER_HOME / 'install-probe', PREFIX / 'policy-check' / 'policy-check.html'
    try:
        page.parent.mkdir(parents=True, exist_ok=True)
        os.chmod(page.parent, 0o755)
        atomic(page, marker, mode=0o644)
        started = marker in dump_dom('data:text/html,' + marker, profile, no_sandbox)
        if not started and not no_sandbox:
            if not allow_no_sandbox:
                raise IsolationError('샌드박스를 켠 채로 Chromium을 시작하지 못해 설치를 중단했습니다. AppArmor 프로필(' + str(APPARMOR_PROFILE) +
                                   ')과 journalctl -k를 확인하세요. 예외가 꼭 필요하면 --allow-no-sandbox로 다시 실행하세요. HERMES 설정은 바뀌지 않았습니다.')
            print('경고: 샌드박스로 시작하지 못해 --allow-no-sandbox에 따라 샌드박스 없이 실행합니다.', flush=True)
            no_sandbox = True
            started = marker in dump_dom('data:text/html,' + marker, profile, no_sandbox)
        if not started:
            raise RuntimeError('격리 브라우저 계정으로 Chromium을 시작하지 못했습니다. HERMES 설정은 바뀌지 않았습니다.')
        file_output = dump_dom(page.as_uri(), profile, no_sandbox)
        problem = policy_problem(marker, file_output, dump_dom('data:text/html,' + marker, profile, no_sandbox))
        if problem:
            raise IsolationError(problem)
        print('격리 확인: 브라우저 계정의 file:// 열기 거부됨(Chrome 정책, 직후 data: 재확인 통과)', flush=True)
    finally:
        page.unlink(missing_ok=True)
        shutil.rmtree(profile, ignore_errors=True)
    return no_sandbox

def cdp_json(path):
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
    with opener.open(CDP_URL + path, timeout=2) as response:
        return json.loads(response.read(1048576))

def cdp_websocket(attempts=30):
    # root 쪽 양성 대조군: 격리 브라우저가 CDP 포트를 열었는지 확인하고 HERMES가 쓰는 것과 같은 WebSocket 주소를 얻는다.
    for _ in range(attempts):
        try:
            url = cdp_json('/json/version')['webSocketDebuggerUrl']
        except (OSError, ValueError, KeyError, TypeError):
            time.sleep(1)
            continue
        if not loopback_websocket(url):
            raise IsolationError('CDP 포트가 루프백 격리 브라우저 주소가 아닌 곳을 알려 줘 설치를 중단했습니다.')
        return url
    raise RuntimeError('격리 브라우저가 CDP 포트를 열지 않았습니다. journalctl -u ' + BROWSER_SERVICE + ' -n 30 --no-pager로 확인하세요.')

def check_cdp_owner(browser):
    # 포트 선점 확인: 9333을 LISTEN 중인 소켓은 모두 브라우저 계정 소유여야 한다.
    tables = ''.join(p.read_text() for p in (Path('/proc/net/tcp'), Path('/proc/net/tcp6')) if p.exists())
    owners = listener_uids(tables, CDP_PORT)
    if owners != {browser.pw_uid}:
        raise IsolationError('CDP 포트를 브라우저 계정이 아닌 계정이 열고 있어 설치를 중단했습니다(UID ' + ', '.join(map(str, sorted(owners))) + ').')

def host_addresses():
    found = []
    for target in ROUTE_PROBES:
        result = subprocess.run(['ip', '-o', 'route', 'get', target], capture_output=True, text=True)
        address = route_source(result.stdout) if result.returncode == 0 else None
        if address and address not in found:
            found.append(address)
    if not found:
        raise RuntimeError('서버 기본 주소를 찾지 못해 자기 주소 차단을 점검할 수 없습니다(ip route get).')
    return found

def check_host_addresses_denied():
    # 서버 자신의 주소(공인 IP 등)에 root가 연 임시 포트: root는 붙고(양성 대조군) 브라우저 계정은 실패해야 한다.
    for address in host_addresses():
        family = socket.AF_INET6 if ':' in address else socket.AF_INET
        with socket.create_server(('::' if family == socket.AF_INET6 else '', 0), family=family) as listener:
            port = listener.getsockname()[1]
            try:
                socket.create_connection((address, port), 5).close()
            except OSError as exc:
                raise RuntimeError('root가 서버 자신의 주소(' + address + ')에 접속하지 못해 차단 점검을 할 수 없습니다: ' + type(exc).__name__) from None
            expect_denied(*host_denial(address, port))

def start_firewall(browser, hermes):
    resolv = Path('/etc/resolv.conf')
    rules = nft_rules(browser.pw_uid, dns_exceptions(resolv.read_text() if resolv.exists() else ''), (0, hermes.pw_uid))
    atomic(NFT_RULES, rules, mode=0o644)
    check = subprocess.run(['nft', '-c', '-f', str(NFT_RULES)], capture_output=True, text=True)
    if check.returncode != 0:
        raise RuntimeError('nftables 규칙을 적용할 수 없어 설치를 중단했습니다: ' + check.stderr.strip()[:300])
    atomic(Path('/etc/systemd/system') / FIREWALL_SERVICE, firewall_unit(), mode=0o644)
    run(['systemctl', 'daemon-reload'])
    run(['systemctl', 'enable', FIREWALL_SERVICE])
    run(['systemctl', 'restart', FIREWALL_SERVICE])

def start_isolated_browser(browser, hermes, allow_no_sandbox):
    for directory in POLICY_DIRS:
        atomic(directory / 'collective-browser.json', chrome_policy(), mode=0o644)
    start_firewall(browser, hermes)
    userns = Path('/proc/sys/kernel/apparmor_restrict_unprivileged_userns')
    restricted = userns.exists() and userns.read_text().strip() == '1'
    try:
        no_sandbox = sandbox_decision(restricted, apply_apparmor() if restricted else None, allow_no_sandbox)
    except RuntimeError as exc:
        raise IsolationError(str(exc)) from None
    no_sandbox = probe_chrome(no_sandbox, allow_no_sandbox)
    atomic(Path('/etc/systemd/system') / BROWSER_SERVICE, browser_unit(CHROME, no_sandbox), mode=0o644)
    run(['systemctl', 'daemon-reload'])
    run(['systemctl', 'enable', BROWSER_SERVICE])
    run(['systemctl', 'restart', BROWSER_SERVICE])
    cdp_websocket()
    check_cdp_owner(browser)
    run(as_user(BROWSER_USER, BROWSER_HOME, ['true']))
    expect_denied(*network_denial())
    expect_denied(*cdp_client_denial(), who='다른 로컬 계정')
    check_host_addresses_denied()
    return no_sandbox

def check_real_browser(user_command):
    smoke = smoke_command(user_command, cdp_websocket())
    try:
        run(smoke + ['open', 'https://example.com'], timeout=120, stdout=subprocess.DEVNULL)
        title = subprocess.check_output(smoke + ['get', 'title'], text=True, timeout=30).strip()
        if 'Example Domain' not in title:
            raise RuntimeError('Server browser page title check failed.')
        # 양성 대조: 방금 연 페이지가 root가 읽는 격리 브라우저의 CDP 대상 목록에 있어야 HERMES 경로가 그 브라우저에 붙은 것이다.
        if not has_page(cdp_json('/json/list'), 'https://example.com'):
            raise RuntimeError('agent-browser가 격리 브라우저에 페이지를 열지 않았습니다(CDP 대상 목록에 없음). 설치를 중단합니다.')
    finally:
        subprocess.run(smoke + ['close'], timeout=30, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    # --cdp 모드의 close는 격리 브라우저를 닫을 수 있다. 서비스가 다시 뜰 때까지 기다린 뒤 다음 단계로 간다.
    cdp_websocket()
    print('Real browser check passed: Example Domain', flush=True)

def check_file_isolation(worker_config_path, hermes_root, hermes_home):
    run(as_user(BROWSER_USER, BROWSER_HOME, ['true']))
    for label, path, command in file_denials(worker_config_path, hermes_root):
        if not path.exists():
            raise RuntimeError('격리 점검 대상이 없습니다: ' + label)
        expect_denied(label, command)
    run(worker_readable(worker_config_path))
    expect_denied(*worker_denial(worker_config_path, hermes_home), who='hermes 계정')

def check_raw_tool_hook(user_command, home, root):
    # 게이트웨이를 다시 띄운 뒤 hermes 계정으로 훅이 승인됐는지, browser_cdp는 막고 일반 도구는 두는지 확인한다.
    hermes = user_command + ['PATH=' + str(root / 'hermes-agent' / 'venv' / 'bin') + ':' + hermes_path(home),
                             'PYTHONIOENCODING=utf-8', 'hermes', 'hooks']
    def output(args):
        result = subprocess.run(hermes + args, capture_output=True, text=True, encoding='utf-8', errors='replace', timeout=60)
        if result.returncode != 0:
            raise RuntimeError('hermes hooks ' + args[0] + ' 실행에 실패했습니다(exit ' + str(result.returncode) + '). 원시 브라우저 도구 차단을 확인하지 못해 HERMES 설정을 되돌립니다.')
        return result.stdout
    problem = hook_check_problem(str(HOOK_SCRIPT), output(['list']), output(['test', HOOK_EVENT, '--for-tool', 'browser_cdp']),
                                 output(['test', HOOK_EVENT, '--for-tool', 'browser_navigate']))
    if problem:
        raise RuntimeError(problem + '. 원시 브라우저 도구를 막지 못해 HERMES 설정을 되돌립니다.')
    print('격리 확인: HERMES가 browser_cdp·browser_dialog 호출을 막음(pre_tool_call 훅, fail_closed)', flush=True)

def backup_hermes(account, config_path, dropin, dotenv, suffix):
    backup = config_path.with_name('config.yaml.before-collective-server-'+suffix)
    shutil.copy2(config_path, backup)
    os.chown(backup, account.pw_uid, account.pw_gid)
    previous_dropin = dropin.read_bytes() if dropin.exists() else None
    if previous_dropin is not None:
        atomic(dropin.with_name(dropin.name+'.before-'+suffix), previous_dropin)
    previous_dotenv = dotenv.read_bytes() if dotenv.exists() else None
    if previous_dotenv is not None:
        atomic(dotenv.with_name('.env.before-collective-server-'+suffix), previous_dotenv, account.pw_uid, account.pw_gid)
    return backup, previous_dropin, previous_dotenv

def install_worker(worker, worker_config, worker_source, worker_config_path):
    worker_path = Path('/opt/collective-research/worker.py')
    unit = Path('/etc/systemd/system') / SERVICE
    atomic(worker_path, worker_source, mode=0o644)
    worker_config_path.parent.mkdir(parents=True, exist_ok=True)
    os.chown(worker_config_path.parent, worker.pw_uid, worker.pw_gid)
    os.chmod(worker_config_path.parent, 0o700)
    atomic(worker_config_path, json.dumps(worker_config), worker.pw_uid, worker.pw_gid)
    atomic(unit, worker_unit(), mode=0o644)
    run(['systemctl', 'daemon-reload'])
    run(['loginctl', 'enable-linger', 'hermes'])
    run(['systemctl', 'enable', '--now', SERVICE])
    run(['systemctl', 'is-active', '--quiet', SERVICE])
    run(['systemctl', 'daemon-reload'])
    run(['loginctl', 'enable-linger', 'hermes'])
    run(['systemctl', 'enable', '--now', SERVICE])
    run(['systemctl', 'is-active', '--quiet', SERVICE])

def configure_hermes(account, worker, config_path, config, user_command, worker_config, worker_source):
    import yaml
    home, root = Path(account.pw_dir), config_path.parent
    userctl = user_command + ['systemctl', '--user']
    suffix = datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S-%f')
    dropin = home / '.config/systemd/user/hermes-gateway.service.d/collective-browser.conf'
    dotenv = root / '.env'
    allowlist = root / 'shell-hooks-allowlist.json'
    backup, previous_dropin, previous_dotenv = backup_hermes(account, config_path, dropin, dotenv, suffix)
    previous_allowlist = allowlist.read_bytes() if allowlist.exists() else None
    worker_config_path = Path('/etc/collective-research/worker.json')
    print('5/6 HERMES API를 격리 브라우저에 연결하고 원시 브라우저 도구를 막습니다...', flush=True)
    atomic(HOOK_SCRIPT, hook_script(), mode=0o755)
    config.setdefault('platform_toolsets', {})['api_server'] = ['browser', 'web', 'no_mcp']
    config['hooks'] = hermes_hooks(config.get('hooks'))
    browser = config.setdefault('browser', {})
    browser.update(cloud_provider='local', backend='off', engine='chrome', headed=False, use_real_profile=False,
                   inactivity_timeout=300, command_timeout=90, cdp_url=CDP_URL)
    browser.pop('cdp_urls', None)
    browser_dotenv = (previous_dotenv or b'') + hermes_env_block(suffix).encode()
    old_worker = subprocess.run(['systemctl', 'is-active', '--quiet', SERVICE]).returncode == 0
    if old_worker:
        run(['systemctl', 'stop', SERVICE])
    try:
        approved_at = datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z')
        atomic(allowlist, hook_allowlist(previous_allowlist, approved_at), account.pw_uid, account.pw_gid)
        atomic(config_path, yaml.safe_dump(config, allow_unicode=True, sort_keys=False), account.pw_uid, account.pw_gid)
        atomic(dotenv, browser_dotenv, account.pw_uid, account.pw_gid)
        atomic(dropin, hermes_dropin(home), account.pw_uid, account.pw_gid, 0o644)
        os.chown(dropin.parent, account.pw_uid, account.pw_gid, follow_symlinks=False)
        run(userctl + ['daemon-reload'])
        run(userctl + ['restart', 'hermes-gateway.service'])
        run(userctl + ['is-active', '--quiet', 'hermes-gateway.service'])
        check_raw_tool_hook(user_command, home, root)
        install_worker(worker, worker_config, worker_source, worker_config_path)
        print('6/6 브라우저·hermes 계정이 비밀 파일을 읽지 못하는지 확인합니다...', flush=True)
        check_file_isolation(worker_config_path, root, home)
    except Exception as exc:
        # 새 worker.json·유닛으로 재부팅 때 다시 뜨지 않게 작업자 서비스를 끄고 비활성화한다.
        subprocess.run(['systemctl', 'disable', '--now', SERVICE], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        if previous_allowlist is None:
            allowlist.unlink(missing_ok=True)
        else:
            atomic(allowlist, previous_allowlist, account.pw_uid, account.pw_gid)
        atomic(config_path, backup.read_bytes(), account.pw_uid, account.pw_gid)
        if previous_dotenv is None:
            dotenv.unlink(missing_ok=True)
        else:
            atomic(dotenv, previous_dotenv, account.pw_uid, account.pw_gid)
        if previous_dropin is None:
            dropin.unlink(missing_ok=True)
        else:
            atomic(dropin, previous_dropin, account.pw_uid, account.pw_gid, 0o644)
        subprocess.run(userctl + ['daemon-reload'])
        subprocess.run(userctl + ['restart', 'hermes-gateway.service'])
        reason = (' ' + str(exc)) if isinstance(exc, RuntimeError) else ''
        error = IsolationError if isinstance(exc, IsolationError) else RuntimeError
        raise error('Setup failed; HERMES config restored. Reissue installer and retry.' + reason) from None
    return backup

def main(options=None):
    options = options or {'allow_no_sandbox': False}
    if os.geteuid() != 0 or platform.system() != 'Linux' or platform.machine() != 'x86_64':
        raise RuntimeError('Run with root on the existing Ubuntu x86_64 HERMES server.')
    if not Path('/etc/os-release').exists() or 'Ubuntu' not in Path('/etc/os-release').read_text():
        raise RuntimeError('This installer supports Ubuntu only.')
    import yaml
    account = pwd.getpwnam('hermes')
    home = Path(account.pw_dir)
    root = home / '.hermes'
    config_path = root / 'config.yaml'
    config = yaml.safe_load(config_path.read_text()) or {}
    source = root / 'hermes-agent' / 'tools'
    browser_sources = '\n'.join(p.read_text(errors='replace') for p in source.glob('browser_tool*.py'))
    if not all(key in browser_sources for key in ('cloud_provider', 'cdp_url', 'BROWSER_CDP_URL')):
        raise RuntimeError('Installed HERMES browser support needs review. Existing config was not changed.')
    # CDP로 연결하면 browser_cdp·browser_dialog가 켜진다. 막을 훅을 지원하지 않는 HERMES면 설정을 바꾸기 전에 멈춘다.
    read = lambda p: p.read_text(errors='replace') if p.exists() else ''
    missing = hook_support_missing(read(root / 'hermes-agent' / 'agent' / 'shell_hooks.py'),
                                   read(root / 'hermes-agent' / 'gateway' / 'run.py'))
    if missing:
        raise RuntimeError('설치된 HERMES에서 pre_tool_call 셸 훅(fail_closed) 지원을 확인하지 못했습니다(' + ', '.join(missing) +
                           '). 원시 브라우저 도구를 막을 수 없어 설정을 바꾸지 않고 멈춥니다.')
    worker_config = json.loads(bytes.fromhex(CONFIG_HEX))
    worker_source = bytes.fromhex(WORKER_HEX)
    if not worker_config['site'].startswith('https://'):
        raise RuntimeError('Invalid Site address.')
    user_command = ['runuser', '-u', 'hermes', '--', 'env', 'HOME='+str(home),
                    'XDG_RUNTIME_DIR=/run/user/'+str(account.pw_uid)]
    userctl = user_command + ['systemctl', '--user']
    run(userctl + ['is-active', '--quiet', 'hermes-gateway.service'])
    print('root로 실행하는 단계:', ', '.join(ROOT_STEPS), flush=True)
    print('1/6 서버 패키지를 설치합니다(apt, root)...', flush=True)
    install_packages()
    print('2/6 전용 계정을 만들고 agent-browser·Chromium을 비특권 계정으로 받습니다...', flush=True)
    browser = ensure_account(BROWSER_USER, BROWSER_HOME, account)
    worker = ensure_account(WORKER_USER, WORKER_HOME, account)
    install_browser_files(ensure_account(NPM_USER, NPM_HOME, account), browser.pw_gid)
    without_other_access(root)
    browser_was_active = subprocess.run(['systemctl', 'is-active', '--quiet', BROWSER_SERVICE]).returncode == 0
    print('3/6 격리 브라우저(샌드박스·방화벽·Chrome 정책)를 시작하고 점검합니다...', flush=True)
    try:
        no_sandbox = start_isolated_browser(browser, account, options['allow_no_sandbox'])
        print('4/6 Checking real browser access...', flush=True)
        check_real_browser(user_command)
        backup = configure_hermes(account, worker, config_path, config, user_command, worker_config, worker_source)
    except Exception as exc:
        # 격리 점검을 통과하지 못한 브라우저는 열어 두지 않는다(fail-closed). 기능 점검·설정 실패면 설치 전 상태로 둔다.
        if keep_browser(exc, browser_was_active):
            print('격리 점검 실패가 아니므로 브라우저 서비스는 설치 전처럼 켜 둡니다: ' + BROWSER_SERVICE, file=sys.stderr, flush=True)
        else:
            subprocess.run(['systemctl', 'disable', '--now', BROWSER_SERVICE], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            print('브라우저 서비스를 끄고 비활성화했습니다: ' + BROWSER_SERVICE, file=sys.stderr, flush=True)
        raise
    print('Services started. Check COLLECTIVE settings for the worker heartbeat.', flush=True)
    print('Backup:', backup)
    print('브라우저 계정:', BROWSER_USER, '(샌드박스 없음: --allow-no-sandbox 예외)' if no_sandbox else '(Chromium 샌드박스 유지)')
    print('Server browser has its own login state. Mac cookies were not copied.')
    print('Logs: journalctl -u collective-research-worker.service -n 30 --no-pager')

def remove_installer(path, unlink=os.unlink):
    """설치 파일에는 자격증명이 들어 있다. 성공 뒤 서버 사본을 지우고, 지우지 못해도 설치 결과는 그대로 둔다."""
    try:
        unlink(path)
    except OSError as exc:
        print('경고: 설치 파일을 삭제하지 못했습니다(' + type(exc).__name__ + '). 직접 지우세요:', path, file=sys.stderr, flush=True)
        return False
    print('서버의 설치 파일을 삭제했습니다:', path, flush=True)
    return True

def cli(argv, install=main, remove=remove_installer, script=None):
    try:
        install(parse_args(argv))
    except Exception as exc:
        # Only explicit local setup errors; never dump generated credentials.
        print('Installation stopped:', type(exc).__name__, file=sys.stderr)
        if isinstance(exc, RuntimeError):
            print(str(exc), file=sys.stderr)
        return 1
    if script and Path(script).is_file():
        remove(Path(script))
    print('Mac에 받은 사본(~/Downloads/install-collective-server.py)도 지우세요.', flush=True)
    return 0

if __name__ == '__main__':
    sys.exit(cli(sys.argv[1:], script=__file__))
