#!/usr/bin/env python3
"""Generated by COLLECTIVE settings. Contains private worker credentials."""
import json
import os
import platform
import pwd
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

CONFIG_HEX = '__COLLECTIVE_CONFIG_HEX__'
WORKER_HEX = '__COLLECTIVE_WORKER_HEX__'
PREFIX = Path('/opt/collective-browser')
SERVICE = 'collective-research-worker.service'

def run(args, **kwargs):
    return subprocess.run([str(x) for x in args], check=True, **kwargs)

def atomic(path, data, uid=0, gid=0, mode=0o600):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix='.collective-', dir=path.parent)
    try:
        with os.fdopen(fd, 'wb') as stream:
            stream.write(data if isinstance(data, bytes) else data.encode())
            stream.flush()
            os.fsync(stream.fileno())
        os.chown(temporary, uid, gid)
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)

def main():
    if os.geteuid() != 0 or platform.system() != 'Linux' or platform.machine() != 'x86_64':
        raise RuntimeError('Run with root on the existing Ubuntu x86_64 HERMES server.')
    if not Path('/etc/os-release').exists() or 'Ubuntu' not in Path('/etc/os-release').read_text():
        raise RuntimeError('This installer supports Ubuntu only.')
    import yaml
    account = pwd.getpwnam('hermes')
    home = Path(account.pw_dir)
    root = home / '.hermes'
    config_path = root / 'config.yaml'
    config = yaml.safe_load(config_path.read_text()) or {}
    source = root / 'hermes-agent' / 'tools'
    browser_sources = '\n'.join(p.read_text(errors='replace') for p in source.glob('browser_tool*.py'))
    if not all(key in browser_sources for key in ('cloud_provider', 'AGENT_BROWSER_EXECUTABLE_PATH')):
        raise RuntimeError('Installed HERMES browser support needs review. Existing config was not changed.')
    worker_config = json.loads(bytes.fromhex(CONFIG_HEX))
    worker_source = bytes.fromhex(WORKER_HEX)
    if not worker_config['site'].startswith('https://'):
        raise RuntimeError('Invalid Site address.')
    user_command = ['runuser', '-u', 'hermes', '--', 'env', 'HOME='+str(home),
                    'XDG_RUNTIME_DIR=/run/user/'+str(account.pw_uid)]
    userctl = user_command + ['systemctl', '--user']
    run(userctl + ['is-active', '--quiet', 'hermes-gateway.service'])
    # Browser binaries live in a dedicated prefix; the HERMES Python install is untouched.
    print('1/4 Installing server browser dependencies...', flush=True)
    apt_env = dict(os.environ, DEBIAN_FRONTEND='noninteractive')
    run(['apt-get', 'update'], env=apt_env)
    run(['apt-get', 'install', '-y', 'nodejs', 'npm', 'sudo', 'ca-certificates'], env=apt_env)
    node_major = int(subprocess.check_output(['node', '--version'], text=True).strip().lstrip('v').split('.')[0])
    if node_major < 18:
        raise RuntimeError('Node 18 or newer is required; HERMES config is unchanged.')
    run(['npm', 'install', '--prefix', PREFIX, '--no-audit', '--no-fund', 'agent-browser@0.26.0'])
    cli = PREFIX / 'node_modules' / '.bin' / 'agent-browser'
    run([cli, 'install', '--with-deps'], env=apt_env)
    run(user_command + [cli, 'install'])
    browsers = list((home / '.agent-browser' / 'browsers').glob('chrome-*/chrome-linux64/chrome'))
    if not browsers:
        raise RuntimeError('Chromium executable was not found. HERMES config is unchanged.')
    chrome = max(browsers, key=lambda p: p.stat().st_mtime)
    browser_env = ['AGENT_BROWSER_EXECUTABLE_PATH='+str(chrome)]
    userns = Path('/proc/sys/kernel/apparmor_restrict_unprivileged_userns')
    restricted_userns = userns.exists() and userns.read_text().strip() == '1'
    if restricted_userns:
        # Match HERMES Chromium startup handling on Ubuntu 24.04; leave host
        # AppArmor settings intact and keep the browser under the hermes user.
        browser_env.append('AGENT_BROWSER_ARGS=--no-sandbox,--disable-dev-shm-usage')
    smoke = user_command + browser_env + [str(cli), '--session', 'collective_install_check']
    print('2/4 Checking real browser access...', flush=True)
    try:
        run(smoke + ['open', 'https://example.com'], timeout=120, stdout=subprocess.DEVNULL)
        title = subprocess.check_output(smoke + ['get', 'title'], text=True, timeout=30).strip()
        if 'Example Domain' not in title:
            raise RuntimeError('Server browser page title check failed.')
    finally:
        subprocess.run(smoke + ['close'], timeout=30, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    print('Real browser check passed: Example Domain', flush=True)
    suffix = datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S-%f')
    backup = config_path.with_name('config.yaml.before-collective-server-'+suffix)
    shutil.copy2(config_path, backup)
    os.chown(backup, account.pw_uid, account.pw_gid)
    dropin = home / '.config/systemd/user/hermes-gateway.service.d/collective-browser.conf'
    previous_dropin = dropin.read_bytes() if dropin.exists() else None
    if previous_dropin is not None:
        atomic(dropin.with_name(dropin.name+'.before-'+suffix), previous_dropin)
    dotenv = root / '.env'
    previous_dotenv = dotenv.read_bytes() if dotenv.exists() else None
    if previous_dotenv is not None:
        atomic(dotenv.with_name('.env.before-collective-server-'+suffix), previous_dotenv, account.pw_uid, account.pw_gid)
    worker_path = Path('/opt/collective-research/worker.py')
    worker_config_path = Path('/etc/collective-research/worker.json')
    unit = Path('/etc/systemd/system') / SERVICE
    print('3/4 Connecting HERMES API to the server browser...', flush=True)
    config.setdefault('platform_toolsets', {})['api_server'] = ['browser', 'web', 'no_mcp']
    browser = config.setdefault('browser', {})
    browser.update(cloud_provider='local', backend='off', engine='chrome', headed=False, use_real_profile=False,
                   inactivity_timeout=300, command_timeout=90)
    browser.pop('cdp_url', None)
    browser.pop('cdp_urls', None)
    path = str(PREFIX / 'node_modules/.bin')+':'+str(home / '.local/bin')+':/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    override = '[Service]\nEnvironment="PATH='+path+'"\nEnvironment="AGENT_BROWSER_EXECUTABLE_PATH='+str(chrome)+'"\n'
    # Prevent an inherited Mac/remote CDP URL from overriding the explicit local backend.
    override += 'UnsetEnvironment=BROWSER_CDP_URL AGENT_BROWSER_CDP_URL AGENT_BROWSER_HEADED\n'
    # HERMES dotenv loads with override=True after systemd. Explicit empty values
    # also prevent repo .env fallback from restoring a remote browser dependency.
    browser_dotenv = (previous_dotenv or b'') + ('\n# COLLECTIVE server browser '+suffix+'\n'
        'BROWSER_CDP_URL=""\nAGENT_BROWSER_CDP_URL=""\nAGENT_BROWSER_HEADED="0"\n'
        'AGENT_BROWSER_ENGINE="chrome"\nAGENT_BROWSER_EXECUTABLE_PATH='+json.dumps(str(chrome))+'\n').encode()
    if restricted_userns:
        browser_dotenv += b'AGENT_BROWSER_ARGS="--no-sandbox,--disable-dev-shm-usage"\n'
    old_worker = subprocess.run(['systemctl', 'is-active', '--quiet', SERVICE]).returncode == 0
    if old_worker:
        run(['systemctl', 'stop', SERVICE])
    try:
        atomic(config_path, yaml.safe_dump(config, allow_unicode=True, sort_keys=False), account.pw_uid, account.pw_gid)
        atomic(dotenv, browser_dotenv, account.pw_uid, account.pw_gid)
        atomic(dropin, override, account.pw_uid, account.pw_gid, 0o644)
        os.chown(dropin.parent, account.pw_uid, account.pw_gid)
        run(userctl + ['daemon-reload'])
        run(userctl + ['restart', 'hermes-gateway.service'])
        run(userctl + ['is-active', '--quiet', 'hermes-gateway.service'])
        atomic(worker_path, worker_source, mode=0o644)
        worker_config_path.parent.mkdir(parents=True, exist_ok=True)
        os.chown(worker_config_path.parent, account.pw_uid, account.pw_gid)
        os.chmod(worker_config_path.parent, 0o700)
        atomic(worker_config_path, json.dumps(worker_config), account.pw_uid, account.pw_gid)
        atomic(unit, '[Unit]\nDescription=COLLECTIVE durable research queue\nWants=network-online.target\nAfter=network-online.target\n\n[Service]\nType=simple\nUser=hermes\nExecStart=/usr/bin/python3 /opt/collective-research/worker.py /etc/collective-research/worker.json\nRestart=on-failure\nRestartSec=15\nRestartPreventExitStatus=78\nNoNewPrivileges=true\nPrivateTmp=true\nProtectSystem=strict\nProtectHome=true\nUMask=0077\n\n[Install]\nWantedBy=multi-user.target\n', mode=0o644)
        run(['systemctl', 'daemon-reload'])
        run(['loginctl', 'enable-linger', 'hermes'])
        run(['systemctl', 'enable', '--now', SERVICE])
        run(['systemctl', 'is-active', '--quiet', SERVICE])
    except Exception:
        subprocess.run(['systemctl', 'stop', SERVICE], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        atomic(config_path, backup.read_bytes(), account.pw_uid, account.pw_gid)
        if previous_dotenv is None:
            dotenv.unlink(missing_ok=True)
        else:
            atomic(dotenv, previous_dotenv, account.pw_uid, account.pw_gid)
        if previous_dropin is None:
            dropin.unlink(missing_ok=True)
        else:
            atomic(dropin, previous_dropin, account.pw_uid, account.pw_gid, 0o644)
        subprocess.run(userctl + ['daemon-reload'])
        subprocess.run(userctl + ['restart', 'hermes-gateway.service'])
        raise RuntimeError('Setup failed; HERMES config restored. Reissue installer and retry.') from None
    print('4/4 Services started. Check COLLECTIVE settings for the worker heartbeat.', flush=True)
    print('Backup:', backup)
    print('Server browser has its own login state. Mac cookies were not copied.')
    print('Logs: journalctl -u collective-research-worker.service -n 30 --no-pager')
    print('This installer contains credentials. Remove the downloaded and server copies after verification.')

if __name__ == '__main__':
    try:
        main()
    except Exception as exc:
        # Only explicit local setup errors; never dump generated credentials.
        print('Installation stopped:', type(exc).__name__, file=sys.stderr)
        if isinstance(exc, RuntimeError):
            print(str(exc), file=sys.stderr)
        sys.exit(1)
