import type {Campaign} from '@/lib/agency';
import {metaReadiness} from '@/lib/meta-ads';
import {metaCreativeContext,viewMetaCreative} from '@/lib/meta-creative-server';
import {isEnabled} from '@/lib/feature-flags';
import {readMetaConnection} from '@/lib/meta-read-connection';
import {assertMetaWriteConnectionChange,metaWriteConnectionId,metaWriteToken,prepareMetaWriteConnection,publicMetaWriteConnection,readMetaWriteConnection,type MetaWriteConnection} from '@/lib/meta-write-connection';
import {MetaInsightError,metaId} from '@/lib/meta-insights';
import {MetaReadError} from '@/lib/meta-insights-provider';
import {createPausedMetaCampaign,verifyPausedMetaCampaign,MetaPausedError} from '@/lib/meta-paused-campaign';
import {pausedCampaignJournal,preparePausedCampaignOperation,type PausedCampaignOperation} from '@/lib/meta-paused-journal';
import {storefrontDigest} from '@/lib/storefront-orders';
import {ApiError,acquireLock,actor,body,database,failure,json,listRecords,readRecord,recordStatement,releaseLock,requireOwnerActor,secureMutation,str} from '@/lib/server';
async function context(owner:string,c:Campaign){const [enabled,connection,reading,x,operations]=await Promise.all([isEnabled(owner,'meta_ads_paused_write'),readMetaWriteConnection(owner,c.brandId),readMetaConnection(owner,c.brandId),metaCreativeContext(owner,c),listRecords<PausedCampaignOperation>(owner,'meta_ads_write_operation',c.id)]);const review=viewMetaCreative(c,x,false),issues=[...metaReadiness(x.plan,c.version).missing];if(!review.reviewValid)issues.push('현재 근거·소재·실험의 검토 기록');if(x.plan?.input.goal!=='purchase')issues.push('판매 목적의 준비 계획');if(!reading)issues.push('브랜드 광고 계정 읽기 연결');if(!connection)issues.push('별도 쓰기 권한 연결');if(connection&&reading?.accountId!==connection.accountId)issues.push('읽기·쓰기 광고 계정 일치');if(!enabled)issues.push('비활성 초안 생성 기능 켜기');if(operations.some(o=>['sending','unknown'].includes(o.receipt.state)))issues.push('이전 생성 작업의 외부 결과 대조');if(operations.some(o=>o.receipt.state==='paused_verified'))issues.push('이미 연결된 비활성 Meta 캠페인 있음');if(c.status==='archived')issues.push('보관되지 않은 캠페인');const evidenceFingerprint=await storefrontDigest({campaignVersion:c.version,plan:x.plan,review:review.saved,connectionVersion:connection?.version??0,accountId:connection?.accountId??null});return {enabled,connection,issues:[...new Set(issues)],evidenceFingerprint,operations}}
function view(c:Campaign,x:Awaited<ReturnType<typeof context>>,canEdit:boolean){return {campaignVersion:c.version,enabled:x.enabled,connection:publicMetaWriteConnection(x.connection),issues:x.issues,evidenceFingerprint:x.evidenceFingerprint,operations:x.operations.map(o=>({id:o.id,name:o.draft.name,accountId:o.draft.accountId,receipt:o.receipt,createdAt:o.createdAt,version:o.version,stale:o.evidenceFingerprint!==x.evidenceFingerprint||o.campaignVersion!==c.version})),canEdit,canActivate:false}}
export async function GET(req:Request){try{const who=await actor(req),c=await readRecord<Campaign>(who.owner,'campaign',str(new URL(req.url).searchParams.get('campaignId'),'캠페인',100,true));return json(view(c,await context(who.owner,c),who.role==='owner'))}catch(e){return failure(e)}}
export async function POST(req:Request){let owner='',lock='';try{const who=await requireOwnerActor(req);secureMutation(req);const b=await body(req);if(!['connect','disconnect','prepare','create','reconcile'].includes(String(b.action)))throw new ApiError(400,'지원하지 않는 비활성 초안 작업입니다.');owner=who.owner;lock=await acquireLock(owner);const c=await readRecord<Campaign>(owner,'campaign',str(b.campaignId,'캠페인',100,true)),x=await context(owner,c);
 if(b.action==='connect'||b.action==='disconnect'){
  if(b.connectionVersion!==(x.connection?.version??0))throw new ApiError(409,'연결이 변경되었습니다. 다시 조회하세요.');
  if(b.action==='disconnect'){await assertMetaWriteConnectionChange(owner,c.brandId,null);await database().prepare("DELETE FROM records WHERE owner=? AND kind='channel_credential' AND id=?").bind(owner,`${owner}:channel_credential:${metaWriteConnectionId(c.brandId)}`).run();return json(view(c,await context(owner,c),true))}
  const accountId=metaId(b.accountId,'광고 계정'),sameAccount=x.connection?.accountId===accountId;await assertMetaWriteConnectionChange(owner,c.brandId,accountId);if(b.allowPausedCreation!==true||!sameAccount&&(!x.enabled||c.status==='archived'))throw new ApiError(409,'비활성 초안 생성 기능과 별도 쓰기 연결 동의를 확인하세요.');if((await listRecords<MetaWriteConnection>(owner,'channel_credential')).some(v=>v.channel==='meta_ads_write'&&v.accountId===accountId&&v.brandId!==c.brandId))throw new ApiError(409,'다른 브랜드의 쓰기 연결 계정입니다.');
  const saved=await prepareMetaWriteConnection(owner,c.brandId,accountId,b.token,(x.connection?.version??0)+1);await recordStatement(owner,'channel_credential',metaWriteConnectionId(c.brandId),saved).run();return json(view(c,await context(owner,c),true));
 }
 if(b.action==='reconcile'){
  const op=await readRecord<PausedCampaignOperation>(owner,'meta_ads_write_operation',str(b.operationId,'작업',100,true));if(op.campaignId!==c.id||op.brandId!==c.brandId)throw new ApiError(404,'이 캠페인의 작업이 아닙니다.');if(!x.connection||op.draft.accountId!==x.connection.accountId)throw new ApiError(409,'같은 광고 계정의 쓰기 연결을 확인하세요.');if(!['sending','unknown','paused_verified'].includes(op.receipt.state))throw new ApiError(409,'결과 확인이 필요한 작업만 조회하세요.');
  const receipt={...op.receipt,externalId:op.receipt.externalId??metaId(b.externalId,'직접 확인한 외부 캠페인')};if(b.confirmed!==true)throw new ApiError(400,'외부 캠페인의 비활성 상태를 조회할지 확인하세요.');const result=await verifyPausedMetaCampaign(await metaWriteToken(owner,x.connection),receipt,true);await pausedCampaignJournal(owner,op.id,who.id).finish(result);return json(view(c,await context(owner,c),true));
 }
 if(b.campaignVersion!==c.version||b.evidenceFingerprint!==x.evidenceFingerprint||x.issues.length)throw new ApiError(409,'현재 준비 계획·검수·연결을 다시 확인하세요. '+x.issues.join(', '));
 if(b.action==='prepare'){
  if(b.specialCategoryReview!=='not_applicable')throw new ApiError(400,'특별 광고 범주 비해당을 먼저 검토하세요.');await preparePausedCampaignOperation(owner,{campaignId:c.id,campaignVersion:c.version,evidenceFingerprint:x.evidenceFingerprint,accountId:x.connection!.accountId,name:str(b.name,'캠페인 이름',120,true),specialCategoryReview:'not_applicable',createdBy:who.id});return json(view(c,await context(owner,c),true));
 }
 const op=await readRecord<PausedCampaignOperation>(owner,'meta_ads_write_operation',str(b.operationId,'작업',100,true));if(op.campaignId!==c.id||op.brandId!==c.brandId||op.draft.accountId!==x.connection!.accountId||op.evidenceFingerprint!==x.evidenceFingerprint)throw new ApiError(409,'준비 후 근거·계정이 변경되었습니다. 새로 검토하세요.');if(b.confirmed!==true)throw new ApiError(400,'Meta에 비활성 캠페인을 실제 생성할지 확인하세요.');
 await createPausedMetaCampaign(await metaWriteToken(owner,x.connection!),op.draft,op.receipt,pausedCampaignJournal(owner,op.id,who.id),x.enabled);return json(view(c,await context(owner,c),true));
 }catch(e){return failure(e instanceof MetaPausedError?new ApiError(e.code==='unknown'?502:409,e.message):e instanceof MetaReadError?new ApiError(502,e.message):e instanceof MetaInsightError?new ApiError(400,e.message):e)}finally{if(lock)await releaseLock(owner,lock)}}
