import type {Campaign} from '@/lib/agency';
import {metaPerformanceReport,reportDifference,type MetaPerformanceSnapshot} from '@/lib/meta-performance-report';
import {MetaInsightError} from '@/lib/meta-insights';
import {ApiError,acquireLock,actor,body,database,failure,json,readRecord,recordStatement,releaseLock,requireAdminActor,secureMutation,stamp,str} from '@/lib/server';
async function history(owner:string,id:string){const rows=await database().prepare("SELECT data FROM records WHERE owner=? AND kind='meta_ads_report' AND parent_id=? ORDER BY CAST(json_extract(data,'$.version') AS INTEGER) DESC LIMIT 20").bind(owner,id).all<{data:string}>();return rows.results.map(r=>JSON.parse(r.data) as MetaPerformanceSnapshot)}
async function view(owner:string,c:Campaign,input:{since?:unknown;until?:unknown},canEdit:boolean){const [report,snapshots]=await Promise.all([metaPerformanceReport(owner,c,input),history(owner,c.id)]);const previous=snapshots.find(s=>s.report.period.since===report.period.since&&s.report.period.until===report.period.until);return {report,snapshots,version:snapshots[0]?.version??0,canEdit,changed:previous?previous.digest!==report.basisDigest:null,difference:previous?reportDifference(previous.report,report):null}}
export async function GET(req:Request){try{const who=await actor(req),p=new URL(req.url).searchParams,c=await readRecord<Campaign>(who.owner,'campaign',str(p.get('campaignId'),'캠페인',100,true));return json(await view(who.owner,c,{since:p.get('since')??undefined,until:p.get('until')??undefined},who.role!=='member'))}catch(e){return failure(e instanceof MetaInsightError?new ApiError(400,e.message):e)}}
export async function POST(req:Request){let owner='',lock='';try{const who=await requireAdminActor(req);secureMutation(req);const b=await body(req);if(b.action!=='freeze'||b.confirmed!==true)throw new ApiError(400,'집계 기준과 한계를 확인한 뒤 보고를 기록하세요.');owner=who.owner;lock=await acquireLock(owner);const c=await readRecord<Campaign>(owner,'campaign',str(b.campaignId,'캠페인',100,true));if(c.status==='archived')throw new ApiError(409,'보관된 캠페인입니다.');const current=await view(owner,c,{since:b.since,until:b.until},true);if(b.expectedVersion!==current.version||b.expectedDigest!==current.report.basisDigest)throw new ApiError(409,'주문·성과·보고 기록이 바뀌었습니다. 새 집계를 확인하세요.');
 const same=current.snapshots.find(s=>s.digest===current.report.basisDigest);if(same)return json({...current,duplicate:true});
 const version=current.version+1,snapshot:MetaPerformanceSnapshot={id:c.id+':'+version,campaignId:c.id,version,capturedAt:stamp(),capturedBy:who.id,digest:current.report.basisDigest,report:current.report};await recordStatement(owner,'meta_ads_report',snapshot.id,snapshot,c.id).run();return json({...current,version,snapshots:[snapshot,...current.snapshots].slice(0,20),changed:false,difference:reportDifference(snapshot.report,current.report),duplicate:false});
 }catch(e){return failure(e instanceof MetaInsightError?new ApiError(400,e.message):e)}finally{if(lock)await releaseLock(owner,lock)}}
