import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { SourceTextModule, SyntheticModule, createContext } from 'node:vm';
import { readFileSync, readdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { webcrypto } from 'node:crypto';
import ts from 'typescript';
const sql=new DatabaseSync(':memory:');
for(const file of readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+file,'utf8'));
class Statement{constructor(query,values=[]){this.query=query;this.values=values}bind(...v){return new Statement(this.query,v)}async first(){return sql.prepare(this.query).get(...this.values)||null}async all(){return {results:sql.prepare(this.query).all(...this.values)}}async run(){const r=sql.prepare(this.query).run(...this.values);return {meta:{changes:Number(r.changes)}}}}
const DB={prepare:q=>new Statement(q),batch:async ss=>{sql.exec('BEGIN');try{const r=[];for(const s of ss)r.push(await s.run());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
const runtime={DB,AUTH_MODE:'legacy',AGENCY_ENCRYPTION_KEY:Buffer.alloc(32,7).toString('base64')};
let callCount=0,providerFail=false;const provider=new Map();
const fakeFetch=async(url,options={})=>{if(url.includes('/models/'))return Response.json({id:'test-model'});if(options.method==='POST'&&url.endsWith('/responses')){callCount++;if(providerFail)throw new Error('network lost');const b=JSON.parse(options.body),id='resp_test'+callCount;provider.set(id,{id,status:'completed',metadata:b.metadata,output:[{content:[{type:'output_text',text:'## Verified test output\nThis is a mock provider response.'}]}],usage:{total_tokens:42}});return Response.json({id,status:'completed'})}const id=url.split('/').pop();if(provider.has(id))return Response.json(provider.get(id));return Response.json({error:{message:'Not found'}},{status:404})};
const ctx=createContext({console,crypto:webcrypto,Response,Request,Headers,TextEncoder,TextDecoder,Uint8Array,Date,URL,AbortSignal,btoa,atob,fetch:fakeFetch,process:{env:{NODE_ENV:'production'}}});
const modules=new Map();const envModule=new SyntheticModule(['env'],function(){this.setExport('env',runtime)},{context:ctx});
function moduleFor(file){file=resolve(file);if(modules.has(file))return modules.get(file);const code=ts.transpileModule(readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;const m=new SourceTextModule(code,{context:ctx,identifier:file});modules.set(file,m);return m}
async function load(file){const m=moduleFor(file);if(m.status==='unlinked')await m.link((spec,ref)=>{if(spec==='cloudflare:workers')return envModule;const f=spec.startsWith('@/')?resolve(spec.slice(2)):resolve(dirname(ref.identifier),spec);return moduleFor(f.endsWith('.ts')?f:f+'.ts')});return m}
const action=await load('app/api/action/route.ts');await action.evaluate();const workspace=await load('app/api/workspace/route.ts');await workspace.evaluate();const run=await load('app/api/run/route.ts');await run.evaluate();
let owner='qa-owner-with-a-production-length-authenticated-user-id';const passed=[];const check=(name,val)=>{assert.ok(val,name);passed.push(name)};
async function request(mod,method,b,override={}){const headers={'Content-Type':'application/json','oai-authenticated-user-id':owner,...override};for(const k in headers)if(headers[k]===null)delete headers[k];const r=await mod.namespace[method](new Request('https://agency.test/api/test',{method,headers,...(b?{body:JSON.stringify(b)}:{})}));return {status:r.status,data:await r.json()}}
const act=(name,b={})=>request(action,'POST',{action:name,...b});const snapshot=()=>request(workspace,'GET');

await snapshot();
const created=await act('save_campaign',{data:{brandId:'ofd',title:'Delete test',goal:'Deletion only',budget:0}});const cid=created.data.id;
const payload={id:cid,version:1,confirmed:true};
check('deletion requires authentication',(await request(action,'POST',{action:'delete_campaign',...payload},{'oai-authenticated-user-id':null})).status===401);
check('cross-origin deletion rejected',(await request(action,'POST',{action:'delete_campaign',...payload},{origin:'https://other.test'})).status===403);
check('another owner cannot delete campaign',(await request(action,'POST',{action:'delete_campaign',...payload},{'oai-authenticated-user-id':'other-owner'})).status===404);
check('confirmation required',(await act('delete_campaign',{...payload,confirmed:false})).status===400);
check('stale campaign rejected',(await act('delete_campaign',{...payload,version:0})).status===409);
const server=await load('lib/server.ts');await server.evaluate();const put=(kind,id,data,parent='',user=owner)=>server.namespace.recordStatement(user,kind,id,data,parent).run();
const has=(kind,id,user=owner)=>!!sql.prepare('SELECT id FROM records WHERE owner=? AND kind=? AND id=?').get(user,kind,`${user}:${kind}:${id}`);
const job='delete-job';sql.prepare('INSERT INTO jobs(id,owner,campaign_id,role,status,model,campaign_version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(job,owner,cid,'cmo','uncertain','mock',1,'now','now');
check('uncertain provider execution prevents deletion',(await act('delete_campaign',payload)).status===409&&has('campaign',cid));
sql.prepare("UPDATE jobs SET status='completed' WHERE id=?").run(job);
await put('brief_draft','linked-draft',{id:'linked-draft',campaignId:cid,status:'queued'});
check('active linked brief prevents deletion',(await act('delete_campaign',payload)).status===409);
await put('brief_draft','linked-draft',{id:'linked-draft',campaignId:cid,status:'completed'});
await put('brief_draft','saved-draft',{id:'saved-draft',savedCampaignId:cid,status:'completed'});
await put('brief_draft','unrelated-draft',{id:'unrelated-draft',input:{title:'unrelated'},status:'queued'});
for(const kind of ['artifact','history','metric','event','learning_snapshot'])await put(kind,'linked-'+kind,{id:'linked-'+kind,campaignId:cid},cid);
await put('viral_experiment','exp',{id:'exp',campaignId:cid},cid);await put('experiment_revision','exp:1',{id:'exp'},'exp');await put('learning_rule','exp:2',{id:'exp:2',experimentId:'exp'},'ofd');
await put('hermes_submission',job,{body:'job input'});await put('hermes_submission','brief-linked-draft',{body:'brief input'});await put('hermes_submission','brief-saved-draft',{body:'brief input'});
await put('viral_case','source',{id:'source'},'ofd');await put('viral_analysis','analysis',{id:'analysis'},'source');
await put('learning_snapshot','other-snapshot',{rules:[{id:'exp:2'}]},'other-campaign');await put('learning_rule','other-rule',{id:'other-rule',experimentId:'other-exp'},'ofd');
await put('campaign',cid,{id:cid},'','other-owner');await put('artifact','foreign',{id:'foreign'},cid,'other-owner');
const before=JSON.stringify(sql.prepare('SELECT * FROM records ORDER BY id').all());
const originalBatch=DB.batch;DB.batch=async ss=>originalBatch([...ss,DB.prepare('INSERT INTO missing_table VALUES (1)')]);
check('storage failure reports error',(await act('delete_campaign',payload)).status===500);DB.batch=originalBatch;
check('deletion failure rolls back every dependent write',before===JSON.stringify(sql.prepare('SELECT * FROM records ORDER BY id').all()));
check('campaign deletion succeeds despite unrelated active brief',(await act('delete_campaign',payload)).data.deleted===true);
check('campaign and direct records removed',!has('campaign',cid)&&!has('artifact','linked-artifact')&&!has('history','linked-history')&&!has('metric','linked-metric')&&!has('event','linked-event')&&!has('learning_snapshot','linked-learning_snapshot'));
check('experiments revisions and derived rules removed',!has('viral_experiment','exp')&&!has('experiment_revision','exp:1')&&!has('learning_rule','exp:2'));
check('drafts and provider payloads removed',!has('brief_draft','linked-draft')&&!has('brief_draft','saved-draft')&&!has('hermes_submission',job)&&!has('hermes_submission','brief-linked-draft')&&!has('hermes_submission','brief-saved-draft'));
check('campaign execution history removed',!sql.prepare('SELECT id FROM jobs WHERE owner=? AND campaign_id=?').get(owner,cid));
check('shared source and unrelated history preserved',has('viral_case','source')&&has('viral_analysis','analysis')&&has('learning_snapshot','other-snapshot')&&has('learning_rule','other-rule')&&has('brief_draft','unrelated-draft'));
check('foreign owner records preserved',has('campaign',cid,'other-owner')&&has('artifact','foreign','other-owner'));
check('lost-response retry is idempotent',(await act('delete_campaign',payload)).status===200);
check('stale edit cannot recreate deleted campaign',(await act('save_campaign',{id:cid,version:1,data:{brandId:'ofd',title:'Resurrection',goal:'No',budget:0}})).status===404);
check('starter campaign can be deleted',(await act('delete_campaign',{id:'ofd-pilot-01',version:1,confirmed:true})).status===200);
const refreshed=await snapshot();check('refresh does not restore deleted starter',refreshed.data.campaigns.length===0&&refreshed.data.brands.length===4);
console.log(JSON.stringify({passed:passed.length,checks:passed},null,2));
