import assert from 'node:assert/strict';
import {test as nodeTest,after} from 'node:test';
// 스위트 러너(scripts/test.mjs)가 세는 {"passed":N}을 남긴다.
let passed=0;const test=(name,fn)=>nodeTest(name,async()=>{await fn();passed++});after(()=>console.log(JSON.stringify({passed})));
import {createHash} from 'node:crypto';
import {testRuntime} from './helpers/auth-runtime.mjs';
const origin='https://agency.example';
const password='A secure password 2026!';
const bootstrap='bootstrap-secret-token-with-at-least-32-characters';
const request=(path,body,cookie,headers={})=>new Request(origin+path,{method:body?'POST':'GET',headers:{origin,'content-type':'application/json',...(cookie?{cookie}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});
async function setup(hooks){const r=testRuntime(undefined,hooks);Object.assign(r.env,{AUTH_MODE:'email',AUTH_ORIGIN:origin,AUTH_BOOTSTRAP_EMAIL:'admin@example.com',AUTH_BOOTSTRAP_OWNER:'old-owner',AUTH_BOOTSTRAP_TOKEN_HASH:createHash('sha256').update(bootstrap).digest('hex')}); const api=await r.load('app/api/auth/route.ts'); const accounts=await r.load('app/api/accounts/route.ts'); const post=(b,c,h)=>api.POST(request('/api/auth',b,c,h)); const provision=()=>post({action:'bootstrap',email:'admin@example.com',password,token:bootstrap});return {...r,api,accounts,post,provision};}
const cookie=r=>r.headers.get('set-cookie')?.split(';')[0];
test('logout remains available after shared IP rate limit is exhausted',async()=>{const r=await setup();const c=cookie(await r.provision());r.sql.exec('UPDATE auth_rate_limits SET count=1000');const response=await r.post({action:'logout'},c);assert.equal(response.status,200);assert.match(response.headers.get('set-cookie'),/Max-Age=0/);assert.equal((await (await r.api.GET(request('/api/auth',null,c))).json()).user,null);});
test('bootstrap requires secret and is globally single use',async()=>{const r=await setup();assert.equal((await r.post({action:'bootstrap',email:'admin@example.com',password,token:'wrong'})).status,401); const a=await r.provision();assert.equal(a.status,200);assert.match(a.headers.get('set-cookie'),/HttpOnly/);assert.equal((await r.provision()).status,401);});
test('login rejects unknown and wrong-password accounts identically',async()=>{const r=await setup();await r.provision();const a=await r.post({action:'login',email:'missing@example.com',password});const b=await r.post({action:'login',email:'admin@example.com',password:'incorrect password'});assert.equal(a.status,401);assert.deepEqual(await a.json(),await b.json());});
test('session lookup rejects forged and expired credentials; logout revokes immediately',async()=>{const r=await setup();const c=cookie(await r.provision());assert.equal((await (await r.api.GET(request('/api/auth',null,c))).json()).user.email,'admin@example.com');assert.equal((await (await r.api.GET(request('/api/auth',null,'__Host-collective_session=forged'))).json()).user,null);await r.post({action:'logout'},c);assert.equal((await (await r.api.GET(request('/api/auth',null,c))).json()).user,null);const c2=cookie(await r.post({action:'login',email:'admin@example.com',password}));r.sql.exec('UPDATE auth_sessions SET expires_at=0');assert.equal((await (await r.api.GET(request('/api/auth',null,c2))).json()).user,null);});
test('CSRF rejects missing Origin, foreign origin and non JSON',async()=>{const r=await setup();assert.equal((await r.post({action:'login'},{},{origin:''})).status,403);assert.equal((await r.post({action:'login'},null,{origin:'https://evil.example'})).status,403);assert.equal((await r.post({action:'login'},null,{'content-type':'text/plain'})).status,415);});
test('invited member shares issuer workspace but cannot manage accounts',async()=>{const r=await setup();const c=cookie(await r.provision());const invite=await r.accounts.POST(request('/api/accounts',{action:'invite',email:'member@example.com',role:'member'},c));assert.equal(invite.status,200);const {token}=await invite.json();const accepted=await r.post({action:'accept',email:'member@example.com',token,password});assert.equal(accepted.status,200);const member=cookie(accepted);assert.equal((await r.accounts.GET(request('/api/accounts',null,member))).status,403);const {authPrincipal}=await r.load('lib/auth-session.ts');assert.equal((await authPrincipal(request('/',null,member))).owner,'old-owner');assert.equal(r.sql.prepare('SELECT token_hash FROM auth_tokens WHERE user_id IS NOT NULL').get().token_hash.includes(token),false);});
test('invitation is email bound, expired tokens fail and concurrent use has one winner',async()=>{const r=await setup();const c=cookie(await r.provision());const response=await r.accounts.POST(request('/api/accounts',{action:'invite',email:'member@example.com',role:'member'},c));const {token}=await response.json();assert.equal((await r.post({action:'accept',email:'other@example.com',token,password})).status,401);const results=await Promise.all([r.post({action:'accept',email:'member@example.com',token,password}),r.post({action:'accept',email:'member@example.com',token,password})]);assert.deepEqual(results.map(x=>x.status).sort(),[200,401]);const reset=await r.accounts.POST(request('/api/accounts',{action:'reset',userId:r.sql.prepare("SELECT id FROM auth_users WHERE email='member@example.com'").get().id},c));r.sql.exec('UPDATE auth_tokens SET expires_at=0');assert.equal((await r.post({action:'accept',email:'member@example.com',token:(await reset.json()).token,password})).status,401);});
test('reset revokes old sessions and disabled accounts cannot use sessions or reset',async()=>{const r=await setup();const c=cookie(await r.provision());const {token}=await (await r.accounts.POST(request('/api/accounts',{action:'invite',email:'member@example.com',role:'member'},c))).json();const mc=cookie(await r.post({action:'accept',email:'member@example.com',token,password}));const id=r.sql.prepare("SELECT id FROM auth_users WHERE email='member@example.com'").get().id;const rt=(await (await r.accounts.POST(request('/api/accounts',{action:'reset',userId:id},c))).json()).token;const nc=cookie(await r.post({action:'accept',email:'member@example.com',token:rt,password:'Replacement password 2026!'}));assert.equal((await (await r.api.GET(request('/',null,mc))).json()).user,null);assert.equal((await r.accounts.POST(request('/api/accounts',{action:'disable',userId:id},c))).status,200);assert.equal((await (await r.api.GET(request('/',null,nc))).json()).user,null);});
test('admin cannot reset other workspace or disable self',async()=>{const r=await setup();const c=cookie(await r.provision());r.sql.exec("INSERT INTO auth_users(id,email,password_hash,workspace_owner,role,status,created_at) VALUES('other','other@example.com','','elsewhere','member','active',0)");assert.equal((await r.accounts.POST(request('/api/accounts',{action:'reset',userId:'other'},c))).status,404);const id=r.sql.prepare("SELECT id FROM auth_users WHERE email='admin@example.com'").get().id;assert.equal((await r.accounts.POST(request('/api/accounts',{action:'disable',userId:id},c))).status,400);const list=await (await r.accounts.GET(request('/api/accounts',null,c))).json();assert.equal(list.accounts.length,1);assert.equal(JSON.stringify(list).includes('password_hash'),false);});
test('rate limiting is persisted and cannot be bypassed with forwarded headers',async()=>{const r=await setup();for(let i=0;i<10;i++)await r.post({action:'login',email:'missing@example.com',password},null,{'x-forwarded-for':`1.2.3.${i}`});assert.equal((await r.post({action:'login',email:'missing@example.com',password})).status,429);assert.ok(r.sql.prepare('SELECT COUNT(*) n FROM auth_rate_limits').get().n>0);});
test('legacy rejects credential mutations and unavailable DB fails closed',async()=>{const r=await setup();r.env.AUTH_MODE='legacy';assert.equal((await r.provision()).status,409);r.env.AUTH_MODE='email';delete r.env.DB;assert.equal((await r.api.GET(request('/api/auth'))).status,503);});
test('password change needs old secret and revokes other sessions and reset links',async()=>{const r=await setup();const first=cookie(await r.provision());const second=cookie(await r.post({action:'login',email:'admin@example.com',password}));assert.equal((await r.post({action:'change_password',currentPassword:'wrong',password:'New password 2026!'},first)).status,401);const changed=await r.post({action:'change_password',currentPassword:password,password:'New password 2026!'},first);assert.equal(changed.status,200);assert.equal((await (await r.api.GET(request('/',null,second))).json()).user,null);assert.equal((await r.post({action:'login',email:'admin@example.com',password})).status,401);assert.equal((await r.post({action:'login',email:'admin@example.com',password:'New password 2026!'})).status,200);});
test('bootstrap concurrency creates exactly one admin and no session for loser',async()=>{const r=await setup();const results=await Promise.all([r.provision(),r.provision()]);assert.deepEqual(results.map(x=>x.status).sort(),[200,401]);assert.equal(r.sql.prepare('SELECT COUNT(*) n FROM auth_users').get().n,1);assert.equal(r.sql.prepare('SELECT COUNT(*) n FROM auth_sessions').get().n,1);});
test('pending user cannot login; weak password and oversized payload are rejected',async()=>{const r=await setup();assert.equal((await r.post({action:'bootstrap',email:'admin@example.com',password:'short',token:bootstrap})).status,400);const c=cookie(await r.provision());await r.accounts.POST(request('/api/accounts',{action:'invite',email:'pending@example.com',role:'member'},c));assert.equal((await r.post({action:'login',email:'pending@example.com',password})).status,401);assert.equal((await r.post({action:'login',email:'admin@example.com',password:'x'.repeat(17000)})).status,413);});
test('unconfigured or foreign production origin fails closed',async()=>{const r=await setup();delete r.env.AUTH_ORIGIN;assert.equal((await r.api.GET(request('/api/auth'))).status,503);r.env.AUTH_ORIGIN='http://agency.example';assert.equal((await r.api.GET(request('/api/auth'))).status,403);r.env.AUTH_ORIGIN=origin;assert.equal((await r.api.GET(new Request('https://other.example/api/auth'))).status,403);});
test('pending accounts cannot be promoted by reinvite and reset links are superseded',async()=>{const r=await setup();const c=cookie(await r.provision());const one=await r.accounts.POST(request('/api/accounts',{action:'invite',email:'member@example.com',role:'member'},c));const old=(await one.json()).token;assert.equal((await r.accounts.POST(request('/api/accounts',{action:'invite',email:'member@example.com',role:'admin'},c))).status,409);const two=await r.accounts.POST(request('/api/accounts',{action:'invite',email:'member@example.com',role:'member'},c));assert.equal(two.status,200);assert.equal((await r.post({action:'accept',email:'member@example.com',token:old,password})).status,401);});
test('IP limit rejects before creating unbounded account rate-limit rows',async()=>{const r=await setup();const key=createHash('sha256').update('ip:unknown-edge-address').digest('hex');r.sql.prepare('INSERT INTO auth_rate_limits(key,count,window_start) VALUES(?,100,?)').run(key,Date.now());assert.equal((await r.post({action:'login',email:'random@example.com',password})).status,429);assert.equal(r.sql.prepare('SELECT COUNT(*) n FROM auth_rate_limits').get().n,1);});
test('stale administrator cannot issue invitations after account disable',async()=>{const r=await setup();const c=cookie(await r.provision());const {authPrincipal}=await r.load('lib/auth-session.ts');const admin=await authPrincipal(request('/',null,c));r.sql.exec("UPDATE auth_users SET status='disabled'");const {issueToken}=await r.load('lib/auth-accounts.ts');await assert.rejects(()=>issueToken(admin,{action:'invite',email:'attacker@example.com',role:'admin'}));assert.equal(r.sql.prepare("SELECT COUNT(*) n FROM auth_users WHERE email='attacker@example.com'").get().n,0);});
test('explicit invalid authentication mode fails closed instead of trusting legacy headers',async()=>{const r=await setup();for(const mode of ['Email','emails','', ' email ']){r.env.AUTH_MODE=mode;const response=await r.api.GET(request('/api/auth',null,null,{'oai-authenticated-user-id':'forged-owner'}));assert.equal(response.status,503);assert.equal((await r.provision()).status,503);}delete r.env.AUTH_MODE;assert.equal((await r.api.GET(request('/api/auth',null,null,{'oai-authenticated-user-id':'forged-owner'}))).status,503);r.env.AUTH_MODE='legacy';assert.deepEqual(await (await r.api.GET(request('/api/auth'))).json(),{mode:'legacy',user:null});assert.equal((await r.api.GET(request('/api/auth'))).status,200);});
test('sole active administrator may cancel an unaccepted administrator invitation',async()=>{const r=await setup();const c=cookie(await r.provision());await r.accounts.POST(request('/api/accounts',{action:'invite',email:'pending-admin@example.com',role:'admin'},c));const id=r.sql.prepare("SELECT id FROM auth_users WHERE email='pending-admin@example.com'").get().id;assert.equal((await r.accounts.POST(request('/api/accounts',{action:'disable',userId:id},c))).status,200);assert.equal(r.sql.prepare("SELECT COUNT(*) n FROM auth_users WHERE role='admin' AND status='active'").get().n,1);});

// 소유자·관리자 분리, 잠금 공격 완화, 계정 복구·권한 변경·초대 취소·세션 종료, 정리 작업, 행위자 기록.
const sha=value=>createHash('sha256').update(value).digest('hex');
const ip=address=>({'cf-connecting-ip':address});
async function team(){
 const r=await setup();const owner=cookie(await r.provision());
 const manage=(body,by=owner,headers={})=>r.accounts.POST(request('/api/accounts',body,by,headers));
 const id=email=>r.sql.prepare('SELECT id FROM auth_users WHERE email=?').get(email)?.id;
 const join=async(email,role,by=owner)=>{const {token}=await (await manage({action:'invite',email,role},by,ip('10.9.9.'+email.length))).json();return cookie(await r.post({action:'accept',email,token,password},null,ip('10.8.8.'+email.length)));};
 const me=async c=>(await (await r.api.GET(request('/api/auth',null,c))).json()).user;
 return {...r,owner,manage,id,join,me};
}
test('bootstrap account is the owner; invited administrators are plain admins',async()=>{const t=await team();assert.equal((await t.me(t.owner)).role,'owner');const b=await t.join('admin-b@example.com','admin');assert.equal((await t.me(b)).role,'admin');assert.equal((await t.post({action:'login',email:'admin-b@example.com',password})).status,200);assert.equal((await (await t.post({action:'login',email:'admin@example.com',password})).json()).user.role,'owner');});
test('admin B gets 403 when resetting, disabling, re-roling or signing out the owner',async()=>{const t=await team();const b=await t.join('admin-b@example.com','admin');const ownerId=t.id('admin@example.com');for(const action of ['reset','disable','set_role','revoke_sessions']){const response=await t.manage({action,userId:ownerId,role:'member'},b);assert.equal(response.status,403,action);}assert.equal(t.sql.prepare("SELECT COUNT(*) n FROM auth_tokens WHERE user_id=? AND kind='reset'").get(ownerId).n,0);assert.equal((await t.me(t.owner)).role,'owner');assert.equal(t.sql.prepare('SELECT status FROM auth_users WHERE id=?').get(ownerId).status,'active');assert.equal((await t.post({action:'login',email:'admin@example.com',password})).status,200);});
test('only the owner invites or manages administrators; admins manage members',async()=>{const t=await team();const b=await t.join('admin-b@example.com','admin');const c=await t.join('admin-c@example.com','admin');assert.ok(c);assert.equal((await t.manage({action:'invite',email:'new-admin@example.com',role:'admin'},b)).status,403);assert.equal(t.id('new-admin@example.com'),undefined);assert.equal((await t.manage({action:'reset',userId:t.id('admin-c@example.com')},b)).status,403);assert.equal((await t.manage({action:'disable',userId:t.id('admin-c@example.com')},b)).status,403);assert.equal((await t.manage({action:'invite',email:'staff@example.com',role:'member'},b)).status,200);await t.post({action:'accept',email:'staff@example.com',token:(await (await t.manage({action:'invite',email:'staff@example.com',role:'member'},b)).json()).token,password});assert.equal((await t.manage({action:'reset',userId:t.id('staff@example.com')},b)).status,200);assert.equal((await t.manage({action:'disable',userId:t.id('admin-c@example.com')})).status,200);});
test('failed logins from another IP do not block the real user and success clears account counters',async()=>{const r=await setup();await r.provision();for(let i=0;i<10;i++)assert.equal((await r.post({action:'login',email:'admin@example.com',password:'wrong password guess'},null,ip('6.6.6.6'))).status,401);assert.equal((await r.post({action:'login',email:'admin@example.com',password},null,ip('6.6.6.6'))).status,429);assert.equal((await r.post({action:'login',email:'admin@example.com',password},null,ip('1.1.1.1'))).status,200);const accountKeys=[sha('account:admin@example.com'),sha('account-ip:admin@example.com|1.1.1.1')];assert.equal(r.sql.prepare('SELECT COUNT(*) n FROM auth_rate_limits WHERE key IN (?,?)').get(...accountKeys).n,0);r.sql.prepare('INSERT INTO auth_rate_limits(key,count,window_start) VALUES(?,50,?)').run(accountKeys[0],Date.now());assert.equal((await r.post({action:'login',email:'admin@example.com',password},null,ip('2.2.2.2'))).status,200);});
test('reactivate returns a disabled account to pending with a one-time reset link',async()=>{const t=await team();await t.join('member@example.com','member');const userId=t.id('member@example.com');assert.equal((await t.manage({action:'reactivate',userId})).status,409);assert.equal((await t.manage({action:'disable',userId})).status,200);const reactivated=await t.manage({action:'reactivate',userId});assert.equal(reactivated.status,200);const {token}=await reactivated.json();assert.equal(t.sql.prepare('SELECT status FROM auth_users WHERE id=?').get(userId).status,'pending');assert.equal((await t.post({action:'login',email:'member@example.com',password})).status,401);assert.equal((await t.post({action:'accept',email:'member@example.com',token,password:'Recovered password 2026!'})).status,200);assert.equal((await t.post({action:'login',email:'member@example.com',password:'Recovered password 2026!'})).status,200);const b=await t.join('admin-b@example.com','admin');const c=await t.join('admin-c@example.com','admin');assert.ok(c);await t.manage({action:'disable',userId:t.id('admin-c@example.com')});assert.equal((await t.manage({action:'reactivate',userId:t.id('admin-c@example.com')},b)).status,403);});
test('owner changes member and admin roles; owner role is immutable and admins cannot change roles',async()=>{const t=await team();const m=await t.join('member@example.com','member');const b=await t.join('admin-b@example.com','admin');const userId=t.id('member@example.com');assert.equal((await t.manage({action:'set_role',userId,role:'admin'},b)).status,403);assert.equal((await t.manage({action:'set_role',userId,role:'owner'})).status,400);assert.equal((await t.manage({action:'set_role',userId:t.id('admin@example.com'),role:'member'})).status,403);assert.equal((await t.manage({action:'set_role',userId,role:'admin'})).status,200);assert.equal((await t.me(m)).role,'admin');assert.equal((await t.manage({action:'set_role',userId,role:'admin'})).status,409);assert.equal((await t.manage({action:'set_role',userId:t.id('admin-b@example.com'),role:'member'})).status,200);assert.equal((await t.me(b)).role,'member');assert.equal((await t.accounts.GET(request('/api/accounts',null,b))).status,403);assert.equal((await t.me(t.owner)).role,'owner');});
test('cancelling an unaccepted invitation deletes it so the email can be invited again',async()=>{const t=await team();const {token}=await (await t.manage({action:'invite',email:'pending@example.com',role:'member'})).json();const userId=t.id('pending@example.com');assert.equal((await t.manage({action:'cancel_invite',userId})).status,200);assert.equal(t.id('pending@example.com'),undefined);assert.equal((await t.post({action:'accept',email:'pending@example.com',token,password})).status,401);assert.equal((await t.manage({action:'invite',email:'pending@example.com',role:'admin'})).status,200);await t.join('member@example.com','member');assert.equal((await t.manage({action:'cancel_invite',userId:t.id('member@example.com')})).status,409);const b=await t.join('admin-b@example.com','admin');assert.equal((await t.manage({action:'cancel_invite',userId:t.id('pending@example.com')},b)).status,403);assert.ok(t.id('pending@example.com'));});
test('revoke_sessions ends every login of the target; the owner may end only their own',async()=>{const t=await team();const first=await t.join('member@example.com','member');const second=cookie(await t.post({action:'login',email:'member@example.com',password}));assert.equal((await t.manage({action:'revoke_sessions',userId:t.id('member@example.com')})).status,200);assert.equal(await t.me(first),null);assert.equal(await t.me(second),null);assert.equal(t.sql.prepare('SELECT status FROM auth_users WHERE id=?').get(t.id('member@example.com')).status,'active');assert.equal((await t.post({action:'login',email:'member@example.com',password})).status,200);const other=cookie(await t.post({action:'login',email:'admin@example.com',password}));const own=await t.manage({action:'revoke_sessions',userId:t.id('admin@example.com')});assert.equal(own.status,200);assert.match(own.headers.get('set-cookie'),/Max-Age=0/);assert.equal(await t.me(t.owner),null);assert.equal(await t.me(other),null);});
test('successful login removes expired sessions, stale tokens and finished rate-limit windows',async()=>{const r=await setup();await r.provision();const userId=r.sql.prepare('SELECT id FROM auth_users').get().id,now=Date.now(),day=86400000;r.sql.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?)').run('expired-session',userId,now-1000,now-2*day);r.sql.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?)').run('live-session',userId,now+day,now);const token=(hash,expires,used)=>r.sql.prepare("INSERT INTO auth_tokens(token_hash,user_id,email,owner,role,kind,expires_at,used,created_at) VALUES(?,?,'admin@example.com','old-owner','admin','reset',?,?,?)").run(hash,userId,expires,used,expires-day);token('old-used',now-8*day,'nonce');token('old-unused',now-8*day,null);token('recent-expired',now-day,null);token('live',now+day,null);r.sql.prepare('INSERT INTO auth_rate_limits VALUES(?,?,?)').run('stale',3,now-16*60000);r.sql.prepare('INSERT INTO auth_rate_limits VALUES(?,?,?)').run('fresh',3,now-60000);assert.equal((await r.post({action:'login',email:'admin@example.com',password},null,ip('3.3.3.3'))).status,200);const has=(table,column,value)=>r.sql.prepare(`SELECT COUNT(*) n FROM ${table} WHERE ${column}=?`).get(value).n===1;assert.equal(has('auth_sessions','session_hash','expired-session'),false);assert.ok(has('auth_sessions','session_hash','live-session'));assert.equal(has('auth_tokens','token_hash','old-used'),false);assert.equal(has('auth_tokens','token_hash','old-unused'),false);assert.ok(has('auth_tokens','token_hash','recent-expired'));assert.ok(has('auth_tokens','token_hash','live'));assert.ok(has('auth_tokens','token_hash','bootstrap'));assert.equal(has('auth_rate_limits','key','stale'),false);assert.ok(has('auth_rate_limits','key','fresh'));});
test('account changes are recorded with the actor and only the owner sees the latest 20',async()=>{const t=await team();const b=await t.join('admin-b@example.com','admin');await t.manage({action:'invite',email:'staff@example.com',role:'member'},b);const userId=t.id('staff@example.com');await t.manage({action:'cancel_invite',userId},b);await t.join('member@example.com','member');const memberId=t.id('member@example.com');for(const action of ['reset','revoke_sessions','disable','reactivate'])assert.equal((await t.manage({action,userId:memberId},t.owner,ip('7.7.7.7'))).status,200,action);assert.equal((await t.manage({action:'set_role',userId:memberId,role:'admin'},t.owner,ip('7.7.7.7'))).status,200);const view=await (await t.accounts.GET(request('/api/accounts',null,t.owner))).json();assert.deepEqual(view.events.slice(0,6).map(e=>e.action),['set_role','reactivate','disable','revoke_sessions','reset','invite']);assert.deepEqual(view.events[0].actor,{id:t.id('admin@example.com'),email:'admin@example.com'});assert.equal(view.events[0].targetEmail,'member@example.com');assert.equal(view.events[0].role,'admin');const byB=view.events.filter(e=>e.actor.email==='admin-b@example.com').map(e=>e.action);assert.deepEqual(byB,['cancel_invite','invite']);assert.equal(JSON.stringify(view.events).includes('token'),false);assert.equal('events' in await (await t.accounts.GET(request('/api/accounts',null,b))).json(),false);for(let i=0;i<25;i++)t.sql.prepare("INSERT INTO records(id,owner,kind,parent_id,data,updated_at) VALUES(?,?,'account_event','',?,?)").run('old-owner:account_event:filler'+i,'old-owner',JSON.stringify({id:'filler'+i,action:'invite'}),'2020-01-01T00:00:'+String(i).padStart(2,'0')+'.000Z');const capped=await (await t.accounts.GET(request('/api/accounts',null,t.owner))).json();assert.equal(capped.events.length,20);assert.equal(capped.events[0].action,'set_role');});

// 리뷰 후속: 분산 잠금 완화(IPv6 /64 묶음, 계정 전체 키 점진 지연), 잠금 기록, 제한 초기화 실패 허용, 로그인 실패 경로의 정리, 해제·강등된 관리자가 발급한 링크 폐기.
test('failures spread over five IPs do not lock out a clean IP and the owner sees one lockout record',async()=>{const t=await team();for(let n=1;n<=5;n++)for(let i=0;i<10;i++)assert.equal((await t.post({action:'login',email:'admin@example.com',password:'wrong password guess'},null,ip('6.6.6.'+n))).status,401);assert.equal((await t.post({action:'login',email:'admin@example.com',password},null,ip('1.1.1.1'))).status,200);const events=(await (await t.accounts.GET(request('/api/accounts',null,t.owner))).json()).events.filter(e=>e.action==='lockout');assert.equal(events.length,1);assert.equal(events[0].targetEmail,'admin@example.com');assert.equal(events[0].targetId,t.id('admin@example.com'));});
test('IPv6 addresses in one /64 share a single account-and-IP budget',async()=>{const r=await setup();await r.provision();for(let i=1;i<=51;i++)await r.post({action:'login',email:'admin@example.com',password:'wrong password guess'},null,ip('2001:db8:1:2::'+i.toString(16)));assert.equal((await r.post({action:'login',email:'admin@example.com',password},null,ip('2001:0db8:0001:0002:ffff:0:0:9'))).status,429);assert.equal((await r.post({action:'login',email:'admin@example.com',password},null,ip('198.51.100.7'))).status,200);assert.equal(r.sql.prepare('SELECT COUNT(*) n FROM auth_rate_limits WHERE key=?').get(sha('ip:2001:db8:1:2::/64')).n,1);});
test('account-wide failures past 50 slow attempts down instead of blocking the account',async()=>{const r=await setup();await r.provision();const now=Date.now();const seed=(name,count,start)=>r.sql.prepare('INSERT OR REPLACE INTO auth_rate_limits(key,count,window_start) VALUES(?,?,?)').run(sha(name),count,start);seed('account:admin@example.com',55,now-60000);seed('account-wait:admin@example.com',0,now-1000);const early=await r.post({action:'login',email:'admin@example.com',password},null,ip('2.2.2.2'));assert.equal(early.status,429);assert.match((await early.json()).error,/잠시/);assert.equal(r.sql.prepare('SELECT count FROM auth_rate_limits WHERE key=?').get(sha('account:admin@example.com')).count,55);seed('account-wait:admin@example.com',0,now-6000);assert.equal((await r.post({action:'login',email:'admin@example.com',password},null,ip('2.2.2.2'))).status,200);});
test('a failed rate-limit reset after a committed login or password change still returns the new session',async()=>{let failing=false;const r=await setup({beforeRun(statement){if(failing&&statement.query.startsWith('DELETE FROM auth_rate_limits WHERE key IN'))throw new Error('transient D1 failure')}});const first=cookie(await r.provision());failing=true;const changed=await r.post({action:'change_password',currentPassword:password,password:'New password 2026!'},first);assert.equal(changed.status,200);assert.match(changed.headers.get('set-cookie'),/HttpOnly/);assert.equal((await (await r.api.GET(request('/api/auth',null,cookie(changed)))).json()).user.email,'admin@example.com');const login=await r.post({action:'login',email:'admin@example.com',password:'New password 2026!'});assert.equal(login.status,200);assert.match(login.headers.get('set-cookie'),/HttpOnly/);});
test('a new IP window removes finished rate-limit windows and expired sessions even without a successful login',async()=>{const r=await setup();await r.provision();const userId=r.sql.prepare('SELECT id FROM auth_users').get().id,now=Date.now();r.sql.prepare('INSERT INTO auth_rate_limits VALUES(?,?,?)').run('stale',3,now-16*60000);r.sql.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?)').run('expired-session',userId,now-1000,now-86400000);assert.equal((await r.post({action:'login',email:'random@example.com',password},null,ip('4.4.4.4'))).status,401);assert.equal(r.sql.prepare("SELECT COUNT(*) n FROM auth_rate_limits WHERE key='stale'").get().n,0);assert.equal(r.sql.prepare("SELECT COUNT(*) n FROM auth_sessions WHERE session_hash='expired-session'").get().n,0);});
test('links issued by an administrator stop working once that administrator is disabled or demoted',async()=>{const t=await team();for(const change of ['disable','set_role']){const admin=change.replace('_','-')+'-admin@example.com',staff=change.replace('_','-')+'-staff@example.com';const b=await t.join(admin,'admin');await t.join(staff,'member');const {token}=await (await t.manage({action:'reset',userId:t.id(staff)},b)).json();assert.equal((await t.manage({action:change,userId:t.id(admin),role:'member'})).status,200,change);assert.equal((await t.post({action:'accept',email:staff,token,password:'Takeover password 2026!'},null,ip('9.9.9.9'))).status,401,change);assert.equal((await t.post({action:'login',email:staff,password},null,ip('9.9.9.8'))).status,200,change);}const view=await (await t.accounts.GET(request('/api/accounts',null,t.owner))).json();assert.equal(JSON.stringify(view.events).includes('token'),false);});
test('sessions end after 7 idle days, slide forward on use and never outlive 30 days from login',async()=>{const r=await setup();const c=cookie(await r.provision()),hash=sha(c.split('=')[1]),day=86400000,hour=3600000;const row=()=>r.sql.prepare('SELECT expires_at e,created_at c FROM auth_sessions WHERE session_hash=?').get(hash);const set=(created,expires)=>r.sql.prepare('UPDATE auth_sessions SET created_at=?,expires_at=? WHERE session_hash=?').run(created,expires,hash);const me=async()=>(await (await r.api.GET(request('/api/auth',null,c))).json()).user;assert.ok(row().e<=Date.now()+7*day+1000);let now=Date.now();set(now-2*day,now+2*hour);assert.equal((await me()).email,'admin@example.com');assert.ok(row().e>=now+7*day-60000);now=Date.now();set(now-30*day+2*hour,now+hour);assert.ok(await me());assert.equal(row().e,row().c+30*day);now=Date.now();set(now-8*day,now-day);assert.equal(await me(),null);});
