// 트랙 R R15a-2a 모집 자료·행사 경로 스위트(/api/franchise 작업 9개·GET 보기 3개, app/api/brand-facts 재검토 훅): 기능 스위치(폐기·취소만 꺼짐 허용)·연락처 키 예외, 역할(직원 403),
// 다른 브랜드·워크스페이스 404, 초안 저장(판·멱등·판 CAS·출처 작업물·한도), 승인·내보내기 게이트(hard_block·분기 A·수익 안전망·위조 승인 행·재생), 게시 위치·폐기,
// 설명회·견학·박람회(정원·동시 신청·잠금·참석 KST 날짜·시작·취소·followUps), 사실 판 인상·정보공개서 버전 변경 재검토(rebase_facts 포함), 조건부 쓰기 보호(rowGuard·reviewStatement),
// 보기(원문 없는 목록·상세 게이트·drift), 감사 행(원문·라벨·가명 코드 없음), 캠페인 삭제 뒤 campaignMissing, 외부 호출 0.
// 교차 검토 반영: 자료 저장의 잠금 만료 경합(승인 판 삭제·동시 저장 유실 없음), 숫자 id 404, 쓰기 작업 전부의 커밋 경합·rev/판 올림, 재생 대상 묶음, 옛 판 내보내기·게시·폐기,
// 행사 변경 경로 개인정보·비용 참조, 내보내기 막힘 영수증, 감사 키 허용 목록, 재검토 훅 실패 주입(저장 유지·null), 판 2 이상 사실 수정, KST 자정을 넘는 재생 파일 이름.
// 근거: mocked(메모리 SQLite node:sqlite, 이메일 모드 세션 주입, 외부 fetch는 던지는 스텁, 시계 이동 Date, batch 가로채기로 경합 재현). 결과는 COLLECTIVE 휴리스틱 · 법률 자문 아님.
// 운영 real 확인·E2E·직원 403 real 확인은 not_run이다(화면 없음, 게시는 레인 A 몫). 브랜드 삭제는 API가 없어 not_run(대상 없음)이다.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {franchiseFixture,captureConsole,HOUR,DISCLAIMER,plain,sha64} from './helpers/franchise-fixture.mjs';

const logged=captureConsole();
const f=await franchiseFixture();
const {sql,env,server}=f;
env.AUTH_MODE='email';env.AUTH_ORIGIN='https://agency.test';
const passed=[];const check=(name,val)=>{assert.ok(val,name);passed.push(name)};
// 서버 시각을 옮긴다(앞으로만). 인자 없는 Date·Date.now()가 이 시각에서 실제 시간만큼 흐른다.
const setNow=ms=>f.clock.set(ms-Date.now()),nowMs=()=>f.clock.now(),iso=(d=0)=>new Date(nowMs()+d).toISOString();
const kstDay=(d=0)=>new Date(nowMs()+9*HOUR+d).toISOString().slice(0,10);
setNow(Date.parse('2026-10-05T03:00:00Z'));
const fa=await f.load('lib/franchise-assets.ts'),factsRoute=await f.load('app/api/brand-facts/route.ts');
const E=plain(f.lib.FRANCHISE_ERRORS),T=k=>E[k].text;
const LOCKED='다른 작업을 저장하고 있습니다. 잠시 후 다시 시도하세요.';
const WS='ra-owner',WS2='ra-owner-2';
const boss=f.signIn('ra-boss','admin',1000,WS),admin=f.signIn('ra-admin','admin',2000,WS),member=f.signIn('ra-member','member',3000,WS),member2=f.signIn('ra-member-2','member',4000,WS);
const boss2=f.signIn('ra-boss-2','admin',1000,WS2);
for(const b of ['fr-a','fr-b','fr-c','fr-l','fr-n'])await f.brand(WS,b);
await f.brand(WS2,'fr-a');

// ── 호출·조회 보조 ──
const responses=[];
const post=async(s,input)=>{const r=await f.post(s,input);responses.push(r.body);return r};
const get=async(s,q)=>{const r=await f.get(s,q);responses.push(r.body);return r};
const headersOf=s=>Object.fromEntries(Object.entries(s).filter(([k])=>k!=='id'));
const factPost=async(s,input)=>{
 sql.prepare("DELETE FROM records WHERE kind='execution_rate'").run();
 const res=await factsRoute.POST(new Request('https://agency.test/api/brand-facts',{method:'POST',headers:{'content-type':'application/json',...headersOf(s)},body:JSON.stringify(input)}));
 const text=await res.text(),body=JSON.parse(text);responses.push(body);return {status:res.status,body,text};
};
const snapshot=()=>sql.prepare("SELECT id,data FROM records WHERE kind LIKE 'recruitment_%' OR kind='franchise_audit' ORDER BY id").all().map(r=>r.id+'\t'+r.data).join('\n');
const assetKey=(id,v)=>`${WS}:recruitment_asset:${id}:${v}`;
const assetRows=id=>sql.prepare("SELECT id,parent_id,data FROM records WHERE kind='recruitment_asset' AND json_extract(data,'$.id')=? ORDER BY json_extract(data,'$.version')").all(id).map(r=>({key:r.id,parent:r.parent_id,...JSON.parse(r.data)}));
const assetRow=(id,v)=>JSON.parse(sql.prepare("SELECT data FROM records WHERE kind='recruitment_asset' AND id=?").get(assetKey(id,v)).data);
const eventRow=id=>JSON.parse(sql.prepare("SELECT data FROM records WHERE kind='recruitment_event' AND id=?").get(`${WS}:recruitment_event:${id}`).data);
const audits=action=>sql.prepare("SELECT data FROM records WHERE kind='franchise_audit' AND json_extract(data,'$.action')=?").all(action).map(r=>JSON.parse(r.data));
const patch=(key,path,value)=>sql.prepare(`UPDATE records SET data=json_set(data,'${path}',json(?)) WHERE id=?`).run(JSON.stringify(value),key);
const insertRow=(key,kind,parent,data)=>sql.prepare('INSERT INTO records(id,owner,kind,parent_id,data,updated_at) VALUES(?,?,?,?,?,?)').run(key,WS,kind,parent,JSON.stringify(data),'2026-10-01T00:00:00.000Z');
const codes=r=>(r.body.reasons||[]).map(x=>x.code);
const codesAre=(r,status,...list)=>r.status===status&&JSON.stringify(codes(r))===JSON.stringify(list);
const fixed=(r,status,key)=>r.status===status&&r.body.error===T(key);
// batch 가로채기: 조건부 쓰기 보호 문장(IS NOT ?)으로 시작하는 다음 batch 직전에 한 번 행을 바꾼다(잠금 밖 경합 재현).
const realBatch=env.DB.batch;
const raceOnce=mutate=>{env.DB.batch=async stmts=>{if(String(stmts[0]?.query).includes('IS NOT ?')){env.DB.batch=realBatch;mutate()}return realBatch(stmts)}};
// 커밋 batch 가로채기: 영수증 행의 작업이 action인 다음 batch 직전에 한 번 끼어든다(보호 문장 유무와 무관). 잠금 만료는 mutation_locks를 지워 재현한다.
const receiptOf=(stmts,action)=>stmts.some(s=>Array.isArray(s.values)&&s.values.some(v=>typeof v==='string'&&v.includes(`"action":"${action}"`)));
const raceCommit=(action,mutate)=>{env.DB.batch=async stmts=>{if(receiptOf(stmts,action)){env.DB.batch=realBatch;await mutate()}return realBatch(stmts)}};
const expireLock=()=>sql.prepare('DELETE FROM mutation_locks').run();
const bumpRev=key=>sql.prepare("UPDATE records SET data=json_set(data,'$.rev',json_extract(data,'$.rev')+10) WHERE id=?").run(key);
const bumpVer=key=>sql.prepare("UPDATE records SET data=json_set(data,'$.version',json_extract(data,'$.version')+10) WHERE id=?").run(key);
const evKey=id=>`${WS}:recruitment_event:${id}`;

// ── 준비: 스위치·프로필·정보공개서 버전·사실·캠페인·지점·작업물 ──
check('owner turns the franchise switch on',(await f.setFlag(boss,true)).status===200);
const LABEL='가상 보관함',FY={forecastInputs:{sme:true,storesAtFyEnd:3,fiscalYearEnd:'2025-12-31'},storageLabels:[LABEL]};
for(const [b,branch] of [['fr-a','A'],['fr-b','A'],['fr-c','B'],['fr-l','A']]){const r=await f.profile(boss,b,{...FY,branch},0);assert.equal(r.status,200,JSON.stringify(r.body))}
const registerVersion=async(brandId,label,seedText,meta)=>{const r=await post(boss,{action:'register_disclosure_version',brandId,label,sha256:sha64(seedText),storageLabel:LABEL,...meta});assert.equal(r.status,200,JSON.stringify(r.body));return r};
const V1META={registeredAt:'2026-03-15T10:00:00+09:00',validFrom:'2026-03-15',validUntil:'2027-06-30'};
const dvA=(await registerVersion('fr-a','가상 정보공개서 A','ra dvA',V1META)).body.result.id,dvB=(await registerVersion('fr-b','가상 정보공개서 B','ra dvB',V1META)).body.result.id;
const VERIFIED='2026-09-25T10:00:00+09:00',UNTIL_Q='2026-10-30T12:00:00+09:00',UNTIL_Y='2027-04-01T00:00:00+09:00';
const saveFact=async d=>{const r=await factPost(boss,{action:'save_fact',data:d,confirmed:true});assert.equal(r.status,200,JSON.stringify(r.body));return r.body};
const fact=(brandId,x)=>({brandId,status:'confirmed',source:'가상 정보공개서',verifiedAt:VERIFIED,...x});
const TOTAL_DATA=fact('fr-a',{key:'startup_cost_total',value:'4,500만원',validUntil:UNTIL_Q,sourceRef:{disclosureVersionId:dvA,fiscalYear:2025,page:12},cost:{storeType:'소형 매장',includes:['가맹비','교육비','인테리어'],excludes:['임차보증금','권리금'],areaM2:33}});
const COUNT_DATA=fact('fr-a',{key:'franchise_store_count',value:'12개',validUntil:UNTIL_Y,sourceRef:{disclosureVersionId:dvA,fiscalYear:2025,page:3,asOf:'2025-12-31'}});
const SALES_DATA=fact('fr-a',{key:'monthly_sales',value:'3,200만원',validUntil:UNTIL_Y,sourceRef:{disclosureVersionId:dvA,fiscalYear:2025,page:20}});
const A_TOTAL=await saveFact(TOTAL_DATA),A_COUNT=await saveFact(COUNT_DATA),A_SALES=await saveFact(SALES_DATA);
const B_COUNT=await saveFact(fact('fr-b',{key:'franchise_store_count',value:'40개',validUntil:UNTIL_Y,sourceRef:{disclosureVersionId:dvB,fiscalYear:2025,page:3,asOf:'2025-12-31'}}));
await server.recordStatement(WS,'store','st-a',{id:'st-a',brandId:'fr-a',name:'가상 지점'},'fr-a').run();
const S_FACT=await saveFact({brandId:'fr-a',storeId:'st-a',key:'parking',value:'매장 앞 2대',status:'confirmed',source:'대표 확인',verifiedAt:VERIFIED,validUntil:UNTIL_Y});
check('first saves of facts carry no reviewAssets key',[A_TOTAL,A_COUNT,A_SALES,B_COUNT,S_FACT].every(x=>!('reviewAssets' in x)&&x.version===1));
const campaign=(id,brandId,objective,title)=>server.recordStatement(WS,'campaign',id,{id,brandId,title,goal:'가상 목표',audience:'',channels:'',stores:'',products:'',budget:null,startDate:'',endDate:'',constraints:'',sources:'',status:'approved',version:1,createdAt:'2026-10-01T00:00:00.000Z',updatedAt:'2026-10-01T00:00:00.000Z',...(objective?{objective}:{})}).run();
for(const [id,b,o,t] of [['ca-a','fr-a','franchise_recruitment','가상 가맹 모집 A'],['ca-a2','fr-a','franchise_recruitment','가상 가맹 모집 A2'],['ca-cons','fr-a',null,'가상 소비자 캠페인'],['ca-b','fr-b','franchise_recruitment','가상 가맹 모집 B'],['ca-c','fr-c','franchise_recruitment','가상 가맹 모집 C'],['ca-l','fr-l','franchise_recruitment','가상 가맹 모집 L']])await campaign(id,b,o,t);
const artifact=(id,campaignId,status,version,origin)=>server.recordStatement(WS,'artifact',id,{id,campaignId,role:'cmo',title:'가상 작업물',content:'가상 작업물 본문',status,version,origin,createdAt:'2026-10-01T00:00:00.000Z'},campaignId).run();
await artifact('art-ai','ca-a','approved',2,'ai');await artifact('art-draft','ca-a','draft',1,'ai');await artifact('art-other','ca-a2','approved',1,'manual');

// ── 원문: assets 보기의 템플릿 + R15a-1 채움 문장 ──
let r=await get(member,'view=assets&brandId=fr-a');
const TPL=r.body.templates,TREFS=r.body.templateFactRefs;
const FOOT_A='※ 정보공개서 등록 버전 가상 정보공개서 A(등록일 2026-03-15) · 기준 사업연도 2025년 · 확인일 2026-09-25';
const COST_LINE='총 창업비용 · 소형 매장: 4,500만원';
check('I45: the startup page template carries the cost fact line and its footnote, and the template refs are the cost fact',r.status===200&&TPL.startup_page.includes(COST_LINE)&&TPL.startup_page.includes(FOOT_A)&&TPL.event_deck.includes(COST_LINE)&&JSON.stringify(TREFS)===JSON.stringify([{id:A_TOTAL.id,version:1}])&&r.body.costFactsMissing===false);
check('I45: the assets view lists recruitment campaigns, types, facts, rules and limits for any role',JSON.stringify(r.body.campaigns.map(c=>c.id).sort())==='["ca-a","ca-a2"]'&&r.body.types.length===7&&r.body.types[0].type==='startup_page'&&r.body.facts.some(x=>x.id===A_TOTAL.id&&x.hasSource===true&&x.line.startsWith(COST_LINE))&&!r.body.facts.some(x=>x.id===S_FACT.id)&&r.body.rules.checklistVersion===fa.CHECKLIST_VERSION&&r.body.limits.assetsPerBrand===100&&r.body.enabled===true&&r.body.role==='member'&&r.body.branch==='A'&&r.body.h7Notice===null&&r.body.disclaimer===DISCLAIMER);
const H=Object.fromEntries(fa.STARTUP_PAGE_SECTIONS.map(s=>[s.id,s.heading])),HD=Object.fromEntries(fa.EVENT_DECK_SECTIONS.map(s=>[s.id,s.heading]));
const after=(text,heading,lines)=>{assert.ok(text.includes(heading),heading);return text.replace(heading,()=>[heading,...lines].join('\n'))};
const FILL_WHY='매일 아침 굽는 도넛으로 동네 손님과 가까워진 브랜드입니다.',FILL_SUPPORT='오픈 첫 달 운영 교육을 지원합니다(계약 체결 가맹점, 개점일부터 30일간).',FILL_FAQ='Q. 가맹 상담은 어떻게 하나요? A. 문의 경로로 신청해 주세요.',FILL_CONTACT='창업 상담 신청서로 문의해 주세요.';
const page=(why=[],faq=[],tpl=TPL.startup_page)=>[['why',[FILL_WHY,...why]],['support',[FILL_SUPPORT]],['faq',[FILL_FAQ,...faq]],['contact',[FILL_CONTACT]]].reduce((t,[id,ls])=>after(t,H[id],ls),tpl);
const deck=story=>[['story',[FILL_WHY,...story]],['demo',['우유 도넛을 함께 맛보는 시간입니다.']],['support',[FILL_SUPPORT]]].reduce((t,[id,ls])=>after(t,HD[id],ls),TPL.event_deck);
const CHECK={version:fa.CHECKLIST_VERSION,checked:plain(fa.CHECKLIST_IDS)};
const save=(s,x)=>post(s,{action:'asset_save',brandId:'fr-a',campaignId:'ca-a',type:'startup_page',factRefs:TREFS,...x});
const portal=(s,body,x={})=>save(s,{type:'portal_intro',factRefs:[],body,...x});
const approve=(s,a,x={})=>post(s,{action:'asset_approve',brandId:'fr-a',assetId:a.assetId,version:a.version,bodyHash:a.bodyHash,checklist:CHECK,...x});
const exportAsset=(s,a,mode='copy',x={})=>post(s,{action:'asset_export',brandId:'fr-a',assetId:a.assetId,version:a.version,mode,...x});
const place=(s,a,x={})=>post(s,{action:'asset_place',brandId:'fr-a',assetId:a.assetId,version:a.version,label:'창업 포털',confirmedAt:kstDay(),...x});
const retire=(s,a,x={})=>post(s,{action:'asset_retire',brandId:'fr-a',assetId:a.assetId,version:a.version,...x});
const forgeApproval=a=>{patch(assetKey(a.assetId,a.version),'$.status','approved');patch(assetKey(a.assetId,a.version),'$.approval',{by:'ra-boss',role:'owner',at:iso(-60000),bodyHash:a.bodyHash,checklist:CHECK})};

// ════ C. 초안 저장 ════
const PAGE1=page();
r=await save(member,{body:PAGE1});
const P=r.body.result?.assetId;
let rowsP=assetRows(P);
check('C7: a member saves a new draft as version 1 of a brand row',r.status===200&&/^ra-/.test(P)&&r.body.result.version===1&&r.body.result.status==='draft'&&rowsP.length===1&&rowsP[0].key===assetKey(P,1)&&rowsP[0].parent==='fr-a'&&rowsP[0].status==='draft'&&rowsP[0].rev===1&&rowsP[0].savedBy.id==='ra-member'&&rowsP[0].savedBy.role==='member'&&rowsP[0].exportCount===0&&rowsP[0].source===null&&rowsP[0].aiGenerated===false&&rowsP[0].disclosureVersionId===dvA&&rowsP[0].campaignId==='ca-a');
check('C7: bodyHash is the SHA-256 of the stored body',rowsP[0].body===PAGE1&&rowsP[0].bodyHash===sha64(PAGE1)&&r.body.result.bodyHash===rowsP[0].bodyHash);
check('C7: the save response carries warnings, the rule version and the disclaimer',Array.isArray(r.body.warnings)&&r.body.ruleVersion===fa.ASSETS_VERSION&&r.body.disclaimer===DISCLAIMER);
const saveAudit=audits('asset_save').find(a=>a.recordId===P);
check('C7: the asset_save audit row holds id, version, hash and no body',!!saveAudit&&saveAudit.assetVersion===1&&saveAudit.bodyHash===rowsP[0].bodyHash&&saveAudit.aiGenerated===false&&saveAudit.actor.id==='ra-member'&&saveAudit.brandId==='fr-a'&&saveAudit.status===200&&saveAudit.target===null&&!JSON.stringify(saveAudit).includes(FILL_WHY)&&!('body' in saveAudit));
let snap=snapshot();
r=await save(member,{assetId:P,baseVersion:1,body:PAGE1});
check('C8: the same body and refs with baseVersion 1 is unchanged and writes nothing',r.status===200&&r.body.result.unchanged===true&&r.body.result.version===1&&snapshot()===snap);
const RID_SAVE='rq-save-dddddddddddd';
r=await portal(member,'재생 확인 초안',{requestId:RID_SAVE});
snap=snapshot();
const saveReplay=await portal(member,'재생 확인 초안',{requestId:RID_SAVE});
check('C8: replaying a new-asset save with the same requestId returns the stored result without a second asset',r.status===200&&saveReplay.status===200&&saveReplay.body.replayed===true&&JSON.stringify(saveReplay.body.result)===JSON.stringify(r.body.result)&&snapshot()===snap);
const TOKEN_BODY='가상본문토큰';
const PAGE2=page([TOKEN_BODY+'이 들어간 둘째 문장입니다.']);
r=await save(member,{assetId:P,baseVersion:1,body:PAGE2,campaignId:'ca-cons'});
rowsP=assetRows(P);
check('C9: a changed body makes version 2 and removes the never-approved version 1 draft',r.status===200&&r.body.result.version===2&&rowsP.length===1&&rowsP[0].version===2&&rowsP[0].body===PAGE2&&rowsP[0].rev===1&&rowsP[0].campaignId==='ca-a');
const P2=r.body.result;
snap=snapshot();
const stale1=await save(member,{assetId:P,baseVersion:1,body:page(['다른 문장'])}),stale2=await save(member,{assetId:P,body:page(['다른 문장'])});
check('C10: an old or missing baseVersion is 409 ASSET_STALE and writes nothing',fixed(stale1,409,'ASSET_STALE')&&fixed(stale2,409,'ASSET_STALE')&&snapshot()===snap);
// 교차 검토 C2: 문자열이 아닌 id는 '새 자료·새 행사'가 아니라 없는 행(404)이다.
const numAsset=await save(member,{assetId:12345,baseVersion:1,body:page(['숫자 id 확인'])});
const numEvent=await post(boss,{action:'event_save',brandId:'fr-a',eventId:777,version:1,campaignId:'ca-a',type:'tour',startsAt:'2026-10-20T14:00:00+09:00',placeLabel:'가상 직영점',capacity:5,spendRef:null,assetRefs:[]});
check('C10: a numeric assetId is 404 ASSET_NOT_FOUND and a numeric eventId is 404 EVENT_NOT_FOUND, both creating nothing',fixed(numAsset,404,'ASSET_NOT_FOUND')&&fixed(numEvent,404,'EVENT_NOT_FOUND')&&snapshot()===snap);
// 교차 검토 C1: 저장이 읽은 뒤 커밋 전에 잠금(120초)이 풀려 다른 요청이 끼어들어도 승인 판을 지우거나 다른 저장을 덮어쓰지 않는다.
r=await portal(member,FILL_WHY+' (잠금 만료 승인)');
const LA=r.body.result;let racedApprove=null;
raceCommit('asset_save',async()=>{expireLock();racedApprove=await approve(boss,LA)});
r=await portal(member,FILL_WHY+' (잠금 만료 승인 수정)',{assetId:LA.assetId,baseVersion:1});
const laRows=assetRows(LA.assetId);
check('C10: an approval that lands after the save read its draft makes the save 409 ASSET_STALE and the approved version stays',racedApprove?.status===200&&fixed(r,409,'ASSET_STALE')&&laRows.length===1&&laRows[0].version===1&&laRows[0].status==='approved'&&!audits('asset_save').some(a=>a.recordId===LA.assetId&&a.assetVersion===2));
r=await portal(member,'동시 저장 기준 초안');
const LB=r.body.result;let secondSave=null;
raceCommit('asset_save',async()=>{expireLock();secondSave=await portal(member2,'동시 저장 둘째 본문',{assetId:LB.assetId,baseVersion:1})});
const firstSave=await portal(member,'동시 저장 첫째 본문',{assetId:LB.assetId,baseVersion:1});
const lbRows=assetRows(LB.assetId);
check('C10: two saves on the same base version end as one 200 and one 409 ASSET_STALE and the winner body is kept',secondSave?.status===200&&secondSave.body.result.version===2&&fixed(firstSave,409,'ASSET_STALE')&&lbRows.length===1&&lbRows[0].version===2&&lbRows[0].body==='동시 저장 둘째 본문'&&lbRows[0].savedBy.id==='ra-member-2'&&audits('asset_save').filter(a=>a.recordId===LB.assetId&&a.assetVersion===2).length===1);
r=await portal(member,FILL_WHY+' (잠금 만료 새 판)');
const LC=r.body.result;
check('C10: the base of the new-version race approves',(await approve(boss,LC)).status===200);
const lcIntruder={...assetRow(LC.assetId,1),version:2,rev:4,exports:[{at:iso(),by:'ra-admin',role:'admin',bodyHash:LC.bodyHash,judgeVersion:'synthetic',assetsVersion:fa.ASSETS_VERSION,checklistVersion:fa.CHECKLIST_VERSION}],exportCount:1};
raceCommit('asset_save',()=>insertRow(assetKey(LC.assetId,2),'recruitment_asset','fr-a',lcIntruder));
r=await portal(member,FILL_WHY+' (잠금 만료 새 판 수정)',{assetId:LC.assetId,baseVersion:1});
check('C10: a version row written meanwhile is not overwritten (409 ASSET_STALE, its export record stays)',fixed(r,409,'ASSET_STALE')&&JSON.stringify(assetRow(LC.assetId,2))===JSON.stringify(lcIntruder)&&assetRow(LC.assetId,1).status==='approved');
sql.prepare('DELETE FROM records WHERE id=?').run(assetKey(LC.assetId,2));
snap=snapshot();
const otherFact=await portal(member,'도넛 가게 소개',{factRefs:[{id:B_COUNT.id,version:1}]}),storeFact=await portal(member,'도넛 가게 소개',{factRefs:[{id:S_FACT.id,version:1}]});
check('C11: another brand fact is 400 fact_other_brand and a store fact is 400 fact_store_scoped',codesAre(otherFact,400,'fact_other_brand')&&codesAre(storeFact,400,'fact_store_scoped')&&otherFact.body.disclaimer===DISCLAIMER&&snapshot()===snap);
const [cons,campB,campNone]=[await portal(member,'도넛 가게 소개',{campaignId:'ca-cons'}),await portal(member,'도넛 가게 소개',{campaignId:'ca-b'}),await portal(member,'도넛 가게 소개',{campaignId:'ca-none'})];
check('C12: a consumer campaign is 409 campaign_not_recruitment, another brand or missing campaign is 400 campaign_other_brand',codesAre(cons,409,'campaign_not_recruitment')&&codesAre(campB,400,'campaign_other_brand')&&codesAre(campNone,400,'campaign_other_brand')&&snapshot()===snap);
const [nul,long,badType]=[await portal(member,'도넛\u0000가게'),await portal(member,'가'.repeat(20001)),await portal(member,'도넛',{type:'poster'})];
check('C13: a NUL or 20,001-character body is 400 invalid_body and an unknown type is 400 invalid_type',codesAre(nul,400,'invalid_body')&&codesAre(long,400,'invalid_body')&&codesAre(badType,400,'invalid_type')&&snapshot()===snap);
r=await portal(member,'도넛 가게\r\n매일 굽습니다');
const CR=r.body.result,crRow=assetRow(CR.assetId,1);
check('C13: a CRLF body is stored with LF and hashed as stored',r.status===200&&crRow.body==='도넛 가게\n매일 굽습니다'&&crRow.bodyHash===sha64('도넛 가게\n매일 굽습니다')&&CR.bodyHash===crRow.bodyHash);
r=await portal(member,'출처 확인 초안',{source:{artifactId:'art-ai',version:2}});
const SRC=r.body.result;
check('C14: an approved current artifact of the same campaign is stored as the source and marks the draft AI-generated',r.status===200&&JSON.stringify(assetRow(SRC.assetId,1).source)==='{"artifactId":"art-ai","version":2,"origin":"ai"}'&&assetRow(SRC.assetId,1).aiGenerated===true&&audits('asset_save').find(a=>a.recordId===SRC.assetId).aiGenerated===true);
r=await portal(member,'출처 확인 초안 둘',{assetId:SRC.assetId,baseVersion:1});
check('C14: saving without a source key keeps the previous source',r.status===200&&r.body.result.version===2&&assetRow(SRC.assetId,2).source.artifactId==='art-ai'&&assetRow(SRC.assetId,2).aiGenerated===true);
snap=snapshot();
const badSources=[{artifactId:'art-other',version:1},{artifactId:'art-draft',version:1},{artifactId:'art-ai',version:1},{artifactId:'art-missing',version:1},{artifactId:'art-ai'},'art-ai'];
const sourceResults=[];for(const source of badSources)sourceResults.push(await portal(member,'출처 확인 초안 셋',{source}));
check('C14: another campaign, an unapproved or older artifact, a missing one or a malformed source is 400 SOURCE_INVALID and writes nothing',sourceResults.every(x=>fixed(x,400,'SOURCE_INVALID'))&&snapshot()===snap);
// 한도: 합성 행은 fr-l에 심고 끝나면 지운다.
for(let k=0;k<100;k++)insertRow(assetKey('ra-seed-'+k,1),'recruitment_asset','fr-l',{id:'ra-seed-'+k,brandId:'fr-l',version:1,status:'retired'});
snap=snapshot();
r=await post(member,{action:'asset_save',brandId:'fr-l',campaignId:'ca-l',type:'portal_intro',factRefs:[],body:'도넛 가게 소개'});
check('C15: with 100 assets in the brand a new asset is 409 LIMIT and writes nothing',fixed(r,409,'LIMIT')&&snapshot()===snap);
sql.prepare('DELETE FROM records WHERE id LIKE ?').run(`${WS}:recruitment_asset:ra-seed-%`);
r=await post(member,{action:'asset_save',brandId:'fr-l',campaignId:'ca-l',type:'portal_intro',factRefs:[],body:'도넛 가게 소개'});
const LIM=r.body.result,limRow=assetRow(LIM.assetId,1);
for(let v=2;v<=10;v++)insertRow(assetKey(LIM.assetId,v),'recruitment_asset','fr-l',{...limRow,version:v,status:'approved'});
snap=snapshot();
r=await post(member,{action:'asset_save',brandId:'fr-l',assetId:LIM.assetId,baseVersion:10,type:'portal_intro',factRefs:[],body:'도넛 가게 소개 둘'});
check('C15: with ten version rows a new version is 409 LIMIT and writes nothing',fixed(r,409,'LIMIT')&&snapshot()===snap);
patch(assetKey(LIM.assetId,10),'$.status','draft');
r=await post(member,{action:'asset_save',brandId:'fr-l',assetId:LIM.assetId,baseVersion:10,type:'portal_intro',factRefs:[],body:'도넛 가게 소개 둘'});
const limRows=assetRows(LIM.assetId);
check('C15: at ten rows a removable latest draft is replaced, so the new version saves and the row count stays ten',r.status===200&&r.body.result.version===11&&limRows.length===10&&!limRows.some(x=>x.version===10)&&limRows[limRows.length-1].version===11);
for(let k=0;k<200;k++)insertRow(`${WS}:recruitment_event:re-seed-${k}`,'recruitment_event','fr-l',{id:'re-seed-'+k,brandId:'fr-l',version:1,status:'scheduled'});
snap=snapshot();
r=await post(boss,{action:'event_save',brandId:'fr-l',campaignId:'ca-l',type:'tour',startsAt:'2026-10-20T14:00:00+09:00',placeLabel:'가상 직영점',capacity:5,spendRef:null,assetRefs:[]});
check('C15: with 200 events in the brand a new event is 409 LIMIT and writes nothing',fixed(r,409,'LIMIT')&&snapshot()===snap);
sql.prepare('DELETE FROM records WHERE id LIKE ?').run(`${WS}:recruitment_event:re-seed-%`);

// ════ B. 역할(직원 403) ════
snap=snapshot();
for(const [name,input] of [['asset_approve',{action:'asset_approve',assetId:P,version:2,bodyHash:P2.bodyHash,checklist:CHECK}],['asset_export',{action:'asset_export',assetId:P,version:2,mode:'copy'}],['asset_place',{action:'asset_place',assetId:P,version:2,label:'창업 포털',confirmedAt:kstDay()}],['asset_retire',{action:'asset_retire',assetId:P,version:2}],
 ['event_save',{action:'event_save',campaignId:'ca-a',type:'tour',startsAt:'2026-10-20T14:00:00+09:00',placeLabel:'가상 직영점',capacity:5,spendRef:null,assetRefs:[]}],['event_cancel',{action:'event_cancel',eventId:'re-x',version:1}]]){
 r=await post(member,{brandId:'fr-a',...input});
 check(`B4: member ${name} is 403 ADMIN_ONLY and writes nothing`,fixed(r,403,'ADMIN_ONLY')&&snapshot()===snap);
}

// ════ D. 승인 ════
snap=snapshot();
r=await approve(admin,P2,{checklist:{version:fa.CHECKLIST_VERSION,checked:plain(fa.CHECKLIST_IDS).slice(1)}});
check('D16: five checklist items is 400 checklist_incomplete and writes nothing',codesAre(r,400,'checklist_incomplete')&&snapshot()===snap);
r=await approve(admin,P2,{checklist:{version:'fr-assets-checklist@2026-09-01.1',checked:plain(fa.CHECKLIST_IDS)}});
const outdated=r;
r=await approve(admin,P2,{bodyHash:sha64('다른 원문')});
check('D16: an old checklist version is 409 checklist_outdated and another hash is 409 hash_mismatch',codesAre(outdated,409,'checklist_outdated')&&codesAre(r,409,'hash_mismatch'));
snap=snapshot();
r=await approve(admin,{...P2,version:1});
check('D16: a version that is not the latest is 409 ASSET_STALE and writes nothing',fixed(r,409,'ASSET_STALE')&&snapshot()===snap);
const DEPOSIT='오늘 예약금 100만원 입금하시면 상권을 선점해 드립니다';
r=await save(member,{body:page([],[DEPOSIT])});
const DEP=r.body.result;
check('D17: a draft with an unremovable sentence still saves',r.status===200&&DEP.status==='draft');
const blockedBefore=audits('asset_blocked').length,RID_BLOCK='rq-block-aaaaaaaaaaaa';
r=await approve(boss,DEP,{requestId:RID_BLOCK});
const blockRow=audits('asset_blocked').find(b=>b.recordId===DEP.assetId);
check('D17: approving it is 409 with hard_block among the reasons, the live error from the judge and the disclaimer',r.status===409&&codes(r).includes('hard_block')&&typeof r.body.error==='string'&&r.body.error!==T('ASSET_BLOCKED')&&r.body.disclaimer===DISCLAIMER&&r.body.ruleVersion===fa.ASSETS_VERSION);
check('D17: one asset_blocked audit row with status 409, reason codes and fixed texts only',audits('asset_blocked').length===blockedBefore+1&&!!blockRow&&blockRow.status===409&&blockRow.requestAction==='asset_approve'&&blockRow.assetVersion===1&&blockRow.reasons.includes('hard_block')&&blockRow.result.error===T('ASSET_BLOCKED')&&blockRow.result.reasons.every(x=>x.message===fa.ASSET_MESSAGES[x.code])&&!/예약금|입금|선점|100만원/.test(JSON.stringify(blockRow)));
snap=snapshot();
const replayBlock=await approve(boss,DEP,{requestId:RID_BLOCK});
check('D17: the same requestId replays the same 409 reasons with the fixed text and writes nothing',replayBlock.status===409&&replayBlock.body.replayed===true&&JSON.stringify(codes(replayBlock))===JSON.stringify(codes(r))&&replayBlock.body.error===T('ASSET_BLOCKED')&&snapshot()===snap);
const beforeApprove=assetRow(P,2);
r=await approve(boss,P2);
const approvedP=assetRow(P,2);
check('D18: the clean startup page from the template approves (200)',r.status===200&&r.body.result.status==='approved'&&r.body.result.version===2&&r.body.result.checklistVersion===fa.CHECKLIST_VERSION&&r.body.result.approvedAt===approvedP.approval.at&&r.body.aiGenerated===false&&r.body.disclaimer===DISCLAIMER);
check('D18: the row is approved by the owner with rev + 1 and an asset_approve audit row',approvedP.status==='approved'&&approvedP.approval.by==='ra-boss'&&approvedP.approval.role==='owner'&&approvedP.approval.bodyHash===P2.bodyHash&&approvedP.rev===beforeApprove.rev+1&&audits('asset_approve').some(a=>a.recordId===P&&a.assetVersion===2&&a.bodyHash===P2.bodyHash&&a.checklistVersion===fa.CHECKLIST_VERSION));
r=await post(member,{action:'asset_save',brandId:'fr-c',campaignId:'ca-c',type:'portal_intro',factRefs:[],body:'분기 B 초안'});
const CB=r.body.result;
check('D19: a branch B brand saves a draft',r.status===200&&CB.status==='draft');
r=await post(boss,{action:'asset_approve',brandId:'fr-c',assetId:CB.assetId,version:1,bodyHash:CB.bodyHash,checklist:CHECK});
const cView=await get(member,`view=asset&brandId=fr-c&assetId=${CB.assetId}`);
check('D19: approval in branch B is 409 branch_not_a and the asset view shows the branch B notice',codesAre(r,409,'branch_not_a')&&cView.status===200&&cView.body.branch==='B'&&cView.body.h7Notice===fa.H7_NOTICES.B);
const RR='수익률은 설명회에서 따로 말씀드려요 대략 25% 정도';
r=await save(member,{type:'event_deck',body:deck([RR])});
const RRD=r.body.result;
r=await approve(boss,RRD);
check('D20: a deck with a revenue-like figure is 409 spoken_revenue_figure at approval',RRD.status==='draft'&&codesAre(r,409,'spoken_revenue_figure'));
forgeApproval(RRD);
r=await exportAsset(admin,RRD);
check('D20: exporting a forged approval of the same deck is still 409 spoken_revenue_figure',codesAre(r,409,'spoken_revenue_figure'));
check('D20: the forged deck is retired',(await retire(boss,RRD)).status===200);
// 잠금 밖 재검토 표시가 읽은 뒤 끼어들면 조건부 쓰기 보호가 batch 전체를 되돌린다.
r=await portal(member,FILL_WHY+' (경합)');
const W=r.body.result;
const approveAudits=audits('asset_approve').length;
raceOnce(()=>patch(assetKey(W.assetId,1),'$.rev',5));
r=await approve(boss,W);
check('D: a write race between read and commit is 409 ASSET_STALE and rolls back the receipt',fixed(r,409,'ASSET_STALE')&&assetRow(W.assetId,1).status==='draft'&&assetRow(W.assetId,1).rev===5&&audits('asset_approve').length===approveAudits);
r=await approve(boss,W);
check('D: approving again after the race reads the new rev and succeeds',r.status===200&&assetRow(W.assetId,1).status==='approved'&&assetRow(W.assetId,1).rev===6);

// ════ E. 내보내기 ════
const RID_DRAFT_EXPORT='rq-export-draft-eeeeeee',blockedBeforeExport=audits('asset_blocked').length;
r=await exportAsset(admin,CR,'download',{requestId:RID_DRAFT_EXPORT});
const badMode=await exportAsset(admin,P2,'print');
check('E21: exporting a draft is 409 not_approved and an unknown mode is 400 EXPORT_MODE',codesAre(r,409,'not_approved')&&fixed(badMode,400,'EXPORT_MODE'));
const exportBlock=audits('asset_blocked').find(b=>b.requestAction==='asset_export'&&b.recordId===CR.assetId);
check('E21: the export 409 writes one asset_blocked receipt with reason codes and fixed texts only',audits('asset_blocked').length===blockedBeforeExport+1&&!!exportBlock&&exportBlock.status===409&&exportBlock.assetVersion===1&&JSON.stringify(exportBlock.reasons)==='["not_approved"]'&&exportBlock.result.error===T('ASSET_BLOCKED')&&Object.keys(exportBlock.result).sort().join()==='disclaimer,error,reasons,ruleVersion'&&exportBlock.result.reasons.every(x=>x.message===fa.ASSET_MESSAGES[x.code]));
snap=snapshot();
const exportBlockReplay=await exportAsset(admin,CR,'download',{requestId:RID_DRAFT_EXPORT});
check('E21: the same requestId replays the export 409 with the fixed text and writes nothing',exportBlockReplay.status===409&&exportBlockReplay.body.replayed===true&&JSON.stringify(codes(exportBlockReplay))==='["not_approved"]'&&exportBlockReplay.body.error===T('ASSET_BLOCKED')&&snapshot()===snap);
const RID_EXPORT='rq-export-bbbbbbbbbbbb';
r=await exportAsset(admin,P2,'download',{requestId:RID_EXPORT});
const exported=assetRow(P,2),firstExport=r;
check('E22: exporting the approved page returns the exact stored body with its hash',r.status===200&&r.body.body===exported.body&&sha64(r.body.body)===r.body.result.bodyHash&&r.body.result.bodyHash===exported.bodyHash&&r.body.result.mode==='download'&&r.body.result.exportedAt===exported.exports[0].at);
check('E22: the file name, content type and flags are fixed',/^recruitment-startup_page-fr-a-\d{8}-v2\.txt$/.test(r.body.filename)&&r.body.filename.includes(kstDay().replace(/-/g,''))&&r.body.contentType==='text/plain;charset=utf-8'&&r.body.aiGenerated===false&&r.body.disclaimer===DISCLAIMER&&Array.isArray(r.body.warnings));
check('E22: the row keeps one export record and exportCount 1',exported.exports.length===1&&exported.exports[0].by==='ra-admin'&&exported.exports[0].role==='admin'&&exported.exports[0].bodyHash===exported.bodyHash&&typeof exported.exports[0].judgeVersion==='string'&&exported.exportCount===1&&exported.rev===approvedP.rev+1);
const exportAudit=audits('asset_export').find(a=>a.recordId===P);
check('E22: the export audit row carries hash, mode and versions but no body',!!exportAudit&&exportAudit.bodyHash===exported.bodyHash&&exportAudit.mode==='download'&&exportAudit.assetVersion===2&&exportAudit.judgeVersion===exported.exports[0].judgeVersion&&exportAudit.checklistVersion===fa.CHECKLIST_VERSION&&exportAudit.aiGenerated===false&&!JSON.stringify(exportAudit).includes(TOKEN_BODY)&&!('body' in exportAudit.result));
snap=snapshot();
r=await exportAsset(admin,P2,'download',{requestId:RID_EXPORT});
check('E23: a replay within five minutes returns the same body without new export or audit rows',r.status===200&&r.body.replayed===true&&r.body.body===exported.body&&r.body.filename===firstExport.body.filename&&JSON.stringify(r.body.result)===JSON.stringify(firstExport.body.result)&&snapshot()===snap);
r=await exportAsset(member,P2,'download',{requestId:RID_EXPORT});
check('E23: another user replaying the request id starts a new request and a member is 403',fixed(r,403,'ADMIN_ONLY'));
sql.prepare("UPDATE auth_users SET role='member' WHERE id='ra-admin'").run();
r=await exportAsset(admin,P2,'download',{requestId:RID_EXPORT});
sql.prepare("UPDATE auth_users SET role='admin' WHERE id='ra-admin'").run();
check('E23: a replay by a user who is no longer an owner or admin is 409 REPLAY_EXPIRED',fixed(r,409,'REPLAY_EXPIRED')&&snapshot()===snap);
const exportAuditKey=sql.prepare("SELECT id FROM records WHERE kind='franchise_audit' AND json_extract(data,'$.action')='asset_export' AND json_extract(data,'$.recordId')=?").get(P).id;
patch(exportAuditKey,'$.bodyHash','0'.repeat(64));
r=await exportAsset(admin,P2,'download',{requestId:RID_EXPORT});
patch(exportAuditKey,'$.bodyHash',exported.bodyHash);
check('E23: a replay whose audit hash differs from the row is 409 REPLAY_EXPIRED',fixed(r,409,'REPLAY_EXPIRED'));
snap=snapshot();
setNow(nowMs()+6*60000);
r=await exportAsset(admin,P2,'download',{requestId:RID_EXPORT});
check('E23: after six minutes the replay is 409 REPLAY_EXPIRED',fixed(r,409,'REPLAY_EXPIRED')&&snapshot()===snap);
r=await portal(member,FILL_WHY+' (폐기 재생)');
const X=r.body.result;
check('E23: a second asset approves',(await approve(boss,X)).status===200);
const RID_X='rq-export-xxxxxxxxxxxx';
check('E23: the second asset exports',(await exportAsset(admin,X,'copy',{requestId:RID_X})).status===200);
check('E23: the second asset is retired',(await retire(admin,X)).status===200);
r=await exportAsset(admin,X,'copy',{requestId:RID_X});
check('E23: a replay after retirement is 409 REPLAY_EXPIRED',fixed(r,409,'REPLAY_EXPIRED'));
forgeApproval(DEP);
r=await exportAsset(admin,DEP);
check('E24: a forged approval of a hard_block body (hash and approval intact) is 409 hard_block at export',r.status===409&&codes(r).includes('hard_block'));
check('E24: the forged page is retired',(await retire(boss,DEP)).status===200);
r=await portal(member,FILL_WHY+' (내보내기 한도)');
const Y=r.body.result;
check('E25: the capped asset approves',(await approve(boss,Y)).status===200);
const RECS=Array.from({length:50},(_,k)=>({at:iso(-(50-k)*60000),by:'ra-admin',role:'admin',bodyHash:Y.bodyHash,judgeVersion:'synthetic',assetsVersion:fa.ASSETS_VERSION,checklistVersion:fa.CHECKLIST_VERSION}));
patch(assetKey(Y.assetId,1),'$.exports',RECS);patch(assetKey(Y.assetId,1),'$.exportCount',50);
r=await exportAsset(admin,Y);
const yRow=assetRow(Y.assetId,1);
check('E25: the 51st export keeps 50 records with the first one and counts 51',r.status===200&&yRow.exports.length===50&&yRow.exports[0].at===RECS[0].at&&yRow.exports[1].at===RECS[2].at&&yRow.exports[49].by==='ra-admin'&&yRow.exports[49].judgeVersion!=='synthetic'&&yRow.exportCount===51);
patch(assetKey(Y.assetId,1),'$.exportCount',70);
r=await exportAsset(admin,Y);
check('E25: exportCount keeps counting past the kept records',r.status===200&&assetRow(Y.assetId,1).exportCount===71&&assetRow(Y.assetId,1).exports.length===50&&assetRow(Y.assetId,1).exports[0].at===RECS[0].at);

// ════ G. 게시 위치·폐기 ════
r=await portal(member,FILL_WHY+' (게시)');
const Z=r.body.result;
check('G33: the placement asset approves',(await approve(boss,Z)).status===200);
r=await place(admin,Z);
check('G33: placing a version that was never exported is 409 not_exported',codesAre(r,409,'not_exported'));
check('G33: the placement asset exports',(await exportAsset(admin,Z)).status===200);
snap=snapshot();
const piiLabel=await place(admin,Z,{label:'문의 010-0000-0999'}),tomorrow=await place(admin,Z,{confirmedAt:kstDay(24*HOUR)});
check('G33: a label with a phone number is 400 PII_IN_TEXT and tomorrow is 400 invalid_placement, both writing nothing',fixed(piiLabel,400,'PII_IN_TEXT')&&codesAre(tomorrow,400,'invalid_placement')&&snapshot()===snap);
const PLACE_TOKEN='가상게시토큰';
r=await place(admin,Z,{label:'창업 포털 '+PLACE_TOKEN});
const placeAudit=audits('asset_place').find(a=>a.recordId===Z.assetId);
check('G33: a valid placement is recorded and its audit row has no label',r.status===200&&r.body.result.placements===1&&assetRow(Z.assetId,1).placements[0].label==='창업 포털 '+PLACE_TOKEN&&!!placeAudit&&placeAudit.placementCount===1&&!JSON.stringify(placeAudit).includes(PLACE_TOKEN));
r=await retire(admin,Z);
const zRow=assetRow(Z.assetId,1);
check('G34: retirement records who and when',r.status===200&&r.body.result.status==='retired'&&zRow.status==='retired'&&zRow.retiredBy.id==='ra-admin'&&zRow.retiredBy.role==='admin'&&typeof zRow.retiredAt==='string'&&audits('asset_retire').some(a=>a.recordId===Z.assetId&&a.assetVersion===1));
r=await exportAsset(admin,Z);
check('G34: exporting after retirement is 409 not_approved',codesAre(r,409,'not_approved'));
snap=snapshot();
r=await retire(admin,Z);
check('G34: retiring again is 200 unchanged and writes nothing',r.status===200&&r.body.result.unchanged===true&&snapshot()===snap);

// ════ H. 설명회·견학·박람회 ════
const EV=x=>({action:'event_save',brandId:'fr-a',campaignId:'ca-a',type:'tour',startsAt:'2026-10-12T14:00:00+09:00',placeLabel:'가상 직영점',capacity:2,spendRef:null,assetRefs:[],...x});
const register=(s,id,code,x={})=>post(s,{action:'event_register',brandId:'fr-a',eventId:id,...(code===undefined?{}:{code}),...x});
const attend=(s,id,x)=>post(s,{action:'event_attendance',brandId:'fr-a',eventId:id,...x});
const cancel=(s,id,version,x={})=>post(s,{action:'event_cancel',brandId:'fr-a',eventId:id,version,...x});
r=await post(boss,EV({brandId:'fr-c',campaignId:'ca-c'}));
check('H35: event_save in a branch B brand is 409 branch_not_a',codesAre(r,409,'branch_not_a'));
insertRow(assetKey('ra-fb',1),'recruitment_asset','fr-b',{...assetRow(Y.assetId,1),id:'ra-fb',brandId:'fr-b',campaignId:'ca-b'});
snap=snapshot();
const spend=await post(boss,EV({spendRef:'sp-1'})),piiPlace=await post(boss,EV({placeLabel:'문의 010-0000-0999'})),draftLink=await post(boss,EV({assetRefs:[{id:CR.assetId,version:1}]})),otherLink=await post(boss,EV({assetRefs:[{id:'ra-fb',version:1}]}));
check('H35: a spend reference is 400 SPEND_REF_UNAVAILABLE and a phone number in the place is 400 PII_IN_TEXT',fixed(spend,400,'SPEND_REF_UNAVAILABLE')&&fixed(piiPlace,400,'PII_IN_TEXT'));
check('H35: a draft link is 409 asset_not_approved and another brand approved link is 400 record_other_brand, all writing nothing',codesAre(draftLink,409,'asset_not_approved')&&codesAre(otherLink,400,'record_other_brand')&&snapshot()===snap);
r=await post(boss,EV({type:'briefing',startsAt:'2026-10-25T14:00:00+09:00',capacity:30,assetRefs:[{id:P,version:2}]}));
const BRIEF=r.body.result;
check('H35: a briefing without a deck saves with the missing-deck warning',r.status===200&&/^re-/.test(BRIEF.eventId)&&BRIEF.version===1&&BRIEF.status==='scheduled'&&r.body.warnings.includes(fa.ASSET_WARNING_MESSAGES.briefingDeckMissing)&&r.body.disclaimer===DISCLAIMER);
const briefRow=eventRow(BRIEF.eventId);
check('H35: the event row is a brand row with zero counts and the creator',briefRow.brandId==='fr-a'&&briefRow.campaignId==='ca-a'&&JSON.stringify(briefRow.counts)==='{"applied":0,"attended":0,"noShow":0}'&&briefRow.codes.length===0&&briefRow.createdBy.id==='ra-boss'&&JSON.stringify(briefRow.assetRefs)===JSON.stringify([{id:P,version:2}])&&audits('event_save').some(a=>a.recordId===BRIEF.eventId&&a.eventVersion===1));
r=await register(member,BRIEF.eventId,null);
const nullCodeAudit=audits('event_register').filter(a=>a.recordId===BRIEF.eventId);
check('H36: a registration with code null is 200 and its audit row says withCode false',r.status===200&&r.body.result.counts.applied===1&&nullCodeAudit.length===1&&nullCodeAudit[0].withCode===false&&eventRow(BRIEF.eventId).codes.length===0);
const PLACE_EV='가상행사장소토큰';
r=await post(admin,EV({placeLabel:'가상 직영점 '+PLACE_EV}));
const E2=r.body.result.eventId;
r=await register(member,E2,'LKB728BT');
check('H36: registering a pseudonymous code is 200 with applied 1',r.status===200&&r.body.result.counts.applied===1&&r.body.result.version===2);
r=await register(member,E2,'LKB728BT');
check('H36: the same code again is 409 code_duplicate',codesAre(r,409,'code_duplicate'));
r=await register(member,E2);
check('H36: a registration without a code is 200 with applied 2',r.status===200&&r.body.result.counts.applied===2);
snap=snapshot();
r=await register(member,E2,'LKC839CU');
check('H36: a third registration on capacity 2 is 409 capacity_full and the row is unchanged',codesAre(r,409,'capacity_full')&&snapshot()===snap);
const regAudit=audits('event_register').filter(a=>a.recordId===E2);
check('H36: registration audit rows note whether a code was given but never the code',regAudit.length===2&&regAudit.some(a=>a.withCode===true)&&regAudit.some(a=>a.withCode===false)&&!JSON.stringify(regAudit).includes('LKB728BT'));
r=await post(boss,EV({capacity:1,startsAt:'2026-10-25T10:00:00+09:00'}));
const E1=r.body.result.eventId;
const both=await Promise.all([register(member,E1,'LKD111AA'),register(member2,E1,'LKE222BB')]);
check('H37: two concurrent registrations on capacity 1 end as one 200 and one 409 (lock or capacity_full)',JSON.stringify(both.map(x=>x.status).sort())==='[200,409]'&&both.filter(x=>x.status===409).every(x=>x.body.error===LOCKED||codes(x).includes('capacity_full'))&&eventRow(E1).counts.applied===1);
r=await post(boss,EV({capacity:10}));
const E10=r.body.result.eventId;
sql.prepare('INSERT INTO mutation_locks(owner,token,expires_at) VALUES(?,?,?)').run(WS+':franchise','held-by-test',nowMs()+60000);
snap=snapshot();
r=await register(member,E10,'LKF333CC');
check('H38: a held franchise lock makes the registration 409 with the lock text and no write',r.status===409&&r.body.error===LOCKED&&snapshot()===snap);
sql.prepare('DELETE FROM mutation_locks WHERE owner=?').run(WS+':franchise');
const RID_REG='rq-register-cccccccccc';
r=await register(member,E10,'LKF333CC',{requestId:RID_REG});
snap=snapshot();
const regReplay=await register(member,E10,'LKF333CC',{requestId:RID_REG}),regReused=await register(member,E2,'LKF333CC',{requestId:RID_REG});
check('H39: the same requestId replays without a second registration and another event is 409 REQUEST_REUSED',r.status===200&&regReplay.status===200&&regReplay.body.replayed===true&&JSON.stringify(regReplay.body.result)===JSON.stringify(r.body.result)&&eventRow(E10).counts.applied===1&&fixed(regReused,409,'REQUEST_REUSED')&&snapshot()===snap);
raceOnce(()=>patch(`${WS}:recruitment_event:${E10}`,'$.version',40));
r=await register(member,E10,'LKM666GG');
check('H: a write race on the event row is 409 EVENT_STALE and the counts stay',fixed(r,409,'EVENT_STALE')&&eventRow(E10).counts.applied===1&&eventRow(E10).version===40);
const e2v=eventRow(E2).version;
const oldEdit=await post(boss,EV({eventId:E2,version:1,capacity:3})),below=await post(boss,EV({eventId:E2,version:e2v,capacity:1}));
check('H40: an old version is 409 EVENT_STALE and a capacity below the applications is 409 capacity_below_applied',fixed(oldEdit,409,'EVENT_STALE')&&codesAre(below,409,'capacity_below_applied')&&eventRow(E2).version===e2v);
r=await post(boss,EV({eventId:E2,version:e2v,campaignId:'ca-a2'}));
check('H40: moving an event to another campaign is 400 campaign_other_brand',codesAre(r,400,'campaign_other_brand'));
r=await post(boss,EV({eventId:E2,version:e2v,placeLabel:'가상 직영점 2층 '+PLACE_EV}));
check('H40: a valid edit bumps the version and keeps counts and codes',r.status===200&&r.body.result.version===e2v+1&&eventRow(E2).counts.applied===2&&eventRow(E2).codes.length===1&&eventRow(E2).placeLabel==='가상 직영점 2층 '+PLACE_EV);
r=await attend(member,E2,{version:eventRow(E2).version,attended:1,noShow:1,codes:[{code:'LKB728BT',state:'attended'}]});
check('H41: attendance before the event day (KST) is 400 attendance_before_event',codesAre(r,400,'attendance_before_event'));
setNow(Date.parse('2026-10-12T06:00:00Z'));
const e2Before=eventRow(E2);
r=await attend(member,E2,{version:e2Before.version,attended:1,noShow:1,codes:[{code:'LKB728BT',state:'attended'}]});
const e2After=eventRow(E2);
check('H41: on the event day attendance is 200 with counts, code states and a new version',r.status===200&&JSON.stringify(r.body.result.counts)==='{"applied":2,"attended":1,"noShow":1}'&&e2After.version===e2Before.version+1&&JSON.stringify(e2After.codes)==='[{"code":"LKB728BT","state":"attended"}]');
check('H41: the attendance audit row has counts and no code',audits('event_attendance').some(a=>a.recordId===E2&&JSON.stringify(a.eventCounts)==='{"applied":2,"attended":1,"noShow":1}'&&!JSON.stringify(a).includes('LKB728BT')));
const staleAttend=await attend(member,E2,{version:e2Before.version,attended:1,noShow:1}),unknownCode=await attend(member,E2,{version:e2After.version,attended:1,noShow:1,codes:[{code:'LKZ999ZZ',state:'attended'}]});
check('H41: an old version is 409 EVENT_STALE and an unknown code is 400 code_unknown',fixed(staleAttend,409,'EVENT_STALE')&&codesAre(unknownCode,400,'code_unknown'));
r=await register(member,E10,'LKG444DD');
check('H42: registering after the start is 409 event_started',codesAre(r,409,'event_started'));
r=await cancel(boss,E10,1);
check('H43: cancelling with an old version is 409 EVENT_STALE',fixed(r,409,'EVENT_STALE')&&eventRow(E10).status==='scheduled');
r=await cancel(boss,E10,eventRow(E10).version);
const e10=eventRow(E10);
check('H43: cancelling is 200 and records who and when',r.status===200&&r.body.result.status==='cancelled'&&e10.status==='cancelled'&&e10.cancelledBy.id==='ra-boss'&&typeof e10.cancelledAt==='string'&&audits('event_cancel').some(a=>a.recordId===E10&&a.eventVersion===e10.version));
r=await register(member,E10,'LKH555EE');
check('H43: registering on a cancelled event is 409 with event_cancelled',r.status===409&&codes(r).includes('event_cancelled'));
snap=snapshot();
r=await cancel(boss,E10,e10.version);
check('H43: cancelling again is 200 unchanged and writes nothing',r.status===200&&r.body.result.unchanged===true&&snapshot()===snap);
r=await get(member,'view=events&brandId=fr-a');
check('H44: followUps count scheduled events that started within 48 hours, with counts and no codes',r.status===200&&JSON.stringify(r.body.followUps)==='{"count":1,"attended":1,"noShow":1}');
check('H44: the events view lists rows newest first with labels and linked asset states',r.body.events.length===4&&r.body.events[0].id===BRIEF.eventId&&r.body.events.every(e=>typeof e.typeLabel==='string')&&r.body.events.find(e=>e.id===BRIEF.eventId).assetRefs[0].status==='approved'&&r.body.events.find(e=>e.id===BRIEF.eventId).assetRefs[0].type==='startup_page'&&r.body.approvedAssets.some(a=>a.id===P&&a.version===2&&a.latest===true)&&!r.body.approvedAssets.some(a=>a.id===Z.assetId)&&r.body.enabled===true&&r.body.disclaimer===DISCLAIMER);
setNow(Date.parse('2026-10-12T05:00:00Z')+49*HOUR);
r=await get(member,'view=events&brandId=fr-a');
check('H44: 49 hours after the start the follow-up count is 0',r.status===200&&r.body.followUps.count===0);

// ════ B. 직원 허용·다른 범위 ════
r=await post(boss,EV({startsAt:'2026-10-01T14:00:00+09:00',capacity:5}));
const PAST=r.body.result.eventId;
r=await attend(member,PAST,{version:1,attended:0,noShow:0});
const memberViews=await Promise.all([get(member,'view=assets&brandId=fr-a'),get(member,`view=asset&brandId=fr-a&assetId=${P}`),get(member,'view=events&brandId=fr-a')]);
check('B5: a member records attendance on a past event and reads the three views',r.status===200&&memberViews.every(v=>v.status===200));
await f.setFlag(boss2,true);
snap=snapshot();
const idor=[await retire(boss2,P2),await post(boss,{action:'asset_retire',brandId:'fr-b',assetId:P,version:2}),await post(boss,{action:'asset_retire',brandId:'fr-a',assetId:'bad id!',version:2})];
const idorEvents=[await cancel(boss2,E2,eventRow(E2).version),await post(boss,{action:'event_register',brandId:'fr-b',eventId:E2})];
const idorViews=[await get(boss2,`view=asset&brandId=fr-a&assetId=${P}`),await get(member,`view=asset&brandId=fr-b&assetId=${P}`)];
const noBrand=await post(boss,{action:'asset_save',brandId:'fr-none',campaignId:'ca-a',type:'portal_intro',factRefs:[],body:'x'});
check('B6: another workspace or brand asset is 404 ASSET_NOT_FOUND',idor.every(x=>fixed(x,404,'ASSET_NOT_FOUND'))&&idorViews.every(x=>fixed(x,404,'ASSET_NOT_FOUND')));
check('B6: another workspace or brand event is 404 EVENT_NOT_FOUND and a missing brand is 404',idorEvents.every(x=>fixed(x,404,'EVENT_NOT_FOUND'))&&noBrand.status===404&&snapshot()===snap);

// ════ A. 스위치·키 ════
r=await portal(member,'꺼짐 폐기 초안');
const OFFA=r.body.result,RID_W='rq-export-wwwwwwwwwwww';
check('A1: an approved asset exports before the switch goes off',(await exportAsset(admin,W,'copy',{requestId:RID_W})).status===200);
check('A1: the owner turns the switch off',(await f.setFlag(boss,false)).status===200);
snap=snapshot();
for(const [name,s,input] of [['asset_save',member,{action:'asset_save',campaignId:'ca-a',type:'portal_intro',factRefs:[],body:'x'}],['asset_approve',boss,{action:'asset_approve',assetId:OFFA.assetId,version:1,bodyHash:OFFA.bodyHash,checklist:CHECK}],
 ['asset_export',boss,{action:'asset_export',assetId:P,version:2,mode:'copy'}],['asset_place',boss,{action:'asset_place',assetId:P,version:2,label:'창업 포털',confirmedAt:kstDay()}],['event_save',boss,EV({})],['event_register',member,{action:'event_register',eventId:E1}],
 ['event_attendance',member,{action:'event_attendance',eventId:PAST,version:2,attended:1,noShow:0}]]){
 r=await post(s,{brandId:'fr-a',...input});
 check(`A1: switch off: ${name} is 409 OFF and writes nothing`,fixed(r,409,'OFF')&&snapshot()===snap);
}
r=await post(member,{action:'asset_approve',brandId:'fr-a',assetId:OFFA.assetId,version:1,bodyHash:OFFA.bodyHash,checklist:CHECK});
check('A2: switch off: a member approval is 409 OFF (switch before role)',fixed(r,409,'OFF')&&snapshot()===snap);
const offRetire=await retire(boss,OFFA),offCancel=await cancel(boss,E1,eventRow(E1).version);
check('A1: switch off: retirement and cancellation are 200',offRetire.status===200&&offRetire.body.result.status==='retired'&&offCancel.status===200&&eventRow(E1).status==='cancelled');
r=await exportAsset(admin,W,'copy',{requestId:RID_W});
check('A1: switch off: an export replay is 409 REPLAY_EXPIRED (the gate reads the switch again)',fixed(r,409,'REPLAY_EXPIRED'));
const offViews=await Promise.all([get(member,'view=assets&brandId=fr-a'),get(member,`view=asset&brandId=fr-a&assetId=${P}`),get(member,'view=events&brandId=fr-a')]);
check('A1: switch off: the three views read with enabled false',offViews.every(v=>v.status===200&&v.body.enabled===false));
check('A1: the owner turns the switch back on',(await f.setFlag(boss,true)).status===200);
const KEY=env.AGENCY_ENCRYPTION_KEY;delete env.AGENCY_ENCRYPTION_KEY;
const keyless=[await portal(member,'키 없는 초안'),await post(boss,EV({startsAt:'2026-10-25T16:00:00+09:00',capacity:3}))];
const keylessReg=await register(member,keyless[1].body.result?.eventId,'LKJ777HH'),keylessView=await get(member,'view=assets&brandId=fr-a'),keylessLead=await f.createLead(boss,'fr-a');
const KA=(await portal(member,FILL_WHY+' (키 없음)')).body.result,KE=keyless[1].body.result?.eventId;
const keylessRest=[await approve(boss,KA),await exportAsset(admin,KA),await place(admin,KA),await retire(admin,KA),await attend(member,PAST,{version:eventRow(PAST).version,attended:0,noShow:0}),await cancel(boss,KE,eventRow(KE).version)];
env.AGENCY_ENCRYPTION_KEY=KEY;
check('A3: without the contact key asset_save, event_save, event_register and GET assets are 200 while a lead action is 503',keyless.every(x=>x.status===200)&&keylessReg.status===200&&keylessView.status===200&&keylessLead.status===503&&keylessLead.body.error===T('KEY_MISSING'));
check('A3: without the contact key approve, export, place, retire, attendance and cancel are 200 too (all nine actions)',keylessRest.every(x=>x.status===200));

// ════ F. 사실·정보공개서 버전 변경 재검토 ════
const pBefore=assetRow(P,2);
r=await factPost(boss,{action:'save_fact',id:A_TOTAL.id,version:1,confirmed:true,data:{...TOTAL_DATA,sourceRef:{...TOTAL_DATA.sourceRef,page:13}}});
const pFlagged=assetRow(P,2);
check('F26: changing only the page of a referenced cost fact flags the approved asset',r.status===200&&r.body.version===2&&r.body.reviewPublications===0&&r.body.reviewAssets===1&&pFlagged.review.needed===true&&JSON.stringify(pFlagged.review.reasons)==='["fact_changed"]'&&typeof pFlagged.review.at==='string'&&pFlagged.rev===pBefore.rev+1&&pFlagged.status==='approved');
r=await exportAsset(admin,P2);
check('F26: exporting the flagged asset is 409 review_needed',codesAre(r,409,'review_needed'));
r=await portal(member,'가맹점 수 안내 초안',{factRefs:[{id:A_COUNT.id,version:1}]});
const Q=r.body.result;
r=await portal(member,'가맹점 수 안내 폐기본',{factRefs:[{id:A_COUNT.id,version:1}]});
const R=r.body.result;
check('F29: the retired referencing asset is retired first',Q.status==='draft'&&(await retire(boss,R)).status===200);
r=await factPost(boss,{action:'save_fact',id:A_COUNT.id,version:1,confirmed:true,data:{...COUNT_DATA,validUntil:'2027-04-15T00:00:00+09:00'}});
check('F27: extending only validUntil of a referenced fact flags the other asset',r.status===200&&r.body.reviewAssets===1&&assetRow(Q.assetId,1).review.needed===true);
check('F29: the draft is flagged and the retired version is not',assetRow(Q.assetId,1).status==='draft'&&assetRow(R.assetId,1).review.needed===false);
r=await factPost(boss,{action:'save_fact',id:A_SALES.id,version:1,confirmed:true,data:{...SALES_DATA,validUntil:'2027-04-10T00:00:00+09:00'}});
check('F28: changing an unreferenced fact has no reviewAssets key',r.status===200&&!('reviewAssets' in r.body));
const n1=await factPost(boss,{action:'save_fact',confirmed:true,data:{brandId:'fr-n',key:'signature_menu',value:'가상 우유 도넛',status:'confirmed',source:'대표 확인',verifiedAt:VERIFIED,validUntil:UNTIL_Y}});
const n2=await factPost(boss,{action:'save_fact',id:n1.body.id,version:1,confirmed:true,data:{brandId:'fr-n',key:'signature_menu',value:'가상 크림 도넛',status:'confirmed',source:'대표 확인',verifiedAt:VERIFIED,validUntil:UNTIL_Y}});
const nSaved=await server.readRecord(WS,'brand_fact',n1.body.id);
check('F28: a non-franchise fact update keeps the previous response bytes',n2.status===200&&n2.text===JSON.stringify({id:nSaved.id,version:2,fact:nSaved,warnings:[],reviewPublications:0}));
r=await save(member,{assetId:P,baseVersion:2,body:pBefore.body,factRefs:[{id:A_TOTAL.id,version:2}]});
check('F30: re-saving the same body with the current fact version makes a new draft without review, the old approval keeps its flag',r.status===200&&r.body.result.version===3&&assetRow(P,3).review.needed===false&&assetRow(P,3).status==='draft'&&assetRow(P,2).status==='approved'&&assetRow(P,2).review.needed===true&&assetRows(P).length===2);
// 다른 매장 유형의 창업비용 사실은 옛 버전에 남겨 둔다(옮기지 않는다): 버전이 current가 아니면 템플릿·templateFactRefs에서 빠져야 한다.
const CAFE=await saveFact({...TOTAL_DATA,value:'6,000만원',cost:{...TOTAL_DATA.cost,storeType:'카페형',areaM2:66}});
const pending=await registerVersion('fr-a','가상 정보공개서 A 변경','ra dvA2',{registeredAt:'2026-10-13T10:00:00+09:00',validFrom:'2026-10-16',validUntil:'2027-09-30'});
const dvA2=pending.body.result.id;
check('F31: registering a pending version changes no current version and adds no review keys',!('reviewAssets' in pending.body)&&!('reviewPublications' in pending.body)&&assetRow(P,3).review.needed===false);
setNow(Date.parse('2026-10-16T03:00:00Z'));
r=await factPost(boss,{action:'rebase_facts',brandId:'fr-a',disclosureVersionId:dvA2,items:[{id:A_TOTAL.id,version:2,fiscalYear:2025,page:13,verifiedAt:'2026-10-16T10:00:00+09:00',validUntil:UNTIL_Q}]});
check('F31: rebase_facts flags the draft that referenced the moved fact',r.status===200&&r.body.rebased===1&&r.body.reviewAssets>=1&&assetRow(P,3).review.needed===true&&assetRow(P,3).review.reasons.includes('fact_changed'));
r=await post(member,{action:'asset_save',brandId:'fr-b',campaignId:'ca-b',type:'portal_intro',factRefs:[{id:B_COUNT.id,version:1}],body:'가맹점 수 안내 B'});
const QB=r.body.result;
const regB2=await registerVersion('fr-b','가상 정보공개서 B 변경','ra dvB2',{registeredAt:'2026-10-15T10:00:00+09:00',validFrom:'2026-10-15',validUntil:'2027-09-30'});
check('F31: a version that replaces the current one flags assets on the old version with version_changed',QB.status==='draft'&&regB2.body.reviewAssets>=1&&regB2.body.reviewPublications===0&&assetRow(QB.assetId,1).review.reasons.includes('version_changed')&&assetRow(QB.assetId,1).review.reasons.includes('fact_changed'));
const fas=await f.load('lib/franchise-assets-server.ts');
const qKey=`${Q.assetId}:1`,qRow=assetRow(Q.assetId,1);
await env.DB.batch([fas.rowGuard(WS,'recruitment_asset',qKey,'$.rev',qRow.rev),server.recordStatement(WS,'recruitment_asset',qKey,{...qRow,rev:qRow.rev+1},'fr-a')]);
check('F32: rowGuard with the read rev lets the upsert through',assetRow(Q.assetId,1).rev===qRow.rev+1);
snap=snapshot();let guardError='';
try{await env.DB.batch([fas.rowGuard(WS,'recruitment_asset',qKey,'$.rev',qRow.rev),server.recordStatement(WS,'recruitment_asset',qKey,{...qRow,rev:99},'fr-a')])}catch(e){guardError=String(e?.message)}
check('F32: rowGuard with a stale rev fails with UNIQUE and rolls the batch back',/UNIQUE/.test(guardError)&&snapshot()===snap);
const staleReview=await fas.reviewStatement(WS,qKey,{needed:true,reasons:['fact_changed'],at:iso()},999,iso()).run();
check('F32: reviewStatement with a stale rev changes nothing',Number(staleReview.meta.changes)===0&&snapshot()===snap);
const mark1=await fas.markAssetsForChange(WS,'fr-a',{versionIds:[dvA]},iso()),mark2=await fas.markAssetsForChange(WS,'fr-a',{versionIds:[dvA]},iso());
check('F32: markAssetsForChange is idempotent (second call 0)',mark1>=1&&mark2===0&&assetRow(Q.assetId,1).review.reasons.includes('version_changed'));
r=await post(member,{action:'asset_save',brandId:'fr-b',campaignId:'ca-b',type:'portal_intro',factRefs:[],body:'재시도 확인 초안'});
const RT=r.body.result,rtKey=assetKey(RT.assetId,1);
let batches=0;
env.DB.batch=async stmts=>{if(!batches++)sql.prepare("UPDATE records SET data=json_set(data,'$.rev',7) WHERE id=?").run(rtKey);return realBatch(stmts)};
const retried=await fas.markAssetsForChange(WS,'fr-b',{versionIds:[regB2.body.result.id]},iso());
env.DB.batch=realBatch;
check('F32: a review mark that loses a race is re-read and applied once',retried===1&&batches===2&&assetRow(RT.assetId,1).rev===8&&assetRow(RT.assetId,1).review.reasons.includes('version_changed'));
check('F32: markAssetsForVersionChange with nothing changed is 0',await fas.markAssetsForVersionChange(WS,'fr-a',[],[],iso(),null,[])===0);

// ════ I. 보기·감사·연쇄 ════
r=await get(member,'view=assets&brandId=fr-a');
const hasKey=(o,k)=>!!o&&typeof o==='object'&&(Object.hasOwn(o,k)||Object.values(o).some(v=>hasKey(v,k)));
const pEntry=r.body.assets.find(a=>a.assetId===P);
check('I45: the assets view has no body key and no body token anywhere',r.status===200&&!hasKey(r.body,'body')&&!JSON.stringify(r.body).includes(TOKEN_BODY));
check('I45: latest and versions of the page are correct',!!pEntry&&pEntry.type==='startup_page'&&pEntry.typeLabel===fa.ASSET_TYPE_LABELS.startup_page&&pEntry.campaignTitle==='가상 가맹 모집 A'&&pEntry.campaignMissing===false&&pEntry.latest.version===3&&pEntry.latest.status==='draft'&&pEntry.latest.review.needed===true&&JSON.stringify(pEntry.versions)==='[{"version":3,"status":"draft","exportCount":0},{"version":2,"status":"approved","exportCount":1}]'&&r.body.assets[0].type==='startup_page');
const TPL2=r.body.templates.startup_page,TREFS2=r.body.templateFactRefs;
check('I45: the template follows the rebased cost fact and leaves out the cost fact on the superseded version',!TPL2.includes('카페형')&&r.body.facts.some(x=>x.id===CAFE.id)&&TPL2.includes('※ 정보공개서 등록 버전 가상 정보공개서 A 변경(등록일 2026-10-13) · 기준 사업연도 2025년 · 확인일 2026-10-16')&&JSON.stringify(TREFS2)===JSON.stringify([{id:A_TOTAL.id,version:3}]));
r=await save(member,{body:page([],[],TPL2).replace('\n\n'+H.contact+'\n'+FILL_CONTACT,''),factRefs:TREFS2});
const MISS=r.body.result;
r=await get(member,`view=asset&brandId=fr-a&assetId=${MISS.assetId}`);
check('I46: a draft missing a fixed section shows section_missing in the gate and the six-item checklist',r.status===200&&r.body.gate.reasons.some(x=>x.code==='section_missing'&&x.message===fa.ASSET_MESSAGES.section_missing)&&r.body.gate.status===409&&r.body.checklist.items.length===6&&r.body.checklist.version===fa.CHECKLIST_VERSION&&r.body.asset.body.length>0&&!('rev' in r.body.asset)&&r.body.latestVersion===1&&r.body.campaign.id==='ca-a');
r=await get(member,`view=asset&brandId=fr-a&assetId=${P}&version=2`);
check('I46: the flagged old approval shows the fact drift and suggests a new save',r.status===200&&r.body.asset.version===2&&r.body.drift[0].factId===A_TOTAL.id&&r.body.drift[0].refVersion===1&&r.body.drift[0].currentVersion===3&&r.body.drift[0].changed===true&&r.body.resaveSuggested===true&&r.body.latestVersion===3&&r.body.versions.length===2);
r=await get(member,`view=asset&brandId=fr-a&assetId=${SRC.assetId}`);
check('I46: the detail view reports the source and AI flag',r.status===200&&r.body.source.artifactId==='art-ai'&&r.body.aiGenerated===true&&r.body.asset.version===2);
r=await portal(member,'사실 없는 소개 초안');
const FL=r.body.result;
check('I46: a factless draft is saved on the current version',r.status===200&&assetRow(FL.assetId,1).disclosureVersionId===dvA2&&assetRow(FL.assetId,1).factRefs.length===0);
r=await post(boss,{action:'amend_disclosure_version',brandId:'fr-a',id:dvA2,version:1,reasonCode:'typo',label:'가상 정보공개서 A 변경(정정)'});
check('F31: amending the label of the current version flags assets saved on it with version_changed',r.status===200&&r.body.reviewAssets>=1&&assetRow(MISS.assetId,1).review.reasons.includes('version_changed'));
r=await get(member,`view=asset&brandId=fr-a&assetId=${FL.assetId}`);
check('I46: a factless draft flagged only by the label amendment still suggests a new save (no drift, version still current)',r.status===200&&r.body.asset.review.needed===true&&JSON.stringify(r.body.asset.review.reasons)==='["version_changed"]'&&r.body.drift.length===0&&!r.body.gate.reasons.some(x=>x.code==='version_not_current'||x.code==='fact_changed')&&r.body.resaveSuggested===true);
r=await get(admin,'view=audit&brandId=fr-a');
const NEW_ACTIONS=['asset_save','asset_approve','asset_export','asset_place','asset_retire','asset_blocked','event_save','event_cancel','event_register','event_attendance'];
const seenActions=new Set(r.body.audit.map(a=>a.action));
check('I47: the admin audit view lists the ten new actions with Korean labels',r.status===200&&NEW_ACTIONS.every(a=>seenActions.has(a))&&NEW_ACTIONS.every(a=>/[가-힣]/.test(f.lib.AUDIT_ACTION_LABELS[a])));
const auditJson=JSON.stringify(sql.prepare("SELECT data FROM records WHERE kind='franchise_audit'").all());
const TOKENS=[TOKEN_BODY,PLACE_TOKEN,PLACE_EV,'LKB728BT','LKF333CC','LKD111AA','LKE222BB','LKJ777HH',DEPOSIT,'예약금',RR,'가맹점 수 안내','출처 확인 초안',FILL_WHY];
check('I47: no audit row holds body text, place labels or pseudonymous codes',TOKENS.every(t=>!auditJson.includes(t)));
// 부분 유출(원문·라벨 앞머리 등)도 잡도록 자료·행사 감사 행의 키를 허용 목록으로 고정한다.
const AUDIT_KEYS=new Set(['id','brandId','action','actor','at','requestAction','status','result','target','recordId','assetVersion','bodyHash','mode','checklistVersion','judgeVersion','reasons','eventVersion','eventCounts','withCode','aiGenerated','placementCount']);
const assetAudits=()=>sql.prepare("SELECT data FROM records WHERE kind='franchise_audit'").all().map(x=>JSON.parse(x.data)).filter(a=>NEW_ACTIONS.includes(a.action));
const auditKeysOk=()=>assetAudits().every(a=>Object.keys(a).every(k=>AUDIT_KEYS.has(k)));
check('I47: every asset and event audit row carries only the allowed keys',assetAudits().length>=NEW_ACTIONS.length&&auditKeysOk());
r=await portal(member,FILL_WHY+' (삭제 캠페인)',{campaignId:'ca-a2'});
const AC=r.body.result;
check('I48: the asset of the second campaign approves',(await approve(boss,AC)).status===200);
const deleted=await server.deleteCampaign(WS,{id:'ca-a2',confirmed:true,version:1});
check('I48: deleting the campaign leaves the asset row',deleted.deleted===true&&assetRows(AC.assetId).length===1&&assetRows(AC.assetId)[0].status==='approved');
r=await exportAsset(admin,AC);
check('I48: exporting an asset of a deleted campaign is 400 campaign_other_brand',codesAre(r,400,'campaign_other_brand'));
await server.recordStatement(WS,'campaign','ca-arch',{id:'ca-arch',brandId:'fr-a',title:'가상 보관 모집',goal:'가상 목표',audience:'',channels:'',stores:'',products:'',budget:null,startDate:'',endDate:'',constraints:'',sources:'',status:'approved',version:1,objective:'franchise_recruitment',archivedAt:'2026-10-02T00:00:00.000Z',createdAt:'2026-10-01T00:00:00.000Z',updatedAt:'2026-10-02T00:00:00.000Z'}).run();
r=await get(member,'view=assets&brandId=fr-a');
const acEntry=r.body.assets.find(a=>a.assetId===AC.assetId);
check('I48: the assets view marks the deleted campaign and drops it from the campaign list',!!acEntry&&acEntry.campaignMissing===true&&acEntry.campaignTitle===null&&!r.body.campaigns.some(c=>c.id==='ca-a2'));
const archivedEvents=await get(member,'view=events&brandId=fr-a');
check('I48: an archived recruitment campaign is left out of the asset and event campaign lists',r.body.campaigns.some(c=>c.id==='ca-a')&&!r.body.campaigns.some(c=>c.id==='ca-arch')&&archivedEvents.status===200&&archivedEvents.body.campaigns.some(c=>c.id==='ca-a')&&!archivedEvents.body.campaigns.some(c=>c.id==='ca-arch'));
const FORBIDDEN=/법적으로 적합|준수 완료|합법/;
check('I49: no response and no new module makes a legal-adequacy claim',!responses.some(b=>FORBIDDEN.test(JSON.stringify(b)))&&!FORBIDDEN.test(readFileSync('lib/franchise-assets-server.ts','utf8')));
check('I49: the console holds no body text or pseudonymous code and no unexpected failure',TOKENS.every(t=>!logged.some(l=>l.includes(t)))&&!logged.some(l=>/franchise_request_failed|agency_request_failed|asset_flag_failed/.test(l)));
check('I49: no external call was made',f.calls.length===0);
const NEW_ERRORS={ASSET_NOT_FOUND:404,ASSET_STALE:409,ASSET_BLOCKED:409,EXPORT_MODE:400,SOURCE_INVALID:400,EVENT_NOT_FOUND:404,EVENT_STALE:409,SPEND_REF_UNAVAILABLE:400};
check('I49: the eight new fixed errors are Korean with 400, 404 or 409',Object.entries(NEW_ERRORS).every(([k,s])=>E[k]&&E[k].status===s&&/[가-힣]/.test(E[k].text)));

// ════ J. 교차 검토 보강: 커밋 경합·재생 대상·옛 판·행사 변경 경로 ════
// 1) 커밋 직전에 잠금 밖 재검토 표시(rev)나 다른 쓰기(행사 판)가 끼어들면 조건부 쓰기 보호가 batch를 되돌린다(행·영수증 그대로). 성공하면 rev·판이 1 오른다.
r=await portal(member,FILL_WHY+' (커밋 경합)');
const GR=r.body.result,grKey=assetKey(GR.assetId,1),grAudits=action=>audits(action).filter(a=>a.recordId===GR.assetId).length;
check('J: the commit-race asset approves and exports',(await approve(boss,GR)).status===200&&(await exportAsset(admin,GR)).status===200);
let grBefore=assetRow(GR.assetId,1),receiptsBefore=grAudits('asset_export');
raceCommit('asset_export',()=>bumpRev(grKey));
r=await exportAsset(admin,GR);
check('J: an export racing a review mark is 409 ASSET_STALE, keeps the export records and writes no receipt',fixed(r,409,'ASSET_STALE')&&assetRow(GR.assetId,1).rev===grBefore.rev+10&&assetRow(GR.assetId,1).exports.length===grBefore.exports.length&&assetRow(GR.assetId,1).exportCount===grBefore.exportCount&&grAudits('asset_export')===receiptsBefore);
grBefore=assetRow(GR.assetId,1);receiptsBefore=grAudits('asset_place');
raceCommit('asset_place',()=>bumpRev(grKey));
r=await place(admin,GR);
check('J: a placement racing a review mark is 409 ASSET_STALE with no placement and no receipt',fixed(r,409,'ASSET_STALE')&&assetRow(GR.assetId,1).placements.length===0&&assetRow(GR.assetId,1).rev===grBefore.rev+10&&grAudits('asset_place')===receiptsBefore);
grBefore=assetRow(GR.assetId,1);
r=await place(admin,GR);
check('J: a placement raises rev by one',r.status===200&&assetRow(GR.assetId,1).placements.length===1&&assetRow(GR.assetId,1).rev===grBefore.rev+1);
grBefore=assetRow(GR.assetId,1);receiptsBefore=grAudits('asset_retire');
raceCommit('asset_retire',()=>bumpRev(grKey));
r=await retire(admin,GR);
check('J: a retirement racing a review mark is 409 ASSET_STALE, the row stays approved and no receipt',fixed(r,409,'ASSET_STALE')&&assetRow(GR.assetId,1).status==='approved'&&assetRow(GR.assetId,1).rev===grBefore.rev+10&&grAudits('asset_retire')===receiptsBefore);
grBefore=assetRow(GR.assetId,1);
r=await retire(admin,GR);
check('J: a retirement raises rev by one',r.status===200&&assetRow(GR.assetId,1).status==='retired'&&assetRow(GR.assetId,1).rev===grBefore.rev+1);
r=await post(boss,EV({startsAt:'2026-10-15T14:00:00+09:00',capacity:5}));
const RE=r.body.result.eventId,reKey=evKey(RE),reAudits=action=>audits(action).filter(a=>a.recordId===RE).length;
let reBefore=eventRow(RE);receiptsBefore=reAudits('event_save');
raceCommit('event_save',()=>bumpVer(reKey));
r=await post(boss,EV({eventId:RE,version:reBefore.version,startsAt:'2026-10-15T14:00:00+09:00',capacity:6}));
check('J: an event edit racing another write is 409 EVENT_STALE and keeps the row',fixed(r,409,'EVENT_STALE')&&eventRow(RE).capacity===5&&eventRow(RE).version===reBefore.version+10&&reAudits('event_save')===receiptsBefore);
reBefore=eventRow(RE);receiptsBefore=reAudits('event_attendance');
raceCommit('event_attendance',()=>bumpVer(reKey));
r=await attend(member,RE,{version:reBefore.version,attended:0,noShow:0});
check('J: attendance racing another write is 409 EVENT_STALE (event text) and keeps the counts',fixed(r,409,'EVENT_STALE')&&JSON.stringify(eventRow(RE).counts)===JSON.stringify(reBefore.counts)&&eventRow(RE).version===reBefore.version+10&&reAudits('event_attendance')===receiptsBefore);
reBefore=eventRow(RE);receiptsBefore=reAudits('event_cancel');
raceCommit('event_cancel',()=>bumpVer(reKey));
r=await cancel(boss,RE,reBefore.version);
check('J: a cancellation racing another write is 409 EVENT_STALE and the event stays scheduled',fixed(r,409,'EVENT_STALE')&&eventRow(RE).status==='scheduled'&&eventRow(RE).version===reBefore.version+10&&reAudits('event_cancel')===receiptsBefore);
reBefore=eventRow(RE);
r=await cancel(boss,RE,reBefore.version);
check('J: a cancellation raises the event version by one',r.status===200&&r.body.result.version===reBefore.version+1&&eventRow(RE).status==='cancelled'&&eventRow(RE).version===reBefore.version+1);
// 2) 같은 요청 번호는 작업·브랜드·대상이 같을 때만 재생하고, 다른 자료·행사에 쓰면 REQUEST_REUSED 409다.
const RB1=(await portal(member,FILL_WHY+' (재생 대상 하나)')).body.result,RB2=(await portal(member,FILL_WHY+' (재생 대상 둘)')).body.result;
check('J: both replay-target assets approve and export',(await approve(boss,RB1)).status===200&&(await approve(boss,RB2)).status===200&&(await exportAsset(admin,RB1)).status===200&&(await exportAsset(admin,RB2)).status===200);
const RID_EXP='rq-reuse-export-aaaaaa',RID_PL='rq-reuse-place-aaaaaaa',RID_RT='rq-reuse-retire-aaaaaa',rb2Before=assetRow(RB2.assetId,1);
const reuse1=[await exportAsset(admin,RB1,'copy',{requestId:RID_EXP}),await place(admin,RB1,{requestId:RID_PL}),await retire(admin,RB1,{requestId:RID_RT})];
snap=snapshot();
const reuse2=[await exportAsset(admin,RB2,'copy',{requestId:RID_EXP}),await place(admin,RB2,{requestId:RID_PL}),await retire(admin,RB2,{requestId:RID_RT})];
check('J: reusing a requestId for export, place or retire on another asset is 409 REQUEST_REUSED and leaves that asset alone',reuse1.every(x=>x.status===200)&&reuse2.every(x=>fixed(x,409,'REQUEST_REUSED'))&&JSON.stringify(assetRow(RB2.assetId,1))===JSON.stringify(rb2Before)&&snapshot()===snap);
const RS=(await portal(member,'재생 대상 초안')).body.result,RID_SV='rq-reuse-save-aaaaaaaa',RID_NEW='rq-reuse-save-new-aaaa';
const sv1=await portal(member,'재생 대상 초안 둘',{assetId:RS.assetId,baseVersion:1,requestId:RID_SV});
snap=snapshot();
const sv2=await portal(member,'재생 대상 초안 둘',{assetId:RS.assetId,baseVersion:1,requestId:RID_SV});
check('J: resending an existing-asset save with the same requestId replays it',sv1.status===200&&sv1.body.result.version===2&&sv2.status===200&&sv2.body.replayed===true&&JSON.stringify(sv2.body.result)===JSON.stringify(sv1.body.result)&&snapshot()===snap);
const sv3=await portal(member,'재생 대상 새 초안',{requestId:RID_NEW});
snap=snapshot();
const sv4=await portal(member,'재생 대상 초안 셋',{assetId:RS.assetId,baseVersion:2,requestId:RID_NEW});
check('J: a new-asset save requestId sent again with an assetId is 409 REQUEST_REUSED',sv3.status===200&&fixed(sv4,409,'REQUEST_REUSED')&&snapshot()===snap);
const RID_EVN='rq-reuse-event-new-aaa',RID_EVE='rq-reuse-event-edit-aa',eventTotal=()=>Number(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='recruitment_event'").get().n),eventsBefore=eventTotal();
const ne1=await post(boss,EV({startsAt:'2026-11-20T14:00:00+09:00',capacity:5,requestId:RID_EVN})),ne2=await post(boss,EV({startsAt:'2026-11-20T14:00:00+09:00',capacity:5,requestId:RID_EVN}));
const NE=ne1.body.result?.eventId;
const ed1=await post(boss,EV({eventId:NE,version:1,startsAt:'2026-11-20T14:00:00+09:00',capacity:6,requestId:RID_EVE})),ed2=await post(boss,EV({eventId:NE,version:1,startsAt:'2026-11-20T14:00:00+09:00',capacity:6,requestId:RID_EVE}));
const ne3=await post(boss,EV({eventId:NE,version:eventRow(NE).version,startsAt:'2026-11-20T14:00:00+09:00',capacity:7,requestId:RID_EVN}));
check('J: a new event_save and an edit each replay with the same requestId, and the new-event requestId on an edit is 409 REQUEST_REUSED',ne1.status===200&&ne2.status===200&&ne2.body.replayed===true&&JSON.stringify(ne2.body.result)===JSON.stringify(ne1.body.result)&&ed1.status===200&&ed2.status===200&&ed2.body.replayed===true&&JSON.stringify(ed2.body.result)===JSON.stringify(ed1.body.result)&&fixed(ne3,409,'REQUEST_REUSED')&&eventTotal()===eventsBefore+1&&eventRow(NE).capacity===6&&eventRow(NE).version===2);
// 3) 옛 승인 판: 내보내기는 최신 판만(ASSET_STALE), 게시 위치 기록·폐기는 요청한 판에만 쓴다.
const OV=(await portal(member,FILL_WHY+' (옛 판)')).body.result;
check('J: the old-version asset approves and exports',(await approve(boss,OV)).status===200&&(await exportAsset(admin,OV)).status===200);
r=await portal(member,FILL_WHY+' (옛 판 둘)',{assetId:OV.assetId,baseVersion:1});
const OV2=r.body.result,ov1=assetRow(OV.assetId,1),ov2=assetRow(OV.assetId,2),ovExports=audits('asset_export').filter(a=>a.recordId===OV.assetId).length;
r=await exportAsset(admin,OV);
check('J: exporting an older approved version is 409 ASSET_STALE and adds no export record',OV2.version===2&&fixed(r,409,'ASSET_STALE')&&JSON.stringify(assetRow(OV.assetId,1))===JSON.stringify(ov1)&&audits('asset_export').filter(a=>a.recordId===OV.assetId).length===ovExports);
r=await place(admin,OV);
check('J: a placement is recorded on the older exported version and the new draft is untouched',r.status===200&&r.body.result.version===1&&assetRow(OV.assetId,1).placements.length===1&&JSON.stringify(assetRow(OV.assetId,2))===JSON.stringify(ov2));
r=await retire(admin,OV);
check('J: retiring the older version retires only that version',r.status===200&&r.body.result.version===1&&assetRow(OV.assetId,1).status==='retired'&&JSON.stringify(assetRow(OV.assetId,2))===JSON.stringify(ov2));
// 4) 행사 변경 경로도 장소 개인정보와 비용 참조를 막는다.
const GE=(await post(boss,EV({startsAt:'2026-11-25T14:00:00+09:00',capacity:5}))).body.result.eventId;
snap=snapshot();
const editPii=await post(boss,EV({eventId:GE,version:1,startsAt:'2026-11-25T14:00:00+09:00',capacity:5,placeLabel:'문의 010-0000-0999'})),editSpend=await post(boss,EV({eventId:GE,version:1,startsAt:'2026-11-25T14:00:00+09:00',capacity:5,spendRef:'sp-probe1'}));
check('J: an edit with a phone number in the place is 400 PII_IN_TEXT and one with a spend reference is 400 SPEND_REF_UNAVAILABLE, both writing nothing',fixed(editPii,400,'PII_IN_TEXT')&&fixed(editSpend,400,'SPEND_REF_UNAVAILABLE')&&eventRow(GE).version===1&&snapshot()===snap);

// ════ K. 재검토 훅 실패(명세 5.4)와 판 2 이상 사실 수정 ════
// 후보 조회(json_each factRefs)를 실패시키면 사실·버전 변경은 유지되고 reviewAssets:null과 고정 코드 한 줄만 남는다.
await f.brand(WS,'fr-h');
assert.equal((await f.profile(boss,'fr-h',{...FY,branch:'A'},0)).status,200);
const dvH=(await registerVersion('fr-h','가상 정보공개서 H','ra dvH',V1META)).body.result.id;
const H_DATA=fact('fr-h',{key:'franchise_store_count',value:'8개',validUntil:UNTIL_Y,sourceRef:{disclosureVersionId:dvH,fiscalYear:2025,page:3,asOf:'2025-12-31'}});
const H_COUNT=await saveFact(H_DATA);
await campaign('ca-h','fr-h','franchise_recruitment','가상 가맹 모집 H');
const hSave=(body,x={})=>post(member,{action:'asset_save',brandId:'fr-h',campaignId:'ca-h',type:'portal_intro',body,...x});
r=await hSave('가맹점 수 안내 H',{factRefs:[{id:H_COUNT.id,version:1}]});
const HA=r.body.result;
check('K: the hook brand has a draft on its fact',r.status===200&&HA.version===1);
const realPrepare=env.DB.prepare,flagLogs=()=>logged.filter(l=>/asset_flag_failed/.test(l));
const failHook=on=>{env.DB.prepare=on?q=>{if(String(q).includes("json_each(data,'$.factRefs')"))throw new Error('injected hook failure');return realPrepare(q)}:realPrepare};
let logsBefore=flagLogs().length;
failHook(true);
r=await factPost(boss,{action:'save_fact',id:H_COUNT.id,version:1,confirmed:true,data:{...H_DATA,sourceRef:{...H_DATA.sourceRef,page:4}}});
failHook(false);
let hFact=await server.readRecord(WS,'brand_fact',H_COUNT.id);
check('K: a failing review hook on save_fact keeps the saved fact and answers reviewAssets null',r.status===200&&r.body.version===2&&Object.hasOwn(r.body,'reviewAssets')&&r.body.reviewAssets===null&&hFact.version===2&&hFact.sourceRef.page===4&&assetRow(HA.assetId,1).review.needed===false&&flagLogs().length===logsBefore+1&&flagLogs().at(-1)==='fact_asset_flag_failed');
r=await hSave('가맹점 수 안내 H 둘',{assetId:HA.assetId,baseVersion:1,factRefs:[{id:H_COUNT.id,version:2}]});
check('K: the draft is re-saved on fact version 2',r.status===200&&r.body.result.version===2&&assetRow(HA.assetId,2).review.needed===false);
r=await factPost(boss,{action:'save_fact',id:H_COUNT.id,version:2,confirmed:true,data:{...H_DATA,sourceRef:{...H_DATA.sourceRef,page:5}}});
check('K: editing a fact already at version 2 flags the draft that references it with fact_changed',r.status===200&&r.body.version===3&&r.body.reviewAssets===1&&assetRow(HA.assetId,2).review.needed===true&&assetRow(HA.assetId,2).review.reasons.includes('fact_changed'));
r=await hSave('가맹점 수 안내 H 셋',{assetId:HA.assetId,baseVersion:2,factRefs:[{id:H_COUNT.id,version:3}]});
check('K: the draft is re-saved on fact version 3 without a review mark',r.status===200&&r.body.result.version===3&&assetRow(HA.assetId,3).review.needed===false&&assetRows(HA.assetId).length===1);
logsBefore=flagLogs().length;
failHook(true);
r=await post(boss,{action:'register_disclosure_version',brandId:'fr-h',label:'가상 정보공개서 H 변경',sha256:sha64('ra dvH2'),storageLabel:LABEL,registeredAt:'2026-10-16T10:00:00+09:00',validFrom:'2026-10-16',validUntil:'2027-10-30'});
failHook(false);
const dvH2=r.body.result?.id,hVersionIds=sql.prepare("SELECT json_extract(data,'$.id') AS id FROM records WHERE kind='franchise_disclosure_version' AND parent_id='fr-h'").all().map(x=>x.id);
check('K: a failing review hook on a replacing disclosure version keeps the version and answers reviewAssets null',r.status===200&&Object.hasOwn(r.body,'reviewAssets')&&r.body.reviewAssets===null&&typeof dvH2==='string'&&dvH2!==dvH&&hVersionIds.includes(dvH2)&&assetRow(HA.assetId,3).review.needed===false&&flagLogs().length===logsBefore+1&&flagLogs().at(-1)==='franchise_asset_flag_failed');
logsBefore=flagLogs().length;
failHook(true);
r=await factPost(boss,{action:'rebase_facts',brandId:'fr-h',disclosureVersionId:dvH2,items:[{id:H_COUNT.id,version:3,fiscalYear:2025,page:3,verifiedAt:'2026-10-16T10:00:00+09:00',validUntil:UNTIL_Y,asOf:'2025-12-31'}]});
failHook(false);
hFact=await server.readRecord(WS,'brand_fact',H_COUNT.id);
check('K: a failing review hook on rebase_facts keeps the moved fact and answers reviewAssets null',r.status===200&&r.body.rebased===1&&Object.hasOwn(r.body,'reviewAssets')&&r.body.reviewAssets===null&&hFact.version===4&&hFact.sourceRef.disclosureVersionId===dvH2&&assetRow(HA.assetId,3).review.needed===false&&flagLogs().length===logsBefore+1&&flagLogs().at(-1)==='fact_asset_flag_failed');
check('K: the three hook failure lines are fixed codes only',flagLogs().length===3&&flagLogs().every(l=>/^(fact|franchise)_asset_flag_failed$/.test(l)));

// ════ L. 교차 검토 C4: KST 자정을 넘는 내보내기 재생은 처음 내보낸 날의 파일 이름을 준다 ════
setNow(Date.parse('2026-10-16T14:58:00Z'));
r=await portal(member,FILL_WHY+' (자정 재생)');
const MN=r.body.result,RID_MN='rq-export-midnight-aaa';
check('L: the midnight asset approves',(await approve(boss,MN)).status===200);
const mn1=await exportAsset(admin,MN,'copy',{requestId:RID_MN});
setNow(Date.parse('2026-10-16T15:01:00Z'));
snap=snapshot();
const mn2=await exportAsset(admin,MN,'copy',{requestId:RID_MN});
check('L: a replay after KST midnight keeps the first file name and body and writes nothing',mn1.status===200&&mn1.body.filename.includes('-20261016-')&&mn2.status===200&&mn2.body.replayed===true&&mn2.body.filename===mn1.body.filename&&mn2.body.body===mn1.body.body&&snapshot()===snap);

// ════ 끝: 교차 검토 사례까지 포함한 감사 키·콘솔·외부 호출 ════
check('Z: every asset and event audit row, including the cross-review cases, carries only the allowed keys',auditKeysOk());
check('Z: the console holds no body text or pseudonymous code and no request failure, and no external call was made',TOKENS.every(t=>!logged.some(l=>l.includes(t)))&&!logged.some(l=>/franchise_request_failed|agency_request_failed/.test(l))&&!responses.some(b=>FORBIDDEN.test(JSON.stringify(b)))&&f.calls.length===0);

console.log(JSON.stringify({passed:passed.length}));
