import assert from 'node:assert/strict';
import {moduleRuntime} from '../scripts/eval/runtime.mjs';
const {load}=moduleRuntime(async()=>{throw Error('No network');});
const m=await load('lib/growth-inventory.ts');
let passed=0;
const test=(name,fn)=>{fn();passed++;console.log('passed: '+name);};
const now=Date.parse('2026-09-30T12:00:00Z');
const input=(onHand=10)=>({sku:'SKU-01',locationId:'warehouse-1',unit:'piece',onHand});
const event=(kind,quantity,overrides={})=>({id:'event-1',digest:'a'.repeat(64),version:1,kind,quantity,
  reservationId:'',missionId:'',orderId:'',observedAt:'2026-09-30T01:00:00Z',recordedAt:'2026-09-30T02:00:00Z',
  evidenceRef:'evidence-1',safeRelease:false,returnAccepted:false,disposition:'unknown',restock:false,...overrides});
const reserve=(quantity=6,overrides={})=>event('reserve',quantity,{reservationId:'reservation-1',missionId:'mission-1',...overrides});
const allocate=(quantity=4,overrides={})=>event('allocate',quantity,{version:2,id:'event-2',digest:'b'.repeat(64),reservationId:'reservation-1',missionId:'mission-1',orderId:'order-1',...overrides});
const ship=(quantity=3,overrides={})=>event('ship',quantity,{version:3,id:'event-3',digest:'c'.repeat(64),reservationId:'reservation-1',missionId:'mission-1',orderId:'order-1',...overrides});
const afterOrder=()=>[reserve(),allocate()];
const afterShip=()=>[...afterOrder(),ship()];
const project=(events=[],source=input())=>m.projectInventory(source,events,now);
const rejects=fn=>assert.throws(fn,m.GrowthInventoryError);

test('empty initial stock is unknown',()=>assert.equal(m.emptyInventoryInput().onHand,null));
test('initial physical quantity gives availability',()=>assert.equal(project().available,10));
test('unknown initial stock has unknown availability',()=>assert.equal(project([],input(null)).available,null));
test('stocktake establishes absolute stock',()=>assert.equal(project([event('stocktake',7)]).onHand,7));
test('zero stocktake is an explicit zero',()=>assert.equal(project([event('stocktake',0)]).onHand,0));
test('receive adds physical units',()=>assert.equal(project([event('receive',3)]).onHand,13));
test('receive cannot invent unknown base stock',()=>assert.equal(project([event('receive',3)],input(null)).onHand,null));
test('mission reservation reduces availability but not physical stock',()=>{const p=project([reserve()]);assert.equal(p.onHand,10);assert.equal(p.available,4);});
test('reservation at exact available boundary succeeds',()=>assert.equal(project([reserve(10)]).available,0));
test('overselling mission reservation rejected',()=>rejects(()=>project([reserve(11)])));
test('unknown stock blocks mission reservation',()=>rejects(()=>project([reserve()],input(null))));
test('reservation does not expire merely with elapsed time',()=>assert.equal(m.projectInventory(input(),[reserve()],Date.parse('2027-01-01T00:00:00Z')).reserved,6));
test('order allocation transfers mission hold without double counting',()=>{const p=project(afterOrder());assert.equal(p.reserved,6);assert.equal(p.reservations[0].held,2);assert.equal(p.orders[0].held,4);});
test('allocation beyond reserved mission amount preserves actual order',()=>{const p=project([reserve(),allocate(12)]);assert.equal(p.reserved,12);assert.equal(p.shortage,2);assert.equal(p.available,0);});
test('unreserved actual order may establish shortage',()=>{const p=project([allocate(12,{version:1,reservationId:'',missionId:''})]);assert.equal(p.orders[0].quantity,12);assert.equal(p.shortage,2);});
test('actual order against unknown physical stock remains recorded',()=>assert.equal(project([allocate(4,{version:1,reservationId:'',missionId:''})],input(null)).orders[0].held,4));
test('allocation rejects missing linked reservation',()=>rejects(()=>project([allocate(4,{version:1})])));
test('allocation cannot transfer another mission reservation',()=>rejects(()=>project([reserve(),allocate(4,{missionId:'foreign'})])));
test('shipment removes physical and order reserved units equally',()=>{const p=project(afterShip());assert.equal(p.onHand,7);assert.equal(p.reserved,3);assert.equal(p.available,4);});
test('shipment cannot exceed unshipped order hold',()=>rejects(()=>project([...afterOrder(),ship(5)])));
test('shipment cannot invent missing physical units',()=>rejects(()=>project([allocate(12,{version:1,reservationId:'',missionId:''}),ship(11,{version:2,reservationId:'',missionId:''})])));
test('shipment from unknown stock requires reconciliation',()=>rejects(()=>project([allocate(4,{version:1,reservationId:'',missionId:''}),ship(1,{version:2,reservationId:'',missionId:''})],input(null))));
test('safe mission release frees only its unallocated hold',()=>assert.equal(project([...afterOrder(),event('release',2,{version:3,id:'release-1',reservationId:'reservation-1',missionId:'mission-1',safeRelease:true})]).reserved,4));
test('release requires explicit safe cancellation',()=>rejects(()=>project([reserve(),event('release',1,{version:2,id:'release-1',reservationId:'reservation-1',missionId:'mission-1'})])));
test('mission release cannot release order hold',()=>rejects(()=>project([...afterOrder(),event('release',3,{version:3,id:'release-1',reservationId:'reservation-1',missionId:'mission-1',safeRelease:true})])));
test('safe order release only removes unshipped hold',()=>assert.equal(project([...afterShip(),event('release',1,{version:4,id:'release-1',reservationId:'reservation-1',missionId:'mission-1',orderId:'order-1',safeRelease:true})]).reserved,2));
test('release cannot undo already shipped units',()=>rejects(()=>project([...afterShip(),event('release',2,{version:4,id:'release-1',reservationId:'reservation-1',missionId:'mission-1',orderId:'order-1',safeRelease:true})])));
const orderEvent=(kind,quantity,overrides={})=>event(kind,quantity,{version:4,id:kind+'-1',reservationId:'reservation-1',missionId:'mission-1',orderId:'order-1',...overrides});
test('refund never restocks physical units',()=>{const p=project([...afterShip(),orderEvent('refund',2)]);assert.equal(p.onHand,7);assert.equal(p.orders[0].refunded,2);});
test('refund never releases remaining order hold',()=>assert.equal(project([...afterShip(),orderEvent('refund',4)]).orders[0].held,1));
test('refund cannot exceed total ordered units',()=>rejects(()=>project([...afterShip(),orderEvent('refund',5)])));
test('accepted resalable return requires explicit restock to add stock',()=>assert.equal(project([...afterShip(),orderEvent('return',2,{returnAccepted:true,disposition:'resalable',restock:true})]).onHand,9));
test('accepted resalable return without restock does not add stock',()=>assert.equal(project([...afterShip(),orderEvent('return',2,{returnAccepted:true,disposition:'resalable'})]).onHand,7));
test('accepted nonresalable return does not restock',()=>assert.equal(project([...afterShip(),orderEvent('return',2,{returnAccepted:true,disposition:'not_resalable'})]).onHand,7));
test('unaccepted return cannot restock',()=>rejects(()=>project([...afterShip(),orderEvent('return',2,{disposition:'resalable',restock:true})])));
test('unknown disposition cannot restock',()=>rejects(()=>project([...afterShip(),orderEvent('return',2,{returnAccepted:true,restock:true})])));
test('return cannot exceed shipped quantity',()=>rejects(()=>project([...afterShip(),orderEvent('return',4,{returnAccepted:true,disposition:'resalable',restock:true})])));
test('repeated returns cannot restore more than shipped',()=>rejects(()=>project([...afterShip(),orderEvent('return',2,{returnAccepted:true,disposition:'resalable',restock:true}),orderEvent('return',2,{version:5,id:'return-2',returnAccepted:true,disposition:'resalable',restock:true})])));
test('rejected return preserves stock and accepted return count',()=>{const p=project([...afterShip(),orderEvent('return',2)]);assert.equal(p.onHand,7);assert.equal(p.orders[0].returned,0);});
test('stocktake below commitments preserves true stock and shortage',()=>{const p=project([...afterOrder(),event('stocktake',1,{version:3,id:'count-1'})]);assert.equal(p.onHand,1);assert.equal(p.reserved,6);assert.equal(p.shortage,5);});
test('shortage blocks subsequent mission reservation',()=>rejects(()=>project([...afterOrder(),event('stocktake',1,{version:3,id:'count-1'}),reserve(1,{version:4,id:'reserve-2',reservationId:'reservation-2'})])));
test('identical duplicate event has no second effect',()=>assert.equal(project([reserve(),reserve()]).reserved,6));
test('same event id with altered quantity fails even with same digest',()=>rejects(()=>project([reserve(),reserve(5)])));
test('same event id with altered digest fails',()=>rejects(()=>project([reserve(),reserve(6,{digest:'b'.repeat(64)})])));
test('sequence gaps are rejected',()=>rejects(()=>project([reserve(6,{version:2})])));
test('duplicate reservation identity cannot create a second mission hold',()=>rejects(()=>project([reserve(),reserve(1,{version:2,id:'reserve-2'})])));
test('backdated stocktake cannot overwrite later ledger movement',()=>rejects(()=>project([reserve(),event('stocktake',50,{version:2,id:'count-1',observedAt:'2026-09-29T01:00:00Z'})])));
test('recorded timestamp cannot go backwards',()=>rejects(()=>project([reserve(),allocate(4,{recordedAt:'2026-09-30T01:59:59Z'})])));
test('observed timestamp cannot exceed recorded timestamp',()=>rejects(()=>project([reserve(6,{observedAt:'2026-09-30T03:00:00Z'})])));
test('future recorded timestamp rejected',()=>rejects(()=>project([reserve(6,{recordedAt:'2026-10-01T00:00:00Z'})])));
test('transition agrees with full ledger projection',()=>assert.equal(m.transitionInventory(input(),[reserve()],allocate(),now).reserved,project(afterOrder()).reserved));
test('all input and event objects remain unchanged',()=>{const i=input(),e=afterShip(),before=JSON.stringify([i,e]);project(e,i);assert.equal(JSON.stringify([i,e]),before);});
for(const quantity of [-1,0,1.1,NaN,Infinity,Number.MAX_SAFE_INTEGER+1,'1'])test('invalid receive quantity '+String(quantity)+' rejected',()=>rejects(()=>m.parseInventoryEvent(event('receive',quantity))));
test('unsupported unit rejected',()=>rejects(()=>m.parseInventoryInput({...input(),unit:'box'})));
test('null initial stock remains unknown after parsing',()=>assert.equal(m.parseInventoryInput(input(null)).onHand,null));
test('negative initial stock rejected',()=>rejects(()=>m.parseInventoryInput(input(-1))));
test('null stocktake quantity rejected',()=>rejects(()=>m.parseInventoryEvent(event('stocktake',null))));
test('malformed timestamp rejected',()=>rejects(()=>m.parseInventoryEvent(reserve(6,{observedAt:'2026-02-30T01:00:00Z'}))));
test('timezone-less timestamp rejected',()=>rejects(()=>m.parseInventoryEvent(reserve(6,{observedAt:'2026-09-30T01:00:00'}))));
test('evidence references cannot contain personal email',()=>rejects(()=>m.parseInventoryEvent(reserve(6,{evidenceRef:'person@example.com'}))));
test('identifiers cannot contain direct phone numbers',()=>rejects(()=>m.parseInventoryInput({...input(),locationId:'010-1234-5678'})));
test('malformed digest rejected',()=>rejects(()=>m.parseInventoryEvent(reserve(6,{digest:'bad'}))));
test('overflowing inbound quantity rejected',()=>rejects(()=>project([event('receive',Number.MAX_SAFE_INTEGER)])));
test('malformed clock rejected',()=>rejects(()=>m.projectInventory(input(),[],NaN)));
test('missing full event stream rejected',()=>rejects(()=>m.projectInventory(input(),null,now)));
test('non-object input rejected',()=>rejects(()=>m.parseInventoryInput(null)));
test('missing optional event flags default to false',()=>assert.equal(m.parseInventoryEvent({...reserve(),safeRelease:undefined}).safeRelease,false));
test('string release confirmation is not consent',()=>rejects(()=>m.parseInventoryEvent({...reserve(),safeRelease:'true'})));
test('missing observed timestamp rejected',()=>rejects(()=>m.parseInventoryEvent({...reserve(),observedAt:null})));
test('explicit valid timezone offset accepted',()=>assert.equal(project([reserve(6,{observedAt:'2026-09-30T10:00:00+09:00'})]).reserved,6));
test('invalid timezone offset rejected',()=>rejects(()=>m.parseInventoryEvent(reserve(6,{observedAt:'2026-09-30T01:00:00+14:01'}))));
test('missing reservation mission rejected',()=>rejects(()=>m.parseInventoryEvent(reserve(6,{missionId:''}))));
test('allocation requires order identity',()=>rejects(()=>m.parseInventoryEvent(allocate(4,{orderId:''}))));
test('release requires a target identity',()=>rejects(()=>m.parseInventoryEvent(event('release',1,{safeRelease:true}))));
test('refund cannot carry restock flags',()=>rejects(()=>m.parseInventoryEvent(orderEvent('refund',1,{returnAccepted:true,disposition:'resalable',restock:true}))));
test('stocktake cannot carry release consent',()=>rejects(()=>m.parseInventoryEvent(event('stocktake',1,{safeRelease:true}))));
test('mission allocation requires explicit reservation reference',()=>rejects(()=>project([allocate(1,{version:1,reservationId:''})])));
test('same order partial allocation accumulates without double mission hold',()=>{
  const p=project([...afterOrder(),allocate(2,{version:3,id:'allocation-2'})]);
  assert.equal(p.reserved,6);assert.equal(p.orders[0].quantity,6);assert.equal(p.reservations[0].held,0);
});
test('existing order cannot switch its reservation identity',()=>rejects(()=>project([...afterOrder(),allocate(1,{version:3,id:'allocation-2',reservationId:'',missionId:''})])));
test('shipment cannot switch existing order scope',()=>rejects(()=>project([...afterOrder(),ship(1,{missionId:'foreign'})])));
test('multiple orders preserve unrelated holds on shipment',()=>{
  const p=project([...afterOrder(),allocate(2,{version:3,id:'allocation-2',orderId:'order-2'}),ship(1,{version:4})]);
  assert.equal(p.orders.find(x=>x.orderId==='order-2').held,2);assert.equal(p.reserved,5);
});
test('sequential competing missions cannot reserve the same remaining stock',()=>rejects(()=>project([reserve(6),reserve(5,{version:2,id:'reserve-2',reservationId:'reservation-2',missionId:'mission-2'})])));
test('raw secret token is not an evidence reference',()=>rejects(()=>m.parseInventoryEvent(reserve(6,{evidenceRef:'sk-'+ 'a'.repeat(32)}))));
console.log(JSON.stringify({passed,failed:0,integration:'real pure stock ledger; no external calls'}));
