// Real SQLite / crypto / route gates, mocked provider HTTP, no live writes.
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
let calls=[],loseReply=false,readbackMismatch=false,denyWrite=false,failKind='',rejectRead=false;
let product={productId:'product',version:1,fields:{description:'원래 설명'}};
const digest=p=>createHash('sha256').update(JSON.stringify({fields:p.fields,version:p.version})).digest('hex');
const receipts=new Map();
const {load,sql,env}=testRuntime(async(url,options)=>{
 calls.push({url,body:JSON.parse(options.body)});const b=JSON.parse(options.body),action=url.split('/').at(-1);
 if(action==='read'){if(rejectRead)return Response.json({status:'rejected',code:'product_not_found'},{status:404});const p=readbackMismatch?{...product,version:product.version+1}:product;return Response.json({...p,digest:digest(p)})}
 if(action==='receipt')return Response.json(receipts.get(b.requestId)??null);
 if(denyWrite)return Response.json({status:'rejected',code:'stale_product'},{status:409});
 const pending=sql.prepare("SELECT data FROM records WHERE kind='growth_landing_revision' AND json_extract(data,'$.provider.attempt.requestId')=?").get(b.requestId);
 assert.equal(JSON.parse(pending.data).provider.attempt.status,'unknown','intent persisted before external write');
 if(digest(product)!==b.expectedDigest)return Response.json({status:'rejected',code:'stale_product'},{status:409});
 const beforeDigest=digest(product);
 product={...product,version:product.version+1,fields:action==='apply'?b.fields:{description:'원래 설명'}};
 const receipt={requestId:b.requestId,productId:'product',beforeDigest,afterDigest:digest(product),approvalDigest:b.approvalDigest,operation:action,at:new Date().toISOString(),status:'applied',...(action==='rollback'?{originalRequestId:b.originalRequestId}:{})};
 receipts.set(b.requestId,receipt);if(loseReply)throw Error('connection lost after commit');return Response.json(receipt);
},{beforeRun(s){if(failKind&&s.values[2]===failKind&&s.query.startsWith('INSERT INTO records'))throw Error('injected storage failure')}});
const server=await load('lib/server.ts'),route=await load('app/api/growth/landing/route.ts'),growth=await load('app/api/growth/route.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='owner',headers={'oai-authenticated-user-id':owner,origin:'https://agency.test'},c={id:'c',brandId:'b',storeId:'store',version:1,status:'active'};
const put=(kind,id,data,parent='')=>server.recordStatement(owner,kind,id,data,parent).run();
await put('campaign','c',c);await put('store','store',{id:'store',brandId:'b',status:'active'},'b');
const before=new Date(Date.now()-86400000).toISOString(),after=new Date(Date.now()+86400000*30).toISOString();
const grant={id:'grant',brandId:'b',campaignId:'c',campaignVersion:1,version:1,input:{id:'grant',brandId:'b',campaignId:'c',accountId:'mapdal:store',channel:'storefront',status:'active',maxTier:'T2',allowedActions:['publish'],ownerApprovalId:'approval',ownerSignedAt:before,startsAt:before,expiresAt:after,periodStart:before,periodEnd:after,totalCap:0,dayCap:0,weekCap:0,lossCap:0}};
await put('growth_authority','grant',grant,'c');
for(const [action,id,input] of [
 ['save_catalog','cat',{sku:'SKU',title:'상품',price:10000,unitCost:2000,variableCost:1000,stock:0,stockUnit:'piece',currency:'KRW',taxBasis:'included',fulfillment:'배송',refunds:'반품',rightsConfirmed:true,factIds:[],validUntil:after.slice(0,10)}],
 ['save_offer','offer',{title:'오퍼',catalogId:'cat',catalogVersion:1,needId:'',price:10000,quantity:1,landingUrl:'https://mapdal.kr/p/product',purchaseReason:'준비 단축',priceApproved:true}],
 ]){const res=await growth.POST(new Request('https://agency.test/api/growth',{method:'POST',headers,body:JSON.stringify({action,id,input,campaignId:'c',campaignVersion:1,expectedVersion:0})}));assert.equal(res.status,200,await res.text())}
const post=async(b,h=headers)=>{const r=await route.POST(new Request('https://agency.test/api/growth/landing',{method:'POST',headers:h,body:JSON.stringify({campaignId:'c',campaignVersion:1,requestId:randomUUID(),...b})}));return {status:r.status,body:await r.json()}};
const get=async()=>{const r=await route.GET(new Request('https://agency.test/api/growth/landing?campaignId=c',{headers}));assert.equal(r.status,200);return r.json()};
const secret='synthetic-test-secret-with-32-bytes',config={baseUrl:'https://mapdal.kr',tenantId:'tenant',providerStoreId:'provider-store',secret};
let r=await post({action:'provider_configure',expectedVersion:0,input:config});
check(r.status===200,'owner saves encrypted disabled configuration');
let view=await get();check(view.providerConnection.enabled===false&&!JSON.stringify(view).includes(secret)&&!JSON.stringify(view).includes('secret'),'write only configuration projection');
const stored=sql.prepare("SELECT data FROM records WHERE kind='channel_credential' AND json_extract(data,'$.channel')='growth_landing_provider'").get();check(!stored.data.includes(secret),'secret encrypted at rest');
check((await post({action:'provider_configure',expectedVersion:1,input:{...config,baseUrl:'https://127.0.0.1'}})).status===400,'SSRF config denied');
check((await post({action:'provider_enable',expectedVersion:1,installed:true,evidenceRef:'bridge-install'})).status===200,'explicit installed acknowledgement enables adapter');
const proposal={title:'상품 설명 교체',offerId:'offer',offerVersion:1,journeyId:'',journeyVersion:0,landingUrl:'https://mapdal.kr/p/product',rationale:'구매 이유 명확화',rollbackPlan:'기존 설명 복원',sections:[{kind:'purchase_reason',before:'원래 설명',after:'새 설명',factIds:[]}]};
const act=(action,version,extra={})=>post({action,id:'revision',expectedVersion:version,...extra});
check((await act('save_proposal',0,{input:proposal})).status===200,'draft saved');
check((await act('provider_bind',1,{productId:'different',authorityId:'grant',authorityVersion:1})).status===409,'exact public product URL identity required');
check((await act('provider_bind',1,{productId:'product',authorityId:'grant',authorityVersion:1})).status===200,'provider product snapshot bound');
check((await act('approve',2)).status===200,'binding included in approval');
const approval=(await get()).proposals[0].approval.digest;
await put('growth_authority','grant',{...grant,version:2},'c');const initial=calls.length;
check((await act('provider_apply',3,{confirm:true})).status===409&&calls.length===initial,'stale authority blocks before provider call');
await put('growth_authority','grant',grant,'c');
await put('growth_stop','global',{id:'global',version:1,status:'stopped',reason:'stop',updatedAt:before,updatedBy:owner});
check((await act('provider_apply',3,{confirm:true})).status===409&&calls.length===initial,'global stop blocks before provider call');sql.prepare("DELETE FROM records WHERE kind='growth_stop'").run();
failKind='growth_landing_revision_history';check((await act('provider_apply',3,{confirm:true})).status===500&&calls.length===initial,'intent transaction failure does not dispatch');failKind='';
loseReply=true;const requestId=randomUUID(),apply={action:'provider_apply',id:'revision',expectedVersion:3,requestId,confirm:true};
r=await post(apply);check(r.status===200&&r.body.providerStatus==='unknown','lost provider reply stays unknown');
check(receipts.get(requestId).approvalDigest===approval,'sent exact approved digest');
view=await get();check(view.proposals[0].status==='approved'&&view.proposals[0].provider.attempt.status==='unknown','unknown never claims applied');
const writes=calls.filter(x=>x.url.endsWith('/apply')).length;
check((await post(apply)).body.duplicate&&calls.filter(x=>x.url.endsWith('/apply')).length===writes,'same request replay never resends');
check((await act('provider_apply',4,{confirm:true})).status===409,'new request cannot bypass unknown');
check((await act('record_applied',4,{receipt:{at:new Date().toISOString(),evidenceRef:'manual',observedUrl:proposal.landingUrl,reason:''}})).status===409,'manual receipt cannot overwrite provider attempt');
readbackMismatch=true;r=await act('provider_reconcile',4);check(r.status===200&&r.body.providerStatus==='unknown','receipt alone cannot override readback mismatch');
check(r.body.version===4,'unchanged unknown lookup does not create a new revision');
readbackMismatch=false;r=await act('provider_reconcile',4);check(r.status===200&&r.body.providerStatus==='verified','receipt and exact readback reconcile');
view=await get();check(view.proposals[0].status==='applied'&&view.proposals[0].pageChanged==='provider_verified','provider verified distinguished from operator attested');
check(calls.filter(x=>x.url.endsWith('/apply')).length===writes,'reconcile performs reads only');
loseReply=false;r=await act('provider_rollback',5,{confirm:true,reason:'승인한 원본 복원'});check(r.status===200&&r.body.providerStatus==='verified','CAS rollback verified');
check(product.fields.description==='원래 설명'&&(await get()).proposals[0].status==='rolled_back','original fields restored');
check((await post({action:'provider_disable',expectedVersion:2})).status===200,'owner can disable provider');
view=await get();check(!view.providerConnection.enabled,'disabled state reloaded');
check(!JSON.stringify(view).includes(secret),'all history and UI remain secret free');
check((await post({action:'provider_enable',expectedVersion:3,installed:true,evidenceRef:'bridge-install'})).status===200,'reenable requires new connection version');
product={productId:'product',version:10,fields:{description:'원래 설명'}};
const make=async id=>{for(const data of [{action:'save_proposal',expectedVersion:0,input:proposal},{action:'provider_bind',expectedVersion:1,productId:'product',authorityId:'grant',authorityVersion:1},{action:'approve',expectedVersion:2}]){const r=await post({id,...data});assert.equal(r.status,200,JSON.stringify(r.body));}};
await make('readback-failure');rejectRead=true;
r=await post({action:'provider_apply',id:'readback-failure',expectedVersion:3,confirm:true});
check(r.status===200&&r.body.providerStatus==='unknown','readback404 after accepted mutation must remain unknown, not rejected');
rejectRead=false;
check((await post({action:'provider_configure',expectedVersion:4,input:config})).status===409,'unknown attempt blocks replacing provider identity or key');
const lostRequest=(await get()).proposals.find(p=>p.id==='readback-failure').provider.attempt.requestId,savedReceipt=receipts.get(lostRequest);receipts.delete(lostRequest);
check((await post({action:'provider_reconcile',id:'readback-failure',expectedVersion:4})).body.providerStatus==='unknown','null receipt is not final rejection evidence');
receipts.set(lostRequest,savedReceipt);
check((await post({action:'provider_reconcile',id:'readback-failure',expectedVersion:4})).body.providerStatus==='verified','later receipt recovers without mutation');
product={productId:'product',version:20,fields:{description:'원래 설명'}};await make('stale-source');
const catalogRow=JSON.parse(sql.prepare("SELECT data FROM records WHERE kind='growth_catalog'").get().data);
await put('growth_catalog','cat',{...catalogRow,version:2},'c');const beforeSourceCalls=calls.length;
check((await post({action:'provider_apply',id:'stale-source',expectedVersion:3,confirm:true})).status===409&&calls.length===beforeSourceCalls,'source drift prevents external calls');
await put('growth_catalog','cat',catalogRow,'c');
await put('growth_catalog','cat',{...catalogRow,input:{...catalogRow.input,validUntil:'2001-01-01'}},'c');
check((await post({action:'provider_apply',id:'stale-source',expectedVersion:3,confirm:true})).status===409&&calls.length===beforeSourceCalls,'expired source prevents external calls');await put('growth_catalog','cat',catalogRow,'c');
env.AUTH_MODE='email';env.AUTH_ORIGIN='https://agency.test';
sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run('workspace-owner','owner@test.invalid',owner,'admin','active',0);
for(const role of ['admin','member']){
 const token=createHash('sha256').update('landing-provider-'+role).digest('hex');
 sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run(role,role+'@test.invalid',owner,role,'active',1);
 sql.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?)').run(createHash('sha256').update(token).digest('hex'),role,Date.now()+60000,Date.now());
 const h={cookie:'__Host-collective_session='+token,origin:'https://agency.test'};
 check((await post({action:'provider_disable',expectedVersion:4},h)).status===403,'configuration owner only '+role);
 check((await post({action:'provider_apply',id:'stale-source',expectedVersion:3,confirm:true},h)).status===403,'execution owner only '+role);
}
env.AUTH_MODE='legacy';
product={productId:'product',version:100,fields:{description:'원래 설명'}};await make('recovery');
check((await post({action:'provider_apply',id:'recovery',expectedVersion:3,confirm:true})).body.providerStatus==='verified','recovery fixture applied');
const approvedDigest=(await get()).proposals.find(p=>p.id==='recovery').approval.digest;
await post({action:'provider_disable',expectedVersion:4});await post({action:'provider_enable',expectedVersion:5,installed:true,evidenceRef:'bridge-install'});
check((await post({action:'provider_rollback',id:'recovery',expectedVersion:5,confirm:true,reason:'원본 복원'})).status===409,'connection version drift requires explicit recovery approval');
const recoveryInput={action:'provider_approve_recovery',id:'recovery',expectedVersion:5,authorityId:'grant',authorityVersion:1,confirm:true};
check((await post({...recoveryInput,confirm:false})).status===409,'recovery approval requires explicit confirmation');
const originalProduct=product;product={...product,version:product.version+1};
check((await post(recoveryInput)).status===409,'recovery approval refuses intervening product edits');product=originalProduct;
const connectionRow=JSON.parse(sql.prepare("SELECT data FROM records WHERE kind='channel_credential' AND json_extract(data,'$.channel')='growth_landing_provider'").get().data);
await put('channel_credential',connectionRow.id,{...connectionRow,providerStoreId:'different-store'});
check((await post(recoveryInput)).status===409,'recovery approval cannot cross provider store identity');await put('channel_credential',connectionRow.id,connectionRow);
await put('growth_authority','grant',{...grant,input:{...grant.input,status:'revoked'}},'c');
check((await post(recoveryInput)).status===409,'recovery approval checks current authority revocation');await put('growth_authority','grant',grant,'c');
check((await post({action:'provider_approve_recovery',id:'recovery',expectedVersion:5,authorityId:'grant',authorityVersion:1,confirm:true})).status===200,'same identity reenabled connection supports recovery approval');
check((await get()).proposals.find(p=>p.id==='recovery').approval.digest===approvedDigest,'recovery approval preserves original approval digest');
check((await post({action:'provider_rollback',id:'recovery',expectedVersion:6,confirm:true,reason:'원본 복원'})).body.providerStatus==='verified','reapproved recovery can rollback after enable cycle');
product={productId:'product',version:200,fields:{description:'원래 설명'}};await make('capacity');loseReply=true;
check((await post({action:'provider_apply',id:'capacity',expectedVersion:3,confirm:true})).body.providerStatus==='unknown','capacity fixture has durable unknown');loseReply=false;
const pending=(await get()).proposals.find(p=>p.id==='capacity'),capacityReceipt=receipts.get(pending.provider.attempt.requestId);receipts.delete(pending.provider.attempt.requestId);
const countKind=kind=>sql.prepare('SELECT COUNT(*) n FROM records WHERE owner=? AND kind=? AND parent_id=?').get(owner,kind,'c').n;
for(const [kind,cap] of [['growth_landing_revision_history',2000],['growth_landing_revision_request',5000]])for(let i=countKind(kind);i<cap;i++)await put(kind,'capacity-fill-'+i,kind.endsWith('_history')?{...pending,id:'capacity-fill-'+i}: {digest:'fill',id:'capacity',version:4},'c');
for(let i=0;i<5;i++){const result=await post({action:'provider_reconcile',id:'capacity',expectedVersion:4});check(result.status===200&&result.body.version===4&&result.body.providerStatus==='unknown','unchanged reconciliation at capacity remains read only '+i);}
check(countKind('growth_landing_revision_history')===2000&&countKind('growth_landing_revision_request')===5000,'polling consumes no history or request capacity');
receipts.set(pending.provider.attempt.requestId,capacityReceipt);
check((await post({action:'provider_reconcile',id:'capacity',expectedVersion:4})).body.providerStatus==='verified','unknown final reconciliation bypasses ordinary write cap');
view=await get();check(view.history.length<=2000&&view.historyHasMore,'history page remains readable after recovery overflow');
await post({action:'provider_disable',expectedVersion:6});await post({action:'provider_enable',expectedVersion:7,installed:true,evidenceRef:'bridge-install'});
const recoveryApproval={action:'provider_approve_recovery',id:'capacity',expectedVersion:5,authorityId:'grant',authorityVersion:1,confirm:true};
await put('growth_stop','global',{id:'global',version:1,status:'stopped',reason:'stop',updatedAt:before,updatedBy:owner});
check((await post(recoveryApproval)).status===200,'recovery approval is possible at capacity and while new dispatch is stopped');
const beforeRepeat=countKind('growth_landing_revision_history');
check((await post({...recoveryApproval,expectedVersion:6})).body.version===6&&countKind('growth_landing_revision_history')===beforeRepeat,'same recovery approval creates no repeated history');
sql.prepare("DELETE FROM records WHERE kind='growth_stop'").run();
loseReply=true;check((await post({action:'provider_rollback',id:'capacity',expectedVersion:6,confirm:true,reason:'원본 복원'})).body.providerStatus==='unknown','recovery dispatch intent can persist above ordinary cap');loseReply=false;
check((await post({action:'provider_reconcile',id:'capacity',expectedVersion:7})).body.providerStatus==='verified','second terminal outcome also remains recoverable above cap');
check((await get()).proposals.find(p=>p.id==='capacity').status==='rolled_back','final recovered state readable above history cap');
check((await post({action:'save_proposal',id:'over-cap-new',expectedVersion:0,input:proposal})).status===409,'recovery overflow does not raise ordinary new-work limits');
console.log(JSON.stringify({passed}));
