// G2-32 실제 현금 원장. SQLite real, 인증 mocked, 외부 은행·판매처 호출 없음.
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
let failKind='';
const {load,sql,env}=testRuntime(async()=>{throw Error('external forbidden')},{beforeRun(s){if(failKind&&s.values[2]===failKind&&s.query.startsWith('INSERT INTO records'))throw Error('atomic failure')}});
const server=await load('lib/server.ts'),route=await load('app/api/growth/cash/route.ts'),operations=await load('app/api/growth/operations/route.ts'),profit=await load('app/api/growth/profit/route.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='cash-owner',c={id:'cash-c',brandId:'b',storeId:'s',version:1,status:'active'},h={'oai-authenticated-user-id':owner,origin:'https://agency.test'};
const now=new Date(Date.now()-60000).toISOString(),day=now.slice(0,10),period={from:day,to:day};
const put=(kind,id,data,parent='')=>server.recordStatement(owner,kind,id,data,parent).run();
await put('campaign',c.id,c);await put('store','s',{id:'s',brandId:'b'},'b');
await put('store_order','o',{id:'o',version:1,storeId:'s',campaignId:c.id,orderDate:day,status:'paid',paidAmount:10000,refundAmount:0,costs:{foodCost:3000,packagingCost:0,fees:500,deliveryCost:0,benefitCost:0}},'s');
const unpack=async r=>({status:r.status,body:await r.json()});
const post=(b,headers=h)=>route.POST(new Request('https://agency.test/api/growth/cash',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({campaignId:c.id,campaignVersion:1,expectedVersion:0,requestId:randomUUID(),...b})})).then(unpack);
const get=(headers=h)=>route.GET(new Request(`https://agency.test/api/growth/cash?campaignId=${c.id}&from=${day}&to=${day}`,{headers})).then(unpack);
const earnings=()=>profit.GET(new Request(`https://agency.test/api/growth/profit?campaignId=${c.id}&from=${day}&to=${day}`,{headers:h})).then(unpack);
const input=(changes={})=>({kind:'inventory_purchase',accountRef:'bank-account-1',receiptRef:'bank-transfer-1',currency:'KRW',amount:3000,occurredAt:now,evidenceRef:'statement-row-1',reason:'실제 매입 지급 증빙 확인',origin:'operator_attested',...changes});
const write=(id,changes={},extra={})=>post({action:'save_cash',id,input:input(changes),...extra});
const settle=async(id,amount=9500,extra={})=>put('growth_settlement',id,{id,brandId:'b',campaignId:c.id,storeId:'s',input:{eventId:id,revision:1,kind:'received',orderId:'o',orderVersion:1,accountRef:'settlement-account',settlementRef:'batch',receiptRef:'receipt-'+id,currency:'KRW',amount,feeAmount:500,taxBasis:'included',occurredAt:now,evidenceRef:'statement-'+id,origin:'operator_attested',...extra}},'s');
const attest=async(extra={})=>{const v=(await get()).body;return post({action:'attest_period',id:v.coverageId,expectedVersion:v.coverage?.version??0,period,inputDigest:v.inputDigest,evidenceRef:'bank-period-export',confirmedComplete:true,...extra})};

check((await post({action:'save_cash',id:'one',input:input()},{})).status===401,'unauthenticated denied');
check((await post({action:'save_cash',id:'one',input:input()},{...h,origin:'https://evil.test'})).status===403,'CSRF denied');
check((await write('bad',{amount:-1})).status===400,'negative amounts rejected');
check((await write('bad',{amount:1.5})).status===400,'fractional KRW rejected');
check((await write('bad',{currency:'USD'})).status===400,'non KRW rejected');
check((await write('bad',{occurredAt:'2099-01-01T00:00:00Z'})).status===400,'future cash rejected');
check((await write('bad',{evidenceRef:''})).status===400,'evidence required');
check((await write('bad',{origin:'bank_verified'})).status===400,'bank verified assertion rejected');
check((await write('bad',{kind:'expected_cost'})).status===400,'expected costs excluded');
for(const reason of ['연락처 010-1234-5678','담당자 user@example.test','api_key=fixture-only-value',JSON.stringify({api_key:'fixture-only-value'}),'ａｐｉ＿ｋｅｙ＝fixture-only-value','api_\u200bkey:fixture-only-value','api_\u00adkey:fixture-only-value'])check((await write('unsafe',{reason})).status===400,'PII or credential reason rejected');
for(const accountRef of ['01012345678','password:fixture-only-value'])check((await write('unsafe',{accountRef})).status===400,'unsafe reference rejected');

check((await get({'oai-authenticated-user-id':'other'})).status===404,'owner isolation');
await settle('r1');
check((await write('duplicate',{accountRef:'settlement-account',receiptRef:'receipt-r1',kind:'other_receipt'})).status===409,'settlement receipt cannot be added as bank cash');
let r=await earnings();check(r.body.cash.netCashFlow===null,'no period attestation stays unknown');
failKind='growth_cash_history';check((await write('atomic')).status===500,'history failure propagates');failKind='';
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_cash'").get().n===0,'cash batch rolls back');
const once={action:'save_cash',id:'purchase',requestId:randomUUID(),input:input()};
r=await post(once);check(r.status===200&&r.body.version===1,'actual cash saved');
check((await post(once)).body.duplicate===true,'identical UUID replay is idempotent');
const duplicateSettlement={eventId:'late-settlement',revision:1,kind:'received',orderId:'o',orderVersion:1,accountRef:'bank-account-1',settlementRef:'batch-late',receiptRef:'bank-transfer-1',currency:'KRW',amount:3000,feeAmount:0,taxBasis:'included',occurredAt:now,evidenceRef:'bank-proof',origin:'operator_attested'};
const denied=await operations.POST(new Request('https://agency.test/api/growth/operations',{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({campaignId:c.id,campaignVersion:1,action:'save_settlement',input:duplicateSettlement})}));
check(denied.status===409,'cash first then settlement also rejected');
check((await post({...once,input:input({amount:4000})})).status===409,'UUID changed payload rejected');
check((await write('again')).status===409,'bank identity duplicate rejected');
check((await write('purchase',{amount:4000},{expectedVersion:0})).status===409,'stale cash version rejected');
check((await write('purchase',{receiptRef:'different'},{expectedVersion:1})).status===409,'transaction identity immutable');
check((await attest({confirmedComplete:false})).status===400,'completeness must be explicit');
check((await attest({inputDigest:'stale'})).status===409,'stale source digest rejected');
r=await attest();check(r.status===200,'complete period attested');
r=await earnings();check(r.body.cash.netCashFlow===6500,'9500 actual deposit minus 3000 actual payment; settlement fee not deducted twice');
check(r.body.cash.verification==='operator_attested','operator statement not bank verified');
await write('fee',{kind:'fee_payment',receiptRef:'separate-fee',amount:100,evidenceRef:'external-fee-debit'});
r=await earnings();check(r.body.cash.netCashFlow===null,'new cash invalidates period coverage');
await attest();r=await earnings();check(r.body.cash.netCashFlow===6400,'only separately evidenced fee is deducted');
await write('purchase',{amount:2000},{expectedVersion:1});
r=await earnings();check(r.body.cash.netCashFlow===null,'cash correction invalidates coverage');
await attest();check((await earnings()).body.cash.netCashFlow===7400,'latest cash correction counted once');
const voided={action:'void_cash',id:'purchase',expectedVersion:2,requestId:randomUUID(),reason:'잘못 연결한 지급 증빙 무효'};
check((await post(voided)).status===200,'cash void recorded');
check((await post(voided)).body.duplicate===true,'void retry idempotent');
await attest();check((await earnings()).body.cash.netCashFlow===9400,'void excludes cash but history preserved');
check((await get()).body.history.filter(x=>x.id==='purchase').length===3,'append-only cash versions retained');
check((await write('reused')).status===409,'void identity remains reserved; revise same record');
await write('unknown',{receiptRef:'unknown-payment',amount:null});
check((await attest()).status===409,'unknown amount blocks complete period');
check((await earnings()).body.cash.netCashFlow===null,'unknown cash never becomes zero');
await post({action:'void_cash',id:'unknown',expectedVersion:1,reason:'확인되지 않은 중복 메모를 무효 처리'});
await attest();await settle('r1',9000,{revision:2});
check((await earnings()).body.cash.netCashFlow===null,'settlement correction invalidates period');
await attest();check((await earnings()).body.cash.netCashFlow===8900,'updated settlement only once');
await settle('r2',null);
check((await attest()).status===409,'unknown settlement blocks complete cash');
await settle('r2',0);
await attest();await settle('double',9000,{receiptRef:'receipt-r1'});
check((await earnings()).body.cash.netCashFlow===null,'later duplicate settlement receipt cannot inflate total');
check((await attest()).status===409,'duplicate settlement prevents attestation');
// 同owner 다른 campaign cash identity도 막는다.
const c2={...c,id:'other-c'};await put('campaign',c2.id,c2);
const otherView=await route.GET(new Request(`https://agency.test/api/growth/cash?campaignId=${c2.id}&from=${day}&to=${day}`,{headers:h})).then(unpack);
check(otherView.body.coverageId!==(await get()).body.coverageId,'same dates have campaign-scoped coverage identities');
check((await post({campaignId:c2.id,action:'attest_period',id:otherView.body.coverageId,expectedVersion:0,period,inputDigest:otherView.body.inputDigest,evidenceRef:'other-period',confirmedComplete:true})).status===200,'second campaign independently attests same period');
check((await post({campaignId:c2.id,action:'save_cash',id:'elsewhere',input:input()})).status===409,'same bank identity cannot be assigned to another campaign');
const cashOnly={...c,id:'cash-only'};await put('campaign',cashOnly.id,cashOnly);
await post({campaignId:cashOnly.id,action:'save_cash',id:'cash-only-record',input:input({receiptRef:'cash-only-transfer'})});
const deletion=await server.campaignDeletionPreview(owner,cashOnly.id);
check(deletion.deletable===false&&deletion.retained.growth_cash===1,'cash evidence blocks campaign deletion and remains retained');
const token='e'.repeat(64);env.AUTH_MODE='email';env.AUTH_ORIGIN='https://agency.test';
sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run('member','member@test.invalid',owner,'member','active',1);
sql.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?)').run(createHash('sha256').update(token).digest('hex'),'member',Date.now()+60000,Date.now());
const mh={cookie:'__Host-collective_session='+token,origin:'https://agency.test'};
check((await get(mh)).status===403&&(await post({action:'save_cash',id:'member',input:input()},mh)).status===403,'member cannot read or write cash details');
env.AUTH_MODE='legacy';
const overflow=sql.prepare('INSERT INTO records(id,owner,kind,parent_id,data,updated_at) VALUES(?,?,?,?,?,?)');
for(let i=0;i<5001;i++)overflow.run('overflow-'+i,'overflow-owner','growth_settlement','s',JSON.stringify({id:'overflow-'+i,brandId:'b',campaignId:'overflow-c',storeId:'s',input:{kind:'expected'}}),now);
await server.recordStatement('overflow-owner','campaign','overflow-c',{...c,id:'overflow-c'}).run();
check((await profit.GET(new Request('https://agency.test/api/growth/profit?campaignId=overflow-c',{headers:{'oai-authenticated-user-id':'overflow-owner'}}))).status===409,'settlement overflow rejects partial cash instead of truncating');
console.log(JSON.stringify({passed,sqlite:'real',auth:'mocked',external:0}));
