import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
const {load}=testRuntime(async()=>{throw Error('No external requests')});
const {growthBusiness}=await load('lib/growth-business-server.ts');
const {recordStatement}=await load('lib/server.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const c={id:'c',brandId:'b',storeId:'s',startDate:'2026-01-01',endDate:'2026-12-31'};
check((await growthBusiness('o',{...c,storeId:null})).status==='not_measured','no store means not measured');
await recordStatement('o','store','s',{id:'s',brandId:'other'}).run();
check((await growthBusiness('o',c)).status==='unavailable','wrong brand store not read');
await recordStatement('o','store','s',{id:'s',brandId:'b'}).run();
const costs={foodCost:100,packagingCost:100,fees:100,deliveryCost:100,benefitCost:100};
const order={id:'one',storeId:'s',campaignId:'c',orderDate:'2026-09-29',paidAmount:10000,refundAmount:2000,status:'paid',costs,version:1};
await recordStatement('o','store_order','one',order,'s').run();
await recordStatement('o','store_order','two',{...order,id:'two',campaignId:'other',paidAmount:999999},'s').run();
await recordStatement('foreign','store_order','three',order,'s').run();
let r=await growthBusiness('o',c);check(r.netRevenue===8000&&r.records===1,'same owner campaign store orders only');
check(r.contributionBeforeMarketing===7500,'net refunds less known costs');
check(r.contribution===null&&r.cash===null&&r.incrementality==='not_measured','unallocated marketing cash causal remain unknown');
check(r.status==='ledger_only'&&r.reconciliation==='not_verified','ledger not asserted real reconciliation');
await recordStatement('o','store_order','one',{...order,costs:{...costs,fees:null}},'s').run();
r=await growthBusiness('o',c);check(r.contributionBeforeMarketing===null,'missing cost is not zero');
check((await growthBusiness('o',{...c,startDate:'2026-02-30'})).status==='unavailable','invalid period rejected');
check((await growthBusiness('o',{...c,id:'empty'})).netRevenue===0,'empty queried ledger is zero with caveat');
console.log(JSON.stringify({passed}));
