// 상세페이지 수정안 ↔ 운영자 확인 적용 영수증 분리(G2-26/29/12a). 인증 mocked, 메모리 SQLite real, 외부 호출 0.
import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {testRuntime} from './helpers/runtime.mjs';
let failKind='';const {load,sql}=testRuntime(async()=>{throw Error('external forbidden')},{beforeRun(s){if(failKind&&s.values[2]===failKind&&s.query.startsWith('INSERT INTO records'))throw Error('atomic failure')}});
const s=await load('lib/server.ts'),route=await load('app/api/growth/landing/route.ts'),growth=await load('app/api/growth/route.ts'),pure=await load('lib/growth-landing.ts');let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='owner',headers={'oai-authenticated-user-id':owner,origin:'https://agency.test'},c={id:'c',brandId:'b',storeId:'store',version:1,status:'active'};
const put=(kind,id,data,parent='')=>s.recordStatement(owner,kind,id,data,parent).run();
const before=new Date(Date.now()-86400000).toISOString(),after=new Date(Date.now()+30*86400000).toISOString(),day=after.slice(0,10);
await put('campaign','c',c);await put('store','store',{id:'store',brandId:'b',name:'합성 매장'},'b');
const fact=(id,version=1)=>put('brand_fact',id,{id,brandId:'b',key:id==='ship'?'배송 조건':'원산지',value:'합성 사실',status:'confirmed',source:'합성 확인',verifiedAt:before,validUntil:after,version,updatedAt:before},'b');await fact('ship');await fact('origin');
const g=async(action,id,input,expectedVersion=0)=>{const r=await growth.POST(new Request('https://agency.test/api/growth',{method:'POST',headers,body:JSON.stringify({action,id,input,campaignId:'c',campaignVersion:1,expectedVersion})}));assert.equal(r.status,200,JSON.stringify(await r.clone().json()));return r.json()};
const catalog={sku:'LANDING-SKU',title:'상품',price:12000,unitCost:4000,variableCost:1000,stock:0,stockUnit:'piece',currency:'KRW',taxBasis:'included',fulfillment:'배송 조건',refunds:'반품 조건',rightsConfirmed:true,factIds:['ship'],validUntil:day};
const offer={title:'오퍼',catalogId:'cat',catalogVersion:1,needId:'',price:12000,quantity:1,landingUrl:'https://shop.example.com/p/1',purchaseReason:'준비 단축',priceApproved:true};
await g('save_catalog','cat',catalog);await g('save_offer','offer',offer);
const proposal=(patch={})=>({title:'상세 개선',offerId:'offer',offerVersion:1,journeyId:'',journeyVersion:0,landingUrl:'https://shop.example.com/p/1',rationale:'배송 불안 해소',rollbackPlan:'이전 문구로 복구',sections:[{kind:'shipping',before:'배송 안내',after:'평일 오후 2시 전 주문은 당일 출고',factIds:['ship']},{kind:'price_display',before:'가격',after:'12,000원',factIds:[]}],...patch});
const post=async(b,h=headers)=>{const r=await route.POST(new Request('https://agency.test/api/growth/landing',{method:'POST',headers:h,body:JSON.stringify(b)}));return {status:r.status,body:await r.json()}};
const get=async(h=headers)=>{const r=await route.GET(new Request('https://agency.test/api/growth/landing?campaignId=c',{headers:h}));return {status:r.status,body:await r.json()}};
const act=(action,expectedVersion,extra={})=>({campaignId:'c',campaignVersion:1,id:'rev',action,expectedVersion,requestId:randomUUID(),...extra});
const receipt=(patch={})=>({at:new Date().toISOString(),evidenceRef:'page-check-1',observedUrl:'https://shop.example.com/p/1',reason:'',...patch});

check((await post(act('save_proposal',0,{input:proposal()}),{})).status===401,'auth');check((await post(act('save_proposal',0,{input:proposal()}),{...headers,origin:'https://evil.test'})).status===403,'CSRF');
check((await post(act('save_proposal',0,{input:proposal({offerVersion:2})}))).status===409,'offer version CAS');
check((await post(act('save_proposal',0,{input:proposal({landingUrl:'https://shop.example.com/p/1?utm=x'})}))).status===400,'query URL rejected');
check((await post(act('save_proposal',0,{input:proposal({sections:[{kind:'faq',before:'a',after:'문의 010-1234-5678',factIds:[]}]})}))).status===400,'PII rejected');
check((await post(act('save_proposal',0,{input:proposal({sections:[{kind:'faq',before:'같음',after:'같음',factIds:[]}]})}))).status===400,'no-op section rejected');
failKind='growth_landing_revision_history';check((await post(act('save_proposal',0,{input:proposal()}))).status===500,'atomic failure');failKind='';check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_landing_revision'").get().n===0,'rollback');
const first=act('save_proposal',0,{input:proposal()});let r=await post(first);check(r.status===200&&r.body.version===1&&r.body.mayApply===false,'draft saved');check((await post(first)).body.duplicate,'UUID replay');check((await post({...first,input:proposal({title:'다른 제목'})})).status===409,'UUID conflict');
r=await get();let p=r.body.proposals[0];check(p.status==='draft'&&p.pageChanged==='not_confirmed'&&p.readiness.missing.length===0&&p.sourceStatus==='current','draft is not a page change');check(r.body.adapter===null&&r.body.mayApply===false,'no adapter, no apply permission');
check((await post(act('record_applied',1,{receipt:receipt()}))).status===409,'cannot record applied before approval');
await post(act('save_proposal',1,{input:proposal({sections:[{kind:'price_display',before:'가격',after:'지금 9,900원',factIds:[]}]})}));r=await get();check(r.body.proposals[0].readiness.missing.some(m=>m.includes('승인된 오퍼 가격')),'unapproved price flagged');
check((await post(act('approve',2))).status===409,'approval blocked by readiness');
await post(act('save_proposal',2,{input:proposal({sections:[{kind:'trust',before:'',after:'재고 3개 남음',factIds:['origin']}]})}));check((await post(act('approve',3))).status===409,'stock claim blocked');
await post(act('save_proposal',3,{input:proposal({sections:[{kind:'shipping',before:'배송 안내',after:'평일 오후 2시 전 주문은 당일 출고',factIds:['missing-fact']}]})}));check((await post(act('approve',4))).status===409,'unknown fact blocked');
await post(act('save_proposal',4,{input:proposal()}));
await put('growth_stop','global',{status:'stopped'});check((await post(act('approve',5))).status===409,'global stop blocks approval');sql.prepare("DELETE FROM records WHERE kind='growth_stop'").run();
await fact('ship',2);check((await post(act('approve',5))).status===409,'changed fact after save holds approval');r=await get();check(r.body.proposals[0].sourceStatus==='held','changed fact shows held');
await post(act('withdraw',5));check((await post(act('save_proposal',6,{input:proposal()}))).status===409,'withdrawn cannot be edited');
const second=(action,expectedVersion,extra={})=>({...act(action,expectedVersion,extra),id:'rev2'});
check((await post(second('save_proposal',0,{input:proposal()}))).status===200,'new draft after source change');
r=await post(second('approve',1));check(r.status===200,'approved');r=await get();p=r.body.proposals.find(x=>x.id==='rev2');check(p.status==='approved'&&p.approvalValid&&p.pageChanged==='not_confirmed','approval is not page change');
check((await post(second('record_applied',2,{receipt:receipt({observedUrl:'https://shop.example.com/p/2'})}))).status===409,'receipt URL must match');
check((await post(second('record_applied',2,{receipt:receipt({at:new Date(Date.now()+3600000).toISOString()})}))).status===400,'future receipt rejected');
check((await post(second('record_applied',2,{receipt:receipt({at:before})}))).status===409,'receipt before approval rejected');
r=await post(second('record_applied',2,{receipt:receipt()}));check(r.status===200,'applied receipt');r=await get();p=r.body.proposals.find(x=>x.id==='rev2');check(p.status==='applied'&&p.pageChanged==='operator_attested'&&p.applied.method==='manual_attested','operator attested page change');check(r.body.causalStatus==='not_measured','no effect claim');
check((await post(second('record_rollback',3,{receipt:receipt()}))).status===400,'rollback needs reason');
r=await post(second('record_rollback',3,{receipt:receipt({reason:'전환 하락 확인'})}));check(r.status===200,'rollback receipt');r=await get();p=r.body.proposals.find(x=>x.id==='rev2');check(p.status==='rolled_back'&&p.rolledBack.reason==='전환 하락 확인'&&r.body.history.filter(h=>h.id==='rev2').length===4,'rollback history kept');
// Journey raw appliedAt vs operator receipt
await put('growth_journey','j',{id:'j',brandId:'b',campaignId:'c',campaignVersion:1,version:1,input:{title:'결제 이탈',offerId:'offer',offerVersion:1,appliedAt:before},requestDigest:'x',createdAt:before,updatedAt:before,updatedBy:owner},'c');
r=await get();check(r.body.journeys[0].basis==='raw_applied_at_only','raw appliedAt is not a receipt');
const third=(action,expectedVersion,extra={})=>({...act(action,expectedVersion,extra),id:'rev3'});
check((await post(third('save_proposal',0,{input:proposal({journeyId:'j',journeyVersion:2})}))).status===409,'journey CAS');
check((await post(third('save_proposal',0,{input:proposal({journeyId:'j',journeyVersion:1})}))).status===200,'journey linked');await post(third('approve',1));await post(third('record_applied',2,{receipt:receipt()}));r=await get();check(r.body.journeys[0].basis==='operator_receipt'&&r.body.journeys[0].receipts[0].revisionId==='rev3','journey shows operator receipt');
await put('campaign','c',{...c,status:'archived'});check((await post(third('record_rollback',3,{receipt:receipt({reason:'복구'})}))).status===200,'archived still allows rollback receipt');check((await post({...act('save_proposal',0,{input:proposal()}),id:'rev4'})).status===409,'archived blocks new proposal');await put('campaign','c',c);
check((await get({'oai-authenticated-user-id':'other'})).status===404,'owner isolation');
check(pure.landingReadiness(pure.parseLandingProposal(proposal({sections:[{kind:'cta',before:'구매',after:'오늘 15,000원에 구매',factIds:[]}]})),{offerPrice:12000,priceApproved:true,rightsConfirmed:true,factIds:[],offerLandingUrl:'https://shop.example.com/p/1'}).missing.length===1,'unapproved amount in other section flagged');
check(pure.landingReadiness(pure.parseLandingProposal(proposal()),{offerPrice:12000,priceApproved:true,rightsConfirmed:false,factIds:['ship'],offerLandingUrl:'https://shop.example.com/p/1'}).missing.includes('상품 권리 확인이 필요합니다.'),'rights required');
console.log(JSON.stringify({passed}));
