import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
const secret='synthetic-worker-key-0000000000000000';let calls=0,mode='valid',price=100,leaseTarget='';
const {load,sql}=testRuntime(async(url,o)=>{calls++;assert.equal(new URL(url).pathname,'/collective/v1/catalog/read');const b=JSON.parse(o.body),snapshot={tenantId:b.tenantId,storeId:b.storeId,productId:b.productId,state:'active',title:'상품',price,sellable:4,unit:'piece',observedAt:new Date().toISOString()},snapshotJson=JSON.stringify(snapshot),signature=createHmac('sha256',secret).update(`${o.headers['x-collective-timestamp']}\n${o.headers['x-collective-nonce']}\n200\n/collective/v1/catalog/read\n${snapshotJson}`).digest('hex');if(mode==='replace-lease'){sql.prepare("UPDATE mutation_locks SET token='replacement' WHERE owner=?").run(owner);await put('growth_provider_catalog_source',leaseTarget,{id:leaseTarget,version:999,status:'failed',checkedAt:new Date().toISOString()});}return Response.json({snapshot,snapshotJson,signature:mode==='invalid'?'0'.repeat(64):signature});});
const s=await load('lib/server.ts'),crypt=await load('lib/credential-crypto-server.ts'),worker=await load('lib/growth-provider-catalog-worker.ts');
const owner='owner',c={id:'c',brandId:'b',storeId:'s',status:'active',version:1},put=(kind,id,v,parent='s')=>s.recordStatement(owner,kind,id,v,parent).run(),now=Date.now();
await put('campaign','c',c);await put('store','s',{id:'s',brandId:'b',status:'active'},'b');
const connection={id:'growth_landing_provider:s',channel:'growth_landing_provider',brandId:'b',storeId:'s',baseUrl:'https://mapdal.kr',tenantId:'tenant',providerStoreId:'shop',secret:await crypt.sealRecordSecret(owner,'channel_credential','growth_landing_provider:s',secret),enabled:true,version:1};await put('channel_credential',connection.id,connection);
await put('growth_inventory_item','inv',{id:'inv',brandId:'b',storeId:'s',version:0,input:{sku:'SKU',locationId:'s',unit:'piece',onHand:10}});
const binding={id:'a',brandId:'b',storeId:'s',campaignId:'c',sku:'SKU',inventoryId:'inv',catalogId:'cat',catalogVersion:1,productId:'mpd::1',connectionVersion:1,version:1,approvedDigest:'old'};await put('growth_provider_catalog_binding','a',binding);
let passed=0;const check=(v,m)=>{assert.ok(v,m);passed++};
check((await worker.runProviderCatalogWorker('other',now)).status==='idle'&&calls===0,'owner scope excludes foreign bindings');
check((await worker.runProviderCatalogWorker(owner,now)).status==='processed'&&calls===1,'one signed read for explicit binding');
check((await worker.runProviderCatalogWorker(owner,now+1)).status==='idle'&&calls===1,'minimum five minute cadence');
check((await s.readRecord(owner,'growth_provider_catalog_binding','a')).approvedDigest==='old','worker never approves source');
price=200;await worker.runProviderCatalogWorker(owner,now+301000);check((await s.readRecord(owner,'growth_provider_catalog_source','a')).snapshot.price===200,'changed price retained for existing approval invalidation');
check((await s.readRecord(owner,'growth_provider_catalog_binding','a')).version===1,'no automatic rebind or review');
mode='invalid';const failed=await worker.runProviderCatalogWorker(owner,now+602002);check(failed.status==='retry','signature failure enters retry');
check((await s.readRecord(owner,'growth_provider_catalog_source','a')).status==='failed','failure persists canonical held source');
check((await worker.runProviderCatalogWorker(owner,now+602003)).status==='idle','failed source backs off');
const failedAgain=await worker.runProviderCatalogWorker(owner,failed.nextAt);check(failedAgain.nextAt-failed.nextAt===600000,'successive failure doubles backoff');
await put('growth_provider_catalog_binding','b',{...binding,id:'b',campaignId:'missing'});await put('growth_provider_catalog_binding','d',{...binding,id:'d',productId:'mpd::2'});mode='valid';
check((await worker.runProviderCatalogWorker(owner,now+602004)).reason==='campaign_unavailable','orphan is individually deferred');
check((await worker.runProviderCatalogWorker(owner,now+602005)).id==='d','orphan cannot starve next binding');
await put('growth_provider_catalog_binding','e',{...binding,id:'e'});await put('campaign','c',{...c,status:'archived'});const before=calls;check((await worker.runProviderCatalogWorker(owner,now+602006)).reason==='campaign_unavailable'&&calls===before,'archived campaign has no provider call');await put('campaign','c',c);
await put('growth_provider_catalog_binding','f',{...binding,id:'f'});await put('channel_credential',connection.id,{...connection,enabled:false});check((await worker.runProviderCatalogWorker(owner,now+602007)).reason==='connection_unavailable'&&calls===before,'disabled connection no call');await put('channel_credential',connection.id,connection);
await put('growth_provider_catalog_binding','g',{...binding,id:'g'});const token=await s.acquireLock(owner);check((await worker.runProviderCatalogWorker(owner,now+602008)).reason==='busy'&&calls===before,'manual operation owner lease prevents overlap');await s.releaseLock(owner,token);
const concurrent=await Promise.all([worker.runProviderCatalogWorker(owner,now+602009),worker.runProviderCatalogWorker(owner,now+602009)]);check(concurrent.filter(x=>x.status==='processed').length===1&&concurrent.some(x=>x.reason==='busy'),'concurrent ticks issue one read');
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_provider_catalog_history' AND json_extract(data,'$.action')!='pull'").get().n===0,'only pull history exists');
check((await s.readRecord(owner,'growth_inventory_item','inv')).input.onHand===10,'local physical inventory unchanged');
await put('growth_provider_catalog_binding','h',{...binding,id:'h'});
await put('growth_provider_catalog_source','h',{id:'h',checkedAt:new Date(now+602010).toISOString(),status:'ready'});
check((await worker.runProviderCatalogWorker(owner,now+602011)).status==='idle','recent manual source pull also enforces cadence');
await put('growth_provider_catalog_binding','i',{...binding,id:'i'});
sql.exec("CREATE TRIGGER fail_worker_checkpoint BEFORE UPDATE ON records WHEN NEW.kind='growth_provider_catalog_worker' AND json_extract(NEW.data,'$.status')='processed' BEGIN SELECT RAISE(ABORT,'checkpoint'); END;");
await assert.rejects(()=>worker.runProviderCatalogWorker(owner,now+602012));passed++;sql.exec('DROP TRIGGER fail_worker_checkpoint');
check((await worker.runProviderCatalogWorker(owner,now+602013)).status==='idle','lost final checkpoint retains durable pre-pull retry deadline');
check(sql.prepare("SELECT COUNT(*) n FROM mutation_locks WHERE owner=?").get(owner).n===0,'checkpoint error releases owner lease');
const corrupt=(kind,id,data)=>sql.prepare('INSERT INTO records(id,owner,kind,parent_id,data,updated_at) VALUES(?,?,?,?,?,?)').run(owner+':'+kind+':'+id,owner,kind,'s',data,new Date().toISOString());
corrupt('growth_provider_catalog_binding','z-broken','{');
check((await worker.runProviderCatalogWorker(owner,now+602014)).reason==='malformed_binding','malformed head binding gets durable quarantine');
check((await s.readRecord(owner,'growth_provider_catalog_worker','z-broken')).nextAt>now+602014,'malformed binding checkpoint uses record metadata');
await put('growth_provider_catalog_binding','z-good',{...binding,id:'z-good'});
check((await worker.runProviderCatalogWorker(owner,now+602015)).id==='z-good','malformed head cannot starve healthy binding');
await put('growth_provider_catalog_binding','zz-corrupt-state',{...binding,id:'zz-corrupt-state'});
corrupt('growth_provider_catalog_worker','zz-corrupt-state','{');corrupt('growth_provider_catalog_source','zz-corrupt-state','{');
check((await worker.runProviderCatalogWorker(owner,now+602016)).status==='retry','malformed joined JSON does not abort owner queue');
check((await s.readRecord(owner,'growth_provider_catalog_worker','zz-corrupt-state')).failures===1,'malformed worker state replaced by bounded checkpoint');
corrupt('growth_provider_catalog_binding','zz-null','null');
check((await worker.runProviderCatalogWorker(owner,now+602017)).reason==='malformed_binding','JSON null binding is quarantined');
await put('growth_provider_catalog_binding','zzz-lease',{...binding,id:'zzz-lease'});mode='replace-lease';leaseTarget='zzz-lease';
const historyBefore=sql.prepare("SELECT COUNT(*) n FROM records WHERE kind IN ('growth_provider_catalog_history','growth_provider_catalog_request')").get().n;
await assert.rejects(()=>worker.runProviderCatalogWorker(owner,now+602018));passed++;
check((await s.readRecord(owner,'growth_provider_catalog_source','zzz-lease')).version===999,'replaced owner lease cannot overwrite newer canonical source');
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind IN ('growth_provider_catalog_history','growth_provider_catalog_request')").get().n===historyBefore,'stale pull writes no history or request receipt');
check(sql.prepare('SELECT token FROM mutation_locks WHERE owner=?').get(owner).token==='replacement','stale worker preserves replacement owner lease');
console.log(JSON.stringify({passed,sqlite:'real',http:'mocked',externalWrites:0}));
