import assert from 'node:assert/strict';
import {moduleRuntime} from '../scripts/eval/runtime.mjs';
const {load}=moduleRuntime(async()=>{throw Error('No network');});
const m=await load('lib/growth-authority.ts');
let passed=0;const test=(name,fn)=>{fn();passed++;console.log('passed: '+name);};
const now=Date.parse('2026-09-30T03:00:00Z');
const authority=()=>({...m.emptyAuthorityInput(),id:'mandate-1',brandId:'brand-1',campaignId:'campaign-1',accountId:'account-1',channel:'meta',status:'active',maxTier:'T3',allowedActions:['publish','spend','scale'],ownerApprovalId:'approval-1',ownerSignedAt:'2026-09-01T00:00:00Z',startsAt:'2026-09-01T00:00:00Z',expiresAt:'2026-10-01T00:00:00Z',periodStart:'2026-09-01T00:00:00Z',periodEnd:'2026-10-01T00:00:00Z',totalCap:1000,dayCap:500,weekCap:800,lossCap:300});
const action=()=>({id:'action-1',operationKey:'key-1',brandId:'brand-1',campaignId:'campaign-1',accountId:'account-1',channel:'meta',operation:'spend',amount:100,loss:20,budget:'exploration',previousBudget:null,nextBudget:null,evidence:null});
const commitment=(overrides={})=>({authorityId:'mandate-1',action:{...action(),id:'action-old',operationKey:'key-old'},status:'reserved',at:'2026-09-30T01:00:00Z',reservedAmount:100,reservedLoss:20,actualAmount:null,actualLoss:null,...overrides});
const evaluate=(a=authority(),b=action(),c=[],clock=now)=>m.evaluateAuthority(a,b,c,clock);
test('valid supervised exploration is allowed without causal proof',()=>assert.equal(evaluate().allowed,true));
test('empty authority draft parses conservatively',()=>assert.equal(m.parseAuthorityInput({}).totalCap,null));
test('read can run without spend authority',()=>assert.equal(evaluate(null,{...action(),operation:'read',amount:null,loss:null}).allowed,true));
test('draft can run without spend authority',()=>assert.equal(evaluate(null,{...action(),operation:'draft',amount:null,loss:null}).tier,'T1'));
test('read cannot conceal spending',()=>assert.equal(evaluate(null,{...action(),operation:'read'}).allowed,false));
test('publish requires signed authority',()=>assert.equal(evaluate({...authority(),ownerApprovalId:''},{...action(),operation:'publish',amount:0,loss:0}).allowed,false));
test('spend requires an active mandate',()=>assert.equal(evaluate({...authority(),status:'draft'}).allowed,false));
test('revoked mandate blocks new spend',()=>assert.equal(evaluate({...authority(),status:'revoked'}).allowed,false));
for(const operation of ['read','reconcile','stop'])test('revoked mandate permits safe '+operation,()=>assert.equal(evaluate({...authority(),status:'revoked'},{...action(),operation,amount:0,loss:0}).allowed,true));
test('reconcile cannot exceed account scope',()=>assert.equal(evaluate({...authority(),status:'revoked'},{...action(),operation:'reconcile',accountId:'other',amount:0,loss:0}).allowed,false));
test('T4 policy changes always blocked',()=>assert.equal(evaluate(authority(),{...action(),operation:'policy_change'}).allowed,false));
for(const field of ['brandId','campaignId','accountId','channel'])test('exact '+field+' scope enforced',()=>assert.equal(evaluate(authority(),{...action(),[field]:'other'}).allowed,false));
test('allowlist does not grant a different action',()=>assert.equal(evaluate({...authority(),allowedActions:['publish']}).allowed,false));
test('T2 does not allow T3 spend',()=>assert.equal(evaluate({...authority(),maxTier:'T2'}).allowed,false));
test('expiry is exclusive',()=>assert.equal(evaluate({...authority(),expiresAt:'2026-09-30T03:00:00Z'}).allowed,false));
test('future signature cannot grant authority',()=>assert.equal(evaluate({...authority(),ownerSignedAt:'2026-09-30T04:00:00Z'}).allowed,false));
test('future start blocks execution',()=>assert.equal(evaluate({...authority(),startsAt:'2026-09-30T04:00:00Z'}).allowed,false));
test('period end blocks execution',()=>assert.equal(evaluate({...authority(),periodEnd:'2026-09-30T03:00:00Z'}).allowed,false));
for(const field of ['totalCap','dayCap','weekCap','lossCap'])test('missing '+field+' is not unlimited',()=>assert.equal(evaluate({...authority(),[field]:null}).allowed,false));
for(const field of ['totalCap','dayCap','weekCap'])test(field+' includes reservations and candidate amount',()=>assert.equal(evaluate({...authority(),[field]:199},action(),[commitment()]).allowed,false));
test('exact cap boundary allowed',()=>assert.equal(evaluate({...authority(),dayCap:200},action(),[commitment()]).allowed,true));
test('loss includes outstanding reservations',()=>assert.equal(evaluate({...authority(),lossCap:39},action(),[commitment()]).allowed,false));
test('unknown result retains reserved amount',()=>assert.equal(evaluate(authority(),action(),[commitment({status:'unknown'})]).usage.total,100));
test('missing unknown reservation blocks',()=>assert.equal(evaluate(authority(),action(),[commitment({status:'unknown',reservedAmount:null})]).allowed,false));
test('reconciled amounts replace reservation',()=>assert.equal(evaluate(authority(),action(),[commitment({status:'reconciled',actualAmount:50,actualLoss:5})]).usage.total,50));
test('missing reconciled cost does not become zero',()=>assert.equal(evaluate(authority(),action(),[commitment({status:'reconciled'})]).allowed,false));
test('released reservation does not consume funds',()=>assert.equal(evaluate(authority(),action(),[commitment({status:'released'})]).usage.total,0));
test('other campaign same account consumes account cap',()=>assert.equal(evaluate({...authority(),dayCap:150},action(),[commitment({action:{...action(),campaignId:'other',operationKey:'other'}})]).allowed,false));
test('different account does not consume this account cap',()=>assert.equal(evaluate(authority(),action(),[commitment({action:{...action(),accountId:'other',operationKey:'other'}})]).usage.total,0));
test('old unresolved reservations remain in daily capacity',()=>assert.equal(evaluate(authority(),action(),[commitment({at:'2026-09-01T01:00:00Z'})]).usage.day,100));
test('previous KST day reconciled spend excluded from daily cap',()=>assert.equal(evaluate(authority(),action(),[commitment({status:'reconciled',at:'2026-09-29T14:59:59Z',actualAmount:50,actualLoss:5})]).usage.day,0));
test('KST midnight reconciled spend included in daily cap',()=>assert.equal(evaluate(authority(),action(),[commitment({status:'reconciled',at:'2026-09-29T15:00:00Z',actualAmount:50,actualLoss:5})]).usage.day,50));
test('previous Sunday KST is excluded from current week',()=>assert.equal(evaluate(authority(),action(),[commitment({status:'reconciled',at:'2026-09-27T14:59:59Z',actualAmount:50,actualLoss:5})]).usage.week,0));
test('Monday KST begins current week',()=>assert.equal(evaluate(authority(),action(),[commitment({status:'reconciled',at:'2026-09-27T15:00:00Z',actualAmount:50,actualLoss:5})]).usage.week,50));
test('idempotent exact retry does not reserve twice',()=>{const r=evaluate(authority(),action(),[commitment({action:action()})]);assert.equal(r.allowed,true);assert.equal(r.duplicate,true);});
test('same key changed amount fails',()=>assert.equal(evaluate(authority(),action(),[commitment({action:{...action(),amount:101}})]).allowed,false));
test('same key changed scope fails even on another account',()=>assert.equal(evaluate(authority(),action(),[commitment({action:{...action(),accountId:'other'}})]).allowed,false));
test('unknown duplicate must reconcile instead of reexecute',()=>assert.equal(evaluate(authority(),action(),[commitment({action:action(),status:'unknown'})]).allowed,false));
test('duplicate conflicting ledger rows fail closed',()=>assert.equal(evaluate(authority(),action(),[commitment(),commitment()]).allowed,false));
test('confirmed budget needs evidence',()=>assert.equal(evaluate(authority(),{...action(),budget:'confirmed'}).allowed,false));
const scale=()=>({...action(),operation:'scale',budget:'confirmed',previousBudget:100,nextBudget:120,evidence:{id:'proof-1',incremental:true,profitable:true,capacity:true}});
test('confirmed scale within twenty percent and signed caps allowed',()=>assert.equal(evaluate(authority(),scale()).allowed,true));
test('scale above twenty percent blocked',()=>assert.equal(evaluate(authority(),{...scale(),nextBudget:121}).allowed,false));
test('exploration cannot silently become scaling',()=>assert.equal(evaluate(authority(),{...scale(),budget:'exploration'}).allowed,false));
for(const field of ['incremental','profitable','capacity'])test('scaling requires '+field+' proof',()=>assert.equal(evaluate(authority(),{...scale(),evidence:{...scale().evidence,[field]:false}}).allowed,false));
test('scale cannot widen signed cap',()=>assert.equal(evaluate({...authority(),totalCap:90},scale()).allowed,false));
for(const value of [-1,1.2,Infinity,Number.MAX_SAFE_INTEGER+1,'100'])test('rejects unsafe cap '+String(value),()=>assert.throws(()=>m.parseAuthorityInput({...authority(),totalCap:value}),m.GrowthAuthorityError));
test('rejects T4 max tier',()=>assert.throws(()=>m.parseAuthorityInput({...authority(),maxTier:'T4'}),m.GrowthAuthorityError));
test('rejects impossible calendar date',()=>assert.throws(()=>m.parseAuthorityInput({...authority(),expiresAt:'2026-02-30T00:00:00Z'}),m.GrowthAuthorityError));
test('rejects timestamp without timezone',()=>assert.throws(()=>m.parseAuthorityInput({...authority(),expiresAt:'2026-10-01T00:00:00'}),m.GrowthAuthorityError));
test('rejects identifiers containing raw email',()=>assert.throws(()=>m.parseAuthorityInput({...authority(),ownerApprovalId:'owner@example.com'}),m.GrowthAuthorityError));
test('unsafe action input returns blocked decision',()=>assert.equal(evaluate(authority(),{...action(),amount:NaN}).allowed,false));
test('missing action amount is not zero',()=>assert.equal(evaluate(authority(),{...action(),amount:null}).allowed,false));
test('invalid ledger entry blocks rather than disappearing',()=>assert.equal(evaluate(authority(),action(),[{}]).allowed,false));
test('arithmetic overflow blocks',()=>assert.equal(evaluate({...authority(),totalCap:Number.MAX_SAFE_INTEGER,dayCap:Number.MAX_SAFE_INTEGER,weekCap:Number.MAX_SAFE_INTEGER},action(),[commitment({reservedAmount:Number.MAX_SAFE_INTEGER})]).allowed,false));
test('evaluation does not mutate its inputs',()=>{const a=authority(),b=action(),c=[commitment()],before=JSON.stringify([a,b,c]);evaluate(a,b,c);assert.equal(JSON.stringify([a,b,c]),before);});
test('fresh authority arrays are not shared',()=>{const a=m.emptyAuthorityInput(),b=m.emptyAuthorityInput();a.allowedActions.push('spend');assert.equal(b.allowedActions.length,0);});
test('missing mandate blocks new spending',()=>assert.equal(evaluate(null).allowed,false));
test('stop cannot target an account without existing scope',()=>assert.equal(evaluate(null,{...action(),operation:'stop',amount:0,loss:0}).allowed,false));
test('publish without spending can use T2 mandate',()=>assert.equal(evaluate({...authority(),maxTier:'T2'},{...action(),operation:'publish',amount:0,loss:0}).allowed,true));
test('publish cannot hide a cost in T2',()=>assert.equal(evaluate(authority(),{...action(),operation:'publish'}).allowed,false));
test('released operation key cannot execute again',()=>assert.equal(evaluate(authority(),action(),[commitment({action:action(),status:'released'})]).allowed,false));
test('future-dated ledger row blocks',()=>assert.equal(evaluate(authority(),action(),[commitment({at:'2026-10-01T00:00:00Z'})]).allowed,false));
test('missing ledger is not an empty ledger',()=>assert.equal(evaluate(authority(),action(),null).allowed,false));
test('invalid evaluation date blocks',()=>assert.equal(evaluate(authority(),action(),[],NaN).allowed,false));
test('newly reserved competitor operation prevents over-cap next request',()=>{
  const a={...authority(),dayCap:100}; assert.equal(evaluate(a).allowed,true);
  assert.equal(evaluate(a,{...action(),id:'next',operationKey:'next'},[commitment({action:action()})]).allowed,false);
});
test('old same-mandate spend stays in total across a period reset',()=>assert.equal(evaluate({...authority(),periodStart:'2026-09-29T00:00:00Z'},action(),[commitment({status:'reconciled',at:'2026-09-01T01:00:00Z',actualAmount:50,actualLoss:5})]).usage.total,50));
test('scale with missing baseline blocked',()=>assert.equal(evaluate(authority(),{...scale(),previousBudget:null}).allowed,false));
test('scale with underreserved increase blocked',()=>assert.equal(evaluate(authority(),{...scale(),amount:19}).allowed,false));
test('string evidence flags rejected',()=>assert.equal(evaluate(authority(),{...scale(),evidence:{...scale().evidence,profitable:'true'}}).allowed,false));
test('overlong allowance list rejected',()=>assert.throws(()=>m.parseAuthorityInput({...authority(),allowedActions:Array(9).fill('spend')}),m.GrowthAuthorityError));
test('reversed mandate dates rejected',()=>assert.throws(()=>m.parseAuthorityInput({...authority(),startsAt:'2026-11-01T00:00:00Z'}),m.GrowthAuthorityError));
test('direct phone identifier is rejected',()=>assert.throws(()=>m.parseAuthorityInput({...authority(),ownerApprovalId:'010-1234-5678'}),m.GrowthAuthorityError));
test('unresolved reservation below action amount is blocked',()=>assert.equal(evaluate(authority(),action(),[commitment({reservedAmount:1})]).allowed,false));
test('known larger amount in unknown state cannot be hidden',()=>assert.equal(evaluate(authority(),action(),[commitment({status:'unknown',actualAmount:600})]).allowed,false));
console.log(JSON.stringify({passed,failed:0,integration:'real pure policy; no execution or external calls'}));
