import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
let failKind='';
const {load,sql}=testRuntime(async()=>{throw Error('Execution preparation must not dispatch');},{beforeRun(statement){if(failKind&&statement.query.startsWith('INSERT INTO records')&&statement.values[2]===failKind)throw Error('Injected atomic write failure');}});
const server=await load('lib/server.ts'),growth=await load('app/api/growth/route.ts'),authorityRoute=await load('app/api/growth/authority/route.ts'),operations=await load('app/api/growth/operations/route.ts'),route=await load('app/api/growth/execution/route.ts');
let passed=0;const check=(condition,label)=>{assert.ok(condition,label);passed++;};
const owner='execution-owner',c={id:'c',brandId:'brand',storeId:'store',version:1,status:'active'},h={'oai-authenticated-user-id':owner,origin:'https://agency.test'};
await server.recordStatement(owner,'campaign','c',c).run();
await server.recordStatement(owner,'store','store',{id:'store',brandId:'brand'}).run();
const unpack=async r=>({status:r.status,body:await r.json()});
const call=(target,data,headers=h)=>target.POST(new Request('https://agency.test/api/growth/execution',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,expectedVersion:0,...data})})).then(unpack);
const post=(data,headers=h)=>call(route,data,headers),gp=data=>call(growth,data);
const get=(headers=h)=>route.GET(new Request('https://agency.test/api/growth/execution?campaignId=c',{headers})).then(unpack);
const before=new Date(Date.now()-86400000).toISOString(),after=new Date(Date.now()+30*86400000).toISOString();
const mandate={accountId:'account-one',channel:'storefront',status:'active',maxTier:'T3',allowedActions:['publish','spend'],startsAt:before,expiresAt:after,periodStart:before,periodEnd:after,totalCap:100,dayCap:100,weekCap:100,lossCap:20};
check((await call(authorityRoute,{action:'save_authority',id:'auth',sign:true,input:mandate})).status===200,'signed authority');
const signal={title:'시장 근거',sourceUrl:'https://example.com/market',observedAt:before,expiresAt:'2099-01-01',sourceType:'market',summary:'공개 시장 관측',sampleSize:null};
check((await gp({action:'save_signal',id:'s',input:signal})).status===200,'signal fixture');
check((await gp({action:'save_need',id:'n',input:{title:'니즈 가설',situation:'상황',desiredOutcome:'원하는 결과',alternative:'대안',barrier:'장애물',counterEvidence:'반례',signalIds:['s'],deadline:'2099-01-01',nextAction:'검증',assignee:'검토 담당'}})).status===200,'need fixture');
await server.recordStatement(owner,'brand_fact','f',{id:'f',brandId:'brand',key:'product',value:'상품',status:'confirmed',source:'운영 확인',version:1,verifiedAt:'2026-01-01',validUntil:'2099-01-01'},'brand').run();
check((await gp({action:'save_catalog',id:'p',input:{sku:'SKU',title:'상품',price:100,unitCost:20,variableCost:10,stock:20,stockUnit:'piece',currency:'KRW',taxBasis:'included',fulfillment:'배송 조건',refunds:'반품 조건',rightsConfirmed:true,factIds:['f'],validUntil:'2099-01-01'}})).status===200,'product fixture');
check((await gp({action:'save_offer',id:'o',input:{title:'오퍼',catalogId:'p',catalogVersion:1,needId:'n',price:100,quantity:1,landingUrl:'https://example.com/buy',purchaseReason:'구매 이유',priceApproved:true}})).status===200,'offer fixture');
const mission={title:'판매 미션',offerId:'o',offerVersion:1,assignee:'판매 담당',deadline:'2099-01-01',nextAction:'판매 준비',channel:'storefront',budget:60,lossLimit:4,stopRule:'한도 도달',fulfillmentOwner:'배송 담당'};
async function makeMission(id,input=mission){check((await gp({action:'save_mission',id,input})).status===200,'mission fixture '+id);check((await gp({action:'queue_mission',id,expectedVersion:1})).status===200,'staged fixture '+id);}


const created=await call(operations,{action:'create_inventory',input:{sku:'SKU',locationId:'store',unit:'piece',onHand:10},observedAt:before,evidenceRef:'stock-evidence'});
check(created.status===200,'inventory fixture '+JSON.stringify(created));
const inventoryId=created.body.inventory[0].id;
await makeMission('m');
const input={missionId:'m',missionVersion:2,authorityId:'auth',authorityVersion:1,inventoryId,inventoryVersion:1,quantity:3,recoveryOwner:'운영 담당',recoveryDueAt:after,evidenceRef:'prepare-evidence'};
const prep={action:'prepare_execution',input};
check((await get({})).status===401,'anonymous denied');
check((await get({'oai-authenticated-user-id':'foreign'})).status===404,'owner isolation');
check((await post(prep,{...h,origin:'https://evil.test'})).status===403,'csrf denied');
check((await post({...prep,input:{...input,quantity:0}})).status===400,'positive quantity');
check((await post({...prep,input:{...input,inventoryVersion:0}})).status===409,'stale inventory');
check((await post({...prep,input:{...input,quantity:11}})).status===409,'insufficient stock');
check(sql.prepare("SELECT count(*) n FROM records WHERE owner=? AND kind='growth_commitment'").get(owner).n===0,'no budget after stock failure');
check((await post({...prep,input:{...input,missionVersion:1}})).status===409,'stale mission');
check((await post({...prep,input:{...input,authorityVersion:2}})).status===409,'stale authority');
const originalAuthority=await server.readRecord(owner,'growth_authority','auth');
await server.recordStatement(owner,'growth_authority','auth',{...originalAuthority,input:{...originalAuthority.input,expiresAt:before}},'c').run();
check((await post(prep)).status===409,'expired authority denied');
await server.recordStatement(owner,'growth_authority','auth',{...originalAuthority,campaignId:'other'},'c').run();
check((await post(prep)).status===404,'cross scope authority denied');
await server.recordStatement(owner,'growth_authority','auth',originalAuthority,'c').run();
const originalInventory=await server.readRecord(owner,'growth_inventory_item',inventoryId);
const sourceCatalog=await server.readRecord(owner,'growth_catalog','p');
await server.recordStatement(owner,'growth_catalog','p',{...sourceCatalog,input:{...sourceCatalog.input,sku:'sk-abcdefgh'}},'c').run();
await server.recordStatement(owner,'growth_inventory_item',inventoryId,{...originalInventory,input:{...originalInventory.input,sku:'sk-abcdefgh'}},'store').run();
check((await post(prep)).status===400,'legacy secret SKU snapshot denied');
await server.recordStatement(owner,'growth_catalog','p',sourceCatalog,'c').run();
await server.recordStatement(owner,'growth_inventory_item',inventoryId,originalInventory,'store').run();

await server.recordStatement(owner,'growth_inventory_item',inventoryId,{...originalInventory,brandId:'foreign'},'store').run();
check((await post(prep)).status===404,'cross brand inventory denied');
await server.recordStatement(owner,'growth_inventory_item',inventoryId,originalInventory,'store').run();
for(const kind of ['growth_stock_event','growth_action_intent','growth_action_receipt']){
 failKind=kind;check((await post(prep)).status===500,'injected batch failure '+kind);failKind='';
 check(sql.prepare("SELECT count(*) n FROM records WHERE owner=? AND kind='growth_commitment'").get(owner).n===0,'budget rolled back '+kind);
 check((await server.readRecord(owner,'growth_inventory_item',inventoryId)).version===1,'inventory rolled back '+kind);
}
let r=await post(prep);check(r.status===200,'prepared '+JSON.stringify(r));
const intent=r.body.intents[0];
check(intent.state==='prepared'&&intent.version===1&&r.body.mayExecute===false,'local preparation state');
check(r.body.inventory[0].projection.reserved===3,'shared inventory reserved');
check(sql.prepare("SELECT count(*) n FROM records WHERE owner=? AND kind='growth_commitment'").get(owner).n===1,'one budget commitment');
r=await post(prep);check(r.status===200&&r.body.duplicate,'identical retry');
check((await post({...prep,input:{...input,quantity:4}})).status===409,'conflicting retry');
check((await gp({action:'cancel_mission',id:'m',expectedVersion:2})).status===409,'legacy cancellation blocked');
await makeMission('m2');
check((await post({...prep,input:{...input,missionId:'m2',inventoryVersion:2}})).status===409,'shared budget cap');
const releases={action:'release_stock',id:'early-release',inventoryId,inventoryVersion:2,reservationId:intent.reservationId,missionId:'m',missionVersion:2,quantity:3,safeRelease:true,evidenceRef:'release-evidence',observedAt:new Date().toISOString()};
check((await call(operations,releases)).status===409,'prepared intent cannot release');
const receipt={action:'record_execution_receipt',id:intent.id,receiptId:'result-one',expectedVersion:1,input:{status:'unknown',reference:'provider-ref',note:'외부 확인 대기'}};
r=await post(receipt);check(r.status===200&&r.body.intents[0].state==='unknown','unknown recorded '+JSON.stringify(r));
check(r.body.inventory[0].projection.reserved===3,'unknown keeps inventory');
check((await server.readRecord(owner,'growth_mission','m')).status==='unknown','mission reconciled atomically');
check((await call(operations,{...releases,missionVersion:3})).status===409,'unknown intent cannot release');
failKind='growth_history';
check((await post({...receipt,receiptId:'rollback-result',expectedVersion:2,input:{status:'failed',reference:'ref',note:'실패'}})).status===500,'receipt batch failure');failKind='';
check((await server.readRecord(owner,'growth_action_intent',intent.id)).version===2,'intent receipt rollback');
check((await server.readRecord(owner,'growth_mission','m')).version===3,'mission receipt rollback');
check((await post(receipt)).body.duplicate,'receipt retry idempotent');
check((await post({...receipt,input:{...receipt.input,note:'changed'}})).status===409,'conflicting receipt');
check((await gp({action:'record_receipt',id:'m',expectedVersion:3,status:'failed',reference:'ref',note:'fail'})).status===409,'legacy receipt bypass blocked');
const concurrent=await Promise.all([post(receipt),post(receipt)]);
check(concurrent.some(row=>row.status===200)&&concurrent.every(row=>[200,409].includes(row.status)),'owner lock concurrent duplicate');
await call(authorityRoute,{action:'revoke_authority',id:'auth',expectedVersion:1});
await server.recordStatement(owner,'campaign','c',{...c,status:'archived'}).run();
check((await post({...prep,input:{...input,missionId:'m2',authorityVersion:2,inventoryVersion:2}})).status===409,'archived prepare denied');
r=await post({...receipt,receiptId:'result-two',expectedVersion:2,input:{status:'failed',reference:'failed-ref',note:'운영자가 실패를 확인'}});
check(r.status===200&&r.body.intents[0].state==='failed','recovery after revoke archive '+JSON.stringify(r));
check(r.body.inventory[0].projection.reserved===3,'failed does not automatically release');
check((await post({...receipt,receiptId:'result-three',expectedVersion:3})).status===409,'terminal frozen');
check((await get()).body.receipts.length===3,'immutable prepare and receipt history');
await server.recordStatement(owner,'campaign','c',c).run();
await server.recordStatement(owner,'growth_authority','auth',originalAuthority,'c').run();
await makeMission('adopt',{...mission,budget:1,lossLimit:0});
check((await call(authorityRoute,{action:'reserve_mission',authorityId:'auth',expectedVersion:1,missionId:'adopt',missionVersion:2})).status===200,'legacy budget fixture');
const countBefore=sql.prepare("SELECT count(*) n FROM records WHERE owner=? AND kind='growth_commitment'").get(owner).n;
r=await post({...prep,input:{...input,missionId:'adopt',quantity:1,inventoryVersion:2}});
check(r.status===200,'identical legacy budget adopted '+JSON.stringify(r));
check(sql.prepare("SELECT count(*) n FROM records WHERE owner=? AND kind='growth_commitment'").get(owner).n===countBefore,'budget not duplicated');
const adopted=r.body.intents.find(row=>row.input.missionId==='adopt');
r=await post({...receipt,id:adopted.id,receiptId:'observed',expectedVersion:1,input:{status:'observed',reference:'observed-evidence',note:'운영 결과 확인'}});
check(r.status===200&&r.body.intents.find(row=>row.id===adopted.id).state==='observed','observed result supported');
check((await post({...receipt,id:adopted.id,receiptId:'reopen',expectedVersion:2})).status===409,'observed cannot reopen');
await makeMission('oldstock',{...mission,budget:1,lossLimit:0});
const stockHold={action:'reserve_stock',id:'legacy-stock',inventoryId,inventoryVersion:3,missionId:'oldstock',missionVersion:2,quantity:1,evidenceRef:'legacy-evidence',observedAt:new Date().toISOString()};
check((await call(operations,stockHold)).status===200,'legacy stock fixture');
check((await post({...prep,input:{...input,missionId:'oldstock',quantity:1,inventoryVersion:4}})).status===409,'existing stock reservation refused');
const stockMission=await server.readRecord(owner,'growth_mission','oldstock');
await server.recordStatement(owner,'growth_mission','oldstock',{...stockMission,status:'failed'},'c').run();
check((await call(operations,{...stockHold,action:'release_stock',id:'legacy-release',reservationId:'legacy-stock',inventoryVersion:4,safeRelease:true,observedAt:new Date().toISOString()})).status===200,'old stock release fixture');
await server.recordStatement(owner,'growth_mission','oldstock',stockMission,'c').run();
check((await post({...prep,input:{...input,missionId:'oldstock',quantity:1,inventoryVersion:5}})).status===409,'released old reservation also refused');
check(sql.prepare("SELECT count(*) n FROM records WHERE owner=? AND kind='growth_commitment'").get(owner).n===countBefore,'old stock refusal no budget write');
await makeMission('historycap',{...mission,budget:1,lossLimit:0});
const historyTemplate=(await get()).body.receipts[0];
const historyCount=sql.prepare("SELECT count(*) n FROM records WHERE owner=? AND kind='growth_action_receipt'").get(owner).n;
for(let i=historyCount;i<5000;i++){const id='history-cap-'+i;await server.recordStatement(owner,'growth_action_receipt',id,{...historyTemplate,id},'c').run();}
check((await post({...prep,input:{...input,missionId:'historycap',quantity:1,inventoryVersion:5}})).status===409,'prepare refuses full receipt history before writes');
check(sql.prepare("SELECT count(*) n FROM records WHERE owner=? AND kind='growth_action_receipt'").get(owner).n===5000,'receipt cap no excess row');
check(sql.prepare("SELECT count(*) n FROM records WHERE owner=? AND kind='growth_commitment'").get(owner).n===countBefore,'receipt cap no budget write');
console.log(JSON.stringify({passed,storage:'real memory SQL',auth:'mocked',externalCalls:0}));
