import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
const {load,sql,env}=testRuntime(async()=>{throw Error('Authority reservations must never dispatch');});
const server=await load('lib/server.ts'),growth=await load('app/api/growth/route.ts'),route=await load('app/api/growth/authority/route.ts');
let passed=0;const check=(condition,label)=>{assert.ok(condition,label);passed++;};
const owner='authority-owner',c={id:'c',brandId:'brand',version:1,status:'active',storeId:'fixture-store'},h={'oai-authenticated-user-id':owner,origin:'https://agency.test'};
await server.recordStatement(owner,'campaign','c',c).run();
await server.recordStatement(owner,'store','fixture-store',{id:'fixture-store',brandId:'brand'}).run();
await server.recordStatement(owner,'growth_inventory_item','fixture-stock',{id:'fixture-stock',brandId:'brand',storeId:'fixture-store',version:0,input:{sku:'SKU',locationId:'fixture-store',unit:'piece',onHand:20}},'fixture-store').run();
await server.recordStatement(owner,'campaign','other',{...c,id:'other'}).run();
const unpack=async r=>({status:r.status,body:await r.json()});
const post=(data,headers=h)=>route.POST(new Request('https://agency.test/api/growth/authority',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,expectedVersion:0,...data})})).then(unpack);
const get=(headers=h)=>route.GET(new Request('https://agency.test/api/growth/authority?campaignId=c',{headers})).then(unpack);
const gp=data=>growth.POST(new Request('https://agency.test/api/growth',{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,expectedVersion:0,...data})})).then(unpack);
const before=new Date(Date.now()-86400000).toISOString(),after=new Date(Date.now()+30*86400000).toISOString();
const mandate={accountId:'account-one',channel:'storefront',status:'active',maxTier:'T3',allowedActions:['publish','spend'],startsAt:before,expiresAt:after,periodStart:before,periodEnd:after,totalCap:1000,dayCap:1000,weekCap:1000,lossCap:100};
const save={action:'save_authority',id:'auth-1',sign:true,input:mandate};
check((await post({...save,id:'read-only',input:{...mandate,maxTier:'T0',allowedActions:['read']}})).status===200,'T0 read-only active mandate supported');
check((await post({...save,id:'draft-only',input:{...mandate,maxTier:'T1',allowedActions:['draft']}})).status===200,'T1 draft active mandate supported');
check((await post({...save,id:'tier-bypass',input:{...mandate,maxTier:'T0',allowedActions:['read','spend']}})).status===400,'every grant checked against tier');
check((await post({...save,id:'t4',input:{...mandate,allowedActions:['publish','policy_change']}})).status===400,'T4 grant refused');
check((await post({...save,id:'scale',input:{...mandate,allowedActions:['scale']}})).status===400,'unsupported scale grant refused');
check((await post({...save,id:'read-invalid',input:{...mandate,maxTier:'T0',allowedActions:['read'],periodEnd:''}})).status===400,'read-only mandate still needs explicit period');
check((await get({})).status===401,'anonymous rejected');
check((await get({'oai-authenticated-user-id':'other-owner'})).status===404,'owner isolation');
check((await post(save,{...h,origin:'https://evil.test'})).status===403,'origin checked');
check((await post({...save,sign:false})).status===400,'explicit owner signing required');
check((await post({...save,input:{...mandate,totalCap:null}})).status===400,'active authority cannot have unknown cap');
check((await post({...save,input:{...mandate,totalCap:-1}})).status===400,'negative cap refused');
let r=await post({...save,input:{...mandate,id:'spoof',campaignId:'other',brandId:'spoof',ownerApprovalId:'client-forged',ownerSignedAt:before}});
check(r.status===200,'owner authority saved '+JSON.stringify(r));
const authority=r.body.authorities.find(a=>a.id==='auth-1');
check(authority.input.id==='auth-1'&&authority.input.campaignId==='c'&&authority.input.brandId==='brand','scope stamped');
check(authority.input.ownerApprovalId!=='client-forged'&&authority.input.ownerSignedAt!==before,'server stamps signature');
check(r.body.mayExecute===false&&r.body.canAuthorize&&r.body.canReserve,'local authority only');
check((await post(save)).status===409,'stale authority revision rejected');
check((await post({...save,campaignId:'other',expectedVersion:1})).status===404,'cross campaign authority denied');
check((await post({action:'reserve_mission',authorityId:'auth-1',missionId:'missing',missionVersion:1,expectedVersion:1})).status===404,'mission must exist');
const signal={title:'시장 근거',sourceUrl:'https://example.com/market',observedAt:before,expiresAt:'2099-01-01',sourceType:'market',summary:'공개 시장 관측',sampleSize:null};
check((await gp({action:'save_signal',id:'s',input:signal})).status===200,'signal fixture');
check((await gp({action:'save_need',id:'n',input:{title:'니즈 가설',situation:'상황',desiredOutcome:'원하는 결과',alternative:'대안',barrier:'장애물',counterEvidence:'반례',signalIds:['s'],deadline:'2099-01-01',nextAction:'검증',assignee:'검토 담당'}})).status===200,'need fixture');
await server.recordStatement(owner,'brand_fact','f',{id:'f',brandId:'brand',key:'product',value:'상품',status:'confirmed',source:'운영 확인',version:1,verifiedAt:'2026-01-01',validUntil:'2099-01-01'},'brand').run();
check((await gp({action:'save_catalog',id:'p',input:{sku:'SKU',title:'상품',price:100,unitCost:20,variableCost:10,stock:20,stockUnit:'piece',currency:'KRW',taxBasis:'included',fulfillment:'배송 조건',refunds:'반품 조건',rightsConfirmed:true,factIds:['f'],validUntil:'2099-01-01'}})).status===200,'product fixture');
check((await gp({action:'save_offer',id:'o',input:{title:'오퍼',catalogId:'p',catalogVersion:1,needId:'n',price:100,quantity:1,landingUrl:'https://example.com/buy',purchaseReason:'구매 이유',priceApproved:true}})).status===200,'offer fixture');
const mission={title:'판매 미션',offerId:'o',offerVersion:1,assignee:'판매 담당',deadline:'2099-01-01',nextAction:'판매 준비',channel:'storefront',budget:600,lossLimit:40,stopRule:'한도 도달',fulfillmentOwner:'배송 담당'};
async function makeMission(id,input=mission){check((await gp({action:'save_mission',id,input})).status===200,'mission fixture '+id);check((await gp({action:'queue_mission',id,expectedVersion:1})).status===200,'staged fixture '+id);}
await makeMission('m');
const reserve={action:'reserve_mission',authorityId:'auth-1',missionId:'m',missionVersion:2,expectedVersion:1};
check((await post({...reserve,expectedVersion:0})).status===409,'reservation must match authority version reviewed');
check((await post({...reserve,missionVersion:1})).status===409,'stale mission refused');
r=await post({...reserve,input:{amount:0,accountId:'forged'}});
check(r.status===200,'reservation saved '+JSON.stringify(r));
check(r.body.commitments.length===1&&r.body.commitments[0].commitment.reservedAmount===600,'amount from mission');
check(r.body.commitments[0].commitment.action.accountId==='account-one','account from authority');
check(r.body.commitments[0].commitment.status==='reserved'&&r.body.mayExecute===false,'reservation is not dispatch');
const deletion=await server.campaignDeletionPreview(owner,'c');
check(!deletion.deletable&&deletion.blockedReason.includes('성장'),'budget reservation prevents campaign deletion with growth guidance');
r=await post(reserve);check(r.status===200&&r.body.duplicate&&r.body.commitments.length===1,'idempotent reservation');
const firstCommitment=r.body.commitments[0],originalMission=await server.readRecord(owner,'growth_mission','m');
await server.recordStatement(owner,'growth_mission','m',{...originalMission,input:{...originalMission.input,budget:601}},'c').run();
check((await post(reserve)).status===409,'same operation key with changed amount refused');
await server.recordStatement(owner,'growth_mission','m',originalMission,'c').run();
await makeMission('small',{...mission,budget:1,lossLimit:0});
const foreign={...firstCommitment,id:'other-campaign',campaignId:'other',missionId:'other-mission',commitment:{...firstCommitment.commitment,action:{...firstCommitment.commitment.action,id:'other-mission',operationKey:'other-mission:v2',campaignId:'other',amount:400,loss:0},reservedAmount:400,reservedLoss:0}};
await server.recordStatement(owner,'growth_commitment',foreign.id,foreign,'other').run();
check((await post({...reserve,missionId:'small'})).status===409,'other campaign same account consumes cap');
check((await get()).body.commitments.length===1,'view does not expose other campaign ledger');
sql.prepare("DELETE FROM records WHERE owner=? AND kind='growth_commitment' AND parent_id='other'").run(owner);
await makeMission('m2');
check((await post({...reserve,missionId:'m2'})).status===409,'aggregate cap blocks next mission');
check((await post({...save,id:'auth-2'})).status===200,'second signed authority');
check((await post({...reserve,authorityId:'auth-2'})).status===409,'same mission key cannot switch authority');
check((await post({...reserve,authorityId:'auth-2',missionId:'m2'})).status===409,'new authority cannot bypass account aggregate');
check((await post({...save,expectedVersion:1,input:{...mandate,accountId:'switched'}})).status===409,'reserved scope cannot change');
r=await post({...save,expectedVersion:1,input:{...mandate,totalCap:2000,dayCap:2000,weekCap:2000}});check(r.status===200&&r.body.commitments.length===1,'revision preserves reservations');
check(r.body.authorities.find(a=>a.id==='auth-1').input.ownerApprovalId!==authority.input.ownerApprovalId,'revision freshly signed');
check((await post({...reserve,missionId:'m2',expectedVersion:2})).status===200,'explicit cap revision permits remaining capacity');
check((await post({action:'revoke_authority',id:'auth-1',expectedVersion:2})).status===200,'owner revokes');
check((await post({...reserve,expectedVersion:3})).status===409,'revoked authority cannot reserve even duplicate');
check((await post({...save,expectedVersion:3})).status===409,'revoked authority cannot silently reactivate');
const expired={...mandate,expiresAt:before};
check((await post({...save,id:'expired',input:expired})).status===400,'expired activation refused');
check((await post({action:'release_commitment'})).status===400,'no unsupported budget release');
check((await post({...save,id:'auth-admin',input:{...mandate,accountId:'account-admin'}})).status===200,'separate owner approved account');
await makeMission('admin-mission',{...mission,budget:100,lossLimit:10});

env.AUTH_MODE='email';env.AUTH_ORIGIN='https://agency.test';
sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run('workspace-owner','owner@test.invalid',owner,'admin','active',1);
for(const role of ['admin','member']){
 const token=createHash('sha256').update('authority-'+role).digest('hex');
 sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run(role,role+'@test.invalid',owner,role,'active',1000);
 sql.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?)').run(createHash('sha256').update(token).digest('hex'),role,Date.now()+60000,Date.now());
 const headers={cookie:'__Host-collective_session='+token,origin:'https://agency.test'};
 const v=await get(headers);check(v.status===200&&!v.body.canAuthorize&&v.body.canReserve===(role==='admin'),'role view '+role);
 check((await post({...save,id:'role-'+role},headers)).status===403,'only owner signs '+role);
 check((await post({action:'revoke_authority',id:'auth-2',expectedVersion:1},headers)).status===403,'only owner revokes '+role);
 check((await post({...reserve,authorityId:'auth-2',missionId:'m2'},headers)).status===(role==='member'?403:409),'reservation role gate '+role);
 if(role==='admin')check((await post({...reserve,authorityId:'auth-admin',missionId:'admin-mission'},headers)).status===200,'admin can reserve within owner signed cap');
}
env.AUTH_MODE='legacy';
// Capacity limits are checked before a write; full views remain readable.
await server.recordStatement(owner,'campaign','capped',{...c,id:'capped'}).run();
for(let i=0;i<100;i++)await server.recordStatement(owner,'growth_authority','cap-'+i,{...authority,id:'cap-'+i,campaignId:'capped',input:{...authority.input,id:'cap-'+i,campaignId:'capped'}},'capped').run();
check((await post({...save,id:'cap-over',campaignId:'capped'})).status===409,'101st authority refused before write');
check(sql.prepare("SELECT count(*) n FROM records WHERE owner=? AND kind='growth_authority' AND parent_id='capped'").get(owner).n===100,'authority cap has no partial write');
const existingCount=sql.prepare("SELECT count(*) n FROM records WHERE owner=? AND kind='growth_commitment' AND parent_id='c'").get(owner).n;
for(let i=existingCount;i<1000;i++){
 const id='ledger-cap-'+i,entry={...firstCommitment,id,missionId:id,commitment:{...firstCommitment.commitment,action:{...firstCommitment.commitment.action,id,operationKey:id,accountId:'capacity-fixture',amount:0,loss:0},reservedAmount:0,reservedLoss:0}};
 await server.recordStatement(owner,'growth_commitment',id,entry,'c').run();
}
check((await get()).status===200,'full commitment view remains readable');
check((await post({...reserve,authorityId:'auth-admin',missionId:'small'})).status===409,'1001st reservation refused before write');
check(sql.prepare("SELECT count(*) n FROM records WHERE owner=? AND kind='growth_commitment' AND parent_id='c'").get(owner).n===1000,'commitment cap has no partial write');
await server.recordStatement(owner,'campaign','c',{...c,status:'archived'}).run();
check((await post({...save,id:'after-archive'})).status===409,'archived cannot mutate');
check(!(await get()).body.canReserve,'archived read disables reservations');
console.log(JSON.stringify({passed,dispatch:'never',storage:'memory SQL'}));
