import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
const {load}=testRuntime(async()=>{throw Error('No external calls')});
const {emptyDemandInput,emptyDemandStep,parseDemandInput,demandReadiness}=await load('lib/growth-demand.ts');
let passed=0;
const check=(value,label)=>{assert.ok(value,label);passed++};
const rejects=(value)=>{assert.throws(()=>parseDemandInput(value));passed++};
const step={...emptyDemandStep(),authenticityConfirmed:true,id:'step-a',message:'간편한 저녁 한 끼',useScene:'퇴근 후 식사',creativeBrief:'준비 과정을 보여주는 영상',keywords:['간편식'],audience:'저녁 준비 시간을 줄이려는 직장인',purchaseUrl:'https://shop.example.com/products/meal',sourceUrls:['https://research.example.com/report'],rightsStatus:'confirmed',rightsEvidence:'승인 문서 ref-a',plannedCost:0};
const input={...emptyDemandInput(),title:'저녁 식사 수요',offerId:'offer-a',offerVersion:1,missionId:'mission-a',missionVersion:2,objective:'구매 경로 방문 관찰',steps:[step]};
check(parseDemandInput({}).steps.length===0,'empty draft is permitted');
check(demandReadiness(emptyDemandInput(),[]).missing.length>0,'empty draft never ready');
check(emptyDemandStep().plannedCost===null,'unknown spend default');
const ready=demandReadiness(input,[]);
check(ready.missing.length===0&&ready.plannedCost===0&&ready.mayExecute===false,'ready local preparation never grants dispatch');
check(demandReadiness(input,['상품 근거 만료']).missing.includes('상품 근거 만료'),'upstream blockers propagate');
check(demandReadiness({...input,steps:[{...step,plannedCost:null}]},[]).plannedCost===null,'unknown cost is not zero');
check(demandReadiness({...input,steps:[step,{...step,id:'step-b',plannedCost:3000}]},[]).plannedCost===3000,'explicit cost summed');
check(demandReadiness({...input,steps:[{...step,placement:'creator'}]},[]).missing.length>0,'creator requires role and terms');
check(demandReadiness({...input,steps:[{...step,placement:'partner',partnerRole:'콘텐츠 제작',partnerTerms:'승인 후 공개'}]},[]).missing.length===0,'partner documented terms');
for(const field of ['message','useScene','creativeBrief','audience','purchaseUrl','rightsEvidence','id'])check(demandReadiness({...input,steps:[{...step,[field]:''}]},[]).missing.length>0,`missing ${field}`);
for(const patch of [{sourceUrls:[]},{rightsStatus:'unknown'},{rightsStatus:'denied'}])check(demandReadiness({...input,steps:[{...step,...patch}]},[]).missing.length>0,'rights and sources required');
for(const patch of [{title:''},{offerId:''},{offerVersion:0},{missionId:''},{missionVersion:0},{objective:''}])check(demandReadiness({...input,...patch},[]).missing.length>0,'missing linkage');
for(const value of [null,[],true,'draft',{steps:{}},{steps:Array.from({length:13},(_,i)=>({...step,id:`step-${i}`}))},{steps:[step,step]},{offerVersion:'1'},{missionVersion:-1},{missionVersion:1.5},{offerId:'bad id'},{title:null}])rejects(value);
for(const patch of [{channel:'sms'},{placement:'email'},{rightsStatus:'yes'},{performanceStatus:'proven'},{plannedCost:'0'},{plannedCost:-1},{plannedCost:1.5},{plannedCost:Infinity},{keywords:'meal'},{sourceUrls:'https://example.com'},{id:'bad id'},{message:'person@example.com'},{rightsEvidence:'Bearer secret-token-value'},{message:'api_key=private-secret'},{performanceStatus:'observed',performanceEvidence:''}])rejects({...input,steps:[{...step,...patch}]});
for(const url of ['http://example.com','https://localhost/a','https://127.0.0.1/a','https://[::1]/a','https://shop.internal/a','https://x.example.com:444/a','https://user:pass@example.com','https://example.com?a=b','https://example.com#part','https://example.com/%70erson%40example.com','https://example.com/%ZZ','https://example.com/%2561pi_key%253Dsecret','https://example.com/path\\other']){
 rejects({...input,steps:[{...step,purchaseUrl:url}]});
 rejects({...input,steps:[{...step,sourceUrls:[url]}]});
}
check(parseDemandInput({...input,steps:[{...step,performanceStatus:'observed',performanceEvidence:'https://report.example.com/results',performanceNote:'조회 수 관찰; 매출 인과 미확인'}]}).steps[0].performanceStatus==='observed','observed evidence preserved without causal schema');
const frozen=Object.freeze({...input,steps:Object.freeze([Object.freeze({...step,keywords:Object.freeze([...step.keywords]),sourceUrls:Object.freeze([...step.sourceUrls])})])});
check(parseDemandInput(frozen).steps[0]!==frozen.steps[0],'input structures not mutated or shared');
check(parseDemandInput({...input,causalLift:200}).causalLift===undefined,'no causal claim field accepted');
rejects({...input,steps:[{...step,plannedCost:1_000_000_000_001}]});
check(demandReadiness({...input,steps:Array.from({length:12},(_,i)=>({...step,id:`cap-${i}`,plannedCost:1_000_000_000_000}))},[]).plannedCost===12_000_000_000_000,'maximum permitted costs sum exactly');
for(const patch of [{message:'x'.repeat(2001)},{message:'bad\u0001text'},{keywords:['']},{keywords:Array(31).fill('meal')},{sourceUrls:['']},{sourceUrls:Array(21).fill('https://example.com')},{message:'010-1234-5678'},{performanceStatus:'observed',performanceEvidence:'proof',performanceNote:''}])rejects({...input,steps:[{...step,...patch}]});
rejects({...input,offerVersion:null});
rejects({...input,steps:[null]});
rejects({...input,steps:[emptyDemandStep(),emptyDemandStep()]});
check(parseDemandInput({...input,steps:[{...step,keywords:['식사','식사']}]}).steps[0].keywords.length===1,'deduplicate keyword copies');
check(parseDemandInput({...input,steps:[{...step,purchaseUrl:'https://shop.example.com/%EC%8B%9D%EC%82%AC'}]}).steps[0].purchaseUrl.includes('%EC'),'safe encoded Unicode preserved');
check(parseDemandInput({...input,steps:Array.from({length:12},(_,i)=>({...step,id:`s-${i}`}))}).steps.length===12,'maximum step count accepted');
check(emptyDemandStep().authenticityConfirmed===false,'authenticity defaults unconfirmed');
rejects({...input,steps:[{...step,authenticityConfirmed:'true'}]});
check(demandReadiness({...input,steps:[{...step,authenticityConfirmed:false}]},[]).missing.length>0,'authenticity requires explicit confirmation');
for(const field of ['message','creativeBrief','partnerTerms'])for(const instruction of ['가짜 후기 작성','허위 참여 구매','fake review creation','buy fake engagement'])check(demandReadiness({...input,steps:[{...step,[field]:instruction}]},[]).missing.length>0,'explicit fabricated engagement instruction blocked despite confirmation');
check(demandReadiness({...input,steps:[{...step,creativeBrief:'가짜 후기 금지. 실제 사용 장면만 촬영'}]},[]).missing.length===0,'prohibition is not an instruction to fabricate');
for(const prohibition of ['가짜 후기 작성 금지','do not buy fake engagement','never create fake reviews'])check(demandReadiness({...input,steps:[{...step,creativeBrief:prohibition}]},[]).missing.length===0,'explicit prohibition does not block');
check(demandReadiness({...input,steps:[{...step,creativeBrief:'가짜 후기 작성 금지. 하지만 buy fake engagement'}]},[]).missing.length>0,'unrelated prohibition cannot bypass positive instruction');
console.log(JSON.stringify({passed}));
