import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
const {load,sql,env}=testRuntime(async()=>{throw Error('Decisions cannot dispatch')});
const server=await load('lib/server.ts'),route=await load('app/api/growth/decisions/route.ts'),domain=await load('lib/growth-decisions.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='decisions-owner',c={id:'c',brandId:'b',version:1,status:'active'},h={'oai-authenticated-user-id':owner,origin:'https://agency.test'};
await server.recordStatement(owner,'campaign','c',c).run();await server.recordStatement(owner,'campaign','other',{...c,id:'other',brandId:'elsewhere'}).run();
const unpack=async r=>({status:r.status,body:await r.json()});
const post=(data,headers=h)=>route.POST(new Request('https://agency.test/api/growth/decisions',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,expectedVersion:0,...data})})).then(unpack);
const get=(headers=h)=>route.GET(new Request('https://agency.test/api/growth/decisions?campaignId=c',{headers})).then(unpack);
check((await get({})).status===401,'anonymous refused');check((await get({'oai-authenticated-user-id':'foreign'})).status===404,'owner isolation');check((await post({action:'save_decision'},{...h,origin:'https://evil.test'})).status===403,'CSRF');
const input=domain.emptyDecisionInput(),lesson=domain.emptyLessonInput();
const save={action:'save_decision',id:'decision',input,snapshot:{business:{cash:999999}}};
let r=await post(save);check(r.status===200,'save '+JSON.stringify(r));check(r.body.decisions[0].snapshot.business.cash===null,'client fabricated cash ignored');check(r.body.mayExecute===false,'never dispatch');
const frozen=r.body.decisions[0].snapshot,digest=r.body.decisions[0].snapshotDigest;
check(typeof digest==='string'&&digest.length===64,'snapshot digest');check((await post(save)).body.duplicate,'retry idempotent');check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_decision_history'").get().n===1,'retry no history');
check((await post({...save,input:{...input,title:'동시 변경'}})).status===409,'CAS');check((await post({...save,campaignVersion:2})).status===409,'campaign CAS');check((await post({...save,campaignId:'other',expectedVersion:1})).status===404,'scope');
check((await post({...save,id:'missing',input:{...input,missionId:'absent',missionVersion:1}})).status===404,'foreign mission');
r=await post({action:'save_lesson',id:'lesson',input:{...lesson,decisionId:'decision',decisionVersion:1}});check(r.status===200,'lesson decision link '+JSON.stringify(r));
check((await post({action:'save_lesson',id:'bad',input:{...lesson,decisionId:'decision',decisionVersion:2}})).status===409,'decision version exact');
check((await post({...save,expectedVersion:1,input:{...input,title:'검토 수정'}})).status===200,'revise');r=await get();check(r.body.lessons[0].assessment.missing.some(x=>x.includes('결정 변경')),'stale decision holds lesson');check(!r.body.lessons[0].assessment.canReuse,'stale lesson never reusable');
const history=JSON.parse(sql.prepare("SELECT data FROM records WHERE kind='growth_decision_history' ORDER BY id LIMIT 1").get().data);assert.deepEqual(history.snapshot,frozen);passed++;check(history.snapshotDigest===digest,'old snapshot unchanged');check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_decision_history'").get().n===2,'append-only');
check((await server.campaignDeletionPreview(owner,'c')).deletable,'planning deletion');check((await post({...save,id:'bad id'})).status===400,'invalid id');check((await post({...save,id:'external',action:'execute'})).status===400,'no execution surface');
const lock=await server.acquireLock(owner);check((await post({...save,id:'locked'})).status===409,'lock contention');await server.releaseLock(owner,lock);
for(const [kind,action,draft] of [['growth_decision','save_decision',input],['growth_lesson','save_lesson',lesson]]){
 const cid=kind+'-cap';await server.recordStatement(owner,'campaign',cid,{...c,id:cid}).run();
 for(let i=0;i<500;i++)await server.recordStatement(owner,kind,cid+i,{id:cid+i,brandId:'b',campaignId:cid,campaignVersion:1,version:1,input:draft},cid).run();
 check((await post({action,id:cid+'over',campaignId:cid,input:draft})).status===409,'500 cap '+kind);
 check(sql.prepare('SELECT COUNT(*) n FROM records WHERE kind=? AND parent_id=?').get(kind,cid).n===500,'no partial cap write');
}
const md=await load('lib/growth-mission.ts'),jd=await load('lib/growth-journey.ts');
const missionInput={...md.emptyMissionInput(),title:'중단된 판매 계획'};
const missionRow={id:'mission',brandId:'b',campaignId:'c',campaignVersion:1,version:1,input:missionInput,status:'failed'};
await server.recordStatement(owner,'growth_mission','mission',missionRow,'c').run();
const journeyInput={...jd.emptyJourneyInput(),title:'실패한 구매 관측',missionId:'mission',missionVersion:1};
await server.recordStatement(owner,'growth_journey','journey',{id:'journey',brandId:'b',campaignId:'c',campaignVersion:1,version:1,input:journeyInput},'c').run();
const completeDecision={...input,title:'판매 중단',decision:'stop',reason:'손실 관측',observation:'운영 결과 집계',alternativeExplanation:'유입 변화',missionId:'mission',missionVersion:1,journeyId:'journey',journeyVersion:1,nextAction:'원인 검토',assignee:'운영 담당',dueAt:'2099-01-01'};
r=await post({action:'save_decision',id:'failed-decision',input:completeDecision});check(r.status===200,'failed mission stop saved '+JSON.stringify(r));check(r.body.decisions.find(x=>x.id==='failed-decision').assessment.missing.length===0,'failed/incomplete readiness does not gate decision');
const completeLesson={...lesson,title:'실패한 방법',method:'판매 안내 검토',hypothesis:'문의 감소',scope:'합성 관측',falsificationRule:'문의 증가 시 중단',lossLimit:0,sourceType:'decision',evidenceLevel:'operational_observation',missionId:'mission',missionVersion:1,journeyId:'journey',journeyVersion:1,decisionId:'failed-decision',decisionVersion:1,sourceEvidence:'운영 집계',counterEvidence:'유입 변화',expiresAt:'2099-01-01',state:'reusable',outcome:'failure',testPlan:'문의 집계 비교',testResult:'문의 증가',nextAction:'다른 안내 시험',assignee:'운영 담당',dueAt:'2099-01-01'};
r=await post({action:'save_lesson',id:'failed-lesson',input:completeLesson});check(r.status===200,'failure lesson saved');check(r.body.lessons.find(x=>x.id==='failed-lesson').assessment.canReuse,'valid failed trial is reusable negative lesson');
const savedSnapshot=r.body.lessons.find(x=>x.id==='failed-lesson').snapshot;
check((await post({action:'save_lesson',id:'missing-refs',input:{...completeLesson,missionId:'',missionVersion:0,journeyId:'',journeyVersion:0}})).status===409,'decision source cannot omit its refs');
check((await post({action:'save_decision',id:'mismatched',input:{...completeDecision,missionId:'',missionVersion:0}})).status===409,'journey source requires exact mission chain');
for(const status of ['unknown','cancelled']){
 await server.recordStatement(owner,'growth_mission','mission',{...missionRow,status},'c').run();
 r=await get();check(r.body.lessons.find(x=>x.id==='failed-lesson').assessment.canReuse,status+' not forbidden learning source');
}
await server.recordStatement(owner,'growth_mission','mission',{...missionRow,version:2,input:{...missionInput,title:'새 계획'}},'c').run();
r=await get();check(!r.body.lessons.find(x=>x.id==='failed-lesson').assessment.canReuse,'reference revision holds reuse');assert.deepEqual(r.body.lessons.find(x=>x.id==='failed-lesson').snapshot,savedSnapshot);passed++;
check((await post({action:'save_decision',id:'old-mission',input:completeDecision})).status===409,'stale mission save refused');
await server.recordStatement(owner,'growth_mission','mission',missionRow,'c').run();
await server.recordStatement(owner,'campaign','c',{...c,version:2}).run();r=await get();check(!r.body.lessons.find(x=>x.id==='failed-lesson').assessment.canReuse,'campaign revision holds reuse');await server.recordStatement(owner,'campaign','c',c).run();
await server.recordStatement(owner,'growth_decision','cross-brand',{id:'cross-brand',brandId:'foreign',campaignId:'c',version:1,input},'other').run();check((await post({...save,id:'cross-brand',expectedVersion:1})).status===404,'stored brand mismatch refused');
check((await post({...save,id:'pii',input:{...input,reason:'person@example.com'}})).status===400,'PII rejected');
await server.recordStatement(owner,'growth_mission','mission',{...missionRow,input:{...missionInput,nextAction:'api_key=synthetic-secret'}},'c').run();
check((await post({action:'save_decision',id:'unsafe-source',input:completeDecision})).status===400,'unsafe legacy mission source cannot enter snapshot');
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_decision' AND json_extract(data,'$.id')='unsafe-source'").get().n===0,'unsafe snapshot writes nothing');
await server.recordStatement(owner,'growth_mission','mission',missionRow,'c').run();
const offerRow={id:'source-offer',brandId:'b',campaignId:'c',campaignVersion:1,version:1,input:{title:'실패 오퍼',catalogId:'',catalogVersion:0,needId:'',price:0,quantity:1,landingUrl:'',purchaseReason:'',priceApproved:false}};
await server.recordStatement(owner,'growth_offer','source-offer',offerRow,'c').run();
const linkedMission={...missionRow,input:{...missionInput,offerId:'source-offer',offerVersion:1}};
await server.recordStatement(owner,'growth_mission','mission',linkedMission,'c').run();
r=await get();check(r.body.lessons.find(x=>x.id==='failed-lesson').assessment.canReuse,'incomplete offer still valid failed learning source');
await server.recordStatement(owner,'growth_offer','source-offer',{...offerRow,version:2},'c').run();
r=await get();check(!r.body.lessons.find(x=>x.id==='failed-lesson').assessment.canReuse,'transitive offer revision invalidates lesson');
await server.recordStatement(owner,'growth_mission','mission',missionRow,'c').run();
const cd=await load('lib/growth-catalog.ts'),market=await load('lib/growth-market.ts');
const baseSource={brandId:'b',campaignId:'c',campaignVersion:1,version:1};
const catalogRow={...baseSource,id:'source-catalog',input:{...cd.emptyCatalogInput(),factIds:['fact']},factRefs:[{id:'fact',version:1}]};
const needRow={...baseSource,id:'source-need',input:{...market.emptyNeedInput(),signalIds:['signal']},evidenceRefs:[{id:'signal',version:1}]};
const signalRow={...baseSource,id:'signal',input:market.emptySignalInput()};
const factRow={id:'fact',brandId:'b',key:'product',value:'합성 상품',source:'운영자 확인',status:'confirmed',version:1,verifiedAt:'2026-01-01',validUntil:'2099-01-01'};
const fullOffer={...offerRow,input:{...offerRow.input,catalogId:'source-catalog',catalogVersion:1,needId:'source-need'},evidenceRefs:[{id:'source-need',version:1}]};
for(const [kind,row,parent] of [['growth_catalog',catalogRow,'c'],['growth_need',needRow,'c'],['growth_signal',signalRow,'c'],['brand_fact',factRow,'b'],['growth_offer',fullOffer,'c'],['growth_mission',linkedMission,'c']])await server.recordStatement(owner,kind,row.id,row,parent).run();
r=await get();check(r.status===200&&r.body.lessons.find(x=>x.id==='failed-lesson').assessment.canReuse,'full lineage incomplete readiness still learnable '+JSON.stringify(r));
for(const [kind,row,parent] of [['growth_catalog',catalogRow,'c'],['growth_need',needRow,'c'],['growth_signal',signalRow,'c'],['brand_fact',factRow,'b']]){
 await server.recordStatement(owner,kind,row.id,{...row,version:2},parent).run();r=await get();check(!r.body.lessons.find(x=>x.id==='failed-lesson').assessment.canReuse,'transitive '+kind+' revision holds lesson');
 await server.recordStatement(owner,kind,row.id,row,parent).run();
}
await server.recordStatement(owner,'growth_mission','mission',missionRow,'c').run();
const token=createHash('sha256').update('decisions-member').digest('hex');env.AUTH_MODE='email';env.AUTH_ORIGIN='https://agency.test';sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run('member','member@test.invalid',owner,'member','active',1);sql.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?)').run(createHash('sha256').update(token).digest('hex'),'member',Date.now()+60000,Date.now());
const member={cookie:'__Host-collective_session='+token,origin:'https://agency.test'};check(!(await get(member)).body.canEdit,'member read-only');check((await post({...save,id:'member'},member)).status===403,'member refused');env.AUTH_MODE='legacy';
await server.recordStatement(owner,'campaign','c',{...c,status:'archived'}).run();check((await post({...save,expectedVersion:2})).status===409,'archived refused');check(!(await get()).body.canEdit,'archived disabled');
console.log(JSON.stringify({passed,external:'not_called'}));
