// 수요 시퀀스 단계 ↔ 정확한 자체 발행 연결 근거(G2-19/27/28/11). 인증·외부는 mocked, 메모리 SQL은 real.
import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {testRuntime} from './helpers/runtime.mjs';
let failKind='';const {load,sql}=testRuntime(async()=>{throw Error('external forbidden')},{beforeRun(s){if(failKind&&s.values[2]===failKind&&s.query.startsWith('INSERT INTO records'))throw Error('atomic failure')}});
const s=await load('lib/server.ts'),route=await load('app/api/growth/demand-evidence/route.ts'),pure=await load('lib/growth-demand-evidence.ts');let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='owner',headers={'oai-authenticated-user-id':owner,origin:'https://agency.test'},c={id:'c',brandId:'b',storeId:'store',version:1,status:'active'},at='2026-09-20T03:00:00.000Z';
const put=(kind,id,data,parent='')=>s.recordStatement(owner,kind,id,data,parent).run();
const step={id:'s1',channel:'organic',placement:'owned',message:'점심 한 그릇',useScene:'평일 점심',creativeBrief:'실사',keywords:[],audience:'직장인',purchaseUrl:'https://shop.example.com/p',sourceUrls:['https://shop.example.com/r'],rightsStatus:'confirmed',rightsEvidence:'자체 촬영',authenticityConfirmed:true,partnerRole:'',partnerTerms:'',plannedCost:0,performanceStatus:'not_measured',performanceEvidence:'',performanceNote:''};
const creator={...step,id:'s2',placement:'creator',partnerRole:'리뷰',partnerTerms:'고정비'};
const seq={id:'seq',brandId:'b',campaignId:'c',campaignVersion:1,version:1,input:{title:'점심 수요',offerId:'offer',offerVersion:2,missionId:'m',missionVersion:3,objective:'첫 구매',steps:[step,creator]},requestDigest:'x',createdAt:at,updatedAt:at,updatedBy:owner};
const link={id:'i',version:2,campaignId:'c',brandId:'b',intentId:'i',publicationId:'p',status:'published',snapshotDigest:'d'.repeat(64)};
const intent={id:'i',campaignId:'c',brandId:'b',storeId:'store',input:{missionId:'m',missionVersion:3},snapshot:{mission:{channel:'organic',offerId:'offer',offerVersion:2}}};
await put('campaign','c',c);await put('store','store',{id:'store',brandId:'b',name:'합성 매장'},'b');await put('growth_demand','seq',seq,'c');await put('growth_publication_link','i',link,'c');await put('growth_action_intent','i',intent,'c');
await put('execution_publication','p',{id:'p',campaignId:'c',status:'accepted',scheduledAt:'2026-09-01T00:00:00Z'},'c');
const body=(patch={},input={})=>({campaignId:'c',campaignVersion:1,action:'link',expectedVersion:0,requestId:randomUUID(),input:{sequenceId:'seq',sequenceVersion:1,stepId:'s1',publicationLinkId:'i',publicationLinkVersion:2,evidenceRef:'check-001',...input},...patch});
const post=async(b,h=headers)=>{const r=await route.POST(new Request('https://agency.test/api/growth/demand-evidence',{method:'POST',headers:h,body:JSON.stringify(b)}));return {status:r.status,body:await r.json()}};
const get=async(h=headers)=>{const r=await route.GET(new Request('https://agency.test/api/growth/demand-evidence?campaignId=c',{headers:h}));return {status:r.status,body:await r.json()}};
const count=kind=>sql.prepare('SELECT COUNT(*) n FROM records WHERE kind=?').get(kind).n;

check((await post(body(),{})).status===401,'auth required');check((await post(body(),{...headers,origin:'https://evil.test'})).status===403,'CSRF');
check((await post(body({campaignVersion:2}))).status===409,'campaign CAS');check((await post(body({},{sequenceVersion:2}))).status===409,'sequence CAS');check((await post(body({},{publicationLinkVersion:1}))).status===409,'publication link CAS');
let r=await post(body({},{stepId:'s2'}));check(r.status===409&&/크리에이터/.test(r.body.error),'creator step cannot borrow own-media receipt');
check((await post(body({},{stepId:'missing'}))).status===409,'unknown step');check((await post(body({},{evidenceRef:'a@b.com 010-1234-5678'}))).status===400,'private evidence rejected');
await put('growth_action_intent','i',{...intent,input:{...intent.input,missionId:'other'}},'c');check((await post(body())).status===409,'different mission rejected');
await put('growth_action_intent','i',{...intent,snapshot:{mission:{...intent.snapshot.mission,offerVersion:1}}},'c');check((await post(body())).status===409,'old offer version rejected');
await put('growth_action_intent','i',{...intent,storeId:'elsewhere'},'c');check((await post(body())).status===409,'foreign store intent rejected');await put('growth_action_intent','i',intent,'c');
const before=sql.prepare("SELECT * FROM records WHERE kind IN ('growth_demand','growth_publication_link','growth_action_intent','execution_publication') ORDER BY id").all();
failKind='growth_demand_evidence_history';check((await post(body())).status===500,'atomic failure');failKind='';check(count('growth_demand_evidence')===0,'atomic rollback');
const first=body();r=await post(first);check(r.status===200&&r.body.version===1&&r.body.mayExecute===false,'link saved');check((await post(first)).body.duplicate,'same UUID replay');
check((await post({...first,input:{...first.input,evidenceRef:'check-002'}})).status===409,'UUID reuse with different body');check((await post(body())).status===409,'current CAS');
r=await get();let row=r.body.records[0];check(r.status===200&&row.assessment.status==='current'&&row.assessment.performance==='not_published'&&row.assessment.evidence.deliveryState==='accepted','accepted is not published');
check(r.body.sequences[0].steps[0].evidence[0]==='i'&&r.body.sequences[0].steps[0].operatorNote.source==='operator_note','step lists server evidence separately from operator note');
check(r.body.sequences[0].steps[1].eligibility.length>0,'creator eligibility shown');check(r.body.publications[0].linkedTo.stepId==='s1','publication shows linked step');
await put('execution_publication','p',{id:'p',campaignId:'c',status:'published',scheduledAt:'2026-09-01T00:00:00Z'},'c');r=await get();row=r.body.records[0];check(row.assessment.evidence.deliveryState==='published'&&row.assessment.performance==='collecting','published without measurement is collecting');check(row.assessment.causalStatus==='not_measured','no causal claim');
await put('growth_demand','seq',{...seq,version:2,input:{...seq.input,steps:[{...step,performanceStatus:'observed',performanceEvidence:'메모',performanceNote:'좋음'},creator]}},'c');check((await get()).body.records[0].assessment.status==='current','operator note change keeps link');
await put('growth_demand','seq',{...seq,version:3,input:{...seq.input,steps:[{...step,message:'바뀐 메시지'},creator]}},'c');row=(await get()).body.records[0];check(row.assessment.status==='held'&&row.assessment.evidence.measurement===null&&row.assessment.performance==='held','changed step holds evidence');
await put('growth_demand','seq',seq,'c');await put('growth_publication_link','i',{...link,snapshotDigest:'e'.repeat(64)},'c');check((await get()).body.records[0].assessment.status==='held','changed approved publication holds');await put('growth_publication_link','i',link,'c');
await put('growth_demand','seq',{...seq,input:{...seq.input,offerVersion:3}},'c');check((await get()).body.records[0].assessment.status==='held','changed offer holds');await put('growth_demand','seq',seq,'c');
check((await get()).body.records[0].assessment.status==='current','restored exact sources current again');
const zero={foodCost:0,packagingCost:0,fees:0,deliveryCost:0,benefitCost:0},today=new Date().toISOString().slice(0,10);await put('tracking_code','code',{id:'code',code:'SAMPLE',type:'coupon',storeId:'store',campaignId:'c',publicationId:'p'},'store');
await put('store_order','o1',{id:'o1',storeId:'store',campaignId:'c',orderDate:today,status:'paid',paidAmount:1000,refundAmount:0,costs:zero,channel:'social',attributionEvidence:'합성 근거',codeAttribution:{codeId:'code',code:'SAMPLE',publicationId:'p',conflictCodeIds:[]}},'store');
row=(await get()).body.records[0];check(row.assessment.performance==='observed'&&row.assessment.evidence.attribution.value.netRevenue===1000&&row.assessment.causalStatus==='not_measured','attributed order is observed evidence, not causal');
await put('growth_demand','seq',{...seq,version:4,input:{...seq.input,steps:[{...step,audience:'대학생'},creator]}},'c');row=(await get()).body.records[0];check(row.assessment.evidence.attribution===null,'held step never shows attributed revenue');await put('growth_demand','seq',seq,'c');
r=await post(body({action:'retire',expectedVersion:1},{stepId:'s2'}));check(r.status===409,'retire needs exact step');
r=await post(body({action:'retire',expectedVersion:1}));check(r.status===200&&r.body.version===2,'retire recorded');r=await get();check(r.body.records[0].status==='retired'&&r.body.records[0].assessment===null&&r.body.history.length===2,'retired kept in history');
await put('campaign','c',{...c,status:'archived'});check((await post(body({expectedVersion:2}))).status===409,'archived blocks new link');await put('campaign','c',c);
assert.deepEqual(sql.prepare("SELECT * FROM records WHERE kind IN ('growth_demand','growth_publication_link','growth_action_intent','execution_publication') ORDER BY id").all().map(x=>x.id),before.map(x=>x.id));passed++;
check((await get({'oai-authenticated-user-id':'other'})).status===404,'owner isolation');
await put('growth_stop','global',{status:'stopped'});check((await post(body({expectedVersion:2}))).status===200,'evidence link is not execution; allowed while stopped');
check(pure.stepEligibility(undefined).length===1&&pure.deliveryState('cancelled')==='failed'&&pure.deliveryState('submitting')==='unknown','pure helpers');
console.log(JSON.stringify({passed}));
