import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
const {load}=testRuntime(async()=>{throw Error('No external calls')});
const {emptyDecisionInput,emptyLessonInput,parseDecisionInput,parseLessonInput,decisionAssessment,lessonAssessment}=await load('lib/growth-decisions.ts');
let passed=0;
const check=(value,label)=>{assert.ok(value,label);passed++};
const rejects=(parser,value)=>{assert.throws(()=>parser(value));passed++};
const now=Date.parse('2026-09-30T12:00:00+09:00');
const decision={...emptyDecisionInput(),title:'배송 안내 수정',decision:'modify',reason:'이탈 관측',observation:'상담 문의 집계',alternativeExplanation:'고객군 변화',missionId:'mission-a',missionVersion:1,nextAction:'안내 문구 검토',assignee:'운영 담당',dueAt:'2026-09-30'};
const lesson={...emptyLessonInput(),title:'배송 안내 교훈',method:'배송 안내 검토',hypothesis:'안내가 문의를 줄임',scope:'국내 신규 주문',falsificationRule:'문의 증가 시 폐기',lossLimit:0,sourceType:'execution',evidenceLevel:'operational_observation',missionId:'mission-a',missionVersion:1,sourceEvidence:'주문별 집계 문서',counterEvidence:'유입 고객군 변화 가능',expiresAt:'2026-10-31',state:'reusable',outcome:'success',testPlan:'동일 창 문의 건수 비교',testResult:'관측 문의 감소',nextAction:'다음 캠페인에서 재시험',assignee:'운영 담당',dueAt:'2026-09-30'};
const da=patch=>decisionAssessment({...decision,...patch},[],now);
const la=patch=>lessonAssessment({...lesson,...patch},[],now);
check(parseDecisionInput({}).decision==='maintain','decision draft default');
check(parseLessonInput({}).state==='candidate','lesson draft default');
check(da({}).missing.length===0,'complete decision');
check(la({}).canReuse,'complete operational lesson reusable');
check(!da({}).mayExecute,'decision never executes');
check(!da({}).mayScale,'decision never scales');
check(da({}).causalStatus==='not_measured','decision not causal');
check(!la({}).mayPromote,'lesson never promotes rules');
check(la({}).causalStatus==='not_measured','lesson not causal');
for(const field of ['title','reason','observation','alternativeExplanation','nextAction','assignee','dueAt'])check(da({[field]:''}).missing.length>0,`decision missing ${field}`);
check(da({missionId:'',missionVersion:0}).missing.length>0,'decision needs source');
check(da({missionId:'',missionVersion:0,journeyId:'journey-a',journeyVersion:1}).missing.length===0,'journey is decision source');
check(da({missionVersion:0}).missing.length>0,'mission source needs version');
check(da({journeyId:'journey-a',journeyVersion:0}).missing.length>0,'partial secondary source held');
check(da({decision:'scale'}).missing.length>0,'scale requires separate verified enlargement');
for(const choice of ['maintain','modify','stop','explore','scale'])check(parseDecisionInput({...decision,decision:choice}).decision===choice,'all choices allowed as draft');
for(const field of ['title','method','hypothesis','scope','sourceEvidence','counterEvidence','falsificationRule','expiresAt','testPlan','testResult','nextAction','assignee','dueAt'])check(!la({[field]:''}).canReuse,`reuse requires ${field}`);
for(const state of ['candidate','testing','retired'])check(!la({state}).canReuse,`state ${state} not reusable`);
for(const outcome of ['invalid','not_tested'])check(!la({outcome}).canReuse,`outcome ${outcome} not reusable`);
check(la({outcome:'failure'}).canReuse,'failure prevention lesson reusable');
check(!la({lossLimit:null}).canReuse,'unknown loss limit held');
for(const lossLimit of [-1,1.5,1_000_000_000_001,'0',NaN])rejects(parseLessonInput,{lossLimit});
check(!la({evidenceLevel:'provisional'}).canReuse,'provisional evidence not reusable');
check(!la({missionId:'',missionVersion:0}).canReuse,'execution needs mission');
check(la({sourceType:'journey',journeyId:'journey-a',journeyVersion:1}).canReuse,'journey evidence');
check(!la({sourceType:'journey'}).canReuse,'journey source required');
check(la({sourceType:'decision',decisionId:'decision-a',decisionVersion:1}).canReuse,'decision evidence');
check(!la({sourceType:'decision'}).canReuse,'decision source required');
for(const sourceType of ['manual','market'])check(la({sourceType,missionId:'',missionVersion:0}).canReuse,'documented source allowed');
check(!lessonAssessment(lesson,['참조 변경'],now).canReuse,'stale upstream held');
check(decisionAssessment(decision,['참조 변경'],now).missing.includes('참조 변경'),'decision retains upstream');
check(la({dueAt:'2026-09-29'}).canReuse===false,'overdue held');
check(la({expiresAt:'2026-09-29'}).canReuse===false,'expired held');
check(lessonAssessment({...lesson,expiresAt:'2026-09-30'},[],Date.parse('2026-09-30T23:59:59.999+09:00')).canReuse,'KST expiration includes end day');
check(!lessonAssessment({...lesson,expiresAt:'2026-09-30',dueAt:'2026-10-01'},[],Date.parse('2026-10-01T00:00:00+09:00')).canReuse,'KST expiration next midnight held');
check(!lessonAssessment(lesson,[],NaN).canReuse,'invalid clock held');
check(decisionAssessment(decision,[],Infinity).missing.length>0,'invalid decision clock held');
check(da({dueAt:'2026-09-29'}).missing.length>0,'overdue decision held');
check(parseLessonInput({state:'testing'}).state==='testing','incomplete testing draft saved');
check(parseLessonInput({state:'retired'}).state==='retired','incomplete retired draft saved');
check(la({state:'retired',retirementReason:''}).missing.length>0,'retirement reason required by assessment');
check(la({state:'candidate',outcome:'failure'}).canReuse===false,'failure learned without execution approval');
for(const parser of [parseDecisionInput,parseLessonInput]){
 for(const value of [null,[],true,'x',{title:null},{title:'x'.repeat(201)},{title:'bad\u0000value'},{title:'person@example.com'},{title:'Bearer sensitive-value'},{title:'api_key=secret-value'},{assignee:'010-1234-5678'},{missionVersion:-1},{missionVersion:1.5},{missionVersion:NaN},{missionVersion:Infinity},{missionVersion:null},{missionVersion:'1'},{missionVersion:Number.MAX_SAFE_INTEGER+1},{missionId:'bad id'},{dueAt:'2026-02-30'},{dueAt:'2025-02-29'},{dueAt:'2026-9-1'},{dueAt:123},{dueAt:'2026-09-30T00:00:00Z'}])rejects(parser,value);
 check(parser({dueAt:'2024-02-29'}).dueAt==='2024-02-29','leap day valid');
 check(parser({title:'  한글 🎯  '}).title==='한글 🎯','Unicode trimmed');
 check(parser({mayExecute:true}).mayExecute===undefined,'unknown authority fields discarded');
}
for(const patch of [{decision:'publish'},{decision:null},{journeyVersion:-1}])rejects(parseDecisionInput,patch);
for(const patch of [{state:'promoted'},{outcome:'causal'},{sourceType:'model'},{evidenceLevel:'proven'},{decisionVersion:-1},{expiresAt:'2026-13-01'}])rejects(parseLessonInput,patch);
for(const prefix of ['mission','journey','decision']){
 check(!la({[`${prefix}Id`]:`${prefix}-b`,[`${prefix}Version`]:0}).canReuse,'all present refs require version');
 check(!la({[`${prefix}Id`]:'',[`${prefix}Version`]:1}).canReuse,'orphan versions held');
}
check(da({missionId:'',missionVersion:1,journeyId:'journey-a',journeyVersion:1}).missing.length>0,'orphan decision ref held');
const frozen=Object.freeze({...lesson});
check(parseLessonInput(frozen)!==frozen,'parse creates new lesson');
check(emptyLessonInput()!==emptyLessonInput(),'empty lesson independent');
check(emptyDecisionInput()!==emptyDecisionInput(),'empty decision independent');
console.log(JSON.stringify({passed}));
