import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
const {load}=testRuntime(async()=>{throw Error('no external calls');});
const {parseExecutionInput,parseExecutionReceipt,canRecordExecution,executionId}=await load('lib/growth-execution.ts');
let passed=0;const check=(value,label)=>{assert.ok(value,label);passed++;},throws=(fn,label)=>{assert.throws(fn,label);passed++;};
const input={missionId:'mission',missionVersion:2,authorityId:'authority',authorityVersion:1,inventoryId:'inventory',inventoryVersion:0,quantity:1,recoveryOwner:'운영 담당',recoveryDueAt:'2099-01-01T10:00:00+09:00',evidenceRef:'evidence-one'};
check(JSON.stringify(parseExecutionInput(input))===JSON.stringify(input),'input roundtrip');
for(const value of [null,undefined,[],1,'input'])throws(()=>parseExecutionInput(value),'invalid object');
for(const key of ['missionId','authorityId','inventoryId','evidenceRef'])for(const value of ['',null,'not allowed','../escape','a'.repeat(101),'user@example.com'])throws(()=>parseExecutionInput({...input,[key]:value}),key+' invalid id');
for(const key of ['missionVersion','authorityVersion','quantity'])for(const value of [0,-1,null,'1',1.2,Number.MAX_SAFE_INTEGER+1])throws(()=>parseExecutionInput({...input,[key]:value}),key+' invalid integer');
for(const value of [-1,null,'0',1.2,Number.MAX_SAFE_INTEGER+1])throws(()=>parseExecutionInput({...input,inventoryVersion:value}),'invalid inventory version');
for(const due of ['2099-01-01','2099-02-29T10:00:00Z','2099-01-01T24:00:00Z','2099-01-01T10:60:00Z','2099-01-01T10:00:60Z','2099-01-01T10:00:00+15:00','2099-01-01T10:00:00+14:01','2099-01-01T10:00:00+09:60','bad'])throws(()=>parseExecutionInput({...input,recoveryDueAt:due}),'invalid timestamp');
for(const due of ['2099-01-01T10:00:00Z','2099-01-01T10:00:00-14:00','2099-01-01T10:00:00.001+14:00'])check(parseExecutionInput({...input,recoveryDueAt:due}).recoveryDueAt===due,'valid zone');
for(const state of ['prepared','unknown'])check(canRecordExecution(state),'recoverable state');
for(const state of ['failed','observed'])check(!canRecordExecution(state),'terminal state');
for(const status of ['unknown','failed','observed'])check(parseExecutionReceipt({status,reference:'receipt',note:'운영자 확인'}).status===status,'receipt state');
for(const status of ['prepared','success','',null])throws(()=>parseExecutionReceipt({status,reference:'receipt',note:'운영자 확인'}),'invalid receipt state');
for(const value of ['',null,'a'.repeat(1001),'user@example.com','Bearer abcd','api_key=example','sk-proj-example1234','ｕｓｅｒ＠ｅｘａｍｐｌｅ．ｃｏｍ'])throws(()=>parseExecutionReceipt({status:'unknown',reference:'receipt',note:value}),'unsafe note');
throws(()=>executionId('bad value'),'invalid direct id');
console.log(JSON.stringify({passed,externalCalls:0}));
