import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
const {load,sql}=testRuntime(async()=>{throw Error('Operations may not send external requests')});
const route=await load('app/api/growth/operations/route.ts');
const server=await load('lib/server.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='ops-owner',h={'oai-authenticated-user-id':owner,origin:'https://agency.test'};
const c={id:'c',brandId:'b',storeId:'s',version:1,status:'active'};
await server.recordStatement(owner,'campaign','c',c).run();
await server.recordStatement(owner,'campaign','other',{...c,id:'other'}).run();
await server.recordStatement(owner,'store','s',{id:'s',brandId:'b',version:1,status:'active'}).run();
const get=(headers=h)=>route.GET(new Request('https://agency.test/api/growth/operations?campaignId=c',{headers}));
const post=async(data,headers=h)=>{const response=await route.POST(new Request('https://agency.test/api/growth/operations',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,...data})}));return {status:response.status,body:await response.json()}};
check((await get({})).status===401,'anonymous refused');
check((await post({action:'create_inventory'},{...h,origin:'https://evil.test'})).status===403,'CSRF refused');
const created=await post({action:'create_inventory',input:{sku:'SYNTHETIC',locationId:'s',unit:'piece',onHand:5},evidenceRef:'count-sheet-1',observedAt:new Date(Date.now()-1000).toISOString()});
check(created.status===200,'inventory created '+JSON.stringify(created));
const inventoryId=created.body.inventory[0].id;
check(created.body.inventory[0].projection.available===5,'opening stock five');
check((await post({action:'create_inventory',input:{sku:'SYNTHETIC',locationId:'s',unit:'piece',onHand:10},evidenceRef:'count-sheet-2',observedAt:new Date().toISOString(),campaignId:'other'})).status===409,'same brand location SKU shared not cloned per campaign');
const order={id:'a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1',storeId:'s',version:1,orderDate:'2026-09-30',paidAmount:10000,refundAmount:0,status:'paid',costs:{foodCost:null,packagingCost:null,fees:null,deliveryCost:null,benefitCost:null}};
await server.recordStatement(owner,'store_order',order.id,order,'s').run();
await server.recordStatement(owner,'growth_mission','m',{id:'m',campaignId:'c',brandId:'b',campaignVersion:1,version:1,status:'staged',input:{offerId:'offer',offerVersion:1}},'c').run();
await server.recordStatement(owner,'growth_offer','offer',{id:'offer',campaignId:'c',brandId:'b',campaignVersion:1,version:1,input:{catalogId:'catalog',catalogVersion:1}},'c').run();
await server.recordStatement(owner,'growth_catalog','catalog',{id:'catalog',campaignId:'c',brandId:'b',campaignVersion:1,version:1,input:{sku:'SYNTHETIC'}},'c').run();
const link={orderId:order.id,orderVersion:1,sourceKey:'shop',accountId:'seller',externalLineId:'line',inventoryId,units:3,missionId:'m',missionVersion:1,offerId:'offer',offerVersion:1,paidAllocation:10000,refundAllocation:0,currency:'KRW',taxBasis:'included',evidenceRef:'seller-line',source:'operator_attested'};
let r=await post({action:'link_order',input:link,expectedVersion:0});check(r.status===200,'real ledger order linked '+JSON.stringify(r));
const lineId=r.body.orderLines[0].id;
check(r.body.inventory[0].projection.reserved===3&&r.body.inventory[0].projection.available===2,'order allocates stock once');
r=await post({action:'link_order',input:link,expectedVersion:0});check(r.status===200&&r.body.duplicate,'duplicate line receipt idempotent');
check(r.body.inventory[0].projection.reserved===3,'retry does not double reserve');
const event={action:'record_operation',id:'ship-1',inventoryVersion:2,lineId,kind:'ship',quantity:2,evidenceRef:'warehouse-note-1',observedAt:new Date().toISOString()};
r=await post(event);check(r.status===200&&r.body.inventory[0].projection.onHand===3,'shipment removes physical stock');
check((await post(event)).body.duplicate,'shipment retry no double subtract');
await server.recordStatement(owner,'store_order',order.id,{...order,version:2,refundAmount:5000},'s').run();
r={body:await (await get()).json()};check(r.body.orderLines[0].allocation.status==='reconciliation_required','refund marks old money allocation stale');
check(r.body.inventory[0].projection.onHand===3,'refund never restocks');
r=await post({action:'link_order',input:{...link,orderVersion:2,refundAllocation:5000},expectedVersion:1});check(r.status===200&&r.body.orderLines[0].version===2,'reconcile allocation without new reservation');
check(r.body.inventory[0].projection.reserved===1,'reconcile does not reallocate stock');
check((await post({...event,id:'ship-too-many',inventoryVersion:3,quantity:2,observedAt:new Date().toISOString()})).status===409,'cannot ship beyond remaining allocation');
check((await server.campaignDeletionPreview(owner,'c')).deletable===false,'operational history protects campaign');
check(sql.prepare("SELECT count(*) n FROM records WHERE kind='store_order'").get().n===1,'link does not duplicate sales ledger');
await server.recordStatement(owner,'store_order',order.id,{...order,version:3,status:'cancelled',refundAmount:10000},'s').run();
check((await post({...event,id:'ship-cancelled',quantity:1,inventoryVersion:3,observedAt:new Date().toISOString()})).status===409,'cancelled/stale order cannot ship');
await server.recordStatement(owner,'store_order',order.id,{...order,version:3,storeId:'elsewhere'},'elsewhere').run();
check((await post({...event,id:'ship-moved',quantity:1,inventoryVersion:3,observedAt:new Date().toISOString()})).status===404,'moved order cannot ship');
await server.recordStatement(owner,'store_order',order.id,{...order,version:2,refundAmount:5000},'s').run();
const adjust={action:'stock_adjust',id:'count-2',inventoryId,inventoryVersion:3,kind:'stocktake',quantity:8,evidenceRef:'count-sheet-2',observedAt:new Date().toISOString()};
r=await post(adjust);check(r.status===200&&r.body.inventory[0].projection.onHand===8,'stocktake replaces physical count');
check((await post(adjust)).body.duplicate,'stocktake retry is idempotent');
check((await post({...adjust,id:'stale-count'})).status===409,'stale count rejected');
check((await post({...adjust,id:'string-count',inventoryVersion:4,quantity:'9'})).status===400,'quantity coercion prohibited');
check((await post({...adjust,id:'old-observation',inventoryVersion:4,observedAt:'2020-01-01T00:00:00Z'})).status===409,'historical stocktake cannot overwrite newer movements');
const reserve={action:'reserve_stock',id:'reservation-1',inventoryId,inventoryVersion:4,missionId:'m',missionVersion:1,quantity:2,evidenceRef:'allocation-plan',observedAt:new Date().toISOString()};
r=await post(reserve);check(r.status===200&&r.body.inventory[0].projection.reserved===3,'mission hold shares actual order pool');
check((await post(reserve)).body.duplicate,'mission reservation retry idempotent');
check((await post({...reserve,id:'reservation-2',inventoryVersion:5,quantity:20})).status===409,'overselling reservation denied');
check((await post({...reserve,id:'other-campaign-hold',inventoryVersion:5,campaignId:'other'})).status===404,'mission cannot be reserved from another campaign');
const release={action:'release_stock',id:'release-1',inventoryId,inventoryVersion:5,reservationId:'reservation-1',missionId:'m',missionVersion:1,quantity:2,safeRelease:true,evidenceRef:'cancel-confirmation',observedAt:new Date().toISOString()};
await server.recordStatement(owner,'growth_mission','m',{id:'m',campaignId:'c',brandId:'b',version:1,status:'unknown',input:{offerId:'offer',offerVersion:1}},'c').run();
check((await post(release)).status===409,'unknown external outcome keeps inventory held');
await server.recordStatement(owner,'growth_mission','m',{id:'m',campaignId:'c',brandId:'b',version:1,status:'cancelled',input:{offerId:'offer',offerVersion:1}},'c').run();
r=await post(release);check(r.status===200&&r.body.inventory[0].projection.reserved===1,'cancelled mission explicit release clears unallocated hold');
const settlement={eventId:'cash-a',revision:1,kind:'received',orderId:order.id,orderVersion:2,accountRef:'seller',settlementRef:'batch',receiptRef:'payment-a',currency:'KRW',amount:4500,feeAmount:500,taxBasis:'unknown',occurredAt:new Date().toISOString(),evidenceRef:'statement-a',origin:'bank_verified'};
r=await post({action:'save_settlement',input:settlement});check(r.status===200&&r.body.settlement.receivedCash.total===4500,'actual cash attestation independent from paid ledger');
check(r.body.settlement.ledgerNetRevenue===5000&&r.body.settlement.profit===null&&r.body.settlement.netCashFlow===null,'cash not revenue profit or net cash flow');
check(r.body.settlement.events[0].origin==='operator_attested','client cannot claim bank verification');
check((await post({action:'save_settlement',input:settlement})).body.duplicate,'cash receipt retry idempotent');
check((await post({action:'save_settlement',input:{...settlement,eventId:'cash-duplicate'}})).status===400,'new ID cannot double count same bank reference');
check((await post({action:'save_settlement',input:{...settlement,amount:4600}})).status===409,'same revision changed cash denied');
r=await post({action:'save_settlement',input:{...settlement,revision:2,amount:4600}});check(r.status===200&&r.body.settlement.receivedCash.total===4600,'cash revision corrects latest amount');
check((await post({action:'save_settlement',campaignId:'other',input:{...settlement,revision:3}})).status===409,'other campaign cannot edit cash evidence');
check((await post({action:'save_settlement',input:{...settlement,eventId:'foreign-order',orderId:'missing',receiptRef:'foreign'}})).status===404,'missing order cash refused');
check((await get({...h,'oai-authenticated-user-id':'other-owner'})).status===404,'owner cannot read another workspace');
check(sql.prepare("SELECT count(*) n FROM records WHERE kind='growth_settlement_history'").get().n===2,'cash revisions append history');
await server.recordStatement(owner,'store_order',order.id,{...order,version:3,paidAmount:0,refundAmount:0,status:'paid'},'s').run();
await server.recordStatement(owner,'growth_mission','m',{id:'m',campaignId:'c',brandId:'b',version:2,status:'draft',input:{offerId:'new-offer',offerVersion:1}},'c').run();
r=await post({action:'link_order',input:{...link,orderVersion:3,paidAllocation:0,refundAllocation:0},expectedVersion:2});check(r.status===200,'zero priced paid order reconciles');
r=await post({...event,id:'free-order-ship',inventoryVersion:6,quantity:1,observedAt:new Date().toISOString()});check(r.status===200,'zero priced paid order can fulfill');
check(r.body.settlement.reconciliation==='stale','order revision keeps old cash but marks stale');
console.log(JSON.stringify({passed}));
