import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
const {load}=testRuntime(async()=>{throw Error('external forbidden')});
const {assessPublicationMeasurement}=await load('lib/growth-publication-observation.ts');
let passed=0;const check=(v,label)=>{assert.ok(v,label);passed++};
const at='2026-09-20T03:00:00.000Z',base={campaign:{id:'c',brandId:'b',storeId:'s'},publication:{id:'p',campaignId:'c',status:'published',experimentId:'e',arm:'control',media:{mediaId:'123'}},experiment:{id:'e',brandId:'b',campaignId:'c',channel:'Instagram',metric:'share_rate',status:'running'},source:{id:'e:control',experimentId:'e',channel:'instagram',arm:'control',target:'123',publicationId:'p',window:{from:'2026-09-01',to:'2026-09-19'},lastFetchedAt:at,lastError:null},draft:{id:'e',experimentId:'e',channel:'instagram',arms:{control:{value:{denominator:0,numerator:0,source:'private'},window:{from:'2026-09-01',to:'2026-09-19'},fetchedAt:at,target:'123',credential:{level:'store',brandId:'b',storeId:'s'},definition:'private',limitations:['private']}}}};
const run=patch=>assessPublicationMeasurement({...base,...patch});
check(run().status==='observed'&&run().value.denominator===0,'zero preserved');
check(run({draft:{...base.draft,arms:{control:{...base.draft.arms.control,value:{denominator:null,numerator:0}}}}}).value.denominator===null,'null preserved');
for(const patch of [{pending:true},{lastError:'secret'}, {errorCode:'reauth_required'},{publicationId:'other'},{target:'other'},{arm:'treatment'},{channel:'naver_ads'},{failures:1}])check(run({source:{...base.source,...patch}}).value===null,'held source '+JSON.stringify(patch));
for(const credential of [undefined,{level:'workspace'},{level:'store',brandId:'b',storeId:'other'},{level:'brand',brandId:'other'}])check(run({draft:{...base.draft,arms:{control:{...base.draft.arms.control,credential}}}}).status==='held','scope held');
for(const n of [-1,1.5,Infinity,Number.MAX_SAFE_INTEGER+1,undefined])check(run({draft:{...base.draft,arms:{control:{...base.draft.arms.control,value:{denominator:n,numerator:0}}}}}).value===null,'malformed held');
check(run({draft:{...base.draft,arms:{control:{...base.draft.arms.control,value:{denominator:1,numerator:3}}}}}).status==='observed','shares may exceed reach');
check(run({source:{...base.source,stopped:true,stoppedReason:'실험이 종료되어 수집을 멈췄습니다.',lastFetchedAt:'2026-09-21T00:00:00Z'}}).status==='historical','normal ended retained');
check(run({publication:{...base.publication,status:'accepted'}}).value===null,'unpublished held');
check(run({draft:{...base.draft,arms:undefined,control:{denominator:1,numerator:1}}}).value===null,'legacy arm held');
check(!JSON.stringify(run()).includes('private'),'no raw free text or credential');
check(run({draft:{...base.draft,arms:{control:{...base.draft.arms.control,credential:{level:'invalid',brandId:'b'}}}}}).value===null,'invalid credential scope held');
check(!JSON.stringify(run({source:{...base.source,id:'raw-secret',lastFetchedAt:'raw-secret'}})).includes('raw-secret'),'malformed source identifier and timestamp not exposed');
check(run({experiment:{...base.experiment,status:'evaluated'}}).status==='historical','completed experiment measurement historical');
check(run({experiment:{...base.experiment,status:'draft'}}).value===null,'draft experiment held');
check(run({source:{...base.source,lastFetchedAt:'2099-01-01T00:00:00Z'},draft:{...base.draft,arms:{control:{...base.draft.arms.control,fetchedAt:'2099-01-01T00:00:00Z'}}}}).value===null,'future success held');
console.log(JSON.stringify({passed,external:0}));
