import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
const {load}=testRuntime(async()=>{throw Error('No external calls')});
const {emptyJourneyInput,emptyJourneyObservation,parseJourneyInput,journeyAssessment}=await load('lib/growth-journey.ts');
let passed=0;
const check=(value,label)=>{assert.ok(value,label);passed++};
const rejects=value=>{assert.throws(()=>parseJourneyInput(value));passed++};
const now=Date.parse('2026-09-30T12:00:00+09:00');
const before={...emptyJourneyObservation(),windowStart:'2026-09-01',windowEnd:'2026-09-03',observedAt:'2026-09-06',delayHours:24,tracking:'reliable',sourceUrls:['https://reports.example.com/before'],evidence:'관측 집계 문서',denominator:100,conversions:10,paidOrders:20,refundedOrders:2,contributionProfit:-100};
const after={...before,windowStart:'2026-09-10',windowEnd:'2026-09-12',observedAt:'2026-09-15',denominator:200,conversions:40,paidOrders:50,refundedOrders:10,contributionProfit:0};
const input={...emptyJourneyInput(),title:'상품 설명 이탈',hypothesis:'배송 안내 부족',alternativeExplanation:'유입 고객군 변화',offerId:'offer-a',offerVersion:1,missionId:'mission-a',missionVersion:1,segment:'신규 방문',denominatorDefinition:'중복 제거 방문자',before,after,action:'배송 안내 보강',assignee:'운영 담당',dueAt:'2026-09-20',appliedAt:'2026-09-08',factEvidence:'문의 집계 문서'};
const assess=patch=>journeyAssessment({...input,...patch},[],now);
check(parseJourneyInput({}).before.denominator===null,'draft permits unknown numbers');
check(journeyAssessment(emptyJourneyInput(),[],now).comparison.status==='not_measured','empty comparison unmeasured');
check(journeyAssessment(emptyJourneyInput(),[],now).missing.length>0,'empty draft readiness incomplete');
const result=assess({});
check(result.comparison.status==='observed','mature comparable observations');
check(result.comparison.conversionDeltaPp===10,'conversion percentage points');
check(result.comparison.refundDeltaPp===10,'refund independent paid orders denominator');
check(result.comparison.profitDelta===100,'negative and zero profit preserved');
check(result.mayExecute===false&&result.causalStatus==='not_measured','never execution or causal conclusion');
check(result.missing.length===0,'complete proposal');
check(journeyAssessment(input,['상위 근거 만료'],now).comparison.status==='held','upstream holds comparison');
for(const field of ['title','hypothesis','alternativeExplanation','action','assignee','dueAt','offerId','missionId','segment','denominatorDefinition'])check(assess({[field]:''}).missing.length>0,`required ${field}`);
check(assess({factEvidence:'',handoffReason:'상담 확인 대기'}).missing.length>0,'handoff does not replace facts');
check(parseJourneyInput({...input,factEvidence:'',handoffReason:'상담 확인 대기'}).handoffReason==='상담 확인 대기','handoff retained');
for(const patch of [{tracking:'unknown'},{tracking:'broken'},{delayHours:null},{windowEnd:'2026-09-11'},{windowStart:'2026-09-02',windowEnd:'2026-09-04'},{observedAt:'2026-10-01'},{observedAt:'2026-09-12'},{sourceUrls:[]},{evidence:''}])check(assess({after:{...after,...patch}}).comparison.status==='held','untrustworthy comparison held');
check(assess({appliedAt:''}).comparison.status==='held','missing applied date held');
check(assess({appliedAt:before.windowEnd}).comparison.status==='held','application must follow before');
check(assess({appliedAt:'2026-09-11'}).comparison.status==='held','application cannot follow after start');
check(assess({after:{...after,denominator:null}}).comparison.conversionDeltaPp===null,'missing denominator cannot produce zero');
check(assess({after:{...after,denominator:0,conversions:0}}).comparison.conversionDeltaPp===null,'zero denominator has no conversion rate');
check(assess({after:{...after,refundedOrders:null}}).comparison.refundDeltaPp===null,'missing refunds not zero');
check(assess({after:{...after,paidOrders:0,refundedOrders:0}}).comparison.refundDeltaPp===null,'zero paid count has no refund rate');
check(assess({after:{...after,contributionProfit:null}}).comparison.profitDelta===null,'unknown profit not zero');
check(assess({after:{...after,denominator:null,conversions:null,paidOrders:null,refundedOrders:null,contributionProfit:null}}).comparison.status==='not_measured','no comparable metrics unmeasured');
for(const value of [null,[],true,'x',{title:null},{stage:'purchase'},{channel:'email'},{device:'tablet'},{denominatorUnit:'click'},{offerVersion:-1},{missionVersion:1.5},{offerId:'bad id'},{dueAt:'2026-02-30'},{dueAt:'2026-9-1'},{appliedAt:'2026-01-01T00:00:00Z'},{title:'a'.repeat(201)},{action:'person@example.com'},{assignee:'010-1234-5678'},{hypothesis:'api_key=secret-value'},{title:'bad\u0001value'},{before:[]},{before:null}])rejects(value);
for(const patch of [{denominator:-1},{conversions:1.2},{denominator:Infinity},{denominator:'100'},{denominator:1_000_000_000_001},{contributionProfit:-1_000_000_000_001},{delayHours:-1},{tracking:'ok'},{windowStart:'2026-09-04'},{conversions:101},{refundedOrders:21},{sourceUrls:'https://example.com'},{sourceUrls:['']},{sourceUrls:Array(21).fill('https://example.com')}])rejects({...input,before:{...before,...patch}});
for(const url of ['http://example.com','https://localhost/a','https://127.0.0.1/a','https://[::1]/a','https://x.internal/a','https://example.com:444/a','https://user:pass@example.com','https://example.com?x=1','https://example.com#x','https://example.com/%70erson%40example.com','https://example.com/%2561pi_key%253Dsecret','https://example.com/%ZZ'])rejects({...input,before:{...before,sourceUrls:[url]}});
check(parseJourneyInput({...input,before:{...before,paidOrders:101}}).before.paidOrders===101,'paid orders independent of conversions');
check(parseJourneyInput({...input,before:{...before,contributionProfit:-1_000_000_000_000}}).before.contributionProfit<0,'bounded negative profit');
check(parseJourneyInput({...input,before:{...before,sourceUrls:['https://example.com','https://example.com']}}).before.sourceUrls.length===1,'deduplicate sources');
const frozen=Object.freeze({...input,before:Object.freeze({...before,sourceUrls:Object.freeze([...before.sourceUrls])})});
check(parseJourneyInput(frozen).before!==frozen.before,'immutable observation copies');
check(parseJourneyInput({...input,resolved:true}).resolved===undefined,'no resolution assertion accepted');
check(assess({after:{...after,tracking:'broken'}}).comparison.conversionDeltaPp===null,'held comparison suppresses deltas');
check(assess({after:{...after,observedAt:'2026-09-14'}}).comparison.status==='observed','exact KST maturity boundary included');
check(assess({after:{...after,observedAt:'2026-09-13'}}).comparison.status==='held','KST day before maturity held');
check(journeyAssessment(input,[],Date.parse('2026-09-13T23:59:59+09:00')).comparison.status==='held','current time must also be mature');
check(journeyAssessment(input,[],NaN).comparison.status==='held','invalid clock held');
check(assess({after:{...after,conversions:null}}).comparison.status==='observed','partial independent metric observation permitted');
check(assess({after:{...after,conversions:null}}).comparison.refundDeltaPp===10,'missing conversion does not erase refund metric');
check(assess({before:{...before,conversions:0},after:{...after,conversions:0}}).comparison.conversionDeltaPp===0,'observed zero delta is not unknown');
check(assess({after:{...after,delayHours:0,observedAt:'2026-09-13'}}).comparison.status==='observed','zero delay matures after inclusive end day');
check(assess({appliedAt:after.windowStart}).comparison.status==='observed','apply on after start accepted');
check(assess({after:{...after,windowStart:'2026-09-03',windowEnd:'2026-09-05'}}).comparison.status==='held','shared endpoint is overlapping inclusive window');
check(parseJourneyInput({...input,dueAt:'2024-02-29'}).dueAt==='2024-02-29','valid leap day accepted');
rejects({...input,dueAt:'2025-02-29'});
for(const field of ['before','after'])for(const metric of ['denominator','conversions','paidOrders','refundedOrders','contributionProfit'])check(parseJourneyInput({...input,[field]:{...input[field],[metric]:null}})[field][metric]===null,'unknown metrics preserved');
for(const patch of [{denominator:Number.MAX_SAFE_INTEGER+1},{contributionProfit:NaN},{delayHours:1.5},{delayHours:1_000_000_000_001},{evidence:'Bearer credential-value'},{evidence:'bad\u0000text'},{windowStart:123},{observedAt:null}])rejects({...input,before:{...before,...patch}});
for(const patch of [{offerVersion:null},{missionVersion:'1'},{before:false},{stage:null},{source:'ignored'}]){
 if (patch.source)check(parseJourneyInput({...input,...patch}).source===undefined,'unknown fields discarded');
 else rejects({...input,...patch});
}
check(parseJourneyInput({...input,before:{...before,sourceUrls:['https://example.com/%EC%8B%9D%EC%82%AC']}}).before.sourceUrls.length===1,'safe Unicode URL preserved');
rejects({...input,before:{...before,sourceUrls:['https://example.com/path\\other']}});
rejects({...input,before:{...before,sourceUrls:['https://example.com/%2525252561']}});
console.log(JSON.stringify({passed}));
