import assert from 'node:assert/strict';
import {randomUUID,createHmac} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
const secret='synthetic-catalog-only-key-000000000000';let sellable=4,mode='valid',calls=0,duringPull=null;
const {load,sql}=testRuntime(async(url,o)=>{calls++;assert.equal(new URL(url).pathname,'/collective/v1/catalog/read');const b=JSON.parse(o.body),snapshot={tenantId:b.tenantId,storeId:b.storeId,productId:b.productId,state:mode==='deleted'?'deleted':'active',title:'상품',price:100,sellable:mode==='deleted'?null:sellable,unit:'piece',observedAt:new Date().toISOString()},snapshotJson=JSON.stringify(snapshot),signature=createHmac('sha256',secret).update(`${o.headers['x-collective-timestamp']}\n${o.headers['x-collective-nonce']}\n200\n/collective/v1/catalog/read\n${snapshotJson}`).digest('hex');if(duringPull)await duringPull();return Response.json({snapshot,snapshotJson,signature:mode==='bad-signature'?'0'.repeat(64):signature});});
const s=await load('lib/server.ts'),crypto=await load('lib/credential-crypto-server.ts'),api=await load('app/api/growth/provider-catalog/route.ts'),stock=await load('lib/growth-stock-readiness-server.ts');
const owner='o',c={id:'c',brandId:'b',storeId:'s',status:'active',version:1},headers={'oai-authenticated-user-id':owner,origin:'https://agency.test'},put=(kind,id,v,parent='c')=>s.recordStatement(owner,kind,id,v,parent).run();
await put('campaign','c',c);await put('store','s',{id:'s',brandId:'b'},'b');
const input={sku:'SKU',stockUnit:'piece',price:100};await put('growth_catalog','cat',{id:'cat',campaignId:'c',brandId:'b',campaignVersion:1,version:1,input});
await put('growth_inventory_item','inv',{id:'inv',brandId:'b',storeId:'s',version:1,input:{sku:'SKU',locationId:'s',unit:'piece',onHand:10}},'s');
const at=new Date().toISOString(),event={id:'reserve',digest:'a'.repeat(64),version:1,kind:'reserve',quantity:3,reservationId:'res',missionId:'m',orderId:'',observedAt:at,recordedAt:at,evidenceRef:'fixture',safeRelease:false,returnAccepted:false,disposition:'unknown',restock:false,inventoryId:'inv',brandId:'b',storeId:'s'};await put('growth_stock_event','reserve',event,'inv');
await put('channel_credential','growth_landing_provider:s',{id:'growth_landing_provider:s',channel:'growth_landing_provider',brandId:'b',storeId:'s',baseUrl:'https://mapdal.kr',tenantId:'tenant',providerStoreId:'shop',secret:await crypto.sealRecordSecret(owner,'channel_credential','growth_landing_provider:s',secret),enabled:true,version:1});
let passed=0;const check=(v,m)=>{assert.ok(v,m);passed++};
const post=async(b,h=headers)=>{const r=await api.POST(new Request('https://agency.test/api/growth/provider-catalog',{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,requestId:randomUUID(),...b})}));return{status:r.status,body:await r.json()}};
const view=async()=>{const r=await api.GET(new Request('https://agency.test/api/growth/provider-catalog?campaignId=c',{headers}));return r.json();},currentStock=async()=>(await stock.catalogStocks(owner,c,[input]))[0];
check((await currentStock()).available===7,'local-only SKU unchanged');
check((await post({action:'bind',catalogId:'cat',catalogVersion:1,inventoryId:'inv',inventoryVersion:1,productId:'mpd::1',expectedVersion:0},{})).status===401,'auth required');
check((await post({action:'bind',catalogId:'cat',catalogVersion:1,inventoryId:'inv',inventoryVersion:1,productId:'mpd::1',expectedVersion:0})).status===200,'owner exact mapping');
let row=(await view()).rows[0];check((await currentStock()).status==='held','binding holds until signed source reviewed');
check((await post({action:'pull',id:row.binding.id,expectedVersion:1})).status===200,'read-only pull accepted');row=(await view()).rows[0];
check((await post({action:'review',id:row.binding.id,expectedVersion:1,sourceVersion:row.source.version,sourceDigest:row.source.digest,confirmed:true})).status===200,'exact source reviewed');
check((await currentStock()).available===1&&(await currentStock()).reserved===3,'provider ceiling subtracts outstanding local reservations');
check(JSON.stringify(await s.readRecord(owner,'growth_stock_event','reserve'))===JSON.stringify(event),'stock event immutable');
const invBefore=await s.readRecord(owner,'growth_inventory_item','inv');
await put('growth_inventory_item','inv',{...invBefore,version:2},'s');
await put('growth_stock_event','reserve-extra',{...event,id:'reserve-extra',version:2,quantity:1,reservationId:'res-extra',missionId:'m-extra'},'inv');
check((await currentStock()).available===0&&(await currentStock()).reserved===4,'new reservation exhausts provider capacity without another pull');
await put('growth_stock_event','reserve-extra',{...event,id:'reserve-extra',version:2,quantity:2,reservationId:'res-extra',missionId:'m-extra'},'inv');
check((await currentStock()).available===0&&(await currentStock()).reserved===5,'over-capacity existing obligations cannot open more availability');
await put('growth_stock_event','reserve-extra',{...event,id:'reserve-extra',version:2,quantity:1,reservationId:'res-extra',missionId:'m-extra'},'inv');
await put('growth_stock_event','allocate-extra',{...event,id:'allocate-extra',version:3,kind:'allocate',quantity:1,reservationId:'res-extra',missionId:'m-extra',orderId:'order-extra'},'inv');
await put('growth_stock_event','ship-extra',{...event,id:'ship-extra',version:4,kind:'ship',quantity:1,reservationId:'res-extra',missionId:'m-extra',orderId:'order-extra'},'inv');
await put('growth_inventory_item','inv',{...invBefore,version:4},'s');
check((await currentStock()).status==='held','shipment cannot resurrect availability from unchanged provider snapshot');
await put('growth_stock_event','receive-extra',{...event,id:'receive-extra',version:5,kind:'receive',quantity:1,reservationId:'',missionId:'',orderId:''},'inv');
await put('growth_inventory_item','inv',{...invBefore,version:5},'s');
check((await currentStock()).onHand===10&&(await currentStock()).status==='held','equal on-hand after receive does not erase physical event lineage');
row=(await view()).rows[0];check((await post({action:'review',id:row.binding.id,expectedVersion:2,sourceVersion:row.source.version,sourceDigest:row.source.digest,confirmed:true})).status===409,'review rejects pre-movement source');
await post({action:'pull',id:row.binding.id,expectedVersion:2});row=(await view()).rows[0];check((await currentStock()).status==='held','same provider contents after movement need fresh review');
check((await post({action:'review',id:row.binding.id,expectedVersion:2,sourceVersion:row.source.version,sourceDigest:row.source.digest,confirmed:true})).status===200&&(await currentStock()).available===1,'repull and exact review recover after physical movement');
// Restore this test fixture and repull so subsequent signature/CAS scenarios stay independent.
for(const id of ['allocate-extra','ship-extra','receive-extra'])sql.prepare("DELETE FROM records WHERE kind='growth_stock_event' AND id=?").run(owner+':growth_stock_event:'+id);
await put('growth_inventory_item','inv',invBefore,'s');sql.prepare("DELETE FROM records WHERE kind='growth_stock_event' AND id=?").run(owner+':growth_stock_event:reserve-extra');
check((await currentStock()).status==='held','restored physical fixture still needs new signed pull');
await post({action:'pull',id:row.binding.id,expectedVersion:3});row=(await view()).rows[0];await post({action:'review',id:row.binding.id,expectedVersion:3,sourceVersion:row.source.version,sourceDigest:row.source.digest,confirmed:true});
check(!JSON.stringify(await view()).includes(secret),'credential never projected');
row=(await view()).rows[0];mode='bad-signature';await post({action:'pull',id:row.binding.id,expectedVersion:4});check((await currentStock()).status==='held'&&(await view()).rows[0].source.status==='failed','malformed signed product held and sync failure visible');
mode='valid';sellable=2;await post({action:'pull',id:row.binding.id,expectedVersion:4});row=(await view()).rows[0];check((await currentStock()).status==='held','changed stock snapshot requires new review');
check((await post({action:'review',id:row.binding.id,expectedVersion:4,sourceVersion:row.source.version-1,sourceDigest:row.source.digest,confirmed:true})).status===409,'source revision CAS');
await post({action:'review',id:row.binding.id,expectedVersion:4,sourceVersion:row.source.version,sourceDigest:row.source.digest,confirmed:true});check((await currentStock()).available===0,'reviewed lower ceiling cannot disregard existing obligations');
mode='deleted';await post({action:'pull',id:row.binding.id,expectedVersion:5});check((await currentStock()).status==='held','provider deletion held without deleting local stock');
check((await s.readRecord(owner,'growth_inventory_item','inv')).input.onHand===10,'physical on-hand unchanged');
check(calls===6,'bounded single-product pulls');
check(sql.prepare("SELECT count(*) n FROM records WHERE kind='growth_provider_catalog_history'").get().n>0,'audit history stored');
const oldSource=await s.readRecord(owner,'growth_provider_catalog_source',row.binding.id);
sql.exec("CREATE TRIGGER fail_catalog_history BEFORE INSERT ON records WHEN NEW.kind='growth_provider_catalog_history' BEGIN SELECT RAISE(ABORT,'atomic'); END;");
mode='valid';check((await post({action:'pull',id:row.binding.id,expectedVersion:5})).status===500,'history failure fails whole source transaction');
check(JSON.stringify(await s.readRecord(owner,'growth_provider_catalog_source',row.binding.id))===JSON.stringify(oldSource),'failed audit preserves prior source');sql.exec('DROP TRIGGER fail_catalog_history');
duringPull=async()=>{await put('growth_stock_event','during-pull-receive',{...event,id:'during-pull-receive',version:2,kind:'receive',quantity:1,reservationId:'',missionId:'',orderId:''},'inv');await put('growth_inventory_item','inv',{...invBefore,version:2},'s');};
check((await post({action:'pull',id:row.binding.id,expectedVersion:5})).status===200&&(await view()).rows[0].source.status==='failed','physical movement during provider request invalidates source');
check((await currentStock()).status==='held','concurrent physical movement never creates executable stock snapshot');
console.log(JSON.stringify({passed,sqlite:'real',provider:'mocked',externalWrites:0}));
