// Real SQLite, synthetic Q snapshots, no external requests.
import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
const {load}=testRuntime(async()=>{throw Error('external forbidden')});
const s=await load('lib/server.ts'),helper=await load('lib/growth-optimization-rule-server.ts');
const owner='o',c={id:'c',brandId:'b',storeId:'s',channels:'커머스',version:1},put=(kind,id,v)=>s.recordStatement(owner,kind,id,v,c.id).run();
const rule={id:'rule',brandId:'b',storeId:'s',origin:'review',grade:'operator_preference',role:'content',channel:'*',title:'배송 안내',guidance:'배송 조건을 먼저 제시한다.',scope:'브랜드',status:'active',version:1,expiresAt:'2099-01-01',createdAt:'2026-01-01',updatedAt:'2026-01-01'};
const kase={id:'case',kind:'role',role:'content',set:'sealed',label:'합성',request:{campaign:c},expectations:{},createdAt:'2026-01-01',updatedAt:'2026-01-01'};
await put('learning_rule',rule.id,rule);await put('eval_case',kase.id,kase);
const r={id:'candidate',input:{candidateKind:'operating_rule',targetRef:'rule',proposal:rule.guidance,tokenBudget:100000,krwBudget:10000}};
let passed=0;const check=(v,m)=>{assert.ok(v,m);passed++};
const e=await helper.freezeRuleEvaluation(owner,c,r,{caseIds:['case']});
check(e.kind==='operator_preferences'&&e.rule.version===1&&e.pair.block.rules[0].text===r.input.proposal,'exact full rule and Q block frozen');
check((await helper.validateRuleEvaluation(owner,c,{...r,ruleEvaluation:e})).valid,'free validation current');
await assert.rejects(()=>helper.freezeRuleEvaluation(owner,c,{...r,input:{...r.input,proposal:'다른 본문'}},{caseIds:['case']}));passed++;
await put('eval_case','case',{...kase,request:{campaign:{...c,brandId:'other'}}});await assert.rejects(()=>helper.freezeRuleEvaluation(owner,c,r,{caseIds:['case']}));passed++;
await put('eval_case','case',kase);
await put('learning_rule','rule',{...rule,guidance:'수정',version:2});await assert.rejects(()=>helper.assertRuleEvaluation(owner,c,{...r,ruleEvaluation:e}));passed++;
await put('learning_rule','rule',rule);
await put('eval_case','case',{...kase,label:'modified'});await assert.rejects(()=>helper.assertRuleEvaluation(owner,c,{...r,ruleEvaluation:e}));passed++;
await put('eval_case','case',kase);
assert.throws(()=>helper.requireEnforcedEvaluationCost());passed++;
check((await s.listRecords(owner,'eval_run')).length===0,'free validation never creates paid run');
const q=await load('lib/eval-server.ts'),hash=await load('lib/storefront-orders.ts');
const intent={label:'growth-opt-rule:test',at:new Date().toISOString(),by:owner,tokenBudget:100000};
const response=await q.evalAction(owner,{action:'start_run',label:intent.label,variant:'pair',pair:{kind:'operator_preferences',ruleIds:['rule']},caseIds:['case'],tokenBudget:100000},{owner,id:owner,role:'owner',email:null});
const responseBody=await response.json(),run=responseBody.run??responseBody;
check(await helper.ruleRunMatches({...e,intent},run),'public Q creates exact operator preference pair');
check(!await helper.ruleRunMatches({...e,intent},{...run,pair:{...run.pair,blockHash:'tampered'}}),'full block hash mismatch rejected');
check(!await helper.ruleRunMatches({...e,intent},{...run,usedTokens:100001}),'over-budget run rejected');
check(!await helper.ruleRunMatches({...e,intent},{...run,pair:{unit:'content',candidateVersionId:'other'}}),'prompt pair cannot replace rule pair');
const aid=await (await load('lib/role-execution.ts')).roleArtifactId('snap');
const artifact={id:aid,campaignId:'c',role:'content',version:1,origin:'ai',status:'approved'};
await put('artifact',artifact.id,artifact);await put('learning_snapshot','snap',{id:'snap',campaignId:'c',role:'content',artifactId:artifact.id,operatorPreferences:[rule]});
const link={id:'link',campaignId:'c',brandId:'b',version:1,status:'published',snapshot:{publication:{copy:{artifactId:aid,artifactVersion:1}}}};await put('growth_publication_link',link.id,link);
const input={interventionRefs:[{kind:'publication_link',id:'link',version:1}]},experiment={id:'experiment',input,registration:{digest:await hash.storefrontDigest({id:'experiment',input}),refs:input.interventionRefs}};
check((await helper.ruleSalesIntervention(owner,c,{...r,ruleEvaluation:e},experiment)).snapshotId==='snap','exact injected full rule snapshot joins registered publication');
await put('artifact',artifact.id,{...artifact,version:2});await assert.rejects(()=>helper.ruleSalesIntervention(owner,c,{...r,ruleEvaluation:e},experiment));passed++;
await put('artifact',artifact.id,artifact);await put('learning_snapshot','snap',{id:'snap',campaignId:'c',role:'content',artifactId:artifact.id,operatorPreferences:[{...rule,guidance:'different same version'}]});await assert.rejects(()=>helper.ruleSalesIntervention(owner,c,{...r,ruleEvaluation:e},experiment));passed++;
const api=await load('lib/growth-optimization-server.ts'),who={owner,id:owner,role:'owner',email:null};
await put('growth_lesson_application','failure',{id:'failure',campaignId:'c',brandId:'b',version:1,outcome:{result:'failure'}});
const call=(action,expectedVersion,more={})=>api.saveGrowthOptimization(who,c,{action,id:'flow',campaignVersion:1,expectedVersion,requestId:globalThis.crypto.randomUUID(),...more});
await call('save_candidate',0,{input:{...r.input,failureKind:'lesson_application',failureId:'failure',failureVersion:1,failureSummary:'합성 실패'}});
await call('freeze',1,{evaluation:{caseIds:['case']}});await call('validate_evaluation',2);
const frozen=await s.readRecord(owner,'growth_optimization','flow');check(frozen.stage==='frozen'&&frozen.validation.valid&&!frozen.offline,'free validation cannot masquerade as Q pass');
await assert.rejects(()=>call('start_evaluation',3,{confirmed:true,krwCapNotEnforced:true}));passed++;
check(!(await s.readRecord(owner,'growth_optimization','flow')).ruleEvaluation.intent,'unbounded paid approval cannot create intent');
console.log(JSON.stringify({passed,externalCalls:0,sqlite:'real',q:'mocked'}));
