import assert from 'node:assert/strict';import {testRuntime} from './helpers/runtime.mjs';
const {load}=testRuntime(async()=>{throw Error('external forbidden')});const d=await load('lib/growth-reorder.ts');let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const now=Date.parse('2026-09-30T03:00:00Z'),input={...d.emptyReorderInput(),catalogId:'p',catalogVersion:1,candidateId:'q',candidateVersion:1,unit:'piece',demand:{from:'2026-09-21',to:'2026-09-30',quantity:20,evidenceRef:'demand-v1'},coverageDays:5,safetyQuantity:3,outstanding:{state:'confirmed_none',observedAt:'2026-09-30T09:00:00+09:00',evidenceRef:'receipts-v1'},purchaseBudget:10000,budgetEvidenceRef:'budget-v1',note:''};
const catalog={id:'p',version:1,campaignVersion:1,input:{sku:'SKU',taxBasis:'included',validUntil:'2099-01-01'}},candidate={id:'q',version:1,campaignVersion:1,input:{catalogId:'p',catalogVersion:1,supplierCode:'SUP',unit:'piece',currency:'KRW',unitCost:100,moq:12,leadDays:2,shippingCost:50,extraCost:0,taxBasis:'included',validUntil:'2099-01-01',evidenceRef:'quote-v1',note:''}},stock={status:'known',unit:'piece',onHand:5,reserved:10,available:0,shortage:5,items:[],reason:''};
const run=(patch={},inv=stock,q=candidate,cat=catalog,at=now)=>d.assessReorder({...input,...patch},cat,q,inv,1,at);
check(d.parseReorderInput(input,now).demand.quantity===20,'parse quantity');check(d.parseReorderInput({...input,demand:{...input.demand,quantity:null}},now).demand.quantity===null,'null preserved');
for(const patch of [{coverageDays:-1},{safetyQuantity:1.1},{purchaseBudget:Number.MAX_SAFE_INTEGER+1},{note:'person@example.com'},{demand:{...input.demand,from:'2026-02-30'}},{demand:{...input.demand,from:'2026-10-01',to:'2026-10-02'}},{demand:{...input.demand,from:'2026-09-30',to:'2026-09-21'}},{outstanding:{...input.outstanding,observedAt:'2026-09-30T13:00:00Z'}}]){assert.throws(()=>d.parseReorderInput({...input,...patch},now));passed++}
let r=run();check(r.status==='reviewable','known reviewable');check(r.observedDays===10&&r.demandPerDay===2,'inclusive rate');check(r.rawStock===-5,'reserved shortage preserved');check(r.reorderPoint===7&&r.targetQuantity===17,'lead coverage safety');check(r.neededQuantity===22&&r.purchaseQuantity===22,'MOQ minimum not multiple');check(r.cashNeed===2250,'cash includes fixed fee');check(r.daysUntilReorder===0,'already reorder point');check(r.mayOrder===false,'no execution');
r=run({}, {...stock,onHand:100,reserved:0});check(r.purchaseQuantity===0&&r.quoteSubtotal===0&&r.cashNeed===0,'zero need skips MOQ fees');check(r.daysUntilReorder===46,'days is assumption');
r=run({demand:{...input.demand,quantity:0}}, {...stock,onHand:10,reserved:0});check(r.daysUntilReorder===null&&r.purchaseQuantity===0,'zero demand no forecast');
for(const patch of [{demand:{...input.demand,quantity:null}},{coverageDays:null},{safetyQuantity:null},{outstanding:{state:'unknown',observedAt:null,evidenceRef:''}},{outstanding:{...input.outstanding,observedAt:'2026-09-29T00:00:00Z'}}])check(run(patch).status==='held','missing held');
check(run({}, {...stock,status:'unknown',onHand:null}).purchaseQuantity===null,'unknown stock no quantity');check(run({}, {...stock,unit:'pack'}).purchaseQuantity===null,'no unit conversion');
r=run({},stock,{...candidate,input:{...candidate.input,taxBasis:'excluded'}},{...catalog,input:{...catalog.input,taxBasis:'excluded'}});check(r.cashNeed===null&&r.quoteSubtotal===2250&&r.budgetAssessment==='unknown'&&r.status==='held','tax excluded subtotal not cash');
check(run({purchaseBudget:1}).budgetAssessment==='exceeded'&&run({purchaseBudget:1}).status==='held','budget exceeded holds');check(run({purchaseBudget:null,budgetEvidenceRef:''}).budgetAssessment==='not_configured','optional budget');
check(run({demand:{...input.demand,quantity:Number.MAX_SAFE_INTEGER}}).status==='held','quantity multiplication overflow');check(run({},stock,{...candidate,input:{...candidate.input,unitCost:Number.MAX_SAFE_INTEGER}}).cashNeed===null,'cost overflow');check(run({},stock,candidate,catalog,Date.parse('2026-09-30T15:00:00Z')).status==='held','confirmation stale next KST day');
assert.throws(()=>d.parseReorderInput({...input,outstanding:{...input.outstanding,observedAt:'2026-09-30T00:00:00+15:00'}},now));passed++;
r=run({},stock,candidate,{...catalog,input:{...catalog.input,stockUnit:'pack'}});check(r.status==='held'&&['rawStock','neededQuantity','purchaseQuantity','quoteSubtotal','cashNeed','reorderPoint','targetQuantity','daysUntilReorder'].every(k=>r[k]===null),'explicit catalog pack does not produce piece reorder quantities or cash');
check(run({},stock,candidate,{...catalog,input:{...catalog.input,stockUnit:'unknown'}}).purchaseQuantity===22,'legacy unknown retains explicitly stated sourcing assumption');
console.log(JSON.stringify({passed,external:'not_called'}));
