// Synthetic SQLite and public Q APIs. No provider request is permitted.
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
let loseQSave=false;
const rt=testRuntime(async()=>{throw Error('external forbidden')},{beforeRun:statement=>{if(loseQSave&&statement.values?.[2]==='eval_run'){loseQSave=false;rt.sql.prepare(statement.query).run(...statement.values);throw Error('simulated lost Q storage response')}}});
const s=await rt.load('lib/server.ts'),api=await rt.load('lib/growth-optimization-server.ts');
const owner='o',who={id:owner,owner,role:'owner',email:null},c={id:'c',brandId:'b',version:1,status:'active'};
const put=(kind,id,v)=>s.recordStatement(owner,kind,id,v,'c').run();
await put('growth_lesson_application','f',{id:'f',campaignId:'c',brandId:'b',version:1,outcome:{result:'failure'}});
const input={failureKind:'lesson_application',failureId:'f',failureVersion:1,failureSummary:'합성 실패',candidateKind:'prompt_unit',targetRef:'channel.commerce',proposal:'등록된 배송 안내 후보 평가',tokenBudget:100000,krwBudget:10000};
const body='배송 가능 여부와 구매 조건을 먼저 설명한다.',sha=createHash('sha256').update(JSON.stringify(body)).digest('hex'),vid='channel.commerce@'+sha.slice(0,12);
await put('prompt_version',vid,{id:vid,unit:'channel.commerce',body,sha256:sha});
const evalCase={id:'case',kind:'role',role:'content',label:'합성 봉인',set:'sealed',request:{campaign:{id:'c',channels:'커머스'}},expectations:{prohibitedTerms:[]},campaignId:'c',createdAt:'2026-01-01',updatedAt:'2026-01-01'};
await put('eval_case','case',evalCase);
let count=0;const check=(ok,label)=>{assert.ok(ok,label);count++};
const call=(action,version,more={},id='x')=>api.saveGrowthOptimization(who,c,{action,id,expectedVersion:version,campaignVersion:1,requestId:randomUUID(),...more});
await call('save_candidate',0,{input});
await call('freeze',1,{evaluation:{candidateVersionId:vid,caseIds:['case']}});
await put('eval_run','unrelated',{id:'unrelated',status:'completed',results:[],tokenBudget:1000,usedTokens:5,createdAt:new Date(Date.now()+1000).toISOString()});
await assert.rejects(call('record_offline',2,{evalRunId:'unrelated',verdict:'pass'}));check(true,'unrelated manual pass rejected');
const row=await s.readRecord(owner,'growth_optimization','x');check(!!row.evaluation?.caseDigest,'frozen case digest exists');
await assert.rejects(call('start_evaluation',2,{confirmed:false}));check(true,'owner explicit spend confirmation required');
await assert.rejects(api.saveGrowthOptimization({...who,role:'admin'},c,{action:'start_evaluation',id:'x',expectedVersion:2,campaignVersion:1,requestId:randomUUID(),confirmed:true,krwCapNotEnforced:true}));check(true,'admin cannot queue');
await put('growth_stop','global',{id:'global',status:'stopped',version:1,reason:'합성 중단',updatedAt:new Date().toISOString(),updatedBy:owner});
await assert.rejects(call('start_evaluation',2,{confirmed:true,krwCapNotEnforced:true}));check(true,'global stop blocks new evaluation');
await put('growth_stop','global',{id:'global',status:'running',version:2,reason:'합성 재개',updatedAt:new Date().toISOString(),updatedBy:owner});
const req={action:'start_evaluation',id:'x',expectedVersion:2,campaignVersion:1,requestId:randomUUID(),confirmed:true,krwCapNotEnforced:true};
await assert.rejects(api.saveGrowthOptimization(who,c,req));check(true,'KRW warning cannot bypass hard cost gate');
// Legacy accepted intents are seeded solely to exercise read-only recovery/matching.
async function legacyIntent(id){const old=await s.readRecord(owner,'growth_optimization',id),intent={label:'growth-opt:legacy-'+id,at:new Date().toISOString(),by:owner,tokenBudget:old.input.tokenBudget,krwBudget:old.input.krwBudget,krwCapNotEnforced:true};await put('growth_optimization',id,{...old,version:3,evaluation:{...old.evaluation,intent}});try{await (await rt.load('lib/eval-server.ts')).evalAction(owner,{action:'start_run',label:intent.label,variant:'pair',pair:{unit:old.evaluation.pair.unit,candidateVersionId:vid},caseIds:['case'],tokenBudget:intent.tokenBudget},who)}catch{/* storage response loss fixture */}}
await legacyIntent('x');
const runs=()=>rt.sql.prepare("SELECT data FROM records WHERE kind='eval_run' AND json_extract(data,'$.label') LIKE 'growth-opt:%'").all().map(r=>JSON.parse(r.data));
check(runs().length===1,'Q run queued or blocked exactly once');
await assert.rejects(api.saveGrowthOptimization(who,c,req));check(runs().length===1,'same request response loss never creates duplicate');
await assert.rejects(call('start_evaluation',3,{confirmed:true,krwCapNotEnforced:true}));check(runs().length===1,'new UUID cannot repeat uncertain execution');
await put('eval_case','case',{...evalCase,label:'changed'});
await assert.rejects(call('record_offline',3,{}));check(true,'changed cases cannot be recovered as same evaluation');
await call('save_candidate',0,{input:{...input,candidateKind:'landing_copy'}},'landing');await assert.rejects(call('freeze',1,{},'landing'));
await assert.rejects(call('record_offline',2,{evalRunId:'unrelated',verdict:'pass'},'landing'));check(true,'non-prompt requires dedicated adapter');

await put('eval_case','case',evalCase);
const helper=await rt.load('lib/growth-optimization-evaluation-server.ts'),current=await s.readRecord(owner,'growth_optimization','x'),run=runs()[0];
check(await helper.runMatches(current,run),'exact Q snapshot accepted');
check(!await helper.runMatches(current,{...run,usedTokens:100001}),'over-budget run rejected');
check(!await helper.runMatches(current,{...run,pair:{...run.pair,candidateVersionId:'channel.commerce@000000000000'}}),'other registered candidate rejected');
check(!await helper.runMatches(current,{...run,caseIds:['another']}),'different case set rejected');
check(!await helper.runMatches(current,{...run,results:run.results.map(x=>({...x,caseId:'another'}))}),'result rows cannot claim unrelated cases');
await assert.rejects(call('start_evaluation',3,{confirmed:true}));check(true,'KRW warning cannot be omitted');
await call('save_candidate',0,{input:{...input,krwBudget:0}},'zero');await call('freeze',1,{evaluation:{candidateVersionId:vid,caseIds:['case']}},'zero');
await assert.rejects(call('start_evaluation',2,{confirmed:true,krwCapNotEnforced:true},'zero'));check(true,'zero KRW never authorizes provider spend');
await call('save_candidate',0,{input:{...input,tokenBudget:50000}},'small');
await assert.rejects(call('freeze',1,{evaluation:{candidateVersionId:vid,caseIds:['case']}},'small'));check(true,'pair reservation over budget blocked before enqueue');
await call('save_candidate',0,{input},'lost');await call('freeze',1,{evaluation:{candidateVersionId:vid,caseIds:['case']}},'lost');loseQSave=true;
await legacyIntent('lost');
await assert.rejects(call('start_evaluation',3,{confirmed:true,krwCapNotEnforced:true},'lost'));check(runs().length===2,'Q save response loss retains intent and blocks blind retry');
const lost=(await s.readRecord(owner,'growth_optimization','lost')),lostRun=runs().find(x=>x.label===lost.evaluation.intent.label);check(!!lostRun,'accepted run recovered by immutable intent label after lost response');
await assert.rejects(helper.salesIntervention(owner,c,current,{id:'wrong',registration:{digest:'forged',refs:[]},input:{interventionRefs:[]}}));check(true,'mismatched sales registration rejected');
const gateway={eval:{hash:'e'},operational:{hash:'o'}},done={...run,status:'completed',usedTokens:100,gatewaySnapshot:gateway,gatewaySnapshotEnd:gateway,results:run.results.map(x=>({...x,status:'completed',model:'synthetic',graders:[{id:'input_budget',status:x.variant==='candidate'?'fail':'pass'}]}))};
await put('eval_run',run.id,done);await call('record_offline',3,{verdict:'pass'});
check((await s.readRecord(owner,'growth_optimization','x')).offline.verdict==='fail','client pass cannot override server fail');
console.log(JSON.stringify({passed:count}));
