// 고객 문의 운영자 요약·약속 기한·처리 기록·반복 유형(G2-30 CS). 인증 mocked, 메모리 SQLite real, 외부 0.
import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {testRuntime} from './helpers/runtime.mjs';
const {load}=testRuntime(async()=>{throw Error('external forbidden')});
const server=await load('lib/server.ts'),route=await load('app/api/growth/cs/route.ts'),pure=await load('lib/growth-cs.ts');let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='owner',c={id:'c',brandId:'b',storeId:'s',version:1,status:'active'},h={'oai-authenticated-user-id':owner,origin:'https://agency.test'};
const put=(kind,id,data,parent='')=>server.recordStatement(owner,kind,id,data,parent).run();await put('campaign','c',c);
await put('growth_order_line','line',{id:'line',brandId:'b',storeId:'s',campaignId:'c',version:2,input:{orderId:'o',inventoryId:'i',missionId:'m'}},'s');
await put('growth_return_reason','ev1',{id:'ev1',eventId:'ev1',brandId:'b',storeId:'s',campaignId:'c',version:1,input:{reasonCode:'wrong_option',evidenceRef:'x'},snapshot:{lineId:'line'}},'c');
const H=3600000,iso=t=>new Date(t).toISOString(),now=Date.now();
const ticket=(p={})=>({category:'shipping_delay',channel:'chat',summary:'배송 지연 문의, 출고 일정 안내 필요',lineId:'line',receivedAt:iso(now-5*H),promisedBy:iso(now-H),assignee:'CS 담당',priority:'normal',...p});
const unpack=async r=>({status:r.status,body:await r.json()}),post=(data,headers=h)=>route.POST(new Request('https://agency.test/api/x',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,expectedVersion:0,requestId:randomUUID(),...data})})).then(unpack),get=(headers=h)=>route.GET(new Request('https://agency.test/api/growth/cs?campaignId=c',{headers})).then(unpack);
check((await post({action:'save_ticket',id:'t1',input:ticket()},{})).status===401,'auth');check((await post({action:'save_ticket',id:'t1',input:ticket()},{...h,origin:'https://evil.test'})).status===403,'CSRF');
check((await post({action:'save_ticket',id:'t1',input:ticket({summary:'고객 010-1234-5678 연락 요청'})})).status===400,'phone rejected');check((await post({action:'save_ticket',id:'t1',input:ticket({summary:'주소: 서울시 어딘가 1-2'})})).status===400,'address rejected');
check((await post({action:'save_ticket',id:'t1',input:ticket({summary:'"배송이 너무 늦어서 정말 화가 납니다 빨리 보내주세요"'})})).status===400,'long quoted raw message rejected');
check((await post({action:'save_ticket',id:'t1',input:ticket({promisedBy:iso(now-6*H)})})).status===400,'promise before receipt rejected');check((await post({action:'save_ticket',id:'t1',input:ticket({receivedAt:iso(now+2*H)})})).status===400,'future receipt rejected');
check((await post({action:'save_ticket',id:'t1',input:ticket({lineId:'nope'})})).status===404,'unknown line rejected');
let r=await post({action:'save_ticket',id:'t1',input:ticket()});check(r.status===200&&r.body.mayExecute===false,'ticket saved');
r=await get();let t=r.body.tickets[0];check(t.status==='open'&&t.service.overdue&&r.body.overdue===1&&t.lineStatus==='current'&&t.returnReasons[0].reasonCode==='wrong_option','overdue open ticket linked to line and return reason');check(r.body.mayReply===false&&r.body.mayRefund===false,'no reply or refund');
const ev=(v,p)=>post({action:'record_event',id:'t1',expectedVersion:v,event:{at:iso(now-2*H),evidenceRef:'ev-1',note:'',...p}});
check((await ev(1,{action:'reopen'})).status===409,'cannot reopen open ticket');check((await ev(1,{action:'respond',at:iso(now-6*H)})).status===409,'event before receipt rejected');
check((await ev(1,{action:'respond'})).status===200,'responded');check((await post({action:'save_ticket',id:'t1',expectedVersion:2,input:ticket({summary:'바꾼 요약'})})).status===409,'intake frozen after response');
check((await ev(2,{action:'resolve',at:iso(now-3*H)})).status===409,'resolve before previous event rejected');check((await ev(2,{action:'resolve',at:iso(now-30*60000)})).status===409,'resolution code required');
r=await ev(2,{action:'resolve',at:iso(now-30*60000),resolution:'shipped'});check(r.status===200,'resolved');r=await get();t=r.body.tickets[0];check(t.status==='resolved'&&!t.service.overdue&&t.service.resolvedLate&&t.service.firstResponseHours===3,'resolved late tracked, first response hours');
await put('growth_order_line','line',{id:'line',brandId:'b',storeId:'s',campaignId:'c',version:3,input:{orderId:'o',inventoryId:'i',missionId:'m'}},'s');check((await get()).body.tickets[0].lineStatus==='held','line changed shows held');
for(const n of [2,3])await post({action:'save_ticket',id:'t'+n,input:ticket({lineId:'',promisedBy:iso(now+H)})});
r=await get();check(r.body.recurring.recurring.includes('shipping_delay')&&r.body.recurring.basis==='ticket_count_not_rate','3 shipping delays in 30 days flagged as recurring count');check(r.body.history.length>=5,'history');
await put('campaign','c',{...c,status:'archived'});check((await post({action:'record_event',id:'t2',expectedVersion:1,event:{action:'cancel',at:iso(now-60000),evidenceRef:'ev-c',note:''}})).status===200,'archived campaign still records CS handling');
check((await get({'oai-authenticated-user-id':'other'})).status===404,'owner isolation');
check(pure.csServiceLevel({status:'open',input:pure.parseCsTicket(ticket({promisedBy:iso(now+H)})),events:[]},now).overdue===false,'not overdue before promise');
console.log(JSON.stringify({passed}));
