import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
const {load,sql}=testRuntime(async()=>{throw Error('external forbidden')});
const server=await load('lib/server.ts'),helper=await load('lib/growth-offer-review-drafts-server.ts'),hash=await load('lib/storefront-orders.ts'),exp=await load('lib/growth-experiment-server.ts'),pure=await load('lib/growth-experiment.ts'),catalog=await load('lib/growth-catalog.ts'),mission=await load('lib/growth-mission.ts');
const who={owner:'owner',id:'daily',role:'owner',email:null},c={id:'c',brandId:'b',storeId:'s',version:1,status:'active'},base={brandId:'b',campaignId:'c',campaignVersion:1,version:1};
const put=(kind,id,data,parent='c')=>server.recordStatement(who.owner,kind,id,data,parent).run();
await put('campaign','c',c);await put('store','s',{id:'s',brandId:'b'},'b');
await put('growth_catalog','cat',{...base,id:'cat',input:{...catalog.emptyCatalogInput(),title:'상품',sku:'sku',validUntil:'2099-12-31'}});
const offer={...base,id:'offer',input:{...catalog.emptyOfferInput(),title:'오퍼',catalogId:'cat',catalogVersion:1,priceApproved:true}};await put('growth_offer','offer',offer);
await put('growth_mission','mission',{...base,id:'mission',input:{...mission.emptyMissionInput(),title:'미션',offerId:'offer',offerVersion:1,channel:'storefront'}});
const now=Date.now(),iso=v=>new Date(v).toISOString(),design={title:'합성 실험',mode:'confirm',aa:false,hypothesis:'상품 안내',missionId:'mission',missionVersion:1,offerId:'offer',offerVersion:1,channel:'storefront',intervention:'상품 안내',interventionRefs:[{kind:'offer',id:'offer',version:1}],assignmentUnit:'pseudonymous_visitor',treatmentShare:0.5,metric:'paid_orders',lowerBound:0,upperBound:1,minEffect:0.05,minSamplePerArm:30,startAt:iso(now-86400000),endAt:iso(now-3600000),maturityDays:0,stopRule:'중단'};
const e={...base,id:'exp',storeId:'s',status:'registered',input:design,registration:{digest:await hash.storefrontDigest({id:'exp',input:design}),refs:design.interventionRefs,at:iso(now-172800000)},seed:'synthetic'};await put('growth_experiment','exp',e);
const order={id:'order',storeId:'s',campaignId:'c',version:1,orderDate:iso(now-7200000).slice(0,10),status:'paid',paidAmount:1000,refundAmount:0,costs:{foodCost:1}};await put('store_order','order',order,'s');
await put('growth_experiment_unit','unit',{id:'unit',designId:'exp',brandId:'b',campaignId:'c',version:1,unitHash:'a'.repeat(64),arm:'control',observation:{exposed:true,trackingComplete:true,contaminated:false,orderIds:['order']}});
const basis=await exp.readExperimentOutcomeBasis(who.owner,c,'exp'),analysis=pure.analyseExperiment(design,[{arm:'control',exposed:true,trackingComplete:true,contaminated:false,value:1}],now,1),result={...base,id:'exp:1',designId:'exp',analysisNumber:1,designDigest:e.registration.digest,inputDigest:basis.inputDigest,analysis};await put('growth_experiment_result','exp:1',result);
let passed=0;const check=(ok,label)=>{assert.ok(ok,label);passed++;};
check((await helper.createGrowthOfferReviewDrafts(who,c)).created===1,'canonical latest analysis creates one review draft');
check((await helper.createGrowthOfferReviewDrafts(who,c)).created===0,'repeated daily chunk is idempotent');
let view=await helper.growthOfferReviewDraftsView(who,c);check(view.rows.length===1&&view.rows[0].sourceStatus==='current','visible current source');
check(JSON.stringify(await server.readRecord(who.owner,'growth_offer','offer'))===JSON.stringify(offer),'offer and price approval untouched');
check(view.rows[0].offer.version===1&&view.rows[0].offer.digest.length===64&&view.rows[0].mayApply===false,'review draft binds exact offer and never grants apply');
await put('store_order','order',{...order,refundAmount:1000,version:2},'s');view=await helper.growthOfferReviewDraftsView(who,c);check(view.rows[0].sourceStatus==='stale','refund invalidates observed analysis immediately');check((await helper.createGrowthOfferReviewDrafts(who,c)).created===0,'stale result never creates draft');await put('store_order','order',order,'s');
await put('growth_experiment_result','exp:2',{...result,id:'exp:2',analysisNumber:2});view=await helper.growthOfferReviewDraftsView(who,c);check(view.rows[0].sourceStatus==='stale','new latest analysis invalidates earlier proposal');check((await helper.createGrowthOfferReviewDrafts(who,c)).created===1,'new current evidence makes separate review draft');
await put('growth_offer','offer',{...offer,input:{...offer.input,purchaseReason:'changed'}});view=await helper.growthOfferReviewDraftsView(who,c);check(view.rows.every(r=>r.sourceStatus==='stale'),'same-version offer mutation is stale');await put('growth_offer','offer',offer);
await assert.rejects(helper.createGrowthOfferReviewDrafts({...who,role:'member'},c));passed++;
await assert.rejects(helper.createGrowthOfferReviewDrafts(who,{...c,version:2}));passed++;
await put('growth_stop','global',{id:'global',status:'stopped',version:1,reason:'stop',updatedAt:iso(now),updatedBy:who.owner},'');check((await helper.createGrowthOfferReviewDrafts(who,c)).created===0,'global stop creates no new draft');
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_offer'").get().n===1,'no replacement offers created');
await put('growth_stop','global',{id:'global',status:'running',version:2,reason:'resume',updatedAt:iso(now),updatedBy:who.owner},'');
const demand=await load('lib/growth-demand-evidence-server.ts');
const step={id:'step',channel:'organic',placement:'owned',message:'구매 조건 안내',useScene:'구매',creativeBrief:'사진',keywords:[],audience:'방문자',purchaseUrl:'https://example.com/p',sourceUrls:['https://example.com/ref'],rightsStatus:'confirmed',rightsEvidence:'자체',authenticityConfirmed:true,partnerRole:'',partnerTerms:'',plannedCost:0,performanceStatus:'not_measured',performanceEvidence:'',performanceNote:''};
const seq={...base,id:'seq',input:{title:'안내',offerId:'offer',offerVersion:1,missionId:'mission',missionVersion:1,steps:[step]}};
await put('growth_demand','seq',seq);await put('growth_publication_link','link',{...base,id:'link',intentId:'intent',publicationId:'publication',status:'published',snapshotDigest:'d'.repeat(64)});await put('growth_action_intent','intent',{...base,id:'intent',storeId:'s',input:{missionId:'mission',missionVersion:1},snapshot:{mission:{channel:'organic',offerId:'offer',offerVersion:1}}});await put('execution_publication','publication',{id:'publication',campaignId:'c',status:'published',scheduledAt:iso(now-86400000)});
await put('growth_demand_evidence','link',{...base,id:'link',status:'active',input:{sequenceId:'seq',sequenceVersion:1,stepId:'step',publicationLinkId:'link',publicationLinkVersion:1,evidenceRef:'observed'},snapshot:{sequenceVersion:1,stepDigest:await demand.stepDigest(step),offerId:'offer',offerVersion:1,missionId:'mission',missionVersion:1,publicationLinkVersion:1,publicationSnapshotDigest:'d'.repeat(64),intentId:'intent',intentMissionVersion:1,publicationId:'publication'}});
check((await helper.createGrowthOfferReviewDrafts(who,c)).created===0,'published alone is not response measurement');
await put('tracking_code','code',{id:'code',code:'TEST',type:'coupon',storeId:'s',campaignId:'c',publicationId:'publication'},'s');await put('store_order','response-order',{id:'response-order',storeId:'s',campaignId:'c',orderDate:iso(now).slice(0,10),status:'paid',paidAmount:1000,refundAmount:0,costs:{foodCost:0,packagingCost:0,fees:0,deliveryCost:0,benefitCost:0},channel:'social',attributionEvidence:'합성',codeAttribution:{codeId:'code',code:'TEST',publicationId:'publication',conflictCodeIds:[]}},'s');
check((await helper.createGrowthOfferReviewDrafts(who,c)).created===1,'canonical attributed reaction creates separate review draft');
view=await helper.growthOfferReviewDraftsView(who,c);check(view.rows.some(r=>r.source.kind==='response'&&r.sourceStatus==='current'),'reaction evidence visible without causal claim');
await put('growth_demand','seq',{...seq,input:{...seq.input,steps:[{...step,performanceStatus:'observed',performanceNote:'arbitrary private note'}]}});view=await helper.growthOfferReviewDraftsView(who,c);check(view.rows.find(r=>r.source.kind==='response').sourceStatus==='current'&&!JSON.stringify(view).includes('arbitrary private note'),'manual performance note excluded');
await put('growth_demand','seq',{...seq,input:{...seq.input,steps:[{...step,message:'changed'}]}});view=await helper.growthOfferReviewDraftsView(who,c);check(view.rows.find(r=>r.source.kind==='response').sourceStatus==='stale','changed canonical step invalidates draft');
await put('growth_demand','seq',seq);
await put('growth_experiment','broken',{...base,id:'broken',status:'registered'});
check((await helper.createGrowthOfferReviewDrafts(who,c)).sourceErrors>=1,'malformed source is isolated from other intake');
const template=view.rows[0];for(let i=0;i<997;i++)await put('growth_offer_review_draft','filler-'+i,{...template,id:'filler-'+i});
await put('growth_experiment_result','exp:3',{...result,id:'exp:3',analysisNumber:3});const held=await helper.createGrowthOfferReviewDrafts(who,c);check(held.intakeHeld&&held.created===0,'intake cap explicit without deleting prior drafts');
view=await helper.growthOfferReviewDraftsView(who,c);check(view.hasMore&&view.rows.length===50,'bounded visible history remains accessible at capacity');
for(let i=0;i<21;i++)await put('growth_experiment','cursor-'+i,{...e,id:'cursor-'+i,registration:{...e.registration,digest:'invalid'}});
check((await helper.createGrowthOfferReviewDrafts(who,c)).remaining,'source cursor bounds each chunk');
check(!(await helper.createGrowthOfferReviewDrafts(who,c)).remaining,'next chunk reaches remaining sources despite held intake');
console.log(JSON.stringify({passed,sqlite:'real',external:'not_called'}));
