import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
let breakBatch=false;
const {load,sql,env}=testRuntime(async()=>{throw Error('Consumer cannot dispatch')},{beforeRun:s=>{if(breakBatch&&s.values.includes('growth_consumer_request'))throw Error('synthetic write failure')}});
const server=await load('lib/server.ts'),route=await load('app/api/growth/consumer/route.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='consumer-owner',c={id:'c',brandId:'b',storeId:'s',version:1,status:'active'},h={'oai-authenticated-user-id':owner,origin:'https://agency.test'};
await server.recordStatement(owner,'campaign','c',c).run();await server.recordStatement(owner,'store','s',{id:'s',brandId:'b',status:'active'}).run();
await server.recordStatement(owner,'campaign','same',{...c,id:'same'}).run();
const order={id:'order',storeId:'s',version:1,orderDate:'2020-01-01',status:'paid',paidAmount:100,refundAmount:0};await server.recordStatement(owner,'store_order','order',order,'s').run();
const unpack=async r=>({status:r.status,body:await r.json()});
const post=(data,headers=h)=>route.POST(new Request('https://agency.test/api/growth/consumer',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,expectedVersion:0,requestId:randomUUID(),...data})})).then(unpack);
const get=(headers=h)=>route.GET(new Request('https://agency.test/api/growth/consumer?campaignId=c',{headers})).then(unpack);
check((await get({})).status===401,'anonymous');check((await get({'oai-authenticated-user-id':'foreign'})).status===404,'owner');check((await post({action:'create_customer'},{...h,origin:'https://evil.test'})).status===403,'CSRF');
const create={action:'create_customer',requestId:randomUUID()};let r=await post(create);check(r.status===200,'create '+JSON.stringify(r));const customerId=r.body.customers[0].id;check(/^[0-9a-f-]{36}$/.test(customerId),'random pseudonym');check((await post(create)).body.duplicate,'create replay');check((await post({...create,email:'person@example.com'})).status===400,'no identity fields');
check(r.body.resultCustomerId===customerId&&(await post(create)).body.resultCustomerId===customerId,'exact create and replay target');
breakBatch=true;check((await post({action:'create_customer'})).status===500,'batch failure surfaced');breakBatch=false;check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_customer'").get().n===1,'failed create rolled back');
check((await post({...create,campaignId:'same'})).status===409,'same request cannot change campaign');
let version=1;const consent=(purpose,state='granted',patch={})=>post({action:'set_consent',customerId,expectedVersion:version,purpose,state,noticeVersion:'notice-v1',evidenceRef:'consent-log',observedAt:'2026-01-01T00:00:00Z',expiresAt:'2099-01-01T00:00:00Z',...patch});
check((await post({action:'link_order',customerId,expectedVersion:version,orderId:'order',orderVersion:1,evidenceRef:'order-proof'})).status===409,'identity consent needed');
for(const purpose of ['identity_link','post_purchase','marketing_reorder']){r=await consent(purpose);check(r.status===200,'grant '+purpose+' '+JSON.stringify(r));version++}
breakBatch=true;check((await consent('post_purchase','revoked')).status===500,'withdraw rollback failure');breakBatch=false;check((await get()).body.customers[0].version===version,'withdraw rollback keeps projection');
check((await post({action:'link_order',customerId,expectedVersion:version,orderId:'order',orderVersion:1,evidenceRef:'api_key=synthetic-secret'})).status===400,'link secret blocked');
const link={action:'link_order',customerId,expectedVersion:version,orderId:'order',orderVersion:1,evidenceRef:'order-proof',requestId:randomUUID()};r=await post(link);check(r.status===200,'link '+JSON.stringify(r));version++;check(r.body.customers[0].assessment.reorderEligible,'candidate');check((await post(link)).body.duplicate,'link idempotent');check(!r.body.maySend&&!r.body.mayExecute,'no send');
check((await post({...link,requestId:randomUUID()})).status===409,'CAS');check((await consent('marketing_reorder','revoked',{campaignVersion:2})).status===409,'campaign CAS');
await server.recordStatement(owner,'store_order','order',{...order,version:2,refundAmount:1},'s').run();check(!(await get()).body.customers[0].assessment.reorderEligible,'current order refund stale');
check((await post({...link,requestId:randomUUID(),expectedVersion:version})).status===409,'old order version');
r=await post({...link,requestId:randomUUID(),expectedVersion:version,orderVersion:2});check(r.status===200,'reconfirm');version++;check(!r.body.customers[0].assessment.reorderEligible,'refund holds after reconfirm');
const other=await post({action:'create_customer'}),otherId=other.body.customers.find(x=>x.id!==customerId).id;check((await post({...link,requestId:randomUUID(),customerId:otherId,expectedVersion:1,orderVersion:2})).status===409,'no reassignment without consent');
check((await post({action:'set_consent',customerId:otherId,expectedVersion:1,purpose:'identity_link',state:'granted',noticeVersion:'n-v1',evidenceRef:'consent-log',observedAt:'2026-01-01T00:00:00Z',expiresAt:'2099-01-01T00:00:00Z',campaignId:'same'})).status===200,'samebrand campaigns share customer');
check((await post({...link,requestId:randomUUID(),customerId:otherId,expectedVersion:2,orderVersion:2})).status===409,'cannot reassign even with consent');
const oldRevoke={action:'set_consent',customerId:otherId,expectedVersion:2,purpose:'post_purchase',state:'revoked',requestId:randomUUID()};
check((await post(oldRevoke)).status===200,'replay fixture revoke');
// Advance only the persisted fixture's withdrawal boundary; no timing/retry dependency.
const replayFixture=await server.readRecord(owner,'growth_customer',otherId),earlier=new Date(Date.now()-1000).toISOString();
await server.recordStatement(owner,'growth_customer',otherId,{...replayFixture,consents:{...replayFixture.consents,post_purchase:{...replayFixture.consents.post_purchase,observedAt:earlier,withdrawnAt:earlier}}},'b').run();
check((await post({action:'set_consent',customerId:otherId,expectedVersion:3,purpose:'post_purchase',state:'granted',noticeVersion:'n-v2',evidenceRef:'fresh-consent',observedAt:new Date().toISOString(),expiresAt:'2099-01-01T00:00:00Z'})).status===200,'replay fixture fresh grant');
const replayAfterGrant=await post(oldRevoke);check(!replayAfterGrant.body.withdrawn&&replayAfterGrant.body.customers.find(x=>x.id===otherId).consents.post_purchase.state==='granted','old withdrawal replay reports current grant without revoking it');
r=await consent('marketing_reorder','revoked');check(r.status===200,'withdraw');version++;check((await consent('marketing_reorder')).status===409,'old grant cannot resurrect');
await server.recordStatement(owner,'campaign','c',{...c,status:'archived'}).run();check((await post({action:'create_customer'})).status===409,'archive create');r=await consent('identity_link','revoked');check(r.status===200,'archive withdraw');version++;
const withdrawn=(await get()).body.customers.find(x=>x.id===customerId);check(withdrawn.links.length===0&&withdrawn.assessment.latestPurchaseAt===null,'identity withdrawal suppresses purchase use');
const eraseRequest={action:'erase_customer',customerId,expectedVersion:version,requestId:randomUUID()};r=await post(eraseRequest);check(r.status===200,'archive erase '+JSON.stringify(r));check((await get()).body.customers.every(x=>x.id!==customerId),'erased hidden');check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='store_order'").get().n===1,'original order retained');
check(r.body.version===version+1&&(await post(eraseRequest)).body.version===version+1,'erase replay ack version');
for(const kind of ['growth_consumer_consent','growth_consumer_order_link','growth_consumer_order_history'])check(sql.prepare('SELECT COUNT(*) n FROM records WHERE kind=? AND json_extract(data,\'$.customerId\')=?').get(kind,customerId).n===0,'erase '+kind);
await server.recordStatement(owner,'campaign','c',c).run();r=await post(create);check(r.body.duplicate&&r.body.erased&&(await get()).body.customers.every(x=>x.id!==customerId),'create replay cannot reactivate erased');
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_consumer_request' AND json_extract(data,'$.customerId')=? AND json_extract(data,'$.digest') IS NOT NULL").get(customerId).n===0,'erase removes request payload digests');
const lock=await server.acquireLock(owner);check((await post({action:'create_customer'})).status===409,'owner lock');await server.releaseLock(owner,lock);
for(let i=0;i<501;i++)await server.recordStatement(owner,'store_order','extra'+i,{...order,id:'extra'+i},'s').run();
r=await get();check(r.status===200&&r.body.orderAvailability==='unavailable'&&r.body.customers.length===1,'order cap preserves withdrawal UI');check(r.body.customers.every(x=>!x.assessment.reorderEligible),'unavailable orderholds');
await server.recordStatement(owner,'campaign','c',{...c,storeId:'missing'}).run();r=await get();check(r.status===200&&r.body.orderAvailability==='unavailable','missing store preserves customer consent');await server.recordStatement(owner,'campaign','c',c).run();
for(let i=0;i<501;i++)await server.recordStatement(owner,'growth_customer','cap'+i,{id:'cap'+i,brandId:'b',state:'erased',version:1},'b').run();
check((await post({action:'create_customer'})).status===409,'customer cap');
check((await post({action:'set_consent',customerId:otherId,expectedVersion:4,purpose:'identity_link',state:'revoked'})).status===200,'overcapacity cannot block withdrawal');
check((await post({action:'erase_customer',customerId:otherId,expectedVersion:5})).status===200,'overcapacity cannot block erasure');
const token=createHash('sha256').update('consumer-member').digest('hex');env.AUTH_MODE='email';env.AUTH_ORIGIN='https://agency.test';sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run('member','member@test.invalid',owner,'member','active',1);sql.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?)').run(createHash('sha256').update(token).digest('hex'),'member',Date.now()+60000,Date.now());
const member={cookie:'__Host-collective_session='+token,origin:'https://agency.test'};check((await get(member)).status===403,'member cannot read pseudonyms');check((await post({action:'create_customer'},member)).status===403,'member cannot mutate');
console.log(JSON.stringify({passed,external:'not_called'}));
