import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
const {load,sql,env}=testRuntime(async()=>{throw Error('Journey records cannot dispatch')});
const server=await load('lib/server.ts'),route=await load('app/api/growth/journey/route.ts'),growth=await load('app/api/growth/route.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='journey-owner',c={id:'c',brandId:'b',version:1,status:'active',storeId:'fixture-store'},h={'oai-authenticated-user-id':owner,origin:'https://agency.test'};
await server.recordStatement(owner,'campaign','c',c).run();
await server.recordStatement(owner,'store','fixture-store',{id:'fixture-store',brandId:'b'}).run();
await server.recordStatement(owner,'growth_inventory_item','fixture-stock',{id:'fixture-stock',brandId:'b',storeId:'fixture-store',version:0,input:{sku:'SYNTHETIC',locationId:'fixture-store',unit:'piece',onHand:20}},'fixture-store').run();await server.recordStatement(owner,'campaign','other',{...c,id:'other',brandId:'elsewhere'}).run();
const unpack=async r=>({status:r.status,body:await r.json()});
const post=(data,headers=h)=>route.POST(new Request('https://agency.test/api/growth/journey',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,expectedVersion:0,...data})})).then(unpack);
const get=(headers=h)=>route.GET(new Request('https://agency.test/api/growth/journey?campaignId=c',{headers})).then(unpack);
const gp=data=>growth.POST(new Request('https://agency.test/api/growth',{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,expectedVersion:0,...data})})).then(unpack);
check((await get({})).status===401,'anonymous refused');check((await get({'oai-authenticated-user-id':'foreign'})).status===404,'owner isolation');check((await post({action:'save_blocker'},{...h,origin:'https://evil.test'})).status===403,'CSRF');
const signal={title:'간편 구매',sourceUrl:'https://example.com/research',observedAt:new Date(Date.now()-1000).toISOString(),expiresAt:'2099-01-01',sourceType:'market',summary:'선물 준비 문의',sampleSize:null};
const need={title:'선물 상황',situation:'공연 방문',desiredOutcome:'간편 선물',alternative:'개별 선택',barrier:'선택 어려움',counterEvidence:'묶음이 불필요한 고객',signalIds:['signal'],deadline:'2099-01-01',nextAction:'오퍼 비교',assignee:'기획 담당'};
const catalog={sku:'SYNTHETIC',title:'합성 상품',price:10000,unitCost:3000,variableCost:1000,stock:10,stockUnit:'piece',currency:'KRW',taxBasis:'included',fulfillment:'영업일 발송',refunds:'미개봉 반품',rightsConfirmed:true,factIds:['f'],validUntil:'2099-01-01'};
await server.recordStatement(owner,'brand_fact','f',{id:'f',brandId:'b',key:'product',value:'합성 상품',source:'운영자 확인',status:'confirmed',version:1,verifiedAt:'2026-01-01',validUntil:'2099-01-01'},'b').run();
const offer={title:'선물 오퍼',catalogId:'catalog',catalogVersion:1,needId:'need',price:10000,quantity:1,landingUrl:'https://example.com/product',purchaseReason:'간편 준비',priceApproved:true},mission={title:'판매 계획',offerId:'offer',offerVersion:1,assignee:'판매 담당',deadline:'2099-01-01',nextAction:'판매면 검토',channel:'manual',budget:10000,lossLimit:1000,stopRule:'품절 시 중지',fulfillmentOwner:'운영 담당'};
for(const [entity,input] of [['signal',signal],['need',need],['catalog',catalog],['offer',offer],['mission',mission]])check((await gp({action:'save_'+entity,id:entity,input})).status===200,'seed '+entity);
const domain=await load('lib/growth-journey.ts');
const observation={...domain.emptyJourneyObservation(),windowStart:'2020-01-01',windowEnd:'2020-01-01',observedAt:'2020-01-05',delayHours:0,tracking:'reliable',sourceUrls:['https://example.com/report'],evidence:'합성 집계',denominator:100,conversions:10,paidOrders:10,refundedOrders:0,contributionProfit:-1000};
const input={...domain.emptyJourneyInput(),segment:'전체 방문',denominatorDefinition:'다음 단계 도달 방문자 수 / 중복 제거 방문자 수',factEvidence:'옵션 운영 설명',appliedAt:'2020-01-02',before:observation,after:{...observation,windowStart:'2020-01-02',windowEnd:'2020-01-02',conversions:20,contributionProfit:0},title:'결제 장벽',offerId:'offer',offerVersion:1,missionId:'mission',missionVersion:1,hypothesis:'옵션 안내 부족',alternativeExplanation:'유입 구성 변화',action:'옵션 설명 보완',assignee:'상품 담당',dueAt:'2099-01-01'},save={action:'save_blocker',id:'blocker',input};
let r=await post(save);check(r.status===200,'save '+JSON.stringify(r));check(r.body.blockers[0].assessment.missing.length===0,'complete local observation ready');check(r.body.blockers[0].assessment.comparison.conversionDeltaPp===10,'server exposes observational percentage-point delta');check(r.body.blockers[0].assessment.causalStatus==='not_measured','no causal promotion');check(r.body.mayExecute===false&&r.body.blockers[0].assessment.mayExecute===false,'ready never dispatches');check((await post(save)).body.duplicate,'retry idempotent');check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_journey_history'").get().n===1,'retry no extra history');
check((await post({...save,input:{...input,title:'동시 변경'}})).status===409,'stale sequence rejected');check((await post({...save,campaignVersion:2})).status===409,'stale campaign rejected');check((await post({...save,campaignId:'other',expectedVersion:1})).status===404,'cross campaign sequence refused');
check((await post({...save,id:'wrong-offer',input:{...input,offerId:'missing'}})).status===404,'missing offer refused');check((await post({...save,id:'old-offer',input:{...input,offerVersion:2}})).status===409,'offer version required');
await gp({action:'save_offer',id:'offer',expectedVersion:1,input:{...offer,title:'수정된 오퍼'}});r=await get();check(r.body.blockers[0].assessment.missing.some(x=>x.includes('오퍼 변경')),'changed reference holds assessment');check(r.body.blockers[0].assessment.comparison.status==='held'&&r.body.blockers[0].assessment.comparison.conversionDeltaPp===null,'stale chain hides deltas');
check((await post({...save})).body.duplicate,'identical retry returns persisted record without claiming freshness');
r=await post({...save,expectedVersion:1,input:{...input,title:'새 제목'}});check(r.status===409,'stale offer prevents edit');
await gp({action:'save_mission',id:'mission',expectedVersion:1,input:{...mission,offerVersion:2}});
const updated={...input,offerVersion:2,missionVersion:2,title:'관측 후 수정'};r=await post({...save,expectedVersion:1,input:updated});check(r.status===200&&r.body.blockers[0].version===2,'explicit relink and revision');
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_journey_history'").get().n===2,'append-only revisions');
const currentMission=await server.readRecord(owner,'growth_mission','mission');await server.recordStatement(owner,'growth_mission','mission',{...currentMission,status:'unknown'},'c').run();r=await get();check(r.body.blockers[0].assessment.comparison.status==='held','unknown mission holds comparison');await server.recordStatement(owner,'growth_mission','mission',currentMission,'c').run();
check((await server.campaignDeletionPreview(owner,'c')).deletable,'local planning does not block campaign deletion');
check((await post({...save,id:'secret',input:{...input,hypothesis:'person@example.com'}})).status===400,'PII refused');
check((await post({...save,id:'unsupported',action:'publish'})).status===400,'no external action surface');
await gp({action:'save_offer',id:'different-offer',input:offer});
check((await post({...save,id:'mismatch',input:{...updated,offerId:'different-offer',offerVersion:1}})).status===409,'mission cannot reference a different offer');
const draft=domain.emptyJourneyInput();
await server.recordStatement(owner,'campaign','capped',{...c,id:'capped'}).run();
for(let i=0;i<500;i++)await server.recordStatement(owner,'growth_journey','cap-'+i,{id:'cap-'+i,brandId:'b',campaignId:'capped',campaignVersion:1,version:1,input:draft},'capped').run();
check((await post({action:'save_blocker',id:'cap-over',campaignId:'capped',input:draft})).status===409,'501st draft refused before write');
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_journey' AND parent_id='capped'").get().n===500,'capacity no partial write');
const full=await route.GET(new Request('https://agency.test/api/growth/journey?campaignId=capped',{headers:h}));check(full.status===200,'full capacity remains readable');
check((await post({...save,id:'bad id'})).status===400,'malformed record id refused');
const heldLock=await server.acquireLock(owner);
check((await post({...save,id:'locked',input:draft})).status===409,'concurrent mutation lock refused');
await server.releaseLock(owner,heldLock);
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_journey' AND json_extract(data,'$.id')='locked'").get().n===0,'lock contention writes nothing');
await server.recordStatement(owner,'growth_journey','cross-brand',{id:'cross-brand',brandId:'foreign',campaignId:'c',version:1,input:draft},'other').run();
check((await post({...save,id:'cross-brand',expectedVersion:1,input:draft})).status===404,'stored row brand isolation on mutation');
await server.recordStatement(owner,'growth_journey','overflow',{id:'overflow',brandId:'b',campaignId:'capped',version:1,input:draft},'capped').run();
check((await route.GET(new Request('https://agency.test/api/growth/journey?campaignId=capped',{headers:h}))).status===409,'legacy overflow read fails closed');
const token=createHash('sha256').update('journey-member').digest('hex');env.AUTH_MODE='email';env.AUTH_ORIGIN='https://agency.test';sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run('member','member@test.invalid',owner,'member','active',1);sql.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?)').run(createHash('sha256').update(token).digest('hex'),'member',Date.now()+60000,Date.now());
const member={cookie:'__Host-collective_session='+token,origin:'https://agency.test'};check((await get(member)).body.canEdit===false,'member read-only');check((await post({...save,id:'member'},member)).status===403,'member write refused');env.AUTH_MODE='legacy';
await server.recordStatement(owner,'campaign','c',{...c,status:'archived'}).run();check((await post({...save,expectedVersion:2})).status===409,'archived write refused');check(!(await get()).body.canEdit,'archived view disabled');
console.log(JSON.stringify({passed,external:'not_called'}));
