// Real SQLite; no model/provider calls. Failure drafts must never replace reviewed candidates.
import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
const {load,sql}=testRuntime(async()=>{throw Error('external forbidden')});
const server=await load('lib/server.ts'),helper=await load('lib/growth-failure-drafts-server.ts');
const who={owner:'owner',id:'daily',email:null,role:'owner'},c={id:'c',brandId:'b',storeId:'s',version:1,status:'active'};
const put=(kind,id,value,parent='c')=>server.recordStatement(who.owner,kind,id,value,parent).run();
const read=()=>sql.prepare("SELECT data FROM records WHERE kind='growth_optimization'").all().map(x=>JSON.parse(x.data));
let passed=0;const check=(x,label)=>{assert.ok(x,label);passed++};
await put('campaign','c',c);
const result=(id,designId,analysisNumber,status)=>({id,brandId:'b',campaignId:'c',designId,analysisNumber,analysis:{status,reasons:['failure text must not be copied']}});
await put('growth_experiment_result','old',result('old','e',1,'rejected'));
await put('growth_experiment_result','new',result('new','e',2,'supported'));
await put('growth_experiment_result','failed',result('failed','f',1,'rejected'));
await put('growth_experiment_result','foreign',{...result('foreign','x',1,'rejected'),brandId:'other'});
await put('growth_lesson_application','lesson',{id:'lesson',brandId:'b',campaignId:'c',version:2,outcome:{result:'failure'}});
await put('growth_lesson_application','ok',{id:'ok',brandId:'b',campaignId:'c',version:1,outcome:{result:'success'}});
let r=await helper.createGrowthFailureDrafts(who,c);
check(r.created===2,'only current scoped failures');
check(read().every(x=>x.stage==='draft'&&!x.frozen&&!x.offline&&!x.sales&&!x.adoption),'review only');
check(read().every(x=>x.input.tokenBudget===0&&x.input.krwBudget===0),'no inferred spend permission');
check(read().every(x=>x.autoDraft.sourceDigest.length===64),'source provenance');
check(!JSON.stringify(read()).includes('failure text must not be copied'),'untrusted source prose not copied');
check((await helper.createGrowthFailureDrafts(who,c)).created===0,'daily replay creates no duplicate');
const first=read()[0];await put('growth_optimization',first.id,{...first,version:2,input:{...first.input,proposal:'사람이 수정한 가설'}});
await helper.createGrowthFailureDrafts(who,c);check(read().find(x=>x.id===first.id).input.proposal==='사람이 수정한 가설','operator edit preserved');
await put('growth_experiment_result','failed-next',result('failed-next','f',2,'invalid'));
check((await helper.createGrowthFailureDrafts(who,c)).created===1,'new analysis creates distinct reviewed evidence candidate');
await put('growth_experiment_result','stop',result('stop','stop',1,'rejected'));
await put('growth_stop','global',{id:'global',status:'stopped',version:1,reason:'test',updatedAt:new Date().toISOString(),updatedBy:'owner'},'');
check((await helper.createGrowthFailureDrafts(who,c)).created===0,'stop blocks drafts');
await put('growth_stop','global',{id:'global',status:'running',version:2,reason:'test',updatedAt:new Date().toISOString(),updatedBy:'owner'},'');
await assert.rejects(()=>helper.createGrowthFailureDrafts({...who,role:'member'},c));passed++;
await assert.rejects(()=>helper.createGrowthFailureDrafts(who,{...c,version:2}));passed++;
sql.exec("CREATE TRIGGER fail_failure_history BEFORE INSERT ON records WHEN NEW.kind='growth_optimization_history' BEGIN SELECT RAISE(ABORT,'atomic test'); END;");
const before=read().length;await assert.rejects(()=>helper.createGrowthFailureDrafts(who,c));passed++;
check(read().length===before,'history failure rolls back candidate');
sql.exec('DROP TRIGGER fail_failure_history');
check((await helper.createGrowthFailureDrafts(who,c)).created===1,'failed write safely retried');
const optimizer=await load('lib/growth-optimization-server.ts');
const retired=(await optimizer.growthOptimizationView(who,c)).candidates.find(x=>x.input.failureId==='failed');
check(retired.failureStatus==='changed','superseded analysis cannot remain current');
console.log(JSON.stringify({passed}));
