import assert from 'node:assert/strict';import {testRuntime} from './helpers/runtime.mjs';const {load}=testRuntime(async()=>{throw Error('external forbidden')});const {buildOperationReview}=await load('lib/growth-operation-review.ts');let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const now=Date.parse('2026-09-30T12:00:00Z');
const order={id:'order',storeId:'store',campaignId:'c',version:2,status:'paid',paidAmount:1000,refundAmount:0};
const line={id:'line',brandId:'b',storeId:'store',campaignId:'c',input:{orderId:'order',orderVersion:2,inventoryId:'stock',units:2,missionId:'mission'},allocation:{status:'current',reasons:[]}};
const stock={id:'stock',brandId:'b',storeId:'store',input:{unit:'piece'},projection:{onHand:10,shortage:0,orders:[{orderId:'line',missionId:'mission',quantity:2,held:2,shipped:0,released:0,refunded:0,returned:0}]}};
const view={campaignId:'c',brandId:'b',storeId:'store',orders:[order],orderLines:[line],inventory:[stock]};
const run=patch=>buildOperationReview({...view,...patch},now);
let r=run();check(r.items.length===1&&r.items[0].heldUnits===2,'exact line allocation held');check(r.items[0].codes.includes('unshipped_hold'),'held not shipment delay');check(!r.items.some(x=>x.codes.includes('stock_allocation_missing')),'join allocation by line ID');
check(run({inventory:[{...stock,projection:{...stock.projection,orders:[{...stock.projection.orders[0],orderId:'order'}]}}]}).items.some(x=>x.codes.includes('stock_allocation_missing')),'store order ID cannot substitute line ID');
check(run({orders:[{...order,version:3}]}).items[0].codes.includes('order_changed'),'order version changed');
for(const patch of [{status:'cancelled'},{status:'refunded',refundAmount:1000},{refundAmount:200}])check(run({orders:[{...order,...patch}]}).items[0].codes.includes('cancelled_refunded_hold'),'cancel and refunds held review');
check(run({orderLines:[]}).items[0].codes.includes('campaign_line_missing'),'own campaign order with no current line');
check(run({orders:[{...order,campaignId:'other'}],orderLines:[]}).items.length===0,'unrelated campaign order excluded');check(run({orders:[{...order,campaignId:'other'}]}).items.length===1,'current campaign line keeps eligible order');
check(run({orderLines:[{...line,storeId:'other'}],orders:[]}).items.length===0,'foreign store line excluded');
const zero={...stock,projection:{...stock.projection,orders:[{...stock.projection.orders[0],held:0,shipped:2}]}};check(run({inventory:[zero]}).items.length===0,'fully shipped zero held normal');
const unknown={...stock,projection:{...stock.projection,onHand:null,shortage:null}};check(run({inventory:[unknown]}).items.some(x=>x.codes.includes('inventory_unknown')),'unknown shared stock remains explicit');
check(run({inventory:[{...stock,projection:{...stock.projection,shortage:3}}]}).items.some(x=>x.codes.includes('inventory_shortage')),'shared shortage review');
const before=JSON.stringify(view);run();check(JSON.stringify(view)===before,'readonly input');
check(run({orderLines:[line,line],inventory:[stock,stock]}).items.length===1,'duplicate records one line row');
check(run({inventory:[]}).items[0].heldUnits===null,'unknown allocation never zero');assert.throws(()=>buildOperationReview(view,NaN));passed++;
check(r.mayExecute===false,'no execution permission');
const split=run({orderLines:[line,{...line,id:'line2'}],inventory:[{...unknown,projection:{...unknown.projection,orders:[...unknown.projection.orders,{...unknown.projection.orders[0],orderId:'line2'}]}}]});check(split.items.filter(x=>x.key==='inventory:stock').length===1,'shared inventory issue emitted once across lines');
const allocationReview=run({orderLines:[{...line,allocation:{status:'current',reasons:['일부 품목 금액 배분 미확인']}}]});check(allocationReview.items.find(x=>x.lineId==='line').codes.includes('allocation_review'),'current allocation still may contain unknown amounts');
check(run({orders:[]}).items.find(x=>x.lineId==='line').codes.includes('allocation_review'),'missing original order requires reconcile not new order');
const changed=run({orders:[{...order,version:3,refundAmount:200}]});check(changed.items.filter(x=>x.lineId==='line').length===1&&changed.items[0].codes.includes('cancelled_refunded_hold')&&changed.items[0].heldUnits===2,'multiple reasons merged without converting refund amount to units');
check(run({inventory:[{...zero,projection:{...zero.projection,onHand:0,shortage:0,available:0}}]}).items.length===0,'zero onHand or available is not shortage');
const quantityMissing=run({inventory:[{...stock,projection:{...stock.projection,orders:[{...stock.projection.orders[0],quantity:undefined}]}}]});check(quantityMissing.items.find(x=>x.lineId==='line').heldUnits===null,'unknown allocation quantity cannot establish exact allocation');
const mismatch=run({inventory:[{...stock,projection:{...stock.projection,orders:[{...stock.projection.orders[0],missionId:'foreign'}]}}]});check(mismatch.items.find(x=>x.lineId==='line').heldUnits===null,'foreign mission allocation not current line evidence');
const unitsUnknown=run({inventory:[{...stock,input:{unit:'unknown'}}]});check(unitsUnknown.items.find(x=>x.lineId==='line').unit===null,'unknown unit never defaults');
const reversed=run({orderLines:[...view.orderLines].reverse(),orders:[...view.orders].reverse(),inventory:[...view.inventory].reverse()});assert.deepEqual(reversed,r);passed++;
check(run({storeId:null}).items.length===0,'no store no invented scope');

const direct=run({inventory:[{...stock,projection:{...stock.projection,orders:[{...stock.projection.orders[0],missionId:'',reservationId:''}]}}]});check(!direct.items.find(x=>x.lineId==='line').codes.includes('stock_allocation_missing')&&direct.items.find(x=>x.lineId==='line').heldUnits===2,'normal direct allocation has empty mission and reservation IDs');
const malformedDirect=run({inventory:[{...stock,projection:{...stock.projection,orders:[{...stock.projection.orders[0],missionId:'',reservationId:'foreign'}]}}]});check(malformedDirect.items.find(x=>x.lineId==='line').heldUnits===null,'empty mission cannot use unrelated reservation');
console.log(JSON.stringify({passed,external:0}));
