import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
const {load}=testRuntime();const {parseSettlementEvidence:parse,projectSettlements:project}=await load('lib/growth-settlement.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};const rejects=(fn,n)=>{assert.throws(fn,undefined,n);passed++};
const now='2026-09-30T10:00:00Z',order={id:'order',version:1,paidAmount:10000,refundAmount:0};
const receipt={eventId:'expected',revision:1,kind:'expected',orderId:'order',orderVersion:1,accountRef:'seller',settlementRef:'batch',receiptRef:'payment',currency:'KRW',amount:10000,feeAmount:null,taxBasis:'unknown',occurredAt:'2026-09-30T09:00:00Z',evidenceRef:'statement',origin:'operator_attested'};
const a={...receipt,eventId:'cash-a',kind:'received',receiptRef:'payment-a',amount:4000,feeAmount:100},b={...a,eventId:'cash-b',receiptRef:'payment-b',amount:6000,feeAmount:200};
let p=project([order],[receipt,a,b],now);check(p.ledgerNetRevenue===10000&&p.expectedAmount.total===10000&&p.receivedCash.total===10000,'expected and cash distinct from revenue');
check(p.reportedFees.knownAmount===300&&p.reportedFees.complete&&p.expectedFees.total===null,'expected fees do not contaminate received fees');
check(project([order],[{...receipt,feeAmount:300},a,b],now).reportedFees.total===300,'expected and received fees never double counted');
check(p.reconciliation==='not_verified','operator attestation never bank verification');
check(project([order],[a,a],now).receivedCash.total===4000,'duplicate same revision ignored');
rejects(()=>project([order],[a,{...a,amount:4500}],now),'conflicting revision denied');
check(project([order],[{...a,revision:2,amount:4500},a],now).receivedCash.total===4500,'late lower revision cannot overwrite correction');
for(const change of [{orderId:'other'},{accountRef:'another'},{kind:'expected'},{receiptRef:'different'}])rejects(()=>project([order],[a,{...a,...change,revision:2}],now),'immutable references');
check(project([order],[{...a,amount:null}],now).receivedCash.total===null,'unknown cash not zero');
check(project([order],[{...a,amount:0}],now).receivedCash.total===0,'explicit zero allowed');
p=project([{...order,version:2,refundAmount:1000}],[a],now);check(p.ledgerNetRevenue===9000&&p.receivedCash.total===4000&&p.reconciliation==='stale','refund revision preserves cash but invalidates reconciliation');
check(project([], [a],now).reconciliation==='stale','orphan evidence stale');
rejects(()=>project([order],[a,{...a,eventId:'duplicate-other-id'}],now),'receipt reference cannot be duplicated');
for(const change of [{amount:-1},{amount:1.5},{amount:Number.MAX_SAFE_INTEGER+1},{currency:'USD'},{occurredAt:'2026-02-30T00:00:00Z'},{accountRef:'010-1234-5678'},{evidenceRef:'https://example.com/private'},{origin:'bank_verified'}])rejects(()=>parse({...a,...change},now),'invalid evidence');
rejects(()=>parse({...a,occurredAt:'2026-10-01T00:00:00Z'},now),'future cash denied');
check(parse({...receipt,occurredAt:'2026-10-01T00:00:00Z'},now).kind==='expected','future expected allowed');
check(project([order],[],now).receivedCash.total===null,'absence of evidence is not cash zero');
console.log(JSON.stringify({passed}));
