import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
let failHistory=false;
const {load,sql}=testRuntime(async()=>{throw Error('external forbidden')},{beforeRun(s){if(failHistory&&s.query.startsWith('INSERT INTO records')&&s.values[2]==='growth_history')throw Error('atomic failure')}});
const server=await load('lib/server.ts'),detection=await load('lib/growth-detection-server.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='draft-owner',who={owner,id:owner,email:null,role:'owner'},now=Date.parse('2026-10-20T00:00:00Z');
const put=(kind,id,row,parent='')=>server.recordStatement(owner,kind,id,row,parent).run();
const c={id:'c',brandId:'b',storeId:'s',version:1,status:'active',title:'캠페인'};
await put('store','s',{id:'s',brandId:'b'},'b');
for(const id of ['c','c2']){await put('campaign',id,{...c,id});await detection.runGrowthDetection(who,{...c,id},'daily_loop',now)}
const raw=(kind,parent)=>sql.prepare('SELECT data FROM records WHERE owner=? AND kind=? AND parent_id=?').all(owner,kind,parent).map(r=>JSON.parse(r.data));
check(raw('growth_detected_signal','c').length>0&&raw('growth_detected_signal','c2').length===raw('growth_detected_signal','c').length,'same seasonal key is independently detected for both campaigns');
const drafts=await load('lib/growth-opportunity-drafts-server.ts');
const result=await drafts.createGrowthOpportunityDrafts(who,c,now);
check(result.created>0,'daily signal creates review draft');
let needs=raw('growth_need','c');const first=needs[0];
check(first.input.signalIds.length===0&&first.input.assignee&&first.input.deadline&&first.input.nextAction,'draft has assignee/deadline but does not fabricate confirmed market source');
check(first.autoDraft.sourceId&&first.autoDraft.sourceDigest&&first.autoDraft.sourceVersion===1,'draft preserves exact detection provenance');
check(raw('growth_history','c').length===needs.length,'draft current and initial history are written together');
check((await drafts.createGrowthOpportunityDrafts(who,c,now)).created===0,'repeat run never duplicates drafts');
const workspace=await load('lib/growth-workspace-server.ts');
await workspace.saveGrowth(who,c,{action:'save_need',id:first.id,campaignVersion:1,expectedVersion:1,input:{...first.input,title:'운영자 수정 유지'}});
await drafts.createGrowthOpportunityDrafts(who,c,now);
check(raw('growth_need','c').find(n=>n.id===first.id).input.title==='운영자 수정 유지','daily rerun preserves operator changes');
check(raw('growth_need','c').find(n=>n.id===first.id).autoDraft.sourceDigest===first.autoDraft.sourceDigest,'operator revisions preserve original detection provenance');
const sig=raw('growth_detected_signal','c')[0];
await put('growth_detected_signal','dismissed',{...sig,id:'dismissed',status:'dismissed',detection:{...sig.detection,key:'dismissed'}},'c');
await put('growth_detected_signal','foreign',{...sig,id:'foreign',brandId:'other',detection:{...sig.detection,key:'foreign'}},'c');
await put('growth_detected_signal','unsafe',{...sig,id:'unsafe',detection:{...sig.detection,key:'unsafe',detail:'Bearer secret-token-forbidden'}},'c');
await put('growth_detected_signal','quoted',{...sig,id:'quoted',detection:{...sig.detection,key:'quoted',detail:'{"api_key":"credential-example"}'}},'c');
check((await drafts.createGrowthOpportunityDrafts(who,c,now)).created===0,'dismissed, foreign and unsafe signals do not create drafts');
failHistory=true;await assert.rejects(()=>drafts.createGrowthOpportunityDrafts(who,{...c,id:'c2'},now),/atomic failure/);passed++;failHistory=false;
check(raw('growth_need','c2').length===0&&raw('growth_history','c2').length===0,'history failure rolls back every draft in batch');
const legacy={...sig,id:'legacy',campaignId:'legacy-c',status:'dismissed'};
await put('campaign','legacy-c',{...c,id:'legacy-c'});await put('growth_detected_signal','legacy',legacy,'legacy-c');
await detection.runGrowthDetection(who,{...c,id:'legacy-c'},'daily_loop',now);
check(raw('growth_detected_signal','legacy-c').filter(s=>s.detection.key===legacy.detection.key).length===1,'legacy identifier remains deduplicated and dismissed');
const stop=await load('lib/growth-stop-server.ts');
await stop.changeGrowthStop(who,{action:'stop',expectedVersion:0,requestId:crypto.randomUUID(),reason:'검토 중단'});
check((await drafts.createGrowthOpportunityDrafts(who,{...c,id:'c2'},now)).reason==='stopped','stop prevents new drafts');
check(raw('growth_need','c2').length===0,'stop writes zero drafts');
await assert.rejects(()=>drafts.createGrowthOpportunityDrafts({...who,role:'member'},c,now),e=>e.status===403);passed++;
await assert.rejects(()=>drafts.createGrowthOpportunityDrafts(who,{...c,version:2},now),e=>e.status===409);passed++;
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind IN ('growth_action_intent','growth_commitment','growth_signal','execution_publication')").get().n===0,'draft creation performs no execution/budget/source approval');
console.log(JSON.stringify({passed}));
