// Real SQLite; synthetic identity/consent and signed MAPDAL responses. No live sending.
import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';import {testRuntime} from './helpers/runtime.mjs';
let receiptCost=10;let mode='accepted',sends=0,lookups=0,cancels=0,lastPayload=null,intentBeforeSend=false;let sqlRef;
const {load,sql,env}=testRuntime(async(url,opts)=>{
 const u=new URL(url),b=JSON.parse(opts.body);assert.equal(u.hostname,'mapdal.kr');assert.ok(opts.headers['x-collective-signature']);assert.equal(opts.redirect,'error');
 if(u.pathname.endsWith('/send')){sends++;lastPayload=b.payload;intentBeforeSend=sqlRef.prepare("SELECT count(*) n FROM records WHERE kind='growth_consumer_delivery' AND json_extract(data,'$.status')='unknown'").get().n>0;if(mode==='timeout')throw Error('synthetic timeout');}
 if(u.pathname.endsWith('/receipt'))lookups++;if(u.pathname.endsWith('/cancel'))cancels++;
 if(mode==='notfound')return Response.json(null);
 const payload=lastPayload;return Response.json({requestId:payload.requestId,payloadDigest:b.payloadDigest,status:u.pathname.endsWith('/cancel')?'failed':mode==='delivered'?'delivered':'accepted',costKrw:u.pathname.endsWith('/cancel')?0:receiptCost,receiptId:randomUUID(),at:new Date().toISOString(),code:u.pathname.endsWith('/cancel')?'cancelled':null});
});sqlRef=sql;
const server=await load('lib/server.ts'),route=await load('app/api/growth/consumer-delivery/route.ts'),consumer=await load('app/api/growth/consumer/route.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};const owner='delivery-owner',now=new Date(Date.now()-60000).toISOString(),future=new Date(Date.now()+86400000).toISOString();
const c={id:'campaign',brandId:'brand',storeId:'store',version:1,status:'active'},h={'oai-authenticated-user-id':owner,origin:'https://agency.test'},customerId=randomUUID(),templateId=randomUUID();
const put=(kind,id,data,parent=c.id)=>server.recordStatement(owner,kind,id,data,parent).run();
await put('campaign',c.id,c,'');await put('store','store',{id:'store',brandId:'brand'},'brand');
const consent=purpose=>({purpose,state:'granted',noticeVersion:'notice-v1',evidenceRef:'proof-1',observedAt:now,expiresAt:future});
const customer={id:customerId,brandId:'brand',version:1,state:'active',consents:{identity_link:consent('identity_link'),post_purchase:consent('post_purchase'),marketing_reorder:consent('marketing_reorder')},createdAt:now,updatedAt:now};
await put('growth_customer',customerId,customer,'brand');
await put('store_order','order',{id:'order',storeId:'store',version:1,orderDate:now.slice(0,10),status:'paid',paidAmount:1000,refundAmount:0},'store');
await put('growth_consumer_order_link','link',{id:'link',brandId:'brand',customerId,storeId:'store',orderId:'order',orderVersion:1,version:1,evidenceRef:'link-proof'},'brand');
const authority={id:'grant',brandId:'brand',campaignId:c.id,campaignVersion:1,version:1,input:{id:'grant',brandId:'brand',campaignId:c.id,accountId:'tenant',channel:'consumer_delivery',status:'active',maxTier:'T3',allowedActions:['publish','spend'],ownerApprovalId:'owner-signed',ownerSignedAt:now,startsAt:now,expiresAt:future,periodStart:now,periodEnd:future,totalCap:1000,dayCap:1000,weekCap:1000,lossCap:1000}};
await put('growth_authority','grant',authority);
const unpack=async r=>({status:r.status,body:await r.json()}),post=(body,headers=h)=>route.POST(new Request('https://agency.test/api/growth/consumer-delivery',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({campaignId:c.id,campaignVersion:1,expectedVersion:0,requestId:randomUUID(),...body})})).then(unpack);
const get=(headers=h)=>route.GET(new Request('https://agency.test/api/growth/consumer-delivery?campaignId='+c.id,{headers})).then(unpack);
const data={customerId,customerVersion:1,purpose:'post_purchase',templateId,templateDigest:'a'.repeat(64),maxCostKrw:10,expiresAt:future,waitDays:0,authorityId:'grant',authorityVersion:1};
const config={tenantId:'tenant',providerStoreId:'shop',secret:'synthetic-consumer-delivery-secret-000000',enabled:false};
check((await post({action:'configure',config},{})).status===401,'anonymous configuration denied');
check((await post({action:'configure',config},{...h,origin:'https://evil.test'})).status===403,'CSRF denied');
check((await post({action:'configure',config})).status===200,'encrypted configuration starts disabled');
check(!(await get()).body.connection.enabled,'default disabled credential');
check(!JSON.stringify((await get()).body).includes(config.secret),'secret absent from GET');
const configuredRequest={action:'configure',expectedVersion:1,config,requestId:randomUUID()};
check((await post(configuredRequest)).status===200,'connection revision saved');
check((await post(configuredRequest)).body.duplicate,'connection request replay stable');
check((await post({...configuredRequest,config:{...config,providerStoreId:'other'}})).status===409,'connection replay payload conflict');
check((await post({action:'configure',expectedVersion:2,config:{...config,tenantId:'01012345678'}})).status===400,'connection identifiers reject phone numbers');
const id=randomUUID(),queue={action:'queue',id,input:data,requestId:randomUUID()};
check((await post({...queue,input:{...data,phone:'01012345678'}})).status===400,'raw contact fields rejected');
check((await post(queue)).status===200,'eligible consumer queued');
check((await post(queue)).body.duplicate,'queue replay idempotent');
check((await post({...queue,input:{...data,maxCostKrw:20}})).status===409,'request payload conflict rejected');
check((await post({action:'approve',id,expectedVersion:1,confirm:true})).status===409,'disabled connection blocks approval');
await post({action:'configure',expectedVersion:2,config:{...config,enabled:true}});
check((await post({action:'approve',id,expectedVersion:1,confirm:true})).status===200,'owner approves immutable current payload');
const dispatched={action:'dispatch',id,expectedVersion:2,requestId:randomUUID()};let r=await post(dispatched);
check(r.status===200&&sends===1&&intentBeforeSend,'durable unknown intent exists before one provider send');
check(lastPayload.recipientId===customerId&&!JSON.stringify(lastPayload).includes('phone'),'only linked opaque customer UUID sent');
check((await post(dispatched)).body.duplicate&&sends===1,'dispatch retry never resends');
check((await post({action:'dispatch',id,expectedVersion:4})).status===409&&sends===1,'fresh dispatch key cannot resend accepted intent');
mode='delivered';receiptCost=null;r=await post({action:'reconcile',id,expectedVersion:4});check(r.status===200&&lookups===1,'receipt reconciliation reads without send');
check((await get()).body.deliveries.find(x=>x.id===id).status==='delivered','provider delivery is separately confirmed');
check((await post({action:'configure',expectedVersion:3,config:{...config,providerStoreId:'changed',enabled:true}})).status===409,'terminal unknown cost retains original provider identity');
receiptCost=10;check((await post({action:'reconcile',id,expectedVersion:5})).status===200,'terminal delivery with unknown cost can reconcile final cost');
const paid=JSON.parse(sql.prepare("SELECT data FROM records WHERE kind='growth_commitment' AND json_extract(data,'$.id')=?").get('consumer-delivery-'+id).data);check(paid.commitment.actualAmount===10&&paid.commitment.status==='reconciled','terminal cost closes reserved commitment');
const unknownId=randomUUID();await post({action:'queue',id:unknownId,input:data});await post({action:'approve',id:unknownId,expectedVersion:1,confirm:true});mode='timeout';
check((await post({action:'dispatch',id:unknownId,expectedVersion:2})).status===200,'timeout saved as unknown');
const count=sends;check((await post({action:'dispatch',id:unknownId,expectedVersion:3})).status===409&&sends===count,'unknown cannot resend');
mode='notfound';await post({action:'reconcile',id:unknownId,expectedVersion:3});check((await get()).body.deliveries.find(x=>x.id===unknownId).status==='unknown','missing receipt does not prove failure');
check((await post({action:'configure',expectedVersion:3,config:{...config,enabled:true,providerStoreId:'new-shop'}})).status===409,'unknown receipt prevents provider identity replacement');
check((await post({action:'configure',expectedVersion:3,config:{...config,enabled:true,secret:'replacement-synthetic-signing-secret-000000'}})).status===409,'unknown receipt prevents signing key replacement');
check((await post({action:'configure',expectedVersion:3,config:{...config,enabled:false}})).status===200,'same pending connection can be disabled');
check((await post({action:'configure',expectedVersion:4,config:{...config,enabled:true}})).status===200,'same connection can be reenabled');
const pendingId=randomUUID();await post({action:'queue',id:pendingId,input:data});await post({action:'approve',id:pendingId,expectedVersion:1,confirm:true});
await put('growth_customer',customerId,{...customer,consents:{...customer.consents,post_purchase:{...consent('post_purchase'),state:'revoked'}}},'brand');
check((await post({action:'dispatch',id:pendingId,expectedVersion:2})).status===409&&sends===count,'last-minute purpose withdrawal sends zero');
await put('growth_customer',customerId,customer,'brand');
await put('growth_stop','global',{id:'global',version:1,status:'stopped',reason:'검토',updatedAt:now,updatedBy:owner},'');
check((await post({action:'dispatch',id:pendingId,expectedVersion:2})).status===409&&sends===count,'global stop sends zero');
await put('growth_stop','global',{id:'global',version:2,status:'running',reason:'검토 완료',updatedAt:now,updatedBy:owner},'');
await put('growth_authority','grant',{...authority,version:2});check((await post({action:'dispatch',id:pendingId,expectedVersion:2})).status===409,'authority revision blocks send');await put('growth_authority','grant',authority);
await put('store_order','order',{id:'order',storeId:'store',version:2,orderDate:now.slice(0,10),status:'paid',paidAmount:1000,refundAmount:0},'store');check((await post({action:'dispatch',id:pendingId,expectedVersion:2})).status===409,'order revision blocks send');await put('store_order','order',{id:'order',storeId:'store',version:1,orderDate:now.slice(0,10),status:'paid',paidAmount:1000,refundAmount:0},'store');
await put('growth_stop','global',{id:'global',version:1,status:'corrupt'},'');
check((await post({action:'dispatch',id:pendingId,expectedVersion:2})).status===409,'malformed global stop fails closed');
await put('growth_stop','global',{id:'global',version:2,status:'running',reason:'검토 완료',updatedAt:now,updatedBy:owner},'');
await put('growth_authority','grant',{...authority,input:{...authority.input,totalCap:19}});
check((await post({action:'dispatch',id:pendingId,expectedVersion:2})).status===409&&sends===count,'unknown cost reservation counts against total cap');
await put('growth_authority','grant',{...authority,input:{...authority.input,maxTier:'T2',allowedActions:['publish']}});
const free=randomUUID();await post({action:'queue',id:free,input:{...data,maxCostKrw:0}});
check((await post({action:'approve',id:free,expectedVersion:1,confirm:true})).status===200,'zero-cost T2 publication can be approved');
check((await post({action:'approve',id:pendingId,expectedVersion:2,confirm:true})).status===409,'paid delivery requires T3 spend delegation');
await put('growth_authority','grant',authority);
const cancelId=randomUUID();await post({action:'queue',id:cancelId,input:data});
check((await post({action:'cancel',id:cancelId,expectedVersion:1})).status===200,'queued cancellation is local');
check((await post({action:'approve',id:cancelId,expectedVersion:2,confirm:true})).status===409,'cancelled queue cannot be revived');
check((await post({action:'queue',id:randomUUID(),input:{...data,expiresAt:now}})).status===409,'expired message cannot queue');
// Erasure is atomic with local suppression; ambiguous provider work retains cancellation audit but no recipient payload.
const er=await consumer.POST(new Request('https://agency.test/api/growth/consumer',{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({action:'erase_customer',campaignId:c.id,campaignVersion:1,customerId,expectedVersion:1,requestId:randomUUID()})}));check(er.status===200,'existing consumer erasure accepted');
const erased=(await get()).body.deliveries;check(erased.find(x=>x.id===pendingId).status==='failed','queued work suppressed on erasure');
check(erased.every(x=>x.payload===null&&x.customerId===null&&x.input===null&&x.approval===null),'recipient and linking snapshots scrubbed');
check(!sql.prepare("SELECT data FROM records WHERE kind='growth_consumer_delivery_history'").all().some(x=>x.data.includes(customerId)),'history payload scrubbed while audit retained');
mode='accepted';const unknown=erased.find(x=>x.id===unknownId);r=await post({action:'reconcile',id:unknownId,expectedVersion:unknown.version});check(r.status===200&&cancels===1&&sends===count,'erased unknown intent only cancels/reconciles, never resends');
check((await get({'oai-authenticated-user-id':'other'})).status===404,'owner isolation');
env.AUTH_MODE='email';env.AUTH_ORIGIN='https://agency.test';
sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run('original-owner','owner@test.invalid',owner,'admin','active',0);
for(const role of ['admin','member']){
 const token=(role==='admin'?'a':'b').repeat(64);sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run(role,role+'@test.invalid',owner,role,'active',1);
 sql.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?)').run(createHash('sha256').update(token).digest('hex'),role,Date.now()+60000,Date.now());
 const rh={cookie:'__Host-collective_session='+token,origin:'https://agency.test'};
 const denied=await post({action:'configure',config,expectedVersion:3},rh);assert.equal(denied.status,403,JSON.stringify(denied));passed++;
 check((await post({action:'approve',id:pendingId,expectedVersion:3,confirm:true},rh)).status===403,role+' cannot owner-approve');
 if(role==='member')check((await get(rh)).status===403,'member cannot inspect delivery ledger');
}
env.AUTH_MODE='legacy';
check((await server.campaignDeletionPreview(owner,c.id)).deletable===false,'delivery audit prevents campaign purge');
console.log(JSON.stringify({passed,sqlite:'real',auth:'mocked',provider:'mocked',sends}));
