import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
const {load,sql,env}=testRuntime(async()=>{throw Error('Demand drafts cannot dispatch')});
const server=await load('lib/server.ts'),route=await load('app/api/growth/demand/route.ts'),growth=await load('app/api/growth/route.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='demand-owner',c={id:'c',brandId:'b',version:1,status:'active',storeId:'fixture-store'},h={'oai-authenticated-user-id':owner,origin:'https://agency.test'};
await server.recordStatement(owner,'campaign','c',c).run();
await server.recordStatement(owner,'store','fixture-store',{id:'fixture-store',brandId:'b'}).run();
await server.recordStatement(owner,'growth_inventory_item','fixture-stock',{id:'fixture-stock',brandId:'b',storeId:'fixture-store',version:0,input:{sku:'SYNTHETIC',locationId:'fixture-store',unit:'piece',onHand:20}},'fixture-store').run();await server.recordStatement(owner,'campaign','other',{...c,id:'other',brandId:'elsewhere'}).run();
const unpack=async r=>({status:r.status,body:await r.json()});
const post=(data,headers=h)=>route.POST(new Request('https://agency.test/api/growth/demand',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,expectedVersion:0,...data})})).then(unpack);
const get=(headers=h)=>route.GET(new Request('https://agency.test/api/growth/demand?campaignId=c',{headers})).then(unpack);
const gp=data=>growth.POST(new Request('https://agency.test/api/growth',{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,expectedVersion:0,...data})})).then(unpack);
check((await get({})).status===401,'anonymous refused');check((await get({'oai-authenticated-user-id':'foreign'})).status===404,'owner isolation');check((await post({action:'save_sequence'},{...h,origin:'https://evil.test'})).status===403,'CSRF');
const signal={title:'간편 구매',sourceUrl:'https://example.com/research',observedAt:new Date(Date.now()-1000).toISOString(),expiresAt:'2099-01-01',sourceType:'market',summary:'선물 준비 문의',sampleSize:null};
const need={title:'선물 상황',situation:'공연 방문',desiredOutcome:'간편 선물',alternative:'개별 선택',barrier:'선택 어려움',counterEvidence:'묶음이 불필요한 고객',signalIds:['signal'],deadline:'2099-01-01',nextAction:'오퍼 비교',assignee:'기획 담당'};
const catalog={sku:'SYNTHETIC',title:'합성 상품',price:10000,unitCost:3000,variableCost:1000,stock:10,stockUnit:'piece',currency:'KRW',taxBasis:'included',fulfillment:'영업일 발송',refunds:'미개봉 반품',rightsConfirmed:true,factIds:['f'],validUntil:'2099-01-01'};
await server.recordStatement(owner,'brand_fact','f',{id:'f',brandId:'b',key:'product',value:'합성 상품',source:'운영자 확인',status:'confirmed',version:1,verifiedAt:'2026-01-01',validUntil:'2099-01-01'},'b').run();
const offer={title:'선물 오퍼',catalogId:'catalog',catalogVersion:1,needId:'need',price:10000,quantity:1,landingUrl:'https://example.com/product',purchaseReason:'간편 준비',priceApproved:true},mission={title:'판매 계획',offerId:'offer',offerVersion:1,assignee:'판매 담당',deadline:'2099-01-01',nextAction:'판매면 검토',channel:'manual',budget:10000,lossLimit:1000,stopRule:'품절 시 중지',fulfillmentOwner:'운영 담당'};
for(const [entity,input] of [['signal',signal],['need',need],['catalog',catalog],['offer',offer],['mission',mission]])check((await gp({action:'save_'+entity,id:entity,input})).status===200,'seed '+entity);
const step={id:'step-1',channel:'organic',placement:'owned',message:'선물 준비를 간편하게',useScene:'공연 방문 전',creativeBrief:'사용 장면 이미지',keywords:[],audience:'선물 구매 관심층',purchaseUrl:'https://example.com/product',sourceUrls:['https://example.com/research'],authenticityConfirmed:true,rightsStatus:'confirmed',rightsEvidence:'owned-material',partnerRole:'',partnerTerms:'',plannedCost:0,performanceStatus:'not_measured',performanceEvidence:'',performanceNote:''};
const input={title:'선물 수요 시퀀스',objective:'구매 상황 전달',offerId:'offer',offerVersion:1,missionId:'mission',missionVersion:1,steps:[step]},save={action:'save_sequence',id:'sequence',input};
let r=await post(save);check(r.status===200,'save '+JSON.stringify(r));check(r.body.sequences[0].readiness.missing.length===0,'complete chain ready');check(r.body.mayExecute===false&&r.body.sequences[0].readiness.mayExecute===false,'ready never dispatches');check((await post(save)).body.duplicate,'retry idempotent');check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_demand_history'").get().n===1,'retry no extra history');
check((await post({...save,input:{...input,title:'동시 변경'}})).status===409,'stale sequence rejected');check((await post({...save,campaignVersion:2})).status===409,'stale campaign rejected');check((await post({...save,campaignId:'other',expectedVersion:1})).status===404,'cross campaign sequence refused');
check((await post({...save,id:'wrong-offer',input:{...input,offerId:'missing'}})).status===404,'missing offer refused');check((await post({...save,id:'old-offer',input:{...input,offerVersion:2}})).status===409,'offer version required');
check((await post({...save,id:'cost',input:{...input,steps:[{...step,plannedCost:10001}]}})).body.sequences.find(s=>s.id==='cost').readiness.missing.some(m=>m.includes('예산')),'sequence cost cannot exceed mission cap');
await gp({action:'save_signal',id:'signal',expectedVersion:1,input:{...signal,summary:'관측 정정'}});r=await get();check(r.body.sequences.find(s=>s.id==='sequence').readiness.missing.length>0,'upstream evidence changes invalidate ready sequence');
r=await post({...save,expectedVersion:1,input:{...input,steps:[{...step,id:'step-2'},step]}});check(r.status===200&&r.body.sequences.find(s=>s.id==='sequence').input.steps[0].id==='step-2','ordered sequence persists');
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_demand_history' AND json_extract(data,'$.sequenceId')='sequence'").get().n===2,'append-only revisions');
check((await server.campaignDeletionPreview(owner,'c')).deletable,'local planning does not block campaign deletion');
check((await post({...save,id:'secret',input:{...input,objective:'person@example.com'}})).status===400,'PII refused');
check((await post({...save,id:'unsupported',action:'publish'})).status===400,'no external action surface');
await gp({action:'save_offer',id:'different-offer',input:offer});
check((await post({...save,id:'mismatch',input:{...input,offerId:'different-offer'}})).status===409,'mission cannot reference a different offer');
const draft={title:'초안',objective:'',offerId:'',offerVersion:0,missionId:'',missionVersion:0,steps:[]};
await server.recordStatement(owner,'campaign','capped',{...c,id:'capped'}).run();
for(let i=0;i<500;i++)await server.recordStatement(owner,'growth_demand','cap-'+i,{id:'cap-'+i,brandId:'b',campaignId:'capped',campaignVersion:1,version:1,input:draft},'capped').run();
check((await post({action:'save_sequence',id:'cap-over',campaignId:'capped',input:draft})).status===409,'501st draft refused before write');
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_demand' AND parent_id='capped'").get().n===500,'capacity no partial write');
const full=await route.GET(new Request('https://agency.test/api/growth/demand?campaignId=capped',{headers:h}));check(full.status===200,'full capacity remains readable');
const token=createHash('sha256').update('demand-member').digest('hex');env.AUTH_MODE='email';env.AUTH_ORIGIN='https://agency.test';sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run('member','member@test.invalid',owner,'member','active',1);sql.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?)').run(createHash('sha256').update(token).digest('hex'),'member',Date.now()+60000,Date.now());
const member={cookie:'__Host-collective_session='+token,origin:'https://agency.test'};check((await get(member)).body.canEdit===false,'member read-only');check((await post({...save,id:'member'},member)).status===403,'member write refused');env.AUTH_MODE='legacy';
await server.recordStatement(owner,'campaign','c',{...c,status:'archived'}).run();check((await post({...save,expectedVersion:2})).status===409,'archived write refused');check(!(await get()).body.canEdit,'archived view disabled');
console.log(JSON.stringify({passed,external:'not_called'}));
