import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
const {load,sql}=testRuntime(async()=>{throw Error('Growth planning must not transmit externally')});
const server=await load('lib/server.ts');
const route=await load('app/api/growth/route.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='growth-owner',c={id:'c',brandId:'b',version:1,status:'active'};
const h={'oai-authenticated-user-id':owner,origin:'https://agency.test'};
await server.recordStatement(owner,'campaign','c',c).run();
await server.recordStatement(owner,'campaign','other',{...c,id:'other',brandId:'other-brand'}).run();
const unpack=async r=>({status:r.status,body:await r.json()});
const get=(headers=h)=>route.GET(new Request('https://agency.test/api/growth?campaignId=c',{headers})).then(unpack);
const post=(data,headers=h)=>route.POST(new Request('https://agency.test/api/growth',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,expectedVersion:0,...data})})).then(unpack);
check((await get({})).status===401,'anonymous read');
check((await get({'oai-authenticated-user-id':'foreign'})).status===404,'owner isolation');
check((await post({action:'save_signal'},{...h,origin:'https://evil.test'})).status===403,'csrf');
check((await post({action:'activate'})).status===400,'cannot grant execution via growth');
const signal={title:'실제 상품 문의 증가',sourceUrl:'https://example.com/research',observedAt:new Date(Date.now()-60000).toISOString(),expiresAt:'2099-01-01',sourceType:'market',summary:'상품 구성과 선물 용도를 확인하는 수요',sampleSize:null};
const s={action:'save_signal',id:'signal-1',input:signal};
let r=await post(s);check(r.status===200,'signal saved '+JSON.stringify(r));
r=await post(s);check(r.status===200&&r.body.duplicate,'network retry idempotent');
check((await post({...s,input:{...signal,title:'변경'}})).status===409,'stale write rejected');
check((await post({...s,campaignId:'other',expectedVersion:1})).status===404,'cross campaign ID denied');
const need={title:'선물 준비가 번거로운 고객',situation:'공연 방문 전',desiredOutcome:'빠른 선물 준비',alternative:'상품 개별 구매',barrier:'선택이 어렵다',counterEvidence:'묶음 선호가 실제 결제로 이어지지 않을 수 있다',signalIds:['signal-1'],deadline:'2099-01-01',nextAction:'선물 오퍼 비교',assignee:'판매 담당'};
check((await post({action:'save_need',id:'need-1',input:{...need,signalIds:['absent']}})).status===404,'missing evidence rejected');
check((await post({action:'save_need',id:'need-1',input:need})).status===200,'need saved');
const catalog={sku:'SYNTHETIC',title:'합성 상품',price:10000,unitCost:3000,variableCost:1000,stock:10,currency:'KRW',taxBasis:'included',fulfillment:'영업일 기준 발송',refunds:'미개봉 반품 안내',rightsConfirmed:true,factIds:['f'],validUntil:'2099-01-01'};
check((await post({action:'save_catalog',id:'cat-1',input:catalog})).status===409,'unconfirmed fact denied');
await server.recordStatement(owner,'brand_fact','f',{id:'f',brandId:'b',key:'product',value:'합성 상품',source:'운영자 확인',status:'confirmed',version:1,verifiedAt:'2026-01-01',validUntil:'2099-01-01'},'b').run();
check((await post({action:'save_catalog',id:'cat-1',input:catalog})).status===200,'catalog saved');
const offer={title:'선물 오퍼',catalogId:'cat-1',catalogVersion:1,needId:'need-1',price:10000,quantity:1,landingUrl:'https://example.com/product',purchaseReason:'선물 준비를 간편하게',priceApproved:true};
check((await post({action:'save_offer',id:'offer-1',input:offer})).status===200,'offer saved');
const mission={title:'첫 선물 판매',offerId:'offer-1',offerVersion:1,assignee:'판매 담당',deadline:'2099-01-01',nextAction:'판매면 검토\n배송 정책 확인',channel:'storefront',budget:100000,lossLimit:10000,stopRule:'품절 또는 손실 한도',fulfillmentOwner:'운영 담당'};
check((await post({action:'save_mission',id:'mission-1',input:mission})).status===200,'mission saved');
r=await get();check(r.body.missions[0].readiness.missing.length===0,'linked readiness');
check(r.body.missions[0].status==='draft'&&!r.body.mayExecute,'ready planning is not execution');
check(r.body.needs[0].readiness.evidenceLevel==='hypothesis','need remains hypothesis');
check(r.body.summary.salesStatus==='not_measured','no invented sales');
await server.recordStatement(owner,'brand_fact','f',{id:'f',brandId:'b',key:'product',value:'상품 변경',source:'운영자 확인',status:'confirmed',version:2,verifiedAt:'2026-01-01',validUntil:'2099-01-01'},'b').run();
r=await get();check(r.body.missions[0].readiness.missing.length>0,'fact revision invalidates downstream mission');
check((await post({action:'queue_mission',id:'mission-1',expectedVersion:1})).status===409,'cannot stage stale chain');
await post({action:'save_catalog',id:'cat-1',expectedVersion:1,input:catalog});
await post({action:'save_offer',id:'offer-1',expectedVersion:1,input:{...offer,catalogVersion:2}});
await post({action:'save_mission',id:'mission-1',expectedVersion:1,input:{...mission,offerVersion:2}});
r=await post({action:'queue_mission',id:'mission-1',expectedVersion:2});check(r.status===200&&r.body.missions[0].status==='staged','stages manual work only');
check(r.body.missions[0].readiness.mayExecute===false,'queue not external authorization');
check((await post({action:'save_mission',id:'mission-1',expectedVersion:3,input:mission})).status===409,'staged mission frozen');
check((await post({action:'record_receipt',id:'mission-1',expectedVersion:3,input:{status:'completed',reference:'external-1'}})).status===400,'no unverified success');
r=await post({action:'record_receipt',id:'mission-1',expectedVersion:3,input:{status:'unknown',reference:'external-1',note:'접수 결과 확인 중'}});check(r.status===200&&r.body.missions[0].status==='unknown','uncertain persisted');
check((await post({action:'queue_mission',id:'mission-1',expectedVersion:4})).status===409,'unknown cannot requeue');
r=await get();check(r.body.missions[0].receipt.status==='unknown','reload preserves unknown');
check(sql.prepare("SELECT count(*) n FROM records WHERE kind='growth_history'").get().n>0,'revision history');
await post({...s,expectedVersion:1,input:{...signal,title:'수요 관측 정정'}});
r=await get();check(r.body.missions[0].readiness.missing.length>0,'signal revision invalidates dependent chain');
await post({action:'save_need',id:'need-1',expectedVersion:1,input:need});
r=await get();check(r.body.offers[0].readiness.missing.length>0,'need revision requires offer review');
const capped={...c,id:'capped'};
await server.recordStatement(owner,'campaign',capped.id,capped).run();
for(let i=0;i<499;i++)await server.recordStatement(owner,'growth_signal','cap-'+i,{id:'cap-'+i,campaignId:capped.id,brandId:'b',campaignVersion:1,version:1,input:signal},capped.id).run();
check((await post({...s,id:'cap-final',campaignId:capped.id})).status===200,'500th record allowed');
check((await post({...s,id:'cap-over',campaignId:capped.id})).status===409,'501st record refused');
check(sql.prepare("SELECT count(*) n FROM records WHERE kind='growth_signal' AND parent_id='capped'").get().n===500,'limit rejection has no write');
check((await route.GET(new Request('https://agency.test/api/growth?campaignId=capped',{headers:h}))).status===200,'full workspace remains readable');
check((await server.campaignDeletionPreview(owner,'c')).deletable,'local planning and manual notes do not block campaign deletion');
check((await post({action:'save_mission',id:'pii',input:{...mission,assignee:'person@example.com'}})).status===400,'mission direct identifiers refused');
await server.recordStatement(owner,'campaign','c',{...c,status:'archived'}).run();
check((await post({...s,expectedVersion:1,input:{...signal,title:'보관 후'}})).status===409,'archived cannot mutate');
console.log(JSON.stringify({passed}));
