import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
const {load}=testRuntime(async()=>{throw Error('network forbidden')});
const worker=await load('lib/research-worker.ts');
const token=await worker.registerWorker('catalog-rotation'),principal={owner:'catalog-rotation',hash:await worker.workerHash(token)};
let catalogs=0,consumers=0,pulls=0;
const idle=async()=>({status:'idle'});
const pull=async()=>{pulls++;return {status:'processed'}};
const consumer=async()=>{consumers++;return {status:'processed'}};
const catalog=async owner=>{assert.equal(owner,principal.owner);catalogs++;return {status:'processed'}};
const tick=()=>worker.workerTick(principal,async()=>{throw Error('research forbidden')},idle,idle,undefined,undefined,undefined,undefined,pull,undefined,consumer,catalog);
assert.equal((await tick()).queue,'storefront_pull');
assert.equal((await tick()).queue,'consumer_recovery');
assert.equal((await tick()).queue,'provider_catalog');
assert.equal((await tick()).queue,'storefront_pull');
assert.equal((await tick()).queue,'consumer_recovery');
assert.equal((await tick()).queue,'provider_catalog');
assert.deepEqual([pulls,consumers,catalogs],[2,2,2]);
await assert.rejects(()=>worker.workerTick({...principal,hash:'0'.repeat(64)},async()=>new Response(),idle,idle,undefined,undefined,undefined,undefined,undefined,undefined,undefined,catalog));
assert.equal(catalogs,2);
console.log(JSON.stringify({passed:9}));
