import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
const {load}=testRuntime(async()=>{throw Error('Operations may not send external requests')});
const route=await load('app/api/growth/operations/route.ts');
const server=await load('lib/server.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='ops-owner',h={'oai-authenticated-user-id':owner,origin:'https://agency.test'};
const c={id:'c',brandId:'b',storeId:'s',version:1,status:'active'};
await server.recordStatement(owner,'campaign','c',c).run();
await server.recordStatement(owner,'campaign','other',{...c,id:'other'}).run();
await server.recordStatement(owner,'store','s',{id:'s',brandId:'b',version:1,status:'active'}).run();
const get=(headers=h)=>route.GET(new Request('https://agency.test/api/growth/operations?campaignId=c',{headers}));
const post=async(data,headers=h)=>{const response=await route.POST(new Request('https://agency.test/api/growth/operations',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,...data})}));return {status:response.status,body:await response.json()}};
check((await get({})).status===401,'anonymous refused');
check((await post({action:'create_inventory'},{...h,origin:'https://evil.test'})).status===403,'CSRF refused');
const created=await post({action:'create_inventory',input:{sku:'SYNTHETIC',locationId:'s',unit:'piece',onHand:5},evidenceRef:'count-sheet-1',observedAt:new Date(Date.now()-1000).toISOString()});
check(created.status===200,'inventory created '+JSON.stringify(created));
const inventoryId=created.body.inventory[0].id;
check(created.body.inventory[0].projection.available===5,'opening stock five');
check((await post({action:'create_inventory',input:{sku:'SYNTHETIC',locationId:'s',unit:'piece',onHand:10},evidenceRef:'count-sheet-2',observedAt:new Date().toISOString(),campaignId:'other'})).status===409,'same brand location SKU shared not cloned per campaign');
const order={id:'a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1',storeId:'s',version:1,orderDate:'2026-09-30',paidAmount:10000,refundAmount:0,status:'paid',costs:{foodCost:null,packagingCost:null,fees:null,deliveryCost:null,benefitCost:null}};
await server.recordStatement(owner,'store_order',order.id,order,'s').run();
await server.recordStatement(owner,'growth_mission','m',{id:'m',campaignId:'c',brandId:'b',campaignVersion:1,version:1,status:'staged',input:{offerId:'offer',offerVersion:1}},'c').run();
await server.recordStatement(owner,'growth_offer','offer',{id:'offer',campaignId:'c',brandId:'b',campaignVersion:1,version:1,input:{catalogId:'catalog',catalogVersion:1}},'c').run();
await server.recordStatement(owner,'growth_catalog','catalog',{id:'catalog',campaignId:'c',brandId:'b',campaignVersion:1,version:1,input:{sku:'SYNTHETIC',stockUnit:'piece'}},'c').run();
const link={orderId:order.id,orderVersion:1,sourceKey:'shop',accountId:'seller',externalLineId:'line',inventoryId,units:3,missionId:'m',missionVersion:1,offerId:'offer',offerVersion:1,paidAllocation:10000,refundAllocation:0,currency:'KRW',taxBasis:'included',evidenceRef:'seller-line',source:'operator_attested'};
const beforeLinkInventory=await server.readRecord(owner,'growth_inventory_item',inventoryId);await server.recordStatement(owner,'growth_inventory_item',inventoryId,{...beforeLinkInventory,input:{...beforeLinkInventory.input,unit:'pack'}},'s').run();check((await post({action:'link_order',input:link,expectedVersion:0})).status===409,'new allocation cannot convert piece to pack');await server.recordStatement(owner,'growth_inventory_item',inventoryId,beforeLinkInventory,'s').run();
let r=await post({action:'link_order',input:link,expectedVersion:0});check(r.status===200,'real ledger order linked '+JSON.stringify(r));
const lineId=r.body.orderLines[0].id;
check(r.body.inventory[0].projection.reserved===3&&r.body.inventory[0].projection.available===2,'order allocates stock once');
r=await post({action:'link_order',input:link,expectedVersion:0});check(r.status===200&&r.body.duplicate,'duplicate line receipt idempotent');
check(r.body.inventory[0].projection.reserved===3,'retry does not double reserve');
// A provider source blocked after a physical change must gate new preparation only.
await server.recordStatement(owner,'growth_provider_catalog_binding','held',{id:'held',brandId:'b',storeId:'s',sku:'SYNTHETIC',inventoryId,productId:'mpd::1',catalogId:'catalog',catalogVersion:1,version:1,connectionVersion:1},'s').run();
const stock=await load('lib/growth-stock-readiness-server.ts');
check((await stock.catalogStocks(owner,c,[{sku:'SYNTHETIC',stockUnit:'piece'}]))[0].status==='held','provider held state confirmed before existing shipment');
const event={action:'record_operation',id:'ship-1',inventoryVersion:2,lineId,kind:'ship',quantity:2,evidenceRef:'warehouse-note-1',observedAt:new Date().toISOString()};
r=await post(event);check(r.status===200&&r.body.inventory[0].projection.onHand===3,'shipment removes physical stock');
check((await post(event)).body.duplicate,'shipment retry no double subtract');
await server.recordStatement(owner,'store_order',order.id,{...order,version:2,refundAmount:5000},'s').run();
r={body:await (await get()).json()};check(r.body.orderLines[0].allocation.status==='reconciliation_required','refund marks old money allocation stale');
check(r.body.inventory[0].projection.onHand===3,'refund never restocks');
r=await post({action:'link_order',input:{...link,orderVersion:2,refundAllocation:5000},expectedVersion:1});check(r.status===200&&r.body.orderLines[0].version===2,'reconcile allocation without new reservation');
check(r.body.inventory[0].projection.reserved===1,'reconcile does not reallocate stock');
check((await post({...event,id:'ship-too-many',inventoryVersion:3,quantity:2,observedAt:new Date().toISOString()})).status===409,'cannot ship beyond remaining allocation');
r=await post({action:'record_operation',id:'safe-release-held-provider',inventoryVersion:3,lineId,kind:'release',quantity:1,safeRelease:true,evidenceRef:'cancel-proof',observedAt:new Date().toISOString()});
check(r.status===200&&r.body.inventory[0].projection.reserved===0,'provider held does not prevent safe unshipped release');
check((await stock.catalogStocks(owner,c,[{sku:'SYNTHETIC',stockUnit:'piece'}]))[0].status==='held','recovery leaves provider held for new preparation');
console.log(JSON.stringify({passed,sqlite:'real',provider:'not_called'}));
