// Real SQLite; synthetic owner, consent and provider. No actual customer messages.
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
let sends=0,reads=0,mode='delivered',payload;
const {load,sql}=testRuntime(async(url,opts)=>{
 const b=JSON.parse(opts.body),send=url.endsWith('/send');
 if(send){sends++;payload=b.payload;if(mode==='timeout')throw Error('response lost');}else reads++;
 return Response.json({requestId:payload.requestId,payloadDigest:b.payloadDigest,status:'delivered',costKrw:0,receiptId:randomUUID(),at:new Date().toISOString(),code:null});
});
const s=await load('lib/server.ts'),route=await load('app/api/growth/consumer-delivery/route.ts'),worker=await load('lib/growth-consumer-execution-worker.ts');
let passed=0;const check=(x,n)=>{assert.ok(x,n);passed++};
const owner='worker-owner',c={id:'c',brandId:'b',storeId:'s',version:1,status:'active'},customerId=randomUUID();
const past=new Date(Date.now()-60000).toISOString(),future=new Date(Date.now()+86400000).toISOString(),put=(kind,id,data,parent=c.id)=>s.recordStatement(owner,kind,id,data,parent).run();
await put('campaign',c.id,c,'');await put('store','s',{id:'s',brandId:'b'},'b');
const consent=purpose=>({purpose,state:'granted',noticeVersion:'v1',evidenceRef:'proof',observedAt:past,expiresAt:future});
const customer={id:customerId,brandId:'b',version:1,state:'active',consents:{identity_link:consent('identity_link'),post_purchase:consent('post_purchase'),marketing_reorder:consent('marketing_reorder')}};
await put('growth_customer',customerId,customer,'b');
await put('store_order','order',{id:'order',storeId:'s',version:1,orderDate:past.slice(0,10),status:'paid',paidAmount:100,refundAmount:0},'s');
await put('growth_consumer_order_link','link',{id:'link',brandId:'b',customerId,storeId:'s',orderId:'order',orderVersion:1,version:1,evidenceRef:'proof'},'b');
await put('growth_authority','grant',{id:'grant',brandId:'b',campaignId:c.id,campaignVersion:1,version:1,input:{id:'grant',brandId:'b',campaignId:c.id,accountId:'tenant',channel:'consumer_delivery',status:'active',maxTier:'T2',allowedActions:['publish'],ownerApprovalId:'approved',ownerSignedAt:past,startsAt:past,expiresAt:future,periodStart:past,periodEnd:future,totalCap:0,dayCap:0,weekCap:0,lossCap:0}});
const post=async body=>{const r=await route.POST(new Request('https://agency.test/api/growth/consumer-delivery',{method:'POST',headers:{'oai-authenticated-user-id':owner,origin:'https://agency.test','content-type':'application/json'},body:JSON.stringify({campaignId:c.id,campaignVersion:1,expectedVersion:0,requestId:randomUUID(),...body})}));return {status:r.status,body:await r.json()}};
const config={tenantId:'tenant',providerStoreId:'shop',secret:'synthetic-worker-signing-secret-00000000',enabled:false};
await post({action:'configure',config});await post({action:'configure',expectedVersion:1,config:{...config,enabled:true}});
const input={customerId,customerVersion:1,purpose:'post_purchase',templateId:randomUUID(),templateDigest:'a'.repeat(64),maxCostKrw:0,expiresAt:future,waitDays:0,authorityId:'grant',authorityVersion:1};
async function queue(autoDispatch){const id=randomUUID();assert.equal((await post({action:'queue',id,input})).status,200);const approved=await post({action:'approve',id,expectedVersion:1,confirm:true,...(autoDispatch===undefined?{}:{autoDispatch})});assert.equal(approved.status,200,JSON.stringify(approved));return id;}
const get=id=>s.readRecord(owner,'growth_consumer_delivery',id);
const manual=await queue();
check((await worker.advanceConsumerDeliveryWork(owner)).status==='idle'&&sends===0,'old/manual approval never auto sends');
const broken=await queue(true),brokenRow=await get(broken);await put('growth_consumer_delivery',broken,{...brokenRow,campaignId:'missing'},'missing');
await worker.advanceConsumerDeliveryWork(owner);check(sends===0&&!(await get(broken)).approval,'missing campaign quarantined without blocking following work');
const automatic=await queue(true),second=await queue(true);
const lock=await s.acquireLock(owner);check((await worker.advanceConsumerDeliveryWork(owner)).status==='idle'&&sends===0,'same owner mutation lock');await s.releaseLock(owner,lock);
check((await worker.advanceConsumerDeliveryWork(owner)).status==='processed'&&sends===1,'exactly one approved message per tick');
check((await get(automatic)).status==='delivered'&&(await get(second)).status==='queued','bounded queue preserves second');
await worker.advanceConsumerDeliveryWork(owner);check(sends===2&&(await get(manual)).status==='queued','second approved sends, manual remains');
const unknown=await queue(true);mode='timeout';await worker.advanceConsumerDeliveryWork(owner);check((await get(unknown)).status==='unknown'&&sends===3,'lost response keeps durable unknown');
check((await worker.advanceConsumerDeliveryWork(owner)).status==='idle','durable retry delay');
mode='delivered';await worker.advanceConsumerDeliveryWork(owner,Date.now()+60000);check(sends===3&&reads===1&&(await get(unknown)).status==='delivered','unknown recovers with receipt only');
const revoked=await queue(true);await put('growth_customer',customerId,{...customer,version:2,consents:{...customer.consents,post_purchase:{...consent('post_purchase'),state:'revoked'}}},'b');
await worker.advanceConsumerDeliveryWork(owner);check(sends===3&&!(await get(revoked)).approval,'withdrawal blocks send and requires fresh owner approval');
await put('growth_customer',customerId,customer,'b');
const stopped=await queue(true);await put('growth_stop','global',{id:'global',status:'stopped',version:1,reason:'운영 중단',updatedAt:past,updatedBy:owner},'');await worker.advanceConsumerDeliveryWork(owner);check(sends===3&&!(await get(stopped)).approval,'global stop prevents auto send');
await put('growth_stop','global',{id:'global',status:'running',version:2,reason:'운영 재개',updatedAt:past,updatedBy:owner},'');
const malformed=await post({action:'approve',id:manual,expectedVersion:2,confirm:true,autoDispatch:'yes'});check(malformed.status===400,'explicit automation boolean required');
const other=await worker.advanceConsumerDeliveryWork('other-owner');check(other.status==='idle'&&sends===3,'owner isolation');
const drain=await load('lib/growth-consumer-delivery-drain.ts'),healthy=await queue(true),orphanId=randomUUID();
await put('growth_consumer_delivery',orphanId,{...(await get(healthy)),id:orphanId,campaignId:'deleted-campaign',status:'unknown',cancelPending:true},'deleted-campaign');
const first=await drain.drainConsumerCancellations(owner,1);check(first.attempted===1&&!!(await get(orphanId)).cancelRetryAt,'orphan cancellation retains durable retry');
const retry=await drain.drainConsumerCancellations(owner,1);if(!retry.attempted)await worker.advanceConsumerDeliveryWork(owner);
check(sends===4&&(await get(healthy)).status==='delivered','orphan cancellation does not starve healthy approved work');
const capped=await queue(true);mode='timeout';await worker.advanceConsumerDeliveryWork(owner);check((await get(capped)).status==='unknown','capacity fixture is a real uncertain send');
for(let i=0;i<5000;i++)await put('growth_consumer_delivery_history','capacity-'+i,{synthetic:true});
const pending=await get(capped),cancel={action:'cancel',id:capped,expectedVersion:pending.version,requestId:randomUUID()};
check((await post(cancel)).status===200&&(await get(capped)).cancelPending,'history cap never blocks withdrawal of existing obligation');
check((await post(cancel)).body.duplicate,'capacity recovery preserves request replay');
check((await post({action:'queue',id:randomUUID(),input})).status===409,'capacity still blocks new work');
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='growth_consumer_delivery_history'").get().n>0,'attempts remain auditable');
console.log(JSON.stringify({passed,sqlite:'real',provider:'mocked',sends}));
