import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const {createConsumerConsent,mountConsumerConsent}=await import('data:text/javascript;base64,'+Buffer.from(readFileSync('scripts/mapdal/consumer-consent-browser.js')).toString('base64'));
let passed=0;const test=async(name,fn)=>{await fn();passed++;};
const notices=()=>({purposes:['post_purchase','marketing_reorder'].map(purpose=>({purpose,version:'v1',text:'운영자가 제공한 합성 고지',maxAgeSeconds:3600,granted:false,expiresAt:null}))});
function setup(responses=[{status:200,value:notices()}]){const calls=[];const api=createConsumerConsent({csrfToken:'synthetic-csrf-token-000000',fetchImpl:async(url,options)=>{calls.push({url,...options});const r=responses.shift();if(r instanceof Error)throw r;return {status:r.status,json:async()=>r.value};}});return {api,calls};}
await test('initially unchecked and no post on loading',async()=>{const r=notices();r.purposes[0].granted=true;r.purposes[0].expiresAt='2099-01-01T00:00:00Z';const {api,calls}=setup([{status:200,value:r}]);await api.load();assert(api.state().purposes.every(p=>!p.selected));assert.equal(api.state().purposes[0].granted,true);assert.equal(calls.length,1);assert.equal(calls[0].method,'GET');});
await test('no consent without explicit choice',async()=>{const {api,calls}=setup();await api.load();assert.equal(await api.save('post_purchase'),false);assert.equal(calls.length,1);});
await test('purpose choices independent and payload has no identity',async()=>{const {api,calls}=setup([{status:200,value:notices()},{status:200,value:notices()}]);await api.load();api.choose('post_purchase',true);assert.equal(api.state().purposes[1].selected,false);assert.equal(await api.save('post_purchase'),true);assert.deepEqual(JSON.parse(calls[1].body),{purpose:'post_purchase',granted:true,version:'v1'});assert.equal(calls[1].credentials,'same-origin');assert.equal(calls[1].redirect,'error');});
await test('explicit withdraw submits only false',async()=>{const {api,calls}=setup([{status:200,value:notices()},{status:200,value:notices()}]);await api.load();await api.withdraw('marketing_reorder');assert.equal(JSON.parse(calls[1].body).granted,false);});
await test('lost response blocks further changes until reload and shows error',async()=>{const {api,calls}=setup([{status:200,value:notices()},new Error('lost'),{status:200,value:notices()}]);await api.load();api.choose('post_purchase',true);await api.save('post_purchase');assert(api.state().error);assert(api.state().needsReload);assert.equal(await api.withdraw('post_purchase'),false);assert.equal(calls.length,2);await api.load();assert.equal(api.state().needsReload,false);});
await test('duplicate pending clicks produce one POST',async()=>{let done;const wait=new Promise(r=>done=r);let calls=0;const api=createConsumerConsent({csrfToken:'synthetic-csrf-token-000000',fetchImpl:async(u,o)=>{calls++;if(o.method==='POST')await wait;return {status:200,json:async()=>notices()};}});await api.load();api.choose('post_purchase',true);const pending=api.save('post_purchase');assert.equal(await api.save('post_purchase'),false);done();await pending;assert.equal(calls,2);});
await test('invalid server notices block choices',async()=>{const {api}=setup([{status:200,value:{purposes:[]}}]);assert.equal(await api.load(),false);assert(api.state().error);});
await test('panel starts with unchecked independent checkboxes and text-only notice',async()=>{class Element{constructor(tag){this.tagName=tag;this.children=[];this.listeners={};}append(...e){this.children.push(...e);}replaceChildren(...e){this.children=[...e];}addEventListener(k,fn){this.listeners[k]=fn;}setAttribute(k,v){this[k]=v;}}const doc={createElement:tag=>new Element(tag)};const root=new Element('div');root.ownerDocument=doc;const {api}=setup();mountConsumerConsent(root,api);await api.load();const all=[];const walk=e=>{all.push(e);e.children.forEach(walk);};walk(root);const checks=all.filter(e=>e.type==='checkbox');assert.equal(checks.length,2);assert(checks.every(e=>e.checked===false));assert(all.some(e=>e.textContent==='운영자가 제공한 합성 고지'));});
console.log(JSON.stringify({passed,network:'mocked',liveWrites:0}));
