import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
const {load}=testRuntime(async()=>{throw new Error('No Meta writes')});
const lib=await load('lib/meta-reservation.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const now=Date.now(),scope={scopeDigest:'a'.repeat(64),accountId:'1',adsetId:'2',startAt:new Date(now+60000).toISOString(),endAt:new Date(now+86400000).toISOString(),verifiedAt:new Date(now).toISOString()};
const input={amount:9000,totalBudget:10000,safetyReserve:1000,lossLimit:3000,stopRule:'3일 구매 없음',scope};
check(lib.reservationIssues(input,[],now).length===0,'safe envelope');
check(lib.reservationIssues({...input,amount:9001},[],now).length>0,'reserve outside envelope');
check(lib.reservationIssues({...input,amount:0},[],now).length>0,'zero amount');
check(lib.reservationIssues({...input,amount:1.2},[],now).length>0,'integer KRW');
check(lib.reservationIssues({...input,scope:{...scope,startAt:new Date(now-1).toISOString()}},[],now).length>0,'past start');
check(lib.reservationIssues({...input,scope:{...scope,verifiedAt:new Date(now-16*60000).toISOString()}},[],now).length>0,'stale verification');
const active={id:'r',campaignId:'c',accountId:'1',adsetId:'2',state:'reserved',amount:1000};
check(lib.reservationIssues(input,[active],now).length>0,'same external adset cannot reserve twice');
check(lib.reservationIssues(input,[{...active,state:'released'}],now).length===0,'released frees local reservation');
check(lib.reservationIssues(input,[{...active,state:'unknown'}],now).length>0,'unknown cannot free envelope');
check(lib.reservationIssues({...input,lossLimit:10000},[],now).length>0,'loss limit within envelope');
check(lib.reservationIssues({...input,stopRule:''},[],now).length>0,'explicit stop condition');
console.log(JSON.stringify({passed}));
