import assert from 'node:assert/strict';
import {deflateSync} from 'node:zlib';
import {testRuntime} from './helpers/runtime.mjs';
let calls=0,fail=false,saveFail=false;
const {load,env,sql}=testRuntime(async()=>{calls++;if(fail)throw new Error('secret_token');return Response.json({images:{one:{hash:'f'.repeat(32)}}})},{beforeRun:s=>{if(saveFail&&s.query.startsWith('UPDATE records')&&String(s.values[0]).includes('"state":"uploaded"'))throw new Error('save failure')}});
const server=await load('lib/server.ts'),route=await load('app/api/meta-ads/assets/route.ts'),creativeRoute=await load('app/api/meta-ads/creative/route.ts'),creativeLib=await load('lib/meta-creative-review.ts'),planLib=await load('lib/meta-ads.ts'),flags=await load('lib/feature-flags.ts'),media=await load('lib/execution-media.ts'),crypto=await load('lib/credential-crypto-server.ts');
function crc32(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let bit=0;bit<8;bit++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}return (crc^0xffffffff)>>>0}
function chunk(type,data){const name=Buffer.from(type),size=Buffer.alloc(4),crc=Buffer.alloc(4);size.writeUInt32BE(data.length);crc.writeUInt32BE(crc32(Buffer.concat([name,data])));return Buffer.concat([size,name,data,crc])}
const signature=Buffer.from([137,80,78,71,13,10,26,10]),ihdr=Buffer.alloc(13);
ihdr.writeUInt32BE(1080,0);ihdr.writeUInt32BE(1080,4);ihdr[8]=8;ihdr[9]=2;
function fixture(fill=0){const pixels=Buffer.alloc((1080*3+1)*1080,fill);for(let row=0;row<1080;row++)pixels[row*(1080*3+1)]=0;return Buffer.concat([signature,chunk('IHDR',ihdr),chunk('IDAT',deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))])}

const png=fixture();let bucketBytes=png;env.BUCKET={get:async()=>({size:bucketBytes.length,arrayBuffer:async()=>Uint8Array.from(bucketBytes).buffer})};
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};const owner='bundle-route',headers={'oai-authenticated-user-id':owner,origin:'https://agency.test'},write=(kind,id,data,parent)=>server.recordStatement(owner,kind,id,data,parent).run();await write('brand','b',{id:'b',name:'Synthetic brand',color:'#112233'});await write('store','s',{id:'s',brandId:'b',version:1,status:'active'},'b');const fact={id:'fact',brandId:'b',key:'price',value:'10,000원',status:'confirmed',source:'Synthetic source',verifiedAt:'2026-01-01T00:00:00Z',validUntil:'2100-01-01T00:00:00Z',version:1,updatedAt:'2026-01-01T00:00:00Z'};await write('brand_fact','fact',fact,'b');await write('channel_credential','meta_ads:b',{channel:'meta_ads',brandId:'b',accountId:'123',readEnabled:true,version:1});
async function setup(id,review=true){const c={id,brandId:'b',storeId:'s',title:'Synthetic campaign',version:1,status:'draft'};await write('campaign',id,c);await write('meta_ads_plan',id,{id,campaignId:id,brandId:'b',campaignVersion:1,version:1,input:{...planLib.emptyMetaPlan(),product:'Synthetic product',landingUrl:'https://example.com/product',storeStack:'Manual import',accountLabel:'Synthetic account',startAt:'2026-09-29T00:00:00Z',endAt:'2099-01-01T00:00:00Z',attributionWindow:'7d click',stopRule:'Owner stop',price:10000,unitCost:3000,variableCost:200,totalBudget:10000,dailyTarget:1000,lossLimit:3000,safetyReserve:1000,taxBasis:'included',checks:Object.fromEntries(Object.keys(planLib.metaChecks).map(k=>[k,true]))}},id);await write('execution_creative','creative-'+id,{id:'creative-'+id,campaignId:id,brandId:'b',storeId:'s',campaignVersion:1,version:1,factRefs:[{id:'fact',version:1}],caption:'가격: 10,000원',pngHash:await media.sha256(png),objectKey:'mocked.png'},id);await write('store_experiment','exp-'+id,{id:'exp-'+id,storeId:'s',brandId:'b',campaignId:id,title:'Synthetic experiment',version:1,status:'draft',hypothesis:'Synthetic hypothesis',control:'A',treatment:'B',measurement:'Ledger',target:20},'s');if(review){const r=await creativeRoute.POST(new Request('https://agency.test/api/meta-ads/creative',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({action:'review',campaignId:id,campaignVersion:1,planVersion:1,expectedVersion:0,warningsAcknowledged:true,input:{...creativeLib.emptyMetaCreative(),creativeId:'creative-'+id,experimentId:'exp-'+id,title:'Synthetic',hook:'상품 구성 확인',body:'10,000원',cta:'구성 확인',rightsEvidence:'자체 제작',reviewNote:'랜딩 확인',rightsConfirmed:true,landingConfirmed:true}})}));assert.equal(r.status,200)}return c}


await setup('c');const res=async r=>({status:r.status,body:await r.json()}),get=(h=headers)=>route.GET(new Request('https://agency.test/api/meta-ads/assets?campaignId=c',{headers:h})).then(res),post=(b={},h=headers)=>route.POST(new Request('https://agency.test/api/meta-ads/assets',{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',action:'prepare',campaignVersion:1,...b})})).then(res);
check((await get({})).status===401,'anonymous');check((await get({'oai-authenticated-user-id':'other'})).status===404,'owner isolation');check((await post({}, {...headers,origin:'https://evil.test'})).status===403,'CSRF');check((await post()).status===409&&calls===0,'default disabled');await flags.setFeatureFlag(owner,{flag:'meta_ads_image_upload',enabled:true},{id:owner,email:null});
await write('channel_credential','meta_ads_write:b',{channel:'meta_ads_write',brandId:'b',accountId:'123',permission:'ads_management',version:1,updatedAt:'2026-09-28T00:00:00Z',secret:await crypto.sealRecordSecret(owner,'channel_credential','meta_ads_write:b','synthetic_upload_token')});
let v=(await get()).body;check(v.issues.length===0,'review and account ready');check((await post({evidenceFingerprint:'old'})).status===409,'stale review');let r=await post({evidenceFingerprint:v.evidenceFingerprint});check(r.status===200&&r.body.operations.length===1&&calls===0,'local prepare');const initial=r.body.operations[0];const preparedCredential=await server.readRecord(owner,'channel_credential','meta_ads_write:b');await write('channel_credential','meta_ads_write:b',{...preparedCredential,updatedAt:'2026-09-29T00:00:00Z'});v=(await get()).body;r=await post({evidenceFingerprint:v.evidenceFingerprint});check(r.body.operations[0].id===initial.id&&r.body.operations[0].version===2,'unsent preparation rebases same key after connection refresh');const op=r.body.operations[0],upload={action:'upload',operationId:op.id,expectedVersion:op.version,confirmed:true,evidenceFingerprint:v.evidenceFingerprint};
check((await post({...upload,confirmed:false})).status===400&&calls===0,'explicit upload consent');bucketBytes=fixture(255);check((await post(upload)).status===409&&calls===0,'bucket bytes mismatch');bucketBytes=png;r=await post(upload);check(r.status===200&&r.body.operations[0].state==='uploaded'&&calls===1,'immutable uploaded receipt');check(r.body.operations[0].receipt.sourceBytesVerified&&!r.body.operations[0].receipt.displayBytesVerified,'source not display proof');check((await post(upload)).status===409&&calls===1,'duplicate refuses');check((await post({evidenceFingerprint:v.evidenceFingerprint})).body.operations.length===1,'prepare cannot mint new upload');
const imageServer=await load('lib/meta-image-upload-server.ts'),c=await server.readRecord(owner,'campaign','c');check((await imageServer.eligibleMetaImageReceipts(owner,c)).length===1,'current bundle receipt eligible');await assert.rejects(()=>imageServer.metaImageUploadJournal(owner,op.id,owner).finish({state:'unknown'}));passed++;
const bundle=await load('lib/meta-ad-bundle-server.ts'),linked=await imageServer.eligibleMetaImageReceipts(owner,c),scopeContext={parents:[{id:'parent',receipt:{externalId:'789'}}],creative:{plan:{input:{dailyTarget:1000,landingUrl:'https://example.test',startAt:'start',endAt:'end'}}},review:{saved:{input:{hook:'hook',body:'body'}}},issues:[],connection:{accountId:'123'},imageReceipts:linked},scopeInput={operationId:'parent',dailyBudgetKrw:1000,imageUploadReceiptId:op.id,expectedMetaImageHash:'f'.repeat(32)};
check(bundle.metaAdBundleScope(c,scopeContext,scopeInput).sourceBytesVerified===true,'bundle binds receipt source provenance');assert.throws(()=>bundle.metaAdBundleScope(c,scopeContext,{...scopeInput,expectedMetaImageHash:'0'.repeat(32)}));passed++;
const credential=await server.readRecord(owner,'channel_credential','meta_ads_write:b');await write('channel_credential','meta_ads_write:b',{...credential,updatedAt:'2099-01-01T00:00:00Z'});check((await imageServer.eligibleMetaImageReceipts(owner,c)).length===1,'credential refresh retains immutable source proof for same account');await write('channel_credential','meta_ads_write:b',credential);
for(const mode of ['timeout','save-fail']){const id=mode;await setup(id);const req=async action=>{const view=await route.GET(new Request('https://agency.test/api/meta-ads/assets?campaignId='+id,{headers})).then(res);return post({campaignId:id,evidenceFingerprint:view.body.evidenceFingerprint,...action})};r=await req({action:'prepare'});const o=r.body.operations[0];fail=mode==='timeout';saveFail=mode==='save-fail';r=await req({action:'upload',operationId:o.id,expectedVersion:1,confirmed:true});check(r.status===502,'unknown response '+mode);fail=false;saveFail=false;const saved=await server.readRecord(owner,'meta_ads_image_upload',o.id);check(saved.state==='unknown','unknown persisted '+mode);const n=calls;check((await req({action:'upload',operationId:o.id,expectedVersion:saved.version,confirmed:true})).status===409&&calls===n,'no unknown reupload '+mode)}
check((await server.campaignDeletionPreview(owner,'c')).deletable===false,'receipt retains deletion block');
const {createHash}=await import('node:crypto');env.AUTH_MODE='email';env.AUTH_ORIGIN='https://agency.test';sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run('workspace-owner','owner@test.invalid',owner,'admin','active',1);for(const role of ['admin','member']){const token=createHash('sha256').update('image-'+role).digest('hex');sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run(role,role+'@test.invalid',owner,role,'active',1000);sql.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?)').run(createHash('sha256').update(token).digest('hex'),role,Date.now()+60000,Date.now());const h={cookie:'__Host-collective_session='+token,origin:'https://agency.test'},view=(await get(h)).body;check(view.canEdit===(role==='admin'),'role edit access '+role);check((await post({evidenceFingerprint:view.evidenceFingerprint},h)).status===(role==='admin'?200:403),'admin allowed/member denied '+role)}
console.log(JSON.stringify({passed}));
