import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
let posts=0,remote={},spend='0',offset=1,failAt=0;
const {load,sql}=testRuntime(async(url,opts)=>{const path=new URL(url).pathname,id=path.split('/').at(-1);if(opts.method==='POST'){posts++;if(posts===failAt)throw new Error('timeout');remote[id]={...remote[id],configured_status:new URLSearchParams(opts.body).get('status')};return Response.json({success:true})}if(id==='me')return Response.json({currency:{user_currency:'KRW',currency_offset:offset}});if(id==='permissions')return Response.json({data:[{permission:'ads_management',status:'granted'}]});if(id==='act_123')return Response.json({account_id:'123',currency:'KRW',timezone_name:'Asia/Seoul',account_status:1});if(id==='adsets')return Response.json({data:[{id:'201'}]});if(id==='ads')return Response.json({data:[{id:'203'}]});if(id==='insights')return Response.json({data:[{account_id:'123',adset_id:'201',account_currency:'KRW',spend}]});return Response.json(remote[id]??{})});
const server=await load('lib/server.ts'),creativeRoute=await load('app/api/meta-ads/creative/route.ts'),creativeLib=await load('lib/meta-creative-review.ts'),planLib=await load('lib/meta-ads.ts'),flags=await load('lib/feature-flags.ts'),digest=await load('lib/storefront-orders.ts'),creativeServer=await load('lib/meta-creative-server.ts'),crypto=await load('lib/credential-crypto-server.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};const owner='bundle-route',headers={'oai-authenticated-user-id':owner,origin:'https://agency.test'},write=(kind,id,data,parent)=>server.recordStatement(owner,kind,id,data,parent).run();await write('brand','b',{id:'b',name:'Synthetic brand',color:'#112233'});await write('store','s',{id:'s',brandId:'b',version:1,status:'active'},'b');const fact={id:'fact',brandId:'b',key:'price',value:'10,000원',status:'confirmed',source:'Synthetic source',verifiedAt:'2026-01-01T00:00:00Z',validUntil:'2100-01-01T00:00:00Z',version:1,updatedAt:'2026-01-01T00:00:00Z'};await write('brand_fact','fact',fact,'b');await write('channel_credential','meta_ads:b',{channel:'meta_ads',brandId:'b',accountId:'123',readEnabled:true,version:1});
async function setup(id,review=true){const c={id,brandId:'b',storeId:'s',title:'Synthetic campaign',version:1,status:'draft'};await write('campaign',id,c);await write('meta_ads_plan',id,{id,campaignId:id,brandId:'b',campaignVersion:1,version:1,input:{...planLib.emptyMetaPlan(),product:'Synthetic product',landingUrl:'https://example.com/product',storeStack:'Manual import',accountLabel:'Synthetic account',startAt:new Date(Date.now()+3600000).toISOString(),endAt:new Date(Date.now()+86400000).toISOString(),attributionWindow:'7d click',stopRule:'Owner stop',price:10000,unitCost:3000,variableCost:200,totalBudget:10000,dailyTarget:1000,lossLimit:3000,safetyReserve:1000,taxBasis:'included',checks:Object.fromEntries(Object.keys(planLib.metaChecks).map(k=>[k,true]))}},id);await write('execution_creative','creative-'+id,{id:'creative-'+id,campaignId:id,brandId:'b',storeId:'s',campaignVersion:1,version:1,factRefs:[{id:'fact',version:1}],caption:'가격: 10,000원',pngHash:'a'.repeat(64),objectKey:'mocked.png'},id);await write('store_experiment','exp-'+id,{id:'exp-'+id,storeId:'s',brandId:'b',campaignId:id,title:'Synthetic experiment',version:1,status:'draft',hypothesis:'Synthetic hypothesis',control:'A',treatment:'B',measurement:'Ledger',target:20},'s');if(review){const r=await creativeRoute.POST(new Request('https://agency.test/api/meta-ads/creative',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({action:'review',campaignId:id,campaignVersion:1,planVersion:1,expectedVersion:0,warningsAcknowledged:true,input:{...creativeLib.emptyMetaCreative(),creativeId:'creative-'+id,experimentId:'exp-'+id,title:'Synthetic',hook:'상품 구성 확인',body:'10,000원',cta:'구성 확인',rightsEvidence:'자체 제작',reviewNote:'랜딩 확인',rightsConfirmed:true,landingConfirmed:true}})}));assert.equal(r.status,200)}return c}


await write('channel_credential','meta_ads_write:b',{channel:'meta_ads_write',brandId:'b',accountId:'123',permission:'ads_management',version:1,updatedAt:'2026-09-28T00:00:00Z',secret:await crypto.sealRecordSecret(owner,'channel_credential','meta_ads_write:b','synthetic_create_token')});
let parentIndex=1000;async function ready(id){await setup(id);const c=await server.readRecord(owner,'campaign',id),x=await creativeServer.metaCreativeContext(owner,c),review=creativeServer.viewMetaCreative(c,x,false),parentId=await digest.storefrontDigest({id}),externalId=String(++parentIndex),imageId=await digest.storefrontDigest({image:id});await write('meta_ads_write_operation',parentId,{id:parentId,campaignId:id,brandId:'b',campaignVersion:1,evidenceFingerprint:await digest.storefrontDigest({campaignVersion:1,plan:x.plan,review:review.saved,connectionVersion:1,accountId:'123'}),draft:{accountId:'123'},receipt:{accountId:'123',state:'paused_verified',externalId},version:1},id);remote[externalId]={id:externalId,name:'Parent [Collective '+parentId+']',account_id:'123',objective:'OUTCOME_SALES',configured_status:'PAUSED',effective_status:'PAUSED'};await write('meta_ads_image_upload',imageId,{id:imageId,campaignId:id,brandId:'b',creativeId:'creative-'+id,creativeVersion:1,pngHash:'a'.repeat(64),accountId:'123',state:'uploaded',receipt:{sourceBytesVerified:true,metaImageHash:'f'.repeat(32)}},id);return {operationId:parentId,imageUploadReceiptId:imageId,pageId:'50',pixelId:'60',graphDailyBudget:'100000',budgetUnitEvidence:'수동 검토',ageMin:18,ageMax:65,callToActionType:'LEARN_MORE'}}
const pausedRoute=await load('app/api/meta-ads/paused/route.ts'),executionRoute=await load('app/api/meta-ads/execution/route.ts'),bundle=await load('lib/meta-ad-bundle-server.ts'),reservation=await load('lib/meta-reservation-server.ts'),execution=await load('lib/meta-execution-server.ts');
await flags.setFeatureFlag(owner,{flag:'meta_ads_bundle',enabled:true},{id:owner,email:null});
const input={...await ready('c'),graphDailyBudget:'1000',dailyBudgetKrw:1000,country:'KR',expectedMetaImageHash:'f'.repeat(32),adsetId:'201',creativeId:'202',adId:'203'},c=await server.readRecord(owner,'campaign','c'),x=await bundle.metaAdBundleContext(owner,c),scope=bundle.metaAdBundleScope(c,x,input),scopeDigest=await digest.storefrontDigest({scope,evidenceFingerprint:x.evidenceFingerprint}),at=new Date().toISOString();
await write('meta_ads_bundle','c',{id:'c',campaignId:'c',brandId:'b',campaignVersion:1,version:1,input,evidenceFingerprint:x.evidenceFingerprint,status:'verified',verifiedScope:{...scope,scopeDigest,verifiedAt:at},reviewedBy:owner,reviewedAt:at,updatedAt:at,updatedBy:owner},'c');
remote['201']={id:'201',account_id:'123',campaign_id:scope.campaignId,configured_status:'PAUSED',daily_budget:'1000',billing_event:'IMPRESSIONS',optimization_goal:'OFFSITE_CONVERSIONS',destination_type:'WEBSITE',start_time:scope.startAt,end_time:scope.endAt,promoted_object:{pixel_id:scope.pixelId,custom_event_type:'PURCHASE'},targeting:{geo_locations:{countries:['KR']},age_min:18,age_max:65}};
remote['202']={id:'202',account_id:'123',object_story_spec:{page_id:scope.pageId,link_data:{link:scope.landingUrl,name:scope.hook,message:scope.body,image_hash:scope.expectedMetaImageHash,call_to_action:{type:scope.callToActionType,value:{link:scope.landingUrl}}}}};remote['203']={id:'203',account_id:'123',campaign_id:scope.campaignId,adset_id:'201',configured_status:'PAUSED',creative:{id:'202'}};
await write('worker_credential','current',{hash:'workerhash',createdAt:at});await write('worker_state','current',{lastSeen:at,tokenHash:'workerhash'});
await reservation.reserveMetaBudget(owner,owner,c,{expectedScopeDigest:scopeDigest,amount:5000,note:'Synthetic reservation'});const r=(await reservation.reservationRecords(owner))[0];
const post=async(b,h=headers)=>{const response=await executionRoute.POST(new Request('https://agency.test/api/meta-ads/execution',{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,confirmed:true,...b})}));return {status:response.status,body:await response.json()}};
const approval={action:'approve',reservationId:r.id,reservationVersion:r.version,expectedScopeDigest:scopeDigest,maxSpend:5000,expiresAt:scope.endAt,emergencyStopMandate:true};
check((await post(approval,{})).status===401,'anonymous');check((await post(approval,{...headers,origin:'https://evil.test'})).status===403,'CSRF');check((await post(approval,{'oai-authenticated-user-id':'other',origin:headers.origin})).status===404,'owner isolation');check((await post(approval)).status===409&&posts===0,'defaultOFF');
await flags.setFeatureFlag(owner,{flag:'meta_ads_execution',enabled:true},{id:owner,email:null});let result=await post(approval);check(result.status===200,'approve '+JSON.stringify(result));let e=result.body.records[0];check(e.state==='approved'&&posts===0,'approval has zero POST');check((await post(approval)).status===409,'duplicate reservation approval');
await assert.rejects(()=>reservation.releaseMetaBudget(owner,owner,c,{id:r.id,expectedVersion:r.version}));passed++;
result=await post({action:'activate',id:e.id,expectedVersion:e.version});check(result.status===200&&result.body.records[0].state==='active','activation '+JSON.stringify(result));e=result.body.records[0];check(posts===3,'three hierarchy POSTs');const disconnect=await pausedRoute.POST(new Request('https://agency.test/api/meta-ads/paused',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({action:'disconnect',campaignId:'c',connectionVersion:1})}));check(disconnect.status===409,'cannot disconnect live stop credential');check((await post({action:'activate',id:e.id,expectedVersion:e.version})).status===409&&posts===3,'no double activation');
await flags.setFeatureFlag(owner,{flag:'meta_ads_execution',enabled:false},{id:owner,email:null});result=await post({action:'stop',id:e.id,expectedVersion:e.version});check(result.status===200&&result.body.records[0].state==='stopped','flagOFF stop '+JSON.stringify(result));e=result.body.records[0];await assert.rejects(()=>reservation.releaseMetaBudget(owner,owner,c,{id:r.id,expectedVersion:r.version}));passed++;
spend='120';result=await post({action:'settle',id:e.id,expectedVersion:e.version,settledSpend:119,billingFinalConfirmed:true});check(result.status===409,'underreported billing rejected');result=await post({action:'settle',id:e.id,expectedVersion:e.version,settledSpend:120,billingFinalConfirmed:true});check(result.status===200&&result.body.records[0].state==='settled','settled after stopped/spend');await reservation.releaseMetaBudget(owner,owner,c,{id:r.id,expectedVersion:r.version});passed++;
await write('meta_ads_reservation',r.id,r,'c');
await flags.setFeatureFlag(owner,{flag:'meta_ads_execution',enabled:true},{id:owner,email:null});
const approved={...e,state:'approved',version:e.version+1,pending:null,maySpend:false,totalSpend:0,dailySpend:0};spend='0';
await write('meta_ads_execution',e.id,{...approved,activationDeadline:new Date(Date.now()-1000).toISOString()},'c');check((await post({action:'activate',id:e.id,expectedVersion:approved.version})).status===409,'expired activation deadline');
await write('meta_ads_execution',e.id,approved,'c');failAt=posts+2;result=await post({action:'activate',id:e.id,expectedVersion:approved.version});check(result.status===200&&result.body.records[0].state==='unknown','partial timeout durable unknown');const postCount=posts;e=result.body.records[0];check((await post({action:'activate',id:e.id,expectedVersion:e.version})).status===409&&posts===postCount,'unknown never reactivates');
const credential=await server.readRecord(owner,'channel_credential','meta_ads_write:b');await write('channel_credential','meta_ads_write:b',{...credential,version:2,updatedAt:new Date().toISOString()});await flags.setFeatureFlag(owner,{flag:'meta_ads_execution',enabled:false},{id:owner,email:null});
await execution.advanceMetaExecutionWork(owner);e=await server.readRecord(owner,'meta_ads_execution',e.id);check(e.state==='stopped','worker flagOFF token rotation recovery');
await write('meta_ads_execution',e.id,{...e,state:'active',maySpend:true,updatedAt:'2000-01-01T00:00:00Z'},'c');const old=remote['203'];delete remote['203'];await execution.advanceMetaExecutionWork(owner);e=await server.readRecord(owner,'meta_ads_execution',e.id);check(remote[scope.campaignId].configured_status==='PAUSED'&&e.state==='unknown','missing child cannot block parent pause');remote['203']=old;
await write('meta_ads_execution','bad',{...e,id:'bad',scope:{...e.scope,accountId:'999'},updatedAt:'1990-01-01T00:00:00Z'},'c');
sql.prepare("UPDATE records SET updated_at='1990-01-01' WHERE kind='meta_ads_execution' AND id=?").run(owner+':meta_ads_execution:bad');const failed=await execution.advanceMetaExecutionWork(owner);check(failed.status==='retry','failed monitor reports retry');check((await server.readRecord(owner,'meta_ads_execution','bad')).updatedAt!=='1990-01-01T00:00:00Z','failed monitor rotates queue age');
console.log(JSON.stringify({passed}));
