import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
const {load,env,sql}=testRuntime(async()=>{throw new Error('Budget review must not call an external provider')});
const server=await load('lib/server.ts'),route=await load('app/api/meta-ads/budget/route.ts'),creativeRoute=await load('app/api/meta-ads/creative/route.ts'),creativeLib=await load('lib/meta-creative-review.ts'),planLib=await load('lib/meta-ads.ts'),budget=await load('lib/meta-budget-review.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};const owner='paused-route',headers={'oai-authenticated-user-id':owner,origin:'https://agency.test'},write=(kind,id,data,parent)=>server.recordStatement(owner,kind,id,data,parent).run();await write('brand','b',{id:'b',name:'Synthetic brand',color:'#112233'});await write('store','s',{id:'s',brandId:'b',version:1,status:'active'},'b');const fact={id:'fact',brandId:'b',key:'price',value:'10,000원',status:'confirmed',source:'Synthetic source',verifiedAt:'2026-01-01T00:00:00Z',validUntil:'2100-01-01T00:00:00Z',version:1,updatedAt:'2026-01-01T00:00:00Z'};await write('brand_fact','fact',fact,'b');await write('channel_credential','meta_ads:b',{channel:'meta_ads',brandId:'b',accountId:'123',readEnabled:true,version:1});
async function setup(id,review=true){const c={id,brandId:'b',storeId:'s',title:'Synthetic campaign',version:1,status:'draft'};await write('campaign',id,c);await write('meta_ads_plan',id,{id,campaignId:id,brandId:'b',campaignVersion:1,version:1,input:{...planLib.emptyMetaPlan(),product:'Synthetic product',landingUrl:'https://example.com/product',storeStack:'Manual import',accountLabel:'Synthetic account',startAt:new Date(Date.now()+86400000).toISOString(),endAt:new Date(Date.now()+8*86400000).toISOString(),attributionWindow:'7d click',stopRule:'Owner stop',price:10000,unitCost:3000,variableCost:200,totalBudget:10000,dailyTarget:1000,lossLimit:3000,safetyReserve:1000,taxBasis:'included',checks:Object.fromEntries(Object.keys(planLib.metaChecks).map(k=>[k,true]))}},id);await write('execution_creative','creative-'+id,{id:'creative-'+id,campaignId:id,brandId:'b',storeId:'s',campaignVersion:1,version:1,factRefs:[{id:'fact',version:1}],caption:'가격: 10,000원',pngHash:'a'.repeat(64),objectKey:'mocked.png'},id);await write('store_experiment','exp-'+id,{id:'exp-'+id,storeId:'s',brandId:'b',campaignId:id,title:'Synthetic experiment',version:1,status:'draft',hypothesis:'Synthetic hypothesis',control:'A',treatment:'B',measurement:'Ledger',target:20},'s');if(review){const r=await creativeRoute.POST(new Request('https://agency.test/api/meta-ads/creative',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({action:'review',campaignId:id,campaignVersion:1,planVersion:1,expectedVersion:0,warningsAcknowledged:true,input:{...creativeLib.emptyMetaCreative(),creativeId:'creative-'+id,experimentId:'exp-'+id,title:'Synthetic',hook:'상품 구성 확인',body:'10,000원',cta:'구성 확인',rightsEvidence:'자체 제작',reviewNote:'랜딩 확인',rightsConfirmed:true,landingConfirmed:true}})}));assert.equal(r.status,200)}return c}

await setup('c');
const res=async r=>({status:r.status,body:await r.json()}),get=(h=headers,id='c')=>route.GET(new Request('https://agency.test/api/meta-ads/budget?campaignId='+id,{headers:h})).then(res);
const post=(b={},h=headers)=>route.POST(new Request('https://agency.test/api/meta-ads/budget',{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',action:'review',confirmed:true,note:'Synthetic budget rationale',...b})})).then(res);
check((await get({})).status===401,'anonymous');check((await get({'oai-authenticated-user-id':'other'})).status===404,'workspace isolation');check((await post({}, {...headers,origin:'https://evil.test'})).status===403,'CSRF');
let v=(await get()).body;check(v.issues.length===0&&v.scope.allocatable===9000&&!v.maySpend,'ready budget never grants spending');
check((await post({expectedVersion:0,expectedDigest:v.digest,confirmed:false})).status===400,'confirmation required');check((await post({expectedVersion:0,expectedDigest:'stale'})).status===409,'stale digest');check((await post({expectedVersion:0,expectedDigest:v.digest,note:''})).status===400,'rationale required');
let r=await post({expectedVersion:0,expectedDigest:v.digest});check(r.status===200&&r.body.current&&r.body.status==='reviewed','review exact current scope');check(r.body.records[0].actorId===owner&&r.body.records[0].scope.creativeHash==='a'.repeat(64),'actor and exact creative proof');check(r.body.records[0].purpose==='plan_scope_only'&&r.body.records[0].maySpend===false,'not reusable spending approval');check((await post({expectedVersion:0,expectedDigest:v.digest})).status===409,'version CAS');r=await post({expectedVersion:1,expectedDigest:v.digest});check(r.body.duplicate&&r.body.records.length===1,'unchanged review idempotent');
const plan=await server.readRecord(owner,'meta_ads_plan','c');await write('meta_ads_plan','c',{...plan,version:2,input:{...plan.input,totalBudget:11000}},'c');v=(await get()).body;check(v.status==='stale'&&!v.current,'plan mutation invalidates review');check(v.records[0].scope.totalBudget===10000,'historical budget immutable');check((await post({expectedVersion:1,expectedDigest:v.digest})).status===409,'creative review invalidated by plan edit');r=await post({action:'revoke',expectedVersion:1});check(r.status===200&&r.body.status==='revoked'&&r.body.records[0].scope.totalBudget===10000,'revoke old exact scope despite changed plan');check((await post({action:'revoke',expectedVersion:2})).status===409,'cannot revoke twice');
await server.database().prepare("DELETE FROM records WHERE owner=? AND kind='meta_ads_creative_review' AND parent_id=?").bind(owner,'c').run();await setup('c');v=(await get()).body;r=await post({expectedVersion:2,expectedDigest:v.digest});check(r.body.current&&r.body.version===3,'new review after explicit revocation');
const conn=await server.readRecord(owner,'channel_credential','meta_ads:b');await write('channel_credential','meta_ads:b',{...conn,updatedAt:'2099-01-01T00:00:00Z'});v=(await get()).body;check(v.status==='stale','reconnect timestamp changes even when version reused');
await setup('no-review',false);check((await get(headers,'no-review')).body.issues.some(x=>x.includes('소재')),'unreviewed creative blocked');
const original=await server.readRecord(owner,'meta_ads_plan','c'),now=Date.now();const evaluate=input=>budget.metaBudgetEnvelope({...original,input:{...original.input,...input}},now);
check(evaluate({safetyReserve:10000}).issues.length>0,'no funds after reserve');check(evaluate({dailyTarget:9500}).issues.length>0,'daily target exceeds deployable');check(evaluate({lossLimit:9500}).issues.length>0,'loss exceeds deployable');check(evaluate({startAt:new Date(now).toISOString()}).issues.length>0,'past or present start');check(evaluate({endAt:new Date(now+33*86400000).toISOString()}).issues.length>0,'pilot over 31 days');check(evaluate({startAt:'invalid'}).issues.length>0,'invalid date');check(evaluate({endAt:original.input.startAt}).issues.length>0,'empty interval');
await write('meta_ads_plan','c',{...original,input:{...original.input,startAt:new Date(now-1000).toISOString()}},'c');check((await get()).body.issues.some(x=>x.includes('시작 시각')),'expired review cannot authorize later');
const c=await server.readRecord(owner,'campaign','c');await write('campaign','c',{...c,status:'archived'});check((await get()).body.issues.some(x=>x.includes('보관')),'archived campaign blocks review');check((await post({action:'revoke',expectedVersion:3})).status===200,'archived review remains revocable');
env.AUTH_MODE='email';env.AUTH_ORIGIN='https://agency.test';sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run('workspace-owner','owner@test.invalid',owner,'admin','active',1);
for(const role of ['admin','member']){const token=createHash('sha256').update(role).digest('hex');sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run(role,role+'@test.invalid',owner,role,'active',1000);sql.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?)').run(createHash('sha256').update(token).digest('hex'),role,Date.now()+60000,Date.now());const h={cookie:'__Host-collective_session='+token,origin:'https://agency.test'};check((await post({},h)).status===403,'owner only '+role);check((await get(h)).body.canEdit===false,'read only '+role);}
check((await post({action:'activate'})).status!==200,'no activation action');console.log(JSON.stringify({passed}));
