// Mocked auth + SQLite + Meta GET responses. No live token, spend or customer event.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
let calls=[],mode='normal';
const row={date_start:'2026-09-01',date_stop:'2026-09-01',account_id:'123',campaign_id:'456',ad_id:'789',spend:'12.34',impressions:'100',clicks:'4',actions:[{action_type:'omni_purchase',value:'1'}],action_values:[{action_type:'omni_purchase',value:'5000'}]};
const {load,env,sql}=testRuntime(async(url,opts)=>{
 calls.push({url,opts});const u=new URL(url);assert.equal(u.origin,'https://graph.facebook.com');assert.equal(opts.method,'GET');assert.equal(opts.redirect,'manual');assert.equal(u.searchParams.has('access_token'),false);assert.equal(opts.headers.Authorization,'Bearer synthetic_token_123');
 if(mode==='timeout')throw new Error('secret synthetic_token_123');
 if(mode==='auth')return Response.json({error:{code:190,message:'synthetic_token_123'}},{status:400});
 if(mode==='rate')return Response.json({error:{code:4,message:'synthetic_token_123'}},{status:400});
 if(mode==='permission')return Response.json({error:{code:200}},{status:400});
 if(u.pathname.endsWith('/act_123'))return Response.json({account_id:'123',currency:mode==='currency'?'USD':'KRW',timezone_name:'Asia/Seoul',account_status:1});
 if(u.pathname.endsWith('/act_123/insights'))return Response.json({data:[]});
 if(u.pathname.endsWith('/456'))return Response.json({id:'456',account_id:mode==='cross'?'999':'123'});
 assert.ok(u.pathname.endsWith('/456/insights'));
 if(mode==='empty')return Response.json({data:[]});
 if(mode==='malformed')return Response.json({data:[{...row,spend:'NaN'}]});
 if(mode==='duplicate')return Response.json({data:[row,row]});
 if(mode==='partial'&&u.searchParams.has('after'))return Response.json({error:{code:4}},{status:429});
 if(['pages','loop','partial'].includes(mode)&&(!u.searchParams.has('after')||mode==='loop'))return Response.json({data:[row],paging:{next:'https://evil.test/?access_token=secret',cursors:{after:'safe_cursor'}}});
 return Response.json({data:[mode==='pages'?{...row,ad_id:'790'}:row]});
});
const lib=await load('lib/meta-insights.ts'),server=await load('lib/server.ts'),route=await load('app/api/meta-ads/insights/route.ts'),provider=await load('lib/meta-insights-provider.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='meta-read-owner',campaign={id:'campaign',brandId:'brand',version:1,status:'draft'};
await server.recordStatement(owner,'brand','brand',{id:'brand'}).run();await server.recordStatement(owner,'campaign',campaign.id,campaign).run();
const hdr={'oai-authenticated-user-id':owner,origin:'https://agency.test'},base={action:'import',campaignId:'campaign',campaignVersion:1,expectedVersion:0,accountId:'123',externalCampaignId:'456',since:'2026-09-01',until:'2026-09-02',attribution:'7d_click_1d_view',currency:'KRW',timeZone:'Asia/Seoul',csv:lib.metaInsightTemplate+'2026-09-01,123,456,789,12.34,100,4,,\n'};
const result=async r=>({status:r.status,body:await r.json()});
const get=(headers=hdr)=>route.GET(new Request('https://agency.test/api/meta-ads/insights?campaignId=campaign',{headers})).then(result);
const post=(over={},headers=hdr)=>route.POST(new Request('https://agency.test/api/meta-ads/insights',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({...base,...over})})).then(result);
check((await get({})).status===401,'anonymous');check((await get({'oai-authenticated-user-id':'other'})).status===404,'workspace isolation');check((await post({}, {...hdr,origin:'https://evil.test'})).status===403,'CSRF');
check((await post({action:'sync'})).status===409&&calls.length===0,'default off');
let r=await post();check(r.status===200&&r.body.summary.spendMinor===1234,'integer minor money');check(r.body.summary.purchases===null&&r.body.summary.purchaseValueMinor===null&&r.body.summary.actualRevenue===null,'missing is unknown');
check((await post()).body.unchanged===true,'duplicate retry idempotent');check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='event'").get().n===1,'no duplicate audit');
for(const over of [{since:'2026-02-30'},{until:'2026-10-10'},{accountId:'999'},{currency:'USD'},{attribution:'unknown'},{csv:base.csv.replace('12.34','-1')},{csv:base.csv.replace('12.34','12.345')},{csv:base.csv+base.csv.split('\n')[1]+'\n'},{csv:base.csv.replace('date,','email,')},{csv:base.csv.replace('789','not-an-id')},{csv:base.csv.replace('2026-09-01,','2026-08-01,')},{csv:base.csv.replace('100,4','100.2,4')}])check((await post({...over,expectedVersion:1})).status===400,'invalid import '+JSON.stringify(over));
check(calls.length===0,'imports no external calls');
check((await post({expectedVersion:0,csv:base.csv.replace('12.34','20')})).status===409,'CAS conflict');
check((await post({action:'activate'})).status===400,'no activation action');
const conn={action:'connect',connectionVersion:0,token:'synthetic_token_123',readEnabled:true};
check((await post({...conn,readEnabled:false})).status===400&&calls.length===0,'explicit read switch');
const encryption=env.AGENCY_ENCRYPTION_KEY;env.AGENCY_ENCRYPTION_KEY='';check((await post(conn)).status===503&&calls.length===0,'no token transmission without encryption');env.AGENCY_ENCRYPTION_KEY=encryption;
r=await post(conn);check(r.status===200&&r.body.connection.accountId==='123','verified connection');check(!JSON.stringify(r.body).includes('synthetic_token'),'response redacts token');
const stored=await server.readRecord(owner,'channel_credential','meta_ads:brand');check(!JSON.stringify(stored).includes('synthetic_token'),'encrypted at rest');
check((await post({...conn,connectionVersion:0})).status===409,'connection CAS');
await server.recordStatement(owner,'brand','otherbrand',{id:'otherbrand'}).run();await server.recordStatement(owner,'campaign','othercampaign',{...campaign,id:'othercampaign',brandId:'otherbrand'}).run();
check((await post({...conn,campaignId:'othercampaign'})).status===409,'account cannot be reused across brands');check((await post({action:'sync',campaignId:'othercampaign'})).status===409,'no brand fallback');
r=await post({action:'sync',expectedVersion:1});check(r.status===200&&r.body.report.source==='meta_api'&&r.body.summary.purchaseValueMinor===500000,'API data maps only omni purchase');
const good=JSON.stringify(r.body.report);const sync={action:'sync',expectedVersion:2};
for(const m of ['auth','rate','permission','timeout','currency','cross','malformed','duplicate','partial']){mode=m;r=await post(sync);check(r.status>=400,'provider failure '+m);check(!JSON.stringify(r).includes('synthetic_token'),'safe provider failure '+m);check(JSON.stringify((await get()).body.report)===good,'previous snapshot preserved '+m);check((await get()).body.syncState.status==='failed','durable failure '+m)}
mode='normal';r=await post(sync);check(r.status===200,'recover after failure');check(r.body.syncState.status==='succeeded'&&r.body.syncState.errorCode===null&&r.body.syncState.lastSucceededAt===r.body.syncState.finishedAt,'durable recovery');check(r.body.report.version===3&&r.body.report.digest===JSON.parse(good).digest,'same values reverified with fresh collection version');check(!JSON.stringify(sql.prepare("SELECT data FROM records WHERE kind='meta_ads_sync_state'").all()).includes('synthetic_token'),'no secret in status');
mode='pages';const report=await provider.collectMetaRead('synthetic_token_123',base);check(report.rows.length===2,'bounded pagination fixed host');mode='loop';await assert.rejects(()=>provider.collectMetaRead('synthetic_token_123',base));passed++;mode='empty';const empty=await provider.collectMetaRead('synthetic_token_123',base);check(empty.rows.length===0&&lib.summarizeMetaInsights(empty.rows).purchases===null,'empty is not fabricated conversion');mode='normal';
env.AUTH_MODE='email';env.AUTH_ORIGIN='https://agency.test';const session=createHash('sha256').update('member').digest('hex');sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run('member','member@test.invalid',owner,'member','active',1000);sql.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?)').run(createHash('sha256').update(session).digest('hex'),'member',Date.now()+60000,Date.now());const member={cookie:'__Host-collective_session='+session,origin:'https://agency.test'};
check((await get(member)).body.canEdit===false,'member can read');check((await post(conn,member)).status===403,'member cannot connect');env.AUTH_MODE='legacy';
r=await post({action:'disconnect',connectionVersion:1});check(r.status===200&&r.body.connection===null,'disconnect');check((await post({action:'sync',expectedVersion:2})).status===409,'disconnect disables external reads');
check((await get()).body.report.version===3,'disconnect preserves report');
await server.recordStatement(owner,'campaign','campaign',{...campaign,version:2}).run();check((await get()).body.stale,'campaign change shows stale');check((await post()).status===409,'stale campaign blocked');
console.log(JSON.stringify({passed}));
