// Real server route + mocked Graph, synthetic records; no external requests.
import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
let posts=0,remote={},spend='0',offset=1,failAt=0,loseBudgetResponse=false,injectCASConflict=false;
const {load,sql}=testRuntime(async(url,opts)=>{const path=new URL(url).pathname,id=path.split('/').at(-1);if(opts.method==='POST'){posts++;if(posts===failAt)throw new Error('timeout');const params=new URLSearchParams(opts.body);remote[id]={...remote[id],...(params.has('status')?{configured_status:params.get('status')}:{daily_budget:params.get('daily_budget')})};if(params.has('daily_budget')&&loseBudgetResponse){loseBudgetResponse=false;throw Error('accepted then response lost')}return Response.json({success:true})}if(id==='me')return Response.json({currency:{user_currency:'KRW',currency_offset:offset}});if(id==='permissions')return Response.json({data:[{permission:'ads_management',status:'granted'}]});if(id==='act_123')return Response.json({account_id:'123',currency:'KRW',timezone_name:'Asia/Seoul',account_status:1});if(id==='adsets')return Response.json({data:[{id:'201'}]});if(id==='ads')return Response.json({data:[{id:'203'}]});if(id==='insights')return Response.json({data:[{account_id:'123',adset_id:'201',account_currency:'KRW',spend}]});return Response.json(remote[id]??{})},{beforeRun:statement=>{if(injectCASConflict&&statement.query.startsWith('INSERT INTO records(id,owner,kind,parent_id,data,updated_at) SELECT')&&statement.values.includes('meta_ads_execution')){injectCASConflict=false;sql.prepare("UPDATE records SET data=json_set(data,'$.version',999) WHERE kind='meta_ads_execution'").run()}}});
const server=await load('lib/server.ts'),creativeRoute=await load('app/api/meta-ads/creative/route.ts'),creativeLib=await load('lib/meta-creative-review.ts'),planLib=await load('lib/meta-ads.ts'),flags=await load('lib/feature-flags.ts'),digest=await load('lib/storefront-orders.ts'),creativeServer=await load('lib/meta-creative-server.ts'),crypto=await load('lib/credential-crypto-server.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};const owner='bundle-route',headers={'oai-authenticated-user-id':owner,origin:'https://agency.test'},write=(kind,id,data,parent)=>server.recordStatement(owner,kind,id,data,parent).run();await write('brand','b',{id:'b',name:'Synthetic brand',color:'#112233'});await write('store','s',{id:'s',brandId:'b',version:1,status:'active'},'b');const fact={id:'fact',brandId:'b',key:'price',value:'10,000원',status:'confirmed',source:'Synthetic source',verifiedAt:'2026-01-01T00:00:00Z',validUntil:'2100-01-01T00:00:00Z',version:1,updatedAt:'2026-01-01T00:00:00Z'};await write('brand_fact','fact',fact,'b');await write('channel_credential','meta_ads:b',{channel:'meta_ads',brandId:'b',accountId:'123',readEnabled:true,version:1});
async function setup(id,review=true){const c={id,brandId:'b',storeId:'s',title:'Synthetic campaign',version:1,status:'draft'};await write('campaign',id,c);await write('meta_ads_plan',id,{id,campaignId:id,brandId:'b',campaignVersion:1,version:1,input:{...planLib.emptyMetaPlan(),product:'Synthetic product',landingUrl:'https://example.com/product',storeStack:'Manual import',accountLabel:'Synthetic account',startAt:new Date(Date.now()+3600000).toISOString(),endAt:new Date(Date.now()+86400000).toISOString(),attributionWindow:'7d click',stopRule:'Owner stop',price:10000,unitCost:3000,variableCost:200,totalBudget:10000,dailyTarget:1000,lossLimit:3000,safetyReserve:1000,taxBasis:'included',checks:Object.fromEntries(Object.keys(planLib.metaChecks).map(k=>[k,true]))}},id);await write('execution_creative','creative-'+id,{id:'creative-'+id,campaignId:id,brandId:'b',storeId:'s',campaignVersion:1,version:1,factRefs:[{id:'fact',version:1}],caption:'가격: 10,000원',pngHash:'a'.repeat(64),objectKey:'mocked.png'},id);await write('store_experiment','exp-'+id,{id:'exp-'+id,storeId:'s',brandId:'b',campaignId:id,title:'Synthetic experiment',version:1,status:'draft',hypothesis:'Synthetic hypothesis',control:'A',treatment:'B',measurement:'Ledger',target:20},'s');if(review){const r=await creativeRoute.POST(new Request('https://agency.test/api/meta-ads/creative',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({action:'review',campaignId:id,campaignVersion:1,planVersion:1,expectedVersion:0,warningsAcknowledged:true,input:{...creativeLib.emptyMetaCreative(),creativeId:'creative-'+id,experimentId:'exp-'+id,title:'Synthetic',hook:'상품 구성 확인',body:'10,000원',cta:'구성 확인',rightsEvidence:'자체 제작',reviewNote:'랜딩 확인',rightsConfirmed:true,landingConfirmed:true}})}));assert.equal(r.status,200)}return c}


await write('channel_credential','meta_ads_write:b',{channel:'meta_ads_write',brandId:'b',accountId:'123',permission:'ads_management',version:1,updatedAt:'2026-09-28T00:00:00Z',secret:await crypto.sealRecordSecret(owner,'channel_credential','meta_ads_write:b','synthetic_create_token')});
let parentIndex=1000;async function ready(id){await setup(id);const c=await server.readRecord(owner,'campaign',id),x=await creativeServer.metaCreativeContext(owner,c),review=creativeServer.viewMetaCreative(c,x,false),parentId=await digest.storefrontDigest({id}),externalId=String(++parentIndex),imageId=await digest.storefrontDigest({image:id});await write('meta_ads_write_operation',parentId,{id:parentId,campaignId:id,brandId:'b',campaignVersion:1,evidenceFingerprint:await digest.storefrontDigest({campaignVersion:1,plan:x.plan,review:review.saved,connectionVersion:1,accountId:'123'}),draft:{accountId:'123'},receipt:{accountId:'123',state:'paused_verified',externalId},version:1},id);remote[externalId]={id:externalId,name:'Parent [Collective '+parentId+']',account_id:'123',objective:'OUTCOME_SALES',configured_status:'PAUSED',effective_status:'PAUSED'};await write('meta_ads_image_upload',imageId,{id:imageId,campaignId:id,brandId:'b',creativeId:'creative-'+id,creativeVersion:1,pngHash:'a'.repeat(64),accountId:'123',state:'uploaded',receipt:{sourceBytesVerified:true,metaImageHash:'f'.repeat(32)}},id);return {operationId:parentId,imageUploadReceiptId:imageId,pageId:'50',pixelId:'60',graphDailyBudget:'100000',budgetUnitEvidence:'수동 검토',ageMin:18,ageMax:65,callToActionType:'LEARN_MORE'}}
const pausedRoute=await load('app/api/meta-ads/paused/route.ts'),executionRoute=await load('app/api/meta-ads/execution/route.ts'),bundle=await load('lib/meta-ad-bundle-server.ts'),reservation=await load('lib/meta-reservation-server.ts'),execution=await load('lib/meta-execution-server.ts');
await flags.setFeatureFlag(owner,{flag:'meta_ads_bundle',enabled:true},{id:owner,email:null});
const input={...await ready('c'),graphDailyBudget:'1000',dailyBudgetKrw:1000,country:'KR',expectedMetaImageHash:'f'.repeat(32),adsetId:'201',creativeId:'202',adId:'203'},c=await server.readRecord(owner,'campaign','c'),x=await bundle.metaAdBundleContext(owner,c),scope=bundle.metaAdBundleScope(c,x,input),scopeDigest=await digest.storefrontDigest({scope,evidenceFingerprint:x.evidenceFingerprint}),at=new Date().toISOString();
await write('meta_ads_bundle','c',{id:'c',campaignId:'c',brandId:'b',campaignVersion:1,version:1,input,evidenceFingerprint:x.evidenceFingerprint,status:'verified',verifiedScope:{...scope,scopeDigest,verifiedAt:at},reviewedBy:owner,reviewedAt:at,updatedAt:at,updatedBy:owner},'c');
remote['201']={id:'201',account_id:'123',campaign_id:scope.campaignId,configured_status:'PAUSED',daily_budget:'1000',billing_event:'IMPRESSIONS',optimization_goal:'OFFSITE_CONVERSIONS',destination_type:'WEBSITE',start_time:scope.startAt,end_time:scope.endAt,promoted_object:{pixel_id:scope.pixelId,custom_event_type:'PURCHASE'},targeting:{geo_locations:{countries:['KR']},age_min:18,age_max:65}};
remote['202']={id:'202',account_id:'123',object_story_spec:{page_id:scope.pageId,link_data:{link:scope.landingUrl,name:scope.hook,message:scope.body,image_hash:scope.expectedMetaImageHash,call_to_action:{type:scope.callToActionType,value:{link:scope.landingUrl}}}}};remote['203']={id:'203',account_id:'123',campaign_id:scope.campaignId,adset_id:'201',configured_status:'PAUSED',creative:{id:'202'}};
await write('worker_credential','current',{hash:'workerhash',createdAt:at});await write('worker_state','current',{lastSeen:at,tokenHash:'workerhash'});
await reservation.reserveMetaBudget(owner,owner,c,{expectedScopeDigest:scopeDigest,amount:5000,note:'Synthetic reservation'});const r=(await reservation.reservationRecords(owner))[0];
const post=async(b,h=headers)=>{const response=await executionRoute.POST(new Request('https://agency.test/api/meta-ads/execution',{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,confirmed:true,...b})}));return {status:response.status,body:await response.json()}};
const approval={action:'approve',reservationId:r.id,reservationVersion:r.version,expectedScopeDigest:scopeDigest,maxSpend:5000,expiresAt:scope.endAt,emergencyStopMandate:true};
check((await post(approval,{})).status===401,'anonymous');check((await post(approval,{...headers,origin:'https://evil.test'})).status===403,'CSRF');check((await post(approval,{'oai-authenticated-user-id':'other',origin:headers.origin})).status===404,'owner isolation');check((await post(approval)).status===409&&posts===0,'defaultOFF');
await flags.setFeatureFlag(owner,{flag:'meta_ads_execution',enabled:true},{id:owner,email:null});let result=await post(approval);check(result.status===200,'approve '+JSON.stringify(result));let e=result.body.records[0];check(e.state==='approved'&&posts===0,'approval has zero POST');check((await post(approval)).status===409,'duplicate reservation approval');
await assert.rejects(()=>reservation.releaseMetaBudget(owner,owner,c,{id:r.id,expectedVersion:r.version}));passed++;
result=await post({action:'activate',id:e.id,expectedVersion:e.version});check(result.status===200&&result.body.records[0].state==='active','activation '+JSON.stringify(result));e=result.body.records[0];check(posts===3,'three hierarchy POSTs');const disconnect=await pausedRoute.POST(new Request('https://agency.test/api/meta-ads/paused',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({action:'disconnect',campaignId:'c',connectionVersion:1})}));check(disconnect.status===409,'cannot disconnect live stop credential');check((await post({action:'activate',id:e.id,expectedVersion:e.version})).status===409&&posts===3,'no double activation');

const gr=await load('app/api/growth/route.ts'),ar=await load('app/api/growth/authority/route.ts'),op=await load('app/api/growth/operations/route.ts'),expRoute=await load('app/api/growth/expansion/route.ts');
const call=async(route,body)=>{const res=await route.POST(new Request('https://agency.test/api/x',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({campaignId:'c',campaignVersion:1,expectedVersion:0,requestId:globalThis.crypto.randomUUID(),...body})}));return {status:res.status,body:await res.json()}};
const before=new Date(Date.now()-86400000).toISOString(),after=new Date(Date.now()+86400000).toISOString();
await call(ar,{action:'save_authority',id:'authority',sign:true,input:{accountId:'123',channel:'meta',status:'active',maxTier:'T3',allowedActions:['spend','publish'],startsAt:before,expiresAt:after,periodStart:before,periodEnd:after,totalCap:10000,dayCap:10000,weekCap:10000,lossCap:10000}});
await call(gr,{action:'save_signal',id:'signal',input:{title:'근거',sourceUrl:'https://example.com/m',observedAt:before,expiresAt:'2099-01-01',sourceType:'market',summary:'관측',sampleSize:null}});
await call(gr,{action:'save_need',id:'need',input:{title:'니즈',situation:'상황',desiredOutcome:'결과',alternative:'대안',barrier:'장애',counterEvidence:'반례',signalIds:['signal'],deadline:'2099-01-01',nextAction:'검증',assignee:'담당'}});
await call(gr,{action:'save_catalog',id:'catalog',input:{sku:'SKU',title:'상품',price:100,unitCost:20,variableCost:10,stock:0,stockUnit:'piece',currency:'KRW',taxBasis:'included',fulfillment:'배송',refunds:'반품',rightsConfirmed:true,factIds:['fact'],validUntil:'2099-01-01'}});
await call(gr,{action:'save_offer',id:'offer',input:{title:'오퍼',catalogId:'catalog',catalogVersion:1,needId:'need',price:100,quantity:1,landingUrl:scope.landingUrl,purchaseReason:'이유',priceApproved:true}});
await call(gr,{action:'save_mission',id:'mission',input:{title:'미션',offerId:'offer',offerVersion:1,assignee:'담당',deadline:'2099-01-01',nextAction:'판매',channel:'meta',budget:5000,lossLimit:3000,stopRule:'한도',fulfillmentOwner:'배송'}});
await call(op,{action:'create_inventory',input:{sku:'SKU',locationId:'s',unit:'piece',onHand:50},observedAt:before,evidenceRef:'stock-evidence'});
const refs=[{kind:'offer',id:'offer',version:1},{kind:'manual',id:'meta_execution:'+e.id,version:1}];
const experimentServer=await load('lib/growth-experiment-server.ts');
const experimentInput={title:'합성 확증',mode:'confirm',aa:false,hypothesis:'구매 증가',missionId:'mission',missionVersion:1,offerId:'offer',offerVersion:1,channel:'meta',interventionRefs:refs,minEffect:0.05,metric:'paid_orders',assignmentUnit:'pseudonymous_visitor',treatmentShare:0.5,lowerBound:0,upperBound:1,minSamplePerArm:30,startAt:new Date(Date.now()-86400000).toISOString(),endAt:new Date(Date.now()-3600000).toISOString(),maturityDays:0,stopRule:'한도',intervention:'안내'};
const designDigest=await digest.storefrontDigest({id:'gx',input:experimentInput});
await write('growth_experiment','gx',{id:'gx',brandId:'b',campaignId:'c',storeId:'s',version:2,status:'registered',input:experimentInput,registration:{digest:designDigest,at:before,refs}},'c');
for(const arm of ['control','treatment'])for(let i=0;i<100;i++){
 const id=arm+'-'+i,orderId='order-'+id;
 if(arm==='treatment')await write('store_order',orderId,{id:orderId,storeId:'s',campaignId:'c',version:1,orderDate:new Date(Date.now()-7200000).toISOString().slice(0,10),status:'paid',paidAmount:100,refundAmount:0,costs:{unitCost:10}},'s');
 await write('growth_experiment_unit',id,{id,designId:'gx',brandId:'b',campaignId:'c',version:1,unitHash:id,arm,observation:{exposed:true,trackingComplete:true,contaminated:false,orderIds:arm==='treatment'?[orderId]:[]}},'c');
}
const actualAnalysis=await experimentServer.saveGrowthExperiment({owner,id:owner,role:'owner'},c,{action:'analyse',id:'gx',campaignVersion:1,requestId:globalThis.crypto.randomUUID()});
check(actualAnalysis.status==='supported','canonical server analysis supports synthetic effect');
const originalOrder=await server.readRecord(owner,'store_order','order-treatment-0'),originalUnit=await server.readRecord(owner,'growth_experiment_unit','treatment-0');
const drifts=[['refund','store_order',originalOrder,{...originalOrder,version:2,refundAmount:100}],['cost','store_order',originalOrder,{...originalOrder,version:2,costs:{unitCost:90}}],['withdrawal','growth_experiment_unit',originalUnit,{...originalUnit,version:2,observation:null}]];
result=await call(expRoute,{action:'propose',id:'scale',input:{missionId:'mission',missionVersion:1,experimentId:'gx',analysisNumber:1,nextBudget:6000,addQuantity:1,rationale:'합성 확증'}});check(result.status===200,'expansion proposed '+JSON.stringify(result));
const approve={action:'approve_reserve',id:'scale',expectedVersion:1,authorityId:'authority',authorityVersion:1,metaBudgetApproval:{executionId:e.id,executionVersion:e.version,nextDailyBudgetKrw:1200,confirmed:true}};
for(const [label,kind,original,changed] of drifts){
 await write(kind,original.id,changed,kind==='store_order'?'s':'c');const postCount=posts;
 const blocked=await call(expRoute,approve);check(blocked.status===409&&posts===postCount&&!(await server.listRecords(owner,'meta_budget_amendment')).length,label+' before approval blocks reservation');
 await write(kind,original.id,original,kind==='store_order'?'s':'c');
}
result=await call(expRoute,{...approve,metaBudgetApproval:{...approve.metaBudgetApproval,nextDailyBudgetKrw:6000}});check(result.status===409,'total cannot be mistaken for daily');
injectCASConflict=true;result=await call(expRoute,approve);check(result.status===500&&!(await server.listRecords(owner,'meta_budget_amendment')).length&&!(await server.listRecords(owner,'growth_commitment')).length,'CAS mismatch rolls back amendment and funding reservation');
const beforePosts=posts,concurrent=await Promise.all([call(expRoute,approve),call(expRoute,approve)]);result=concurrent.find(x=>x.status===200);check(!!result&&concurrent.filter(x=>x.status===409).length===1,'concurrent expansion approval reserves only once');check(result.status===200&&posts===beforePosts,'approval saves intent + reservation before provider write '+JSON.stringify(result));
const pendingExecution=await server.readRecord(owner,'meta_ads_execution',e.id);
const amendment=(await server.listRecords(owner,'meta_budget_amendment'))[0];check(amendment.increase===1000&&amendment.nextDaily===1200,'separate funding increment');
const commitment=await server.readRecord(owner,'growth_commitment','mission:scale:scale');check(commitment.providerCostRef.id===e.id,'provider expense alias exact execution');
check((await call(expRoute,approve)).status===409,'new request cannot reserve same execution twice');
for(const [label,kind,original,changed] of drifts){
 await write(kind,original.id,changed,kind==='store_order'?'s':'c');const postCount=posts;
 await execution.advanceMetaExecutionWork(owner);
 check((await server.readRecord(owner,'meta_budget_amendment',amendment.id)).state==='blocked'&&posts===postCount,label+' after approval blocks provider POST');
 await write(kind,original.id,original,kind==='store_order'?'s':'c');
 await write('meta_ads_execution',e.id,pendingExecution,'c');await write('meta_budget_amendment',amendment.id,amendment,'c');sql.prepare("DELETE FROM records WHERE kind='meta_budget_amendment_history'").run();
}
await execution.advanceMetaExecutionWork(owner);
e=await server.readRecord(owner,'meta_ads_execution',e.id);let a=await server.readRecord(owner,'meta_budget_amendment',amendment.id);
check(a.state==='applied'&&remote['201'].daily_budget==='1200'&&posts===beforePosts+1,'bounded worker one actual budget POST '+JSON.stringify(a));
check(e.scope.graphDailyBudget==='1000'&&e.maxSpend===6000&&e.dailyTarget===1200&&e.budgetAmendment.state==='applied','immutable base with effective revision');
await execution.advanceMetaExecutionWork(owner);check((await server.readRecord(owner,'meta_ads_execution',e.id)).state==='active'&&posts===beforePosts+1,'strict monitor accepts only approved effective budget');
check((await call(expRoute,{action:'reconcile',id:'scale',expectedVersion:2,commitmentVersion:1,outcome:'failed',reconciliation:{mode:'release',actualAmount:0,actualLoss:0,noExecution:true,noOutstandingObligations:true,evidenceRef:'fake',note:'false'}})).status===409,'provider reservation cannot be manually released');
// Reset synthetic state to exercise an accepted budget write whose response disappears.
await write('meta_ads_execution',e.id,pendingExecution,'c');await write('meta_budget_amendment',amendment.id,amendment,'c');sql.prepare("DELETE FROM records WHERE kind='meta_budget_amendment_history'").run();remote['201']={...remote['201'],daily_budget:'1000'};
const historyBefore=()=>sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='meta_budget_amendment_history'").get().n;
loseBudgetResponse=true;const beforeLoss=posts;await execution.advanceMetaExecutionWork(owner);a=await server.readRecord(owner,'meta_budget_amendment',amendment.id);check(a.state==='unknown'&&posts===beforeLoss+1&&remote['201'].daily_budget==='1200','accepted POST response loss is durable unknown');
await execution.advanceMetaExecutionWork(owner);a=await server.readRecord(owner,'meta_budget_amendment',amendment.id);e=await server.readRecord(owner,'meta_ads_execution',e.id);check(a.state==='applied'&&e.state==='stopped'&&posts===beforeLoss+4,'unknown stops parent hierarchy then GET-only recovery with no budget retry');
const terminalPosts=posts,terminalHistory=historyBefore();await execution.advanceMetaExecutionWork(owner);check(posts===terminalPosts&&historyBefore()===terminalHistory,'terminal recovery neither repeats writes nor consumes history');
e=await server.readRecord(owner,'meta_ads_execution',e.id);await post({action:'stop',id:e.id,expectedVersion:e.version});e=await server.readRecord(owner,'meta_ads_execution',e.id);
spend='5500';result=await post({action:'settle',id:e.id,expectedVersion:e.version,settledSpend:5500,billingFinalConfirmed:true});check(result.status===200,'final bill settles execution and alias atomically');
check((await server.readRecord(owner,'growth_commitment',commitment.id)).commitment.actualAmount===500,'additional funding allocated above original envelope');
const profit=await (await load('lib/growth-profit-server.ts')).growthProfitView({owner,id:owner,role:'owner',email:null},c,{});check(profit.marketing.known===5500,'provider bill counted once, not plus funding alias');
// Recovery must remain possible even with a full archive of terminal executions.
e=await server.readRecord(owner,'meta_ads_execution',e.id);await write('meta_ads_execution',e.id,{...e,state:'active',maySpend:true},'c');
for(let i=0;i<1001;i++)await write('meta_ads_execution','archive-'+i,{...e,id:'archive-'+i,state:'settled'},'c');
await execution.advanceMetaExecutionWork(owner);check((await server.readRecord(owner,'meta_ads_execution',e.id)).state==='stopped','archive capacity does not block safety stop');
console.log(JSON.stringify({passed}));
