import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
const {load,sql,env}=testRuntime(async()=>{throw new Error('No external calls from learning')});
const server=await load('lib/server.ts'),reports=await load('app/api/meta-ads/report/route.ts');
const route=await load('app/api/meta-ads/learning/route.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='meta-learning',h={'oai-authenticated-user-id':owner,origin:'https://agency.test'};
const c={id:'c',brandId:'b',storeId:'s',version:1,title:'Synthetic',status:'active'};
const write=(kind,id,data,parent)=>server.recordStatement(owner,kind,id,data,parent).run();
await write('brand','b',{id:'b',name:'Synthetic brand',color:'#112233'});await write('campaign','c',c);await write('store','s',{id:'s',brandId:'b',version:1,status:'active'},'b');
const request=(path,data,headers=h)=>new Request('https://agency.test/api/meta-ads/'+path,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify(data)});
const unpack=async r=>({status:r.status,body:await r.json()});
const get=(headers=h)=>route.GET(new Request('https://agency.test/api/meta-ads/learning?campaignId=c',{headers})).then(unpack);
const current=await reports.GET(new Request('https://agency.test/api/meta-ads/report?campaignId=c&since=2026-09-01&until=2026-09-02',{headers:h})).then(r=>r.json());
await reports.POST(request('report',{action:'freeze',campaignId:'c',since:'2026-09-01',until:'2026-09-02',confirmed:true,expectedVersion:0,expectedDigest:current.report.basisDigest}));
const candidate={hypothesis:'상품 설명을 바꾸면 구매 의향이 달라진다',variable:'훅',control:'상품 구성 중심',treatment:'사용 장면 중심',metric:'paid_orders',minSample:100,stopCondition:'기간 종료 후 검토',creativeId:'creative',creativeVersion:1,creativeHash:'a'.repeat(64)};
await write('execution_creative','creative',{id:'creative',brandId:'b',storeId:'s',campaignId:'c',campaignVersion:1,version:1,pngHash:'a'.repeat(64),factRefs:[],objectKey:'synthetic'},'c');
const base={campaignId:'c',action:'record',snapshotId:'c:1',expectedDigest:current.report.basisDigest,expectedVersion:0,decision:'retest',note:'근거를 더 모으기 위한 재실험',candidate,confirmed:true};
const post=(extra={},headers=h)=>route.POST(request('learning',{...base,...extra},headers)).then(unpack);
check((await get({})).status===401,'anonymous');check((await get({'oai-authenticated-user-id':'other'})).status===404,'tenant isolation');
check((await post({}, {...h,origin:'https://evil.test'})).status===403,'CSRF');
check((await post({confirmed:false})).status===400,'explicit decision confirmation');
check((await post({decision:'winner'})).status===400,'no invented winner');
check((await post({candidate:{...candidate,minSample:0}})).status===400,'positive sample');
check((await post({candidate:{...candidate,creativeId:'other'}})).status===409,'current same campaign creative');
check((await post({expectedDigest:'old'})).status===409,'source digest binding');
check((await post({snapshotId:'foreign:1'})).status===404,'snapshot isolation');
let r=await post();check(r.status===200,'record decision '+JSON.stringify(r));check(r.body.records.length===1,'one decision');
check(r.body.records[0].evidenceStatus==='insufficient'&&r.body.records[0].candidate.status==='draft','insufficient stays insufficient');
check(r.body.records[0].candidate.creativeVersion===1,'creative lineage');
check(r.body.records[0].mayActivate===false,'no automatic promotion');
r=await post();check(r.status===200&&r.body.duplicate&&r.body.records.length===1,'same retry idempotent');
check((await post({note:'different'})).status===409,'stale version');
check((await post({expectedVersion:1,note:'판단 수정',decision:'hold',candidate:null})).status===200,'append decision revision');
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='meta_ads_learning_decision'").get().n===2,'immutable revisions');
const preview=(await get()).body.records.find(v=>v.id==='c:1');
const registration={action:'preregister',decisionId:'c:1',expectedDecisionVersion:1,expectedCandidateDigest:preview.candidateDigest,expectedVersion:2,startAt:new Date(Date.now()+86400000).toISOString(),endAt:new Date(Date.now()+3*86400000).toISOString(),maturityHours:168,fixedConditions:'동일 예산·대상·배정 경로·가격',singleVariableConfirmed:true};
check((await post({...registration,singleVariableConfirmed:false})).status===400,'single variable acknowledgment');
check((await post({...registration,maturityHours:0})).status===400,'maturity wait required');
check((await post({...registration,startAt:new Date(Date.now()-1000).toISOString()})).status===400,'future start required');
check((await post({...registration,startAt:'2028-02-30T00:00:00Z',endAt:'2028-03-03T00:00:00Z'})).status===400,'invalid calendar date');
check((await post({...registration,expectedCandidateDigest:'stale'})).status===409,'candidate hash CAS');
check((await post({...registration,expectedDecisionVersion:0})).status===409,'candidate version CAS');
r=await post(registration);check(r.status===200,'preregistration positive '+JSON.stringify(r));const registered=r.body.records[0];
check(registered.candidate.status==='preregistered'&&registered.registration.sourceDecisionId==='c:1','immutable preregistration references draft');
check(registered.registration.primaryMetric==='paid_orders'&&registered.registration.minSample===100&&registered.registration.control===candidate.control,'freeze candidate design');
check(registered.resultStatus==='insufficient'&&registered.mayActivate===false,'preregistration is not winner or activation');
r=await post(registration);check(r.status===200&&r.body.duplicate&&r.body.records.length===3,'preregister duplicate immutable');
check((await post({...registration,expectedVersion:3,maturityHours:24})).status===409,'cannot rewrite registration');
check((await get()).body.records.find(v=>v.id==='c:1').candidate.status==='draft','original draft preserved');
check((await post({...registration}, {...h,origin:'https://evil.test'})).status===403,'preregistration CSRF');
check((await post({...registration,decisionId:'foreign:1'})).status===404,'preregistration tenant isolation');
await write('meta_ads_learning_decision','foreign',{...registered,id:'foreign',campaignId:'another',registration:undefined,candidate:{...candidate,status:'draft'}},'another');
check((await post({...registration,decisionId:'foreign'})).status===409,'another campaign candidate rejected');
check((await post({expectedVersion:3,note:'두 번째 후보'})).status===200,'new immutable candidate');
const second=(await get()).body.records[0],secondInput={...registration,decisionId:second.id,expectedDecisionVersion:second.version,expectedCandidateDigest:second.candidateDigest,expectedVersion:4};
const parallel=await Promise.all([post(secondInput),post(secondInput)]);check(parallel.filter(v=>v.status===200).length===1&&parallel.filter(v=>v.status===409).length===1,'concurrent registration one winner');
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='meta_ads_learning_decision' AND parent_id='c' AND json_extract(data,'$.registration.sourceDecisionId')=?").get(second.id).n===1,'one registration per candidate');
const oldCreative=await server.readRecord(owner,'execution_creative','creative');await write('execution_creative','creative',{...oldCreative,version:2,pngHash:'b'.repeat(64)},'c');
check((await get()).body.records.find(v=>v.id==='c:1').stale===true,'candidate creative changes invalidate historical basis');
check((await get()).body.records[0].resultStatus==='invalid','changed material invalidates registration result');
check((await post(registration)).status===409,'stale candidate registration retry rejected');
check((await post({expectedVersion:2,note:'old creative'})).status===409,'reject changed creative after preview');
await write('store_order','o',{id:'o',storeId:'s',orderDate:'2026-09-01',status:'paid',source:'direct',paidAmount:10000,refundAmount:0,costs:{foodCost:null,packagingCost:null,fees:null,deliveryCost:null,benefitCost:null},version:1},'s');
r=await get();check(r.body.snapshots[0].stale===true,'new order changes report basis');
check((await post({expectedVersion:2})).status===409,'stale report rejected');
check(r.body.records.length===5&&r.body.records.find(v=>v.id==='c:1').candidate.status==='draft','prior decision preserved');
await write('campaign','c',{...c,status:'archived'});check((await post({expectedVersion:2})).status===409,'archived blocked');
env.AUTH_MODE='email';env.AUTH_ORIGIN='https://agency.test';sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run('workspace-owner','owner@test.invalid',owner,'admin','active',1);
for(const role of ['admin','member']){const token=createHash('sha256').update('learning-'+role).digest('hex');sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run(role,role+'@test.invalid',owner,role,'active',1000);sql.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?)').run(createHash('sha256').update(token).digest('hex'),role,Date.now()+60000,Date.now());const headers={cookie:'__Host-collective_session='+token,origin:'https://agency.test'};check((await post(registration,headers)).status===403,'owner only preregistration '+role);check((await get(headers)).body.canPreregister===false,'no owner controls '+role);}
console.log(JSON.stringify({passed}));
