import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
let mode='ok',calls=[];
const {load}=testRuntime(async(url,options)=>{const u=new URL(url);calls.push({u,options});assert.equal(u.origin,'https://graph.facebook.com');assert.equal(options.method,'GET');assert.equal(options.redirect,'manual');assert.equal(options.headers.Authorization,'Bearer synthetic_read_token');if(mode==='timeout')throw new Error('synthetic_read_token');if(mode==='auth')return Response.json({error:{code:190,message:'synthetic_read_token'}},{status:400});if(mode==='redirect')return new Response('',{status:302,headers:{location:'https://evil.test'}});if(!u.pathname.endsWith('/campaigns'))return Response.json({account_id:'123',currency:'KRW',timezone_name:'Asia/Seoul',account_status:1});const item={id:'456',account_id:mode==='other-account'?'999':'123',name:mode==='bad-name'?'bad\nname':'Synthetic sale',status:'PAUSED',effective_status:'PAUSED',objective:'OUTCOME_SALES'};return Response.json({data:mode==='empty'?[]:mode==='duplicate'?[item,item]:mode==='over-limit'?Array.from({length:51},(_,i)=>({...item,id:String(100+i)})):[item],...(mode==='paged'?{paging:{next:'https://evil.test/?access_token=must-never-follow',cursors:{after:'opaque-cursor'}}}:mode==='loop'?{paging:{next:'present',cursors:{after:u.searchParams.get('after')}}}:{})});});
const p=await load('lib/meta-insights-provider.ts'),server=await load('lib/server.ts'),crypto=await load('lib/credential-crypto-server.ts'),route=await load('app/api/meta-ads/campaigns/route.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++;};const browse=()=>p.listMetaCampaigns('synthetic_read_token','123');
let result=await browse();check(result.items[0].id==='456'&&result.nextCursor===null,'one scoped page');check(calls.length===2&&calls[1].u.searchParams.get('limit')==='50','account and bounded GET list');check(!JSON.stringify(result).includes('synthetic_read_token'),'secret never returned');mode='paged';result=await browse();check(result.nextCursor==='opaque-cursor','cursor returned without provider URL');mode='ok';await p.listMetaCampaigns('synthetic_read_token','123',result.nextCursor);check(calls.at(-1).u.searchParams.get('after')==='opaque-cursor','fixed host cursor pagination');mode='empty';check((await browse()).items.length===0,'empty page');
for(const m of ['other-account','bad-name','duplicate','over-limit','auth','redirect','timeout']){mode=m;await assert.rejects(browse,e=>!e.message.includes('synthetic_read_token'));passed++;}
mode='loop';await assert.rejects(()=>p.listMetaCampaigns('synthetic_read_token','123','opaque-cursor'));passed++;let before=calls.length;await assert.rejects(()=>p.listMetaCampaigns('synthetic_read_token','123','\n'));check(calls.length===before,'bad cursor rejected before network');
mode='ok';const owner='meta-catalog',headers={'oai-authenticated-user-id':owner,origin:'https://agency.test'};await server.recordStatement(owner,'brand','b',{id:'b',name:'Synthetic'}).run();await server.recordStatement(owner,'campaign','c',{id:'c',brandId:'b',version:1,status:'draft'}).run();const res=async r=>({status:r.status,body:await r.json()}),post=(data={},h=headers)=>route.POST(new Request('https://agency.test/api/meta-ads/campaigns',{method:'POST',headers:{...h,'content-type':'application/json'},body:JSON.stringify({action:'browse',campaignId:'c',connectionVersion:1,connectionUpdatedAt:'2026-09-28T00:00:00Z',...data})})).then(res);
check((await post({},{})).status===401,'anonymous');check((await post({}, {'oai-authenticated-user-id':'other'})).status===404,'owner scope');check((await post({}, {...headers,origin:'https://evil.test'})).status===403,'CSRF');before=calls.length;check((await post()).status===409&&calls.length===before,'no connection no network');const connection={channel:'meta_ads',brandId:'b',accountId:'123',readEnabled:true,version:1,updatedAt:'2026-09-28T00:00:00Z',secret:await crypto.sealRecordSecret(owner,'channel_credential','meta_ads:b','synthetic_read_token')};await server.recordStatement(owner,'channel_credential','meta_ads:b',connection).run();check((await post({connectionVersion:0})).status===409&&calls.length===before,'stale connection');check((await post({connectionUpdatedAt:'old'})).status===409&&calls.length===before,'reconnection timestamp');let r=await post({accountId:'999'});check(r.status===200&&r.body.accountId==='123','client cannot change account');check(r.body.items[0].name==='Synthetic sale','selection display data');mode='auth';r=await post();check(r.status===502&&!JSON.stringify(r.body).includes('synthetic_read_token'),'safe provider error');mode='ok';await server.recordStatement(owner,'campaign','c',{id:'c',brandId:'b',version:2,status:'archived'}).run();before=calls.length;check((await post()).status===409&&calls.length===before,'archived campaign no browse');check((await server.listRecords(owner,'meta_ads_insights','c')).length===0,'browse never saves insights');console.log(JSON.stringify({passed}));
