// mocked: synthetic plans, memory SQLite and injected auth. External calls prohibited.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
const {load,sql,env}=testRuntime(async()=>{throw new Error('외부 호출 금지')});
const logic=await load('lib/meta-ads.ts'),server=await load('lib/server.ts'),route=await load('app/api/meta-ads/route.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='meta-owner',c={id:'campaign',brandId:'brand',version:1,status:'draft'};
await server.recordStatement(owner,'campaign',c.id,c).run();
const input={...logic.emptyMetaPlan(),product:'합성 상품',landingUrl:'https://example.com/product',storeStack:'manual',accountLabel:'파일럿',startAt:'2099-01-01T00:00:00+09:00',endAt:'2099-01-08T00:00:00+09:00',attributionWindow:'7일 클릭',stopRule:'손실 한도 도달 시 중단',price:10000,unitCost:3000,variableCost:1000,totalBudget:100000,dailyTarget:10000,lossLimit:20000,safetyReserve:10000,taxBasis:'included',checks:Object.fromEntries(Object.keys(logic.metaChecks).map(k=>[k,true]))};
check(logic.parseMetaPlan(input).errors.length===0,'valid');
for(const bad of [{price:-1},{price:'100'},{unitCost:0.5},{totalBudget:Infinity},{dailyTarget:100001},{landingUrl:'javascript:alert(1)'},{landingUrl:'https://user:pass@example.com/'},{landingUrl:'https://example.com/?token=x'},{endAt:'2020-01-01T00:00:00Z'},{checks:{inventory:'true'}},{path:'other'},{currency:'USD'}])check(logic.parseMetaPlan({...input,...bad}).errors.length>0,'invalid '+JSON.stringify(bad));
const hdr={'oai-authenticated-user-id':owner,origin:'https://agency.test'};
const call=async r=>({status:r.status,body:await r.json()});
const get=(headers=hdr,id=c.id)=>route.GET(new Request('https://agency.test/api/meta-ads?campaignId='+id,{headers})).then(call);
const post=(over={},headers=hdr)=>route.POST(new Request('https://agency.test/api/meta-ads',{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify({action:'save_plan',campaignId:c.id,expectedVersion:0,campaignVersion:1,input,...over})})).then(call);
check((await get({})).status===401,'anonymous');check((await get({'oai-authenticated-user-id':'other'})).status===404,'workspace isolation');
check((await post({}, {...hdr,origin:'https://evil.test'})).status===403,'CSRF');
let r=await get();check(r.body.version===0&&!r.body.readiness.canActivate&&r.body.readiness.missing.length>0,'empty is blocked');
r=await post();check(r.status===200&&r.body.version===1&&r.body.readiness.planningComplete,'save complete');check(!r.body.readiness.canActivate&&Object.values(r.body.readiness.external).every(x=>!x),'complete never authorizes spend');check(r.body.readiness.unitContribution===6000,'unit economics');
check((await post()).status===409,'retry conflict');check((await post({action:'activate',expectedVersion:1})).status===400,'activation rejected');
check((await post({expectedVersion:1,input:{...input,approved:true,accessToken:'must-not-persist'}})).status===200,'unknown values ignored');
const row=await server.readRecord(owner,'meta_ads_plan',c.id);check(!JSON.stringify(row).includes('must-not-persist')&&!('approved' in row.input),'no injected approval or token');
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='event'").get().n===2,'only successful mutations audited');
await server.recordStatement(owner,'campaign',c.id,{...c,version:2}).run();
r=await get();check(r.body.readiness.missing.includes('변경된 캠페인 기준으로 계획 다시 저장'),'campaign changes invalidate readiness');check((await post({expectedVersion:2})).status===409,'stale campaign rejected');
const unknown={...row,input:{...input,unitCost:null}};check(logic.metaReadiness(unknown,1).unitContribution===null,'missing cost not zero');check(logic.metaReadiness({...row,input:{...input,goal:'awareness'}},1).salesEvidence==='매출 미검증','awareness not sales');check(!logic.metaReadiness(row,1,Date.parse('2100-01-01')).planningComplete,'expired period');
env.AUTH_MODE='email';env.AUTH_ORIGIN='https://agency.test';
const signIn=(id,role)=>{const token=createHash('sha256').update(id).digest('hex');sql.prepare('INSERT INTO auth_users(id,email,workspace_owner,role,status,created_at) VALUES(?,?,?,?,?,?)').run(id,id+'@test.invalid',owner,role,'active',1000);sql.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?)').run(createHash('sha256').update(token).digest('hex'),id,Date.now()+60000,Date.now());return {cookie:'__Host-collective_session='+token,origin:'https://agency.test'}};
const member=signIn('member','member'),admin=signIn('admin','admin');
check((await post({},member)).status===403,'member denied');check((await get(member)).body.canEdit===false,'member readonly');check((await post({expectedVersion:2,campaignVersion:2},admin)).status===200,'admin may plan');

const competing=await Promise.all([post({expectedVersion:3,campaignVersion:2},admin),post({expectedVersion:3,campaignVersion:2},admin)]);
check(competing.filter(r=>r.status===200).length===1&&competing.filter(r=>r.status===409).length===1,'concurrent writes preserve one revision');
const saved=await server.readRecord(owner,'meta_ads_plan',c.id);
check(saved.version===4&&saved.brandId==='brand','server-owned identity and version');
await server.recordStatement(owner,'campaign',c.id,{...c,version:2,status:'archived'}).run();
check((await post({expectedVersion:4,campaignVersion:2},admin)).status===409,'archived denied');
console.log(JSON.stringify({passed}));
