import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
const {load,sql}=testRuntime(async()=>{throw new Error('No external calls from learning')});
const server=await load('lib/server.ts'),reports=await load('app/api/meta-ads/report/route.ts');
const route=await load('app/api/meta-ads/learning/route.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='meta-learning',h={'oai-authenticated-user-id':owner,origin:'https://agency.test'};
const c={id:'c',brandId:'b',storeId:'s',version:1,title:'Synthetic',status:'active'};
const write=(kind,id,data,parent)=>server.recordStatement(owner,kind,id,data,parent).run();
await write('brand','b',{id:'b',name:'Synthetic brand',color:'#112233'});await write('campaign','c',c);await write('store','s',{id:'s',brandId:'b',version:1,status:'active'},'b');
const request=(path,data,headers=h)=>new Request('https://agency.test/api/meta-ads/'+path,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify(data)});
const unpack=async r=>({status:r.status,body:await r.json()});
const get=(headers=h)=>route.GET(new Request('https://agency.test/api/meta-ads/learning?campaignId=c',{headers})).then(unpack);
const current=await reports.GET(new Request('https://agency.test/api/meta-ads/report?campaignId=c&since=2026-09-01&until=2026-09-02',{headers:h})).then(r=>r.json());
await reports.POST(request('report',{action:'freeze',campaignId:'c',since:'2026-09-01',until:'2026-09-02',confirmed:true,expectedVersion:0,expectedDigest:current.report.basisDigest}));
const candidate={hypothesis:'상품 설명을 바꾸면 구매 의향이 달라진다',variable:'훅',control:'상품 구성 중심',treatment:'사용 장면 중심',metric:'paid_orders',minSample:100,stopCondition:'기간 종료 후 검토',creativeId:'creative',creativeVersion:1,creativeHash:'a'.repeat(64)};
await write('execution_creative','creative',{id:'creative',brandId:'b',storeId:'s',campaignId:'c',campaignVersion:1,version:1,pngHash:'a'.repeat(64),factRefs:[],objectKey:'synthetic'},'c');
const base={campaignId:'c',action:'record',snapshotId:'c:1',expectedDigest:current.report.basisDigest,expectedVersion:0,decision:'retest',note:'근거를 더 모으기 위한 재실험',candidate,confirmed:true};
const post=(extra={},headers=h)=>route.POST(request('learning',{...base,...extra},headers)).then(unpack);
check((await get({})).status===401,'anonymous');check((await get({'oai-authenticated-user-id':'other'})).status===404,'tenant isolation');
check((await post({}, {...h,origin:'https://evil.test'})).status===403,'CSRF');
check((await post({confirmed:false})).status===400,'explicit decision confirmation');
check((await post({decision:'winner'})).status===400,'no invented winner');
check((await post({candidate:{...candidate,minSample:0}})).status===400,'positive sample');
check((await post({candidate:{...candidate,creativeId:'other'}})).status===409,'current same campaign creative');
check((await post({expectedDigest:'old'})).status===409,'source digest binding');
check((await post({snapshotId:'foreign:1'})).status===404,'snapshot isolation');
let r=await post();check(r.status===200,'record decision '+JSON.stringify(r));check(r.body.records.length===1,'one decision');
check(r.body.records[0].evidenceStatus==='insufficient'&&r.body.records[0].candidate.status==='draft','insufficient stays insufficient');
check(r.body.records[0].candidate.creativeVersion===1,'creative lineage');
check(r.body.records[0].mayActivate===false,'no automatic promotion');
r=await post();check(r.status===200&&r.body.duplicate&&r.body.records.length===1,'same retry idempotent');
check((await post({note:'different'})).status===409,'stale version');
check((await post({expectedVersion:1,note:'판단 수정',decision:'hold',candidate:null})).status===200,'append decision revision');
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='meta_ads_learning_decision'").get().n===2,'immutable revisions');
const oldCreative=await server.readRecord(owner,'execution_creative','creative');await write('execution_creative','creative',{...oldCreative,version:2,pngHash:'b'.repeat(64)},'c');
check((await get()).body.records[1].stale===true,'candidate creative changes invalidate historical basis');
check((await post({expectedVersion:2,note:'old creative'})).status===409,'reject changed creative after preview');
await write('store_order','o',{id:'o',storeId:'s',orderDate:'2026-09-01',status:'paid',source:'direct',paidAmount:10000,refundAmount:0,costs:{foodCost:null,packagingCost:null,fees:null,deliveryCost:null,benefitCost:null},version:1},'s');
r=await get();check(r.body.snapshots[0].stale===true,'new order changes report basis');
check((await post({expectedVersion:2})).status===409,'stale report rejected');
check(r.body.records.length===2&&r.body.records[1].candidate.status==='draft','prior decision preserved');
await write('campaign','c',{...c,status:'archived'});check((await post({expectedVersion:2})).status===409,'archived blocked');
console.log(JSON.stringify({passed}));
