import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';
let calls=[],mode='normal';
const {load}=testRuntime(async(url,options)=>{calls.push({url,options});const u=new URL(url);assert.equal(u.origin,'https://graph.facebook.com');assert.equal(options.redirect,'manual');assert.equal(options.headers.Authorization,'Bearer synthetic_write_token');assert.equal(u.searchParams.has('access_token'),false);if(mode==='timeout')throw new Error('synthetic_write_token secret');if(mode==='redirect')return new Response('',{status:302,headers:{location:'https://evil.test'}});if(mode==='error')return Response.json({error:{message:'synthetic_write_token'}},{status:400});if(options.method==='POST'){if(mode==='badid')return Response.json({id:'https://evil.test'});return Response.json({id:'789'})}if(mode==='readfail')throw new Error('secret');return Response.json({id:'789',name:mode==='name'?'unrelated':'Synthetic [Collective '+draft.operationKey+']',account_id:mode==='cross'?'999':'123',objective:mode==='objective'?'OUTCOME_TRAFFIC':'OUTCOME_SALES',configured_status:mode==='active'?'ACTIVE':'PAUSED',effective_status:mode==='pending'?'IN_PROCESS':'PAUSED'})});
const lib=await load('lib/meta-paused-campaign.ts');let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};const draft={accountId:'123',name:'Synthetic campaign',objective:'OUTCOME_SALES',specialCategoryReview:'not_applicable',operationKey:'a'.repeat(64)},token='synthetic_write_token';
let stored=null,history=[];const journal={begin:async v=>{if(stored)return false;stored=v;history.push(v);return true},finish:async v=>{stored=v;history.push(v)}};const reset=()=>{stored=null;history=[];calls=[];mode='normal'};const receipt=()=>lib.preparedPausedReceipt(draft);const create=(enabled=true,raw=draft,r=receipt(),j=journal)=>lib.createPausedMetaCampaign(token,raw,r,j,enabled);
await assert.rejects(()=>create(false),e=>e.code==='disabled');check(calls.length===0,'disabled zero calls');for(const raw of [{...draft,status:'ACTIVE'},{...draft,daily_budget:1000},{...draft,accountId:'../me'},{...draft,objective:'OUTCOME_TRAFFIC'},{...draft,specialCategoryReview:'unknown'},{...draft,operationKey:'bad'},{...draft,name:'bad\nname'}]){await assert.rejects(()=>create(true,raw));check(calls.length===0,'invalid zero calls')}
let result=await create();check(result.state==='paused_verified'&&result.externalId==='789','readback verification');check(history.map(x=>x.state).join(',')==='sending,unknown,paused_verified','durable lifecycle');const body=new URLSearchParams(calls[0].options.body);check(body.get('status')==='PAUSED'&&!body.has('daily_budget')&&!body.has('lifetime_budget'),'PAUSED no budget');check(body.get('name').includes(draft.operationKey),'stable correlation name');check(calls.length===2&&calls[1].options.method==='GET','one POST one read');await assert.rejects(()=>create(true,draft,stored));check(calls.length===2,'verified cannot recreate');await assert.rejects(()=>create());check(calls.length===2,'stale prepared rejected by atomic begin');
for(const m of ['timeout','redirect','error','badid','readfail','cross','objective','active','pending','name']){reset();mode=m;await assert.rejects(()=>create(),e=>!e.message.includes('synthetic_write_token')&&['unknown','mismatch'].includes(e.code));check(stored.state==='unknown','failure unknown '+m);check(calls.filter(x=>x.options.method==='POST').length===1,'no retry '+m);if(stored.externalId){mode='normal';result=await lib.verifyPausedMetaCampaign(token,stored,true);check(result.state==='paused_verified'&&calls.filter(x=>x.options.method==='POST').length===1,'read-only reconcile '+m)}}
reset();const results=await Promise.allSettled([create(),create()]);check(results.filter(x=>x.status==='fulfilled').length===1&&calls.filter(x=>x.options.method==='POST').length===1,'concurrent reservation');reset();await assert.rejects(()=>create(true,draft,receipt(),{begin:async()=>{throw new Error('DB unavailable')},finish:async()=>{}}));check(calls.length===0,'no durable reservation no call');reset();await assert.rejects(()=>create(true,draft,receipt(),{begin:journal.begin,finish:async()=>{throw new Error('DB unavailable')}}),e=>e.code==='unknown'&&e.externalId==='789');check(stored.state==='sending'&&calls.length===1,'journal failure after create no second write');
console.log(JSON.stringify({passed}));
