import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
const {load,sql}=testRuntime(async()=>{throw new Error('external forbidden')});
const server=await load('lib/product-research/server.ts'),flags=await load('lib/feature-flags.ts'),policy=await load('lib/product-research/server-policy.ts');
const scoring=await load('lib/product-research/analytics/score.ts'),pipeline=await load('lib/product-research/server-pipeline.ts');
const owner='risk-provenance',who={owner,id:owner,role:'owner',email:null};let passed=0;const check=(v,m)=>{assert.ok(v,m);passed++};
await flags.setFeatureFlag(owner,{flag:'product_research',enabled:true},{id:owner,email:null});
const csv=['rank,title,brand,price,review_count,rating,external_id,url','1,가상브랜드 E2E관문약과 300g,가상브랜드,12900,321,4.8,e2e-gate-yakgwa,','2,가상브랜드 E2E다이어트차 다이어트 효과 100g,가상브랜드,8900,120,4.6,e2e-gate-diet,','3,가상브랜드 E2E짝퉁과자 150g,가상브랜드,5900,45,4.4,e2e-gate-fake,'].join('\n');
for(const [back,sourceId] of [[1,'musinsa_ranking_manual'],[0,'coupang_ranking_manual']])await server.researchAction(who,{action:'import_file',requestId:randomUUID(),sourceId,fileName:'gate.csv',text:csv,scope:'가상 과자 랭킹',observedDate:new Date(Date.now()+9*3600000-back*86400000).toISOString().slice(0,10)});
const view=await server.researchAction(who,{action:'recompute',requestId:randomUUID()});
const diet=view.products.find(p=>p.name.includes('다이어트')),fake=view.products.find(p=>p.name.includes('짝퉁'));
check(diet?.score?.needsReview===true,'real public import exposes risk review card');
check(fake?.score?.blocked!==null&&!!fake?.score,'real public import exposes blocked counterfeit card');
const risk=diet.score.subScores.find(s=>s.key==='risk');check(risk.evidence.length>0,'risk cites original product title snapshots');
check((await policy.scoreResearchPolicy(owner,diet.score)).allowed,'complete risk title provenance permitted');
const material=await pipeline.loadMaterial(owner),draft=pipeline.computeProducts(material,[],[],new Set(),new Date().toISOString()).drafts.find(d=>d.product.name.includes('다이어트'));
const input=scoring.buildScoreInput(draft.bundle,draft.asOf),current=scoring.scoreCard(input,{computedAt:new Date().toISOString()}),changed=scoring.scoreCard({...input,riskEvidence:['changed-original']},{computedAt:new Date().toISOString()});
check(current.id!==changed.id&&current.inputDigest!==changed.inputDigest,'risk source change creates new score revision');
check(current.total===changed.total&&current.confidence===changed.confidence,'source provenance preserves numeric scoring');
const snapshotId=risk.evidence[0],key=`${owner}:pr_snapshot:${snapshotId}`,original=sql.prepare('SELECT data FROM records WHERE id=?').get(key).data;
sql.prepare('UPDATE records SET data=json_set(data,\'$.sourceId\',\'youtube_data\') WHERE id=?').run(key);
check(!(await policy.scoreResearchPolicy(owner,diet.score)).allowed,'forbidden original invalidates title-based risk card');
sql.prepare('UPDATE records SET data=? WHERE id=?').run(original,key);sql.prepare('DELETE FROM records WHERE id=?').run(key);
check(!(await policy.scoreResearchPolicy(owner,diet.score)).allowed,'missing original invalidates title-based risk card');
// pinned 묶음은 일부 원본이 사라져도 상품명 fallback을 유지한다. 남은 정상 근거로 세탁되지 않아야 한다.
sql.prepare('INSERT INTO records(id,owner,kind,parent_id,data,updated_at) VALUES(?,?,?,?,?,?)').run(key,owner,'pr_snapshot',JSON.parse(original).sourceId,original,new Date().toISOString());
const productKey=`${owner}:pr_product:${diet.id}`,savedProduct=JSON.parse(sql.prepare('SELECT data FROM records WHERE id=?').get(productKey).data);
const extra={sourceId:'coupang_ranking_manual',externalId:'extra-title',title:'다이어트 효과 약과',url:null};
const extraSnapshot={...JSON.parse(original),id:'extra-original',sourceId:extra.sourceId,observations:[{subject:{type:'listing',...extra,price:null,brand:null,categoryPath:null},metric:'rank',value:1,period:{from:'2026-09-01',to:'2026-09-01'}}]};
sql.prepare('INSERT INTO records(id,owner,kind,parent_id,data,updated_at) VALUES(?,?,?,?,?,?)').run(`${owner}:pr_snapshot:extra-original`,owner,'pr_snapshot',extra.sourceId,JSON.stringify(extraSnapshot),new Date().toISOString());
sql.prepare('UPDATE records SET data=? WHERE id=?').run(JSON.stringify({...savedProduct,listings:[...savedProduct.listings,extra],match:{...savedProduct.match,confirmedBy:{id:owner,email:null}}}),productKey);
await server.researchAction(who,{action:'recompute',requestId:randomUUID()});
const currentCard=()=>{const p=JSON.parse(sql.prepare('SELECT data FROM records WHERE id=?').get(productKey).data);return JSON.parse(sql.prepare('SELECT data FROM records WHERE id=?').get(`${owner}:pr_score:${p.scoreId}`).data)};
check((await policy.scoreResearchPolicy(owner,currentCard())).allowed,'mixed pinned titles all backed before deletion');
sql.prepare('DELETE FROM records WHERE id=?').run(`${owner}:pr_snapshot:extra-original`);
await server.researchAction(who,{action:'recompute',requestId:randomUUID()});
const incomplete=currentCard();
check(incomplete.riskEvidenceComplete===false,'missing one pinned title original marks incomplete risk evidence');
check(incomplete.subScores.some(s=>s.evidence.length>0),'other valid evidence remains for regression');
check(!(await policy.scoreResearchPolicy(owner,incomplete)).allowed,'partial surviving evidence never rescues whole card');
check(!(await policy.scoreResearchPolicies(owner,[incomplete])).get(incomplete.id).allowed,'bulk path rejects incomplete risk evidence');
console.log(JSON.stringify({passed,sqlite:'real',auth:'mocked',externalCalls:0}));
