import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {testRuntime} from './helpers/runtime.mjs';
const {load,sql}=testRuntime(async()=>{throw new Error('external forbidden')});
const server=await load('lib/product-research/server.ts'),flags=await load('lib/feature-flags.ts'),policy=await load('lib/product-research/server-policy.ts');
const scoring=await load('lib/product-research/analytics/score.ts'),pipeline=await load('lib/product-research/server-pipeline.ts');
const owner='risk-provenance',who={owner,id:owner,role:'owner',email:null};let passed=0;const check=(v,m)=>{assert.ok(v,m);passed++};
await flags.setFeatureFlag(owner,{flag:'product_research',enabled:true},{id:owner,email:null});
const csv=['rank,title,brand,price,review_count,rating,external_id,url','1,가상브랜드 E2E관문약과 300g,가상브랜드,12900,321,4.8,e2e-gate-yakgwa,','2,가상브랜드 E2E다이어트차 다이어트 효과 100g,가상브랜드,8900,120,4.6,e2e-gate-diet,','3,가상브랜드 E2E짝퉁과자 150g,가상브랜드,5900,45,4.4,e2e-gate-fake,'].join('\n');
for(const [back,sourceId] of [[1,'musinsa_ranking_manual'],[0,'coupang_ranking_manual']])await server.researchAction(who,{action:'import_file',requestId:randomUUID(),sourceId,fileName:'gate.csv',text:csv,scope:'가상 과자 랭킹',observedDate:new Date(Date.now()+9*3600000-back*86400000).toISOString().slice(0,10)});
const view=await server.researchAction(who,{action:'recompute',requestId:randomUUID()});
const diet=view.products.find(p=>p.name.includes('다이어트')),fake=view.products.find(p=>p.name.includes('짝퉁'));
check(diet?.score?.needsReview===true,'real public import exposes risk review card');
check(fake?.score?.blocked!==null&&!!fake?.score,'real public import exposes blocked counterfeit card');
const risk=diet.score.subScores.find(s=>s.key==='risk');check(risk.evidence.length>0,'risk cites original product title snapshots');
check((await policy.scoreResearchPolicy(owner,diet.score)).allowed,'complete risk title provenance permitted');
const material=await pipeline.loadMaterial(owner),draft=pipeline.computeProducts(material,[],[],new Set(),new Date().toISOString()).drafts.find(d=>d.product.name.includes('다이어트'));
const input=scoring.buildScoreInput(draft.bundle,draft.asOf),current=scoring.scoreCard(input,{computedAt:new Date().toISOString()}),changed=scoring.scoreCard({...input,riskEvidence:['changed-original']},{computedAt:new Date().toISOString()});
check(current.id!==changed.id&&current.inputDigest!==changed.inputDigest,'risk source change creates new score revision');
check(current.total===changed.total&&current.confidence===changed.confidence,'source provenance preserves numeric scoring');
const snapshotId=risk.evidence[0],key=`${owner}:pr_snapshot:${snapshotId}`,original=sql.prepare('SELECT data FROM records WHERE id=?').get(key).data;
sql.prepare('UPDATE records SET data=json_set(data,\'$.sourceId\',\'youtube_data\') WHERE id=?').run(key);
check(!(await policy.scoreResearchPolicy(owner,diet.score)).allowed,'forbidden original invalidates title-based risk card');
sql.prepare('UPDATE records SET data=? WHERE id=?').run(original,key);sql.prepare('DELETE FROM records WHERE id=?').run(key);
check(!(await policy.scoreResearchPolicy(owner,diet.score)).allowed,'missing original invalidates title-based risk card');
console.log(JSON.stringify({passed,sqlite:'real',auth:'mocked',externalCalls:0}));
