// Actual React SSR, mocked UI primitives/API registry; no network or credentials.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {createRequire} from 'node:module';
import {SourceTextModule,SyntheticModule,createContext} from 'node:vm';
import ts from 'typescript';
const require=createRequire(import.meta.url),React=require('react'),jsx=require('react/jsx-runtime'),{renderToStaticMarkup}=require('react-dom/server');
const context=createContext({Date,Intl,URL,console}),cache=new Map();
const keys=['naver_searchad','naver_developers','naver_api_hub','youtube','coupang_partners','licensed'];
const sources=[{id:'naver_shop_search',label:'네이버 쇼핑 검색',method:'api',autoFetch:false},{id:'naver_datalab_search',label:'네이버 데이터랩 검색어 트렌드',method:'api',autoFetch:true},{id:'naver_datalab_shopping',label:'네이버 데이터랩 쇼핑인사이트',method:'api',autoFetch:true}];
const api={CREDENTIAL_KEYS:keys,CREDENTIAL_SOURCES:Object.fromEntries(keys.map(k=>[k,k.startsWith('naver')?sources.map(s=>s.id):[]])),REASON_MIN:10,REASON_MAX:500};
function synth(names,values){return new SyntheticModule([...names],function(){for(const name of names)this.setExport(name,values[name]??(()=>''));},{context});}
function mod(file){file=resolve(file);if(cache.has(file))return cache.get(file);const code=ts.transpileModule(readFileSync(file,'utf8'),{fileName:file,compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;const m=new SourceTextModule(code,{context,identifier:file});m.names=new Map();for(const s of ts.createSourceFile(file,code,ts.ScriptTarget.ES2022).statements){if(!ts.isImportDeclaration(s))continue;const n=new Set();if(s.importClause?.name)n.add('default');for(const e of s.importClause?.namedBindings?.elements??[])n.add((e.propertyName||e.name).text);m.names.set(s.moduleSpecifier.text,n);}cache.set(file,m);return m;}
const part=tag=>{function Part({children,disabledReason,variant,size,...props}){void variant;void size;return React.createElement(tag,{...props,title:disabledReason},children);}Part.displayName=tag;return Part;};
const components={Button:part('button'),Input:part('input'),NativeSelect:part('select'),NativeSelectOption:part('option'),MetaLine:({items})=>React.createElement('span',null,items.filter(Boolean).join(' / ')),DataTable:({rows,columns,caption})=>React.createElement('table',{'aria-label':caption},React.createElement('tbody',null,rows.map((row,i)=>React.createElement('tr',{key:i},columns.map((col,j)=>React.createElement('td',{key:j},col.cell?.(row))))))),CollectionControl:({connected})=>React.createElement('div',{'data-collection-connected':String(connected)}),LockedNote:({reason})=>React.createElement('p',null,reason)};
async function link(spec,ref){const names=ref.names.get(spec)||[];if(spec==='react')return synth(names,React);if(spec==='react/jsx-runtime')return synth(names,jsx);if(spec.endsWith('.css'))return synth(names,{default:new Proxy({},{get:(_,k)=>String(k)})});if(spec==='./product-research-shared')return mod('app/product-research-shared.tsx');if(spec==='@/lib/product-research/api')return synth(names,api);if(spec==='@/lib/product-research/sources')return synth(names,{SOURCES:sources,IMPORTABLE_SOURCES:[]});if(spec==='@/lib/product-research/ui-detail')return synth(names,{LIMITS:{},oldestImportDay:()=>'',calibrationText:()=>''});if(spec==='@/lib/format')return synth(names,{dateTime:()=>'',count:v=>String(v),percent:v=>String(v)});return synth(names,components);}
const shared=mod('app/product-research-shared.tsx');await shared.link(link);await shared.evaluate();
let passed=0;const test=(name,fn)=>{fn();passed++;};
test('HUB has distinct client credentials and legacy is explicit',()=>{const hub=shared.namespace.credentialForms.naver_api_hub;assert(hub);assert.equal(hub.label,'NAVER API HUB');assert.deepEqual(Array.from(hub.fields,f=>f.name),['clientId','clientSecret']);assert.equal(hub.fields[1].secret,true);assert.match(shared.namespace.credentialForms.naver_developers.label,/기존 연결용/);});
const ui=mod('app/product-research-sources.tsx');await ui.link(link);await ui.evaluate();
const view={sources:sources.map(s=>({...s,connected:s.id==='naver_shop_search',lastFetchedAt:null,lastStatus:null,dailyQuota:null,quotaUsedToday:null})),credentials:[],canConnect:true,canEdit:true,collectEnabled:true,collect:{lastRunAt:null,nextRunAt:null,lastErrors:[]},imports:[],alerts:[],quarantine:[]};
const render=over=>renderToStaticMarkup(React.createElement(ui.namespace.SourcesTab,{view:{...view,...over},act:async()=>({ok:true}),busy:false,onCandidates:()=>{},onRefresh:async()=>true}));
test('retired stale-connected source never enables collection',()=>{const html=render();const row=html.match(/<tr>.*?네이버 쇼핑 검색.*?<\/tr>/)?.[0];assert(row);assert.match(row,/서비스 종료/);assert.doesNotMatch(row,/연결됨/);assert.match(html,/data-collection-connected="false"/);assert.match(html,/<button[^>]*disabled=""[^>]*>지금 수집<\/button>/);});
test('HUB form explains both permission checks and hides secret',()=>{const html=render();assert.match(html,/NAVER API HUB Client ID/);assert.match(html,/NAVER API HUB Client Secret/);assert.match(html,/검색어 트렌드와 쇼핑인사이트.*확인.*저장/);assert.match(html,/<input(?=[^>]*type="password")(?=[^>]*name="pr-credential-naver_api_hub-clientSecret")(?=[^>]*autoComplete="new-password")[^>]*>/);});
test('admin cannot receive HUB credential inputs',()=>{const html=render({canConnect:false});assert.doesNotMatch(html,/name="pr-credential-naver_api_hub/);assert.match(html,/소유자만 할 수 있습니다/);});
test('active datalab connection enables global collection',()=>{const html=render({sources:view.sources.map(s=>({...s,connected:s.id==='naver_datalab_search'}))});assert.match(html,/data-collection-connected="true"/);assert.match(html,/<button(?![^>]*disabled="")[^>]*>지금 수집<\/button>/);});
const both=[{key:'naver_api_hub',connected:true},{key:'naver_developers',connected:true}];
test('HUB removal warns that legacy collection continues',()=>{const text=shared.namespace.credentialDisconnectImpact('naver_api_hub',both);assert.match(text,/기존 네이버 개발자센터 키로 계속 수집/);assert.match(text,/자동 수집 스위치를 끄세요/);assert.doesNotMatch(text,/이 출처의 자동 수집을 멈춥니다/);});
test('legacy removal preserves preferred HUB collection',()=>{const text=shared.namespace.credentialDisconnectImpact('naver_developers',both);assert.match(text,/NAVER API HUB 키로 계속 수집/);assert.doesNotMatch(text,/이 출처의 자동 수집을 멈춥니다/);});
test('last key removal stops only its source',()=>{const text=shared.namespace.credentialDisconnectImpact('naver_api_hub',[both[0]]);assert.match(text,/이 출처의 자동 수집을 멈춥니다/);assert.match(text,/이미 모은 스냅샷과 점수/);});
test('HUB precedence is visible when both keys are connected',()=>assert.match(render({credentials:both}),/함께 연결되어 있으면 NAVER API HUB 키를 우선 사용/));
console.log(JSON.stringify({passed,render:'real React SSR',primitives:'mocked',network:0}));
