import assert from 'node:assert/strict';
import {testRuntime} from './helpers/runtime.mjs';

let failSnapshot = false, failSubmission = false, failUsage = false, lostAck = false, calls = 0, holdProvider = false;
const polled = new Set();
const submissions = new Map();
const runtime = testRuntime(async (url, options = {}) => {
 if(url.endsWith('/responses'))return Response.json({id:'resp_known',status:'completed',model:'test',usage:{total_tokens:15},output:[{content:[{type:'output_text',text:'OpenAI output'}]}]});
 if (url.endsWith('/v1/runs')) {
  const key = options.headers['Idempotency-Key'];
  if (!submissions.has(key)) submissions.set(key, 'run_' + ++calls);
  if (lostAck) { lostAck = false; throw new Error('lost acknowledgement'); }
  return Response.json({run_id: submissions.get(key)});
 }
 const id = url.split('/').pop();
 polled.add(id);
 return Response.json({object: 'hermes.run', run_id: id, status: holdProvider ? 'running' : 'completed', output: 'A provider artifact', usage: {total_tokens: 12}});
}, {beforeRun(statement) { if ((failSnapshot && statement.values[2] === 'learning_snapshot') || (failSubmission && statement.values[2] === 'hermes_submission') || (failUsage && statement.values[2] === 'provider_usage')) throw new Error('injected persistence failure'); }});
const {sql, load} = runtime;
const server = await load('lib/server.ts');
const run = await load('app/api/run/route.ts');
const owner = 'reliability-owner';
await server.seedBrands(owner);
await sql.prepare('INSERT INTO settings(owner,secret,model,updated_at) VALUES(?,?,?,?)').run(owner, await server.encrypt(JSON.stringify({provider: 'hermes', endpoint: 'https://hermes.example.com', key: 'test-key'})), 'test', new Date().toISOString());
const request = data => run.POST(new Request('https://agency.test/api/run', {method: 'POST', headers: {'Content-Type': 'application/json', 'oai-authenticated-user-id': owner}, body: JSON.stringify(data)}));
const passed = [];
function check(name, value) { assert.ok(value, name); passed.push(name); }

failSnapshot = true;
let response = await request({action: 'start', campaignId: 'ofd-pilot-01', role: 'cmo'});
check('snapshot failure returns error', response.status === 500);
check('atomic preparation leaves no orphan job', sql.prepare('SELECT COUNT(*) n FROM jobs').get().n === 0);
check('no provider charged on storage failure', calls === 0);
failSnapshot = false; lostAck = true;
response = await request({action: 'start', campaignId: 'ofd-pilot-01', role: 'cmo'});
check('ack loss is not treated as success', response.status === 502);
const job = sql.prepare('SELECT * FROM jobs').get();
check('uncertain job retains durable submission', job.status === 'uncertain' && !!sql.prepare("SELECT id FROM records WHERE kind='hermes_submission'").get());
response = await request({action: 'recover', id: job.id});
check('restart recovery uses same provider request', response.status === 200 && calls === 1);
response = await request({action: 'poll', id: job.id});
check('recovered run completes', (await response.json()).status === 'completed');
const worker = await load('lib/research-worker.ts');
const token = await worker.registerWorker(owner);
const hash = await worker.workerHash(token);
await server.recordStatement(owner, 'brand_research', 'long-research', {id: 'long-research', status: 'running', createdAt: new Date().toISOString()}).run();
let researchTicks = 0, measurementTicks = 0, executionTicks = 0;
for (let i = 0; i < 6; i++) await worker.workerTick({owner, hash}, async () => { researchTicks++; return Response.json({status: 'running'}); }, async () => { measurementTicks++; return {status: 'processed'}; }, async () => { executionTicks++; return {status: 'processed'}; });
check('long research cannot starve measurements', measurementTicks >= 2);
check('background workflows receive a fair turn', executionTicks >= 2 && researchTicks >= 2);
for (const id of ['research-b','research-c']) await server.recordStatement(owner, 'brand_research', id, {id, status: 'running', createdAt: new Date().toISOString()}).run();
const researched = new Set();
for (let i = 0; i < 9; i++) await worker.workerTick({owner, hash}, async (_, input) => { researched.add(input.id); return Response.json({status: 'running'}); }, async () => ({status: 'processed'}), async () => ({status: 'processed'}));
check('fair queues preserve round robin within research', researched.size === 3);
await worker.revokeWorker(owner);
await assert.rejects(() => worker.workerTick({owner, hash}, async () => Response.json({})), /인증/);
passed.push('revoked worker cannot advance workflows');
check('unregistered automation is rejected', (await request({action: 'start_sequence', campaignId: 'ofd-pilot-01'})).status === 409);
await worker.registerWorker(owner);
const background = await load('lib/background-execution.ts');
const campaign = await server.readRecord(owner, 'campaign', 'ofd-pilot-01');
await server.recordStatement(owner, 'campaign', 'sequence-campaign', {...campaign, id: 'sequence-campaign', version: 1}).run();
const beforeSequence = calls;
response = await request({action: 'start_sequence', campaignId: 'sequence-campaign'});
check('automation consent is durable and does not charge immediately', response.status === 200 && calls === beforeSequence);
await request({action: 'stop_sequence', campaignId: 'sequence-campaign'});
await background.advanceBackgroundWork(owner);
check('paused sequence never starts a provider request', calls === beforeSequence);
await request({action: 'start_sequence', campaignId: 'sequence-campaign'});
for (let i = 0; i < 20; i++) await background.advanceBackgroundWork(owner);
const sequence = await server.readRecord(owner, 'campaign_sequence', 'sequence-campaign');
check('all eight roles finish with no browser polling', sequence.status === 'completed' && calls === beforeSequence + 8);
check('background completion preserves human approval', sql.prepare("SELECT COUNT(*) n FROM records WHERE owner=? AND kind='artifact' AND parent_id=? AND json_extract(data,'$.status')='approved'").get(owner, 'sequence-campaign').n === 0);
await server.recordStatement(owner, 'campaign', 'stale-sequence', {...campaign, id: 'stale-sequence', version: 1}).run();
await request({action: 'start_sequence', campaignId: 'stale-sequence'});
await server.recordStatement(owner, 'campaign', 'stale-sequence', {...campaign, id: 'stale-sequence', version: 2}).run();
const beforeStale = calls;
await background.advanceBackgroundWork(owner);
check('changed brief blocks automated spending', (await server.readRecord(owner, 'campaign_sequence', 'stale-sequence')).status === 'blocked' && calls === beforeStale);
const foreign = await background.advanceBackgroundWork('different-owner');
check('background worker remains owner scoped', foreign.status === 'idle' && calls === beforeStale);
await request({action: 'start_sequence', campaignId: 'stale-sequence'});
const setting = sql.prepare('SELECT * FROM settings WHERE owner=?').get(owner);
sql.prepare('DELETE FROM settings WHERE owner=?').run(owner);
check('automation can always be paused while disconnected', (await request({action: 'stop_sequence', campaignId: 'stale-sequence'})).status === 200);
sql.prepare('INSERT INTO settings(owner,secret,model,updated_at) VALUES(?,?,?,?)').run(owner, setting.secret, setting.model, setting.updated_at);
await request({action: 'start_sequence', campaignId: 'stale-sequence'});
await server.deleteCampaign(owner, {id: 'stale-sequence', version: 2, confirmed: true});
check('deleting a campaign removes its future automation', sql.prepare("SELECT COUNT(*) n FROM records WHERE owner=? AND kind='campaign_sequence' AND parent_id=?").get(owner, 'stale-sequence').n === 0);
const learning = await load('lib/learning-execution.ts');
const beforeLearning = sql.prepare('SELECT COUNT(*) n FROM jobs').get().n;
failSubmission = true;
response = await learning.executeLearning(owner, {action: 'start_discovery', brandId: 'ofd', query: 'Public bakery examples'});
check('learning preparation failure is visible', !response.ok);
check('learning submission and job commit together', sql.prepare('SELECT COUNT(*) n FROM jobs').get().n === beforeLearning);
failSubmission = false;
response = await learning.executeLearning(owner, {action: 'start_discovery', brandId: 'ofd', query: 'Public bakery examples'});
const learningJob = await response.json();
await background.advanceBackgroundWork(owner);
check('learning result is collected without an open browser', sql.prepare('SELECT status FROM jobs WHERE id=?').get(learningJob.id).status === 'failed');
check('invalid learning JSON retains provider usage', sql.prepare("SELECT COUNT(*) n FROM records WHERE owner=? AND kind='provider_usage' AND json_extract(data,'$.domainOutcome')='invalid_output'").get(owner).n >= 1);
const meetings = await load('lib/meeting-execution.ts');
await server.recordStatement(owner, 'campaign', 'meeting-campaign', {...campaign, id: 'meeting-campaign', version: 1}).run();
response = await meetings.executeMeeting(owner, {action: 'start', id: 'background-meeting', campaignId: 'meeting-campaign', campaignVersion: 1, agenda: '실제 공급자 결과만 검토'});
check('meeting intent is durably stored', response.ok);
await background.advanceBackgroundWork(owner);
await background.advanceBackgroundWork(owner);
check('meeting advances and records invalid result without a browser', (await server.readRecord(owner, 'team_meeting', 'background-meeting')).status === 'failed');
holdProvider = true; polled.clear();
for (const id of ['a','B']) await server.recordStatement(owner, 'brief_draft', id, {id, status: 'queued', providerId: 'run_' + id, input: {}}).run();
await server.recordStatement(owner, 'background_cursor', 'current', {last: 'brief:a'}).run();
for (let i = 0; i < 4; i++) await background.advanceBackgroundWork(owner);
check('mixed-case work IDs cannot starve each other', polled.has('run_a') && polled.has('run_B'));
await server.recordStatement(owner, 'campaign', 'openai-campaign', {...campaign, id:'openai-campaign',version:1}).run();
sql.prepare('UPDATE settings SET secret=? WHERE owner=?').run(await server.encrypt('test-openai-key'), owner);
failUsage=true;
response=await request({action:'start',campaignId:'openai-campaign',role:'cmo'});
check('known OpenAI response ID survives usage storage failure', !response.ok && sql.prepare('SELECT provider_id FROM jobs WHERE campaign_id=?').get('openai-campaign').provider_id==='resp_known');
check('OpenAI exact request is durably prepared', !!sql.prepare("SELECT id FROM records WHERE kind='openai_submission' AND parent_id=?").get('openai-campaign'));
console.log(JSON.stringify({passed: passed.length, checks: passed}));
