import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {SourceTextModule,createContext} from 'node:vm';
import ts from 'typescript';
const context=createContext({console}),cache=new Map();
function moduleFor(path){path=resolve(path);if(cache.has(path))return cache.get(path);const m=new SourceTextModule(ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText,{context,identifier:path});cache.set(path,m);return m;}
const m=moduleFor('lib/role-output.ts');await m.link((s,r)=>moduleFor(resolve(dirname(r.identifier),s+'.ts')));await m.evaluate();
const {roleOutputContract,parseRoleOutput,isQuestionOnly,artifactUsable,upstreamContext}=m.namespace;
const bad='현재 메시지에는 수행할 작업이 명시되지 않았습니다. 원하시는 작업을 선택해 주세요. 1. 시장 조사 2. 전략 수립';
assert.equal(isQuestionOnly(bad),true);
assert.throws(()=>parseRoleOutput(bad,'insight'));
const contract=roleOutputContract('insight');
const valid={contractVersion:contract.version,role:'insight',sections:contract.sections.map(s=>({id:s.id,content:'자료 필요: 현장 관찰이 없습니다. 확인 전에는 가설로 취급하며 메뉴 확정 후 고객에게 직접 질문합니다.'}))};
assert.ok(parseRoleOutput(JSON.stringify(valid),'insight',contract).includes('자료 필요'));
assert.throws(()=>parseRoleOutput(JSON.stringify({...valid,sections:valid.sections.slice(1)}),'insight',contract));
assert.throws(()=>parseRoleOutput(JSON.stringify({...valid,role:'strategy'}),'insight',contract));
assert.throws(()=>parseRoleOutput(JSON.stringify({...valid,sections:valid.sections.map(s=>({...s,content:bad}))}),'insight',contract));
assert.throws(()=>parseRoleOutput(JSON.stringify({...valid,sections:valid.sections.map(s=>({...s,content:'가'.repeat(40001)}))}),'insight',contract));
assert.equal(parseRoleOutput('기존 실행의 사용 가능한 결과','cmo'),'기존 실행의 사용 가능한 결과');
const artifact={id:'a',role:'cmo',content:'검토 가능한 실행 기획',status:'approved',version:1,campaignVersion:2};
assert.equal(artifactUsable(artifact,2),true);
assert.equal(artifactUsable({...artifact,status:'revision'},2),false);
assert.equal(artifactUsable({...artifact,campaignVersion:1},2),false);
assert.equal(artifactUsable({...artifact,content:bad},2),false);
assert.equal(artifactUsable({...artifact,campaignVersion:undefined,origin:'manual'},2),true);
const prior=upstreamContext([{...artifact,content:'a'.repeat(9000)},{...artifact,id:'later',role:'growth'}],'strategy',2);
assert.equal(prior.length,1);assert.equal(prior[0].id,'a');assert.equal(prior[0].excerpt,true);assert.equal(prior[0].originalLength,9000);assert.ok(prior[0].content.length<=6000);
assert.equal(upstreamContext([{...artifact,content:'가'.repeat(9000)}],'quality',2)[0].excerpt,false);
console.log('PASS: structured role output, ODA nonanswers, legacy compatibility, predecessor validity, bounded upstream context');
