// 판매처 주문 조회 어댑터(G2-04/18): 봉인 토큰·읽기 전용 GET·커서는 저장 묶음에서만 전진·실패 백오프·고객 정보 거부·스위치. fetch mocked, 메모리 SQLite real.
import assert from 'node:assert/strict';import {testRuntime} from './helpers/runtime.mjs';
let responder=async()=>new Response('{}',{status:500});const calls=[];let failKind='';
const {load,sql}=testRuntime(async(url,init)=>{calls.push({url:String(url),init});return responder(url,init)},{beforeRun(s){if(failKind&&s.query.startsWith('INSERT INTO records')&&s.values[2]===failKind)throw Error('atomic failure')}});
const server=await load('lib/server.ts'),route=await load('app/api/storefront-pulls/route.ts'),pull=await load('lib/storefront-pull-server.ts'),flags=await load('lib/feature-flags.ts'),pure=await load('lib/storefront-pull.ts');let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='owner',h={'oai-authenticated-user-id':owner,origin:'https://agency.test'};
await server.recordStatement(owner,'brand','b',{id:'b',name:'브랜드'}).run();await server.recordStatement(owner,'store','s',{id:'s',brandId:'b',name:'지점',version:1,status:'active'},'b').run();
const post=async(data,headers=h)=>{const r=await route.POST(new Request('https://agency.test/api/storefront-pulls',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify(data)}));return {status:r.status,body:await r.json()}},get=async()=>{const r=await route.GET(new Request('https://agency.test/api/storefront-pulls',{headers:h}));return r.json()};
const token='tok_'+'a'.repeat(28),input={storeId:'s',sourceKey:'mapdal',baseUrl:'https://shop.example.com/collective/orders',token,intervalMinutes:30};
check((await post({action:'create',input:{...input,baseUrl:'http://shop.example.com/o'}})).status===400,'http rejected');check((await post({action:'create',input:{...input,baseUrl:'https://127.0.0.1/o'}})).status===400,'private host rejected');check((await post({action:'create',input:{...input,baseUrl:'https://shop.example.com/o?key=x'}})).status===400,'query rejected');check((await post({action:'create',input:{...input,token:'short'}})).status===400,'weak token rejected');
let r=await post({action:'create',input});check(r.status===200&&!r.body.connection.enabled&&!('secret' in r.body.connection),'created disabled, secret hidden');const id=r.body.connection.id;
check(!JSON.stringify(await get()).includes(token)&&!JSON.stringify(sql.prepare("SELECT data FROM records WHERE kind='channel_credential'").all()).includes(token),'token never stored or returned in plain text');
check((await pull.pullOnce(owner,id)).status==='idle','disabled connection does not call');check(calls.length===0,'no call while disabled');
await post({action:'enable',id,expectedVersion:1});
const order=(n,p={})=>({order_id:`MD-20260928-AABB${n}`,revision:1,order_date:'2026-09-28',status:'paid',mode:'delivery',paid_amount:12000,refund_amount:0,...p});
const page=(orders,nextCursor,hasMore)=>async()=>new Response(JSON.stringify({orders,nextCursor,hasMore}),{status:200});
responder=page([order('01'),order('02')],'c1',true);r=await pull.pullOnce(owner,id);check(r.status==='processed'&&r.created===2&&r.hasMore,'first page imported');
check(calls[0].init.method==='GET'&&calls[0].init.headers.authorization===`Bearer ${token}`&&calls[0].url==='https://shop.example.com/collective/orders?limit=100','read-only GET with bearer token, no cursor first');
let conn=(await get()).connections[0];check(conn.cursor==='c1'&&conn.lastResult.fetched===2&&conn.failures===0,'cursor advanced with import');
responder=page([order('02'),order('03')],'c2',false);r=await pull.pullOnce(owner,id);check(calls.at(-1).url.includes('cursor=c1')&&r.created===1&&r.duplicates===1,'next page uses cursor; replayed order is duplicate not double count');
conn=(await get()).connections[0];check(conn.cursor==='c2'&&Date.parse(conn.nextAttemptAt)>Date.now()+20*60000,'no more pages waits for interval');
check(sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='store_order'").get().n===3,'three orders stored');
responder=async()=>new Response('{"orders":[],"nextCursor":null,"hasMore":false,"buyer":"x"}',{status:200});r=await pull.pullOnce(owner,id);conn=(await get()).connections[0];check(r.status==='retry'&&conn.lastError==='invalid_response'&&conn.cursor==='c2'&&conn.failures===1,'customer fields rejected, cursor unchanged');
responder=page([{...order('09'),buyer_phone:'010'}],'c9',false);r=await pull.pullOnce(owner,id);conn=(await get()).connections[0];check(conn.lastError==='invalid_response'&&conn.cursor==='c2'&&conn.failures===2,'extra order field rejected');
check(Date.parse(conn.nextAttemptAt)-Date.now()>50*60000,'backoff grows');
responder=async()=>new Response('no',{status:401});r=await pull.pullOnce(owner,id);check((await get()).connections[0].lastError==='unauthorized','401 recorded');
responder=async()=>{throw new Error('socket')};r=await pull.pullOnce(owner,id);check((await get()).connections[0].lastError==='network'&&(await get()).connections[0].cursor==='c2','network error keeps cursor');
responder=async()=>new Response('x'.repeat(300000),{status:200});r=await pull.pullOnce(owner,id);check((await get()).connections[0].lastError==='too_large','oversized body rejected');
responder=page([order('04')],'c3',false);failKind='store_order';r=await pull.pullOnce(owner,id).catch(()=>({status:'threw'}));failKind='';conn=(await get()).connections[0];check(conn.cursor==='c2'&&sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='store_order'").get().n===3,'atomic: failed batch leaves cursor and orders unchanged');
r=await pull.pullOnce(owner,id);check(r.status==='processed'&&(await get()).connections[0].cursor==='c3','recovers on next attempt');
check((await pull.runStorefrontPulls(owner)).status==='idle','worker idle while flag off');await flags.setFeatureFlag(owner,{flag:'storefront_pull',enabled:true},{id:owner,email:null});
sql.prepare("UPDATE records SET data=json_set(data,'$.nextAttemptAt',?) WHERE kind='channel_credential'").run(new Date(Date.now()-1000).toISOString());responder=page([],'c3',false);check((await pull.runStorefrontPulls(owner)).status==='processed','worker pulls due connection when enabled');
check((await post({action:'update',id,expectedVersion:1,input:{sourceKey:'mapdal',baseUrl:'https://other.example.com/orders',intervalMinutes:60}})).status===409,'stale connection version rejected');
const v=(await get()).connections[0].version;r=await post({action:'update',id,expectedVersion:v,input:{sourceKey:'mapdal',baseUrl:'https://other.example.com/orders',intervalMinutes:60}});check(r.status===200&&r.body.connection.cursor===null,'changing source resets cursor');
check((await post({action:'pull_now',id},{'oai-authenticated-user-id':'other',origin:'https://agency.test'})).status!==200,'other owner cannot pull');
check(pure.backoffMs(10,30)===24*3600000,'backoff capped at 24h');check(pure.pullUrl('https://a.example.com/o','x y')==='https://a.example.com/o?cursor=x+y&limit=100','cursor url-encoded');
console.log(JSON.stringify({passed}));
