// UX-PLAN P4·P5: 홈 '오늘의 안건'(GET /api/agenda)과 성장·판매 탭 요약(GET /api/growth/summary). 읽기 전용 집계.
// 인증 mocked, 메모리 SQLite real, 외부 0. 보관 캠페인 제외, 소유자 격리, 다른 캠페인 기록 미포함, 기한 판정을 고정한다.
import assert from 'node:assert/strict';import {testRuntime} from './helpers/runtime.mjs';
const {load}=testRuntime(async()=>{throw Error('external forbidden')});
const server=await load('lib/server.ts'),agendaRoute=await load('app/api/agenda/route.ts'),summaryRoute=await load('app/api/growth/summary/route.ts');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++};
const owner='owner',h={'oai-authenticated-user-id':owner};
const put=(kind,id,data,parent='',who=owner)=>server.recordStatement(who,kind,id,data,parent).run();
const H=3600000,now=Date.now(),iso=t=>new Date(t).toISOString(),day=t=>new Date(t+9*H).toISOString().slice(0,10);
await put('campaign','c1',{id:'c1',brandId:'b',title:'매운 세트 10월',version:1,status:'active'});
await put('campaign','c2',{id:'c2',brandId:'b',title:'보관 캠페인',version:1,status:'active',archivedAt:iso(now-H)});
await put('campaign','c3',{id:'c3',brandId:'b',title:'다른 캠페인',version:1,status:'active'});
await put('growth_cs_ticket','t-over',{id:'t-over',campaignId:'c1',status:'open',input:{summary:'배송 지연 문의',promisedBy:iso(now-H)}},'c1');
await put('growth_cs_ticket','t-soon',{id:'t-soon',campaignId:'c1',status:'open',input:{summary:'옵션 문의',promisedBy:iso(now+2*H)}},'c1');
await put('growth_cs_ticket','t-done',{id:'t-done',campaignId:'c1',status:'resolved',input:{summary:'끝난 문의',promisedBy:iso(now-5*H)}},'c1');
await put('growth_cs_ticket','t-arch',{id:'t-arch',campaignId:'c2',status:'open',input:{summary:'보관 캠페인 문의',promisedBy:iso(now-H)}},'c2');
await put('growth_detected_signal','s1',{id:'s1',campaignId:'c1',status:'new',title:'7일 수요 급증'},'c1');
await put('growth_detected_signal','s2',{id:'s2',campaignId:'c1',status:'acknowledged',title:'확인한 신호'},'c1');
await put('growth_expansion','e1',{id:'e1',campaignId:'c3',status:'proposed',input:{title:'예산 20% 증액'}},'c3');
await put('growth_landing_revision','l1',{id:'l1',campaignId:'c1',status:'draft',input:{title:'가격 문구 수정'}},'c1');
await put('growth_collaboration','co1',{id:'co1',campaignId:'c1',input:{partnerName:'크리에이터 A'},receipts:[{stage:'proposed'},{stage:'agreed'},{stage:'delivered'}]},'c1');
await put('growth_mission','m1',{id:'m1',campaignId:'c1',status:'draft',input:{title:'자연 유입 판매',deadline:day(now+24*H)}},'c1');
await put('growth_mission','m2',{id:'m2',campaignId:'c1',status:'draft',input:{title:'지난 미션',deadline:day(now-3*24*H)}},'c1');
await put('growth_cs_ticket','t-other',{id:'t-other',campaignId:'x',status:'open',input:{summary:'다른 소유자',promisedBy:iso(now-H)}},'x','other');
const unpack=async r=>({status:r.status,body:await r.json()});
const getAgenda=(headers=h)=>agendaRoute.GET(new Request('https://agency.test/api/agenda',{headers})).then(unpack);
let r=await getAgenda({});check(r.status===401,'agenda requires auth');
r=await getAgenda();const a=r.body,ids=a.items.map(i=>i.id);
check(r.status===200,'agenda ok');
check(ids.includes('growth_cs_ticket:t-over')&&a.items.find(i=>i.id==='growth_cs_ticket:t-over').kind==='overdue','overdue CS promise');
check(a.items.find(i=>i.id==='growth_cs_ticket:t-soon')?.kind==='upcoming','CS promise within a day is upcoming');
check(!ids.includes('growth_cs_ticket:t-done')&&!ids.includes('growth_cs_ticket:t-arch')&&!ids.includes('growth_cs_ticket:t-other'),'resolved, archived-campaign and other-owner items excluded');
check(ids.includes('growth_detected_signal:s1')&&!ids.includes('growth_detected_signal:s2'),'only new signals');
check(a.items.find(i=>i.id==='growth_expansion:e1')?.kind==='decision'&&a.items.find(i=>i.id==='growth_expansion:e1')?.campaignTitle==='다른 캠페인','expansion awaiting approval across campaigns');
check(a.items.find(i=>i.id==='growth_landing_revision:l1')?.title.includes('승인 대기'),'landing draft awaits approval');
check(a.items.find(i=>i.id==='growth_collaboration:co1')?.kind==='decision','delivered collaboration awaits approval');
check(a.items.find(i=>i.id==='growth_mission:m1')?.kind==='upcoming'&&a.items.find(i=>i.id==='growth_mission:m2')?.kind==='overdue','mission deadlines');
const kinds=a.items.map(i=>i.kind);check(kinds.indexOf('overdue')<kinds.indexOf('decision')&&kinds.lastIndexOf('decision')<kinds.indexOf('signal')&&kinds.indexOf('signal')<kinds.indexOf('upcoming'),'ordered overdue → decision → signal → upcoming');
check(a.counts.overdue===2&&a.counts.decision===3&&a.counts.signal===1&&a.counts.upcoming===2&&a.total===8,'counts');
check(a.items.every(i=>['decide','execute','observe','prepare','evidence','learn'].includes(i.section)),'each item names a growth section');
const getSummary=(id,headers=h)=>summaryRoute.GET(new Request(`https://agency.test/api/growth/summary?campaignId=${id}`,{headers})).then(unpack);
r=await getSummary('c1');const s=r.body;
check(r.status===200&&s.counts.cs===3&&s.counts.detection===2&&s.counts.landing===1&&s.counts.collaboration===1,'summary counts campaign records only');
check(s.counts.expansion===0,'another campaign is not counted');
check(s.attention.cs==='기한 초과 1건'&&s.attention.detection==='새 신호 1건'&&!s.attention.expansion,'attention flags');
check((await getSummary('c1',{'oai-authenticated-user-id':'other'})).status===404,'owner isolation');
const summaryServer=await load('lib/growth-summary-server.ts'),listed=[...summaryServer.summaryKindFilter.matchAll(/'([a-z_]+)'/g)].map(m=>m[1]).sort();
check(JSON.stringify(listed)===JSON.stringify([...new Set(Object.values(JSON.parse(JSON.stringify(summaryServer.summaryKinds))).flat())].sort()),'SQL kind list equals summaryKinds');
console.log(JSON.stringify({passed}));
