import {ApiError,acquireLock,releaseLock,assertNoActiveJobs,database,identity,secureMutation,json,failure,body,str,num,recordStatement,readRecord,listRecords,eventStatement,validateCampaign,stamp,uid,encrypt,configuration,connection} from '@/lib/server';
import {roles,type Campaign,type Brand,type Artifact,type Metric} from '@/lib/agency';
export async function POST(req:Request){let lockOwner="",lockToken="";try{const owner=identity(req);secureMutation(req);const b=await body(req);lockOwner=owner;lockToken=await acquireLock(owner);const db=database();
if(b.action==='save_campaign'){
 const data=validateCampaign(b.data||{});let campaign:Campaign;const writes:D1PreparedStatement[]=[];
 if(b.id){const old=await readRecord<Campaign>(owner,'campaign',str(b.id,'캠페인',100,true));if(b.version!==old.version)throw new ApiError(409,'다른 화면에서 브리프가 변경됐습니다. 새로고침 후 다시 저장해 주세요.');const running=await db.prepare("SELECT id FROM jobs WHERE owner=? AND campaign_id=? AND status IN ('starting','queued','in_progress','uncertain')").bind(owner,old.id).first();if(running)throw new ApiError(409,'AI 작업이 끝난 후 브리프를 수정해 주세요.');campaign={...old,...data,version:old.version+1,status:'draft',updatedAt:stamp()};const artifacts=await listRecords<Artifact>(owner,'artifact',old.id);for(const a of artifacts)writes.push(recordStatement(owner,'artifact',a.id,{...a,status:'outdated'},old.id));
 }else campaign={...data,id:uid(),status:'draft',version:1,createdAt:stamp(),updatedAt:stamp()};
 writes.push(recordStatement(owner,'campaign',campaign.id,campaign),eventStatement(owner,campaign.id,b.id?'브리프 수정 · 이전 승인은 종료되었습니다.':'새 캠페인 브리프를 만들었습니다.'));await db.batch(writes);return json({id:campaign.id});
}
if(b.action==='save_brand'){await assertNoActiveJobs(owner);const old=await readRecord<Brand>(owner,'brand',str(b.id,'브랜드',100,true));const updated={...old};for(const k of ['description','audience','tone','constraints','knowledge'] as const)updated[k]=str(b.data?.[k]??'',k,k==='knowledge'?30000:5000);const affected=(await listRecords<Campaign>(owner,'campaign')).filter(c=>c.brandId===old.id);const writes=[recordStatement(owner,'brand',old.id,updated),eventStatement(owner,'',`${old.name} 브랜드 지식을 수정했습니다.`)];for(const c of affected){writes.push(recordStatement(owner,'campaign',c.id,{...c,version:c.version+1,status:'draft',updatedAt:stamp()}),eventStatement(owner,c.id,'브랜드 지식 변경 · 기존 작업물을 다시 검토합니다.'));for(const a of await listRecords<Artifact>(owner,'artifact',c.id))writes.push(recordStatement(owner,'artifact',a.id,{...a,status:'outdated'},c.id))}await db.batch(writes);return json({ok:true})}
if(b.action==='save_artifact'){
 await assertNoActiveJobs(owner);const c=await readRecord<Campaign>(owner,'campaign',str(b.campaignId,'캠페인',100,true));const old=b.id?await readRecord<Artifact & {campaignVersion:number}>(owner,'artifact',str(b.id,'작업물',100,true)):null;if(old&&old.campaignId!==c.id)throw new ApiError(400,'캠페인이 일치하지 않습니다.');if(old&&b.version!==old.version)throw new ApiError(409,'작업물이 변경됐습니다. 새로고침 후 다시 저장해 주세요.');if(old?.status==='outdated')throw new ApiError(409,'이전 브리프의 작업물입니다. 새 작업물을 등록하세요.');const role=str(b.role,'담당',100,true);if(!roles.some(r=>r.id===role))throw new ApiError(400,'담당을 선택하세요.');const a={id:old?.id||uid(),campaignId:c.id,campaignVersion:c.version,role,title:str(b.title,'제목',200,true),content:str(b.content,'내용',40000,true),version:(old?.version||0)+1,status:'review',origin:old?.origin||'manual',createdAt:stamp()};const writes=[recordStatement(owner,'artifact',a.id,a,c.id),recordStatement(owner,'campaign',c.id,{...c,status:'review',updatedAt:stamp()}),eventStatement(owner,c.id,`${roles.find(r=>r.id===role)?.name} 작업물 ${old?'수정':'등록'} · v${a.version}`)];for(const downstream of await listRecords<Artifact>(owner,'artifact',c.id)){if(downstream.id!==a.id&&downstream.status!=='outdated'&&roles.findIndex(r=>r.id===downstream.role)>=roles.findIndex(r=>r.id===role))writes.push(recordStatement(owner,'artifact',downstream.id,{...downstream,status:'outdated'},c.id))}if(old){const h={...old,id:uid(),originalId:old.id};writes.push(recordStatement(owner,'history',h.id,h,c.id))}await db.batch(writes);return json({id:a.id})}
if(b.action==='review_artifact'){
 await assertNoActiveJobs(owner);const a=await readRecord<Artifact>(owner,'artifact',str(b.id,'작업물',100,true));if(a.status==='outdated')throw new ApiError(409,'이전 브리프의 작업물은 승인할 수 없습니다.');if(a.version!==b.version)throw new ApiError(409,'작업물이 수정됐습니다. 최신 내용을 확인해 주세요.');if(!['approved','revision'].includes(b.decision))throw new ApiError(400,'검토 결과를 선택하세요.');const note=str(b.note??'','검토 의견',5000);if(b.decision==='revision'&&!note)throw new ApiError(400,'수정 요청 내용을 적어 주세요.');const c=await readRecord<Campaign>(owner,'campaign',a.campaignId);if((a as Artifact & {campaignVersion:number}).campaignVersion!==c.version)throw new ApiError(409,'브리프 버전이 변경됐습니다. 작업물을 다시 작성하세요.');const artifacts=await listRecords<Artifact>(owner,'artifact',c.id);const current=artifacts.filter(x=>x.status!=='outdated').map(x=>x.id===a.id?{...x,status:b.decision}:x);const allApproved=current.length>0&&current.some(x=>x.role==='quality')&&current.every(x=>x.status==='approved');await db.batch([recordStatement(owner,'artifact',a.id,{...a,status:b.decision},c.id),recordStatement(owner,'campaign',c.id,{...c,status:allApproved?'approved':b.decision==='revision'?'revision':'review',updatedAt:stamp()}),eventStatement(owner,c.id,`${a.title} v${a.version} ${b.decision==='approved'?'승인':'수정 요청'}${note?' · '+note:''}`)]);return json({ok:true})}
if(b.action==='save_metric'){
 const c=await readRecord<Campaign>(owner,'campaign',str(b.campaignId,'캠페인',100,true));if(b.id){const old=await readRecord<Metric>(owner,'metric',str(b.id,'성과',100,true));if(old.campaignId!==c.id)throw new ApiError(400,'캠페인이 일치하지 않습니다.')};const m:Metric={id:b.id||uid(),campaignId:c.id,period:str(b.period,'측정 기간',200,true),revenue:num(b.revenue,'순매출'),variableCosts:num(b.variableCosts,'변동 원가'),adSpend:num(b.adSpend,'매체비'),productionCost:num(b.productionCost,'제작비'),orders:num(b.orders,'주문 수'),baselineContribution:b.baselineContribution===null||b.baselineContribution===''?null:num(b.baselineContribution,'비교 기준 공헌이익'),notes:str(b.notes??'','측정 메모',5000)};await db.batch([recordStatement(owner,'metric',m.id,m,c.id),eventStatement(owner,c.id,`${m.period} 성과를 기록했습니다.`)]);return json({id:m.id})}
if(b.action==='save_connection'){
 await assertNoActiveJobs(owner);const model=str(b.model,'모델',150,true);if(!/^[a-zA-Z0-9_.:-]+$/.test(model))throw new ApiError(400,'모델 ID를 확인하세요.');const key=str(b.key,'API 키',500,true);if(!key.startsWith('sk-'))throw new ApiError(400,'OpenAI API 키를 확인해 주세요.');let check:Response;try{check=await fetch('https://api.openai.com/v1/models/'+encodeURIComponent(model),{headers:{Authorization:`Bearer ${key}`},signal:AbortSignal.timeout(15000)})}catch{throw new ApiError(502,'OpenAI 연결을 확인하지 못했습니다. 잠시 후 다시 시도하세요.')}if(!check.ok)throw new ApiError(400,check.status===401?'API 키 인증에 실패했습니다.':'이 키로 선택한 모델을 사용할 수 없습니다. 모델 ID와 권한을 확인하세요.');const secret=await encrypt(key);await db.prepare('INSERT INTO settings(owner,secret,model,updated_at) VALUES(?,?,?,?) ON CONFLICT(owner) DO UPDATE SET secret=excluded.secret,model=excluded.model,updated_at=excluded.updated_at').bind(owner,secret,model,stamp()).run();return json({ok:true})}
if(b.action==='disconnect'){await assertNoActiveJobs(owner);await db.prepare('DELETE FROM settings WHERE owner=?').bind(owner).run();return json({ok:true})}
throw new ApiError(400,'지원하지 않는 작업입니다.');
}catch(e){return failure(e)}finally{if(lockToken)await releaseLock(lockOwner,lockToken)}}
