import type {Campaign} from '@/lib/agency';
import {metaCreativeContext as context,inspectMetaCreative as inspect,viewMetaCreative as view} from '@/lib/meta-creative-server';
import {parseMetaCreative,MetaCreativeError,type MetaCreativeReview} from '@/lib/meta-creative-review';
import {ApiError,acquireLock,actor,body,database,eventStatement,failure,json,readRecord,recordStatement,releaseLock,requireAdminActor,secureMutation,stamp,str} from '@/lib/server';
export async function GET(req:Request){try{const who=await actor(req),c=await readRecord<Campaign>(who.owner,'campaign',str(new URL(req.url).searchParams.get('campaignId'),'캠페인',100,true));return json(view(c,await context(who.owner,c),who.role!=='member'))}catch(e){return failure(e)}}
export async function POST(req:Request){let owner='',lock='';try{const who=await requireAdminActor(req);secureMutation(req);const b=await body(req);if(b.action!=='save'&&b.action!=='review')throw new ApiError(400,'지원하지 않는 검토 작업입니다.');const input=parseMetaCreative(b.input);owner=who.owner;lock=await acquireLock(owner);const c=await readRecord<Campaign>(owner,'campaign',str(b.campaignId,'캠페인',100,true)),x=await context(owner,c);
 if(c.status==='archived'||b.campaignVersion!==c.version||b.expectedVersion!==(x.saved?.version??0)||b.planVersion!==(x.plan?.version??0))throw new ApiError(409,'계획이나 캠페인이 변경되었습니다. 최신 내용을 다시 확인하세요.');
 if(input.creativeId&&!x.creatives.some(v=>v.id===input.creativeId))throw new ApiError(404,'이 캠페인의 소재가 아닙니다.');if(input.experimentId&&!x.experiments.some(v=>v.id===input.experimentId&&v.kind===input.experimentKind))throw new ApiError(404,'이 캠페인의 실험이 아닙니다.');
 const checked=inspect(c,x,input);if(b.action==='review'&&(checked.issues.length||b.warningsAcknowledged!==true))throw new ApiError(409,checked.issues.length?checked.issues.join(' '):'자동 점검의 경고와 한계를 확인하세요.');
 const now=stamp(),saved:MetaCreativeReview={id:c.id,campaignId:c.id,brandId:c.brandId,campaignVersion:c.version,planVersion:x.plan?.version??0,version:(x.saved?.version??0)+1,input,status:b.action==='review'?'reviewed':'draft',factRefs:x.facts.confirmed.map(f=>({id:f.id,version:f.version})),creativeVersion:checked.creative?.version??null,pngHash:checked.creative?.pngHash??null,experimentVersion:checked.experiment?.version??null,reviewedAt:b.action==='review'?now:null,reviewedBy:b.action==='review'?who.id:null,updatedAt:now,updatedBy:who.id};
 await database().batch([recordStatement(owner,'meta_ads_creative_review',c.id,saved,c.id),eventStatement(owner,c.id,`Meta 소재안 v${saved.version} ${saved.status==='reviewed'?'검토 기록':'초안 저장'} · 광고 집행 미승인`,{id:who.id,email:who.email})]);return json(view(c,{...x,saved},true));
 }catch(e){return failure(e instanceof MetaCreativeError?new ApiError(400,e.message):e)}finally{if(lock)await releaseLock(owner,lock)}}
