'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Mic,Square,Upload,FileText,Check,ChevronRight,LoaderCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {api} from '@/lib/client';
import {extractArchiveFile} from '@/lib/archive-upload';
import {interviewSections,interviewProgress,recommendedQuestions,audioFile,type InterviewAnswers,type InterviewSource,type InterviewSectionId} from '@/lib/brand-interview';
import {interviewIndustries,interviewIndustry,industryQuestionGuide,type InterviewIndustryId} from '@/lib/brand-interview-industries';
import type {ArchiveSourceSummary} from '@/lib/archive';
import {toast} from 'sonner';
const MAX_FILE=8*1024*1024;
type PublicInterview=Omit<InterviewSource,'interview'>&{transcriptionPending?:boolean;interview:Omit<InterviewSource['interview'],'job'>&{job?:{id:string;status:'queued'|'uncertain'|'completed'|'failed'|'cancelled';error?:string;createdAt:string;updatedAt:string}}};
export function BrandInterviewPanel({brandId,sources,onSaved,onCampaign,canManage}:{brandId:string;sources:ArchiveSourceSummary[];onSaved:()=>Promise<void>;onCampaign:(goal?:string)=>void;canManage:boolean}){
 const [industry,setIndustry]=useState<InterviewIndustryId>('general'),[loading,setLoading]=useState(true);
 const [items,setItems]=useState<PublicInterview[]>([]),[current,setCurrent]=useState<PublicInterview|null>(null),[title,setTitle]=useState('브랜드 담당자 인터뷰'),[role,setRole]=useState('점주'),[answers,setAnswers]=useState<InterviewAnswers>({}),[attachments,setAttachments]=useState<string[]>([]),[section,setSection]=useState<InterviewSectionId>('story'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[dirty,setDirty]=useState(false),[drag,setDrag]=useState(false),[consent,setConsent]=useState(false),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[recorded,setRecorded]=useState<File|null>(null),[playback,setPlayback]=useState(''),[selected,setSelected]=useState<number[]>([]);
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),fileInput=useRef<HTMLInputElement>(null),mounted=useRef(true),currentRef=useRef(current),inFlight=useRef(false);
 useEffect(()=>{currentRef.current=current},[current]);
 const running=!!current?.interview.job&&['queued','uncertain'].includes(current.interview.job.status),locked=loading||busy||running||recording;
 const choose=useCallback((item:PublicInterview|null)=>{setCurrent(item);setIndustry(interviewIndustry(item?.interview.industry).id);setTitle(item?.title||'브랜드 담당자 인터뷰');setRole(item?.interview.role||'점주');setAnswers(item?.interview.answers||{});setAttachments(item?.interview.attachments||[]);setSelected([]);setDirty(false)},[]);
 const load=useCallback(async()=>{const r=await fetch('/api/archive/interview?brandId='+encodeURIComponent(brandId));const d=await r.json() as {error?:string;interviews:PublicInterview[]};if(!r.ok)throw new Error(d.error||'인터뷰를 불러오지 못했습니다.');setItems(d.interviews);return d.interviews as PublicInterview[]},[brandId]);
 useEffect(()=>{mounted.current=true;void Promise.resolve().then(load).then(rows=>{if(mounted.current)choose(rows[0]||null)}).catch(e=>{if(mounted.current)setError(e.message)}).finally(()=>{if(mounted.current)setLoading(false)});return()=>{mounted.current=false;if(recorder.current&&recorder.current.state!=='inactive')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop())}},[load,choose]);
 useEffect(()=>{const latest=sources.find(s=>s.id===current?.id);if(!latest||!current||dirty||busy||latest.version===current.version)return;let live=true;void Promise.resolve().then(load).then(rows=>{if(live){const updated=rows.find(s=>s.id===current.id);if(updated)choose(updated)}}).catch(e=>setError(e.message));return()=>{live=false}},[sources,current,dirty,busy,load,choose]);
 useEffect(()=>{if(!recording)return;const timer=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(timer)},[recording]);
 useEffect(()=>()=>{if(playback)URL.revokeObjectURL(playback)},[playback]);
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(dirty||recording||recorded){e.preventDefault();e.returnValue=''}};const navigate=(e:MouseEvent)=>{if(!(dirty||recording||recorded)||!(e.target instanceof Element)||e.target.closest('.interview-studio')||e.target.closest('[role=tab]')||!e.target.closest('a,button'))return;if(!window.confirm('저장하지 않은 인터뷰 또는 녹음이 있습니다. 버리고 이동할까요?')){e.preventDefault();e.stopImmediatePropagation()}};window.addEventListener('beforeunload',leave);document.addEventListener('click',navigate,true);return()=>{window.removeEventListener('beforeunload',leave);document.removeEventListener('click',navigate,true)}},[dirty,recording,recorded]);
 const call=useCallback(async(action:string,extra:Record<string,unknown>={},base=currentRef.current)=>await api(action,{brandId,id:base?.id,version:base?.version,...extra},'/api/archive/interview') as unknown as PublicInterview,[brandId]);
 async function save(ids=attachments){const next=await call('save',{title,role,industry,answers,attachments:ids});choose(next);await load();await onSaved();return next}
 async function perform(fn:()=>Promise<void>){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{inFlight.current=false;setBusy(false)}}
 async function update(action:string,extra:Record<string,unknown>={}){const next=await call(action,extra);choose(next);await load();if(action==='apply')await onSaved()}
 useEffect(()=>{if(!running)return;const timer=setInterval(()=>{if(inFlight.current)return;inFlight.current=true;void call('poll').then(s=>{if(mounted.current){setCurrent(s);setItems(rows=>rows.map(x=>x.id===s.id?s:x))}}).catch(e=>setError(e.message)).finally(()=>{inFlight.current=false})},6000);return()=>clearInterval(timer)},[running,call]);
 async function uploadFiles(files:File[]){
  const ids=[...attachments];
  for(const file of files){
   if(ids.length>=20)throw new Error('첨부는 20개까지 가능합니다.');
   if(!file.size||file.size>MAX_FILE)throw new Error(file.name+': 8MB 이하 파일을 선택해 주세요.');
   const extracted=audioFile(file.name)?{content:'',extraction:'전사 대기',scope:'녹음 원본'}:await extractArchiveFile(file);
   const form=new FormData();form.set('brandId',brandId);form.set('file',file);form.set('title',file.name);form.set('content',extracted.content);form.set('extraction',extracted.extraction);form.set('extractionScope',extracted.scope);
   const r=await fetch('/api/archive/file',{method:'POST',body:form});const d=await r.json() as {id:string;error?:string};if(!r.ok)throw new Error(d.error||'파일 보관 실패');ids.push(d.id);setAttachments([...ids]);setDirty(true);
  }
  await save(ids);toast.success('원본 파일과 인터뷰를 보관했습니다.');
 }
 async function beginRecording(){
  if(!consent)throw new Error('녹음 참여자의 동의를 확인해 주세요.');
  if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined')throw new Error('이 브라우저는 녹음을 지원하지 않습니다. 녹음 파일을 첨부해 주세요.');
  if(recorded)throw new Error('현재 녹음을 먼저 보관하거나 다운로드한 뒤 삭제하세요.');
  const media=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current){media.getTracks().forEach(t=>t.stop());return}stream.current=media;
  const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(t=>MediaRecorder.isTypeSupported(t));
  let rec:MediaRecorder;try{rec=new MediaRecorder(media,{...(mime?{mimeType:mime}:{}),audioBitsPerSecond:64000})}catch(e){media.getTracks().forEach(t=>t.stop());throw e}
  recorder.current=rec;const chunks:Blob[]=[];let size=0;setSeconds(0);
  rec.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);size+=e.data.size;if(size>=7*1024*1024&&rec.state!=='inactive'){rec.stop();toast.info('녹음 한도에 도달해 중지했습니다. 보관 후 다음 구간을 녹음하세요.')}}};
  rec.onerror=()=>{setError('녹음이 중단됐습니다. 저장된 구간을 확인하세요.');if(rec.state!=='inactive')rec.stop();media.getTracks().forEach(t=>t.stop())};
  rec.onstop=()=>{media.getTracks().forEach(t=>t.stop());recorder.current=null;stream.current=null;if(!mounted.current)return;setRecording(false);const type=rec.mimeType||mime||'audio/webm';if(chunks.length){const file=new File(chunks,'인터뷰-'+new Date().toISOString().replace(/[:.]/g,'-')+(type.includes('mp4')?'.m4a':type.includes('ogg')?'.ogg':'.webm'),{type});setRecorded(file);setPlayback(URL.createObjectURL(file))}};
  rec.start(1000);setRecording(true);
 }
 const tailored=industryQuestionGuide(industry,section);
 const active=interviewSections.find(s=>s.id===section)!;const progress=interviewProgress(answers);const files=attachments.map(id=>sources.find(s=>s.id===id)).filter((s):s is ArchiveSourceSummary=>!!s);const proposals=current?.interview.proposals||[];
 return <section className="interview-studio">
  <header className="interview-heading"><div><p className="eyebrow">BRAND INTERVIEW</p><h3>캠페인을 결정할 수 있는 정보를 모으세요</h3><p>누구에게 무엇을 팔지, 얼마를 쓰고 무엇으로 성과를 확인할지 결정하기 위한 인터뷰입니다.</p></div><span className="interview-progress">{progress} / 8 섹션 기록</span></header>
  <p className="subtle-note">먼저 목표·성과·예산을 합의한 뒤 상품·고객·채널을 확인하세요. 수치는 기간·단위·자료 출처를 함께 기록하고, 모르면 ‘확인 필요 / 담당 역할 / 확인일’로 남겨주세요. 고객 개인 정보 대신 익명 사례·집계 자료를 사용하세요.</p>
  {loading&&<p role="status">인터뷰를 불러오는 중입니다.</p>}
  {error&&<p className="load-error" role="alert">{error}</p>}
  <div className="interview-toolbar"><NativeSelect aria-label="인터뷰 선택" disabled={locked} value={current?.id||''} onChange={e=>{if(dirty&&!window.confirm('저장하지 않은 답변을 버리고 이동할까요?'))return;choose(items.find(s=>s.id===e.target.value)||null)}}><NativeSelectOption value="">새 인터뷰</NativeSelectOption>{items.map(i=><NativeSelectOption key={i.id} value={i.id}>{i.title}</NativeSelectOption>)}</NativeSelect><Button variant="outline" disabled={locked} onClick={()=>{if(!dirty||window.confirm('저장하지 않은 답변을 버리고 새로 시작할까요?'))choose(null)}}>새 인터뷰</Button><Button disabled={locked} onClick={()=>void perform(async()=>{await save();toast.success('인터뷰를 저장했습니다.')})}>{busy&&<LoaderCircle className="spin"/>}{dirty?'변경 내용 저장':'인터뷰 저장'}</Button></div>
  <div className="form-two"><label className="field"><span>인터뷰 제목</span><Input value={title} maxLength={200} disabled={locked} onChange={e=>{setTitle(e.target.value);setDirty(true)}}/></label><label className="field"><span>인터뷰 대상 역할</span><Input value={role} maxLength={100} disabled={locked} placeholder="점주 · 브랜드 담당자 · 매장 매니저" onChange={e=>{setRole(e.target.value);setDirty(true)}}/></label></div>
  <label className="field"><span>업종별 질문지</span><NativeSelect aria-label="업종별 질문지" disabled={locked} value={industry} onChange={e=>{setIndustry(e.target.value as InterviewIndustryId);setDirty(true)}}>{interviewIndustries.map(i=><NativeSelectOption key={i.id} value={i.id}>{i.label}</NativeSelectOption>)}</NativeSelect><small>{interviewIndustry(industry).focus} · 공통 필수 질문은 그대로 유지됩니다. 업종을 바꿔도 작성한 답변은 지워지지 않습니다.</small></label>
  <div className="interview-layout"><nav aria-label="인터뷰 섹션">{interviewSections.map((s,i)=><button key={s.id} aria-current={section===s.id?'step':undefined} onClick={()=>setSection(s.id)}><span>{answers[s.id]?.trim()?<Check size={15}/>:String(i+1).padStart(2,'0')}</span>{s.title}<ChevronRight size={14}/></button>)}</nav><div className="interview-answer"><p className="eyebrow">공통 필수 질문</p><h4>{active.question}</h4><div className="interview-question-purpose"><p><b>왜 필요한가요</b>{active.why}</p><p><b>캠페인에서 결정할 것</b>{active.decision}</p><p><b>확보할 정보</b>{active.fields}</p><details><summary>답변 예시 보기 · 가상 예시, 실제 브랜드 정보 아님</summary><p>{active.example}</p><small>예시를 사실로 복사하지 말고 실제 자료로 확인한 내용만 기록하세요.</small></details></div>{tailored&&<aside className="interview-industry-question"><p className="eyebrow">{interviewIndustry(industry).label} · 업종 질문</p><h4>{tailored.question}</h4><div className="interview-question-purpose"><p><b>왜 필요한가요</b>{tailored.why}</p><p><b>캠페인에서 결정할 것</b>{tailored.decision}</p><p><b>확인할 자료</b>{tailored.evidence}</p></div><small>공통 질문과 함께 확인하고 아래 답변란에 기록하세요. 자료가 없으면 확인할 담당과 날짜를 남기세요.</small></aside>}<label className="field"><span>{active.title} · 답변</span><Textarea rows={9} value={answers[section]||''} maxLength={5000} disabled={locked} placeholder={active.fields+'\n기간·단위·자료 출처: \n확인 필요 / 담당 역할 / 확인일: '} onChange={e=>{setAnswers({...answers,[section]:e.target.value});setDirty(true)}}/></label><p className="subtle-note">{(answers[section]||'').length.toLocaleString()} / 5,000자</p><details open><summary>답변을 실행안으로 좁히는 추가 질문</summary><ul>{active.followupGuides.map(q=><li key={q.question}><p>{q.question}</p><p className="subtle-note"><b>왜 필요한가요: </b>{q.why}<br/><b>캠페인 활용: </b>{q.decision}</p></li>)}</ul></details><div className="form-actions"><Button variant="outline" disabled={section==='story'} onClick={()=>setSection(interviewSections[interviewSections.findIndex(s=>s.id===section)-1].id)}>이전 질문</Button><Button variant="outline" disabled={section==='campaign'} onClick={()=>setSection(interviewSections[interviewSections.findIndex(s=>s.id===section)+1].id)}>다음 질문<ChevronRight/></Button></div></div></div>
  <aside className="interview-recommendations"><h4>지금 더 물어보면 좋은 질문</h4><p className="subtle-note">미입력·짧은 메모를 기준으로 제안합니다. 답변의 정확성이나 충분성을 자동 판정하지 않습니다.</p>{recommendedQuestions(answers,industry).map(q=><button key={q.section+q.question} onClick={()=>setSection(q.section)}><small>{q.reason}</small><span>{q.question}</span></button>)}{progress===8&&<p>8개 섹션에 메모가 있습니다. 기록 개수는 캠페인 준비 완료를 뜻하지 않습니다. 타깃·상품 이익·혜택·예산·전환 경로·측정 자료와 미확정 사항을 확인해 주세요.</p>}</aside>
  <div className="interview-capture"><section><h4><Upload size={18}/>인터뷰와 브랜드 자료 첨부</h4><div className={'interview-drop '+(drag?'dragging':'')} onDragOver={e=>{e.preventDefault();if(!locked)setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(!locked)void perform(()=>uploadFiles(Array.from(e.dataTransfer.files)))}}><FileText size={28}/><p>파일을 여기에 끌어다 놓으세요</p><small>TXT · MD · PDF · DOCX · CSV · JSON · 이미지 · MP3 · WAV · M4A · WEBM · OGG<br/>파일당 8MB, 인터뷰당 20개. Plaud 전사 TXT도 사용할 수 있습니다.</small><input ref={fileInput} type="file" multiple hidden accept=".txt,.md,.pdf,.docx,.csv,.json,.png,.jpg,.jpeg,.webp,.mp3,.wav,.m4a,.mp4,.webm,.ogg" onChange={e=>{const picked=Array.from(e.target.files||[]);e.target.value='';void perform(()=>uploadFiles(picked))}}/><Button variant="outline" disabled={locked} onClick={()=>fileInput.current?.click()}>파일 선택</Button></div><ul className="interview-files">{files.map(f=><li key={f.id}><div><a href={'/api/archive/file?id='+encodeURIComponent(f.id)}>{f.fileName||f.title}</a><small>{f.extraction||'자료 보관됨'}</small></div>{audioFile(f.fileName||'')&&!f.characters&&<Button size="sm" variant="outline" disabled={locked||!consent} onClick={()=>void perform(async()=>{const s=dirty?await save():current;const result=await call('transcribe',{sourceId:f.id,consent},s);await onSaved();if(result.transcriptionPending)toast.info('전사 중입니다. 잠시 후 음성 전사를 다시 눌러 결과를 확인하세요. 중복 실행되지 않습니다.');else toast.success('전사 완료. 자동 정리로 섹션에 배치하세요.')})}>음성 전사</Button>}<Button size="sm" variant="ghost" disabled={locked} aria-label={(f.fileName||f.title)+' 인터뷰에서 제외'} onClick={()=>{setAttachments(attachments.filter(id=>id!==f.id));setDirty(true)}}>연결 해제</Button></li>)}</ul></section>
  <section><h4><Mic size={18}/>대화 녹음</h4><p>대화에 집중하고, 끝난 뒤 원문을 확인하며 정리하세요.</p><label className="archive-check"><input type="checkbox" checked={consent} disabled={recording} onChange={e=>setConsent(e.target.checked)}/><span>참여자에게 녹음·보관 및 연결된 음성 전사 서비스로의 전송 동의를 받았습니다.</span></label><div className="interview-recorder" aria-live="polite"><strong>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong>{recording?<Button onClick={()=>recorder.current?.stop()}><Square/>녹음 종료</Button>:<Button variant="outline" disabled={loading||busy||running||!consent||!!recorded} onClick={()=>void perform(beginRecording)}><Mic/>녹음 시작</Button>}</div><p className="subtle-note">약 15분마다 나누어 녹음하세요. 화면을 이동하기 전에 원본을 보관해 주세요.</p>{recorded&&<div className="interview-recorded"><audio controls src={playback}/><a href={playback} download={recorded.name}>녹음 원본 다운로드</a><Button disabled={locked} onClick={()=>void perform(async()=>{await uploadFiles([recorded]);setRecorded(null)})}>녹음 원본 보관</Button><Button variant="ghost" disabled={locked} onClick={()=>{if(window.confirm('보관하지 않은 녹음을 삭제할까요?'))setRecorded(null)}}>녹음 삭제</Button></div>}</section></div>
  <section className="interview-organize"><div><h4>인터뷰를 섹션별로 자동 정리</h4><p>텍스트와 전사문을 읽고, 원문 인용과 함께 답변을 제안합니다. 기존 답변은 선택한 내용과 합쳐집니다.</p></div><Button disabled={locked||(!current&&!dirty)} onClick={()=>void perform(async()=>{const s=await save();choose(await call('start',{},s));await load()})}>HERMES로 자동 정리</Button>{running&&<><p role="status"><LoaderCircle className="spin" size={16}/> {current?.interview.job?.status==='uncertain'?'접수 확인 필요':'정리 중'} · 다른 작업을 해도 HERMES에서 계속 진행합니다.</p><Button variant="outline" disabled={busy} onClick={()=>void perform(()=>update('poll'))}>기존 요청 확인</Button><Button variant="ghost" disabled={busy} onClick={()=>void perform(()=>update('cancel'))}>정리 중지</Button></>}{current?.interview.job?.error&&<p role="alert">{current.interview.job.error}</p>}
  {!!proposals.length&&<div className="interview-proposals"><h4>섹션별 제안 · {proposals.length}개</h4>{proposals.map((p,i)=><label key={i}><input type="checkbox" checked={selected.includes(i)} onChange={e=>setSelected(e.target.checked?[...selected,i]:selected.filter(x=>x!==i))}/><div><b>{interviewSections.find(s=>s.id===p.section)?.title}</b><p>{p.answer}</p><blockquote>{p.quote}</blockquote><small>출처: {sources.find(s=>s.id===p.sourceId)?.title||current?.title}</small>{answers[p.section]&&<p className="subtle-note">기존 답변이 있습니다. 반영하면 아래에 추가됩니다.</p>}</div></label>)}<Button disabled={locked||!selected.length||dirty} onClick={()=>void perform(()=>update('apply',{selected}))}>선택한 답변을 섹션에 반영</Button>{dirty&&<p>수기 변경을 먼저 저장해 주세요.</p>}</div>}</section>
  <footer className="interview-footer"><p>답변 반영 후에는 자료 아카이브에서 원문을 대조하고 ‘내용을 확인하고 사용’을 눌러 주세요. 확정한 인터뷰만 캠페인의 근거가 됩니다.</p><Button variant="outline" disabled={!current||current.status!=='confirmed'||dirty||locked} onClick={()=>onCampaign(answers.campaign||answers.goals)}>인터뷰를 바탕으로 캠페인 작성<ChevronRight/></Button>{!canManage&&<small>자료 확정은 관리자에게 요청해 주세요.</small>}</footer>
 </section>;
}
