'use client';
import {DeepResearchPanel} from './deep-research-panel';
import {clientId} from '@/lib/client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Plus,Upload,Search,FileText,ExternalLink,Check,LoaderCircle,RefreshCw,Pause} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {toast} from 'sonner';
import {api,type WorkspaceData} from '@/lib/client';
import type {Brand} from '@/lib/agency';
import {ResearchWorkerNotice} from './research-worker-panel';
import {archiveCategories,metricFields,researchStages,researchActive,dashboardMetrics,comparablePrevious,metricReferences,type ArchiveData,type ArchiveSource,type ChannelObservation,type MetricField,type BrandIntake,type PublicResearch} from '@/lib/archive';
import {extractArchiveFile} from '@/lib/archive-upload';
const blankIntake:BrandIntake={website:'',socialLinks:'',market:'',clientNeed:'',competitors:''};
const date=()=>new Date().toISOString().slice(0,10);
const post=async(action:string,data:Record<string,unknown>={},path='/api/archive')=>api(action,data,path);
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function IntakeFields({value,onChange}:{value:BrandIntake;onChange:(v:BrandIntake)=>void}){return <>{([['website','공식 웹사이트'],['socialLinks','공식 SNS · 판매 채널 URL'],['market','시장 · 대상 지역'],['clientNeed','의뢰 목적 · 해결하고 싶은 문제'],['competitors','경쟁 브랜드 · 고객의 대안']] as const).map(([k,label])=><Field key={k} label={label}>{k==='website'?<Input type="url" value={value[k]} onChange={e=>onChange({...value,[k]:e.target.value})} placeholder="https://…"/>:<Textarea rows={2} value={value[k]} onChange={e=>onChange({...value,[k]:e.target.value})}/>}</Field>)}</>}
export function CreateBrandDialog({open,onClose,onCreated,connection}:{open:boolean;onClose:()=>void;onCreated:(id:string)=>Promise<void>;connection:WorkspaceData['connection']}){
 const[name,setName]=useState(''),[category,setCategory]=useState(''),[description,setDescription]=useState(''),[intake,setIntake]=useState(blankIntake),[auto,setAuto]=useState(true),[busy,setBusy]=useState(false);const id=useRef('');
 useEffect(()=>{if(open){setName('');setCategory('');setDescription('');setIntake(blankIntake);id.current=clientId()}},[open]);
 return <Dialog open={open} onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>브랜드 등록</DialogTitle><DialogDescription>의뢰 목적과 공식 채널을 알려주면 조사 범위를 더 정확하게 잡을 수 있습니다.</DialogDescription></DialogHeader><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const r=await post('create_brand',{id:id.current,data:{name,category,description,intake},autoResearch:auto});onClose();window.dispatchEvent(new Event('brand-research-queued'));toast.success('브랜드가 등록됐습니다.'+(r.researchQueued?' 심층 조사는 백그라운드에서 시작합니다.':''));await onCreated(r.id)}catch(err){toast.error((err as Error).message)}finally{setBusy(false)}}}><div className="form-two"><Field label="브랜드 이름"><Input required value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="업종"><Input required value={category} onChange={e=>setCategory(e.target.value)} placeholder="예: 베이커리 · 뷰티"/></Field></div><Field label="간단한 소개"><Textarea value={description} onChange={e=>setDescription(e.target.value)}/></Field><IntakeFields value={intake} onChange={setIntake}/><label className="archive-check"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>등록 후 백그라운드 심층 조사</label><p className="subtle-note">등록은 바로 완료되며, HERMES 연결 시 심층 조사를 백그라운드로 접수합니다. 미연결이면 아카이브를 먼저 만들고 자료를 직접 추가할 수 있습니다.</p><Button disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Plus/>}브랜드 등록</Button></form></DialogContent></Dialog>;
}
const initial:ArchiveData={sources:[],observations:[],diagnostics:[],research:[],state:{id:'',revision:0,updatedAt:''},storageReady:false};
export function BrandArchive({brand,workspace,onBack,onEdit,onConnect,onCampaign,onReload}:{brand:Brand;workspace:WorkspaceData;onBack:()=>void;onEdit:()=>void;onConnect:()=>void;onCampaign:(goal:string)=>void;onReload:()=>Promise<void>}){
 const[syncError,setSyncError]=useState('');
 const[data,setData]=useState<ArchiveData>(initial),[tab,setTab]=useState('overview'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[paused,setPaused]=useState(false),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[add,setAdd]=useState(false),[metricOpen,setMetricOpen]=useState(false),[selectedMetric,setSelectedMetric]=useState(''),[source,setSource]=useState<ArchiveSource|null>(null),[intake,setIntake]=useState<BrandIntake>(brand.intake||blankIntake);const polling=useRef(false);
 const load=useCallback(async()=>{const r=await fetch('/api/archive?brandId='+encodeURIComponent(brand.id));const d=await r.json() as ArchiveData & {error?:string};if(!r.ok)throw new Error(d.error||'아카이브를 불러오지 못했습니다.');setData(d as ArchiveData);setError('')},[brand.id]);
 useEffect(()=>{setData(initial);setIntake(brand.intake||blankIntake);void load().catch(e=>setError(e.message))},[brand,load]);
 useEffect(()=>{const update=(event:Event)=>{if((event as CustomEvent).detail===brand.id)void load().catch(()=>{})};window.addEventListener('brand-research-updated',update);return()=>window.removeEventListener('brand-research-updated',update)},[brand.id,load]);
 useEffect(()=>{setSyncError('');const sync=(event:Event)=>{const d=(event as CustomEvent).detail;if(!d.brandId||d.brandId===brand.id)setSyncError(d.error)};window.addEventListener('brand-research-sync',sync);return()=>window.removeEventListener('brand-research-sync',sync)},[brand.id]);
 const active=data.research.find(researchActive);const latest=data.research[0];const diagnosis=data.diagnostics[0];const fresh=diagnosis?.archiveRevision===data.state.revision;
 useEffect(()=>{if(!active||paused)return;const timer=setInterval(async()=>{if(polling.current)return;polling.current=true;try{await load()}catch(e){setPaused(true);setError((e as Error).message)}finally{polling.current=false}},4000);return()=>clearInterval(timer)},[active?.id,active?.status,paused,load]);
 async function research(mode:'deep'|'classify',previousResearchId?:string){if(!workspace.connection.configured||workspace.connection.provider!=='hermes'){onConnect();return}setBusy(true);try{await post('start',{id:clientId(),brandId:brand.id,mode,previousResearchId},'/api/archive/research');setPaused(false);window.dispatchEvent(new Event('brand-research-queued'));await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function control(action:string){if(!active)return;setBusy(true);try{await post(action,{id:active.id},'/api/archive/research');setPaused(false);window.dispatchEvent(new Event('brand-research-queued'));await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const current=data.observations.find(o=>o.id===selectedMetric)||data.observations[0],previous=current?comparablePrevious(current,data.observations):undefined;
 const metrics=dashboardMetrics(current),prior=dashboardMetrics(previous),confirmed=data.sources.filter(s=>s.status==='confirmed').length;
 const shown=data.sources.filter(s=>(category==='all'||s.category===category)&&(!query||[s.title,s.excerpt].some(t=>t.toLowerCase().includes(query.toLowerCase()))));
 async function reviewSource(status:ArchiveSource['status']){if(!source)return;setBusy(true);try{await post('review_source',{brandId:brand.id,id:source.id,version:source.version,status});setSource(null);await load()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <section className="brand-archive"><button className="archive-back" onClick={onBack}><ArrowLeft size={16}/>브랜드 목록</button><header className="archive-header"><span className="archive-monogram" style={{background:brand.bg,color:brand.color}}>{brand.short}</span><div><p className="eyebrow">BRAND ARCHIVE</p><h2>{brand.name}</h2><p>{brand.description||'브랜드의 근거를 모으고 다음 전략을 결정합니다.'}</p></div><Button variant="outline" onClick={onEdit}>기본 정보 수정</Button></header>
 <div className="archive-progress">{[['01','의뢰 이해',!!brand.intake?.clientNeed],['02','근거 축적',!!data.sources.length],['03','브랜드 진단',!!diagnosis&&fresh],['04','전략 준비',diagnosis?.status==='confirmed'&&fresh]].map(([n,label,done])=><div key={String(n)} className={done?'done':''}><small>{n}</small><b>{label}</b><span>{done?'기록됨':'준비 중'}</span></div>)}</div>
 <div className="archive-actions"><Button disabled={busy||!!active} onClick={()=>void research('deep')}><Search/>심층 조사 시작</Button><Button variant="outline" disabled={!!active} onClick={()=>setAdd(true)}><Upload/>자료 추가</Button><Button variant="outline" disabled={busy||!!active||!data.sources.some(s=>s.characters>0&&s.status!=='excluded')} onClick={()=>void research('classify')}>자료 분류·다시 진단</Button><Button variant="ghost" onClick={()=>onCampaign(diagnosis&&fresh&&diagnosis.status==='confirmed'?diagnosis.opportunities[0]?.action||brand.intake?.clientNeed||'':brand.intake?.clientNeed||'')}>캠페인 브리프<ArrowRight/></Button></div>
 {active&&<div className="archive-research" aria-live="polite"><div><b>{active.mode==='deep'?'심층 브랜드 조사':'자료 분류·진단'}{active.protocol?(active.status==='uncertain'?' · 접수 확인 중':active.steps[0]?.status==='pending'?' · 접수 대기':' · HERMES 실행 중'):` · ${active.steps.filter(s=>s.status==='completed').length}/${active.steps.length}`}</b><p>{researchStages[active.steps.find(s=>s.status!=='completed')?.stage||'diagnosis']}</p><small>{active.model} · {active.steps.filter(s=>s.status==='completed').length}/{active.steps.length}단계 저장됨</small><ResearchWorkerNotice/><p>시작: {new Date(active.createdAt).toLocaleString('ko-KR')} · 서버 상태 확인: {active.lastCheckedAt?new Date(active.lastCheckedAt).toLocaleString('ko-KR'):'아직 응답 없음'}</p>{active.activityAt&&<p>마지막 서버 활동: {new Date(active.activityAt).toLocaleString('ko-KR')} · {active.activity||'진행 중'}</p>}<p>단계가 완료될 때마다 자료를 보관하고 마지막 단계에서 종합 진단을 저장합니다. 아래 확인 시각의 갱신은 조사 진척을 보장하지 않습니다.</p>{active.error&&<p role="alert">{active.error}</p>}</div><div><Button variant="outline" disabled={busy} onClick={()=>void control(active.status==='uncertain'?'recover':'advance')}>지금 상태 확인</Button>{active.status==='uncertain'&&<Button variant="outline" disabled={busy} onClick={()=>void control('recover')}>기존 요청 확인</Button>}<Button variant="ghost" disabled={busy||active.stopRequested} onClick={()=>void control('cancel')}><Pause/>{active.stopRequested?'중지 확인 중':'중지'}</Button></div></div>}
 {syncError&&<p className="load-error" role="alert">결과 동기화 지연: {syncError}</p>}
 {!active&&latest?.status==='failed'&&<div className="load-error" role="alert"><div><b>조사 결과를 완료하지 못했습니다.</b><p>{latest.error}</p>{latest.steps.some(s=>s.rawResult)&&<details><summary>보관된 HERMES 응답 원문</summary><p>검증되지 않은 응답입니다. 확정 자료·진단에는 반영되지 않았습니다.</p>{latest.steps.filter(s=>s.rawResult).map(s=><pre key={s.id} style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',maxHeight:400,overflow:'auto'}}>{s.rawResult}</pre>)}</details>}</div></div>}
 {error&&<div className="load-error" role="alert"><span>{error}</span><Button variant="outline" onClick={()=>{setPaused(false);void load().catch(e=>setError(e.message))}}><RefreshCw/>다시 확인</Button></div>}
 <Tabs value={tab} onValueChange={setTab}><TabsList variant="line"><TabsTrigger value="overview">현황·진단</TabsTrigger><TabsTrigger value="sources">자료 아카이브 {data.sources.length}</TabsTrigger><TabsTrigger value="intake">의뢰·브랜드 이해</TabsTrigger><TabsTrigger value="research">조사 기록</TabsTrigger></TabsList>
 <TabsContent value="overview"><DeepResearchPanel brand={brand} research={data.research.find(r=>!!r.protocol)} sources={data.sources} busy={busy||!!active} onFollowup={id=>void research('deep',id)}/><div className="archive-overview-grid"><section className="archive-diagnosis"><div className="section-heading"><h3>브랜드 진단</h3><span>{diagnosis?(fresh?(diagnosis.status==='confirmed'?'확인된 진단':'검토 대기'):'새 자료 반영 필요'):'조사 전'}</span></div>{diagnosis?<><p className="archive-diagnosis-summary">{diagnosis.summary}</p><div className="diagnosis-pair"><div><h4>고객의 니즈 · 의뢰 목적</h4><p>{diagnosis.needs}</p></div><div><h4>가장 중요한 빈틈</h4><p>{diagnosis.gaps}</p></div></div><details><summary>브랜드·고객·강점·근거 보기</summary><p>{diagnosis.positioning}</p><p>{diagnosis.audience}</p><p>{diagnosis.strengths}</p><p>근거: {diagnosis.sourceIds.map(id=>data.sources.find(s=>s.id===id)?.title||id).join(' · ')||'확인된 근거 없음'}</p><p>한계: {diagnosis.limitations}</p></details>{diagnosis.opportunities.map(o=><article className="archive-opportunity" key={o.title}><h4>{o.title}</h4><p>{o.hypothesis}</p><p><b>다음 행동</b> {o.action}</p><small>검증: {o.metric}</small></article>)}{diagnosis.status!=='confirmed'&&<Button variant="outline" disabled={busy||!!active||!fresh||diagnosis.researchQuality?.status==='needs_data'||!diagnosis.sourceIds.length||diagnosis.sourceIds.some(id=>!data.sources.some(s=>s.id===id&&s.status==='confirmed'))} onClick={async()=>{setBusy(true);try{await post('confirm_diagnosis',{brandId:brand.id,id:diagnosis.id});await load()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}}><Check/>이 진단을 전략 기준으로 채택</Button>}<small className="subtle-note">근거 자료를 확인한 뒤 ‘자료 분류·다시 진단’을 실행하면 최신 진단을 채택할 수 있습니다. 채택한 진단은 캠페인 초안에 반영됩니다.</small></>:<div className="archive-empty"><Search size={28}/><h4>전략 전에, 브랜드부터 이해합니다.</h4><p>공식 채널과 의뢰 목적을 입력하고 심층 조사를 시작하거나 보유 자료를 추가해 주세요.</p></div>}</section><aside className="archive-readiness"><h3>근거 준비 상태</h3><strong>{confirmed}<small> / {data.sources.length} 자료 확인</small></strong><ul>{Object.entries(archiveCategories).filter(([k])=>k!=='other').map(([k,label])=><li key={k}><span>{label}</span><b>{data.sources.filter(s=>s.category===k&&s.status==='confirmed').length||'미확인'}</b></li>)}</ul><h4>먼저 확인할 질문</h4>{diagnosis?.questions.length?diagnosis.questions.map(q=><p key={q}>{q}</p>):<p>사업 목표, 고객 장벽, 실제 상품·가격, 운영 조건과 성과 자료를 준비해 주세요.</p>}</aside></div>
 <section className="archive-performance"><div className="section-heading"><div><h3>채널별 성과</h3><p>같은 계정·기간·정의로 비교합니다. 없는 수치는 ‘미수집’입니다.</p></div><Button variant="outline" disabled={!!active} onClick={()=>setMetricOpen(true)}><Plus/>통계 기록</Button></div>{!!data.observations.length&&<NativeSelect aria-label="측정 기록 선택" value={current?.id||''} onChange={e=>setSelectedMetric(e.target.value)}>{data.observations.map(o=><NativeSelectOption key={o.id} value={o.id}>{o.channel} · {o.account} · {o.periodStart}~{o.periodEnd}</NativeSelectOption>)}</NativeSelect>}<div className="archive-metric-grid">{metrics.map((m,i)=><article key={m.id}><h4>{m.label}</h4><strong>{m.value===null?(m.unavailable||'미수집'):m.value.toLocaleString('ko-KR',{maximumFractionDigits:2})}<small>{m.value!==null?m.unit:''}</small></strong>{previous&&m.value!==null&&prior[i].value!==null?<span>이전 기록 대비 {m.id==='contribution'?`${(m.value-prior[i].value!).toLocaleString('ko-KR')}원`:m.unit==='%'?`${(m.value-prior[i].value!).toFixed(2)}%p`:prior[i].value!>0?`${((m.value/prior[i].value!-1)*100).toFixed(1)}%`:'기준 0 · 변화율 계산 불가'}</span>:<span>동일 조건 비교 자료 필요</span>}<p>{m.formula}</p></article>)}</div>{previous&&<p className="subtle-note">비교 기준 기간: {previous.periodStart} ~ {previous.periodEnd} · 동일 조건으로 기록된 가장 최근 과거 기간</p>}{current?<div className="archive-measurement-note"><b>{current.channel} · {current.account}</b><p>{current.periodStart} ~ {current.periodEnd} · {current.scope==='all'?'유료+자연 유입':current.scope==='paid'?'유료':'자연 유입'} · {current.method==='public'?'공개 관찰':current.method==='export'?'내보내기 자료':'직접 기록'}</p><p>게시물 {current.values.posts??'미수집'} · 팔로워 {current.values.followers??'미수집'} · 조회 {current.values.views??'미수집'} · 세션 {current.values.sessions??'미수집'}</p><p>출처: {current.source} · 원본 확인 시점: {current.observedAt.slice(0,10)}</p>{current.method==='public'&&<p>공개 화면의 조회·팔로워는 관찰 당시 누적 값일 수 있습니다. 기간 실적으로 간주하거나 전기와 비교하지 않습니다.</p>}<p>집계 조건: {current.definition}</p></div>:<p className="notice">계정 통계 내보내기나 실제 측정값을 등록하면 채워집니다. 공개 조사만으로 도달·저장·구매·매출을 추정하지 않습니다.</p>}<details className="archive-metric-help"><summary>지표를 이렇게 선택한 이유</summary><p>게시물·팔로워는 활동 규모입니다. 성과는 도달, 시청 유지, 공유·저장, 유입과 사업 행동을 구분해 봅니다. 플랫폼마다 집계 기준이 달라 임의의 통합 바이럴 점수나 채널 간 도달 합계를 만들지 않습니다.</p>{metricReferences.map(r=><a key={r.url} href={r.url} target="_blank" rel="noreferrer">{r.title}<ExternalLink size={13}/></a>)}</details></section></TabsContent>
 <TabsContent value="sources"><div className="filterbar"><Input placeholder="자료 제목·요약 검색" aria-label="자료 검색" value={query} onChange={e=>setQuery(e.target.value)}/><NativeSelect aria-label="자료 분류" value={category} onChange={e=>setCategory(e.target.value)}><NativeSelectOption value="all">모든 분류</NativeSelectOption>{Object.entries(archiveCategories).map(([k,v])=><NativeSelectOption value={k} key={k}>{v}</NativeSelectOption>)}</NativeSelect></div><div className="archive-source-list">{shown.map(s=><button key={s.id} onClick={async()=>{try{const r=await fetch('/api/archive?brandId='+encodeURIComponent(brand.id)+'&sourceId='+encodeURIComponent(s.id));const d=await r.json() as ArchiveSource & {error?:string};if(!r.ok)throw new Error(d.error);setSource(d)}catch(e){toast.error((e as Error).message)}}}><FileText/><div><h4>{s.title}</h4><p>{s.excerpt||'원본만 보관 · 내용 확인 필요'}</p><small>{archiveCategories[s.category]} · {s.origin==='research'?'AI 조사':s.origin==='upload'?'파일 업로드':'직접 입력'} · {s.observedAt.slice(0,10)} · {s.extraction||s.scope}</small></div><span className={'source-state '+s.status}>{s.status==='confirmed'?'확인됨':s.status==='excluded'?'사용 제외':'검토 대기'}</span></button>)}</div>{!shown.length&&<div className="archive-empty"><FileText size={28}/><p>아직 자료가 없습니다. 조사하거나 보유 자료를 추가해 주세요.</p></div>}</TabsContent>
 <TabsContent value="intake"><form className="archive-intake form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await post('save_intake',{brandId:brand.id,data:intake});await onReload();await load();toast.success('의뢰 내용을 저장했습니다.')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}}><h3>의뢰를 정확하게 이해하기</h3><p>공식 채널은 동명 브랜드를 구분하는 기준이 됩니다. 고객의 요청과 아직 검증하지 않은 가설을 구분해 적어 주세요.</p><IntakeFields value={intake} onChange={setIntake}/><Button disabled={busy||!!active}>의뢰 정보 저장</Button></form></TabsContent>
 <TabsContent value="research"><p className="notice">서버 작업자가 연결되면 브랜드·제품 이해 → 고객·시장·경쟁 → 채널·콘텐츠 → 심층 비교·종합 진단 순서로 조사하고 단계별 자료를 저장합니다. 작업자가 가동 중이면 Mac과 앱을 꺼도 이어집니다. 작업자 설치 전 시작한 조사는 기존 단계 구성을 유지합니다. 실제 모델과 추론 설정은 연결된 HERMES 설정을 따르며, Astra ultra 적용을 보장하는 버튼은 아닙니다. 웹 접근이 막히면 한계를 기록하고 업로드 자료로 진행할 수 있습니다. 자료 분류는 30개씩 순차 처리합니다. 종합 진단은 최신 자료 최대 30개(각 4,500자 발췌), 최근 통계 12건과 단계별 요약을 사용합니다.</p>{data.research.map(r=><section className="archive-research-record" key={r.id}><h3>{r.mode==='deep'?'심층 브랜드 조사':'자료 분류·진단'} · {r.status==='completed'&&r.report?.quality.status==='needs_data'?'추가 자료 필요':({running:'진행 중',uncertain:'접수 확인 필요',completed:'완료',failed:'중단',cancelled:'중지됨'})[r.status]}</h3><small>{r.createdAt.slice(0,16).replace('T',' ')} · {r.model}</small>{r.error&&<p className="form-error">{r.error}</p>}{r.steps.map(s=><details key={s.id}><summary>{researchStages[s.stage]} · {s.status==='completed'?'완료':s.status==='pending'?'대기':s.status==='failed'?'중단':'진행 확인'}</summary><p>{s.summary||'요약이 아직 없습니다.'}</p><p className="subtle-note">한계: {s.limitations||'기록 전'}</p></details>)}</section>)}{!latest&&<div className="archive-empty">아직 조사 기록이 없습니다.</div>}</TabsContent></Tabs>
 <SourceDialog open={add} onClose={()=>setAdd(false)} brandId={brand.id} storageReady={data.storageReady} onSaved={load}/><ObservationDialog open={metricOpen} onClose={()=>setMetricOpen(false)} brandId={brand.id} onSaved={load}/>
 <Dialog open={!!source} onOpenChange={v=>!v&&setSource(null)}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>{source?.title}</DialogTitle><DialogDescription>{source?archiveCategories[source.category]:''} · 원문과 확인 범위를 대조해 주세요.</DialogDescription></DialogHeader>{source&&<><p className="notice">확인 시점: {source.observedAt.slice(0,10)} · {source.scope}</p><div className="archive-source-tools">{source.url&&<a href={source.url} target="_blank" rel="noreferrer">출처 열기<ExternalLink size={14}/></a>}{source.fileName&&<a href={'/api/archive/file?id='+encodeURIComponent(source.id)}>원본 다운로드 · {source.fileName}</a>}</div><pre className="archive-source-content">{source.content||'추출된 텍스트가 없습니다. 원본을 확인해 텍스트 자료를 추가해 주세요.'}</pre><div className="form-actions"><Button variant="ghost" disabled={busy||!!active} onClick={()=>void reviewSource('excluded')}>사용 제외</Button><Button disabled={busy||!!active||!source.content} onClick={()=>void reviewSource('confirmed')}><Check/>내용을 확인하고 사용</Button></div></>}</DialogContent></Dialog>
 </section>;
}
function SourceDialog({open,onClose,brandId,storageReady,onSaved}:{open:boolean;onClose:()=>void;brandId:string;storageReady:boolean;onSaved:()=>Promise<void>}){
 const[title,setTitle]=useState(''),[url,setUrl]=useState(''),[content,setContent]=useState(''),[category,setCategory]=useState(''),[scope,setScope]=useState('사용자가 제공한 자료'),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState('');
 useEffect(()=>{if(open){setTitle('');setUrl('');setContent('');setCategory('');setScope('사용자가 제공한 자료');setFile(null)}},[open]);
 return <Dialog open={open} onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>브랜드 자료 추가</DialogTitle><DialogDescription>원본과 출처를 보관합니다. 내용에 따라 1차 분류되며 AI 분류·진단을 이어갈 수 있습니다.</DialogDescription></DialogHeader><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{if(file){setProgress('텍스트 추출 중…');let extraction={content:'',extraction:'추출 실패 · 원본 보관',scope:'텍스트 추출 실패. 원본을 확인하고 내용 메모를 추가해 주세요.'};try{extraction=await extractArchiveFile(file)}catch(err){toast.warning((err as Error).message+' 원본은 보관합니다.')}const form=new FormData();form.set('brandId',brandId);form.set('file',file);form.set('title',title||file.name);form.set('content',(extraction.content+(content?'\n[사용자 메모]\n'+content:'')).slice(0,80000));form.set('scope',extraction.scope+' · '+scope);form.set('extraction',extraction.extraction);if(category)form.set('category',category);setProgress('원본 저장 중…');const r=await fetch('/api/archive/file',{method:'POST',body:form});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error)}else await post('add_source',{brandId,data:{title,url,content,category:category||undefined,scope}});await onSaved();onClose();toast.success('자료를 보관했습니다. 내용을 확인하면 캠페인에 활용됩니다.')}catch(err){toast.error((err as Error).message)}finally{setBusy(false);setProgress('')}}}>
 <Field label="자료 제목"><Input required={!file} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="파일 선택 (선택) · 8MB 이하"><Input type="file" disabled={!storageReady} accept=".pdf,.docx,.txt,.md,.csv,.json,.png,.jpg,.jpeg,.webp" onChange={e=>{const f=e.target.files?.[0];if(f&&f.size>8*1024*1024){toast.error('8MB 이하 파일을 선택하세요.');e.target.value='';return}setFile(f||null)}}/></Field><small>PDF·DOCX는 텍스트를 추출합니다. 스캔·이미지·도형은 원본을 보관하고 설명 메모를 이용합니다.</small><Field label="분류"><NativeSelect value={category} onChange={e=>setCategory(e.target.value)}><NativeSelectOption value="">자동 1차 분류</NativeSelectOption>{Object.entries(archiveCategories).map(([k,v])=><NativeSelectOption key={k} value={k}>{v}</NativeSelectOption>)}</NativeSelect></Field>{!file&&<Field label="출처 URL (선택)"><Input type="url" value={url} onChange={e=>setUrl(e.target.value)}/></Field>}<Field label={file?'추가 메모':'확인한 내용 · 원문 텍스트'}><Textarea required={!file} rows={6} value={content} onChange={e=>setContent(e.target.value)} maxLength={80000}/></Field><Field label="자료 범위 · 한계"><Input value={scope} onChange={e=>setScope(e.target.value)} required/></Field><Button disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Upload/>}{progress||'자료 보관'}</Button></form></DialogContent></Dialog>;
}
function ObservationDialog({open,onClose,brandId,onSaved}:{open:boolean;onClose:()=>void;brandId:string;onSaved:()=>Promise<void>}){
 const[f,setF]=useState({channel:'Instagram',account:'',periodStart:date(),periodEnd:date(),observedAt:date(),source:'',definition:'',scope:'all',method:'export'}),[values,setValues]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false);
 useEffect(()=>{if(open){setF({channel:'Instagram',account:'',periodStart:date(),periodEnd:date(),observedAt:date(),source:'',definition:'',scope:'all',method:'export'});setValues({})}},[open]);
 return <Dialog open={open} onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>채널 통계 기록</DialogTitle><DialogDescription>확인한 항목만 입력하세요. 빈칸은 미수집이며 0과 구분합니다. 원본 통계 파일은 자료 아카이브에 함께 보관할 수 있습니다.</DialogDescription></DialogHeader><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await post('add_observation',{brandId,data:{...f,values:Object.fromEntries(Object.keys(metricFields).map(k=>[k,values[k]===''||values[k]===undefined?null:Number(values[k])]))}});await onSaved();onClose()}catch(err){toast.error((err as Error).message)}finally{setBusy(false)}}}><div className="form-two">{([['channel','채널'],['account','계정 · 대상'],['periodStart','측정 시작'],['periodEnd','측정 종료'],['observedAt','원본 확인 시점']] as const).map(([k,label])=><Field key={k} label={label}><Input type={(k.startsWith('period')||k==='observedAt')?'date':'text'} required value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></Field>)}</div><div className="form-two"><Field label="집계 범위"><NativeSelect value={f.scope} onChange={e=>setF({...f,scope:e.target.value})}><NativeSelectOption value="all">전체 (유료+자연)</NativeSelectOption><NativeSelectOption value="organic">자연 유입</NativeSelectOption><NativeSelectOption value="paid">유료</NativeSelectOption></NativeSelect></Field><Field label="수집 방식"><NativeSelect value={f.method} onChange={e=>setF({...f,method:e.target.value})}><NativeSelectOption value="export">계정 내보내기 자료</NativeSelectOption><NativeSelectOption value="manual">직접 기록</NativeSelectOption><NativeSelectOption value="public">공개 화면 관찰</NativeSelectOption></NativeSelect></Field></div><Field label="수치 출처"><Input required value={f.source} onChange={e=>setF({...f,source:e.target.value})} placeholder="예: Instagram Insights 내보내기, 파일명"/></Field><Field label="집계 정의 · 시간대 · 전환 행동 · 비용 범위"><Textarea required value={f.definition} onChange={e=>setF({...f,definition:e.target.value})} placeholder="예: Asia/Seoul, 계정 전체, 구매 완료가 발생한 세션, 환불 차감 매출"/></Field><div className="form-two">{Object.entries(metricFields).map(([k,label])=><Field label={label} key={k}><Input type="number" min="0" step="any" placeholder="미수집" value={values[k]||''} onChange={e=>setValues({...values,[k]:e.target.value})}/></Field>)}</div><p className="notice">공개 화면 수치는 누적 스냅숏일 수 있어 전기 비교에서 제외됩니다. ‘핵심 행동 발생 세션’은 이벤트 횟수가 아닙니다. 해당 행동이 한 번 이상 발생한 세션 수를 입력하세요. 조회·노출·도달도 서로 구분합니다.</p><Button disabled={busy}>측정 기록 저장</Button></form></DialogContent></Dialog>;
}
