'use client';
import {clientId} from '@/lib/client';
import {useEffect,useRef,useState} from 'react';
import {toast} from 'sonner';
import {ArrowRight,Check,ChevronDown,LoaderCircle,RefreshCw,Sparkles,Square,Target} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import type {Brand,Campaign} from '@/lib/agency';
import {api,type WorkspaceData} from '@/lib/client';
import {applySuggestions,briefFields,emptyPlan,planFields,readiness,valueOf,type BriefDraft,type BriefInput,type BriefKey,type QuestionKey,type PlanKey} from '@/lib/brief';
const initial=():BriefInput=>({brandId:'ofd',title:'',goal:'',audience:'',channels:'',stores:'',products:'',budget:0,startDate:'',endDate:'',constraints:'',sources:'',plan:emptyPlan()});
const isActive=(d:BriefDraft|null)=>!!d&&['starting','queued','in_progress','uncertain'].includes(d.status);
async function draftApi(action:string,payload:Record<string,unknown>):Promise<BriefDraft>{const r=await fetch('/api/brief',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const d=await r.json() as BriefDraft;if(!r.ok)throw new Error(d.error||'초안을 불러오지 못했습니다.');return d}
const steps=[{id:'strategy',label:'전략과 고객',description:'누구의 어떤 행동을 바꿀까요?'},{id:'measure',label:'성과와 실험',description:'무엇을 어떻게 검증할까요?'},{id:'execute',label:'실행과 운영',description:'실제로 시작하려면 무엇이 필요할까요?'},{id:'evidence',label:'근거와 학습',description:'무엇을 알고 있고, 무엇을 확인해야 할까요?'}];
export function CampaignDialog({open,onClose,brands,edit,goal='',brandId='ofd',onSaved,connection,onConnect,autoStart=false,resumeId,reload}:{open:boolean;onClose:()=>void;brands:Brand[];edit?:Campaign|null;goal?:string;brandId?:string;onSaved:(id:string)=>Promise<void>;connection:WorkspaceData['connection'];onConnect:()=>void;autoStart?:boolean;resumeId?:string;reload:()=>Promise<void>}){
 const[f,setF]=useState<BriefInput>(initial);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[draft,setDraft]=useState<BriefDraft|null>(null);const[tab,setTab]=useState('strategy');const[applied,setApplied]=useState<Partial<Record<BriefKey,string>>>({});const appliedId=useRef('');const requestId=useRef('');const generation=useRef(0);const[checkTick,setCheckTick]=useState(0);const active=isActive(draft);const hermes=connection.configured&&connection.provider==='hermes';
 const receive=(d:BriefDraft,token:number)=>{if(token!==generation.current)return;setDraft(d);setError('');if(d.status==='completed'&&d.result&&appliedId.current!==d.id){appliedId.current=d.id;setF(current=>applySuggestions(current,d.result!.suggestions));setApplied(Object.fromEntries(d.result.suggestions.map(s=>[s.field,s.value])));toast.success('HERMES 초안을 빈칸에 채웠습니다. 제안과 확인할 내용을 검토하세요.')}if(d.error)setError(d.error)};
 async function generate(input=f){const token=generation.current;setBusy(true);setError('');if(!hermes){setError('HERMES 연결 후 목표에 맞는 초안을 작성할 수 있습니다. 지금 입력한 내용은 브리프로 저장할 수 있습니다.');setBusy(false);return}const id=requestId.current||clientId();requestId.current=id;try{const d=await draftApi('start',{id,data:input,campaignId:edit?.id,campaignVersion:edit?.version});receive(d,token);await reload()}catch(e){if(token===generation.current)setError((e as Error).message)}finally{if(token===generation.current)setBusy(false)}}
 useEffect(()=>{if(!open){generation.current++;return}const token=++generation.current;appliedId.current='';requestId.current='';setDraft(null);setError('');setBusy(false);setTab('strategy');const next=edit?{...initial(),...edit,plan:{...emptyPlan(),...edit.plan}}:{...initial(),brandId,goal,constraints:brands.find(b=>b.id===brandId)?.constraints||''};setF(next);setApplied(edit?.draftMeta?.values||{});
  if(resumeId){setBusy(true);void draftApi('load',{id:resumeId}).then(d=>{if(token!==generation.current)return;requestId.current=d.id;setF(d.input);receive(d,token)}).catch(e=>{if(token===generation.current)setError(e.message)}).finally(()=>{if(token===generation.current)setBusy(false)})}
  else if(autoStart&&goal.trim()&&!edit)void generate(next);
  return()=>{generation.current++};
 // Reopening is deliberate; workspace refreshes must never reset an edited form.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[open,resumeId,edit?.id]);
 useEffect(()=>{if(!open||!draft||!isActive(draft)||draft.status==='uncertain')return;let stopped=false;let polling=false;const token=generation.current;const poll=async()=>{if(stopped||polling)return;polling=true;try{const d=await draftApi('poll',{id:draft.id});if(!stopped)receive(d,token);if(!isActive(d))void reload()}catch(e){if(!stopped)setError((e as Error).message)}finally{polling=false}};const timer=setInterval(poll,4000);void poll();return()=>{stopped=true;clearInterval(timer)}},[open,draft?.id,draft?.status,checkTick]);
 function set(k:QuestionKey,v:string){setF(current=>k in planFields?{...current,plan:{...current.plan,[k]:v}}:{...current,[k]:k==='budget'?Number(v):v})}
 async function control(action:'recover'|'cancel'){if(!draft)return;setBusy(true);const token=generation.current;try{receive(await draftApi(action,{id:draft.id}),token);await reload()}catch(e){setError((e as Error).message)}finally{if(token===generation.current)setBusy(false)}}
 async function save(connect=false){setBusy(true);setError('');try{const r=await api('save_campaign',{id:edit?.id,version:edit?.version,briefDraftId:draft?.id,data:{...f,title:f.title.trim()||f.goal.slice(0,60)}});await onSaved(r.id);onClose();toast.success('캠페인 브리프를 저장했습니다.');if(connect)onConnect()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const field=(k:BriefKey,placeholder='',rows=3)=>{const ai=applied[k]===valueOf(f,k)&&!!applied[k];return <label className="field" key={k}><span className="brief-field-label">{briefFields[k]}{ai&&<em>AI 제안 · 검토 필요</em>}</span>{k==='title'?<Input value={f.title} maxLength={150} onChange={e=>set(k,e.target.value)} placeholder={placeholder}/>:<Textarea rows={rows} value={valueOf(f,k)} onChange={e=>set(k,e.target.value)} placeholder={placeholder}/>}</label>};
 const checks=readiness(f);const proposal=draft?.result;
 return <Dialog open={open} onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="campaign-brief-dialog"><DialogHeader><div className="brief-eyebrow"><Target size={16}/>CAMPAIGN BLUEPRINT</div><DialogTitle>{edit?'캠페인을 더 구체적으로':'목표 하나에서, 실행할 수 있는 캠페인으로'}</DialogTitle><DialogDescription>HERMES가 브랜드 지식과 이전 캠페인을 참고해 초안을 작성합니다. 중요한 결정만 보완하세요.</DialogDescription></DialogHeader>
 <form onSubmit={e=>{e.preventDefault();void save()}} className="blueprint-form">
 <div className="goal-workbench"><div className="goal-workbench-top"><label className="field"><span>브랜드</span><NativeSelect aria-label="브리프 브랜드" value={f.brandId} disabled={!!edit||active||busy} onChange={e=>{setF(x=>({...initial(),brandId:e.target.value,goal:x.goal,constraints:brands.find(b=>b.id===e.target.value)?.constraints||''}));setDraft(null);requestId.current='';setApplied({})}}>{brands.map(b=><NativeSelectOption key={b.id} value={b.id}>{b.name}</NativeSelectOption>)}</NativeSelect></label><span className={'hermes-state '+(hermes?'available':'')}>{hermes?'HERMES 연결됨':'HERMES 연결 필요'}</span></div><label className="field"><span>이루고 싶은 목표 <b>*</b></span><Textarea aria-label="브리프 목표" required maxLength={5000} rows={2} disabled={active||busy} value={f.goal} onChange={e=>{setF(x=>({...x,goal:e.target.value}));if(draft){setDraft(null);setApplied({});requestId.current=''}}} placeholder="예: 맵달서울 물품보관함 사용률을 높이고 싶어."/></label><div className="generate-row"><p>타깃 · 메시지 · 실행안 · 성과지표를 함께 설계합니다.</p><Button className="lime-button" type="button" disabled={busy||active||!f.goal.trim()} onClick={()=>{if(draft&&!isActive(draft)){requestId.current='';appliedId.current=''}void generate()}}>{busy||active?<LoaderCircle className="spin"/>:<Sparkles/>}{active?'HERMES 작성 중':proposal?'빈칸 보완 제안 받기':'HERMES로 초안 채우기'}</Button></div></div>
 {(active||error)&&<div className="brief-generation" role="status" aria-live="polite"><div><strong>{active?'전략과 실행 초안을 작성하고 있습니다':'초안 상태를 확인해 주세요'}</strong><p>{error||'목표 해석 → 브랜드·과거 성과 참고 → 전략·측정 설계. 잠시 닫아도 대시보드에서 이어볼 수 있습니다.'}</p></div><div>{draft?.status==='uncertain'&&<Button type="button" variant="outline" disabled={busy} onClick={()=>control('recover')}><RefreshCw/>같은 요청 확인</Button>}{active&&<Button type="button" variant="ghost" disabled={busy} onClick={()=>control('cancel')}><Square/>작성 중지</Button>}{!hermes&&<Button type="button" variant="outline" disabled={busy||!f.goal.trim()} onClick={()=>save(true)}>브리프 저장 후 연결<ArrowRight/></Button>}</div></div>}
 {proposal&&<section className="draft-summary"><span><Sparkles size={16}/>HERMES 초안</span><p>{proposal.summary}</p><small>빈칸에 적용했습니다. 기존 입력은 보존했습니다. AI가 제안한 내용은 확인 전 가설입니다.</small></section>}
 {proposal?.questions.length? <section className="brief-questions"><div><h3>먼저 확인할 {proposal.questions.length}가지</h3><span>모르면 비워두고 저장할 수 있습니다.</span></div>{proposal.questions.map((q,i)=><label key={i} className="brief-question"><b>{String(i+1).padStart(2,'0')}</b><div><strong>{q.question}</strong><small>{q.why}</small>{['budget','startDate','endDate'].includes(q.field)?<Input type={q.field==='budget'?'number':'date'} min={q.field==='budget'?0:undefined} value={valueOf(f,q.field)} disabled={active} aria-label={q.question} onChange={e=>set(q.field,e.target.value)}/>:<Textarea rows={2} value={valueOf(f,q.field)} disabled={active} aria-label={q.question} onChange={e=>set(q.field,e.target.value)} placeholder="확인한 내용을 적으면 관련 항목에 반영됩니다."/>}</div></label>)}</section>:null}
 <Tabs value={tab} onValueChange={setTab} className="blueprint-tabs"><TabsList variant="line">{steps.map(s=><TabsTrigger value={s.id} key={s.id}>{s.label}</TabsTrigger>)}</TabsList>
 <fieldset disabled={busy||active}>
 <TabsContent value="strategy"><h3>{steps[0].description}</h3>{field('title','짧고 기억에 남는 캠페인 이름')}<div className="form-two">{field('audience','누가, 어디에서, 어떤 상황에 있나요?')}{field('behavior','클릭 이후 고객의 어떤 실제 행동이 달라져야 하나요?')}{field('barrier','고객이 이용하지 않는 이유. 사실과 가설을 구분하세요.')}{field('products','실제 서비스·제품과 고객에게 주는 가치')}</div>{field('message','핵심 메시지와 다음 행동(CTA)')}{field('journey','발견 → 위치·가격 확인 → 방문 → 결제 → 이용 완료')}</TabsContent>
 <TabsContent value="measure"><h3>{steps[1].description}</h3>{field('kpi','예: 실제 사용 락커 시간 ÷ 가동 가능한 락커 시간 × 100')}<div className="form-two">{field('baseline','실측값, 기간과 출처. 모르면 비워두세요.')}{field('target','대표님이 결정할 목표값과 기한. 추정 실적을 입력하지 않습니다.')}</div>{field('hypothesis','어떤 변화가 왜 고객 행동을 바꿀까요?')}{field('experiment','한 번에 바꿀 변수, 비교군·기간, 날씨·행사 등 통제 요인')}{field('tracking','채널별 QR/UTM, 이용 완료 기록, 집계 주기와 담당')}{field('decision','확대·수정·중단 판단 기준과 손실·운영 한계')}</TabsContent>
 <TabsContent value="execute"><h3>{steps[2].description}</h3><div className="form-two">{field('channels','채널마다 유입·안내·전환 역할을 구분하세요.')}{field('stores','매장, 시장, 운영 범위')}{field('operations','실제 요금·영업시간·결제·크기·지원 언어. 확인된 내용만 입력하세요.')}{field('owner','최종 결정자, 현장 담당자, 데이터 확인 담당자')}</div>{field('deliverables','채널별 소재, 필요한 언어, 제작 규격과 수량')}{field('schedule','기준 데이터 확보 → 준비 → 실험 → 결과 점검')}<div className="form-two"><label className="field"><span>시작일</span><Input aria-label="시작일" type="date" value={f.startDate} onChange={e=>setF({...f,startDate:e.target.value})}/></label><label className="field"><span>종료일</span><Input aria-label="종료일" type="date" value={f.endDate} onChange={e=>setF({...f,endDate:e.target.value})}/></label></div><label className="field"><span>확정한 예산 상한 (원)</span><Input aria-label="확정한 예산 상한" type="number" min="0" max="1000000000000" value={f.budget||''} onChange={e=>setF({...f,budget:Number(e.target.value)})} placeholder="미확정"/><small>미입력 또는 0은 미확정으로 저장합니다.</small></label>{field('budgetPlan','예산 확정 후 채널·제작·측정에 배분할 원칙')}{field('constraints','브랜드 기준과 현장 운영 조건')}</TabsContent>
 <TabsContent value="evidence"><h3>{steps[3].description}</h3><label className="field"><span>참고 자료와 근거</span><Textarea rows={5} value={f.sources} onChange={e=>setF({...f,sources:e.target.value})} placeholder="운영 자료, 고객 의견, 실제 수치, 참고 링크와 기준일을 입력하세요."/></label>{proposal?.assumptions.length?<div className="assumption-box"><h4>검증할 AI 가설</h4><ul>{proposal.assumptions.map((s,i)=><li key={i}>{s}</li>)}</ul></div>:null}{(proposal?.contextUsed||edit?.draftMeta?.contextUsed)?.length?<div className="context-used"><h4>HERMES가 참고했다고 밝힌 자료</h4><ul>{(proposal?.contextUsed||edit?.draftMeta?.contextUsed||[]).map((s,i)=><li key={i}>{s}</li>)}</ul></div>:null}{field('learning','실험이 끝난 뒤 실제 결과, 한계, 다음에 바꿀 점을 기록하세요.')}<p className="brief-footnote">이 캠페인의 목표·계획·기록은 다음 캠페인의 초안 작성 시 같은 브랜드의 참고 자료로 활용됩니다.</p></TabsContent>
 </fieldset></Tabs>
 {proposal&&<details className="all-suggestions"><summary>HERMES의 전체 제안 비교 <span>{proposal.suggestions.length}개</span><ChevronDown size={16}/></summary><div>{proposal.suggestions.map(s=><article key={s.field}><div><h4>{briefFields[s.field]}</h4><p>{s.value}</p><small>{s.reason}</small></div><Button type="button" variant="outline" size="sm" disabled={active||valueOf(f,s.field)===s.value} onClick={()=>{setF(x=>applySuggestions(x,[s],true));setApplied(x=>({...x,[s.field]:s.value}))}}>{valueOf(f,s.field)===s.value?'적용됨':valueOf(f,s.field)?'이 제안으로 교체':'적용'}</Button></article>)}</div></details>}
 <div className="brief-readiness"><strong>실행 전 확인</strong>{checks.map(g=><div key={g.title}><span>{g.title}</span><b>{g.missing.length?`${g.missing.length}개 미입력`:'필수 항목 입력됨'}</b></div>)}<small>입력 여부를 확인합니다. 사실 검증이나 실행 승인을 뜻하지 않습니다.</small></div>
 <div className="blueprint-footer"><p>{edit?'수정하면 새 버전이 생성되며 기존 작업물은 다시 검토합니다.':'아직 모르는 정보가 있어도 초안을 저장할 수 있습니다.'}</p><div><Button variant="outline" type="button" onClick={onClose} disabled={busy}>닫기</Button><Button disabled={busy||active||!f.goal.trim()} type="submit">{busy?<LoaderCircle className="spin"/>:<Check/>}{edit?'브리프 수정 저장':'캠페인 초안 저장'}</Button></div></div>
 </form></DialogContent></Dialog>
}
export function CampaignBlueprint({campaign:c}:{campaign:Campaign}){
 const plan=c.plan||emptyPlan();const checks=readiness(c);
 return <div className="saved-blueprint"><div className="process-strip">{['목표·근거','전략·가설','제작·검수','실험·측정','학습·개선'].map((s,i)=><span key={s}><b>{i+1}</b>{s}</span>)}</div><div className="saved-readiness">{checks.map(g=><div key={g.title}><strong>{g.title}</strong><p>{g.missing.length?g.missing.map(k=>briefFields[k]).join(' · '):'필수 항목 입력됨 · 내용 검토 필요'}</p></div>)}</div>{Object.entries(planFields).map(([k,label])=>plan[k as PlanKey]?<section className="detail-block" key={k}><h3>{label}{c.draftMeta?.values[k as BriefKey]===plan[k as PlanKey]&&<span className="ai-label">AI 제안</span>}</h3><p>{plan[k as PlanKey]}</p></section>:null)}{c.draftMeta?.assumptions.length?<section className="detail-block"><h3>검증할 가설</h3><ul>{c.draftMeta.assumptions.map((s,i)=><li key={i}>{s}</li>)}</ul></section>:null}</div>
}
