'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {ExternalLink,RefreshCw,Search} from 'lucide-react';
import type {Brand} from '@/lib/agency';
import type {ArchiveSourceSummary,PublicResearch} from '@/lib/archive';
import {archiveCategories} from '@/lib/archive';
import {comparisonGroups,defaultResearchPlan,researchPhases,type ResearchAccess} from '@/lib/deep-research';
export function DeepResearchPanel({brand,research,sources,busy,onFollowup}:{brand:Brand;research?:PublicResearch;sources:ArchiveSourceSummary[];busy:boolean;onFollowup:(id:string)=>void}){
 const[access,setAccess]=useState<ResearchAccess|null>(null),[checking,setChecking]=useState(false),[error,setError]=useState('');
 const plan=research?.plan||defaultResearchPlan(brand),report=research?.report,connection=access||research?.access,groups=report?comparisonGroups(report.cases):[];
 const source=(id:string)=>sources.find(s=>s.id===id);
 return <section className="deep-research-panel"><div className="section-heading"><div><p className="eyebrow">BRAND DISCOVERY</p><h3>브랜드를 이해하는 초기 조사</h3><p>{plan.objective}</p></div><Button variant="outline" disabled={checking} onClick={async()=>{setChecking(true);setError('');try{const r=await fetch('/api/archive/research');const d=await r.json() as ResearchAccess&{error?:string};if(!r.ok)throw new Error(d.error||'연결을 확인하지 못했습니다.');setAccess(d)}catch(e){setError((e as Error).message)}finally{setChecking(false)}}}><RefreshCw className={checking?'spin':''}/>조사 도구 확인</Button></div>
 {error&&<p role="alert" className="form-error">{error}</p>}
 <div className="deep-plan-stats"><span>최근 <b>{plan.lookbackDays}일</b></span><span>자사 콘텐츠 목표 <b>{plan.targetCases}개</b></span><span>경쟁·대안 목표 <b>{plan.targetCompetitors}개</b></span><span>보완 조사 최대 <b>{plan.maxFollowups}회</b></span></div>
 <p className="subtle-note">접근 가능한 범위에서 조사합니다. 표본이 적거나 접근이 막히면 부족한 근거를 남깁니다. 목표 수량은 수집 완료 수량이 아닙니다.</p>
 <details><summary>조사 질문과 수행 범위</summary><ol>{plan.questions.map(q=><li key={q}>{q}</li>)}</ol><p>우선 확인할 채널: {plan.channels.join(' · ')}. 공식 계정과 사업 목적을 확인한 뒤 조사 비중을 조정합니다.</p><div className="deep-phases">{researchPhases.map((p,i)=><span key={p}>{String(i+1).padStart(2,'0')} {p}{report?' · 기록됨':''}</span>)}</div><p>계획부터 보완 조사까지 HERMES의 한 연속 작업으로 실행합니다. 접수 후에는 이 화면을 닫아도 실행이 이어지며, 다시 열면 결과를 확인해 보관합니다. HERMES 서버와 연결된 브라우저가 실행 가능한 상태여야 합니다.</p></details>
 {connection&&<div className="deep-access"><b>Aside {connection.aside==='advertised'?'도구 등록 확인':'등록 미확인'}</b><span>브라우저 도구 {connection.browser==='advertised'?'등록 확인':'등록 미확인'}</span><small>확인 시점 {connection.checkedAt.slice(0,16).replace('T',' ')}</small>{connection.notes.map(n=><p key={n}>{n}</p>)}</div>}
 {!report&&<p className="notice"><Search size={16}/> 실제 브라우징 기록, 콘텐츠 비교와 반론 검토 결과가 여기에 모입니다. 도구 등록 확인과 사이트 접속 성공은 구분합니다.</p>}
 {report&&<><div className={'deep-verdict '+report.quality.status}><div><h4>{report.quality.status==='needs_data'?'추가 자료·보완 조사 필요':'진단 검토 가능'}</h4><p>자사 콘텐츠 {report.cases.filter(c=>c.relationship==='own').length}개 · 경쟁·대안 {report.competitors.length}개 · 시청 기록 {report.quality.viewedCases}개 · 비교 가능한 묶음 {report.quality.comparableGroups}개</p></div><Button variant="outline" disabled={busy} onClick={()=>onFollowup(research!.id)}>부족한 근거 보완 조사</Button></div>
 <p className="subtle-note">접근·시청 기록은 HERMES가 보고한 관찰입니다. 자동 검사는 형식과 근거 연결을 점검하며 사실 검증을 대신하지 않습니다. 원문을 확인한 뒤 전략에 사용하세요.</p>
 {!!report.quality.issues.length&&<details open><summary>아직 해결하지 못한 항목 {report.quality.issues.length}</summary><ul>{report.quality.issues.map((s,i)=><li key={i}>{s}</li>)}</ul></details>}
 <div className="deep-coverage">{report.quality.coverage.map(c=><span key={c.category}>{archiveCategories[c.category as keyof typeof archiveCategories]} <b>{c.count}개</b></span>)}</div>
 <details><summary>조사 과정과 반론 검토</summary>{report.phases.map(p=><article key={p.phase}><h4>{p.phase}</h4><p>{p.summary}</p></article>)}{report.review.claims.map((c,i)=><article key={i}><h4>{c.claim}</h4><p>근거: {c.sourceIds.map(id=>source(id)?.title||id).join(' · ')}</p><p>반례·다른 설명: {c.counterEvidence}</p><p>추가 검증: {c.nextCheck}</p></article>)}{report.review.followups.map((f,i)=><article key={i}><h4>보완 조사 {i+1} · {f.question}</h4><p>{f.finding}</p><small>{f.sourceIds.map(id=>source(id)?.title||id).join(' · ')}</small></article>)}</details>
 <details><summary>고객의 선택 이유·장벽 {report.customerSignals.length}건</summary>{report.customerSignals.map((s,i)=><article key={i}><h4>{({motivation:'선택 이유',barrier:'구매 장벽',complaint:'불만',question:'반복 질문'})[s.kind]}</h4><p>{s.observation}</p><p>검토할 시사점: {s.implication}</p><small>{source(s.sourceId)?.title}</small></article>)}</details>
 <details><summary>경쟁 브랜드와 대안 {report.competitors.length}개</summary>{report.competitors.map(c=><article key={c.name}><h4>{c.name}</h4><p>{c.difference}</p><small>{c.sourceIds.map(id=>source(id)?.title||id).join(' · ')}</small></article>)}</details>
 <details><summary>HERMES가 보고한 접근 기록 {report.access.length}건</summary>{report.access.map(a=><article key={a.sourceId}><h4>{source(a.sourceId)?.title||a.sourceId}</h4><p>{({browser:'브라우징',api:'API',upload:'업로드',search_snippet:'검색 요약만 확인'})[a.method]} · {a.tool}</p><p>{a.scope}</p>{source(a.sourceId)?.url&&<a href={source(a.sourceId)!.url} target="_blank" rel="noreferrer">출처 확인 <ExternalLink size={13}/></a>}</article>)}</details>
 <details><summary>콘텐츠 분석 {report.cases.length}개 · 비교 {groups.length}묶음</summary><p className="subtle-note">동일 계정·채널·형식·광고 조건·게시 경과 구간·영상 길이 구간 안에서 최소 6개가 있을 때 관찰 조회수의 상·중·하위를 나눕니다. 표본 내 비교이며 인과관계나 전체 계정 순위를 뜻하지 않습니다.</p>{groups.map(g=><p key={g.label}><b>{g.label}</b> · {g.count}개 · 조회 중앙값 {g.median.toLocaleString('ko-KR')}</p>)}<div className="deep-cases">{report.cases.map(c=>{const band=groups.flatMap(g=>g.items).find(i=>i.id===c.id);return <article key={c.id}><div className="section-heading"><h4>{c.channel} · {c.account}</h4><span>{band?({high:'표본 상위',middle:'표본 중간',low:'표본 하위'})[band.band]:'비교 조건 부족'}</span></div><p>{c.relationship==='own'?'자사':'경쟁사'} · 조회 {c.views===null?'미확인':c.views.toLocaleString('ko-KR')} · {({organic:'자연 유입',paid:'유료',unknown:'광고 여부 미확인'})[c.distribution]}</p><small>게시 {c.publishedAt.slice(0,10)} / 관찰 {c.observedAt.slice(0,10)} · {({not_viewed:'영상 미시청',partial:'일부 시청',full:'전체 시청'})[c.viewing]}</small><p><b>첫 장면·도입</b> {c.hook}</p><p><b>메시지</b> {c.message}</p><p><b>증거</b> {c.proof}</p><p><b>행동 유도</b> {c.cta}</p><p><b>장벽</b> {c.friction}</p><p><b>가설</b> {c.hypothesis}</p><p><b>다른 설명</b> {c.alternative}</p>{c.timeline.map((t,i)=><p key={i}><b>{t.second}초</b> {t.observation}</p>)}{source(c.sourceId)?.url&&<a href={source(c.sourceId)!.url} target="_blank" rel="noreferrer">원문 대조 <ExternalLink size={13}/></a>}</article>})}</div></details>
 </>}
 </section>;
}
