'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {useAccount} from './account-context';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import {askConfirm} from '@/components/app/confirm-dialog';
import {MetaLine} from '@/components/app/meta-line';
import {Note} from '@/components/app/note';
import type {CsSource} from '@/lib/growth-cs-source';
import {deliveryNeedsReceipt,type DeliveryRow} from '@/lib/growth-consumer-delivery';
import styles from './growth-panel.module.css';
type View={campaignVersion:number;connection:{enabled:boolean;configured:boolean;version:number;tenantId:string;providerStoreId:string};deliveries:DeliveryRow[]};
type Customer={id:string;version:number;assessment:{postPurchaseEligible:boolean;reorderEligible:boolean}};
const labels={queued:'대기',unknown:'결과 미확인·재전송 금지',accepted:'제공자 접수',delivered:'전달 확인',failed:'실패·억제'};
class DeliveryHttpError extends Error{constructor(message:string,readonly status:number){super(message)}}
async function api(campaignId:string,init:RequestInit={}){const r=await fetch(`/api/growth/consumer-delivery${init.method?'':`?campaignId=${encodeURIComponent(campaignId)}`}`,{...init,cache:'no-store'}),x=await r.json() as Record<string,unknown>;if(!x||typeof x!=='object')throw new Error('발송 응답을 확인하지 못했습니다.');if(!r.ok)throw new DeliveryHttpError(typeof x.error==='string'?x.error:'발송 원장 요청 실패',r.status);return x}
export function GrowthConsumerDeliveryPanel({campaignId,customers,serviceSources}:{campaignId:string;customers:Customer[];serviceSources?:CsSource[]}){
 const account=useAccount(),[view,setView]=useState<View|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[needsRefresh,setNeedsRefresh]=useState(false),working=useRef(false),pendingQueue=useRef<Record<string,unknown>|null>(null);const [hasPendingQueue,setHasPendingQueue]=useState(false);
 const [sourceId,setSourceId]=useState('');const [customerId,setCustomerId]=useState(''),[purpose,setPurpose]=useState('post_purchase'),[templateId,setTemplateId]=useState(''),[templateDigest,setTemplateDigest]=useState(''),[maxCost,setMaxCost]=useState('0'),[expires,setExpires]=useState(''),[authorityId,setAuthorityId]=useState(''),[authorityVersion,setAuthorityVersion]=useState('1'),[waitDays,setWaitDays]=useState('30');
 const [tenant,setTenant]=useState(''),[store,setStore]=useState(''),[secret,setSecret]=useState('');
 const load=useCallback(async(signal?:AbortSignal)=>{const x=await api(campaignId,{signal});if(signal?.aborted)return;if(!Array.isArray(x.deliveries)||typeof x.campaignVersion!=='number'||!x.connection||typeof x.connection!=='object')throw new Error('발송 원장 응답 형식 오류');setView(x as unknown as View);if(pendingQueue.current&&x.deliveries.some((r:DeliveryRow)=>r.id===pendingQueue.current?.id)){pendingQueue.current=null;setHasPendingQueue(false);setMessage('이전 대기 요청의 저장을 확인했습니다.')}setNeedsRefresh(false)},[campaignId]);
 useEffect(()=>{const controller=new AbortController();Promise.resolve().then(()=>load(controller.signal)).catch(e=>{if(!controller.signal.aborted)setMessage(e instanceof Error?e.message:'조회 실패')});return()=>controller.abort()},[load]);
 async function mutate(body:Record<string,unknown>){
  if(working.current||!view)return;working.current=true;setBusy(true);setMessage('');let saved=false;
  const request=body.action==='queue'&&pendingQueue.current?pendingQueue.current:{campaignId,campaignVersion:view.campaignVersion,expectedVersion:0,requestId:crypto.randomUUID(),...body};if(body.action==='queue'&&!pendingQueue.current){pendingQueue.current=request;setHasPendingQueue(true)}
  try{await api(campaignId,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request)});saved=true;if(body.action==='queue'){pendingQueue.current=null;setHasPendingQueue(false)}setSecret('');await load();setMessage('저장했습니다.');}
  catch(e){if(body.action==='queue'&&e instanceof DeliveryHttpError&&e.status>=400&&e.status<500){pendingQueue.current=null;setHasPendingQueue(false)}setNeedsRefresh(true);setMessage(`${saved?'저장은 완료했지만 재조회에 실패했습니다.':'요청 결과를 확인하지 못했습니다.'} ${e instanceof Error?e.message:''} 최신 원장을 조회한 뒤 계속하세요.`)}
  finally{working.current=false;setBusy(false)}
 }
 const why=busy?'저장 결과를 확인하고 있습니다.':needsRefresh?'최신 원장을 조회하세요.':!account?.isAdmin?'관리자 권한이 필요합니다.':'',disabled=!!why,serviceSource=serviceSources?.find(x=>x.id===sourceId),customer=customers.find(x=>x.id===(serviceSources?serviceSource?.customerId:customerId));
 return <section aria-label={serviceSources?"서비스 답변 원장":"소비자 발송 원장"}><h4>{serviceSources?"본인 문의 서비스 답변":"동의 기반 발송 원장"}</h4><Note>실제 연락처는 제공자에서 관리합니다. 고객 UUID와 등록된 템플릿 UUID·내용 해시만 전달합니다. 접수는 전달 완료가 아니며, 결과 미확인 건은 다시 보내지 않습니다.</Note>
 {message&&<p role="status">{message}</p>}<Button disabledReason="저장 결과를 확인하고 있습니다." disabled={busy} onClick={()=>{setMessage('');void load().catch(e=>setMessage(e.message))}}>최신 원장 조회</Button>
 {hasPendingQueue&&<Button disabled={busy} disabledReason="처리 중입니다." onClick={()=>{if(pendingQueue.current)void mutate(pendingQueue.current)}}>이전 대기 등록 재시도</Button>}
 {view&&<><p><MetaLine items={[`발송 연결: ${view.connection.enabled?'활성':'비활성'}`,`판 ${view.connection.version}`]}/></p>
 {account?.isOwner&&<details><summary>소유자 발송 연결</summary><p>연결한 판매처에 수신자 UUID·동의 정책·불변 템플릿이 등록된 별도 consumer API가 필요합니다. 최초 저장은 비활성입니다.</p>
 <Input aria-label="발송 테넌트 ID" autoComplete="off" value={tenant} placeholder={view.connection.tenantId||'테넌트 ID'} onChange={e=>setTenant(e.target.value)}/><Input aria-label="발송 제공자 매장 ID" autoComplete="off" value={store} placeholder={view.connection.providerStoreId||'제공자 매장 ID'} onChange={e=>setStore(e.target.value)}/><Input aria-label="발송 서명 비밀값" type="password" name="growth-consumer-signing-secret" autoComplete="new-password" value={secret} onChange={e=>setSecret(e.target.value)}/>
 <Button disabledReason={why} disabled={disabled} onClick={()=>void mutate({action:'configure',expectedVersion:view.connection.version,config:{tenantId:tenant||view.connection.tenantId,providerStoreId:store||view.connection.providerStoreId,secret,enabled:false}})}>연결 비활성 저장</Button>
 {view.connection.configured&&<Button disabledReason={why} disabled={disabled} onClick={async()=>{if(await askConfirm({title:view.connection.enabled?'발송 연결을 끌까요?':'발송 연결을 켤까요?',impact:'새 발송 요청의 허용 상태를 변경합니다. 수신자·동의·불변 템플릿의 제공자 등록이 필요합니다.',undo:'연결 상태는 다시 변경할 수 있습니다.',confirmLabel:'연결 변경'}))void mutate({action:'configure',expectedVersion:view.connection.version,config:{tenantId:tenant||view.connection.tenantId,providerStoreId:store||view.connection.providerStoreId,secret,enabled:!view.connection.enabled}})}}>{view.connection.enabled?'연결 끄기':'연결 켜기'}</Button>}</details>}
 <div className={styles.grid}>{serviceSources?<label>본인 문의<NativeSelect aria-label="응답할 본인 문의" value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">문의 선택</option>{serviceSources.map(x=><option key={x.id} value={x.id}>{x.id} (티켓 판 {x.ticketVersion})</option>)}</NativeSelect></label>:<><label>고객<NativeSelect aria-label="발송 고객" value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">고객 선택</option>{customers.map(x=><option key={x.id} value={x.id}>{x.id} (판 {x.version})</option>)}</NativeSelect></label><label>목적<NativeSelect value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="post_purchase">구매 후 관리</option><option value="marketing_reorder">마케팅·재구매</option></NativeSelect></label></>}
 <label>불변 템플릿 UUID<Input value={templateId} onChange={e=>setTemplateId(e.target.value)}/></label><label>템플릿 SHA-256<Input value={templateDigest} onChange={e=>setTemplateDigest(e.target.value)}/></label><label>최대 실제 발송비(KRW)<Input type="number" min="0" value={serviceSources?'0':maxCost} readOnly={!!serviceSources} onChange={e=>setMaxCost(e.target.value)}/></label><label>발송 만료(UTC ISO)<Input value={expires} placeholder="YYYY-MM-DDTHH:mm:ss.sssZ" onChange={e=>setExpires(e.target.value)}/></label><label>위임 ID<Input value={authorityId} onChange={e=>setAuthorityId(e.target.value)}/></label><label>위임 판<Input type="number" min="1" value={authorityVersion} onChange={e=>setAuthorityVersion(e.target.value)}/></label><label>재구매 대기 일수<Input type="number" min="0" max="365" value={waitDays} onChange={e=>setWaitDays(e.target.value)}/></label></div>
 <Button disabledReason={why||(hasPendingQueue?'이전 대기 요청을 먼저 확인하세요.':'고객을 선택하세요.')} disabled={disabled||!customer||hasPendingQueue} onClick={()=>void mutate({action:'queue',id:crypto.randomUUID(),input:{customerId:customer?.id,customerVersion:customer?.version,purpose:serviceSources?'service_reply':purpose,templateId,templateDigest,maxCostKrw:serviceSources?0:Number(maxCost),expiresAt:expires,waitDays:serviceSources?0:Number(waitDays),authorityId,authorityVersion:Number(authorityVersion),...(serviceSource?{serviceContext:{ticketId:serviceSource.id,ticketVersion:serviceSource.ticketVersion,sourceDigest:serviceSource.sourceDigest}}:{})}})}>발송 대기 저장</Button>
 <p>비용 0원은 T2 게시 위임, 유료 발송은 T3 지출 위임과 예산이 필요합니다.</p>
 {view.deliveries.map(row=><article key={row.id}><p><MetaLine items={[row.id,labels[row.status],`판 ${row.version}`,row.approval?.autoDispatch?'자동 발송 승인됨':row.approval?'승인됨':'',row.suppressed?'발송 억제됨':'',row.cancelPending?'제공자 취소 확인 필요':'']}/></p>
 {row.executionHeld&&<p>승인 이후 발송 조건이 변경되어 자동 실행을 보류했습니다. 현재 내용을 확인하고 다시 승인하세요.</p>}{row.csResponseHeld&&<p>문의 판이 변경되어 응답 이력 동기화를 보류했습니다. 제공자 게시 영수증은 보존됩니다.</p>}{row.input&&<p><MetaLine items={[row.input.purpose,`템플릿 ${row.input.templateId}`,`최대 ${row.maxCostKrw.toLocaleString()}원`,`만료 ${row.input.expiresAt}`]}/></p>}
 {row.status==='queued'&&!row.suppressed&&<><Button disabledReason={why||'소유자 승인이 필요합니다.'} disabled={disabled||!account?.isOwner} onClick={async()=>{if(await askConfirm({title:'발송 내용을 승인할까요?',impact:'현재 동의·주문·템플릿·비용·위임 판을 고정합니다.',undo:'발송 전 대기를 취소하거나 변경된 판으로 다시 승인할 수 있습니다.',confirmLabel:'발송 승인'}))void mutate({action:'approve',id:row.id,expectedVersion:row.version,confirm:true})}}>소유자 승인</Button><Button disabledReason={why||'소유자 승인이 필요합니다.'} disabled={disabled||!account?.isOwner} onClick={async()=>{if(await askConfirm({title:'이 발송을 자동 실행하도록 승인할까요?',impact:'이 수신자·템플릿·비용·위임 판에 한해 작업자가 다음 차례에 1회 발송합니다. 결과 미확인은 재전송하지 않고 조회합니다.',undo:'실행 전 대기를 취소할 수 있습니다. 조건이 바뀌면 새 승인이 필요합니다.',confirmLabel:'자동 발송 승인'}))void mutate({action:'approve',id:row.id,expectedVersion:row.version,confirm:true,autoDispatch:true})}}>자동 실행 승인</Button><Button disabledReason={why||'현재 발송 내용을 먼저 승인하세요.'} disabled={disabled||!row.approval} onClick={async()=>{if(await askConfirm({title:'승인 내용을 발송할까요?',impact:'승인된 수신자 UUID와 템플릿으로 실제 발송을 요청하고 최대 비용을 예약합니다.',undo:'제공자 접수 뒤에는 취소 결과를 별도로 확인해야 합니다.',confirmLabel:'발송 요청'}))void mutate({action:'dispatch',id:row.id,expectedVersion:row.version})}}>승인 내용 발송</Button></>}
 {deliveryNeedsReceipt(row)&&<Button disabledReason={why} disabled={disabled} onClick={()=>void mutate({action:'reconcile',id:row.id,expectedVersion:row.version})}>{row.cancelPending?'제공자 취소 확인':row.receipt?.costKrw===null&&['delivered','failed'].includes(row.status)?'실제 발송비 대사':'영수증 대사'}</Button>}
 {['queued','unknown','accepted'].includes(row.status)&&!row.suppressed&&<Button disabledReason={why} disabled={disabled} onClick={()=>void mutate({action:'cancel',id:row.id,expectedVersion:row.version})}>추가 발송 억제·취소 요청</Button>}</article>)}
 </>}
 </section>;
}
