'use client';
import {EmptyLine} from '@/components/app/empty-line';

import {Button} from '@/components/ui/button';
import {Note} from '@/components/app/note';
import {MetaLine} from '@/components/app/meta-line';
import styles from './growth-panel.module.css';
import type {GrowthOpportunityBoard,OpportunityDeadline,OpportunityPreparation} from '@/lib/growth-opportunity-board';

type Target={entity:'need'|'catalog'|'offer'|'mission';id:string};
type Props={board:GrowthOpportunityBoard;onOpen:(target:Target)=>void;disabled?:boolean;stale?:boolean};
type OpenProps=Pick<Props,'onOpen'|'disabled'>;
const preparation:Record<OpportunityPreparation,string>={held:'보류',unknown:'준비도 미확인',reviewable:'검토 가능'};
const states:Record<string,string>={hypothesis:'검증 전 가설',draft:'초안',staged:'준비 요청됨',unknown:'결과 미확인',failed:'실패 기록',observed:'관측됨(판매 성공 아님)',cancelled:'취소됨'};
const dateStates:Record<OpportunityDeadline['status'],string>={overdue:'기한 경과',today:'오늘',upcoming:'예정',missing:'기한 미확인',invalid:'기한 형식 확인 필요'};
const kst=(at:string|number)=>new Date(at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'});
function Deadline({value}:{value:OpportunityDeadline}){return <span>{dateStates[value.status]}: {value.at===null?'날짜를 확인하세요':/^\d{4}-\d{2}-\d{2}$/.test(value.raw)?`${value.raw} 한국시간 날짜 종료까지`:`${kst(value.at)} (한국시간)`}</span>}
function Reasons({items}:{items:string[]}){return items.length?<ul>{items.map((item,index)=><li key={index}>{item}</li>)}</ul>:null}
function Open({entity,id,title,...props}:Target&{title:string}&OpenProps){const labels={need:'기회',catalog:'상품',offer:'오퍼',mission:'미션'};return <Button variant="panel" size="fit" type="button" disabled={props.disabled} aria-label={`${labels[entity]} 기록 열기: ${title}`} onClick={()=>props.onOpen({entity,id})}>{labels[entity]} 기록 열기</Button>}
function Mission({row,...props}:{row:GrowthOpportunityBoard['unlinked']['missions'][number]}&OpenProps){return <article className={styles.mission}><h5>{row.title} v{row.version}</h5><p><MetaLine items={[states[row.status]??'상태 미확인',row.closed&&'종료된 시도 기록',preparation[row.preparation]]}/></p><p><Deadline value={row.deadline}/></p><p><MetaLine items={[`담당: ${row.assignee||'미확인'}`,`다음 행동: ${row.nextAction||'미확인'}`]}/></p><p><MetaLine items={[`연결 오퍼 ${row.offerId||'없음'}`,`참조 ${row.referenceVersion>0?`v${row.referenceVersion}`:'미확인'}`]}/></p><Reasons items={row.heldReasons}/><Open {...props} entity="mission" id={row.id} title={row.title}/></article>}
function Offer({row,...props}:{row:GrowthOpportunityBoard['unlinked']['offers'][number]}&OpenProps){return <article className={styles.mission}><h5>{row.title} v{row.version} ({preparation[row.preparation]})</h5><p>구매 이유: {row.purchaseReason||'미확인'}</p><p><MetaLine items={[`연결 상품 ${row.catalogId||'없음'}`,`참조 ${row.referenceVersion>0?`v${row.referenceVersion}`:'미확인'}`,`현재 ${row.currentCatalogVersion===null?'없음':`v${row.currentCatalogVersion}`}`]}/></p><Reasons items={row.heldReasons}/><Open {...props} entity="offer" id={row.id} title={row.title}/></article>}
function Schedule({rows,title,...props}:{rows:GrowthOpportunityBoard['schedule'];title:string}&OpenProps){return <section aria-label={title}><h4>{title}</h4>{!rows.length&&<EmptyLine next="다른 기간을 고르세요.">해당 일정이 없습니다.</EmptyLine>}{rows.map(row=><article className={styles.mission} key={row.key}><h5>{row.kind==='need'?'기회 검토':'판매 미션'}: {row.title}</h5><p><Deadline value={row.deadline}/></p><p><MetaLine items={[states[row.status]??'상태 미확인',preparation[row.preparation]]}/></p><p><MetaLine items={[`담당: ${row.assignee||'미확인'}`,`다음 행동: ${row.nextAction||'미확인'}`]}/></p><Reasons items={row.reasons}/><Open {...props} entity={row.kind} id={row.id} title={row.title}/></article>)}</section>}
export function GrowthOpportunityBoardView({board,onOpen,disabled=false,stale=false}:Props){
 const open={onOpen,disabled:disabled||stale},unknown=(row:GrowthOpportunityBoard['schedule'][number])=>row.deadline.status==='missing'||row.deadline.status==='invalid';
 return <section className={styles.panel} aria-label="기회·일정 보드"><h3>기회·일정 보드</h3><Note className={styles.note}>저장한 고객 기회마다 상품·오퍼·미션을 연결한 검토 목록입니다. 기회는 검증 전 가설이며 준비 조건 충족은 집행·판매 성공과 별개입니다.</Note><p><MetaLine items={[`평가 시각: ${kst(board.evaluatedAt)} (한국시간)`,`준비 요청·결과 확인 중 미션 ${board.activeMissionCount}개`,`초안 포함 미종료 미션 ${board.openMissionCount}개`]}/></p><p>{board.sortExplanation} 매출 예측 순위가 아닙니다.</p>{stale&&<p role="status" className={styles.warning}>이전 조회 결과입니다. 새로고침이 완료되기 전에는 현재 상태로 단정하지 마세요.</p>}{disabled&&<Note className={styles.note}>저장하지 않은 입력 또는 진행 중인 작업이 있어 기록 열기를 잠갔습니다. 현재 입력을 먼저 저장하거나 정리하세요.</Note>}
 {!board.opportunities.length&&<EmptyLine next="고객 기회를 저장하면 여기에 모입니다.">저장된 고객 기회가 없습니다.</EmptyLine>}{board.opportunities.map(row=><article key={row.id} className={styles.mission} aria-label={`기회 ${row.title}`}><h4>{row.title} v{row.version}</h4><p><MetaLine items={['검증 전 가설',preparation[row.preparation],<Deadline key="deadline" value={row.deadline}/>]}/></p><p><MetaLine items={[`상황: ${row.situation||'미확인'}`,`원하는 결과: ${row.desiredOutcome||'미확인'}`]}/></p><p><MetaLine items={[`현재 대안: ${row.alternative||'미확인'}`,`구매 장애물: ${row.barrier||'미확인'}`]}/></p><p>반례·반대 근거: {row.counterEvidence||'미확인'}</p><p><MetaLine items={[`담당: ${row.assignee||'미확인'}`,`다음 행동: ${row.nextAction||'미확인'}`]}/></p><p><MetaLine items={[`검토 가능 오퍼 ${row.readyOfferCount}`,`보류 오퍼 ${row.heldOfferCount}`]}/></p>{row.hasUnknownResult&&<p className={styles.note}>결과 미확인 미션이 있습니다. 외부 결과를 확인하기 전 재실행 근거로 사용하지 마세요.</p>}<Reasons items={row.reasons}/><Open {...open} entity="need" id={row.id} title={row.title}/>
 <section aria-label={`연결 상품 ${row.title}`}><h5>연결 상품</h5>{!row.catalogs.length&&<EmptyLine next="판매 기본 기록에서 연결하세요.">연결된 상품이 없습니다.</EmptyLine>}{row.catalogs.map(catalog=><div className={styles.mission} key={catalog.id}><strong>{catalog.title} v{catalog.version}</strong><p><MetaLine items={[`SKU ${catalog.sku||'미확인'}`,`단가 ${catalog.price===null?'미확인':`${catalog.price.toLocaleString('ko-KR')}원`}`]}/></p><Open {...open} entity="catalog" id={catalog.id} title={catalog.title}/></div>)}</section><section aria-label={`연결 오퍼 ${row.title}`}><h5>연결 오퍼</h5>{!row.offers.length&&<EmptyLine next="판매 기본 기록에서 연결하세요.">연결된 오퍼가 없습니다.</EmptyLine>}{row.offers.map(offer=><Offer key={offer.id} row={offer} {...open}/>)}</section><section aria-label={`연결 미션 ${row.title}`}><h5>연결 미션</h5>{!row.missions.length&&<EmptyLine next="판매 기본 기록에서 연결하세요.">연결된 미션이 없습니다.</EmptyLine>}{row.missions.map(mission=><Mission key={mission.id} row={mission} {...open}/>)}</section></article>)}
 <Schedule rows={board.schedule.filter(row=>!unknown(row))} title="기한별 일정" {...open}/><Schedule rows={board.schedule.filter(unknown)} title="기한 미확인 일정" {...open}/>{(board.unlinked.offers.length>0||board.unlinked.missions.length>0)&&<section aria-label="기회 연결이 없는 기록"><h4>기회 연결이 없는 기록</h4><p>연결되지 않은 기록도 보존합니다. 기존 기록에서 상품·오퍼·기회 연결을 확인하세요.</p>{board.unlinked.offers.map(row=><Offer key={row.id} row={row} {...open}/>)}{board.unlinked.missions.map(row=><Mission key={row.id} row={row} {...open}/>)}</section>}</section>;
}
