'use client';

import {Note} from '@/components/app/note';
import {useCallback,useEffect,useRef,useState} from 'react';
import {emptyCandidateInput,emptyComparisonInput,type CandidateInput,type ComparisonInput} from '@/lib/growth-sourcing';
import type {CatalogInput} from '@/lib/growth-catalog';
import styles from './growth-panel.module.css';

type Candidate={id:string;version:number;input:CandidateInput;updatedAt:string};
type Catalog={id:string;version:number;input:CatalogInput};
type Inventory={status:'known'|'unknown';available:number|null;reserved:number|null;onHand:number|null;shortage:number|null;unit:string;reason:string;items:{id:string;version:number}[]};
type Comparison={id:string;input:ComparisonInput;createdAt:string;currentChanged:boolean;snapshot:{catalog:Catalog;candidates:Candidate[];inventory:Inventory};assessment:{rows:{candidateId:string;candidateVersion:number;supplierCode:string;status:'comparable'|'held';missing:string[];quantity:number|null;totalCost:number|null;effectiveUnitCost:number|null;leadDays:number|null;projectedAvailable:number|null;projectedShortage:number|null}[];mayOrder:false}};
type View={candidates:Candidate[];candidateHistory:Candidate[];comparisons:Comparison[];catalogs:Catalog[];campaignVersion:number;canEdit:boolean;mayOrder:false};
const amount=(value:number|null|undefined)=>value===null||value===undefined?'미확인':value.toLocaleString('ko-KR');
const units:Record<string,string>={unknown:'미확인',piece:'개',pack:'팩'};
const tax:Record<string,string>={unknown:'미확인',included:'세금 포함',excluded:'세금 별도'};
const numericFields=[['unitCost','단위원가 (원)'],['moq','최소 주문 수량'],['leadDays','납기 (일)'],['shippingCost','배송비 (원)'],['extraCost','부대비 (원)']] as const;
async function request(campaignId:string,init:RequestInit={}):Promise<View>{
 const response=await fetch(`/api/growth/sourcing${init.method==='POST'?'':`?campaignId=${encodeURIComponent(campaignId)}`}`,{...init,cache:'no-store'}),raw:unknown=await response.json();
 if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('소싱 응답을 확인하지 못했습니다.');
 const data=raw as Record<string,unknown>;
 if(!response.ok)throw new Error(typeof data.error==='string'?data.error:'소싱 요청에 실패했습니다.');
 if(!['candidates','candidateHistory','comparisons','catalogs'].every(key=>Array.isArray(data[key]))||typeof data.campaignVersion!=='number'||typeof data.canEdit!=='boolean')throw new Error('소싱 응답을 확인하지 못했습니다.');
 return data as unknown as View;
}
function CandidateSnapshot({row}:{row:Candidate}){return <dl><div><dt>공급 후보 · 판</dt><dd>{row.input.supplierCode} · v{row.version}</dd></div><div><dt>상품 판 · 단위</dt><dd>v{row.input.catalogVersion} · {units[row.input.unit]}</dd></div>{numericFields.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{amount(row.input[key])}</dd></div>)}<div><dt>세금 · 견적 유효기한</dt><dd>{tax[row.input.taxBasis]} · {row.input.validUntil||'미확인'}</dd></div><div><dt>증빙 참조 · 메모</dt><dd>{row.input.evidenceRef||'미기록'} · {row.input.note||'미기록'}</dd></div></dl>}
function ComparisonHistory({rows}:{rows:Comparison[]}){return <section aria-label="저장된 소싱 비교"><h4>저장된 소싱 비교</h4>{!rows.length&&<p>기록된 비교가 없습니다.</p>}{rows.map(row=><article key={row.id} className={styles.mission}><h4>{row.snapshot.catalog.input.title||row.snapshot.catalog.input.sku} · 요청 {row.input.requestedQuantity}{units[row.input.unit]}</h4><p>{row.createdAt} · 상품 v{row.input.catalogVersion} · 자동 발주 권한 없음</p>{row.currentChanged&&<p className={styles.note}>현재 상품·견적·재고 또는 유효 조건이 달라졌습니다. 이 비교는 저장 당시 판을 유지합니다.</p>}<p>{row.input.note||'비교 메모 없음'}</p><div><strong>저장 당시 현재 재고 원장 참조</strong><p>원장 보유 {amount(row.snapshot.inventory.onHand)} · 예약 {amount(row.snapshot.inventory.reserved)} · 가용 {amount(row.snapshot.inventory.available)} · 부족 {amount(row.snapshot.inventory.shortage)} {units[row.snapshot.inventory.unit]}</p><p>{row.snapshot.inventory.reason}</p><p>원장 참조: {row.snapshot.inventory.items.map(item=>`${item.id} v${item.version}`).join(', ')||'미확인'}</p></div>{row.assessment.rows.map(candidate=><div className={styles.mission} key={candidate.candidateId}><h4>{candidate.supplierCode} · v{candidate.candidateVersion} · {candidate.status==='held'?'비교 보류':'비용 비교 가능'}</h4><p>세금 기준: {tax[row.snapshot.candidates.find(item=>item.id===candidate.candidateId)?.input.taxBasis??'unknown']} · 세금 별도 견적은 세액을 추정하지 않습니다.</p><p>계산 수량 {amount(candidate.quantity)}{units[row.input.unit]} · 견적 기준 총비용 {amount(candidate.totalCost)}원 · 수량당 비용 {amount(candidate.effectiveUnitCost)}원 · 납기 {amount(candidate.leadDays)}일</p><p>입고 가정 가용 {amount(candidate.projectedAvailable)} · 입고 가정 부족 {amount(candidate.projectedShortage)} {units[row.input.unit]} — 실제 입고 기록이 아닙니다.</p>{candidate.missing.length>0&&<ul>{candidate.missing.map((reason,index)=><li key={index}>{reason}</li>)}</ul>}</div>)}<details><summary>비교 당시 후보 견적</summary>{row.snapshot.candidates.map(candidate=><CandidateSnapshot key={candidate.id} row={candidate}/>)}</details></article>)}</section>}
function SourcingEditor({campaignId,view,onView,onBusy,busy}:{campaignId:string;view:View;onView:(v:View)=>void;onBusy:(v:boolean)=>void;busy:boolean}){
 const [identity,setIdentity]=useState(()=>({id:crypto.randomUUID(),version:0})),[draft,setDraft]=useState(emptyCandidateInput),[basis,setBasis]=useState(view.campaignVersion);
 const [comparison,setComparison]=useState(emptyComparisonInput),[comparisonId,setComparisonId]=useState(()=>crypto.randomUUID()),[error,setError]=useState(''),[message,setMessage]=useState('');
 const retry=useRef<{key:string;id:string}|null>(null),write=useRef<AbortController|null>(null),mounted=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;write.current?.abort();};},[]);
 const selected=view.candidates.find(row=>row.id===identity.id),stale=!!selected&&selected.version!==identity.version,campaignStale=basis!==view.campaignVersion,locked=busy||!view.canEdit||campaignStale;
 const catalogRef=`${draft.catalogId}:${draft.catalogVersion}`,comparisonRef=`${comparison.catalogId}:${comparison.catalogVersion}`;
 const comparisonCandidates=view.candidates.filter(row=>row.input.catalogId===comparison.catalogId&&row.input.catalogVersion===comparison.catalogVersion);
 const comparisonStale=comparison.candidates.some(ref=>!comparisonCandidates.some(row=>row.id===ref.id&&row.version===ref.version));
 function pick(row?:Candidate){if(row?.id===identity.id)return;setIdentity(row?{id:row.id,version:row.version}:{id:crypto.randomUUID(),version:0});setDraft(row?structuredClone(row.input):emptyCandidateInput());setBasis(view.campaignVersion);setError('');setMessage('');retry.current=null;}
 async function mutate(action:'save_candidate'|'capture_comparison'){
  if(write.current||locked)return;const payload={action,id:action==='save_candidate'?identity.id:comparisonId,expectedVersion:action==='save_candidate'?identity.version:0,campaignId,campaignVersion:basis,input:action==='save_candidate'?draft:comparison},key=JSON.stringify(payload),requestId=retry.current?.key===key?retry.current.id:crypto.randomUUID();retry.current={key,id:requestId};const c=new AbortController();write.current=c;onBusy(true);setError('');setMessage('');
  try{const next=await request(campaignId,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,requestId}),signal:c.signal});if(!mounted.current||c.signal.aborted)return;onView(next);setBasis(next.campaignVersion);retry.current=null;if(action==='save_candidate'){const row=next.candidates.find(item=>item.id===identity.id);if(row){setIdentity({id:row.id,version:row.version});setDraft(row.input);}}else{setComparisonId(crypto.randomUUID());}setMessage(action==='save_candidate'?'소싱 후보를 저장했습니다.':'소싱 비교를 기록했습니다.');}
  catch(e){if(mounted.current&&!c.signal.aborted)setError(`${e instanceof Error?e.message:'저장하지 못했습니다.'} 입력은 보존했습니다. 응답 미확인은 동일 입력으로 재시도하고, 충돌은 새로고침 후 최신 판을 검토하세요.`);}
  finally{write.current=null;if(mounted.current&&!c.signal.aborted)onBusy(false);}
 }
 return <>{!view.canEdit&&<p className={styles.note}>조회 전용입니다. 관리자 권한과 캠페인 상태에 따라 편집할 수 있습니다.</p>}{error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.success}>{message}</p>}{campaignStale&&<div className={styles.error}>캠페인 판이 변경되었습니다.<button type="button" disabled={busy} onClick={()=>{setBasis(view.campaignVersion);setError('');}}>현재 입력 유지 · 최신 캠페인 판 사용</button></div>}
 <div className={styles.workspace}><div role="group" className={styles.list} aria-label="소싱 후보 목록"><button type="button" disabled={busy||!view.canEdit} onClick={()=>pick()}>새 소싱 후보</button>{view.candidates.map(row=><button key={row.id} type="button" disabled={busy} aria-pressed={row.id===identity.id} onClick={()=>pick(row)}>{row.input.supplierCode||'이름 미기록'} · v{row.version}</button>)}</div><section aria-label="소싱 후보 편집" className={styles.editor}><h4>{identity.version?`소싱 후보 편집 · v${identity.version}`:'새 소싱 후보'}</h4>{stale&&<div className={styles.error}>후보가 v{selected.version}로 바뀌었습니다.<details><summary>최신 후보 견적 검토</summary><CandidateSnapshot row={selected}/></details><button type="button" disabled={busy} onClick={()=>{setIdentity({id:selected.id,version:selected.version});setError('');}}>현재 입력 유지 · 최신 후보 판 사용</button></div>}
 <form onSubmit={event=>{event.preventDefault();void mutate('save_candidate');}}><fieldset disabled={locked||stale} className={styles.form}><legend className={styles.srOnly}>소싱 후보 입력</legend><label className={styles.wide}>후보 상품 판<select required value={draft.catalogId?catalogRef:''} onChange={event=>{const [id,version]=event.target.value.split(':');setDraft({...emptyCandidateInput(),catalogId:id,catalogVersion:Number(version)||0});retry.current=null;}}><option value="">상품 선택</option>{draft.catalogId&&!view.catalogs.some(row=>`${row.id}:${row.version}`===catalogRef)&&<option value={catalogRef}>이전 상품 판 · 다시 선택 필요</option>}{view.catalogs.map(row=><option key={row.id} value={`${row.id}:${row.version}`}>{row.input.title||row.input.sku} · {row.input.sku} · v{row.version}</option>)}</select></label>
 <label className={styles.wide}>공급 후보 내부 코드<input required maxLength={120} value={draft.supplierCode} onChange={event=>setDraft(previous=>({...previous,supplierCode:event.target.value}))}/></label><label>후보 수량 단위<select value={draft.unit} onChange={event=>setDraft(previous=>({...previous,unit:event.target.value as CandidateInput['unit']}))}>{Object.entries(units).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{numericFields.map(([key,label])=><label key={key}>{label}<input type="number" step={1} min={key==='moq'?1:0} value={draft[key]??''} onChange={event=>setDraft(previous=>({...previous,[key]:event.target.value===''?null:Number(event.target.value)}))}/></label>)}<label>세금 기준<select value={draft.taxBasis} onChange={event=>setDraft(previous=>({...previous,taxBasis:event.target.value as CandidateInput['taxBasis']}))}>{Object.entries(tax).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>견적 유효기한<input type="date" value={draft.validUntil} onChange={event=>setDraft(previous=>({...previous,validUntil:event.target.value}))}/></label><label className={styles.wide}>견적 증빙 내부 참조<input maxLength={120} value={draft.evidenceRef} onChange={event=>setDraft(previous=>({...previous,evidenceRef:event.target.value}))}/></label><label className={styles.wide}>후보 메모<textarea rows={2} maxLength={1000} value={draft.note} onChange={event=>setDraft(previous=>({...previous,note:event.target.value}))}/></label><button type="submit">소싱 후보 저장</button></fieldset></form>{selected&&<details><summary>후보 과거 판</summary>{view.candidateHistory.filter(row=>row.id===selected.id).map(row=><CandidateSnapshot key={`${row.id}:${row.version}`} row={row}/>)}</details>}</section></div>
 <section aria-label="소싱 비교 작성"><h4>소싱 비교 작성</h4><p>동일한 상품 판과 수량 단위로 후보를 2개 이상 선택합니다. 최소 주문 수량은 주문 배수 조건이 아닙니다. 배송비·부대비는 해당 계산 수량에 대한 고정 총액입니다. 세금·필수 원가·유효기한이 미확인인 후보는 보류합니다.</p><form onSubmit={event=>{event.preventDefault();void mutate('capture_comparison');}}><fieldset disabled={locked} className={styles.form}><legend className={styles.srOnly}>비교 입력</legend><label className={styles.wide}>비교 상품 판<select required value={comparison.catalogId?comparisonRef:''} onChange={event=>{const [id,version]=event.target.value.split(':');setComparison({...emptyComparisonInput(),catalogId:id,catalogVersion:Number(version)||0});setComparisonId(crypto.randomUUID());retry.current=null;}}><option value="">상품 선택</option>{comparison.catalogId&&!view.catalogs.some(row=>`${row.id}:${row.version}`===comparisonRef)&&<option value={comparisonRef}>이전 상품 판 · 다시 선택 필요</option>}{view.catalogs.map(row=><option key={row.id} value={`${row.id}:${row.version}`}>{row.input.title||row.input.sku} · {row.input.sku} · v{row.version}</option>)}</select></label><label>요청 수량<input type="number" required min={1} step={1} value={comparison.requestedQuantity} onChange={event=>setComparison(previous=>({...previous,requestedQuantity:Number(event.target.value)}))}/></label><label>비교 수량 단위<select value={comparison.unit} onChange={event=>setComparison(previous=>({...previous,unit:event.target.value as ComparisonInput['unit']}))}><option value="piece">개</option><option value="pack">팩</option></select></label><fieldset className={styles.references}><legend>비교 후보 판</legend>{comparisonCandidates.map(row=><label key={row.id} className={styles.check}><input type="checkbox" checked={comparison.candidates.some(ref=>ref.id===row.id)} onChange={event=>setComparison(previous=>({...previous,candidates:event.target.checked?[...previous.candidates.filter(ref=>ref.id!==row.id),{id:row.id,version:row.version}]:previous.candidates.filter(ref=>ref.id!==row.id)}))}/>{row.input.supplierCode} · v{row.version} · {units[row.input.unit]}</label>)}{comparisonStale&&<p className={styles.error}>선택한 후보 판이 변경되었습니다. 비교할 후보를 해제하고 최신 판으로 다시 선택하세요.<button type="button" onClick={()=>setComparison(previous=>({...previous,candidates:[]}))}>후보 선택 초기화</button></p>}</fieldset><label className={styles.wide}>비교 메모<textarea rows={2} maxLength={1000} value={comparison.note} onChange={event=>setComparison(previous=>({...previous,note:event.target.value}))}/></label><button type="submit" disabled={comparison.candidates.length<2||comparisonStale}>소싱 비교 기록</button></fieldset></form></section><ComparisonHistory rows={view.comparisons}/></>;
}
export function GrowthSourcingPanel({campaignId}:{campaignId:string}){
 const [view,setView]=useState<View|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');const read=useRef<AbortController|null>(null);
 const load=useCallback(async(signal:AbortSignal)=>{setLoading(true);setError('');try{const next=await request(campaignId,{signal});if(!signal.aborted)setView(next);}catch(e){if(!signal.aborted)setError(e instanceof Error?e.message:'소싱 기록 조회에 실패했습니다.');}finally{if(!signal.aborted)setLoading(false);}},[campaignId]);
 useEffect(()=>{const c=new AbortController();read.current=c;void Promise.resolve().then(()=>{if(!c.signal.aborted)void load(c.signal);});return()=>read.current?.abort();},[load]);
 function reload(){read.current?.abort();const c=new AbortController();read.current=c;void load(c.signal);}
 return <section aria-label="상품 소싱 비교" className={styles.panel}><header className={styles.header}><div><h3>상품 소싱 비교</h3><p>단일 SKU의 공급 견적을 같은 요청 수량으로 비교하고 당시 판을 보존합니다.</p></div><button aria-label="소싱 기록 새로고침" type="button" disabled={busy||loading} onClick={reload}>새로고침</button></header><Note className={styles.note}>빈 금액은 미확인, 0은 확인한 값입니다. 모든 비용은 원화 견적 기준이며 현금 잔고가 아닙니다. 현재 재고 원장은 참조 자료이며 실제 입고·발주 가능 여부를 보증하지 않습니다. 자동 발주 권한 없음 · 최저가 자동 채택 없음. 개인정보 없이 내부 코드와 증빙 참조만 기록하세요.</Note>{loading&&<p role="status">소싱 기록을 불러오고 있습니다.</p>}{error&&<p role="alert" className={styles.error}>{error}</p>}{view&&<SourcingEditor key={campaignId} campaignId={campaignId} view={view} busy={busy||loading} onView={next=>{read.current?.abort();setLoading(false);setView(next);}} onBusy={value=>{if(value){read.current?.abort();setLoading(false);}setBusy(value);}}/>}</section>;
}
