'use client';
import {EmptyLine} from '@/components/app/empty-line';
import {MetaLine} from '@/components/app/meta-line';
import {metaText} from '@/lib/format';

import {CheckInput} from '@/components/app/check';
import {NativeSelect} from '@/components/ui/native-select';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Note} from '@/components/app/note';
import {useCallback,useEffect,useRef,useState} from 'react';
import styles from './growth-panel.module.css';
import type {GrowthPublicationView} from '@/lib/growth-publication-server';

type View=GrowthPublicationView;
type RecordedAck={recorded:true;viewUnavailable:true;resultLinkId:string;duplicate:boolean;mayExecute:false};
type Link=View['links'][number];
type PublicationPreview=Pick<View['publications'][number],'caption'|'scheduledAt'|'plannedCostKRW'|'creativeId'|'creativeVersion'>&{version?:number;channelId?:string|null};
const states:Record<string,string>={linked:'연결 완료(전송 전)',submitting:'접수 확인 중',unknown:'외부 결과 미확인(예약 유지)',scheduled:'접수·예약 확인(발행 전)',published:'발행 확인(판매 효과 미확인)',failed:'발행 실패(무집행 여부 별도 확인)',cancelled:'취소 기록'};
const publicationStates:Record<string,string>={draft:'승인 전',approved:'실행 승인(미전송)',submitting:'접수 확인 중',uncertain:'접수 여부 미확인',accepted:'접수·예약 확인',published:'발행 확인',failed:'실패',cancelled:'취소',blocked:'공급자 확인 필요'};
async function request(campaignId:string,init?:RequestInit,allowAck?:false):Promise<View>;
async function request(campaignId:string,init:RequestInit,allowAck:true):Promise<View|RecordedAck>;
async function request(campaignId:string,init:RequestInit={},allowAck=false):Promise<View|RecordedAck>{
 const response=await fetch(`/api/growth/publication${init.method==='POST'?'':`?campaignId=${encodeURIComponent(campaignId)}`}`,{...init,cache:'no-store'}),raw:unknown=await response.json();
 if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('자연유입 발행 연결 응답을 확인하지 못했습니다.');const data=raw as Record<string,unknown>;
 if(!response.ok)throw new Error(typeof data.error==='string'?data.error:'발행 연결 요청에 실패했습니다.');
 if(allowAck&&data.recorded===true&&data.viewUnavailable===true&&typeof data.resultLinkId==='string')return data as unknown as RecordedAck;
 if(!['links','intents','publications'].every(key=>Array.isArray(data[key]))||typeof data.campaignVersion!=='number'||typeof data.canLink!=='boolean'||typeof data.canSync!=='boolean')throw new Error('자연유입 발행 연결 응답을 확인하지 못했습니다.');return data as unknown as View;
}
function Preview({publication,version=publication.version}:{publication:PublicationPreview;version?:number}){return <div className={styles.mission}><strong>승인 발행 내용(판 {version===undefined?'미확인':`v${version}`})</strong><p className="whitespace-pre-wrap">{publication.caption}</p><p><MetaLine items={[`예약 시각 ${publication.scheduledAt}`,`예정 비용 ${publication.plannedCostKRW.toLocaleString('ko-KR')}원`,`채널 ${publication.channelId||'미확인'}`]}/></p><p><MetaLine items={[`소재 내부 ID ${publication.creativeId}`,`v${publication.creativeVersion}`]}/></p><p>이미지는 기존 발행 화면에서 확인하세요. 이 화면은 이미지를 외부에서 불러오지 않습니다.</p></div>}
function Editor({campaignId,view,busy,onBusy,onView,onChanged}:{campaignId:string;view:View;busy:boolean;onBusy:(v:boolean)=>void;onView:(v:View)=>void;onChanged:(intentIds:string[])=>void}){
 const [draft,setDraft]=useState({intentId:'',intentVersion:0,publicationId:'',publicationVersion:0,evidenceRef:'',contentConfirmed:false}),[basis,setBasis]=useState(view.campaignVersion),[error,setError]=useState(''),[message,setMessage]=useState(''),[unavailableView,setUnavailableView]=useState<View|null>(null);
 const retry=useRef<{key:string;id:string}|null>(null),pending=useRef<AbortController|null>(null),mounted=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;pending.current?.abort();};},[]);
 const viewUnavailable=unavailableView===view,locked=busy||viewUnavailable;
 const intent=view.intents.find(row=>row.id===draft.intentId),publication=view.publications.find(row=>row.id===draft.publicationId),staleIntent=!!draft.intentId&&intent?.version!==draft.intentVersion,stalePublication=!!draft.publicationId&&publication?.version!==draft.publicationVersion,staleCampaign=basis!==view.campaignVersion;
 const eligibleIntents=view.intents.filter(row=>row.channel==='organic'&&row.state==='prepared'&&!view.links.some(link=>link.intentId===row.id)),eligiblePublications=view.publications.filter(row=>row.status==='approved'&&!row.attemptedAt&&!row.providerId&&!row.needsReview&&!view.links.some(link=>link.publicationId===row.id));
 async function mutate(action:'link_publication'|'sync_publication',link?:Link){
  if(pending.current||locked)return;const current=link?view.publications.find(row=>row.id===link.publicationId):undefined;if(link&&!current){setError('발행 기록이 조회되지 않습니다. 새로고침해 확인하세요.');return;}
  const payload=action==='link_publication'?{action,campaignId,campaignVersion:basis,...draft,expectedVersion:0}:{action,campaignId,campaignVersion:view.campaignVersion,id:link!.id,expectedVersion:link!.version,publicationVersion:current!.version};
  const key=JSON.stringify(payload),requestId=retry.current?.key===key?retry.current.id:crypto.randomUUID();retry.current={key,id:requestId};const c=new AbortController();pending.current=c;onBusy(true);setError('');setMessage('');
  try{const next=await request(campaignId,{method:'POST',signal:c.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,requestId})},true);if(!mounted.current||c.signal.aborted)return;if('viewUnavailable' in next){const targetId=link?.id??draft.intentId;if(next.resultLinkId!==targetId)throw new Error('저장 대상 확인이 필요합니다.');retry.current=null;setUnavailableView(view);onChanged([link?.intentId??draft.intentId]);setMessage('발행 연결 기록을 저장했습니다. 최신 목록은 조회하지 못했습니다. 새로고침으로 현재 상태를 확인하세요.');return;}onView(next);onChanged(next.links.map(row=>row.intentId));setBasis(next.campaignVersion);retry.current=null;setMessage(action==='link_publication'?'발행을 연결했습니다. 외부 전송은 기존 발행 화면에서 별도로 실행하세요.':'서버에 저장된 발행 결과를 동기화했습니다. 공급자 조회나 재전송은 하지 않았습니다.');}
  catch(e){if(mounted.current&&!c.signal.aborted)setError(`${e instanceof Error?e.message:'기록하지 못했습니다.'} 입력은 보존했습니다. 응답 미확인은 같은 입력으로 재시도하고, 충돌은 새로고침 후 정확한 판을 다시 확인하세요.`);}
  finally{pending.current=null;if(mounted.current&&!c.signal.aborted)onBusy(false);}
 }
 function chooseIntent(id:string){setDraft({intentId:id,intentVersion:view.intents.find(row=>row.id===id)?.version??0,publicationId:'',publicationVersion:0,evidenceRef:'',contentConfirmed:false});setError('');setMessage('');retry.current=null;}
 function choosePublication(id:string){setDraft(previous=>({...previous,publicationId:id,publicationVersion:view.publications.find(row=>row.id===id)?.version??0,evidenceRef:'',contentConfirmed:false}));setError('');setMessage('');retry.current=null;}
 return <>{viewUnavailable&&<p className={styles.note}>저장은 완료됐습니다. 아래는 마지막 조회 기록이며 새 목록을 확인하기 전 추가 쓰기를 막습니다.</p>}{error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.success}>{message}</p>}<p><MetaLine items={[`Buffer 연결: ${view.publisher.connected?'연결됨':'연결 없음'}`,`채널 내부 ID ${view.publisher.channelId||'미확인'}`,`계정 표시 ${view.publisher.account||'미확인'}`]}/></p><Note className={styles.note}>자연유입 위임의 계정 내부 ID는 Buffer 채널 ID와 정확히 같아야 합니다. 표시용 계정 이름이 아닌 ID로 연결합니다.</Note>
 {staleCampaign&&<div className={styles.error}>캠페인 판이 달라졌습니다.<Button variant="panel" size="fit" disabled={locked} type="button" onClick={()=>{setBasis(view.campaignVersion);setDraft(previous=>({...previous,contentConfirmed:false}));setError('');}}>현재 입력 유지하고 최신 캠페인 판 사용</Button></div>}
 <form onSubmit={event=>{event.preventDefault();void mutate('link_publication');}}><fieldset disabled={locked||!view.canLink} className={styles.form}><legend>자연유입 실행과 발행 연결</legend><label className={styles.wide}>예약된 자연유입 실행<NativeSelect value={draft.intentId} onChange={event=>chooseIntent(event.target.value)}><option value="">실행 선택</option>{draft.intentId&&!eligibleIntents.some(row=>row.id===draft.intentId)&&<option value={draft.intentId}>이전 선택(현재 연결 불가)</option>}{eligibleIntents.map(row=><option key={row.id} value={row.id}>{metaText([row.missionTitle||row.missionId,`v${row.version}`])}</option>)}</NativeSelect></label>{staleIntent&&<div className={styles.error}>실행 판이 달라졌습니다.{intent&&<Button variant="panel" size="fit" type="button" onClick={()=>{setDraft(previous=>({...previous,intentVersion:intent.version,contentConfirmed:false}));setError('');}}>현재 입력 유지하고 최신 실행 판 사용</Button>}</div>}
 {intent?.offer&&<div className={styles.mission}><strong><MetaLine items={[intent.offerTitle||intent.offerId,`오퍼 v${intent.offerVersion}`]}/></strong><p><MetaLine items={[`단가 ${intent.offer.price===null?'미확인':intent.offer.price.toLocaleString('ko-KR')}원`,`수량 ${intent.offer.quantity}`]}/></p><p>{intent.offer.purchaseReason}</p><p>구매 경로: {intent.offer.landingUrl||'미확인'}</p></div>}
 <label className={styles.wide}>승인된 미시도 발행<NativeSelect value={draft.publicationId} onChange={event=>choosePublication(event.target.value)}><option value="">발행 선택</option>{draft.publicationId&&!eligiblePublications.some(row=>row.id===draft.publicationId)&&<option value={draft.publicationId}>이전 선택(현재 연결 불가)</option>}{eligiblePublications.map(row=><option key={row.id} value={row.id}>{metaText([row.caption.slice(0,70)||row.id,`v${row.version}`])}</option>)}</NativeSelect></label>{stalePublication&&<div className={styles.error}>발행 판이 달라졌습니다. 아래 최신 승인 내용을 검토하고 일치 확인을 다시 해주세요.{publication&&<Button variant="panel" size="fit" type="button" onClick={()=>{setDraft(previous=>({...previous,publicationVersion:publication.version,contentConfirmed:false}));setError('');}}>현재 입력 유지하고 최신 발행 판 사용</Button>}</div>}{publication&&<div className={styles.wide}><Preview publication={publication}/></div>}
 <label className={styles.wide}>내용·오퍼 일치 확인 근거<Input maxLength={160} required value={draft.evidenceRef} onChange={event=>setDraft(previous=>({...previous,evidenceRef:event.target.value}))}/></label><label className={styles.check}><CheckInput checked={draft.contentConfirmed} onChange={event=>setDraft(previous=>({...previous,contentConfirmed:event.target.checked}))}/>기존 발행 화면의 이미지·승인 문구·계정과 연결 오퍼가 일치함을 확인했습니다</label><Button variant="panel" size="fit" type="submit" disabled={staleCampaign||staleIntent||stalePublication||!draft.contentConfirmed||!draft.evidenceRef.trim()||!eligibleIntents.some(row=>row.id===draft.intentId)||!eligiblePublications.some(row=>row.id===draft.publicationId)} disabledReason={staleCampaign?'다른 곳에서 먼저 바뀌었습니다. 최신 기록을 불러온 뒤 다시 하세요.':staleIntent?'다른 곳에서 먼저 바뀌었습니다. 최신 기록을 불러온 뒤 다시 하세요.':stalePublication?'다른 곳에서 먼저 바뀌었습니다. 최신 기록을 불러온 뒤 다시 하세요.':!draft.contentConfirmed?'확인 칸을 먼저 체크하세요.':(!draft.evidenceRef.trim())?'필수 칸을 먼저 채우세요.':(!eligibleIntents.some(row=>row.id===draft.intentId))?'고를 수 있는 의도를 먼저 고르세요.':(!eligiblePublications.some(row=>row.id===draft.publicationId))?'고를 수 있는 발행을 먼저 고르세요.':undefined}>발행 연결 기록</Button></fieldset></form>{!view.canLink&&<p>현재 권한·캠페인 상태에서는 새 발행을 연결할 수 없습니다.</p>}
 <section aria-label="연결된 자연유입 발행"><h4>연결된 자연유입 발행</h4>{!view.links.length&&<EmptyLine first="발행 연결">연결 기록이 없습니다.</EmptyLine>}{view.links.map(link=>{const current=view.publications.find(row=>row.id===link.publicationId);return <article key={link.id} className={styles.mission}><h4>{view.intents.find(row=>row.id===link.intentId)?.missionTitle||link.intentId}</h4><strong><MetaLine items={[states[link.status]??link.status,`연결 v${link.version}`]}/></strong>{!!link.syncHeldReasons?.length&&<ul>{link.syncHeldReasons.map((reason,index)=><li key={index}>{reason}</li>)}</ul>}<p><MetaLine items={[`반영한 발행 v${link.lastPublicationVersion}`,`마지막 동기화 ${link.updatedAt}`]}/></p><p>현재 서버 발행: <MetaLine items={current?[publicationStates[current.status]??current.status,`v${current.version}`,current.version!==link.lastPublicationVersion&&'아직 연결에 반영하지 않은 판']:['조회 불가']}/></p><p>발행 내부 ID {link.publicationId}</p><p>{link.releaseEvidence==='never_attempted_cancelled'?'미시도 취소 근거를 확인했습니다. 예산·재고 해제는 별도 대사에서 확인하세요.':'예약은 유지합니다. 예산·재고 해제는 별도 대사에서 합니다.'}</p><Button variant="panel" size="fit" type="button" disabled={locked||!view.canSync||!current} disabledReason={!view.canSync?'동기화 권한이 없거나 연결이 꺼져 있습니다.':!current?'먼저 대상을 고르세요.':undefined} onClick={()=>void mutate('sync_publication',link)}>저장된 발행 결과 동기화</Button><details><summary>연결 당시 내용·확인 근거</summary><p><MetaLine items={[`확인 담당 ${link.snapshot.confirmedBy}`,link.snapshot.confirmedAt]}/></p><p>내부 근거 {link.snapshot.evidenceRef}</p><Preview publication={link.snapshot.publication} version={link.snapshot.approvedPublicationVersion}/></details></article>})}</section></>;
}
export function GrowthPublicationPanel({campaignId,onChanged}:{campaignId:string;onChanged:(intentIds:string[])=>void}){
 const [view,setView]=useState<View|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');const read=useRef<AbortController|null>(null);
 const load=useCallback(async(signal:AbortSignal)=>{setLoading(true);setError('');try{const next=await request(campaignId,{signal});if(!signal.aborted)setView(next);}catch(e){if(!signal.aborted)setError(e instanceof Error?e.message:'발행 연결을 조회하지 못했습니다.');}finally{if(!signal.aborted)setLoading(false);}},[campaignId]);
 useEffect(()=>{const c=new AbortController();read.current=c;void Promise.resolve().then(()=>{if(!c.signal.aborted)void load(c.signal);});return()=>read.current?.abort();},[load]);
 function reload(){read.current?.abort();const c=new AbortController();read.current=c;void load(c.signal);}
 return <section aria-label="자연유입 발행 연결" className={styles.panel}><header className={styles.header}><div><h3>자연유입 발행 연결</h3><p>예약한 판매 실행 하나를 같은 캠페인의 승인된 미시도 발행 하나와 연결합니다.</p></div><Button variant="panel" size="fit" aria-label="발행 연결 새로고침" type="button" disabled={busy||loading} onClick={reload}>새로고침</Button></header><Note className={styles.note}>연결·동기화는 발행 전송과 별개입니다. 전송·공급자 결과 조회는 캠페인의 기존 발행 화면에서 실행하세요. 접수·예약은 실제 발행이 아니며, 발행 확인은 주문·판매 효과의 증명이 아닙니다. 연결한 뒤에는 실행 결과를 공급자 조회로만 받습니다.</Note>{loading&&<p role="status">발행 연결을 확인하고 있습니다.</p>}{error&&<p role="alert" className={styles.error}>{error}</p>}{view&&<Editor key={campaignId} campaignId={campaignId} view={view} busy={busy||loading} onView={next=>{read.current?.abort();setLoading(false);setView(next);}} onChanged={onChanged} onBusy={value=>{if(value){read.current?.abort();setLoading(false);}setBusy(value);}}/>}</section>;
}
