'use client';

import {NativeSelect} from '@/components/ui/native-select';
import {Textarea} from '@/components/ui/textarea';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Note} from '@/components/app/note';
import {useCallback,useEffect,useRef,useState} from 'react';
import {emptyTargetInput,emptyReviewInput,type TargetInput,type ReviewInput} from '@/lib/growth-targets';
import styles from './growth-panel.module.css';
import {ScreenSkeleton} from '@/components/app/screen-skeleton';

type Target={id:string;version:number;input:TargetInput;createdAt:string;updatedAt:string;assessment?:{missing:string[]}};
type Assessment={status:'held'|'interim'|'observed_met'|'observed_below';missing:string[];observedValue:number|null;absoluteChange:number|null;observedContributionBeforeMarketing:number|null};
type Review={id:string;targetId:string;targetVersion:number;input:ReviewInput;snapshot:{target:Target;decision:{id:string;version:number;input:{title:string}}|null};assessment:Assessment;createdAt:string;currentTargetChanged:boolean;currentBusinessChanged?:boolean};
type Comparison={reviewId:string;currentBusinessChanged:boolean|null;comparisonStatus:'comparable'|'unavailable';scopeChanged:boolean;checkedAt:string;currentTargetChanged:boolean;currentBusiness:{netRevenue:number|null;paidOrders:number|null;contributionBeforeMarketing:number|null}};
type View={reviewComparison?:Comparison;targets:Target[];targetHistory:Target[];reviews:Review[];decisions:{id:string;version:number;input:{title:string}}[];campaignVersion:number;canEdit:boolean;mayExecute:false};
const targetTextFields:readonly (readonly [keyof TargetInput,string])[]=[['title','목표 제목'],['denominator','분모·집계 기준'],['assignee','담당 역할'],['autonomyScope','자율 범위'],['profitCondition','최소 수익 조건'],['requiredImprovement','필수 개선 지표'],['stopRule','중단 조건'],['changeReason','목표 개정 이유'],['unconfirmedReason','미확정 사유']];
const targetDates:readonly (readonly [keyof TargetInput,string])[]=[['from','관측 시작일'],['to','관측 종료일'],['executionStartedAt','실행 착수일'],['stopAt','중단 기준일'],['confirmBy','다음 확정일']];
const reviewFields:readonly (readonly [keyof ReviewInput,string])[]=[['resources','투입 자원·비용 근거'],['questionsAndReturns','고객 질문·반품 원인'],['ownerExceptions','대표 예외 처리'],['nextAction','다음 행동'],['next30Days','다음 30일 계획']];
const metrics:Record<string,string>={netRevenue:'순매출(장부 관측)',paidOrders:'유료 주문 수',contributionProfit:'공헌이익'};
const labels:Record<string,string>=Object.fromEntries([...targetTextFields,...targetDates,...reviewFields,['status','목표 상태'],['metric','목표 지표'],['comparison','비교 방식'],['unit','단위'],['baseline','기준선'],['targetValue','목표값'],['lossLimit','최대 탐색 손실 (원)']]);
const amount=(n:number|null|undefined)=>n===null||n===undefined?'미확인':n.toLocaleString('ko-KR');
async function request(campaignId:string,init:RequestInit={},reviewId?:string):Promise<View>{
 const response=await fetch(`/api/growth/targets${init.method==='POST'?'':`?campaignId=${encodeURIComponent(campaignId)}${reviewId?`&reviewId=${encodeURIComponent(reviewId)}`:''}`}`,{...init,cache:'no-store'}),raw:unknown=await response.json();
 if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('사업목표 응답을 확인하지 못했습니다.');
 const data=raw as Record<string,unknown>;
 if(!response.ok)throw new Error(typeof data.error==='string'?data.error:'사업목표 요청에 실패했습니다.');
 if(!['targets','targetHistory','reviews','decisions'].every(key=>Array.isArray(data[key]))||typeof data.campaignVersion!=='number'||typeof data.canEdit!=='boolean')throw new Error('사업목표 응답을 확인하지 못했습니다.');
 return data as unknown as View;
}
function TargetSnapshot({target}:{target:Target}){
 return <dl>{Object.entries(target.input).map(([key,value])=><div key={key}><dt>{labels[key]??key}</dt><dd>{value===null?'미확인':key==='status'?value==='confirmed'?'확정':'잠정':key==='metric'?metrics[String(value)]:key==='comparison'?'절대값 비교':key==='unit'?value==='orders'?'주문 건':'원':String(value===''?'미기록':value)}</dd></div>)}</dl>;
}
function ReviewHistory({reviews,comparison,onCompare,busy}:{reviews:Review[];comparison?:Comparison;onCompare:(id:string)=>void;busy:boolean}){
 const statusLabels={held:'판단 보류',interim:'중간 리뷰',observed_met:'관측 목표값 이상',observed_below:'관측 목표값 미달'};
 return <section aria-label="저장된 30일 리뷰"><h4>저장된 30일 리뷰</h4>{!reviews.length&&<p>기록된 리뷰가 없습니다.</p>}{reviews.map(row=><article key={row.id} className={styles.mission}><h4>{row.snapshot.target.input.title} · 목표 v{row.targetVersion}</h4><p>{row.createdAt} · {statusLabels[row.assessment.status]}{row.assessment.status!=='interim'&&row.assessment.missing.some(reason=>reason.includes('30일 관측기간'))?' · 중간 리뷰':''}</p><p>관측값: {amount(row.assessment.observedValue)} · 기준선 대비 절대 차이: {amount(row.assessment.absoluteChange)}</p><p>마케팅비 차감 전 관측 이익: {amount(row.assessment.observedContributionBeforeMarketing)}원</p><p>저장 시점의 장부 관측입니다. 최신 정정 자료 반영은 새 리뷰로 확인하세요. 관측 목표값 비교이며 사업 성공·인과 기여·자동 확대 판정이 아닙니다. 공헌이익은 전체 비용 확인 전 판단을 보류합니다.</p>{row.currentTargetChanged&&<p className={styles.note}>현재 목표가 달라졌습니다. 이 리뷰는 당시 목표 판과 관측 자료를 유지합니다.</p>}{row.currentBusinessChanged&&<p className={styles.note}>최신 사업 자료가 달라졌습니다. 과거 리뷰를 변경하지 않고 새 리뷰로 확인하세요.</p>}<Button variant="panel" size="fit" type="button" disabled={busy} onClick={()=>onCompare(row.id)}>최신 장부와 대조</Button>{comparison?.reviewId===row.id&&<div aria-label="최신 장부 대조 결과"><p>{comparison.checkedAt} · {comparison.comparisonStatus==='unavailable'?'장부 근거가 부족해 비교를 보류합니다.':comparison.currentBusinessChanged?'최신 장부가 달라졌습니다.':'저장 당시 장부와 같습니다.'}</p>{comparison.scopeChanged&&<p>캠페인 또는 지점 범위가 달라졌습니다. 동일 범위의 증빙인지 다시 확인하세요.</p>}<p>현재 목표: {comparison.currentTargetChanged?'변경됨':'동일'}</p><p>현재 순매출(장부 관측): {amount(comparison.currentBusiness.netRevenue)}원 · 현재 유료 주문: {amount(comparison.currentBusiness.paidOrders)}건</p><p>과거 리뷰의 관측과 평가는 그대로 유지합니다.</p></div>}<ul>{row.assessment.missing.map((reason,index)=><li key={index}>{reason}</li>)}</ul><details><summary>당시 목표·리뷰 근거 보기</summary><TargetSnapshot target={row.snapshot.target}/><dl>{reviewFields.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{row.input[key]||'미기록'}</dd></div>)}</dl><p>연결 결정: {row.snapshot.decision?`${row.snapshot.decision.input.title} · v${row.snapshot.decision.version}`:'없음'}</p></details></article>)}</section>;
}
function TargetsEditor({campaignId,view,onView,busy,onBusy,onCompare}:{campaignId:string;view:View;onView:(next:View)=>void;busy:boolean;onBusy:(value:boolean)=>void;onCompare:(id:string)=>void}){
 const [draft,setDraft]=useState<TargetInput>(emptyTargetInput),[identity,setIdentity]=useState(()=>({id:crypto.randomUUID() as string,version:0}));
 const [review,setReview]=useState<ReviewInput>(emptyReviewInput),[reviewId,setReviewId]=useState(()=>crypto.randomUUID()),[targetRef,setTargetRef]=useState('');
 const [campaignVersion,setCampaignVersion]=useState(view.campaignVersion),[error,setError]=useState(''),[message,setMessage]=useState('');
 const mounted=useRef(false),pending=useRef<AbortController|null>(null),retry=useRef<{key:string;requestId:string}|null>(null);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;pending.current?.abort();};},[]);
 const selected=view.targets.find(row=>row.id===identity.id),stale=!!selected&&selected.version!==identity.version,staleCampaign=campaignVersion!==view.campaignVersion;
 const revisions=[...view.targetHistory,...view.targets].filter((row,index,all)=>all.findIndex(item=>item.id===row.id&&item.version===row.version)===index).sort((a,b)=>a.id.localeCompare(b.id)||b.version-a.version);
 const reference=view.targets.find(row=>`${row.id}:${row.version}`===targetRef),locked=busy||!view.canEdit||staleCampaign;
 function pick(row?:Target){setIdentity({id:row?.id??crypto.randomUUID(),version:row?.version??0});setDraft(row?{...row.input}:emptyTargetInput());setError('');setMessage('');retry.current=null;}
 async function mutate(action:'save_target'|'capture_review'){
  if(pending.current||busy)return;
  const payload={action,campaignId,campaignVersion,...(action==='save_target'?{id:identity.id,expectedVersion:identity.version,input:draft}:{id:reviewId,expectedVersion:0,targetId:reference?.id,targetVersion:reference?.version,input:review})};
  const key=JSON.stringify(payload),requestId=retry.current?.key===key?retry.current.requestId:crypto.randomUUID();retry.current={key,requestId};
  const c=new AbortController();pending.current=c;onBusy(true);setError('');setMessage('');
  try{
   const next=await request(campaignId,{method:'POST',headers:{'Content-Type':'application/json'},signal:c.signal,body:JSON.stringify({...payload,requestId})});
   if(!mounted.current||c.signal.aborted)return;
   if(action==='save_target'){const row=next.targets.find(item=>item.id===identity.id);if(!row)throw new Error('저장된 목표를 확인하지 못했습니다.');setIdentity({id:row.id,version:row.version});setDraft(row.input);}
   else{if(!next.reviews.some(row=>row.id===reviewId))throw new Error('저장된 리뷰를 확인하지 못했습니다.');setReviewId(crypto.randomUUID());}
   onView(next);setCampaignVersion(next.campaignVersion);retry.current=null;setMessage(action==='save_target'?'사업목표를 저장했습니다.':'30일 리뷰를 기록했습니다.');
  }catch(e){if(mounted.current&&!c.signal.aborted)setError(`${e instanceof Error?e.message:'저장하지 못했습니다.'} 입력은 보존했습니다. 응답 미확인 시 같은 입력으로 재시도하고, 충돌 시 새로고침 후 최신 판을 검토하세요.`);}
  finally{pending.current=null;if(mounted.current&&!c.signal.aborted)onBusy(false);}
 }
 return <>{error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.success}>{message}</p>}{!view.canEdit&&<p>조회 전용입니다.</p>}{staleCampaign&&<p className={styles.error}>캠페인 판이 변경되었습니다.<Button variant="panel" size="fit" type="button" disabled={busy} onClick={()=>setCampaignVersion(view.campaignVersion)}>현재 입력 유지 · 최신 캠페인 기준 사용</Button></p>}
 <div className={styles.workspace}><div role="group" aria-label="사업목표 목록" className={styles.list}><Button variant="panel" size="fit" type="button" disabled={locked} onClick={()=>pick()}>새 사업목표</Button>{view.targets.map(row=><Button variant="panel" size="fit" key={row.id} type="button" disabled={busy} aria-pressed={row.id===identity.id} onClick={()=>pick(row)}>{row.input.title||'제목 없는 목표'} · v{row.version}</Button>)}</div>
 <section aria-label="사업목표 편집" className={styles.editor}><h4>{identity.version?`사업목표 편집 · v${identity.version}`:'새 사업목표'}</h4>{stale&&<div className={styles.error}>서버 목표가 v{selected.version}로 변경되었습니다.<details><summary>최신 목표 보기</summary><TargetSnapshot target={selected}/></details><Button variant="panel" size="fit" type="button" disabled={locked} onClick={()=>setIdentity({id:selected.id,version:selected.version})}>현재 입력 유지 · 최신 목표 버전 사용</Button><Button variant="panel" size="fit" type="button" disabled={busy} onClick={()=>pick(selected)}>서버 목표로 입력 교체</Button></div>}
 <form onSubmit={event=>{event.preventDefault();void mutate('save_target');}}><fieldset className={styles.form} disabled={locked||stale}><legend className={styles.srOnly}>사업목표 입력</legend>
 <label className={styles.field}>목표 상태<NativeSelect value={draft.status} onChange={event=>setDraft(previous=>({...previous,status:event.target.value as TargetInput['status']}))}><option value="provisional">잠정</option><option value="confirmed">확정</option></NativeSelect></label>
 <label className={styles.field}>목표 지표<NativeSelect value={draft.metric} onChange={event=>setDraft(previous=>({...previous,metric:event.target.value as TargetInput['metric'],unit:event.target.value==='paidOrders'?'orders':'KRW'}))}>{Object.entries(metrics).map(([id,label])=><option key={id} value={id}>{label}</option>)}</NativeSelect></label><p className={styles.wide}>주문 장부에서 관측한 값이며 실제 정산·실현 여부의 대사 완료를 뜻하지 않습니다. 절대값으로 비교합니다. 단위: {draft.unit==='orders'?'주문 건':'원'}. 기준선 0에서 성장률을 계산하지 않습니다.</p>
 {targetTextFields.map(([key,label])=><label className={styles.wide} key={key}>{label}<Textarea rows={key==='title'?1:2} maxLength={1000} value={String(draft[key]??'')} onChange={event=>setDraft(previous=>({...previous,[key]:event.target.value}))}/></label>)}
 {targetDates.map(([key,label])=><label className={styles.field} key={key}>{label}<Input type="date" value={String(draft[key]??'')} onChange={event=>setDraft(previous=>({...previous,[key]:event.target.value}))}/></label>)}
 {([['baseline','기준선'],['targetValue','목표값'],['lossLimit','최대 탐색 손실 (원)']] as const).map(([key,label])=><label className={styles.field} key={key}>{label}<Input type="number" step={1} min={key==='lossLimit'||draft.metric!=='contributionProfit'?0:undefined} value={draft[key]??''} onChange={event=>setDraft(previous=>({...previous,[key]:event.target.value===''?null:Number(event.target.value)}))}/></label>)}<Button variant="panel" size="fit" type="submit">사업목표 저장</Button></fieldset></form>
 {selected?.assessment&&<div className={styles.readiness}><strong>저장된 목표의 보완 조건</strong><ul>{selected.assessment.missing.map((reason,index)=><li key={index}>{reason}</li>)}</ul></div>}
 {selected&&<details><summary>목표 개정 이력</summary>{revisions.filter(row=>row.id===selected.id).map(row=><article key={`${row.id}:${row.version}`} className={styles.mission}><h4>v{row.version} · {row.input.title}</h4><TargetSnapshot target={row}/></article>)}</details>}</section></div>
 <section aria-label="30일 리뷰 작성"><h4>30일 리뷰 작성</h4><Button variant="panel" size="fit" type="button" disabled={locked} onClick={()=>{setReview(emptyReviewInput());setTargetRef('');setReviewId(crypto.randomUUID());retry.current=null;}}>새 리뷰 작성</Button><Note className={styles.note}>목표의 정확한 판과 현재 서버 관측을 함께 고정합니다. 종료 전 리뷰는 중간 리뷰이며, 목표 미정·비용 미확인은 판단을 보류합니다. 기록한 리뷰는 수정하지 않습니다.</Note><form onSubmit={event=>{event.preventDefault();void mutate('capture_review');}}><fieldset disabled={locked} className={styles.form}><legend className={styles.srOnly}>리뷰 입력</legend><label className={styles.wide}>리뷰할 목표 판<NativeSelect required value={targetRef} onChange={event=>{setTargetRef(event.target.value);setReview(emptyReviewInput());setReviewId(crypto.randomUUID());}}><option value="">정확한 목표 판 선택</option>{targetRef&&!reference&&<option value={targetRef}>이전 선택 · 목표 판 변경됨</option>}{view.targets.map(row=><option key={`${row.id}:${row.version}`} value={`${row.id}:${row.version}`}>{row.input.title} · v{row.version}</option>)}</NativeSelect></label>
 {reviewFields.map(([key,label])=><label key={key} className={styles.wide}>{label}<Textarea rows={2} maxLength={1500} value={String(review[key]??'')} onChange={event=>setReview(previous=>({...previous,[key]:event.target.value}))}/></label>)}
 <label className={styles.wide}>연결 일일 결정<NativeSelect value={review.decisionId} onChange={event=>setReview(previous=>({...previous,decisionId:event.target.value,decisionVersion:view.decisions.find(row=>row.id===event.target.value)?.version??0}))}><option value="">연결 없음</option>{review.decisionId&&!view.decisions.some(row=>row.id===review.decisionId)&&<option value={review.decisionId}>이전 연결 · 현재 없음</option>}{view.decisions.map(row=><option key={row.id} value={row.id}>{row.input.title} · v{row.version}</option>)}</NativeSelect></label>{review.decisionId&&<p>선택한 결정 판: v{review.decisionVersion}{view.decisions.some(row=>row.id===review.decisionId&&row.version!==review.decisionVersion)&&<Button variant="panel" size="fit" type="button" onClick={()=>setReview(previous=>({...previous,decisionVersion:view.decisions.find(row=>row.id===previous.decisionId)?.version??previous.decisionVersion}))}>최신 결정 판 연결</Button>}</p>}<Button variant="panel" size="fit" type="submit" disabled={!reference}>30일 리뷰 기록</Button></fieldset></form></section><ReviewHistory reviews={view.reviews} comparison={view.reviewComparison} onCompare={onCompare} busy={busy}/>
 </>;
}
export function GrowthTargetsPanel({campaignId}:{campaignId:string}){
 const [view,setView]=useState<View|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');const read=useRef<AbortController|null>(null);
 const load=useCallback(async(signal:AbortSignal,reviewId?:string)=>{setLoading(true);setError('');try{const next=await request(campaignId,{signal},reviewId);if(!signal.aborted)setView(next);}catch(e){if(!signal.aborted)setError(e instanceof Error?e.message:'목표를 불러오지 못했습니다.');}finally{if(!signal.aborted)setLoading(false);}},[campaignId]);
 useEffect(()=>{const c=new AbortController();read.current=c;void Promise.resolve().then(()=>{if(!c.signal.aborted)void load(c.signal);});return()=>read.current?.abort();},[load]);
 function reload(){read.current?.abort();const c=new AbortController();read.current=c;void load(c.signal);}
 return <section aria-label="사업목표·30일 리뷰" className={styles.panel}><header className={styles.header}><div><h3>사업목표·30일 리뷰</h3><p>첫 잠정 목표와 기준선 이후 개정을 남기고 당시의 관측·다음 행동을 함께 기록합니다.</p></div><Button variant="panel" size="fit" aria-label="목표·리뷰 새로고침" type="button" disabled={loading||busy} onClick={reload}>새로고침</Button></header><Note className={styles.note}>금액·기준선의 빈칸은 미확인, 0은 명시한 값입니다. 담당자는 역할로, 증빙은 개인정보 없는 내부 참조로 기록하세요. 목표 확정과 관측값 도달만으로 실행·확대 권한이 생기지 않습니다.</Note>{loading&&<ScreenSkeleton label="목표·리뷰를 불러오고 있습니다." rows={2}/>}{error&&<p role="alert" className={styles.error}>{error}</p>}{view&&<TargetsEditor key={campaignId} campaignId={campaignId} view={view} onView={next=>{read.current?.abort();setLoading(false);setView(next);}} busy={busy} onCompare={id=>{read.current?.abort();const c=new AbortController();read.current=c;void load(c.signal,id);}} onBusy={value=>{if(value){read.current?.abort();setLoading(false);}setBusy(value);}}/>}</section>;
}
