'use client';

import {NativeSelect} from '@/components/ui/native-select';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {whyDisabled} from '@/lib/ui/why-disabled';
import {Note} from '@/components/app/note';
import {useCallback,useEffect,useRef,useState} from 'react';
import styles from './growth-panel.module.css';
import {MetaLine} from '@/components/app/meta-line';
import {metaText} from '@/lib/format';
import type {GrowthSignalSourceView} from '@/lib/growth-signal-source-server';

type View=GrowthSignalSourceView;
type Selection={sourceId:string;sourceVersion:number;campaignVersion:number};
async function read(campaignId:string,signal:AbortSignal):Promise<View>{const response=await fetch(`/api/growth/signal-sources?campaignId=${encodeURIComponent(campaignId)}`,{cache:'no-store',signal}),raw:unknown=await response.json();if(!response.ok)throw new Error('자료 목록을 불러오지 못했습니다. 접근 권한을 확인한 뒤 다시 조회하세요.');if(!raw||typeof raw!=='object'||!Array.isArray((raw as View).candidates)||typeof (raw as View).campaignVersion!=='number')throw new Error('자료 목록 응답을 확인하지 못했습니다.');return raw as View}
export function GrowthSignalSourcePanel({campaignId,onImported}:{campaignId:string;onImported:()=>void}){
 const [view,setView]=useState<View|null>(null),[selection,setSelection]=useState<Selection>({sourceId:'',sourceVersion:0,campaignVersion:0}),[expiresAt,setExpiresAt]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[savedIds,setSavedIds]=useState<string[]>([]);
 const reading=useRef<AbortController|null>(null),writing=useRef<AbortController|null>(null),retry=useRef<{key:string;id:string}|null>(null),mounted=useRef(false);
 const load=useCallback(async()=>{reading.current?.abort();const controller=new AbortController();reading.current=controller;setLoading(true);setError('');try{const next=await read(campaignId,controller.signal);if(!controller.signal.aborted)setView(next);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'자료 목록을 불러오지 못했습니다.');}finally{if(!controller.signal.aborted)setLoading(false);}},[campaignId]);
 useEffect(()=>{mounted.current=true;void Promise.resolve().then(()=>{if(mounted.current)void load();});return()=>{mounted.current=false;reading.current?.abort();writing.current?.abort();};},[load]);
 const selected=view?.candidates.find(row=>row.sourceId===selection.sourceId),imported=!!selected?.importedSignalId||savedIds.includes(`${selection.sourceId}:${selection.sourceVersion}`),staleSource=!!selection.sourceId&&selected?.sourceVersion!==selection.sourceVersion,staleCampaign=!!selection.sourceId&&view?.campaignVersion!==selection.campaignVersion,busy=loading||saving;
 function choose(sourceId:string){setSelection({sourceId,sourceVersion:view?.candidates.find(row=>row.sourceId===sourceId)?.sourceVersion??0,campaignVersion:view?.campaignVersion??0});setExpiresAt('');setError('');setMessage('');retry.current=null;}
 async function submit(){
  if(writing.current||busy||!view?.canImport||!selected||selected.status!=='ready'||imported||staleSource||staleCampaign||!expiresAt)return;
  const payload={campaignId,...selection,expiresAt},key=JSON.stringify(payload),requestId=retry.current?.key===key?retry.current.id:crypto.randomUUID();retry.current={key,id:requestId};const controller=new AbortController();writing.current=controller;reading.current?.abort();setSaving(true);setError('');setMessage('');
  try{const response=await fetch('/api/growth/signal-sources',{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,requestId})}),raw:unknown=await response.json();if(!response.ok)throw new Error(response.status===409?'자료 또는 캠페인 판이 변경됐거나 가져오기 조건이 달라졌습니다. 목록을 새로고침해 확인하세요.':'시장 근거를 가져오지 못했습니다. 자료와 유효기한을 확인하세요.');if(!raw||typeof raw!=='object'||(raw as {imported?:unknown}).imported!==true||typeof (raw as {signalId?:unknown}).signalId!=='string')throw new Error('가져오기 결과를 확인하지 못했습니다.');if(!mounted.current||controller.signal.aborted)return;retry.current=null;setSavedIds(previous=>[...new Set([...previous,`${selection.sourceId}:${selection.sourceVersion}`])]);setMessage('시장 근거를 가져왔습니다. 성장 기록 목록에서 확인하세요.');onImported();void load();}
  catch(e){if(mounted.current&&!controller.signal.aborted)setError(`${e instanceof Error?e.message:'가져오지 못했습니다.'} 입력은 보존했습니다. 응답 미확인은 같은 입력으로 재시도하세요.`);}
  finally{writing.current=null;if(mounted.current&&!controller.signal.aborted)setSaving(false);}
 }
 return <section className={styles.panel} aria-label="확정 시장자료 가져오기"><header className={styles.header}><h3>확정 시장자료 가져오기</h3><Button variant="panel" size="fit" aria-label="자료 목록 새로고침" type="button" disabled={busy} onClick={()=>void load()}>새로고침</Button></header><Note className={styles.note}>브랜드 아카이브에서 확정한 공개 시장 자료를 현재 캠페인의 근거로 가져오기만 합니다. 가져온 자료는 수요 검증이나 매출 증명이 아니며 표본 수는 미확인으로 유지합니다.</Note>{loading&&<p role="status">자료 목록을 확인하고 있습니다.</p>}{error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.success}>{message}</p>}
 {view&&<><form onSubmit={event=>{event.preventDefault();void submit();}}><fieldset disabled={busy} className={styles.form}><legend>확정 자료와 유효기한</legend><label className={styles.wide}>브랜드 아카이브 자료 선택<NativeSelect value={selection.sourceId} onChange={event=>choose(event.target.value)}><option value="">자료 선택</option>{selection.sourceId&&!selected&&<option value={selection.sourceId}>이전 선택(현재 조회 불가)</option>}{view.candidates.map(row=><option key={row.sourceId} value={row.sourceId}>{metaText([`${row.title} v${row.sourceVersion}`,row.importedSignalId?'가져옴':row.status==='ready'?'가져오기 가능':'보류'])}</option>)}</NativeSelect></label>
 {selected&&<div className={styles.wide}><h4>{selected.title}</h4><p><MetaLine items={[`공개 출처: ${selected.sourceUrl||'미확인'}`,`관측 시각: ${selected.observedAt||'미확인'}`]}/></p>{selected.signalPreview&&<><p className="whitespace-pre-wrap">가져올 관측 요약: {selected.signalPreview.summary}</p><p>검사에 통과한 저장 내용을 발췌·보강 없이 그대로 씁니다.</p></>}{!!selected.reasons.length&&<ul>{selected.reasons.map((reason,index)=><li key={index}>{reason}</li>)}</ul>}{imported&&<p>이미 가져온 자료입니다. 중복으로 가져오지 않습니다.</p>}</div>}
 {staleSource&&<div className={styles.error}>자료 판이 달라졌습니다. 최신 내용을 확인한 뒤 기준을 다시 선택하세요.{selected&&<Button variant="panel" size="fit" type="button" onClick={()=>{setSelection(previous=>({...previous,sourceVersion:selected.sourceVersion}));setError('');}}>현재 기한을 유지하고 최신 자료 판 사용</Button>}</div>}{staleCampaign&&<div className={styles.error}>캠페인 판이 달라졌습니다.<Button variant="panel" size="fit" type="button" onClick={()=>{setSelection(previous=>({...previous,campaignVersion:view.campaignVersion}));setError('');}}>현재 기한을 유지하고 최신 캠페인 판 사용</Button></div>}
 <label>가져올 근거 유효기한<Input type="date" required value={expiresAt} onChange={event=>setExpiresAt(event.target.value)}/></label>{(()=>{const why=whyDisabled([[!selected,'가져올 브랜드 아카이브 자료를 먼저 고르세요.'],[!!selected&&selected.status!=='ready','선택한 자료는 위 사유 때문에 아직 가져올 수 없습니다.'],[imported,'이미 가져온 자료입니다.'],[staleSource||staleCampaign,'판이 달라졌습니다. 위 안내대로 기준을 다시 고르세요.'],[!expiresAt,'가져올 근거 유효기한을 입력하세요.']]);return <><Button variant="panel" size="fit" type="submit" disabled={!view.canImport||!!why} disabledReason={!view.canImport?'가져올 권한이 없습니다.':why?why:undefined}>시장 근거로 가져오기</Button></>})()}</fieldset></form>{!view.candidates.length&&<p>이 캠페인 범위에서 조회할 시장 자료가 없습니다. 브랜드 아카이브에서 공개 출처와 내용을 확인하세요.</p>}{!view.canImport&&<p>현재 권한·캠페인 상태에서는 자료를 가져올 수 없습니다.</p>}</>}
 </section>;
}
