'use client';

import {NativeSelect} from '@/components/ui/native-select';
import {Textarea} from '@/components/ui/textarea';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {fromLocalInput,toLocalInput} from '@/lib/format';
import {Note} from '@/components/app/note';
import {useCallback,useEffect,useRef,useState} from 'react';
import {emptyReorderInput,type ReorderInput,type ReorderAssessment} from '@/lib/growth-reorder';
import type {CandidateInput,SourcingInventory} from '@/lib/growth-sourcing';
import type {CatalogInput} from '@/lib/growth-catalog';
import styles from './growth-panel.module.css';
import {ScreenSkeleton} from '@/components/app/screen-skeleton';

type Catalog={id:string;version:number;input:CatalogInput};
type Candidate={id:string;version:number;input:CandidateInput};
type Review={id:string;input:ReorderInput;snapshot:{catalog:Catalog;candidate:Candidate;inventory:SourcingInventory};assessment:ReorderAssessment;createdAt:string;currentChanged:boolean};
type View={catalogs:Catalog[];candidates:Candidate[];reviews:Review[];campaignVersion:number;canEdit:boolean;mayOrder:false};
const amount=(value:number|null|undefined)=>value===null||value===undefined?'미확인':value.toLocaleString('ko-KR');
const units:Record<string,string>={piece:'개',pack:'팩',unknown:'미확인'};
const tax:Record<string,string>={included:'세금 포함',excluded:'세금 별도',unknown:'세금 미확인'};
const budgets={not_configured:'한도 미설정',unknown:'한도 대조 미확인',within:'입력한 비용 한도 이내',exceeded:'입력한 비용 한도 초과'};
async function request(campaignId:string,init:RequestInit={}):Promise<View>{
 const response=await fetch(`/api/growth/reorder${init.method==='POST'?'':`?campaignId=${encodeURIComponent(campaignId)}`}`,{...init,cache:'no-store'}),raw:unknown=await response.json();
 if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('재발주 검토 응답을 확인하지 못했습니다.');
 const data=raw as Record<string,unknown>;
 if(!response.ok)throw new Error(typeof data.error==='string'?data.error:'재발주 검토 요청에 실패했습니다.');
 if(!['catalogs','candidates','reviews'].every(key=>Array.isArray(data[key]))||typeof data.campaignVersion!=='number'||typeof data.canEdit!=='boolean')throw new Error('재발주 검토 응답을 확인하지 못했습니다.');
 return data as unknown as View;
}
function Quote({candidate}:{candidate:Candidate}){const q=candidate.input;return <dl><div><dt>공급 후보·견적 판</dt><dd>{q.supplierCode} · v{candidate.version} · 상품 v{q.catalogVersion}</dd></div><div><dt>단위원가·수량 단위</dt><dd>{amount(q.unitCost)}원 / {units[q.unit]} · {tax[q.taxBasis]}</dd></div><div><dt>최소 주문 수량·납기</dt><dd>{amount(q.moq)}{units[q.unit]} · {amount(q.leadDays)}일</dd></div><div><dt>고정 배송비·부대비</dt><dd>{amount(q.shippingCost)}원 · {amount(q.extraCost)}원</dd></div><div><dt>견적 유효기한·증빙</dt><dd>{q.validUntil||'미확인'} · {q.evidenceRef||'미확인'}</dd></div></dl>}
function History({reviews}:{reviews:Review[]}){return <section aria-label="저장된 재발주 검토"><h4>저장된 재발주 검토</h4>{!reviews.length&&<p>저장된 검토가 없습니다.</p>}{reviews.map(row=>{const a=row.assessment,input=row.input,stock=row.snapshot.inventory;return <article key={row.id} className={styles.mission}><h4>{row.snapshot.catalog.input.title||row.snapshot.catalog.input.sku} · {a.status==='held'?'판단 보류':'가정 검토 가능'}</h4><p>{row.createdAt} · 상품 v{input.catalogVersion} · 견적 v{input.candidateVersion} · 자동 발주 권한 없음</p>{row.currentChanged&&<p className={styles.note}>현재 근거 또는 유효 조건이 달라졌습니다. 저장 당시 검토는 변경하지 않습니다. 새 검토로 재확인하세요.</p>}<p>{a.notice}</p><dl><div><dt>운영자 수요 가정</dt><dd>{input.demand.from} ~ {input.demand.to} · {amount(input.demand.quantity)}{units[input.unit]} / {amount(a.observedDays)}일</dd></div><div><dt>일평균 수요 가정 · 실제 판매속도 아님</dt><dd>{amount(a.demandPerDay)}{units[input.unit]}/일</dd></div><div><dt>원장 보유·예약·가용·부족</dt><dd>{amount(stock.onHand)} · {amount(stock.reserved)} · {amount(stock.available)} · {amount(stock.shortage)} {units[stock.unit]}</dd></div><div><dt>원장 보유에서 예약을 뺀 수량</dt><dd>{amount(a.rawStock)}{units[input.unit]} · 음수는 예약 부족분 포함</dd></div><div><dt>가정 재발주점 · 목표 보유 수량</dt><dd>{amount(a.reorderPoint)} · {amount(a.targetQuantity)} {units[input.unit]}</dd></div><div><dt>가정 필요 수량 · MOQ 반영 구매 검토 수량</dt><dd>{amount(a.neededQuantity)} · {amount(a.purchaseQuantity)} {units[input.unit]}</dd></div><div><dt>가정상 다음 검토까지</dt><dd>{amount(a.daysUntilReorder)}일 · 확정 발주일 아님</dd></div><div><dt>견적 소계 · 세금 포함 구매비 추정</dt><dd>{amount(a.quoteSubtotal)}원 · {amount(a.cashNeed)}원</dd></div><div><dt>입력한 구매 비용 한도 대조</dt><dd>{amount(input.purchaseBudget)}원 · {budgets[a.budgetAssessment]}</dd></div></dl><p>{stock.reason}</p><p>계산값이 있어도 보류 사유가 남으면 발주 판단 근거가 완성된 것이 아닙니다. 필요 수량 0에는 MOQ·고정비를 적용하지 않습니다. 세금 별도 견적의 세금 포함 구매비는 수량이 0인 경우 외에는 미확인입니다.</p>{a.missing.length>0&&<ul>{a.missing.map((reason,index)=><li key={index}>{reason}</li>)}</ul>}<details><summary>검토 당시 견적·가정·증빙</summary><Quote candidate={row.snapshot.candidate}/><dl><div><dt>추가 확보 기간·안전 수량</dt><dd>{amount(input.coverageDays)}일 · {amount(input.safetyQuantity)}{units[input.unit]}</dd></div><div><dt>수요 가정 증빙</dt><dd>{input.demand.evidenceRef||'미확인'}</dd></div><div><dt>미입고 발주 확인</dt><dd>{input.outstanding.state==='confirmed_none'?'운영자가 없음 확인':'미확인'} · {input.outstanding.observedAt||'시각 미확인'} · {input.outstanding.evidenceRef||'증빙 미확인'}</dd></div><div><dt>비용 한도 근거</dt><dd>{input.budgetEvidenceRef||'미확인'}</dd></div><div><dt>재고 원장 판</dt><dd>{stock.items.map(item=>`${item.id} v${item.version}`).join(', ')||'미확인'}</dd></div><div><dt>검토 메모</dt><dd>{input.note||'미기록'}</dd></div></dl></details></article>})}</section>}
function Editor({campaignId,view,busy,onBusy,onView}:{campaignId:string;view:View;busy:boolean;onBusy:(v:boolean)=>void;onView:(v:View)=>void}){
 const [draft,setDraft]=useState(emptyReorderInput),[basis,setBasis]=useState(view.campaignVersion),[id,setId]=useState(()=>crypto.randomUUID()),[error,setError]=useState(''),[message,setMessage]=useState('');
 const mounted=useRef(false),write=useRef<AbortController|null>(null),retry=useRef<{key:string;id:string}|null>(null);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;write.current?.abort();};},[]);
 const catalog=view.catalogs.find(row=>row.id===draft.catalogId),candidate=view.candidates.find(row=>row.id===draft.candidateId),catalogStale=!!draft.catalogId&&catalog?.version!==draft.catalogVersion,candidateStale=!!draft.candidateId&&(!candidate||candidate.version!==draft.candidateVersion||candidate.input.catalogId!==draft.catalogId||candidate.input.catalogVersion!==draft.catalogVersion),campaignStale=basis!==view.campaignVersion;
 const candidates=view.candidates.filter(row=>row.input.catalogId===draft.catalogId&&row.input.catalogVersion===draft.catalogVersion),locked=busy||!view.canEdit;
 function reset(){setDraft(emptyReorderInput());setId(crypto.randomUUID());setBasis(view.campaignVersion);setError('');setMessage('');retry.current=null;}
 function selectCatalog(value:string){const [catalogId,version]=value.split(':');setDraft(previous=>({...(previous.catalogId&&previous.catalogId===catalogId?previous:emptyReorderInput()),catalogId,catalogVersion:Number(version)||0}));setError('');setMessage('');}
 function selectCandidate(value:string){const [candidateId,version]=value.split(':');setDraft(previous=>({...(previous.candidateId===candidateId?previous:{...emptyReorderInput(),catalogId:previous.catalogId,catalogVersion:previous.catalogVersion,unit:previous.unit}),candidateId,candidateVersion:Number(version)||0}));setError('');setMessage('');}
 async function save(){
  if(write.current||locked||campaignStale||catalogStale||candidateStale)return;const payload={action:'capture_review',id,expectedVersion:0,campaignId,campaignVersion:basis,input:draft},key=JSON.stringify(payload),requestId=retry.current?.key===key?retry.current.id:crypto.randomUUID();retry.current={key,id:requestId};const c=new AbortController();write.current=c;onBusy(true);setError('');setMessage('');
  try{const next=await request(campaignId,{method:'POST',headers:{'Content-Type':'application/json'},signal:c.signal,body:JSON.stringify({...payload,requestId})});if(!mounted.current||c.signal.aborted)return;onView(next);setBasis(next.campaignVersion);setId(crypto.randomUUID());retry.current=null;setMessage('재발주 검토를 기록했습니다. 입력 근거의 판을 고정했으며 발주를 실행하지 않았습니다.');}
  catch(e){if(mounted.current&&!c.signal.aborted)setError(`${e instanceof Error?e.message:'기록하지 못했습니다.'} 입력은 보존했습니다. 응답 미확인은 동일 입력으로 재시도하고, 충돌은 새로고침 후 최신 판을 검토하세요.`);}
  finally{write.current=null;if(mounted.current&&!c.signal.aborted)onBusy(false);}
 }
 return <>{error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.success}>{message}</p>}{!view.canEdit&&<p className={styles.note}>조회 전용입니다. 관리자 권한과 캠페인 상태에 따라 기록할 수 있습니다.</p>}<section aria-label="재발주 검토 작성"><header className={styles.header}><h4>재발주 검토 작성</h4><Button variant="panel" size="fit" type="button" disabled={locked} onClick={reset}>새 재발주 검토</Button></header>
 {campaignStale&&<div className={styles.error}>캠페인 판이 바뀌었습니다.<Button variant="panel" size="fit" type="button" disabled={locked} onClick={()=>{setBasis(view.campaignVersion);setError('');}}>현재 입력 유지 · 최신 캠페인 판 사용</Button></div>}{catalogStale&&<div className={styles.error}>상품 판이 바뀌었거나 더 이상 조회되지 않습니다.{catalog&&<><p>{catalog.input.title} · {catalog.input.sku} · v{catalog.version} · {tax[catalog.input.taxBasis]} · 유효 {catalog.input.validUntil||'미확인'}</p><Button variant="panel" size="fit" type="button" disabled={locked} onClick={()=>{setDraft(previous=>({...previous,catalogVersion:catalog.version}));setError('');}}>현재 입력 유지 · 최신 상품 판 사용</Button></>}</div>}{candidateStale&&<div className={styles.error}>후보 판 또는 연결 상품 판이 바뀌었습니다.{candidate&&<details><summary>최신 후보 견적 확인</summary><Quote candidate={candidate}/></details>}{candidate&&candidate.input.catalogId===draft.catalogId&&candidate.input.catalogVersion===draft.catalogVersion&&<Button variant="panel" size="fit" type="button" disabled={locked} onClick={()=>{setDraft(previous=>({...previous,candidateVersion:candidate.version}));setError('');}}>현재 입력 유지 · 최신 후보 판 사용</Button>}</div>}
 <form onSubmit={event=>{event.preventDefault();void save();}}><fieldset disabled={locked} className={styles.form}><legend className={styles.srOnly}>재발주 검토 입력</legend><label className={styles.wide}>검토 상품 판<NativeSelect required value={draft.catalogId?`${draft.catalogId}:${draft.catalogVersion}`:''} onChange={event=>selectCatalog(event.target.value)}><option value="">상품 선택</option>{catalogStale&&<option value={`${draft.catalogId}:${draft.catalogVersion}`}>이전 상품 판 · 재확인 필요</option>}{view.catalogs.map(row=><option key={row.id} value={`${row.id}:${row.version}`}>{row.input.title||row.input.sku} · {row.input.sku} · v{row.version}</option>)}</NativeSelect></label><label className={styles.wide}>소싱 후보 판<NativeSelect required value={draft.candidateId?`${draft.candidateId}:${draft.candidateVersion}`:''} onChange={event=>selectCandidate(event.target.value)}><option value="">후보 선택</option>{candidateStale&&<option value={`${draft.candidateId}:${draft.candidateVersion}`}>이전 후보 판 · 재확인 필요</option>}{candidates.map(row=><option key={row.id} value={`${row.id}:${row.version}`}>{row.input.supplierCode} · v{row.version} · {units[row.input.unit]}</option>)}</NativeSelect></label><label>검토 수량 단위<NativeSelect value={draft.unit} onChange={event=>setDraft(previous=>({...previous,unit:event.target.value as ReorderInput['unit'],demand:{...previous.demand,quantity:null,evidenceRef:''},safetyQuantity:null}))}><option value="piece">개</option><option value="pack">팩</option></NativeSelect></label>
 <fieldset className={styles.references}><legend>운영자 수요 가정</legend><p>판매 주문 집계가 아닙니다. 시작일·종료일을 모두 포함한 기간의 수량을 입력하세요. 한국시간 오늘까지의 기간만 기록합니다.</p>{([['from','수요 가정 시작일'],['to','수요 가정 종료일']]as const).map(([key,label])=><label key={key}>{label}<Input required type="date" value={draft.demand[key]} onChange={event=>setDraft(previous=>({...previous,demand:{...previous.demand,[key]:event.target.value}}))}/></label>)}<label>기간 내 수요 가정 수량<Input type="number" min={0} step={1} value={draft.demand.quantity??''} onChange={event=>setDraft(previous=>({...previous,demand:{...previous.demand,quantity:event.target.value===''?null:Number(event.target.value)}}))}/></label><label>수요 가정 증빙 참조<Input maxLength={160} value={draft.demand.evidenceRef} onChange={event=>setDraft(previous=>({...previous,demand:{...previous.demand,evidenceRef:event.target.value}}))}/></label></fieldset>
 {([['coverageDays','확보 기간 (일)'],['safetyQuantity','안전 수량']]as const).map(([key,label])=><label key={key}>{label}<Input type="number" min={0} step={1} value={draft[key]??''} onChange={event=>setDraft(previous=>({...previous,[key]:event.target.value===''?null:Number(event.target.value)}))}/></label>)}<p className={styles.note}>확보 기간은 후보 납기 이후 추가로 확보할 기간입니다. 최소 주문 수량은 주문 배수 조건을 뜻하지 않습니다.</p>
 <fieldset className={styles.references}><legend>미입고 발주 확인 근거</legend><p>한국시간 당일에 확인한 근거가 필요합니다. 외부 발주 시스템을 자동 조회하지 않습니다. 미입고 발주가 있거나 확인하지 못했다면 미확인으로 두세요.</p><label>미입고 발주 확인<NativeSelect value={draft.outstanding.state} onChange={event=>setDraft(previous=>({...previous,outstanding:{state:event.target.value as ReorderInput['outstanding']['state'],observedAt:null,evidenceRef:''}}))}><option value="unknown">미확인·발주 있음 포함</option><option value="confirmed_none">운영자가 미입고 발주 없음 확인</option></NativeSelect></label><label>미입고 발주 확인 시각(서울 시간)<Input type="datetime-local" value={toLocalInput(draft.outstanding.observedAt)} onChange={event=>setDraft(previous=>({...previous,outstanding:{...previous.outstanding,observedAt:fromLocalInput(event.target.value)||null}}))}/></label><label>미입고 발주 확인 증빙<Input maxLength={160} value={draft.outstanding.evidenceRef} onChange={event=>setDraft(previous=>({...previous,outstanding:{...previous.outstanding,evidenceRef:event.target.value}}))}/></label></fieldset>
 <label>구매 비용 한도 (원)<Input type="number" min={0} step={1} value={draft.purchaseBudget??''} onChange={event=>setDraft(previous=>({...previous,purchaseBudget:event.target.value===''?null:Number(event.target.value)}))}/></label><label>비용 한도 근거<Input maxLength={160} value={draft.budgetEvidenceRef} onChange={event=>setDraft(previous=>({...previous,budgetEvidenceRef:event.target.value}))}/></label><label className={styles.wide}>재발주 검토 메모<Textarea rows={2} maxLength={1000} value={draft.note} onChange={event=>setDraft(previous=>({...previous,note:event.target.value}))}/></label><Button variant="panel" size="fit" type="submit" disabled={!draft.catalogId||!draft.candidateId||catalogStale||candidateStale||campaignStale}>재발주 검토 기록</Button></fieldset></form></section><History reviews={view.reviews}/></>;
}
export function GrowthReorderPanel({campaignId}:{campaignId:string}){
 const [view,setView]=useState<View|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');const read=useRef<AbortController|null>(null);
 const load=useCallback(async(signal:AbortSignal)=>{setLoading(true);setError('');try{const next=await request(campaignId,{signal});if(!signal.aborted)setView(next);}catch(e){if(!signal.aborted)setError(e instanceof Error?e.message:'재발주 검토를 조회하지 못했습니다.');}finally{if(!signal.aborted)setLoading(false);}},[campaignId]);
 useEffect(()=>{const c=new AbortController();read.current=c;void Promise.resolve().then(()=>{if(!c.signal.aborted)void load(c.signal);});return()=>read.current?.abort();},[load]);
 function reload(){read.current?.abort();const c=new AbortController();read.current=c;void load(c.signal);}
 return <section aria-label="재발주 검토" className={styles.panel}><header className={styles.header}><div><h3>재발주 검토</h3><p>수요 가정·소싱 견적·현재 재고 원장을 고정해 구매 필요 수량을 검토합니다.</p></div><Button variant="panel" size="fit" aria-label="재발주 기록 새로고침" type="button" disabled={busy||loading} onClick={reload}>새로고침</Button></header><Note className={styles.note}>빈 수량·금액은 미확인, 0은 확인한 값입니다. 수요 입력은 운영자 가정이며 실제 판매속도가 아닙니다. 구매 비용 한도는 현금 잔고가 아니며, 견적 기준 구매비는 지급 확정액이 아닙니다. 이 기록으로 실제 발주·입고·현금 이동을 실행하지 않습니다. 자동 발주 권한 없음.</Note>{loading&&<ScreenSkeleton label="재발주 검토를 불러오고 있습니다." rows={2}/>}{error&&<p role="alert" className={styles.error}>{error}</p>}{view&&<Editor key={campaignId} campaignId={campaignId} view={view} busy={busy||loading} onView={next=>{read.current?.abort();setLoading(false);setView(next);}} onBusy={value=>{if(value){read.current?.abort();setLoading(false);}setBusy(value);}}/>}</section>;
}
