'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import {metaText} from '@/lib/format';
import {MetaLine} from '@/components/app/meta-line';
import {CheckInput} from '@/components/app/check';
import type {GrowthBundleFulfillmentView} from '@/lib/growth-bundle-fulfillment-server';
import type {GrowthBundleView} from '@/lib/growth-bundle-server';
import styles from './growth-panel.module.css';
type Mode='prepare_bundle_mission'|'link_bundle_order'|'record_bundle_operation'|'reconcile_bundle_mission';
const labels:Record<Mode,string>={prepare_bundle_mission:'미션·예산·전체 재고 준비',link_bundle_order:'실주문 구성품 배정·금액 대사',record_bundle_operation:'출고·부분 반품 증빙',reconcile_bundle_mission:'예산 실비·미집행 해제 대사'};
export function GrowthBundleFulfillmentPanel({campaignId,campaignVersion,bundles,onChanged}:{campaignId:string;campaignVersion:number;bundles:GrowthBundleView['bundles'];onChanged:()=>Promise<void>}){
 const [view,setView]=useState<GrowthBundleFulfillmentView|null>(null),[mode,setMode]=useState<Mode>('prepare_bundle_mission'),[form,setForm]=useState<Record<string,string>>({}),[money,setMoney]=useState<Record<string,{paid:string;refund:string}>>({}),[checks,setChecks]=useState<Record<string,boolean>>({}),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const mounted=useRef(true),writing=useRef<AbortController|null>(null),reading=useRef<AbortController|null>(null),retry=useRef<{key:string;requestId:string}|null>(null),draftId=useRef('');
 const load=useCallback(async()=>{reading.current?.abort();const controller=new AbortController();reading.current=controller;setLoading(true);try{const r=await fetch(`/api/growth/bundle-fulfillment?campaignId=${encodeURIComponent(campaignId)}`,{cache:'no-store',signal:controller.signal}),v=await r.json() as GrowthBundleFulfillmentView&{error?:string};if(!r.ok)throw new Error(v.error??'이행 기록 조회 실패');if(mounted.current&&!controller.signal.aborted)setView(v)}catch(e){if(mounted.current&&!controller.signal.aborted){setView(null);setError(e instanceof Error?e.message:'조회 실패')}}finally{if(mounted.current&&!controller.signal.aborted)setLoading(false)}},[campaignId]);
 useEffect(()=>{mounted.current=true;void Promise.resolve().then(()=>{if(mounted.current)void load()});return()=>{mounted.current=false;reading.current?.abort();writing.current?.abort()}},[load]);
 const mission=view?.missions.find(x=>x.id===form.missionId),bundle=bundles.find(x=>x.id===(mode==='prepare_bundle_mission'?form.bundleId:mission?.bundleId)),line=view?.orders.find(x=>x.id===form.lineId),canonical=view?.canonicalOrders.find(x=>x.id===form.orderId),commitment=view?.commitments.find(x=>x.id===mission?.commitmentId);
 const stockVersions=(ids:string[])=>ids.map(inventoryId=>({inventoryId,version:view?.inventory.find(x=>x.id===inventoryId)?.version??-1}));
 const text=(key:string,label:string,type='text')=><label>{label}<Input type={type} value={form[key]??''} onChange={e=>setForm(x=>({...x,[key]:e.target.value}))}/></label>;
 const check=(key:string,label:string)=><label><CheckInput checked={!!checks[key]} onChange={e=>setChecks(x=>({...x,[key]:e.target.checked}))}/>{label}</label>;
 const select=(key:string,label:string,options:{id:string;label:string}[])=><label>{label}<NativeSelect value={form[key]??''} onChange={e=>{setForm(x=>({...x,[key]:e.target.value}));setMoney({});retry.current=null;draftId.current=''}}><option value="">선택하세요</option>{options.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</NativeSelect></label>;
 function payload(){
  const evidenceRef=form.evidenceRef??'',common={campaignId,campaignVersion,action:mode};
  if(mode==='prepare_bundle_mission'){if(!bundle)throw Error('번들을 선택하세요.');draftId.current||=`bundle-mission-${crypto.randomUUID()}`;return {...common,id:draftId.current,expectedVersion:0,bundleId:bundle.id,bundleVersion:bundle.version,authorityId:form.authorityId,authorityVersion:view?.authorities.find(x=>x.id===form.authorityId)?.version,quantity:Number(form.quantity),inventories:stockVersions(bundle.assessment.stockAllocation.map(x=>x.inventoryId)),evidenceRef,confirmed:checks.confirmed===true,input:{title:bundle.input.title,assignee:form.assignee??'',deadline:form.deadline??'',nextAction:form.nextAction??'',channel:'storefront',budget:form.budget?Number(form.budget):null,lossLimit:form.lossLimit?Number(form.lossLimit):null,stopRule:form.stopRule??'',fulfillmentOwner:form.fulfillmentOwner??''}}}
  if(mode==='link_bundle_order'){if(!mission||!canonical)throw Error('미션과 실주문을 선택하세요.');const existing=view?.orders.find(x=>x.input.missionId===mission.id&&x.input.orderId===canonical.id&&x.input.externalLineId===form.externalLineId);draftId.current||=`bundle-order-${crypto.randomUUID()}`;if(mission.reservation.components.some(x=>!money[x.inventoryId]?.paid.trim()||!money[x.inventoryId]?.refund.trim()))throw Error('모든 구성의 결제·환불 금액을 입력하세요.');const components=mission.reservation.components.map(x=>({inventoryId:x.inventoryId,paidAllocation:Number(money[x.inventoryId]?.paid),refundAllocation:Number(money[x.inventoryId]?.refund)}));return {...common,id:existing?.id??draftId.current,expectedVersion:existing?.version??0,missionId:mission.id,missionVersion:mission.version,orderId:canonical.id,orderVersion:canonical.version,sourceKey:form.sourceKey,accountId:commitment?.authoritySnapshot.accountId,externalLineId:form.externalLineId,quantity:Number(form.quantity),components,paidAllocation:components.reduce((n,x)=>n+x.paidAllocation,0),refundAllocation:components.reduce((n,x)=>n+x.refundAllocation,0),inventories:stockVersions(components.map(x=>x.inventoryId)),evidenceRef}}
  if(mode==='record_bundle_operation'){if(!line)throw Error('배정한 주문을 선택하세요.');return {...common,id:line.id,expectedVersion:line.version,inventoryId:form.inventoryId,inventoryVersion:view?.inventory.find(x=>x.id===form.inventoryId)?.version,kind:form.kind,quantity:Number(form.quantity),observedAt:form.observedAt,evidenceRef,safeRelease:!!checks.safeRelease,returnAccepted:!!checks.returnAccepted,disposition:form.disposition??'unknown',restock:!!checks.restock}}
  if(!mission||!commitment)throw Error('대사할 미션을 선택하세요.');return {...common,id:mission.id,expectedVersion:mission.version,commitmentVersion:commitment.version??1,releaseUnallocated:!!checks.releaseUnallocated,bundleVersion:bundle?.version,inventories:stockVersions(mission.reservation.components.map(x=>x.inventoryId)),status:form.status,input:{mode:form.reconcileMode,actualAmount:form.actualAmount?Number(form.actualAmount):null,actualLoss:form.actualLoss?Number(form.actualLoss):null,evidenceRef,note:form.note??'',noExecution:!!checks.noExecution,noOutstandingObligations:!!checks.noOutstandingObligations}};
 }
 async function save(){if(saving||loading||writing.current)return;setError('');setMessage('');let input:ReturnType<typeof payload>;try{input=payload()}catch(e){setError((e as Error).message);return}const key=JSON.stringify(input),requestId=retry.current?.key===key?retry.current.requestId:crypto.randomUUID();retry.current={key,requestId};const controller=new AbortController();writing.current=controller;setSaving(true);
  try{const r=await fetch('/api/growth/bundle-fulfillment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,requestId}),signal:controller.signal}),v=await r.json() as {recorded?:boolean;error?:string};if(!r.ok||v.recorded!==true)throw Error(v.error??'저장 결과를 확인하지 못했습니다.');if(!mounted.current)return;retry.current=null;draftId.current='';setMessage('내부 원장에 기록했습니다. 외부 발주·배송 요청은 보내지 않았습니다.');await load();await onChanged()}
  catch(e){if(mounted.current&&!controller.signal.aborted)setError(`${(e as Error).message} 응답 미확인은 같은 입력으로 재시도하세요.`)}finally{writing.current=null;if(mounted.current)setSaving(false)}
 }
 return <section aria-label="번들 판매 이행" className={styles.panel}><h4>번들 판매 미션과 이행 원장</h4><p>{view?.notice??'승인한 예산과 구성 재고를 준비하고 실제 운영 증빙을 기록합니다.'} 기존 단일 상품 판매 미션·발행·실험 화면에는 자동 연결되지 않습니다.</p>
  <Button variant="panel" size="fit" type="button" disabled={loading||saving} onClick={()=>void load()}>이행 기록 새로고침</Button>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
  <form onSubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={loading||saving||!view?.canEdit} className={styles.form}><legend>실제 증빙 기반 기록</legend><label>작업<NativeSelect value={mode} onChange={e=>{setMode(e.target.value as Mode);setForm({});setMoney({});setChecks({});draftId.current='';retry.current=null}}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</NativeSelect></label>
   {mode==='prepare_bundle_mission'&&<>{select('bundleId','준비할 번들',bundles.map(x=>({id:x.id,label:`${x.input.title} v${x.version}`})))}{select('authorityId','승인 위임',view?.authorities.filter(x=>x.input.status==='active').map(x=>({id:x.id,label:metaText([x.id,x.input.accountId])}))??[])}{text('quantity','예약 번들 수량','number')}{text('budget','예산 예약(원)','number')}{text('lossLimit','손실 한도(원)','number')}{text('assignee','실행 담당')}{text('deadline','실행 기한','date')}{text('nextAction','다음 행동')}{text('stopRule','중단 기준')}{text('fulfillmentOwner','배송·반품 담당')}{check('confirmed','위임·구성 재고와 전체 준비를 확인했습니다.')}</>}
   {(mode==='link_bundle_order'||mode==='reconcile_bundle_mission')&&select('missionId','번들 미션',view?.missions.map(x=>({id:x.id,label:metaText([x.input.title,`${x.id} v${x.version}`])}))??[])}
   {mode==='link_bundle_order'&&<>{select('orderId','실주문',view?.canonicalOrders.map(x=>({id:x.id,label:metaText([x.id,`${x.paidAmount}원 / 환불 ${x.refundAmount}원`])}))??[])}{text('sourceKey','판매처 출처 ID')}{text('externalLineId','판매처 주문 품목 ID')}{text('quantity','주문 번들 수량','number')}{mission?.reservation.components.map(x=><div key={x.inventoryId}><p>{x.sku}: 번들당 {x.units/mission.quantity}{x.unit==='pack'?'팩':'개'}</p>{(['paid','refund'] as const).map(k=><label key={k}>{k==='paid'?'결제':'환불'} 배분(원)<Input type="number" min={0} value={money[x.inventoryId]?.[k]??''} onChange={e=>setMoney(v=>({...v,[x.inventoryId]:{paid:v[x.inventoryId]?.paid??'',refund:v[x.inventoryId]?.refund??'',[k]:e.target.value}}))}/></label>)}</div>)}</>}
   {mode==='record_bundle_operation'&&<>{select('lineId','배정 주문',view?.orders.map(x=>({id:x.id,label:metaText([x.input.orderId,x.id])}))??[])}{select('inventoryId','구성 상품',line?.components.map(x=>({id:x.inventoryId,label:x.sku}))??[])}{select('kind','실제 이행 사건',[{id:'ship',label:'출고'},{id:'release',label:'미출고 해제'},{id:'refund',label:'환불 수량'},{id:'return',label:'반품 검수'}])}{text('quantity','해당 SKU 수량','number')}{text('observedAt','증빙 관측 시각(UTC ISO)')}{check('safeRelease','미출고 수량의 안전한 해제 확인')}{check('returnAccepted','반품 실물 검수 수락')}{select('disposition','반품 상태',[{id:'unknown',label:'미확인'},{id:'resalable',label:'재판매 가능'},{id:'not_resalable',label:'재판매 불가'}])}{check('restock','검수 수량 재입고')}</>}
   {mode==='reconcile_bundle_mission'&&<>{select('status','집행 결과',[{id:'unknown',label:'미확인'},{id:'failed',label:'실패 확인'},{id:'observed',label:'집행 확인'}])}{select('reconcileMode','예산 대사',[{id:'partial',label:'부분 실비'},{id:'final',label:'실비 최종 확정'},{id:'release',label:'전체 미집행 해제'}])}{text('actualAmount','누적 실비(원)','number')}{text('actualLoss','누적 손실(원)','number')}{text('note','대사 근거 설명')}{check('noExecution','실제 집행이 없음을 확인했습니다.')}{check('noOutstandingObligations','잔여 지급·이행 의무가 없습니다.')}{check('releaseUnallocated','최종 확정 시 미배정 구성 재고를 안전하게 해제합니다.')}</>}
   {text('evidenceRef','개인정보 없는 증빙 ID')}<Button variant="panel" size="fit" type="submit">{labels[mode]} 기록</Button>
  </fieldset></form>
  {view&&<p><MetaLine items={[`번들 미션 ${view.missions.length}개`,`주문 배정 ${view.orders.length}개`]}/>. SKU별 가용·출고·반품 수량은 공유 재고 원장에서 확인하세요.</p>}
 </section>;
}
