'use client';
import {NativeSelect} from '@/components/ui/native-select';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Note} from '@/components/app/note';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {GrowthReturnReasonView} from '@/lib/growth-return-reasons-server';
import styles from './growth-panel.module.css';
type View=GrowthReturnReasonView;
type Event=View['events'][number];
const labels={unknown:'미확인',product_defect:'상품 결함',description_mismatch:'설명과 다름',wrong_option:'옵션 불일치',delivery_issue:'배송 문제',change_of_mind:'구매자 변심',other:'기타'};
type Input={reasonCode:keyof typeof labels;evidenceRef:string};
type Basis={eventId:string;eventVersion:number;lineId:string;lineVersion:number|null;expectedVersion:number;campaignVersion:number};
const basis=(event:Event,campaignVersion:number):Basis=>({eventId:event.eventId,eventVersion:event.eventVersion,lineId:event.lineId,lineVersion:event.lineVersion,expectedVersion:event.current?.version??0,campaignVersion});
async function read(campaignId:string,signal:AbortSignal):Promise<View>{const r=await fetch(`/api/growth/return-reasons?campaignId=${encodeURIComponent(campaignId)}`,{cache:'no-store',signal}),v:unknown=await r.json();if(!r.ok)throw new Error('원인 목록을 조회하지 못했습니다. 관리자 권한과 연결 상태를 확인하세요.');if(!v||typeof v!=='object'||!Array.isArray((v as View).events)||!Array.isArray((v as View).history))throw new Error('목록 응답을 확인하지 못했습니다.');return v as View;}
export function GrowthReturnReasonsPanel({campaignId}:{campaignId:string}){return <Workspace key={campaignId} campaignId={campaignId}/>}
function Workspace({campaignId}:{campaignId:string}){
 const [view,setView]=useState<View|null>(null),[selected,setSelected]=useState<Basis|null>(null),[input,setInput]=useState<Input>({reasonCode:'unknown',evidenceRef:''}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[stale,setStale]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const mounted=useRef(false),reading=useRef<AbortController|null>(null),writing=useRef<AbortController|null>(null),retry=useRef<{key:string;requestId:string}|null>(null);
 const load=useCallback(async()=>{reading.current?.abort();const controller=new AbortController();reading.current=controller;setLoading(true);setError('');try{const next=await read(campaignId,controller.signal);if(!controller.signal.aborted){setView(next);setStale(false);}}catch(e){if(!controller.signal.aborted){setStale(true);setError(e instanceof Error?e.message:'조회 실패');}}finally{if(!controller.signal.aborted)setLoading(false);}},[campaignId]);
 useEffect(()=>{mounted.current=true;void Promise.resolve().then(()=>{if(mounted.current)void load();});return()=>{mounted.current=false;reading.current?.abort();writing.current?.abort();};},[load]);
 const event=view?.events.find(row=>row.eventId===selected?.eventId),changed=!!selected&&!!view&&(!event||JSON.stringify(selected)!==JSON.stringify(basis(event,view.campaignVersion))),busy=loading||saving;
 function choose(id:string){const row=view?.events.find(e=>e.eventId===id);setSelected(row&&view?basis(row,view.campaignVersion):null);setInput(row?.current?{...row.current.input}:{reasonCode:'unknown',evidenceRef:''});setError('');setMessage('');retry.current=null;}
 async function save(){if(busy||writing.current||!view?.canEdit||!selected||!event||event.lineVersion===null||changed||stale)return;
  const payload={campaignId,...selected,input},key=JSON.stringify(payload),requestId=retry.current?.key===key?retry.current.requestId:crypto.randomUUID();retry.current={key,requestId};const controller=new AbortController();writing.current=controller;setSaving(true);setError('');setMessage('');
  try{const r=await fetch('/api/growth/return-reasons',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({...payload,requestId})}),v:unknown=await r.json();if(!r.ok)throw new Error(r.status===409?'사건 또는 원인 기록 판이 변경되었습니다. 새로고침한 뒤 최신 판을 명시적으로 채택하세요.':'원인 기록을 저장하지 못했습니다. 내부 증빙 ID와 권한을 확인하세요.');if(!v||typeof v!=='object'||(v as {recorded?:boolean}).recorded!==true)throw new Error('저장 결과를 확인하지 못했습니다.');if(!mounted.current||controller.signal.aborted)return;retry.current=null;setStale(true);setMessage('원인 기록을 저장했습니다. 최신 목록 조회가 실패해도 저장은 완료된 상태입니다.');await load();}
  catch(e){if(mounted.current&&!controller.signal.aborted)setError(`${e instanceof Error?e.message:'저장 실패'} 입력은 보존했습니다. 응답 미확인은 같은 입력으로 재시도하세요.`);}
  finally{writing.current=null;if(mounted.current&&!controller.signal.aborted)setSaving(false);}
 }
 return <section aria-label="반품 환불 원인" className={styles.panel}><header className={styles.header}><h3>반품·환불 원인 기록</h3><Button variant="panel" size="fit" aria-label="원인 목록 새로고침" type="button" disabled={busy} onClick={()=>void load()}>새로고침</Button></header>
  <Note className={styles.note}>기존 반품·환불 사건에 운영자가 확인한 원인과 내부 증빙만 기록합니다. 외부 공급자나 고객의 확증이 아니며 재고·환불 금액을 변경하지 않습니다. 고객 원문·연락처·URL·비밀키를 입력하지 마세요.</Note>
  {error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.success}>{message}</p>}{loading&&<p role="status">원인 목록을 조회하고 있습니다.</p>}{stale&&<p role="status" className={styles.warning}>이전 조회 결과입니다. 최신 목록 조회 전에는 추가 저장을 할 수 없습니다.</p>}
  {view&&<><form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy||!view.canEdit} className={styles.form}><legend>사건별 원인 근거</legend><label className={styles.wide}>기록할 반품·환불 사건<NativeSelect value={selected?.eventId??''} onChange={e=>choose(e.target.value)}><option value="">사건 선택</option>{view.events.map(row=><option key={row.eventId} value={row.eventId}>{row.kind==='return'?'반품':'환불'} · {row.eventId} · {row.sourceStatus==='held'?'보류':row.current?'기록 있음':'원인 미기록'}</option>)}</NativeSelect></label>
  {event&&<div className={styles.wide+' wrap-anywhere'}><p>이행 사건 ID: {event.eventId} · 사건 v{event.eventVersion}</p><p>성장 품목 ID: {event.lineId} · 품목 v{event.lineVersion??'미확인'}</p><p>재고 ID: {event.inventoryId}</p><p>사건 기록 수량 {event.quantity===null?'미확인':`${event.quantity.toLocaleString('ko-KR')}${event.unit==='piece'?'개':event.unit==='pack'?'팩':' (단위 미확인)'}`}</p><p>사건 관측 시각: {event.observedAt??'미확인'} · 기록 시각: {event.recordedAt??'미확인'}</p><p>이 수량은 사건의 기록 수량이며, 해당 원인으로 발생한 수량이나 환불 금액이 아닙니다. 사건끼리 합산하지 않습니다.</p>{event.reasons.map(reason=><p key={reason}>{reason}</p>)}{event.current&&<p>저장 원인 v{event.current.version}: {labels[event.current.input.reasonCode]} · 증빙 {event.current.input.evidenceRef}</p>}</div>}
  {changed&&<div className={styles.wide}><p>선택한 기준 판이 현재 기록과 다릅니다. 입력을 보존했습니다.</p>{event&&<Button variant="panel" size="fit" type="button" disabled={stale} disabledReason={stale?'다른 곳에서 먼저 바뀌었습니다. 최신 기록을 불러온 뒤 다시 하세요.':undefined} onClick={()=>{setSelected(basis(event,view.campaignVersion));retry.current=null;setError('');}}>현재 입력 유지 · 최신 판 채택</Button>}</div>}
  <label>운영자가 확인한 원인<NativeSelect value={input.reasonCode} onChange={e=>setInput({...input,reasonCode:e.target.value as Input['reasonCode']})}>{Object.entries(labels).map(([code,label])=><option key={code} value={code}>{label}</option>)}</NativeSelect></label><label>원인 증빙 내부 ID (개인정보 제외)<Input required maxLength={100} pattern="[A-Za-z0-9_-]+" value={input.evidenceRef} onChange={e=>setInput({...input,evidenceRef:e.target.value})}/></label><Button variant="panel" size="fit" type="submit" disabled={!event||event.lineVersion===null||changed||stale||!input.evidenceRef} disabledReason={!event?'먼저 대상을 고르세요.':(event.lineVersion===null)?'연결된 주문 줄이 없습니다.':changed?'다른 곳에서 먼저 바뀌었습니다. 최신 기록을 불러온 뒤 다시 하세요.':stale?'다른 곳에서 먼저 바뀌었습니다. 최신 기록을 불러온 뒤 다시 하세요.':!input.evidenceRef?'필수 칸을 먼저 채우세요.':undefined}>원인 기록 저장</Button></fieldset></form>
  {!view.events.length&&<p>현재 캠페인에서 조회할 반품·환불 사건이 없습니다. 원인 0건이나 반품 없음의 증명은 아닙니다.</p>}<details><summary>저장 원인 이력</summary>{view.history.map(row=><p key={row.id+':'+row.version} className="wrap-anywhere">{row.eventId} · 원인 v{row.version} · {labels[row.input.reasonCode]} · {row.input.evidenceRef} · {row.recordedAt} · 운영자 확인</p>)}</details></>}
 </section>;
}
