'use client';
import {EmptyLine} from '@/components/app/empty-line';
import {MetaLine} from '@/components/app/meta-line';
import {LockedNote} from '@/components/app/locked-note';
import {readOnlyReason} from '@/lib/ui/read-only';
import {NativeSelect} from '@/components/ui/native-select';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Note} from '@/components/app/note';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {GrowthLessonApplicationView} from '@/lib/growth-lesson-applications-server';
import {applicationTargets,type ApplicationInput} from '@/lib/growth-lesson-applications';
import styles from './growth-panel.module.css';
type View=GrowthLessonApplicationView;
const targetLabels={mission:'판매 미션',landing_revision:'상세 수정안',demand:'수요 시퀀스',experiment:'판매 실험'} as const;
const resultLabels={success:'성공',failure:'실패',invalid:'무효(판단 불가)'} as const;
const emptyInput=():ApplicationInput=>({lessonId:'',lessonVersion:1,targetKind:'mission',targetId:'',targetVersion:1,howApplied:'',expectedCheck:'',checkAt:''});
async function read(campaignId:string,signal:AbortSignal):Promise<View>{const r=await fetch(`/api/growth/lesson-applications?campaignId=${encodeURIComponent(campaignId)}`,{cache:'no-store',signal}),v:unknown=await r.json();if(!r.ok)throw new Error('교훈 적용을 조회하지 못했습니다. 관리자 권한과 연결 상태를 확인하세요.');if(!v||typeof v!=='object'||!Array.isArray((v as View).applications))throw new Error('교훈 적용 응답을 확인하지 못했습니다.');return v as View;}
export function GrowthLessonApplicationsPanel({campaignId}:{campaignId:string}){return <Workspace key={campaignId} campaignId={campaignId}/>}
function Workspace({campaignId}:{campaignId:string}){
 const [view,setView]=useState<View|null>(null),[input,setInput]=useState<ApplicationInput>(emptyInput),[outcome,setOutcome]=useState({id:'',result:'success',at:'',evidenceRef:'',note:''}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[stale,setStale]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const mounted=useRef(false),reading=useRef<AbortController|null>(null),writing=useRef<AbortController|null>(null),retry=useRef<{key:string;requestId:string}|null>(null),draftId=useRef('');
 const load=useCallback(async()=>{reading.current?.abort();const controller=new AbortController();reading.current=controller;setLoading(true);setError('');try{const next=await read(campaignId,controller.signal);if(!controller.signal.aborted){setView(next);setStale(false);}}catch(e){if(!controller.signal.aborted){setStale(true);setError(e instanceof Error?e.message:'조회 실패');}}finally{if(!controller.signal.aborted)setLoading(false);}},[campaignId]);
 useEffect(()=>{mounted.current=true;void Promise.resolve().then(()=>{if(mounted.current)void load();});return()=>{mounted.current=false;reading.current?.abort();writing.current?.abort();};},[load]);
 const busy=loading||saving;
 async function send(body:Record<string,unknown>,done:string){if(busy||writing.current||!view||stale)return;
  const payload={campaignId,campaignVersion:view.campaignVersion,...body},key=JSON.stringify(payload),requestId=retry.current?.key===key?retry.current.requestId:crypto.randomUUID();retry.current={key,requestId};const controller=new AbortController();writing.current=controller;setSaving(true);setError('');setMessage('');
  try{const r=await fetch('/api/growth/lesson-applications',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({...payload,requestId})}),v:unknown=await r.json();if(!r.ok)throw new Error((v as {error?:string})?.error??'저장하지 못했습니다.');if(!v||typeof v!=='object'||(v as {recorded?:boolean}).recorded!==true)throw new Error('저장 결과를 확인하지 못했습니다.');if(!mounted.current||controller.signal.aborted)return;retry.current=null;if(body.action==='apply'){draftId.current='';setInput(emptyInput());}else setOutcome({id:'',result:'success',at:'',evidenceRef:'',note:''});setStale(true);setMessage(`${done} 최신 조회가 실패해도 저장은 완료된 상태입니다.`);await load();}
  catch(e){if(mounted.current&&!controller.signal.aborted)setError(`${e instanceof Error?e.message:'저장 실패'} 입력은 보존했습니다. 응답 미확인은 같은 입력으로 재시도하세요.`);}
  finally{writing.current=null;if(mounted.current&&!controller.signal.aborted)setSaving(false);}
 }
 return <section aria-label="교훈 적용 계보" className={styles.panel}><header className={styles.header}><h3>운영 교훈 적용·결과 회수</h3><Button variant="panel" size="fit" aria-label="교훈 적용 새로고침" type="button" disabled={busy} onClick={()=>void load()}>새로고침</Button></header>
  <Note className={styles.note}>재사용 가능한 교훈의 적용 기록과 결과를 남깁니다. 적용 대상은 다음 미션·상세 수정안·수요·실험의 정확한 판이고, 확인일에 성공·실패·무효를 회수합니다. 제안은 자동 적용이 아니며, 퇴역·승격은 실패가 반복되어도 운영자가 정합니다. 결과 집계는 인과 판정이 아닙니다.</Note>
  {error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.success}>{message}</p>}{loading&&<p role="status">교훈 적용을 조회하고 있습니다.</p>}{stale&&<p role="status" className={styles.warning}>이전 조회 결과입니다. 최신 조회 전에는 추가 저장을 할 수 없습니다.</p>}
  {view&&<><h4>적용 제안</h4>{!view.suggestions.length&&<EmptyLine next="실패 교훈을 저장하면 다른 캠페인에 쓸 후보로 제안됩니다.">제안할 재사용 교훈이 없습니다.</EmptyLine>}
   <ul>{view.suggestions.map(s=><li key={s.missionId}>{s.title} v{s.missionVersion}: {s.lessons.map(l=><Button disabledReason={view.canEdit?undefined:readOnlyReason} variant="panel" size="fit" key={l.id} type="button" disabled={busy||!view.canEdit} onClick={()=>setInput({...emptyInput(),lessonId:l.id,lessonVersion:l.version,targetKind:'mission',targetId:s.missionId,targetVersion:s.missionVersion})}>{l.title}{l.record?` (성공 ${l.record.success}/실패 ${l.record.failure})`:''} 적용 준비</Button>)}</li>)}</ul>
   {view.canEdit?<form onSubmit={e=>{e.preventDefault();if(!draftId.current)draftId.current=`apply-${crypto.randomUUID().slice(0,8)}`;void send({action:'apply',id:draftId.current,expectedVersion:0,input},'교훈 적용을 기록했습니다.');}}><fieldset disabled={busy} className={styles.form}><legend>교훈 적용 기록</legend>
    <label>교훈<NativeSelect value={input.lessonId} onChange={e=>{const l=view.reusable.find(x=>x.id===e.target.value);setInput({...input,lessonId:e.target.value,lessonVersion:l?.version??1});}}><option value="">교훈 선택</option>{view.reusable.map(l=><option key={l.id} value={l.id}>{l.title} v{l.version}</option>)}</NativeSelect></label>
    <label>적용 대상 종류<NativeSelect value={input.targetKind} onChange={e=>setInput({...input,targetKind:e.target.value as ApplicationInput['targetKind']})}>{applicationTargets.map(t=><option key={t} value={t}>{targetLabels[t]}</option>)}</NativeSelect></label>
    <label>대상 ID<Input value={input.targetId} onChange={e=>setInput({...input,targetId:e.target.value})}/></label><label>대상 판<Input type="number" min={1} value={input.targetVersion} onChange={e=>setInput({...input,targetVersion:Number(e.target.value)})}/></label>
    <label className={styles.wide}>적용 방법<Input maxLength={1000} value={input.howApplied} onChange={e=>setInput({...input,howApplied:e.target.value})}/></label>
    <label>확인할 결과<Input maxLength={500} value={input.expectedCheck} onChange={e=>setInput({...input,expectedCheck:e.target.value})}/></label><label>효과 확인일<Input type="date" value={input.checkAt} onChange={e=>setInput({...input,checkAt:e.target.value})}/></label>
    <Button variant="panel" size="fit" type="submit" disabled={stale||!input.lessonId||!input.targetId||!input.howApplied||!input.expectedCheck||!input.checkAt} disabledReason={stale?'다른 곳에서 먼저 바뀌었습니다. 최신 기록을 불러온 뒤 다시 하세요.':!input.lessonId?'먼저 대상을 고르세요.':!input.targetId?'먼저 대상을 고르세요.':!input.howApplied?'필수 칸을 먼저 채우세요.':!input.expectedCheck?'필수 칸을 먼저 채우세요.':!input.checkAt?'필수 칸을 먼저 채우세요.':undefined}>적용 기록</Button></fieldset></form>:<LockedNote action="교훈 적용 기록" reason={readOnlyReason}/>}
   <h4>적용 기록</h4><ul>{view.applications.map(a=><li key={a.id} className="wrap-anywhere"><p><MetaLine items={[a.id,`교훈 ${a.input.lessonId} v${a.input.lessonVersion} → ${targetLabels[a.input.targetKind]} ${a.input.targetId} v${a.input.targetVersion}`,`확인일 ${a.input.checkAt}`,a.overdue&&'확인일 경과',a.outcome?resultLabels[a.outcome.result]:'결과 대기',a.sourceStatus==='changed'&&'원본 변경']}/></p>{a.sourceReasons.map(x=><p key={x}>{x}</p>)}
    {a.automatic&&<p><MetaLine items={['자동 관측',a.automatic.sourceStatus==='changed'?'원본 변경·재회수 필요':a.automatic.state==='current'?(a.automatic.observation?.kind==='experiment'?'판매 실험 관측':'운영 상태 관측'):'판단 보류',a.automatic.sourceStatus==='current'?a.automatic.observation?.status:null,`회수 ${a.automatic.collectedAt}`,'교훈의 인과 효과는 측정하지 않음']}/>{a.automatic.sourceReasons.join(' ')}</p>}
    {!a.outcome&&<Button variant="panel" size="fit" type="button" disabled={busy||!view.canEdit} disabledReason={view.canEdit?undefined:readOnlyReason} onClick={()=>setOutcome({id:a.id,result:'success',at:new Date(Math.floor((Date.now()+60000)/60000)*60000-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16),evidenceRef:'',note:''})}>{a.id} 결과 기록</Button>}</li>)}</ul>
   {outcome.id&&<fieldset className={styles.form} disabled={busy}><legend>{outcome.id} 결과</legend><label>결과<NativeSelect value={outcome.result} onChange={e=>setOutcome({...outcome,result:e.target.value})}>{Object.entries(resultLabels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</NativeSelect></label><label>결과 확인 시각<Input type="datetime-local" value={outcome.at} onChange={e=>setOutcome({...outcome,at:e.target.value})}/></label><label>결과 증빙 ID<Input value={outcome.evidenceRef} onChange={e=>setOutcome({...outcome,evidenceRef:e.target.value})}/></label><label>결과 근거<Input value={outcome.note} onChange={e=>setOutcome({...outcome,note:e.target.value})}/></label>
    <Button variant="panel" size="fit" type="button" disabled={stale||!outcome.evidenceRef||!outcome.note} disabledReason={stale?'다른 곳에서 먼저 바뀌었습니다. 최신 기록을 불러온 뒤 다시 하세요.':!outcome.evidenceRef?'필수 칸을 먼저 채우세요.':!outcome.note?'필수 칸을 먼저 채우세요.':undefined} onClick={()=>{const a=view.applications.find(x=>x.id===outcome.id);if(a)void send({action:'record_outcome',id:a.id,expectedVersion:a.version,outcome:{result:outcome.result,at:new Date(outcome.at).toISOString(),evidenceRef:outcome.evidenceRef,note:outcome.note}},'결과를 기록했습니다.');}}>결과 저장</Button></fieldset>}
   <details><summary>자동 근거 회수 이력</summary><p>수동 판정은 덮어쓰지 않습니다. 아래는 회수 당시의 근거이며 현재 상태는 적용 기록에서 확인하세요.</p>{view.automaticHistory.rows.map(r=><p key={`${r.id}:${r.version}`}><MetaLine items={[r.id,`회수 판 ${r.version}`,r.state,r.observation?.status,r.collectedAt]}/></p>)}{view.automaticHistory.hasMore&&<p>최근 200건을 표시합니다. 이전 이력도 보존되어 있습니다.</p>}</details>
   <h4>교훈별 재사용 결과</h4><ul>{view.tally.map(t=><li key={t.lessonId}>{t.lessonId}: <MetaLine items={[`적용 ${t.applied}`,`성공 ${t.success}`,`실패 ${t.failure}`,`무효 ${t.invalid}`,`대기 ${t.pending}`,t.reviewSuggested&&'검토 권장(자동 퇴역 아님)']}/></li>)}</ul></>}
 </section>;
}
