'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {toast} from 'sonner';
import {ArrowUpRight,ArrowRight,Plus,Sparkles,FlaskConical,BookOpen,Play,RefreshCw,Pause,LoaderCircle,Check,Search,Download} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {api,downloadText,type WorkspaceData} from '@/lib/client';
import {learningChannels,verifyChannels,defaultVerifyChannel,learningMetrics,ruleApplies,ruleNeedsReview,operatorRule,playbookState,PLAYBOOK_MAX_CHARS,ANY_CHANNEL,type ReviewDecisionSummary,type LearningData,type ViralCase,type ViralAnalysis,type ViralExperiment,type LearningMetric,type LearningRule,type Assessment} from '@/lib/learning';
import {recommendationLabels,decisionConflict,ADOPT_AT,type ViralStats} from '@/lib/viral-stats';
import {ruleState,renewNote,frozenSummaryFor,frozenSummaryLines,expiringBanner,campaignExpiring} from '@/lib/learning-view';
import {pushNav,type LearningTab} from '@/lib/nav-state';
import type {FrozenExperimentSummary} from '@/lib/record-kinds';
import {roles,type Campaign} from '@/lib/agency';
import {defaultBrandId} from '@/lib/brand-default';
import {REVIEW_REASONS} from '@/lib/review-decisions';
import {canChange,useAccount} from './account-context';

const blank:LearningData={cases:[],analyses:[],experiments:[],rules:[],snapshots:[],jobs:[],observations:[],jobOutputs:[]};
const analysisLabels:Record<string,string>={facts:'확인한 사실',hook:'멈춰 본 이유 · 가설',retention:'계속 본 이유 · 가설',sharing:'공유한 이유 · 가설',context:'계정·시점·배포 영향',counterEvidence:'반례와 다른 설명',unknowns:'미확인 · 추가로 필요한 근거'};
const date=(s:string)=>new Date(s).toLocaleString('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const localNow=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const numeric=(s:string)=>s===''?null:Number(s);
const pct=(n:number|null|undefined)=>n===null||n===undefined?'미확인':(n*100).toFixed(2)+'%';
const prob=(p:number)=>p>=0.999?'99.9% 이상':p<=0.001?'0.1% 이하':(p*100).toFixed(1)+'%';
// lift 구간 끝이 비율 10⁶배를 넘으면 null이다. 하한이 null이면 구간 전체가 계산 범위(+99,999,900%) 위에 있다.
const signed=(n:number|null)=>n===null?'상한 없음':(n>=0?'+':'')+n.toFixed(1)+'%';
const lowerBound=(n:number|null)=>n===null?'+99,999,900% 초과':signed(n);
const post=(action:string,payload:Record<string,unknown>={})=>api(action,payload,'/api/learning');
const run=(action:string,payload:Record<string,unknown>={})=>api(action,payload,'/api/learning/run');
// 학습 화면에서 마지막으로 고른 브랜드. 저장소를 쓸 수 없으면(사생활 보호 모드 등) 최근 활동 브랜드로 시작한다.
const brandKey='collective:learning-brand';
function storedBrand(){try{return window.localStorage.getItem(brandKey)}catch{return null}}
function rememberBrand(id:string){try{window.localStorage.setItem(brandKey,id)}catch{/* 저장하지 못하면 이 화면을 여는 동안만 기억한다. */}}
// 학습 화면의 브랜드 활동: 사례 등록·실험 갱신·캠페인 수정 시각.
const learningActivity=(d:Pick<LearningData,'cases'|'experiments'>,campaigns:Campaign[])=>[...d.cases.map(c=>({brandId:c.brandId,at:c.createdAt})),...d.experiments.map(e=>({brandId:e.brandId,at:e.updatedAt||e.createdAt})),...campaigns.map(c=>({brandId:c.brandId,at:c.updatedAt||c.createdAt}))];
function Field({label,children,help}:{label:string;children:React.ReactNode;help?:string}){return <label className="field"><span>{label}</span>{children}{help&&<small>{help}</small>}</label>}
function Empty({title,text}:{title:string;text:string}){return <div className="learning-empty"><FlaskConical size={26}/><h3>{title}</h3><p>{text}</p></div>}
function TextBlock({title,text}:{title:string;text:string}){return <section className="learning-text"><h4>{title}</h4><p>{text}</p></section>}
// 운영자 선호 규칙(B3-1). 인용 선택 줄의 대상·판정 라벨. 검토 메모 원문은 판정 로그에 없다.
const targetLabels:Record<string,string>={artifact:'작업물',brief_suggestion:'브리프 제안',source:'자료',publication:'발행'};
const decisionLabels:Record<string,string>={approved:'승인',revision:'수정 요청',adopted:'채택',edited:'수정',ignored:'미사용',excluded:'제외',cancelled:'발행 취소',returned:'반려'};
const playbookStatus:Record<string,string>={draft:'초안 · 승인 대기',active:'적용 중',paused:'적용 중지',retired:'종료'};
const roleName=(id?:string|null)=>id?roles.find(r=>r.id===id)?.name??id:'모든 역할';
const reasonLabel=(code:string)=>REVIEW_REASONS.find(r=>r.code===code)?.label??code;
const decisionLine=(d:ReviewDecisionSummary)=>[date(d.createdAt),targetLabels[d.targetKind]??d.targetKind,...(d.role?[roleName(d.role)]:[]),decisionLabels[d.decision]??d.decision,...(d.reasonCodes.length?['사유: '+d.reasonCodes.map(reasonLabel).join(', ')]:[]),...(d.origin==='ai_edited'?['사람 수정본']:[])].join(' · ');
type PlaybookDraft={brandId:string;text:string;role:string;channel:string;origin:string;citations:string[]};
// 승인·중지·연장·생성은 소유자만(서버 403) — 화면도 같은 규칙으로 버튼을 끈다. Curator 제안(중복·충돌)은 보여 주기만 하고 자동 병합하지 않는다.
function PlaybookRules({rules,data,busy,canOwn,act,onCreate}:{rules:LearningRule[];data:LearningData;busy:boolean;canOwn:boolean;act:(fn:()=>Promise<unknown>,message:string)=>void;onCreate:()=>void}){
 const suggestions=(data.playbookSuggestions??[]).filter(s=>rules.some(r=>r.id===s.ruleIds[0])),title=(id:string)=>rules.find(r=>r.id===id)?.title??'다른 규칙';
 const pause=(r:LearningRule)=>act(async()=>{const x=await post('playbook_pause',{id:r.id,version:r.version}) as {id:string;affected?:number};toast.info(`이 규칙이 전달된 작업물 ${x.affected??0}건에 재확인 표시를 남겼습니다. 작업물 내용은 바뀌지 않습니다.`)},'적용을 중지했습니다.');
 return <section aria-label="운영자 선호 규칙" style={{marginTop:32}}>
  <div className="learning-card-top"><b>운영자 선호 규칙 · {rules.length}건</b><Button size="sm" variant="outline" disabled={busy||!canOwn} onClick={onCreate}><Plus/>선호 규칙 만들기</Button></div>
  <p className="learning-note">사람 판정(수정 요청·채택·제외 등) 2건 이상을 인용한 운영자 선호입니다. 소유자가 승인하면 같은 브랜드의 AI 역할 입력에 성과 규칙과 다른 블록으로 전달되고 60일 뒤 만료됩니다. 만료 7일 전부터 재확인(연장)이 필요합니다.{canOwn?'':' 승인·중지·연장·생성은 소유자만 할 수 있습니다.'}</p>
  {suggestions.length>0&&<ul className="learning-meta" aria-label="Curator 제안">{suggestions.map(s=><li key={s.ruleIds.join(':')}>{s.kind==='conflict'?'충돌 후보':'중복 후보'} · 「{title(s.ruleIds[0])}」 ↔ 「{title(s.ruleIds[1])}」 · {s.note}</li>)}</ul>}
  {rules.length?<div className="learning-experiments">{rules.map(r=>{const s=playbookState(r),rechecks=(data.playbookRechecks??[]).filter(x=>x.ruleId===r.id).length,live=r.status==='active'&&!s.expired;return <section className="learning-rule" key={r.id}>
   <div className="learning-card-top"><span>{r.channel===ANY_CHANNEL?'모든 채널':r.channel} · {roleName(r.role)} · v{r.version}</span><span className={'learning-tag'+(live?' good':'')}>{r.status==='active'&&s.expired?'만료 · 전달 안 함':playbookStatus[r.status]??r.status}</span></div>
   <p>{r.guidance}</p>
   <p className="learning-meta">등급 운영자 선호 · {r.origin==='preference'?'편집 근거':'교정 판정'} 인용 {r.citations?.length??0}건 · {s.expired?'만료됨':`만료까지 ${s.daysLeft}일`}{s.reconfirm&&!s.expired?' · 재확인 필요':''}{rechecks?` · 재확인 표시 작업물 ${rechecks}건`:''}</p>
   <div className="learning-actions">{(r.status==='draft'||r.status==='paused')&&<Button size="sm" disabled={busy||!canOwn} onClick={()=>act(()=>post('playbook_activate',{id:r.id,version:r.version}),'승인했습니다. 다음 AI 작업부터 전달합니다.')}><Check/>승인</Button>}{r.status==='active'&&<><Button size="sm" variant="outline" disabled={busy||!canOwn} onClick={()=>act(()=>post('playbook_renew',{id:r.id,version:r.version}),'지금부터 60일로 연장했습니다.')}><RefreshCw/>60일 연장</Button><Button size="sm" variant="outline" disabled={busy||!canOwn} onClick={()=>pause(r)}><Pause/>적용 중지</Button></>}</div>
  </section>})}</div>:<Empty title="교정에서 반복된 선호를 규칙으로" text="같은 사유로 여러 번 고친 판정을 인용해 운영자 선호 규칙을 만들면, 승인 뒤 다음 AI 작업에 전달됩니다."/>}
 </section>;
}
// 생성 폼: 본문 400자, 역할·채널, 인용할 사람 판정(브랜드의 최근 판정 중 사유 요약으로 고른다). 저장하면 초안이다.
function PlaybookForm({f,set,decisions}:{f:PlaybookDraft;set:(k:string,v:unknown)=>void;decisions:ReviewDecisionSummary[]}){
 const toggle=(id:string)=>set('citations',f.citations.includes(id)?f.citations.filter(x=>x!==id):[...f.citations,id]);
 return <>
  <Field label={`규칙 본문 * (${f.text.length}/${PLAYBOOK_MAX_CHARS}자)`} help="URL·연락처·이전 지시 무시 같은 명령형 문구는 저장되지 않습니다."><Textarea required rows={4} maxLength={PLAYBOOK_MAX_CHARS} value={f.text} onChange={e=>set('text',e.target.value)} placeholder="예: 첫 문장은 고객의 평일 상황으로 시작한다."/></Field>
  <div className="form-two"><Field label="역할"><NativeSelect value={f.role} onChange={e=>set('role',e.target.value)}><NativeSelectOption value="">모든 역할</NativeSelectOption>{roles.map(r=><NativeSelectOption key={r.id} value={r.id}>{r.name}</NativeSelectOption>)}</NativeSelect></Field><Field label="채널"><NativeSelect value={f.channel} onChange={e=>set('channel',e.target.value)}><NativeSelectOption value={ANY_CHANNEL}>모든 채널</NativeSelectOption>{learningChannels.map(x=><NativeSelectOption key={x} value={x}>{x}</NativeSelectOption>)}</NativeSelect></Field></div>
  <Field label="근거 종류"><NativeSelect value={f.origin} onChange={e=>set('origin',e.target.value)}><NativeSelectOption value="review">교정 판정</NativeSelectOption><NativeSelectOption value="preference">편집 근거 · 사람이 고친 AI 작업물 판정만</NativeSelectOption></NativeSelect></Field>
  <div className="field" role="group" aria-label="인용할 사람 판정"><span>인용할 사람 판정 * · 2건 이상 ({f.citations.length}건 선택)</span><div style={{display:'grid',gap:10,maxHeight:260,overflowY:'auto'}}>{decisions.length?decisions.map(d=><label className="learning-check" key={d.id}><Checkbox checked={f.citations.includes(d.id)} onCheckedChange={()=>toggle(d.id)}/><span style={{minWidth:0,overflowWrap:'anywhere'}}>{decisionLine(d)}</span></label>):<p className="learning-meta">이 브랜드의 사람 판정 기록이 없습니다. 작업물 수정 요청·브리프 제안 판정이 쌓이면 고를 수 있습니다.</p>}</div></div>
 </>;
}
// 사후확률 요약·중간 확인 경고·통계 권고와 사람이 확정한 판정. 권고는 참고이고 확정은 '학습에 반영'에서 사람이 한다.
function StatsBlock({stats,assessment,rule}:{stats:ViralStats|null|undefined;assessment?:Assessment|null;rule?:LearningRule}){
 if(!stats)return <div className="learning-assessment"><p>비율 지표 없음 — 통계 판정 불가</p><small>두 안 모두 분모가 0보다 크고 반응 수가 분모 이하여야 사후확률을 계산합니다. 분모를 넘을 수 있는 공유·클릭 집계는 이항 모형에 맞지 않습니다.</small></div>;
 const decided=rule?rule.sourceAssessment?.decision||(rule.direction==='caution'?'stop':'adopt'):null;
 return <div className="learning-assessment"><div><span>B가 A보다 나을 확률 {prob(stats.probBetter)}</span><span>lift {Math.round(stats.level*100)}% 구간 {lowerBound(stats.liftLow)} ~ {signed(stats.liftHigh)}</span>{stats.warning&&<span className="learning-tag">중간 확인 경고</span>}<b>{recommendationLabels[stats.recommendation]}</b></div>{stats.warning&&<p>{stats.warning.message}</p>}{assessment&&assessment.status!=='promising'&&stats.probBetter>=ADOPT_AT&&<p>기존 판정이 {assessment.label}이라 채택을 권고하지 않습니다. 채택 권고는 관찰상 개선일 때만 냅니다.</p>}<small>확정 판정: {decided==='adopt'?'채택 · 시험 적용 규칙':decided==='stop'?'중단 · 주의사항 규칙':'미확정'}{rule?.sourceAssessment?.decisionConflict?(rule.sourceAssessment.decisionConflict==='interim'?' · 중간 확인 경고 뒤 확정':' · 권고와 다르게 확정'):''}{rule?.sourceAssessment?.decisionReason?` · 사유: ${rule.sourceAssessment.decisionReason}`:''} · Beta(1,1) 사전분포 기준이며 채널 노출 편향과 귀속의 한계는 반영하지 않습니다.</small></div>;
}
// initialBrandId·initialTab: 주소(?view=learning&brand=&tab=)의 브랜드·탭. 고른 브랜드·탭은 onScopeChange로 알려 주소에 남긴다.
export function LearningPanel({workspace,onCampaign,initialBrandId,initialTab,onScopeChange}:{workspace:WorkspaceData;onCampaign:(id:string)=>void;initialBrandId?:string;initialTab?:LearningTab;onScopeChange?:(brandId:string,tab:string)=>void}){
 const[data,setData]=useState<LearningData>(blank),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,showTab]=useState<string>(initialTab??'cases'),[picked,setPicked]=useState<string|null>(()=>initialBrandId??storedBrand()),[query,setQuery]=useState('제품의 첫 장면과 공유 동기가 뚜렷한 최근 바이럴 사례. 비슷한 저성과 사례와 함께 비교.'),[selected,setSelected]=useState<string|null>(null),[modal,setModal]=useState(''),[f,setF]=useState<any>({}),[formError,setFormError]=useState('');
 // 기본 브랜드: 고른 브랜드(기억한 값 포함)가 없으면 사례·실험·캠페인 중 가장 최근 활동이 있는 브랜드. 학습 데이터를 처음 불러올 때 한 번 정하고
 // (저장하지 않음) 이후 폴링으로 다른 브랜드 활동이 최신이 돼도 바꾸지 않는다. 아래 계산은 처음 불러오기 전까지만 쓴다.
 const brandId=picked&&workspace.brands.some(b=>b.id===picked)?picked:defaultBrandId(workspace.brands,learningActivity(data,workspace.campaigns));
 // 운영자 선호 규칙의 생성·승인·중지·연장은 소유자만 한다(서버 playbook_* 403과 같은 규칙).
 const canOwn=canChange(useAccount(),true);
 const latestWorkspace=useRef(workspace);useEffect(()=>{latestWorkspace.current=workspace});
 const setBrand=(id:string)=>{setPicked(id);rememberBrand(id);onScopeChange?.(id,tab)};
 // 탭만 바꿀 때는 주소의 브랜드(링크나 직접 고른 값)만 유지한다. 기본 브랜드는 주소에 싣지 않아 기억되지 않는다.
 const setTab=(t:string)=>{showTab(t);onScopeChange?.(initialBrandId??'',t)};
 // 링크로 연 브랜드는 직접 고른 것처럼 기억한다(loop-7). 이미 열린 화면에 새 링크가 오면(뒤로가기·캠페인 상세 알림) 그 브랜드·탭으로 바꾼다.
 useEffect(()=>{if(initialBrandId)rememberBrand(initialBrandId)},[initialBrandId]);
 const[link,setLink]=useState({brand:initialBrandId,tab:initialTab});
 if(link.brand!==initialBrandId||link.tab!==initialTab){setLink({brand:initialBrandId,tab:initialTab});if(initialBrandId)setPicked(initialBrandId);if(initialTab)showTab(initialTab)}
 const current=useRef(data);current.current=data;const polling=useRef(false),mutating=useRef(false),pollCursor=useRef<string|null>(null);
 const reload=useCallback(async()=>{const r=await fetch('/api/learning');const d=await r.json() as LearningData & {error?:string};if(!r.ok)throw new Error(d.error||'학습 데이터를 불러오지 못했습니다.');setData(d);setLoaded(true);setError('');return d as LearningData},[]);
 useEffect(()=>{void reload().then(d=>{const w=latestWorkspace.current,fallback=defaultBrandId(w.brands,learningActivity(d,w.campaigns));setPicked(p=>p&&w.brands.some(b=>b.id===p)?p:fallback)}).catch(e=>setError(e.message));const timer=setInterval(async()=>{if(polling.current||mutating.current)return;const active=current.current.jobs.filter(j=>['queued','in_progress','starting'].includes(j.status));const j=active[(active.findIndex(j=>j.id===pollCursor.current)+1)%active.length];if(!j)return;pollCursor.current=j.id;polling.current=true;try{await run('poll',{id:j.id});await reload()}catch(e){setError((e as Error).message);await reload().catch(()=>{})}finally{polling.current=false}},8000);return()=>clearInterval(timer)},[reload]);
 const set=(k:string,v:any)=>setF((s:any)=>({...s,[k]:v}));
 // HERMES가 작성한 채택 문구 초안. 없으면 기존 템플릿을 쓴다. 초안이 있어도 채택은 사람이 승인한다.
 const draftFor=(e:ViralExperiment)=>data.guidances?.find(g=>g.id===e.id+':'+e.version)?.guidance||'';
 // 채택 화면에 넘길 통계 권고와 어긋남. 서버도 같은 규칙(decisionConflict)으로 어긋남을 규칙에 기록한다. 사유는 선택이다.
 const judgement=(e:ViralExperiment)=>{const decision=e.assessment?.status==='promising'?'adopt' as const:'stop' as const;return {conflict:decisionConflict(e.stats,decision),recommendation:e.stats?recommendationLabels[e.stats.recommendation]:'',decisionLabel:decision==='adopt'?'채택 · 시험 적용':'중단 · 주의사항',reason:''}};
 function open(kind:string,values:any){setModal(kind);setF(values);setFormError('')}
 async function action(fn:()=>Promise<unknown>,message:string){mutating.current=true;setBusy(true);try{await fn();await reload();if(message)toast.success(message)}catch(e){toast.error((e as Error).message)}finally{mutating.current=false;setBusy(false)}}
 const cases=data.cases.filter(c=>c.brandId===brandId),experiments=data.experiments.filter(e=>e.brandId===brandId),rules=data.rules.filter(r=>r.brandId===brandId&&!operatorRule(r)),playbook=data.rules.filter(r=>r.brandId===brandId&&operatorRule(r)),reviewQueue=rules.filter(r=>r.status==='active'&&ruleNeedsReview(r)),summaries=(data as LearningData&{experimentSummaries?:FrozenExperimentSummary[]}).experimentSummaries??[],c=data.cases.find(x=>x.id===selected),analyses=data.analyses.filter(a=>a.caseId===selected),a=analyses[0],banner=expiringBanner(data.expiringRules??[],brandId);
 const hasHermes=workspace.connection.configured&&workspace.connection.provider==='hermes';
 function addCase(){open('case',{brandId,title:'',channel:'Instagram',url:'',account:'',publishedAt:'',observedAt:localNow(),scope:'',observations:'',transcript:'',views:null,baselineViews:null,comparison:''})}
 function addPlaybook(){open('playbook',{brandId,text:'',role:'',channel:ANY_CHANNEL,origin:'review',citations:[]})}
 function addAnalysis(c:ViralCase){open('analysis',{caseId:c.id,...Object.fromEntries(Object.keys(analysisLabels).map(k=>[k,''])),hypothesis:'',variable:'',control:'',treatment:'',metric:'share_rate'})}
 function addExperiment(a:ViralAnalysis,index:number){const idea=a.ideas[index],caseChannel=data.cases.find(x=>x.id===a.caseId)?.channel||'';open('experiment',{analysisId:a.id,campaignId:workspace.campaigns.find(c=>c.brandId===a.brandId)?.id||'',...idea,caseChannel,verifyChannel:defaultVerifyChannel(caseChannel),title:idea.variable.slice(0,100)+' 실험',minSample:1000,minHours:72,minLift:10,conditions:'동일 채널·타깃·관찰 길이·예산을 유지하고, 계획한 요소 하나만 변경합니다.'})}
 function enterResults(e:ViralExperiment){open('result',{id:e.id,version:e.version,metric:e.metric,control:e.result?.control||{denominator:null,numerator:null,source:''},treatment:e.result?.treatment||{denominator:null,numerator:null,source:''},observedUntil:localNow(),comparable:e.result?.comparable||false,notes:e.result?.notes||''})}
 async function submit(ev:React.FormEvent){ev.preventDefault();setFormError('');setBusy(true);mutating.current=true;try{
  if(modal==='case'){const r=await post('add_case',{data:{...f,observedAt:new Date(f.observedAt).toISOString(),publishedAt:f.publishedAt?new Date(f.publishedAt).toISOString():''}});setSelected(r.id)}
  if(modal==='analysis')await post('save_analysis',{caseId:f.caseId,data:{...f,ideas:[{hypothesis:f.hypothesis,variable:f.variable,control:f.control,treatment:f.treatment,metric:f.metric}]}});
  if(modal==='experiment'){await post('create_experiment',{analysisId:f.analysisId,campaignId:f.campaignId,data:f});setSelected(null);setTab('experiments')}
  if(modal==='result')await post('save_results',{id:f.id,version:f.version,data:{...f,observedUntil:new Date(f.observedUntil).toISOString()}});
  if(modal==='adopt'){await post('adopt_rule',{id:f.id,version:f.version,guidance:f.guidance,reason:f.reason});setTab('rules')}
  if(modal==='renew')await post('renew_rule',{id:f.id,version:f.version,reason:f.reason});
  if(modal==='playbook')await post('playbook_create',{data:{brandId:f.brandId,text:f.text,role:f.role,channel:f.channel,origin:f.origin,citations:f.citations}});
  await reload();setModal('');toast.success('저장했습니다.');
 }catch(e){setFormError((e as Error).message)}finally{setBusy(false);mutating.current=false}}
 return <div className="learning-workspace">
  <section className="learning-command"><div className="learning-command-head"><div><span className="learning-kicker">VIRAL LEARNING LAB</span><h2>무엇이 확산을 만들었을까요?</h2><p>성공 이유를 가설로 만들고, 우리 콘텐츠에서 확인합니다.</p></div><Button variant="outline" onClick={addCase} disabled={!loaded||busy}><Plus/>사례 등록</Button></div><div className="learning-search"><NativeSelect aria-label="학습 브랜드" value={brandId} onChange={e=>setBrand(e.target.value)}>{workspace.brands.map(b=><NativeSelectOption key={b.id} value={b.id}>{loaded?`${b.name} · 사례 ${data.cases.filter(c=>c.brandId===b.id).length}`:b.name}</NativeSelectOption>)}</NativeSelect><Input aria-label="조사 주제" value={query} onChange={e=>setQuery(e.target.value)} placeholder="찾고 싶은 콘텐츠와 시장을 적으세요"/><Button className="lime-button" disabled={!loaded||busy||!hasHermes||!query.trim()} onClick={()=>action(()=>run('start_discovery',{brandId,query}),'HERMES에 사례 조사를 요청했습니다.')}><Search/>HERMES로 사례 찾기</Button></div><p className="learning-meta">{hasHermes?'연결된 검색·브라우저 도구로 조사합니다. 접근하지 못한 자료는 미확인으로 남깁니다.':'HERMES 연결 후 조사·분석을 실행할 수 있습니다. 직접 사례와 분석을 등록할 수도 있습니다.'} 예약·상시 수집은 아직 연결되지 않았습니다.</p></section>
  {error&&<div className="learning-error" role="alert">{error}<Button size="sm" variant="outline" onClick={()=>reload().catch(e=>setError(e.message))}><RefreshCw/>다시 확인</Button></div>}
  <div className="learning-stats">{[['01','수집한 사례',cases.length],['02','원인 분석',data.analyses.filter(a=>a.brandId===brandId).length],['03','콘텐츠 실험',experiments.length],['04','적용 중인 규칙',rules.filter(r=>r.status==='active'&&Date.parse(r.expiresAt)>Date.now()).length]].map(([n,label,count])=><div key={n}><span>{n} / {label}</span><strong>{loaded?count:'—'}</strong></div>)}</div>
  {(banner.items.length>0||banner.elsewhere>0)&&<section className="learning-note" role="status" aria-label="만료 임박 학습 규칙">{banner.items.length>0&&<><b>만료 임박 규칙 {banner.items.length}건</b> · 만료되면 새 AI 작업에 전달되지 않습니다. 재검증 실험으로 다시 측정하세요.<ul>{banner.items.map(item=><li key={item.rule.id}>{item.rule.title} · {item.rule.channel} · {item.note}{item.retest&&<Button size="sm" variant="link" disabled={busy} onClick={()=>action(async()=>{await post('retest_rule',{id:item.rule.id,version:item.rule.version});setTab('experiments')},'재검증 실험을 초안으로 만들었습니다.')}><FlaskConical/>재검증 실험 만들기</Button>}{item.rule.origin==='store'&&' · 점포 마케팅 화면에서 후속 실험을 만드세요.'}</li>)}</ul></>}{banner.elsewhere>0&&<p>다른 브랜드에도 만료 임박 규칙 {banner.elsewhere}건이 있습니다.</p>}</section>}
  <Tabs value={tab} onValueChange={setTab} className="learning-tabs"><TabsList><TabsTrigger value="cases">사례·분석</TabsTrigger><TabsTrigger value="experiments">콘텐츠 실험</TabsTrigger><TabsTrigger value="rules">학습 규칙</TabsTrigger><TabsTrigger value="jobs">실행 기록 {data.jobs.some(j=>['queued','in_progress','starting','uncertain'].includes(j.status))&&'·'}</TabsTrigger></TabsList>
   <TabsContent value="cases">{cases.length?<div className="learning-case-grid">{cases.map(c=>{const n=data.analyses.filter(a=>a.caseId===c.id).length;return <button className="learning-case" key={c.id} onClick={()=>setSelected(c.id)}><div className="learning-card-top"><span>{c.channel}</span><span className="learning-tag">{n?'분석 '+n+'건':'분석 대기'}</span></div><h3>{c.title}</h3><p>{c.observations}</p><div className="learning-case-metrics"><div><small>관찰 조회수</small><b>{c.views===null?'미확인':c.views.toLocaleString()}</b></div><div><small>평소 대비</small><b>{c.baselineViews&&c.views!==null?(c.views/c.baselineViews).toFixed(1)+'배':'비교 자료 필요'}</b></div></div><footer><span>{c.origin==='hermes'?'HERMES 보고':'직접 기록'} · {date(c.observedAt)}</span><ArrowUpRight size={18}/></footer></button>})}</div>:<Empty title="첫 사례에서 학습을 시작하세요" text="게시물 링크와 실제로 확인한 장면·자막·반응을 등록하거나, HERMES에 사례 조사를 맡겨보세요."/>}</TabsContent>
   <TabsContent value="experiments">{experiments.length?<div className="learning-experiments">{experiments.map(e=><section className="learning-experiment" key={e.id}><div className="learning-card-top"><span>{e.channel}{e.caseChannel&&e.caseChannel!==e.channel?` (사례 ${e.caseChannel})`:''} · {learningMetrics[e.metric].label}</span><span className={'learning-tag '+(e.assessment?.status==='promising'?'good':'')}>{e.assessment?.label||({draft:'계획 초안',running:'측정 중'} as any)[e.status]}</span></div><h3>{e.title}</h3><p className="learning-hypothesis">{e.hypothesis}</p><div className="learning-ab"><TextBlock title="A · 대조안" text={e.control}/><TextBlock title="B · 실험안" text={e.treatment}/></div><p className="learning-meta">변수: {e.variable} · 각 안 {e.minSample.toLocaleString()} 이상 · {e.minHours}시간 이상 · 상대 개선 {e.minLift}% 이상</p>{e.startedAt&&<p className="learning-meta">시작 {date(e.startedAt)} · 계획 고정 · v{e.version}</p>}{e.assessment&&<div className="learning-assessment"><div><span>A {pct(e.assessment.controlRate)}</span><ArrowRight size={16}/><span>B {pct(e.assessment.treatmentRate)}</span><b>{e.assessment.lift===null?'상대 차이 미확인':(e.assessment.lift>=0?'+':'')+e.assessment.lift.toFixed(1)+'%'}</b></div>{e.assessment.reasons.map(x=><p key={x}>{x}</p>)}<small>집계 지표의 관찰 비교입니다. 통계적 유의성·인과 효과를 확정하지 않습니다.</small></div>}{e.result&&<StatsBlock stats={e.stats} assessment={e.assessment} rule={rules.find(r=>r.experimentId===e.id&&r.experimentVersion===e.version)}/>}<div className="learning-actions"><Button variant="ghost" onClick={()=>onCampaign(e.campaignId)}>캠페인 열기<ArrowUpRight/></Button>{e.status==='draft'?<Button disabled={busy} onClick={()=>action(()=>post('start_experiment',{id:e.id,version:e.version}),'실험 계획을 고정했습니다. 게시·집행은 별도로 진행하세요.')}><Play/>계획 확정·측정 시작</Button>:<Button variant="outline" disabled={busy} onClick={()=>enterResults(e)}>{e.result?'결과 정정':'결과 입력'}</Button>}{e.assessment&&['promising','not_supported'].includes(e.assessment.status)&&!rules.some(r=>r.experimentId===e.id&&r.experimentVersion===e.version)&&<>{!draftFor(e)&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>action(()=>run('start_guidance',{experimentId:e.id,version:e.version}),'HERMES가 규칙 초안을 작성합니다. 완료되면 채택 화면에 채워집니다.')}><Sparkles/>규칙 초안</Button>}<Button disabled={busy} onClick={()=>open('adopt',{id:e.id,version:e.version,...judgement(e),draft:!!draftFor(e),guidance:draftFor(e)||(e.assessment!.status==='promising'?`시험 적용: ${e.treatment}`:`주의: ${e.variable} 변경에서 개선 가설이 지지되지 않았습니다. ${e.control}을 기준으로 새 변수를 검증하세요.`)+`\n적용 조건: ${e.conditions}\n${learningMetrics[e.metric].label}의 단일 실험 관찰 결과이며 추가 재현이 필요합니다.`})}><BookOpen/>학습에 반영</Button></>}</div></section>)}</div>:<Empty title="분석한 이유를 실험으로 확인하세요" text="사례의 분석 결과에서 실험안을 선택하면 A/B 제작안과 측정 기준을 함께 설계할 수 있습니다."/>}</TabsContent>
   <TabsContent value="rules"><p className="learning-note">같은 브랜드·채널의 새 AI 작업에 자동 반영됩니다. 단일 실험에서 얻은 규칙은 시험 적용하며 30일 후 재검토합니다. 결과를 정정하면 기존 규칙 적용은 종료됩니다.</p>{reviewQueue.length>0&&<p className="learning-note">재검토 대기 {reviewQueue.length}건 · 30일이 지난 관찰은 다시 측정해야 합니다. 측정 없이 연장은 한 번까지이며 근거가 강해지지 않습니다. 그 뒤에는 재검증 실험으로 새 측정을 기록해야 연장할 수 있습니다.</p>}{rules.length?<div className="learning-experiments">{[...rules].sort((a,b)=>Number(ruleNeedsReview(b))-Number(ruleNeedsReview(a))).map(r=>{const s=ruleState(r);return <section className="learning-rule" key={r.id}><div className="learning-card-top"><span>{r.channel}{r.caseChannel&&r.caseChannel!==r.channel?` (사례 ${r.caseChannel})`:''} · v{r.version}</span><span className="learning-tag">{s.label}</span></div><h3>{r.title}</h3><p>{r.guidance}</p>{r.sourceAssessment?.stats&&<p className="learning-meta">B가 A보다 나을 확률 {prob(r.sourceAssessment.stats.probBetter)} · {recommendationLabels[r.sourceAssessment.stats.recommendation]}{r.sourceAssessment.decisionReason?' · 확정 사유: '+r.sourceAssessment.decisionReason:''}</p>}{s.sourceDeleted&&<p className="learning-note" role="note">{s.notice}</p>}{renewNote(r)&&<p className="learning-meta">{renewNote(r)}</p>}{(()=>{const f=frozenSummaryFor(r,summaries);return f&&<details className="learning-frozen"><summary>동결 요약 · 원 캠페인 삭제 때 보관한 실험 수치</summary><ul>{frozenSummaryLines(f).map(line=><li key={line}>{line}</li>)}</ul></details>})()}<footer><span>관찰 근거 · {s.sourceDeleted?`원 캠페인 삭제 ${s.deletedAt?date(s.deletedAt):'시각 미확인'}`:`재검토 ${date(r.expiresAt)}`}{r.renewCount?` · 재측정 없이 ${r.renewCount}회 연장`:''}{r.renewMeasuredAt?` · ${r.renewMeasuredAt.length===10?r.renewMeasuredAt:date(r.renewMeasuredAt)}까지 측정한 결과로 연장`:''}</span>{s.actions.retest&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>action(()=>post('retest_rule',{id:r.id,version:r.version}),'재검증 실험을 초안으로 만들었습니다.')}><FlaskConical/>재검증 실험</Button>}{s.actions.renew&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>open('renew',{id:r.id,version:r.version,renewCount:r.renewCount||0,reason:''})}><RefreshCw/>30일 연장</Button>}{s.actions.retire&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>action(()=>post('retire_rule',{id:r.id,version:r.version}),'규칙 적용을 종료했습니다.')}><Check/>규칙 종료</Button>}{s.actions.pause&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>action(()=>post('pause_rule',{id:r.id,version:r.version}),'다음 작업부터 이 규칙의 적용을 중지합니다.')}><Pause/>적용 중지</Button>}</footer></section>})}</div>:<Empty title="실험 결과가 다음 제작의 기준이 됩니다" text="판정 기준을 충족한 실험에서 학습 규칙을 채택하세요. 잘되지 않았던 방법도 주의사항으로 남길 수 있습니다."/>}<PlaybookRules rules={playbook} data={data} busy={busy} canOwn={canOwn} act={(fn,message)=>void action(fn,message)} onCreate={addPlaybook}/></TabsContent>
   <TabsContent value="jobs"><p className="learning-note">접수된 작업은 HERMES에서 실행됩니다. 이 화면을 다시 열면 결과 확인을 이어갑니다. 접수 여부가 불명확하면 기존 요청을 확인해 중복 실행을 방지합니다.</p>{data.jobs.length?<div className="learning-experiments">{data.jobs.map(j=><section className="learning-job" key={j.id}><div><h3>{j.role==='viral_discovery'?'바이럴 사례 조사':'성공 원인 분석'}</h3><p>{date(j.createdAt)} · {({completed:'완료',failed:'확인 필요',cancelled:'중지됨',queued:'대기 중',in_progress:'분석 중',starting:'접수 중',uncertain:'접수 확인 필요'} as any)[j.status]||j.status}</p>{j.error&&<p className="form-error">{j.error}</p>}</div><div className="learning-actions">{['queued','in_progress','starting'].includes(j.status)&&<Button variant="outline" size="sm" disabled={busy} onClick={()=>action(()=>run('poll',{id:j.id}),'')}><RefreshCw/>결과 확인</Button>}{j.status==='uncertain'&&<Button variant="outline" disabled={busy} onClick={()=>action(()=>run('recover',{id:j.id}),'기존 요청의 접수를 확인했습니다.')}>기존 요청 확인</Button>}{['queued','in_progress'].includes(j.status)&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>action(()=>run('cancel',{id:j.id}),'실행 상태를 확인했습니다.')}><Pause/>중지</Button>}{data.jobOutputs.find(o=>o.id===j.id)&&<Button size="sm" variant="ghost" onClick={()=>downloadText('학습-응답.txt',data.jobOutputs.find(o=>o.id===j.id)!.output)}><Download/>원문</Button>}</div></section>)}</div>:<Empty title="조사와 분석의 실행 기록" text="HERMES에 요청한 작업의 진행 상태와 결과가 여기에 남습니다."/>}</TabsContent>
  </Tabs>
  <Dialog open={!!c&&!modal} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="learning-dialog"><DialogHeader><DialogTitle>{c?.title}</DialogTitle><DialogDescription>{c?.channel} · {c?.origin==='hermes'?'HERMES가 보고한 관찰':'직접 기록한 관찰'} · {c&&date(c.observedAt)}</DialogDescription></DialogHeader>{c&&<><a className="learning-source" href={c.url} target="_blank" rel="noopener noreferrer">원본 게시물 열기<ArrowUpRight size={16}/></a><TextBlock title="확인한 범위" text={c.scope}/><TextBlock title="관찰 기록" text={c.observations}/>{c.transcript&&<TextBlock title="자막·장면 메모" text={c.transcript}/>}<TextBlock title="비교 기준" text={c.comparison||'계정의 평소 반응과 유사한 저성과 사례를 추가하면 분석을 보강할 수 있습니다.'}/>{data.observations.filter(o=>o.caseId===c.id).map(o=><TextBlock key={o.id} title={'추가 관찰 · '+date(o.observedAt)} text={o.observations+`\n조회수: ${o.views??'미확인'}`}/>)}<div className="learning-actions"><Button variant="outline" onClick={()=>addAnalysis(c)} disabled={busy}><Plus/>직접 분석 등록</Button><Button className="lime-button" disabled={busy||!hasHermes||data.jobs.some(j=>j.campaignId==='case:'+c.id&&['starting','queued','in_progress','uncertain'].includes(j.status))} onClick={()=>action(()=>run('start_analysis',{caseId:c.id}),'제공된 근거로 HERMES 분석을 시작했습니다.')}><Sparkles/>HERMES 심층 분석</Button></div>{a?<><p className="learning-section-label">원인 분석 · {a.origin==='hermes'?'HERMES':'직접 작성'} · {date(a.createdAt)} · {analyses.length}개 분석 기록</p>{Object.entries(analysisLabels).map(([k,label])=><TextBlock key={k} title={label} text={(a as any)[k]}/>)}{a.ideas.map((idea,i)=><section className="learning-idea" key={i}><span>TEST {i+1} · {learningMetrics[idea.metric].label}</span><h4>{idea.hypothesis}</h4><p>바꿀 요소: {idea.variable}</p><div className="learning-ab"><TextBlock title="A · 대조안" text={idea.control}/><TextBlock title="B · 실험안" text={idea.treatment}/></div><Button onClick={()=>addExperiment(a,i)}><FlaskConical/>이 가설로 실험 설계</Button></section>)}{analyses.length>1&&<Button variant="ghost" onClick={()=>downloadText('바이럴-분석-이력.json',JSON.stringify(analyses,null,2))}><Download/>전체 분석 이력</Button>}</>:<p className="learning-note">첫 장면·시청 지속·공유 동기를 분석하고, 반례와 미확인을 함께 남깁니다. 영상·오디오 원본의 자동 분석은 연결되어 있지 않습니다.</p>}</>}</DialogContent></Dialog>
  <Dialog open={!!modal} onOpenChange={v=>!v&&!busy&&setModal('')}><DialogContent className="learning-dialog"><DialogHeader><DialogTitle>{({case:'바이럴 사례 등록',analysis:'성공 원인 분석',experiment:'콘텐츠 실험 설계',result:'실험 결과 기록',adopt:'다음 제작에 학습 반영',renew:'학습 규칙 30일 연장',playbook:'운영자 선호 규칙 만들기'} as any)[modal]}</DialogTitle><DialogDescription>{modal==='experiment'?'변경할 요소와 판정 기준을 먼저 정합니다. 측정 시작 후 계획은 고정됩니다.':modal==='result'?'같은 관찰 길이와 지표 정의로 두 안의 수치를 기록하세요. 미확인은 비워두세요.':modal==='adopt'?'동일 브랜드·채널의 새 작업에 적용하고 30일 후 재검토합니다.':modal==='playbook'?'같은 브랜드의 사람 판정을 2건 이상 인용합니다. 저장하면 초안이며 소유자가 승인해야 AI 작업에 전달됩니다.':'확인한 내용과 해석을 구분해 저장합니다.'}</DialogDescription></DialogHeader><form className="form-stack" onSubmit={submit}>
   {modal==='case'&&<><div className="form-two"><Field label="사례 이름 *"><Input required value={f.title} onChange={e=>set('title',e.target.value)}/></Field><Field label="채널"><NativeSelect value={f.channel} onChange={e=>set('channel',e.target.value)}>{learningChannels.map(x=><NativeSelectOption key={x}>{x}</NativeSelectOption>)}</NativeSelect></Field></div><Field label="원본 게시물 URL *"><Input required type="url" value={f.url} onChange={e=>set('url',e.target.value)}/></Field><div className="form-two"><Field label="계정"><Input value={f.account} onChange={e=>set('account',e.target.value)}/></Field><Field label="관찰 시점 *"><Input required type="datetime-local" value={f.observedAt} onChange={e=>set('observedAt',e.target.value)}/></Field><Field label="조회수 · 미확인은 비워두기"><Input min="0" type="number" value={f.views??''} onChange={e=>set('views',numeric(e.target.value))}/></Field><Field label="평소 비교 기준 조회수"><Input min="0" type="number" value={f.baselineViews??''} onChange={e=>set('baselineViews',numeric(e.target.value))}/></Field></div><Field label="비교 기준·관찰 길이"><Textarea value={f.comparison} onChange={e=>set('comparison',e.target.value)} placeholder="예: 같은 계정, 같은 형식의 최근 게시물 중앙값. 게시 후 72시간 기준."/></Field><Field label="실제로 확인한 범위 *"><Input required value={f.scope} onChange={e=>set('scope',e.target.value)} placeholder="예: 영상 첫 5초·캡션·공개 댓글 20개"/></Field><Field label="직접 확인한 내용 *"><Textarea required rows={4} value={f.observations} onChange={e=>set('observations',e.target.value)} placeholder="추측과 구분하여 장면·문구·반응을 적으세요."/></Field><Field label="자막·장면·음성 메모"><Textarea rows={4} value={f.transcript} onChange={e=>set('transcript',e.target.value)} placeholder="0–3초: … / 3–8초: … / 마무리: …"/></Field></>}
   {modal==='analysis'&&<>{Object.entries(analysisLabels).map(([k,label])=><Field key={k} label={label+' *'}><Textarea required rows={2} value={f[k]} onChange={e=>set(k,e.target.value)} placeholder={k==='unknowns'?'확인되지 않은 부분을 명시하세요.':undefined}/></Field>)}</>}
   {(modal==='analysis'||modal==='experiment')&&<>{modal==='experiment'&&<><Field label="실험 이름 *"><Input required value={f.title} onChange={e=>set('title',e.target.value)}/></Field><Field label="연결 캠페인 *"><NativeSelect required value={f.campaignId} onChange={e=>set('campaignId',e.target.value)}><NativeSelectOption value="">캠페인 선택</NativeSelectOption>{workspace.campaigns.filter(c=>c.brandId===brandId).map(c=><NativeSelectOption key={c.id} value={c.id}>{c.title}</NativeSelectOption>)}</NativeSelect></Field><div className="form-two"><Field label="원 사례 채널"><Input readOnly value={f.caseChannel}/></Field><Field label="검증할 채널 *" help="Instagram은 앱에서 발행·성과 수집, 네이버 검색광고는 성과 수집이 됩니다. 다른 채널은 게시와 수치 입력을 직접 합니다. 채택한 규칙은 검증한 채널의 캠페인에 적용됩니다."><NativeSelect required value={f.verifyChannel} onChange={e=>set('verifyChannel',e.target.value)}>{learningChannels.map(x=><NativeSelectOption key={x} value={x}>{verifyChannels.includes(x)?x+' · 앱에서 측정 가능':x}</NativeSelectOption>)}</NativeSelect></Field></div></>}<Field label="검증할 가설 *"><Textarea required value={f.hypothesis} onChange={e=>set('hypothesis',e.target.value)}/></Field><Field label="바꿀 요소 하나 *"><Input required value={f.variable} onChange={e=>set('variable',e.target.value)} placeholder="예: 첫 3초의 장면"/></Field><div className="form-two"><Field label="A · 대조안 *"><Textarea required rows={5} value={f.control} onChange={e=>set('control',e.target.value)}/></Field><Field label="B · 실험안 *"><Textarea required rows={5} value={f.treatment} onChange={e=>set('treatment',e.target.value)}/></Field></div><Field label="주지표"><NativeSelect value={f.metric} onChange={e=>set('metric',e.target.value)}>{Object.entries(learningMetrics).map(([k,v])=><NativeSelectOption key={k} value={k}>{v.label}</NativeSelectOption>)}</NativeSelect></Field></>}
   {modal==='experiment'&&<><div className="form-two"><Field label="각 안의 최소 분모 *"><Input type="number" min="100" required value={f.minSample} onChange={e=>set('minSample',Number(e.target.value))}/></Field><Field label="최소 관찰 시간 *"><Input type="number" min="1" max="2160" required value={f.minHours} onChange={e=>set('minHours',Number(e.target.value))}/></Field><Field label="목표 상대 개선율 (%) *"><Input type="number" min="0.1" step="0.1" max="1000" required value={f.minLift} onChange={e=>set('minLift',Number(e.target.value))}/></Field></div><Field label="동일 조건·적용 범위 *"><Textarea required rows={3} value={f.conditions} onChange={e=>set('conditions',e.target.value)}/></Field><p className="learning-note">기본 수치는 설계 시작값이며 통계적 검정력을 보장하지 않습니다. 게시·광고 집행은 별도로 진행합니다.</p></>}
   {modal==='result'&&<>{(['control','treatment'] as const).map((key,i)=><section className="learning-result-arm" key={key}><h3>{i===0?'A · 대조안':'B · 실험안'}</h3><div className="form-two"><Field label={learningMetrics[f.metric as LearningMetric].denominator}><Input type="number" min="0" step="1" value={f[key].denominator??''} onChange={e=>set(key,{...f[key],denominator:numeric(e.target.value)})}/></Field><Field label={learningMetrics[f.metric as LearningMetric].numerator}><Input type="number" min="0" step="1" value={f[key].numerator??''} onChange={e=>set(key,{...f[key],numerator:numeric(e.target.value)})}/></Field></div><Field label="수치 출처·조회 기간 *"><Input required value={f[key].source} onChange={e=>set(key,{...f[key],source:e.target.value})} placeholder="예: 자사 계정 인사이트, 게시물 URL, 조회 기간"/></Field></section>)}<Field label="측정 종료 시점 *"><Input type="datetime-local" required value={f.observedUntil} onChange={e=>set('observedUntil',e.target.value)}/></Field><label className="learning-check"><Checkbox checked={f.comparable} onCheckedChange={v=>set('comparable',v===true)}/><span>두 안의 타깃·기간·배포 조건을 비교할 수 있습니다.</span></label><Field label="측정 조건·차이·한계 *"><Textarea required value={f.notes} onChange={e=>set('notes',e.target.value)} placeholder="예산·게시 시점·타깃 차이, 자연 유입과 광고 유입 구분, 측정 한계를 기록하세요."/></Field><p className="learning-note">결과 정정 시 기존 학습 규칙은 적용 종료됩니다. 과거 캠페인에 사용한 근거는 보존합니다.</p></>}
   {modal==='renew'&&f.renewCount>0&&<p className="learning-note">연장은 한 번까지 측정 없이 가능합니다. 마지막 연장 이후 재검증 실험 결과(점포 규칙은 후속 실험 성과)를 기록했을 때만 다시 연장할 수 있습니다.</p>}
   {modal==='renew'&&<Field label={f.renewCount>0?'연장 사유 * (새 측정을 보고 유지하는 이유)':'연장 사유 * (새 측정 없이 유지하는 이유)'}><Textarea required rows={5} value={f.reason} onChange={e=>set('reason',e.target.value)}/></Field>}
   {modal==='adopt'&&f.draft&&<p className="learning-note">HERMES 초안입니다. 관찰 결과일 뿐 인과관계가 아니므로 읽고 고친 뒤 채택하세요.</p>}
   {modal==='adopt'&&f.recommendation&&<p className="learning-note">통계 권고: {f.recommendation} · 이번 확정: {f.decisionLabel}{f.conflict==='interim'?' · 중간 확인 경고가 있는 결과입니다. 확정은 막지 않고 규칙에 기록합니다.':f.conflict==='mismatch'?' · 권고와 다른 확정으로 규칙에 기록합니다.':''}</p>}
   {modal==='adopt'&&f.conflict&&<Field label="판정 사유(선택)"><Textarea rows={3} value={f.reason} onChange={e=>set('reason',e.target.value)} placeholder="예: 두 번째 입력은 오기 정정이며 측정 기간은 늘리지 않았습니다."/></Field>}
   {modal==='playbook'&&<PlaybookForm f={f} set={set} decisions={(data.reviewDecisions??[]).filter(d=>d.brandId===f.brandId).slice(0,40)}/>}
   {modal==='adopt'&&<Field label="직원이 다음 제작에 활용할 규칙 *"><Textarea required rows={9} value={f.guidance} onChange={e=>set('guidance',e.target.value)}/></Field>}
   {formError&&<p role="alert" className="form-error">{formError}</p>}<div className="form-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setModal('')}>취소</Button><Button type="submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Check/>}저장</Button></div>
  </form></DialogContent></Dialog>
 </div>;
}

export function CampaignLearning({campaign}:{campaign:Campaign}){
 const[data,setData]=useState<LearningData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;fetch('/api/learning').then(async r=>{const d=await r.json() as LearningData & {error?:string};if(!r.ok)throw new Error(d.error);if(active)setData(d)}).catch(e=>active&&setError(e.message));return()=>{active=false}},[campaign.id,campaign.version]);
 if(error)return <p className="form-error">학습 근거를 불러오지 못했습니다. {error}</p>;
 if(!data)return <p className="learning-meta">학습 근거를 확인하고 있습니다.</p>;
 // 운영자 선호 규칙은 성과 규칙과 따로 센다. 역할 지정 규칙은 그 역할 입력에만 들어간다.
 const available=data.rules.filter(r=>!operatorRule(r)&&ruleApplies(r,campaign.brandId,campaign.channels,undefined,campaign.storeId)),preferences=data.rules.filter(r=>operatorRule(r)&&ruleApplies(r,campaign.brandId,campaign.channels,undefined,campaign.storeId,r.role)),used=data.snapshots.filter(s=>s.campaignId===campaign.id),expiring=campaignExpiring(data.expiringRules??[],campaign);
 // 만료 임박 규칙의 재검증 실험은 학습 화면과 같은 retest_rule로 만든다. 이미 있으면 서버가 기존 실험을 돌려준다.
 async function retest(r:LearningRule){setBusy(true);try{const x=await api('retest_rule',{id:r.id,version:r.version},'/api/learning') as {id:string;duplicate?:boolean};toast.success(x.duplicate?'이미 만든 재검증 실험이 있습니다.':'재검증 실험을 초안으로 만들었습니다.',{action:{label:'실험 보기',onClick:()=>pushNav({view:'learning',brand:campaign.brandId,tab:'experiments'})}})}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <div className="campaign-learning"><h3>제작에 연결되는 학습</h3>{expiring.length>0&&<div className="learning-note" role="status" aria-label="만료 임박 학습 규칙"><b>만료 임박 학습 규칙 {expiring.length}건</b> · 만료되면 이 브랜드의 새 AI 작업에 전달되지 않습니다. 재검증 실험으로 다시 측정하거나 학습 화면에서 연장·종료를 정하세요. <Button size="sm" variant="link" onClick={()=>pushNav({view:'learning',brand:campaign.brandId,tab:'rules'})}>학습 규칙 보기<ArrowUpRight/></Button><ul>{expiring.map(item=><li key={item.rule.id}>{item.rule.title} · {item.rule.channel} · {item.note}{item.retest&&<Button size="sm" variant="link" disabled={busy} onClick={()=>void retest(item.rule)}><FlaskConical/>재검증 실험 만들기</Button>}{item.rule.origin==='store'&&' · 점포 마케팅 화면에서 후속 실험을 만드세요.'}</li>)}</ul></div>}<p>{available.length?`다음 AI 작업에 ${available.length}개 규칙을 전달합니다.`:'현재 브랜드·채널에 적용할 학습 규칙이 없습니다.'}</p>{available.map(r=><details key={r.id}><summary>{r.title} · v{r.version} · 시험 적용</summary><p>{r.guidance}</p></details>)}{preferences.length>0&&<p className="learning-meta">운영자 선호 규칙 {preferences.length}건은 역할 입력에 따로 전달합니다(역할 지정 규칙은 그 역할에만).</p>}{used.length>0&&<details><summary>이 캠페인의 실행 요청에 포함한 근거 · {used.length}회</summary>{used.map(s=><div key={s.id}><b>{s.role} · {date(s.createdAt)}</b>{s.rules.length?s.rules.map(r=><p key={r.id}>{r.title} · v{r.version}<br/>{r.guidance}</p>):<p>당시 적용 가능한 학습 규칙 없음</p>}{s.operatorPreferences?.length?<p>운영자 선호 {s.operatorPreferences.length}건: {s.operatorPreferences.map(r=>r.title+' · v'+r.version).join(', ')}</p>:null}</div>)}</details>}</div>;
}
// 워크스페이스 첫 화면의 만료 임박 학습 규칙 알림(loop-11). 학습 화면을 열지 않아도 규칙이 곧 새 AI 작업에서 빠진다는 것을 알린다.
// 보조 알림이라 불러오지 못하면 표시하지 않는다(학습 화면이 불러오기 오류를 따로 보여 준다). 링크는 가장 먼저 만료되는 규칙의 브랜드를 연다.
export function ExpiringRulesAlert({onOpen}:{onOpen:(brandId:string)=>void}){
 const[rules,setRules]=useState<LearningRule[]>([]);
 useEffect(()=>{let active=true;fetch('/api/learning?only=expiring').then(async r=>{if(!r.ok)return;const d=await r.json() as {expiringRules?:LearningRule[]};if(active)setRules(d.expiringRules??[])}).catch(()=>{/* 보조 알림: 실패하면 숨긴다. */});return()=>{active=false}},[]);
 if(!rules.length)return null;
 const brands=new Set(rules.map(r=>r.brandId)).size;
 return <section className="learning-note" role="status" aria-label="만료 임박 학습 규칙"><b>만료 임박 학습 규칙 {rules.length}건</b>{brands>1?` · ${brands}개 브랜드`:''} · 만료되면 새 AI 작업에 전달되지 않습니다. 재검증 실험으로 다시 측정하거나 연장·종료를 정하세요. <Button size="sm" variant="link" onClick={()=>onOpen(rules[0].brandId)}>학습 규칙 보기<ArrowRight/></Button></section>;
}
