'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {toast} from 'sonner';
import {ArrowUpRight,ArrowRight,Plus,Sparkles,FlaskConical,BookOpen,Play,RefreshCw,Pause,LoaderCircle,Check,Search,Download} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {api,downloadText,type WorkspaceData} from '@/lib/client';
import {learningChannels,learningMetrics,ruleApplies,type LearningData,type ViralCase,type ViralAnalysis,type ViralExperiment,type LearningMetric} from '@/lib/learning';
import type {Campaign} from '@/lib/agency';

const blank:LearningData={cases:[],analyses:[],experiments:[],rules:[],snapshots:[],jobs:[],observations:[],jobOutputs:[]};
const analysisLabels:Record<string,string>={facts:'확인한 사실',hook:'멈춰 본 이유 · 가설',retention:'계속 본 이유 · 가설',sharing:'공유한 이유 · 가설',context:'계정·시점·배포 영향',counterEvidence:'반례와 다른 설명',unknowns:'미확인 · 추가로 필요한 근거'};
const date=(s:string)=>new Date(s).toLocaleString('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const localNow=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const numeric=(s:string)=>s===''?null:Number(s);
const pct=(n:number|null|undefined)=>n===null||n===undefined?'미확인':(n*100).toFixed(2)+'%';
const post=(action:string,payload:Record<string,unknown>={})=>api(action,payload,'/api/learning');
const run=(action:string,payload:Record<string,unknown>={})=>api(action,payload,'/api/learning/run');
function Field({label,children,help}:{label:string;children:React.ReactNode;help?:string}){return <label className="field"><span>{label}</span>{children}{help&&<small>{help}</small>}</label>}
function Empty({title,text}:{title:string;text:string}){return <div className="learning-empty"><FlaskConical size={26}/><h3>{title}</h3><p>{text}</p></div>}
function TextBlock({title,text}:{title:string;text:string}){return <section className="learning-text"><h4>{title}</h4><p>{text}</p></section>}
export function LearningPanel({workspace,onCampaign}:{workspace:WorkspaceData;onCampaign:(id:string)=>void}){
 const[data,setData]=useState<LearningData>(blank),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('cases'),[brandId,setBrand]=useState('ofd'),[query,setQuery]=useState('제품의 첫 장면과 공유 동기가 뚜렷한 최근 바이럴 사례. 비슷한 저성과 사례와 함께 비교.'),[selected,setSelected]=useState<string|null>(null),[modal,setModal]=useState(''),[f,setF]=useState<any>({}),[formError,setFormError]=useState('');
 const current=useRef(data);current.current=data;const polling=useRef(false),mutating=useRef(false),pollCursor=useRef<string|null>(null);
 const reload=useCallback(async()=>{const r=await fetch('/api/learning');const d=await r.json() as LearningData & {error?:string};if(!r.ok)throw new Error(d.error||'학습 데이터를 불러오지 못했습니다.');setData(d);setLoaded(true);setError('');return d as LearningData},[]);
 useEffect(()=>{void reload().catch(e=>setError(e.message));const timer=setInterval(async()=>{if(polling.current||mutating.current)return;const active=current.current.jobs.filter(j=>['queued','in_progress','starting'].includes(j.status));const j=active[(active.findIndex(j=>j.id===pollCursor.current)+1)%active.length];if(!j)return;pollCursor.current=j.id;polling.current=true;try{await run('poll',{id:j.id});await reload()}catch(e){setError((e as Error).message);await reload().catch(()=>{})}finally{polling.current=false}},8000);return()=>clearInterval(timer)},[reload]);
 const set=(k:string,v:any)=>setF((s:any)=>({...s,[k]:v}));
 function open(kind:string,values:any){setModal(kind);setF(values);setFormError('')}
 async function action(fn:()=>Promise<unknown>,message:string){mutating.current=true;setBusy(true);try{await fn();await reload();if(message)toast.success(message)}catch(e){toast.error((e as Error).message)}finally{mutating.current=false;setBusy(false)}}
 const cases=data.cases.filter(c=>c.brandId===brandId),experiments=data.experiments.filter(e=>e.brandId===brandId),rules=data.rules.filter(r=>r.brandId===brandId),c=data.cases.find(x=>x.id===selected),analyses=data.analyses.filter(a=>a.caseId===selected),a=analyses[0];
 const hasHermes=workspace.connection.configured&&workspace.connection.provider==='hermes';
 function addCase(){open('case',{brandId,title:'',channel:'Instagram',url:'',account:'',publishedAt:'',observedAt:localNow(),scope:'',observations:'',transcript:'',views:null,baselineViews:null,comparison:''})}
 function addAnalysis(c:ViralCase){open('analysis',{caseId:c.id,...Object.fromEntries(Object.keys(analysisLabels).map(k=>[k,''])),hypothesis:'',variable:'',control:'',treatment:'',metric:'share_rate'})}
 function addExperiment(a:ViralAnalysis,index:number){const idea=a.ideas[index];open('experiment',{analysisId:a.id,campaignId:workspace.campaigns.find(c=>c.brandId===a.brandId)?.id||'',...idea,title:idea.variable.slice(0,100)+' 실험',minSample:1000,minHours:72,minLift:10,conditions:'동일 채널·타깃·관찰 길이·예산을 유지하고, 계획한 요소 하나만 변경합니다.'})}
 function enterResults(e:ViralExperiment){open('result',{id:e.id,version:e.version,metric:e.metric,control:e.result?.control||{denominator:null,numerator:null,source:''},treatment:e.result?.treatment||{denominator:null,numerator:null,source:''},observedUntil:localNow(),comparable:e.result?.comparable||false,notes:e.result?.notes||''})}
 async function submit(ev:React.FormEvent){ev.preventDefault();setFormError('');setBusy(true);mutating.current=true;try{
  if(modal==='case'){const r=await post('add_case',{data:{...f,observedAt:new Date(f.observedAt).toISOString(),publishedAt:f.publishedAt?new Date(f.publishedAt).toISOString():''}});setSelected(r.id)}
  if(modal==='analysis')await post('save_analysis',{caseId:f.caseId,data:{...f,ideas:[{hypothesis:f.hypothesis,variable:f.variable,control:f.control,treatment:f.treatment,metric:f.metric}]}});
  if(modal==='experiment'){await post('create_experiment',{analysisId:f.analysisId,campaignId:f.campaignId,data:f});setSelected(null);setTab('experiments')}
  if(modal==='result')await post('save_results',{id:f.id,version:f.version,data:{...f,observedUntil:new Date(f.observedUntil).toISOString()}});
  if(modal==='adopt'){await post('adopt_rule',{id:f.id,version:f.version,guidance:f.guidance});setTab('rules')}
  await reload();setModal('');toast.success('저장했습니다.');
 }catch(e){setFormError((e as Error).message)}finally{setBusy(false);mutating.current=false}}
 return <div className="learning-workspace">
  <section className="learning-command"><div className="learning-command-head"><div><span className="learning-kicker">VIRAL LEARNING LAB</span><h2>무엇이 확산을 만들었을까요?</h2><p>성공 이유를 가설로 만들고, 우리 콘텐츠에서 확인합니다.</p></div><Button variant="outline" onClick={addCase} disabled={!loaded||busy}><Plus/>사례 등록</Button></div><div className="learning-search"><NativeSelect aria-label="학습 브랜드" value={brandId} onChange={e=>setBrand(e.target.value)}>{workspace.brands.map(b=><NativeSelectOption key={b.id} value={b.id}>{b.name}</NativeSelectOption>)}</NativeSelect><Input aria-label="조사 주제" value={query} onChange={e=>setQuery(e.target.value)} placeholder="찾고 싶은 콘텐츠와 시장을 적으세요"/><Button className="lime-button" disabled={!loaded||busy||!hasHermes||!query.trim()} onClick={()=>action(()=>run('start_discovery',{brandId,query}),'HERMES에 사례 조사를 요청했습니다.')}><Search/>HERMES로 사례 찾기</Button></div><p className="learning-meta">{hasHermes?'연결된 검색·브라우저 도구로 조사합니다. 접근하지 못한 자료는 미확인으로 남깁니다.':'HERMES 연결 후 조사·분석을 실행할 수 있습니다. 직접 사례와 분석을 등록할 수도 있습니다.'} 예약·상시 수집은 아직 연결되지 않았습니다.</p></section>
  {error&&<div className="learning-error" role="alert">{error}<Button size="sm" variant="outline" onClick={()=>reload().catch(e=>setError(e.message))}><RefreshCw/>다시 확인</Button></div>}
  <div className="learning-stats">{[['01','수집한 사례',cases.length],['02','원인 분석',data.analyses.filter(a=>a.brandId===brandId).length],['03','콘텐츠 실험',experiments.length],['04','적용 중인 규칙',rules.filter(r=>r.status==='active'&&Date.parse(r.expiresAt)>Date.now()).length]].map(([n,label,count])=><div key={n}><span>{n} / {label}</span><strong>{loaded?count:'—'}</strong></div>)}</div>
  <Tabs value={tab} onValueChange={setTab} className="learning-tabs"><TabsList><TabsTrigger value="cases">사례·분석</TabsTrigger><TabsTrigger value="experiments">콘텐츠 실험</TabsTrigger><TabsTrigger value="rules">학습 규칙</TabsTrigger><TabsTrigger value="jobs">실행 기록 {data.jobs.some(j=>['queued','in_progress','starting','uncertain'].includes(j.status))&&'·'}</TabsTrigger></TabsList>
   <TabsContent value="cases">{cases.length?<div className="learning-case-grid">{cases.map(c=>{const n=data.analyses.filter(a=>a.caseId===c.id).length;return <button className="learning-case" key={c.id} onClick={()=>setSelected(c.id)}><div className="learning-card-top"><span>{c.channel}</span><span className="learning-tag">{n?'분석 '+n+'건':'분석 대기'}</span></div><h3>{c.title}</h3><p>{c.observations}</p><div className="learning-case-metrics"><div><small>관찰 조회수</small><b>{c.views===null?'미확인':c.views.toLocaleString()}</b></div><div><small>평소 대비</small><b>{c.baselineViews&&c.views!==null?(c.views/c.baselineViews).toFixed(1)+'배':'비교 자료 필요'}</b></div></div><footer><span>{c.origin==='hermes'?'HERMES 보고':'직접 기록'} · {date(c.observedAt)}</span><ArrowUpRight size={18}/></footer></button>})}</div>:<Empty title="첫 사례에서 학습을 시작하세요" text="게시물 링크와 실제로 확인한 장면·자막·반응을 등록하거나, HERMES에 사례 조사를 맡겨보세요."/>}</TabsContent>
   <TabsContent value="experiments">{experiments.length?<div className="learning-experiments">{experiments.map(e=><section className="learning-experiment" key={e.id}><div className="learning-card-top"><span>{e.channel} · {learningMetrics[e.metric].label}</span><span className={'learning-tag '+(e.assessment?.status==='promising'?'good':'')}>{e.assessment?.label||({draft:'계획 초안',running:'측정 중'} as any)[e.status]}</span></div><h3>{e.title}</h3><p className="learning-hypothesis">{e.hypothesis}</p><div className="learning-ab"><TextBlock title="A · 대조안" text={e.control}/><TextBlock title="B · 실험안" text={e.treatment}/></div><p className="learning-meta">변수: {e.variable} · 각 안 {e.minSample.toLocaleString()} 이상 · {e.minHours}시간 이상 · 상대 개선 {e.minLift}% 이상</p>{e.startedAt&&<p className="learning-meta">시작 {date(e.startedAt)} · 계획 고정 · v{e.version}</p>}{e.assessment&&<div className="learning-assessment"><div><span>A {pct(e.assessment.controlRate)}</span><ArrowRight size={16}/><span>B {pct(e.assessment.treatmentRate)}</span><b>{e.assessment.lift===null?'상대 차이 미확인':(e.assessment.lift>=0?'+':'')+e.assessment.lift.toFixed(1)+'%'}</b></div>{e.assessment.reasons.map(x=><p key={x}>{x}</p>)}<small>집계 지표의 관찰 비교입니다. 통계적 유의성·인과 효과를 확정하지 않습니다.</small></div>}<div className="learning-actions"><Button variant="ghost" onClick={()=>onCampaign(e.campaignId)}>캠페인 열기<ArrowUpRight/></Button>{e.status==='draft'?<Button disabled={busy} onClick={()=>action(()=>post('start_experiment',{id:e.id,version:e.version}),'실험 계획을 고정했습니다. 게시·집행은 별도로 진행하세요.')}><Play/>계획 확정·측정 시작</Button>:<Button variant="outline" disabled={busy} onClick={()=>enterResults(e)}>{e.result?'결과 정정':'결과 입력'}</Button>}{e.assessment&&['promising','not_supported'].includes(e.assessment.status)&&!rules.some(r=>r.experimentId===e.id&&r.experimentVersion===e.version)&&<Button disabled={busy} onClick={()=>open('adopt',{id:e.id,version:e.version,guidance:(e.assessment!.status==='promising'?`시험 적용: ${e.treatment}`:`주의: ${e.variable} 변경에서 개선 가설이 지지되지 않았습니다. ${e.control}을 기준으로 새 변수를 검증하세요.`)+`\n적용 조건: ${e.conditions}\n${learningMetrics[e.metric].label}의 단일 실험 관찰 결과이며 추가 재현이 필요합니다.`})}><BookOpen/>학습에 반영</Button>}</div></section>)}</div>:<Empty title="분석한 이유를 실험으로 확인하세요" text="사례의 분석 결과에서 실험안을 선택하면 A/B 제작안과 측정 기준을 함께 설계할 수 있습니다."/>}</TabsContent>
   <TabsContent value="rules"><p className="learning-note">같은 브랜드·채널의 새 AI 작업에 자동 반영됩니다. 단일 실험에서 얻은 규칙은 시험 적용하며 30일 후 재검토합니다. 결과를 정정하면 기존 규칙 적용은 종료됩니다.</p>{rules.length?<div className="learning-experiments">{rules.map(r=><section className="learning-rule" key={r.id}><div className="learning-card-top"><span>{r.channel} · v{r.version}</span><span className="learning-tag">{r.status==='retired'?'근거 정정 · 적용 종료':r.status==='paused'?'적용 중지':Date.parse(r.expiresAt)<Date.now()?'재검토 필요':'시험 적용 중'}</span></div><h3>{r.title}</h3><p>{r.guidance}</p><footer><span>관찰 근거 · 재검토 {date(r.expiresAt)}</span>{r.status==='active'&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>action(()=>post('pause_rule',{id:r.id,version:r.version}),'다음 작업부터 이 규칙의 적용을 중지합니다.')}><Pause/>적용 중지</Button>}</footer></section>)}</div>:<Empty title="실험 결과가 다음 제작의 기준이 됩니다" text="판정 기준을 충족한 실험에서 학습 규칙을 채택하세요. 잘되지 않았던 방법도 주의사항으로 남길 수 있습니다."/>}</TabsContent>
   <TabsContent value="jobs"><p className="learning-note">접수된 작업은 HERMES에서 실행됩니다. 이 화면을 다시 열면 결과 확인을 이어갑니다. 접수 여부가 불명확하면 기존 요청을 확인해 중복 실행을 방지합니다.</p>{data.jobs.length?<div className="learning-experiments">{data.jobs.map(j=><section className="learning-job" key={j.id}><div><h3>{j.role==='viral_discovery'?'바이럴 사례 조사':'성공 원인 분석'}</h3><p>{date(j.createdAt)} · {({completed:'완료',failed:'확인 필요',cancelled:'중지됨',queued:'대기 중',in_progress:'분석 중',starting:'접수 중',uncertain:'접수 확인 필요'} as any)[j.status]||j.status}</p>{j.error&&<p className="form-error">{j.error}</p>}</div><div className="learning-actions">{['queued','in_progress','starting'].includes(j.status)&&<Button variant="outline" size="sm" disabled={busy} onClick={()=>action(()=>run('poll',{id:j.id}),'')}><RefreshCw/>결과 확인</Button>}{j.status==='uncertain'&&<Button variant="outline" disabled={busy} onClick={()=>action(()=>run('recover',{id:j.id}),'기존 요청의 접수를 확인했습니다.')}>기존 요청 확인</Button>}{['queued','in_progress'].includes(j.status)&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>action(()=>run('cancel',{id:j.id}),'실행 상태를 확인했습니다.')}><Pause/>중지</Button>}{data.jobOutputs.find(o=>o.id===j.id)&&<Button size="sm" variant="ghost" onClick={()=>downloadText('학습-응답.txt',data.jobOutputs.find(o=>o.id===j.id)!.output)}><Download/>원문</Button>}</div></section>)}</div>:<Empty title="조사와 분석의 실행 기록" text="HERMES에 요청한 작업의 진행 상태와 결과가 여기에 남습니다."/>}</TabsContent>
  </Tabs>
  <Dialog open={!!c&&!modal} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="learning-dialog"><DialogHeader><DialogTitle>{c?.title}</DialogTitle><DialogDescription>{c?.channel} · {c?.origin==='hermes'?'HERMES가 보고한 관찰':'직접 기록한 관찰'} · {c&&date(c.observedAt)}</DialogDescription></DialogHeader>{c&&<><a className="learning-source" href={c.url} target="_blank" rel="noopener noreferrer">원본 게시물 열기<ArrowUpRight size={16}/></a><TextBlock title="확인한 범위" text={c.scope}/><TextBlock title="관찰 기록" text={c.observations}/>{c.transcript&&<TextBlock title="자막·장면 메모" text={c.transcript}/>}<TextBlock title="비교 기준" text={c.comparison||'계정의 평소 반응과 유사한 저성과 사례를 추가하면 분석을 보강할 수 있습니다.'}/>{data.observations.filter(o=>o.caseId===c.id).map(o=><TextBlock key={o.id} title={'추가 관찰 · '+date(o.observedAt)} text={o.observations+`\n조회수: ${o.views??'미확인'}`}/>)}<div className="learning-actions"><Button variant="outline" onClick={()=>addAnalysis(c)} disabled={busy}><Plus/>직접 분석 등록</Button><Button className="lime-button" disabled={busy||!hasHermes||data.jobs.some(j=>j.campaignId==='case:'+c.id&&['starting','queued','in_progress','uncertain'].includes(j.status))} onClick={()=>action(()=>run('start_analysis',{caseId:c.id}),'제공된 근거로 HERMES 분석을 시작했습니다.')}><Sparkles/>HERMES 심층 분석</Button></div>{a?<><p className="learning-section-label">원인 분석 · {a.origin==='hermes'?'HERMES':'직접 작성'} · {date(a.createdAt)} · {analyses.length}개 분석 기록</p>{Object.entries(analysisLabels).map(([k,label])=><TextBlock key={k} title={label} text={(a as any)[k]}/>)}{a.ideas.map((idea,i)=><section className="learning-idea" key={i}><span>TEST {i+1} · {learningMetrics[idea.metric].label}</span><h4>{idea.hypothesis}</h4><p>바꿀 요소: {idea.variable}</p><div className="learning-ab"><TextBlock title="A · 대조안" text={idea.control}/><TextBlock title="B · 실험안" text={idea.treatment}/></div><Button onClick={()=>addExperiment(a,i)}><FlaskConical/>이 가설로 실험 설계</Button></section>)}{analyses.length>1&&<Button variant="ghost" onClick={()=>downloadText('바이럴-분석-이력.json',JSON.stringify(analyses,null,2))}><Download/>전체 분석 이력</Button>}</>:<p className="learning-note">첫 장면·시청 지속·공유 동기를 분석하고, 반례와 미확인을 함께 남깁니다. 영상·오디오 원본의 자동 분석은 연결되어 있지 않습니다.</p>}</>}</DialogContent></Dialog>
  <Dialog open={!!modal} onOpenChange={v=>!v&&!busy&&setModal('')}><DialogContent className="learning-dialog"><DialogHeader><DialogTitle>{({case:'바이럴 사례 등록',analysis:'성공 원인 분석',experiment:'콘텐츠 실험 설계',result:'실험 결과 기록',adopt:'다음 제작에 학습 반영'} as any)[modal]}</DialogTitle><DialogDescription>{modal==='experiment'?'변경할 요소와 판정 기준을 먼저 정합니다. 측정 시작 후 계획은 고정됩니다.':modal==='result'?'같은 관찰 길이와 지표 정의로 두 안의 수치를 기록하세요. 미확인은 비워두세요.':modal==='adopt'?'동일 브랜드·채널의 새 작업에 적용하고 30일 후 재검토합니다.':'확인한 내용과 해석을 구분해 저장합니다.'}</DialogDescription></DialogHeader><form className="form-stack" onSubmit={submit}>
   {modal==='case'&&<><div className="form-two"><Field label="사례 이름 *"><Input required value={f.title} onChange={e=>set('title',e.target.value)}/></Field><Field label="채널"><NativeSelect value={f.channel} onChange={e=>set('channel',e.target.value)}>{learningChannels.map(x=><NativeSelectOption key={x}>{x}</NativeSelectOption>)}</NativeSelect></Field></div><Field label="원본 게시물 URL *"><Input required type="url" value={f.url} onChange={e=>set('url',e.target.value)}/></Field><div className="form-two"><Field label="계정"><Input value={f.account} onChange={e=>set('account',e.target.value)}/></Field><Field label="관찰 시점 *"><Input required type="datetime-local" value={f.observedAt} onChange={e=>set('observedAt',e.target.value)}/></Field><Field label="조회수 · 미확인은 비워두기"><Input min="0" type="number" value={f.views??''} onChange={e=>set('views',numeric(e.target.value))}/></Field><Field label="평소 비교 기준 조회수"><Input min="0" type="number" value={f.baselineViews??''} onChange={e=>set('baselineViews',numeric(e.target.value))}/></Field></div><Field label="비교 기준·관찰 길이"><Textarea value={f.comparison} onChange={e=>set('comparison',e.target.value)} placeholder="예: 같은 계정, 같은 형식의 최근 게시물 중앙값. 게시 후 72시간 기준."/></Field><Field label="실제로 확인한 범위 *"><Input required value={f.scope} onChange={e=>set('scope',e.target.value)} placeholder="예: 영상 첫 5초·캡션·공개 댓글 20개"/></Field><Field label="직접 확인한 내용 *"><Textarea required rows={4} value={f.observations} onChange={e=>set('observations',e.target.value)} placeholder="추측과 구분하여 장면·문구·반응을 적으세요."/></Field><Field label="자막·장면·음성 메모"><Textarea rows={4} value={f.transcript} onChange={e=>set('transcript',e.target.value)} placeholder="0–3초: … / 3–8초: … / 마무리: …"/></Field></>}
   {modal==='analysis'&&<>{Object.entries(analysisLabels).map(([k,label])=><Field key={k} label={label+' *'}><Textarea required rows={2} value={f[k]} onChange={e=>set(k,e.target.value)} placeholder={k==='unknowns'?'확인되지 않은 부분을 명시하세요.':undefined}/></Field>)}</>}
   {(modal==='analysis'||modal==='experiment')&&<>{modal==='experiment'&&<><Field label="실험 이름 *"><Input required value={f.title} onChange={e=>set('title',e.target.value)}/></Field><Field label="연결 캠페인 *"><NativeSelect required value={f.campaignId} onChange={e=>set('campaignId',e.target.value)}><NativeSelectOption value="">캠페인 선택</NativeSelectOption>{workspace.campaigns.filter(c=>c.brandId===brandId).map(c=><NativeSelectOption key={c.id} value={c.id}>{c.title}</NativeSelectOption>)}</NativeSelect></Field></>}<Field label="검증할 가설 *"><Textarea required value={f.hypothesis} onChange={e=>set('hypothesis',e.target.value)}/></Field><Field label="바꿀 요소 하나 *"><Input required value={f.variable} onChange={e=>set('variable',e.target.value)} placeholder="예: 첫 3초의 장면"/></Field><div className="form-two"><Field label="A · 대조안 *"><Textarea required rows={5} value={f.control} onChange={e=>set('control',e.target.value)}/></Field><Field label="B · 실험안 *"><Textarea required rows={5} value={f.treatment} onChange={e=>set('treatment',e.target.value)}/></Field></div><Field label="주지표"><NativeSelect value={f.metric} onChange={e=>set('metric',e.target.value)}>{Object.entries(learningMetrics).map(([k,v])=><NativeSelectOption key={k} value={k}>{v.label}</NativeSelectOption>)}</NativeSelect></Field></>}
   {modal==='experiment'&&<><div className="form-two"><Field label="각 안의 최소 분모 *"><Input type="number" min="100" required value={f.minSample} onChange={e=>set('minSample',Number(e.target.value))}/></Field><Field label="최소 관찰 시간 *"><Input type="number" min="1" max="2160" required value={f.minHours} onChange={e=>set('minHours',Number(e.target.value))}/></Field><Field label="목표 상대 개선율 (%) *"><Input type="number" min="0.1" step="0.1" max="1000" required value={f.minLift} onChange={e=>set('minLift',Number(e.target.value))}/></Field></div><Field label="동일 조건·적용 범위 *"><Textarea required rows={3} value={f.conditions} onChange={e=>set('conditions',e.target.value)}/></Field><p className="learning-note">기본 수치는 설계 시작값이며 통계적 검정력을 보장하지 않습니다. 게시·광고 집행은 별도로 진행합니다.</p></>}
   {modal==='result'&&<>{(['control','treatment'] as const).map((key,i)=><section className="learning-result-arm" key={key}><h3>{i===0?'A · 대조안':'B · 실험안'}</h3><div className="form-two"><Field label={learningMetrics[f.metric as LearningMetric].denominator}><Input type="number" min="0" step="1" value={f[key].denominator??''} onChange={e=>set(key,{...f[key],denominator:numeric(e.target.value)})}/></Field><Field label={learningMetrics[f.metric as LearningMetric].numerator}><Input type="number" min="0" step="1" value={f[key].numerator??''} onChange={e=>set(key,{...f[key],numerator:numeric(e.target.value)})}/></Field></div><Field label="수치 출처·조회 기간 *"><Input required value={f[key].source} onChange={e=>set(key,{...f[key],source:e.target.value})} placeholder="예: 자사 계정 인사이트, 게시물 URL, 조회 기간"/></Field></section>)}<Field label="측정 종료 시점 *"><Input type="datetime-local" required value={f.observedUntil} onChange={e=>set('observedUntil',e.target.value)}/></Field><label className="learning-check"><Checkbox checked={f.comparable} onCheckedChange={v=>set('comparable',v===true)}/><span>두 안의 타깃·기간·배포 조건을 비교할 수 있습니다.</span></label><Field label="측정 조건·차이·한계 *"><Textarea required value={f.notes} onChange={e=>set('notes',e.target.value)} placeholder="예산·게시 시점·타깃 차이, 자연 유입과 광고 유입 구분, 측정 한계를 기록하세요."/></Field><p className="learning-note">결과 정정 시 기존 학습 규칙은 적용 종료됩니다. 과거 캠페인에 사용한 근거는 보존합니다.</p></>}
   {modal==='adopt'&&<Field label="직원이 다음 제작에 활용할 규칙 *"><Textarea required rows={9} value={f.guidance} onChange={e=>set('guidance',e.target.value)}/></Field>}
   {formError&&<p role="alert" className="form-error">{formError}</p>}<div className="form-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setModal('')}>취소</Button><Button type="submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Check/>}저장</Button></div>
  </form></DialogContent></Dialog>
 </div>;
}

export function CampaignLearning({campaign}:{campaign:Campaign}){
 const[data,setData]=useState<LearningData|null>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;fetch('/api/learning').then(async r=>{const d=await r.json() as LearningData & {error?:string};if(!r.ok)throw new Error(d.error);if(active)setData(d)}).catch(e=>active&&setError(e.message));return()=>{active=false}},[campaign.id,campaign.version]);
 if(error)return <p className="form-error">학습 근거를 불러오지 못했습니다. {error}</p>;
 if(!data)return <p className="learning-meta">학습 근거를 확인하고 있습니다.</p>;
 const available=data.rules.filter(r=>ruleApplies(r,campaign.brandId,campaign.channels)),used=data.snapshots.filter(s=>s.campaignId===campaign.id);
 return <div className="campaign-learning"><h3>제작에 연결되는 학습</h3><p>{available.length?`다음 AI 작업에 ${available.length}개 규칙을 전달합니다.`:'현재 브랜드·채널에 적용할 학습 규칙이 없습니다.'}</p>{available.map(r=><details key={r.id}><summary>{r.title} · v{r.version} · 시험 적용</summary><p>{r.guidance}</p></details>)}{used.length>0&&<details><summary>이 캠페인의 실행 요청에 포함한 근거 · {used.length}회</summary>{used.map(s=><div key={s.id}><b>{s.role} · {date(s.createdAt)}</b>{s.rules.length?s.rules.map(r=><p key={r.id}>{r.title} · v{r.version}<br/>{r.guidance}</p>):<p>당시 적용 가능한 학습 규칙 없음</p>}</div>)}</details>}</div>;
}
