'use client';
import {askConfirm} from '@/components/app/confirm-dialog';
import {useEffect,useId,useState} from 'react';
import {FileCheck2,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect} from '@/components/ui/native-select';
import {Checkbox} from '@/components/ui/checkbox';
import {copyFromMetaExperiment,metaCreativeFields,type MetaCreativeInput,type MetaCreativeReview} from '@/lib/meta-creative-review';
import s from './meta-insights-panel.module.css';
import {ScreenSkeleton} from '@/components/app/screen-skeleton';
type View={saved:MetaCreativeReview|null;input:MetaCreativeInput;canEdit:boolean;version:number;campaignVersion:number;planVersion:number;landingUrl:string;creatives:{id:string;title:string;current:boolean;caption:string}[];experiments:{id:string;kind:'store'|'viral';title:string;status:string;hypothesis:string;control:string;treatment:string}[];facts:{id:string;key:string;value:string;source:string}[];issues:string[];warnings:string[];notice:string;stale:boolean;reviewValid:boolean};
const errorText=(e:unknown)=>e instanceof Error?e.message:'처리하지 못했습니다.';
export function MetaCreativePanel({campaignId}:{campaignId:string}){
 const id=useId(),[view,setView]=useState<View|null>(null),[input,setInput]=useState<MetaCreativeInput|null>(null),[busy,setBusy]=useState(true),[dirty,setDirty]=useState(false),[ack,setAck]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const a=new AbortController();void fetch('/api/meta-ads/creative?campaignId='+encodeURIComponent(campaignId),{signal:a.signal}).then(async r=>{const v=await r.json() as View & {error?:string};if(!r.ok)throw new Error(v.error||'조회 실패');if(a.signal.aborted)return;setView(v);setInput(v.input);setDirty(false);setAck(false);setError('')}).catch(e=>{if(!a.signal.aborted)setError(errorText(e))}).finally(()=>{if(!a.signal.aborted)setBusy(false)});return()=>a.abort()},[campaignId,retry]);
 function change<K extends keyof MetaCreativeInput>(key:K,value:MetaCreativeInput[K]){setInput(p=>p?{...p,[key]:value}:p);setDirty(true);setAck(false);setSuccess('')}
 async function save(action:'save'|'review'){if(!view||!input)return;setBusy(true);setError('');setSuccess('');try{const r=await fetch('/api/meta-ads/creative',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,campaignId,input,expectedVersion:view.version,campaignVersion:view.campaignVersion,planVersion:view.planVersion,warningsAcknowledged:ack})});const v=await r.json() as View & {error?:string};if(!r.ok)throw new Error(v.error||'저장 실패');setView(v);setInput(v.input);setDirty(false);setAck(false);setSuccess(action==='review'?'소재와 실험의 검토 기록을 저장했습니다. 광고 집행은 승인되지 않았습니다.':'소재안 초안을 저장했습니다.')}catch(e){setError(errorText(e))}finally{setBusy(false)}}
async  function reload(){if(!dirty||await askConfirm({title:'저장하지 않은 소재안 입력을 버리고 다시 불러올까요?',impact:'저장하지 않은 소재안 입력이 사라지고 서버의 최신 소재안으로 바뀝니다.',undo:'버린 입력은 되돌릴 수 없습니다.',confirmLabel:'버리고 불러오기'})){setBusy(true);setSuccess('');setRetry(n=>n+1)}}
 if(!view||!input)return <section className={s.root} aria-label="소재와 실험 검토"><div className={s.empty}>{error?<><p role="alert">{error}</p><Button onClick={reload}>다시 불러오기</Button></>:<ScreenSkeleton label="소재와 근거를 불러오고 있습니다." rows={2}/>}</div></section>;
 const disabled=busy||!view.canEdit,selected=view.experiments.find(e=>e.id===input.experimentId&&e.kind===input.experimentKind);
 return <section className={s.root} aria-label="소재와 실험 검토" aria-busy={busy}><header className={s.header}><div><span className={s.eyebrow}>COLLECTIVE / CREATIVE</span><h2>근거에서 광고 문구까지</h2><p>기존 소재와 시작 전 실험을 연결하고, 사용권과 랜딩을 함께 검토하세요.</p></div><Button variant="outline" disabled={busy} onClick={reload}><RefreshCw size={16}/>다시 불러오기</Button></header>
 <div className={s.workspace}><form className={s.card} onSubmit={e=>{e.preventDefault();void save('save')}}><div className={s.title}><FileCheck2 size={20}/><h3>광고 소재안</h3></div><fieldset disabled={disabled} className={s.fields}><legend className={s.srOnly}>소재안 작성</legend><label htmlFor={id+'creative'}>검토할 소재<NativeSelect id={id+'creative'} value={input.creativeId} onChange={e=>change('creativeId',e.target.value)}><option value="">소재 선택</option>{view.creatives.map(c=><option key={c.id} value={c.id}>{c.title}{c.current?'':' · 근거 재확인 필요'}</option>)}</NativeSelect></label>{!view.creatives.length&&<p className={s.help}>캠페인의 실행 화면에서 확인 사실에 연결된 소재를 먼저 등록하세요.</p>}
 <label htmlFor={id+'experiment'}>시작 전 실험<NativeSelect id={id+'experiment'} value={input.experimentId?input.experimentKind+':'+input.experimentId:''} onChange={e=>{const [kind,...parts]=e.target.value.split(':');setInput(p=>p?{...p,experimentKind:kind==='viral'?'viral':'store',experimentId:parts.join(':')}:p);setDirty(true);setAck(false)}}><option value="">실험 선택</option>{view.experiments.map(e=><option key={e.kind+e.id} value={e.kind+':'+e.id}>{e.title}{e.status==='draft'?'':' · 시작 후'}</option>)}</NativeSelect></label>{!view.experiments.length&&<p className={s.help}>점포 마케팅 또는 바이럴 학습에서 이 캠페인의 실험을 설계하세요.</p>}
 {selected&&<Button type="button" variant="outline" onClick={async()=>{if((input.body||input.hook)&&!(await askConfirm({title:'작성한 문구를 선택한 실험의 처치안으로 바꿀까요?',impact:'지금 입력한 훅·본문이 바뀝니다.',undo:'저장하기 전에는 서버의 소재안이 바뀌지 않습니다. 다시 불러오면 저장된 소재안으로 돌아갑니다.',confirmLabel:'처치안으로 바꾸기'})))return;const copy=copyFromMetaExperiment(selected.treatment);setInput(p=>p?{...p,...copy,title:p.title||selected.title}:p);setDirty(true);setAck(false);setSuccess('실험의 처치안을 가져왔습니다. 근거와 표현을 확인한 뒤 저장하세요.')}}>실험의 처치안에서 문구 가져오기</Button>}
 {(Object.keys(metaCreativeFields) as (keyof typeof metaCreativeFields)[]).map(k=><label key={k} htmlFor={id+k}>{metaCreativeFields[k]}{k==='title'||k==='hook'||k==='cta'?<Input id={id+k} value={input[k]} maxLength={2000} onChange={e=>change(k,e.target.value)}/>:<Textarea id={id+k} value={input[k]} maxLength={k==='script'?6000:2000} rows={k==='script'?5:3} onChange={e=>change(k,e.target.value)}/>}</label>)}
 <div><label><Checkbox checked={input.rightsConfirmed} onCheckedChange={v=>change('rightsConfirmed',v===true)} disabled={disabled}/>파일·음원·출연자 사용권을 확인했습니다</label></div><div><label><Checkbox checked={input.landingConfirmed} onCheckedChange={v=>change('landingConfirmed',v===true)} disabled={disabled}/>문구와 랜딩의 상품·가격·판매 조건이 일치합니다</label></div><Button type="submit">{busy?'처리 중…':'초안 저장'}</Button></fieldset></form>
 <div><div className={s.card}><h3>연결된 근거</h3><p className={s.help}>현재 유효한 확정 사실입니다. 내용이나 유효기간이 바뀌면 검토를 다시 해야 합니다.</p>{view.facts.length?<dl>{view.facts.map(f=><div key={f.id}><dt><b>{f.key}</b></dt><dd>{f.value}<p className={s.help}>{f.source}</p></dd></div>)}</dl>:<p>아직 유효한 확정 사실이 없습니다.</p>}<div className={s.boundary}><b>랜딩 주소</b><p>{view.landingUrl||'실행 준비에서 주소를 입력하세요.'}</p></div>{selected&&<div className={s.boundary}><b>{selected.title}</b><p>{selected.hypothesis}</p><p className={s.help}>대조안: {selected.control||'미입력'}<br/>처치안: {selected.treatment||'미입력'}</p></div>}</div>
 <div className={s.card} style={{marginTop:20}}><h3>{view.reviewValid&&!dirty?'현재 검토 기록이 유효합니다':'검토 전 확인'}</h3>{(view.stale||dirty)&&<p className={s.warning}>{dirty?'작성 중인 입력은 아직 검토되지 않았습니다.':'근거·계획·소재·실험이 변경되어 이전 검토가 유효하지 않습니다.'}</p>}<p className={s.help}>아래 항목은 저장된 소재안 기준입니다.</p>{view.issues.length?<ul>{view.issues.map(issue=><li key={issue}>{issue}</li>)}</ul>:<p>저장된 소재안의 필수 항목을 확인했습니다.</p>}{view.warnings.length>0&&<ul>{view.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul>}<p className={s.help}>{view.notice}</p><label className={s.fields}><Checkbox checked={ack} onCheckedChange={v=>setAck(v===true)} disabled={disabled}/>자동 점검의 경고와 한계를 확인했습니다</label><Button type="button" disabled={disabled||!ack} onClick={()=>void save('review')}>검토 기록 저장</Button><p className={s.help}>검토 기록은 광고 생성·활성화·예산 집행 승인이 아닙니다.</p></div></div></div>{error&&<p role="alert" className={s.error}>{error} 입력은 유지됩니다.</p>}{success&&<p role="status" className={s.success}>{success}</p>}
 </section>;
}
