'use client';
import {EmptyLine} from '@/components/app/empty-line';
import {MetaLine} from '@/components/app/meta-line';
import {useEffect,useId,useState} from 'react';
import {ArrowDownToLine,RefreshCw,ChartNoAxesCombined} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import type {MetaPerformanceReport,MetaPerformanceSnapshot} from '@/lib/meta-performance-report';
import s from './meta-insights-panel.module.css';
type View={report:MetaPerformanceReport;snapshots:MetaPerformanceSnapshot[];version:number;canEdit:boolean;changed:boolean|null;difference:{metaValueMinor:number|null;ledgerRevenue:number|null;attributedRevenue:number|null}|null};
const money=(n:number|null|undefined)=>typeof n==='number'?n.toLocaleString('ko-KR',{maximumFractionDigits:2})+'원':'미확인';
const minor=(n:number|null|undefined)=>typeof n==='number'?money(n/100):'미확인';
const message=(e:unknown)=>e instanceof Error?e.message:'불러오지 못했습니다.';
export function MetaReportPanel({campaignId}:{campaignId:string}){
 const id=useId(),[view,setView]=useState<View|null>(null),[since,setSince]=useState(''),[until,setUntil]=useState(''),[period,setPeriod]=useState({since:'',until:''}),[retry,setRetry]=useState(0),[busy,setBusy]=useState(true),[ack,setAck]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 useEffect(()=>{const a=new AbortController();const q=new URLSearchParams({campaignId,...(period.since&&period.until?period:{})});void fetch('/api/meta-ads/report?'+q,{signal:a.signal}).then(async r=>{const v=await r.json() as View&{error?:string};if(!r.ok)throw new Error(v.error||'조회 실패');if(a.signal.aborted)return;setView(v);setAck(false);setSince(v.report.period.since);setUntil(v.report.period.until);setError('')}).catch(e=>{if(!a.signal.aborted)setError(message(e))}).finally(()=>{if(!a.signal.aborted)setBusy(false)});return()=>a.abort()},[campaignId,period,retry]);
 async function freeze(){if(!view)return;setBusy(true);setError('');try{const r=await fetch('/api/meta-ads/report',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'freeze',campaignId,...view.report.period,expectedVersion:view.version,expectedDigest:view.report.basisDigest,confirmed:ack})});const v=await r.json() as View&{error?:string;duplicate?:boolean};if(!r.ok)throw new Error(v.error||'저장 실패');setView(v);setAck(false);setSuccess(v.duplicate?'같은 근거의 보고가 이미 기록되어 있습니다.':'현재 집계와 한계를 보고 이력에 기록했습니다.')}catch(e){setError(message(e))}finally{setBusy(false)}}
 function download(snapshot:MetaPerformanceSnapshot){const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='collective-meta-report-v'+snapshot.version+'.json';a.click();URL.revokeObjectURL(url)}
 const dirty=!!view&&(since!==view.report.period.since||until!==view.report.period.until),r=view?.report;
 return <section className={s.root} aria-label="광고와 주문 성과 대조" aria-busy={busy}><header className={s.header}><div><span className={s.eyebrow}>성과 근거</span><h2>광고 수치와 실제 주문 사이</h2><p>같은 기간의 자료를 대조하고, 아직 판단할 수 없는 부분을 남깁니다.</p></div><Button variant="outline" disabled={busy} onClick={()=>{setBusy(true);setAck(false);setSuccess('');setRetry(n=>n+1)}}><RefreshCw size={16}/>다시 불러오기</Button></header>
 <form className={s.card} onSubmit={e=>{e.preventDefault();setBusy(true);setAck(false);setSuccess('');setPeriod({since,until})}}><div className={s.columns}><label htmlFor={id+'from'}>시작일<Input id={id+'from'} type="date" required value={since} onChange={e=>{setSince(e.target.value);setAck(false)}}/></label><label htmlFor={id+'to'}>종료일<Input id={id+'to'} type="date" required value={until} onChange={e=>{setUntil(e.target.value);setAck(false)}}/></label></div><Button type="submit" disabled={busy}>기간 적용</Button><p className={s.help}><MetaLine items={['최대 31일','원화','서울 시간','부가세 기준 대조 전']}/></p></form>
 {error&&<p role="alert" className={s.error}>{error}</p>}{success&&<p role="status" className={s.success}>{success}</p>}{dirty&&<p className={s.warning}>아래 수치는 이전 조회 기간 기준입니다. 기간 적용을 눌러 갱신하세요.</p>}
 {r?<><p className={s.caption+' my-5'}><MetaLine items={[`${r.period.since} — ${r.period.until}`,r.stores.map(x=>x.name).join(', ')||'연결된 지점 없음','주문일 기준']}/></p><div className={s.metrics}><div><span>Meta 보고 구매 금액</span><strong>{minor(r.meta?.purchaseValueMinor)}</strong></div><div><span>순매출(주문 장부)</span><strong>{money(r.ledger?.netRevenue)}</strong></div><div><span>캠페인 귀속 매출</span><strong>{money(r.attributed?.netRevenue)}</strong></div><div><span>광고 증분 매출</span><strong>판단 보류</strong></div></div>
 <div className={s.workspace}><div className={s.card}><div className={s.title}><ChartNoAxesCombined size={20}/><h3>숫자의 범위를 확인하세요</h3></div><Table><TableHeader><TableRow><TableHead>자료</TableHead><TableHead>확인한 값</TableHead><TableHead>해석</TableHead></TableRow></TableHeader><TableBody>
 <TableRow><TableCell>Meta 광고비</TableCell><TableCell>{minor(r.meta?.spendMinor)}</TableCell><TableCell>선택한 Meta 캠페인</TableCell></TableRow><TableRow><TableCell>Meta 보고 ROAS</TableCell><TableCell>{r.meta?.reportedRoas==null?'미확인':r.meta.reportedRoas.toFixed(2)+'배'}</TableCell><TableCell>플랫폼 보고 금액 ÷ 광고비</TableCell></TableRow><TableRow><TableCell>장부 유효 주문</TableCell><TableCell>{r.ledger?.orders??'미확인'}</TableCell><TableCell>연결 지점 전체 채널(취소·전액 환불 제외)</TableCell></TableRow><TableRow><TableCell>장부 공헌이익</TableCell><TableCell>{r.ledger?.records?money(r.ledger.contribution):'미확인'}</TableCell><TableCell>환불·주문 변동비 차감, 광고·제작·고정비 차감 전</TableCell></TableRow><TableRow><TableCell>순이익 / 증분 효과</TableCell><TableCell>판단 보류</TableCell><TableCell>비용·귀속·대조군 근거 부족</TableCell></TableRow></TableBody></Table>
 <div className={s.boundary}><b>Meta 자료 기준</b><p>{r.meta?<MetaLine items={[r.meta.source==='manual'?'수동 입력(Meta 검증 없음)':'Meta API 읽기',r.meta.attribution,new Date(r.meta.collectedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})+' KST 수집']}/>:'선택 기간을 포함하는 성과를 먼저 가져오세요.'}</p></div></div><div className={s.card}><h3>지금의 판단: 근거 부족</h3><ul>{r.warnings.map(w=><li key={w}>{w}</li>)}</ul><p className={s.help}>예산 확대·학습 규칙 승격은 이 보고를 보고 운영자가 정합니다.</p></div></div>
 <div className={s.card}><h3>집계 시점 기록</h3><p className={s.caption}>기록 후 환불·주문·광고 성과가 바뀌어도 이전 수치를 보존합니다. 최근 20개 기록을 표시합니다.</p>{view!.changed&&<div className={s.warning}><p>같은 기간의 이전 보고 이후 근거가 변경되었습니다.</p><p><MetaLine items={[`장부 매출 변화 ${money(view!.difference?.ledgerRevenue)}`,`귀속 매출 변화 ${money(view!.difference?.attributedRevenue)}`]}/></p></div>}<label className={s.fields}><Checkbox disabled={busy||dirty||!!error||!view!.canEdit} checked={ack} onCheckedChange={v=>setAck(v===true)}/>집계 범위와 미확인 항목을 확인했습니다</label><Button disabled={busy||dirty||!!error||!view!.canEdit||!ack} disabledReason={dirty?'저장하지 않은 변경이 있습니다. 먼저 저장하세요.':!!error?'오류를 먼저 해결하세요.':(!view!.canEdit)?'보관한 캠페인이거나 변경 권한이 없습니다.':!ack?'확인 칸을 먼저 체크하세요.':undefined} onClick={()=>void freeze()}>현재 보고 기록</Button><Table><TableHeader><TableRow><TableHead>기록</TableHead><TableHead>기간 / 장부 매출</TableHead><TableHead>파일</TableHead></TableRow></TableHeader><TableBody>{view!.snapshots.map(v=><TableRow key={v.id}><TableCell>v{v.version}<small className={s.adId}>{new Date(v.capturedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</small></TableCell><TableCell>{v.report.period.since} — {v.report.period.until}<br/>{money(v.report.ledger?.netRevenue)}</TableCell><TableCell><Button variant="outline" aria-label={'보고 v'+v.version+' 내려받기'} onClick={()=>download(v)}><ArrowDownToLine size={16}/>JSON</Button></TableCell></TableRow>)}</TableBody></Table>{!view!.snapshots.length&&<EmptyLine className={s.empty} next="기간을 고르고 보고를 기록하세요.">아직 기록한 보고가 없습니다.</EmptyLine>}</div></>:!error&&<p role="status" className={s.empty}>광고 성과와 주문 장부를 대조하고 있습니다…</p>}</section>;
}
