'use client';
import {CheckInput} from '@/components/app/check';
import {Note} from '@/components/app/note';
import {useCallback,useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {api} from '@/lib/client';
import type {MetaAdBundleInput} from '@/lib/meta-ad-bundle';
import type {viewMetaAdBundle} from '@/lib/meta-ad-bundle-server';
import {ScreenSkeleton} from '@/components/app/screen-skeleton';
type View=Awaited<ReturnType<typeof viewMetaAdBundle>>;
const blank:MetaAdBundleInput={operationId:'',adsetId:'',creativeId:'',adId:'',pageId:'',pixelId:'',expectedMetaImageHash:'',callToActionType:'LEARN_MORE',dailyBudgetKrw:0,graphDailyBudget:'',budgetUnitEvidence:'',ageMin:18,ageMax:65,country:'KR'};
const labels={adsetId:'Meta 광고세트 ID',creativeId:'Meta 소재 ID',adId:'Meta 광고 ID',pageId:'Facebook 페이지 ID',pixelId:'Meta 픽셀 ID',expectedMetaImageHash:'검토한 Meta 이미지 hash',graphDailyBudget:'Graph daily_budget 원문 정수',budgetUnitEvidence:'원화·Graph 단위 대조 근거'} as const;
export function MetaAdBundlePanel({campaignId}:{campaignId:string}){
 const [data,setData]=useState<View|null>(null),[input,setInput]=useState(blank),[busy,setBusy]=useState(true),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[dirty,setDirty]=useState(false);
 const load=useCallback(async()=>{const r=await fetch('/api/meta-ads/bundle?campaignId='+encodeURIComponent(campaignId)),v=await r.json() as View&{error?:string};if(!r.ok)throw new Error(v.error||'패키지를 불러오지 못했습니다.');setData(v);setInput(v.saved?.input??{...blank,dailyBudgetKrw:v.dailyBudgetKrw??0,operationId:v.parents[0]?.id??''});setDirty(false);setConfirmed(false)},[campaignId]);
 useEffect(()=>{const a=new AbortController();void fetch('/api/meta-ads/bundle?campaignId='+encodeURIComponent(campaignId),{signal:a.signal}).then(async r=>{const v=await r.json() as View&{error?:string};if(!r.ok)throw new Error(v.error||'패키지를 불러오지 못했습니다.');if(!a.signal.aborted){setData(v);setInput(v.saved?.input??{...blank,dailyBudgetKrw:v.dailyBudgetKrw??0,operationId:v.parents[0]?.id??''});setDirty(false);setConfirmed(false);}}).catch(e=>{if(!a.signal.aborted)setError(e.message)}).finally(()=>{if(!a.signal.aborted)setBusy(false)});return()=>a.abort()},[campaignId]);
 async function act(action:'prepare'|'review'|'verify'){if(!data)return;setBusy(true);setError('');try{await api(action,{campaignId,campaignVersion:data.campaignVersion,expectedVersion:data.version,evidenceFingerprint:data.evidenceFingerprint,...(action==='prepare'?{input}:{confirmed})},'/api/meta-ads/bundle');await load()}catch(e){setError((e as Error).message);if(action==='verify')await load().catch(()=>{})}finally{setBusy(false)}}
 function change<K extends keyof MetaAdBundleInput>(key:K,value:MetaAdBundleInput[K]){setInput({...input,[key]:value});setDirty(true);setConfirmed(false)}
 const locked=busy||!data?.canEdit||!data.enabled;
 return <section aria-label="Meta 실행 패키지" className="form-stack"><h3>비활성 광고 실행 패키지</h3><Note className="">Meta에서 마련한 광고세트·단일 이미지 링크 소재·광고의 연결을 검토만 합니다.</Note><p>지원 범위: 대한민국 성인 타깃, 웹사이트 구매 전환, 광고세트 일 예산. 다른 구성은 검증을 통과할 수 없습니다.</p>{error&&<p role="alert">{error}</p>}{!data?<ScreenSkeleton label="패키지를 불러오는 중입니다." rows={2}/>:<>
 {!data.enabled&&<p>소유자가 실행 패키지 기능을 켜야 준비할 수 있습니다.</p>}{data.issues.length>0&&<ul>{data.issues.map(i=><li key={i}>{i}</li>)}</ul>}
 <label className="field"><span>검증된 부모 Meta 캠페인</span><NativeSelect value={input.operationId} disabled={locked} onChange={e=>change('operationId',e.target.value)}><NativeSelectOption value="">선택</NativeSelectOption>{data.parents.map(p=><NativeSelectOption key={p.id} value={p.id}>{p.name} · {p.externalId}</NativeSelectOption>)}</NativeSelect></label>
 <label className="field"><span>원본 이미지 업로드 영수증</span><NativeSelect disabled={locked} value={input.imageUploadReceiptId??''} onChange={e=>change('imageUploadReceiptId',e.target.value)}><NativeSelectOption value="">수동 hash 대조만 사용</NativeSelectOption>{data.imageReceipts.map(r=><NativeSelectOption key={r.id} value={r.id}>{r.metaImageHash}</NativeSelectOption>)}</NativeSelect></label>
 <div className="form-two">{Object.entries(labels).map(([key,label])=><label className="field" key={key}><span>{label}</span><Input disabled={locked} value={input[key as keyof typeof labels]} maxLength={key==='budgetUnitEvidence'?500:100} onChange={e=>change(key as keyof typeof labels,e.target.value)}/></label>)}</div>
 <label className="field"><span>Meta 버튼 유형</span><NativeSelect disabled={locked} value={input.callToActionType} onChange={e=>change('callToActionType',e.target.value as MetaAdBundleInput['callToActionType'])}><NativeSelectOption value="LEARN_MORE">더 알아보기</NativeSelectOption><NativeSelectOption value="SHOP_NOW">구매하기</NativeSelectOption></NativeSelect></label>
 <p>준비 계획 원화 일별 목표: {data.dailyBudgetKrw?.toLocaleString()??'미입력'}원. Graph 예산 값은 원화와 단위가 다른 별도 정수이니 직접 대조하세요.</p><p>대조 랜딩: {data.landingUrl||'미입력'}</p><p>외부 이미지 hash를 대조해도 원본 PNG와 파일 내용이 같다는 검증은 아닙니다. 활성화는 집행·정지 탭에서 승인한 뒤 합니다.</p>
 <div className="form-two">{(['ageMin','ageMax'] as const).map(k=><label className="field" key={k}><span>{k==='ageMin'?'최소 연령':'최대 연령'}</span><Input type="number" min={18} max={65} disabled={locked} value={input[k]} onChange={e=>change(k,Number(e.target.value))}/></label>)}</div>
 <Button disabled={locked||!!data.issues.length} disabledReason={!!data.issues.length?'위에 표시된 문제를 먼저 해결하세요.':undefined} onClick={()=>void act('prepare')}>패키지 준비 저장</Button>
 {data.saved&&<><p>패키지 상태: {data.saved.status} · 판 {data.version}{data.stale?' · 근거 변경, 다시 준비 필요':''}</p><label><CheckInput disabled={locked||dirty} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Meta 소재 이미지·문구·버튼과 검수 원본, 페이지·픽셀·랜딩·타깃·기간, 원화와 Graph 예산 단위를 직접 대조했습니다.</label><div className="form-actions"><Button disabled={locked||dirty||data.stale||!confirmed} disabledReason={dirty?'저장하지 않은 변경이 있습니다. 먼저 저장하세요.':data.stale?'다른 곳에서 먼저 바뀌었습니다. 최신 기록을 불러온 뒤 다시 하세요.':!confirmed?'확인 칸을 먼저 체크하세요.':undefined} onClick={()=>void act('review')}>패키지 검토 기록</Button><Button disabled={locked||dirty||data.stale||!confirmed||data.saved.status==='prepared'} disabledReason={dirty?'저장하지 않은 변경이 있습니다. 먼저 저장하세요.':data.stale?'다른 곳에서 먼저 바뀌었습니다. 최신 기록을 불러온 뒤 다시 하세요.':!confirmed?'확인 칸을 먼저 체크하세요.':(data.saved.status==='prepared')?'이미 준비했습니다.':undefined} onClick={()=>void act('verify')}>외부 비활성 구성 조회</Button></div>{data.verifiedScope?<p>마지막 외부 확인: {data.verifiedScope.verifiedAt}. 현재까지 계속 비활성이라는 보증은 아니며, 이 확인은 15분 동안만 후속 승인 근거로 참조됩니다.</p>:<p>현재 유효한 외부 확인이 없습니다. 검토 후 다시 조회하세요.</p>}</>}
 </>}</section>;
}
