'use client';
import {EmptyLine} from '@/components/app/empty-line';
import {Note} from '@/components/app/note';
import {askConfirm} from '@/components/app/confirm-dialog';
import {useEffect,useId,useState} from 'react';
import {Pause,RefreshCw,KeyRound} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import type {PausedCampaignReceipt} from '@/lib/meta-paused-campaign';
import s from './meta-insights-panel.module.css';
import {ScreenSkeleton} from '@/components/app/screen-skeleton';
type View={campaignVersion:number;enabled:boolean;connection:{accountId:string;version:number;updatedAt:string}|null;issues:string[];evidenceFingerprint:string;operations:{id:string;name:string;accountId:string;receipt:PausedCampaignReceipt;createdAt:string;version:number;stale:boolean}[];canEdit:boolean};
const labels={prepared:'전송 전',sending:'전송 결과 확인 필요',unknown:'생성 결과 확인 필요',paused_verified:'PAUSED 확인 기록'};
const message=(e:unknown)=>e instanceof Error?e.message:'처리하지 못했습니다.';
export function MetaPausedPanel({campaignId}:{campaignId:string}){
 const id=useId(),[view,setView]=useState<View|null>(null),[retry,setRetry]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[account,setAccount]=useState(''),[token,setToken]=useState(''),[consent,setConsent]=useState(false),[name,setName]=useState(''),[category,setCategory]=useState(false),[external,setExternal]=useState<Record<string,string>>({});
 useEffect(()=>{const a=new AbortController();void fetch('/api/meta-ads/paused?campaignId='+encodeURIComponent(campaignId),{signal:a.signal}).then(async r=>{const v=await r.json() as View&{error?:string};if(!r.ok)throw new Error(v.error||'조회 실패');if(a.signal.aborted)return;setView(v);setAccount(v.connection?.accountId??'');setError('')}).catch(e=>{if(!a.signal.aborted)setError(message(e))});return()=>a.abort()},[campaignId,retry]);
 async function action(action:string,extra:Record<string,unknown>={}){if(!view)return;setBusy(true);setError('');setSuccess('');try{const r=await fetch('/api/meta-ads/paused',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,campaignId,campaignVersion:view.campaignVersion,evidenceFingerprint:view.evidenceFingerprint,connectionVersion:view.connection?.version??0,...extra})});const v=await r.json() as View&{error?:string};if(!r.ok)throw new Error(v.error||'처리 실패');setView(v);if(action==='connect'){setToken('');setConsent(false)}setSuccess(action==='prepare'?'전송 전 준비 기록을 저장했습니다. 아직 Meta에 생성하지 않았습니다.':action==='create'?'Meta 캠페인을 생성하고 PAUSED 상태를 확인했습니다. 광고는 집행되지 않습니다.':action==='reconcile'?'외부 캠페인의 PAUSED 상태를 확인했습니다.':action==='disconnect'?'쓰기 연결을 해제했습니다. 생성 이력과 읽기 연결은 유지됩니다.':'별도 쓰기 연결을 확인했습니다.')}catch(e){setError(message(e));try{const r=await fetch('/api/meta-ads/paused?campaignId='+encodeURIComponent(campaignId));if(r.ok)setView(await r.json() as View)}catch{/* Keep user input. */}}finally{setBusy(false)}}
 if(!view)return <section className={s.root} aria-label="Meta 비활성 초안"><div className={s.empty}>{error?<><p role="alert">{error}</p><Button onClick={()=>setRetry(n=>n+1)}>다시 불러오기</Button></>:<ScreenSkeleton label="비활성 초안 상태를 불러오고 있습니다." rows={2}/>}</div></section>;
 const disabled=busy||!view.canEdit;
 return <section className={s.root} aria-label="Meta 비활성 초안" aria-busy={busy}><header className={s.header}><div><span className={s.eyebrow}>비활성 초안</span><h2>집행 전에, 비활성 초안으로</h2><p>검토한 계획을 Meta 판매 캠페인에 연결합니다. 생성 후 외부 비활성 상태까지 확인합니다.</p></div><Button variant="outline" disabled={busy} onClick={()=>setRetry(n=>n+1)}><RefreshCw size={16}/>다시 불러오기</Button></header>
 {!view.enabled&&<p className={s.warning}>현재 비활성 초안 생성이 꺼져 있습니다. 소유자가 기능 설정에서 켠 뒤 별도 쓰기 권한을 연결할 수 있습니다.</p>}{!view.canEdit&&<p className={s.help}>외부 계정 연결과 생성은 워크스페이스 소유자만 할 수 있습니다.</p>}
 <div className={s.workspace}><div className={s.card}><div className={s.title}><Pause size={20}/><h3>전송할 판매 캠페인</h3></div><form onSubmit={e=>{e.preventDefault();void action('prepare',{name,specialCategoryReview:category?'not_applicable':'unknown'})}}><fieldset className={s.fields} disabled={disabled||view.issues.length>0}><legend className={s.srOnly}>비활성 캠페인 준비</legend><label htmlFor={id+'name'}>Meta 캠페인 이름<Input id={id+'name'} value={name} maxLength={120} required onChange={e=>setName(e.target.value)}/></label><label><Checkbox checked={category} onCheckedChange={v=>setCategory(v===true)}/>특별 광고 범주에 해당하지 않는 상품·서비스임을 검토했습니다</label><p className={s.help}>특별 광고 범주에 해당하거나 판단하지 못한 경우 이 경로로 생성할 수 없습니다.</p><Button type="submit" disabled={!category} disabledReason={!category?'필수 칸을 먼저 채우세요.':undefined}>전송 전 준비 기록</Button></fieldset></form><div className={s.boundary}><b>이 단계에서 만드는 것</b><p>예산이 없는 PAUSED 판매 캠페인 하나입니다. 광고세트·소재·광고는 아직 만들지 않습니다. 예산 승인과 활성화는 별도 단계입니다.</p></div></div>
 <div className={s.card}><div className={s.title}><KeyRound size={20}/><h3>별도 쓰기 연결</h3></div>{view.connection&&<><span className={s.connected}>쓰기 권한 확인</span><p className={s.account}>계정 {view.connection.accountId}</p><Button variant="outline" disabled={disabled} onClick={()=>void action('disconnect')}>쓰기 연결 해제</Button></>}<form onSubmit={e=>{e.preventDefault();void action('connect',{accountId:account,token,allowPausedCreation:consent})}}><fieldset className={s.fields} disabled={disabled||!view.enabled}><legend className={s.srOnly}>별도 쓰기 계정 연결</legend><label htmlFor={id+'account'}>광고 계정 ID<Input id={id+'account'} inputMode="numeric" value={account} required onChange={e=>{setAccount(e.target.value);setConsent(false)}}/></label><label htmlFor={id+'token'}>Meta 쓰기 권한 토큰<Input id={id+'token'} type="password" autoComplete="off" value={token} required maxLength={4096} onChange={e=>{setToken(e.target.value);setConsent(false)}}/></label><p className={s.help}>같은 브랜드의 읽기 연결이 먼저 필요합니다. ads_management 권한을 확인하고 토큰을 암호화해 별도로 저장합니다.</p><label><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/>비활성 초안 생성을 위한 별도 쓰기 연결에 동의합니다</label><Button type="submit" variant="outline" disabled={!consent} disabledReason={!consent?'동의 확인을 먼저 체크하세요.':undefined}>{view.connection?'쓰기 연결 갱신':'쓰기 권한 연결'}</Button></fieldset></form></div></div>
 {view.issues.length>0&&<div className={s.card}><h3>생성 전 확인할 항목</h3><ul>{view.issues.map(v=><li key={v}>{v}</li>)}</ul></div>}
 {error&&<p role="alert" className={s.error}>{error} 전송 기록과 입력은 유지됩니다.</p>}{success&&<p role="status" className={s.success}>{success}</p>}
 <div className={s.results}><h3>생성 작업 기록</h3><Note className={s.caption}>결과를 확인하지 못한 작업은 자동 재전송하지 않습니다. 외부 ID가 없으면 Meta에서 작업 식별자가 붙은 이름을 확인하세요.</Note>{view.operations.length?view.operations.map(op=><article className={s.card+' mb-4'} key={op.id}><div className={s.title}><h3>{op.name}</h3><span>{labels[op.receipt.state]}</span></div><p>계정 {op.accountId} · 외부 캠페인 {op.receipt.externalId||'미확인'}</p><p className={s.help+' wrap-anywhere'}>작업 식별자 {op.id}</p>{op.stale&&<p className={s.warning}>준비 후 계획·검수·연결이 바뀌었습니다. 이 준비 기록으로 새 전송을 할 수 없습니다.</p>}{op.receipt.state==='prepared'&&<Button disabled={disabled||op.stale||view.issues.length>0} disabledReason={op.stale?'다른 곳에서 먼저 바뀌었습니다. 최신 기록을 불러온 뒤 다시 하세요.':(view.issues.length>0)?'위에 표시된 문제를 먼저 해결하세요.':undefined} onClick={async()=>{if(await askConfirm({title:'Meta에 예산 없는 PAUSED 판매 캠페인 하나를 실제 생성할까요?',impact:'광고는 집행하지 않습니다.',undo:'앱에는 만든 캠페인을 지우는 기능이 없습니다. 필요하면 Meta 광고 관리자에서 직접 삭제하세요.',confirmLabel:'PAUSED 캠페인 생성'}))void action('create',{operationId:op.id,confirmed:true})}}>Meta에 비활성 캠페인 생성</Button>}{['sending','unknown','paused_verified'].includes(op.receipt.state)&&<div className={s.fields}>{!op.receipt.externalId&&<label htmlFor={id+op.id}>직접 확인한 외부 캠페인 ID<Input id={id+op.id} inputMode="numeric" value={external[op.id]??''} onChange={e=>setExternal(p=>({...p,[op.id]:e.target.value}))}/></label>}<Button variant="outline" disabled={disabled||!view.connection||(!op.receipt.externalId&&!external[op.id])} disabledReason={!view.connection?'Meta 연결을 먼저 하세요.':!op.receipt.externalId&&!external[op.id]?'외부 캠페인 ID를 먼저 넣으세요.':undefined} onClick={()=>void action('reconcile',{operationId:op.id,externalId:external[op.id],confirmed:true})}>외부 PAUSED 상태 다시 확인</Button></div>}{op.receipt.verifiedAt&&<p className={s.help}>{new Date(op.receipt.verifiedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} KST 상태 확인 · 이후 외부 변경은 다시 확인해야 합니다.</p>}</article>):<EmptyLine className={s.empty} next="위에서 생성 준비를 기록하세요.">아직 생성 준비 기록이 없습니다.</EmptyLine>}</div></section>;
}
