'use client';
import {CheckInput} from '@/components/app/check';
import {askConfirm,askInput} from '@/components/app/confirm-dialog';
import {dateTime} from '@/lib/format';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import type {viewMetaExecution} from '@/lib/meta-execution-server';
import type {metaReservationView} from '@/lib/meta-reservation-server';
import s from './meta-insights-panel.module.css';
type View=Awaited<ReturnType<typeof viewMetaExecution>>;
export function MetaExecutionPanel({campaignId}:{campaignId:string}){
 const [view,setView]=useState<View|null>(null),[reservations,setReservations]=useState<Awaited<ReturnType<typeof metaReservationView>>|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[maxSpend,setMaxSpend]=useState(''),[expiry,setExpiry]=useState(''),[confirmed,setConfirmed]=useState(false),[reload,setReload]=useState(0);
 useEffect(()=>{const a=new AbortController();setBusy(true);Promise.all(['/api/meta-ads/execution','/api/meta-ads/reservations'].map(async path=>{const r=await fetch(path+'?campaignId='+encodeURIComponent(campaignId),{signal:a.signal}),v=await r.json() as View&Awaited<ReturnType<typeof metaReservationView>>&{error?:string};if(!r.ok)throw new Error(v.error||'조회 실패');return v})).then(([v,r])=>{if(!a.signal.aborted){setView(v);setReservations(r);setError('');setConfirmed(false)}}).catch(e=>{if(!a.signal.aborted)setError(e instanceof Error?e.message:'조회 실패')}).finally(()=>{if(!a.signal.aborted)setBusy(false)});return()=>a.abort()},[campaignId,reload]);
 async function action(action:string,extra:Record<string,unknown>={}){if(!view)return;setBusy(true);setError('');try{const r=await fetch('/api/meta-ads/execution',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,campaignId,campaignVersion:view.campaignVersion,confirmed:true,...extra})}),v=await r.json() as View&Awaited<ReturnType<typeof metaReservationView>>&{error?:string};if(!r.ok)throw new Error(v.error||'실행 요청 실패');setView(v);setConfirmed(false)}catch(e){setError(e instanceof Error?e.message:'실행 요청 실패')}finally{setBusy(false)}}
 const reserved=reservations?.records.find(r=>r.state==='reserved');
 return <section className={s.root} aria-label="Meta 광고 실행" aria-busy={busy}><header className={s.header}><div><h2>승인한 광고 실행과 비상 중단</h2><p>원본 업로드·예산 예약·최신 외부 구성을 묶어 별도 승인합니다.</p></div><Button variant="outline" disabled={busy} onClick={()=>setReload(n=>n+1)}>다시 불러오기</Button></header>{error&&<p role="alert">{error}</p>}{view&&<><p>{view.notice}</p><p>실행 기능 {view.enabled?'켜짐':'꺼짐'} · 감시 워커 {view.workerOnline?'온라인':'오프라인'} · 지출 가능성 {view.maySpend?'있음':'없음'}</p><form onSubmit={e=>{e.preventDefault();if(reserved)void action('approve',{reservationId:reserved.id,reservationVersion:reserved.version,expectedScopeDigest:reservations?.scopeDigest,maxSpend:Number(maxSpend),expiresAt:new Date(expiry).toISOString(),emergencyStopMandate:confirmed})}}><fieldset disabled={busy||!view.canEdit||!view.enabled||!view.workerOnline||!reserved}><legend>실행 승인</legend><label>최대 집행액 (원)<Input type="number" min="1" step="1" value={maxSpend} required onChange={e=>{setMaxSpend(e.target.value);setConfirmed(false)}}/></label><label>승인 만료 시각<Input type="datetime-local" value={expiry} required onChange={e=>{setExpiry(e.target.value);setConfirmed(false)}}/></label><label><CheckInput checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>예약 범위·손실 한도와 기한을 확인했으며 한도·오류·만료 시 비상 중단을 위임합니다</label><Button type="submit" disabled={!confirmed}>실행 범위 승인</Button></fieldset></form>{view.records.map(e=><article className={s.card} key={e.id}><h3>{e.state} · 최대 {e.maxSpend.toLocaleString()}원</h3><p>일일 {e.dailyTarget.toLocaleString()}원 · 손실 중단 {e.lossLimit.toLocaleString()}원 · 누적 {e.totalSpend??'미확인'}원</p><p>승인 만료 {dateTime(e.expiresAt)} · {e.stopReason}</p>{e.state==='approved'&&<Button disabled={busy||!view.canEdit||!view.enabled} onClick={async()=>{if(await askConfirm({title:'승인한 범위를 지금 실행할까요?',impact:'광고를 활성화하면 실제 광고비가 발생할 수 있습니다.',undo:'같은 화면의 비상 중단으로 멈출 수 있습니다. 이미 쓴 광고비는 되돌릴 수 없습니다.',confirmLabel:'광고 활성화',danger:true}))void action('activate',{id:e.id,expectedVersion:e.version})}}>승인한 광고 활성화</Button>}{!['settled','revoked'].includes(e.state)&&<Button disabled={busy||!view.canEdit} variant="outline" onClick={()=>void action('stop',{id:e.id,expectedVersion:e.version})}>비상 중단 / 승인 철회</Button>}{e.state==='stopped'&&<Button disabled={busy||!view.canEdit} variant="outline" onClick={async()=>{const value=await askInput({title:'최종 청구 금액을 기록할까요?',body:'Meta의 최종 청구 내역을 대조한 원화 금액을 입력하세요. 집계 지연 중이면 취소하세요.',impact:'지연된 청구까지 확인하여 최종 대조를 마쳤을 때만 기록하세요.',undo:'기록한 최종 대조는 되돌리지 않습니다.',input:{label:'최종 청구 금액(원)',type:'number'},confirmLabel:'최종 대조 기록'});if(value!==null&&value.trim())void action('settle',{id:e.id,expectedVersion:e.version,settledSpend:Number(value),billingFinalConfirmed:true})}}>최종 광고비 대조</Button>}</article>)}</>}</section>
}
