'use client';
import {useEffect,useId,useState} from 'react';
import {Download,FileSpreadsheet,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {StorefrontWebhookPanel} from './storefront-webhook-panel';
import {storefrontTemplate} from '@/lib/storefront-orders';
import {recentPeriod,type StoreOrder,type ledgerSummary} from '@/lib/store-operations';
import s from './storefront-orders-panel.module.css';
import {ScreenSkeleton} from '@/components/app/screen-skeleton';
type View={storeName:string;canEdit:boolean;linkedOrders:number;sources:string[];from:string;to:string;summary:ReturnType<typeof ledgerSummary>;orders:StoreOrder[]};
type Preview={previewKey:string;created:number;updated:number;duplicates:number;older:number;outcomes:{externalId:string;action:string;netRevenue:number}[]};
const actionLabel:Record<string,string>={create:'새 주문',update:'상태 갱신',duplicate:'같은 내용',older:'이전 상태 · 건너뜀'};
const message=(e:unknown)=>e instanceof Error?e.message:'처리하지 못했습니다.';
export function StorefrontOrdersPanel({campaignId}:{campaignId:string}){
 const id=useId(),[storeId,setStoreId]=useState<string|null>(null),[resolved,setResolved]=useState(false),[view,setView]=useState<View|null>(null),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0),[sourceKey,setSourceKey]=useState(''),[csv,setCsv]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[period,setPeriod]=useState(recentPeriod);
 useEffect(()=>{const a=new AbortController();void fetch('/api/meta-ads?campaignId='+encodeURIComponent(campaignId),{signal:a.signal}).then(async r=>{const v=await r.json() as {error?:string;links:{storeId:string|null}};if(!r.ok)throw new Error(v.error||'캠페인 조회 실패');setStoreId(v.links.storeId);setResolved(true)}).catch(e=>{if(!a.signal.aborted)setError(message(e))});return()=>a.abort()},[campaignId,retry]);
 useEffect(()=>{if(!storeId)return;const a=new AbortController();void fetch('/api/storefront-orders?'+new URLSearchParams({storeId,from:period.from,to:period.to}),{signal:a.signal}).then(async r=>{const v=await r.json() as View & {error?:string};if(!r.ok)throw new Error(v.error||'장부 조회 실패');setView(v);setError('')}).catch(e=>{if(!a.signal.aborted)setError(message(e))});return()=>a.abort()},[storeId,period.from,period.to,retry]);
 async function send(action:'preview'|'import'){if(!storeId)return;setBusy(true);setError('');setSuccess('');try{const r=await fetch('/api/storefront-orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,storeId,sourceKey,csv,previewKey:preview?.previewKey})});const v=await r.json() as Preview & {error?:string};if(!r.ok)throw new Error(v.error||'가져오기 실패');if(action==='preview')setPreview(v);else{setPreview(null);setSuccess(`새 주문 ${v.created}건 · 갱신 ${v.updated}건 · 중복 ${v.duplicates}건 · 이전 상태 ${v.older}건. 중복과 이전 상태는 장부에 더하지 않았습니다.`);setRetry(n=>n+1)}}catch(e){setError(message(e));setPreview(null)}finally{setBusy(false)}}
 function download(){const u=URL.createObjectURL(new Blob(['\uFEFF'+storefrontTemplate],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='collective-storefront-orders.csv';a.click();URL.revokeObjectURL(u)}
 if(!resolved||!storeId||!view)return <section className={s.root} aria-label="주문 대조"><div className={s.empty}><FileSpreadsheet size={28}/>{error?<><p role="alert">{error}</p><Button onClick={()=>setRetry(n=>n+1)}>다시 불러오기</Button></>:resolved&&!storeId?<><h3>주문을 기록할 지점을 연결하세요</h3><p>캠페인 설정에서 같은 브랜드의 지점을 연결하면, 기존 주문 장부에 자사몰 주문과 환불을 반영할 수 있습니다.</p></>:<ScreenSkeleton label="주문 장부를 불러오고 있습니다." rows={2}/>}</div></section>;
 const total=view.summary;
 return <section className={s.root} aria-label="주문 대조" aria-busy={busy}><header className={s.header}><div><span className={s.eyebrow}>COLLECTIVE / ORDERS</span><h2>판매 이후까지 확인하세요</h2><p>{view.storeName}의 주문과 환불을 기존 장부에 반영합니다.</p></div><Button variant="outline" disabled={busy} onClick={()=>setRetry(n=>n+1)}><RefreshCw size={16}/>새로고침</Button></header>
 <div className={s.period}><label htmlFor={id+'from'}>조회 시작일<Input id={id+'from'} type="date" value={period.from} onChange={e=>setPeriod(p=>({...p,from:e.target.value}))}/></label><label htmlFor={id+'to'}>조회 종료일<Input id={id+'to'} type="date" value={period.to} onChange={e=>setPeriod(p=>({...p,to:e.target.value}))}/></label></div>
 <div className={s.metrics}><div><span>장부 순매출</span><strong>{total.netRevenue.toLocaleString()}원</strong></div><div><span>유효 주문</span><strong>{total.orders.toLocaleString()}건</strong></div><div><span>취소 · 전액 환불</span><strong>{total.cancelled+total.refunded}건</strong></div></div><p className={s.caption}>{view.from} — {view.to} 지점 전체 채널 장부입니다. 누락된 주문이 있을 수 있으며, Meta 광고에 귀속된 매출이나 광고의 증분 효과를 뜻하지 않습니다.</p>
 <div className={s.workspace}><form className={s.card} onSubmit={e=>{e.preventDefault();void send('preview')}}><h3>자사몰 주문 가져오기</h3><fieldset disabled={busy||!view.canEdit} className={s.fields}><legend className={s.srOnly}>주문 파일 선택</legend><label htmlFor={id+'source'}>몰 식별자<Input id={id+'source'} aria-label="몰 식별자" value={sourceKey} onChange={e=>{setSourceKey(e.target.value);setPreview(null)}} placeholder="예: brand-store" pattern="[a-z0-9][a-z0-9_-]{1,39}" required/><span>같은 몰은 항상 같은 영문 식별자를 사용하세요.</span></label><div className={s.fileHeading}><b>주문 CSV</b><Button type="button" variant="ghost" size="sm" onClick={download}><Download size={15}/>양식 받기</Button></div><Input type="file" aria-label="자사몰 주문 CSV" accept=".csv,text/csv" onChange={async e=>{setCsv('');setPreview(null);const f=e.target.files?.[0];if(!f)return;if(f.size>150000){setError('파일은 150KB 이하로 나누어 주세요.');return}try{setCsv(await f.text());setError('')}catch{setError('파일을 읽지 못했습니다.')}}}/><p className={s.caption}>최대 100개 주문. 이름·전화번호·주소·이메일은 포함하지 않습니다.</p><Button type="submit" disabled={!csv}>장부에 반영할 내용 확인</Button></fieldset>
 {preview&&<div className={s.preview}><b>반영 전 확인</b><p>새 주문 {preview.created} · 갱신 {preview.updated} · 중복 {preview.duplicates} · 이전 상태 {preview.older}</p><Table><TableHeader><TableRow><TableHead>주문 ID</TableHead><TableHead>처리</TableHead><TableHead>환불 후 금액</TableHead></TableRow></TableHeader><TableBody>{preview.outcomes.map(x=><TableRow key={x.externalId}><TableCell>{x.externalId}</TableCell><TableCell>{actionLabel[x.action]}</TableCell><TableCell>{x.netRevenue.toLocaleString()}원</TableCell></TableRow>)}</TableBody></Table><Button type="button" disabled={busy||!view.canEdit} onClick={()=>void send('import')}>확인한 주문 장부에 반영</Button></div>}</form>
 <div className={s.guide}><h3>변경 순서와 환불 기준</h3><ol><li><b>주문 ID는 유지합니다.</b><p>결제와 환불은 같은 주문에 기록합니다.</p></li><li><b>변경될 때마다 순서를 높입니다.</b><p>revision은 1, 2, 3처럼 증가합니다. 뒤늦게 받은 낮은 번호는 건너뜁니다.</p></li><li><b>환불액은 누적 금액입니다.</b><p>3,000원 환불 후 2,000원을 더 환불했다면 5,000원을 입력합니다.</p></li></ol><details><summary>양식 값 확인</summary><p>status: paid(결제·부분 환불), refunded(전액 환불), cancelled(취소). mode: delivery(배송·배달), pickup(픽업), hall(매장), group(단체). order_date는 최초 주문일입니다.</p></details><p className={s.caption}>연결된 외부 주문 {view.linkedOrders}건 · 고객 전환 전송 꺼짐</p></div></div>
 {error&&<p className={s.error} role="alert">{error} 입력 파일은 유지됩니다.</p>}{success&&<p className={s.success} role="status">{success}</p>}
 <StorefrontWebhookPanel key={storeId} storeId={storeId}/><div className={s.results}><h3>최근 장부 기록</h3><Table><TableHeader><TableRow><TableHead>주문일 / 번호</TableHead><TableHead>결제액</TableHead><TableHead>누적 환불</TableHead><TableHead>상태</TableHead></TableRow></TableHeader><TableBody>{view.orders.map(o=><TableRow key={o.id}><TableCell>{o.orderDate}<small>{o.orderNumber}</small></TableCell><TableCell>{o.paidAmount.toLocaleString()}원</TableCell><TableCell>{o.refundAmount.toLocaleString()}원</TableCell><TableCell>{o.status==='paid'?'결제·부분 환불':o.status==='refunded'?'전액 환불':'취소'}</TableCell></TableRow>)}</TableBody></Table>{!view.orders.length&&<p className={s.empty}>선택 기간에 기록된 주문이 없습니다.</p>}<p className={s.caption}>최근 50건 표시 · 요약은 선택 기간의 전체 장부 기준입니다.</p></div>
 </section>;
}
