'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {toast} from 'sonner';
import {Plus,MapPin,ArrowUpRight,Search,RefreshCw,Check,LoaderCircle,FileText,FlaskConical,ExternalLink,Pencil} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {api,clientId,type WorkspaceData} from '@/lib/client';
import {money,type Brand} from '@/lib/agency';
import {researchActive,researchStages} from '@/lib/archive';
import {channelCatalog,checkStates,tradeAreas,storeFields,storeMetricFields,experimentStates,decisions,storeMetrics,storeReadiness,type Store,type StoreChannel,type StoreData,type StoreExperiment,type StoreMeasurement,type StoreReport,type StoreTask} from '@/lib/store-marketing';
import {StoreDiagnosticPanel,StoreLedgerPanel,LedgerMeasurementDialog} from './store-operations-panel';
const empty:StoreData={stores:[],channels:[],experiments:[],measurements:[],reports:[],tasks:[],research:[],sources:[]};
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Seoul'});
const channelName=(key:string)=>channelCatalog.find(c=>c.key===key)?.name||key;
const post=(action:string,data:Record<string,unknown>)=>api(action,data,'/api/stores');
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="store-field"><span>{label}</span>{children}</label>}
function Blank({children}:{children:React.ReactNode}){return <div className="store-empty">{children}</div>}
// 브랜드·지점은 주소(?brand=&store=)와 연결한다. initialStoreId는 주소의 지점이고, 고른 브랜드·지점은 onScopeChange로 알린다.
// 자동으로 고른 첫 활성 지점과 주소의 없는 지점을 고친 경우는 replace로 알려 방문 기록을 늘리지 않는다.
export function StoreMarketingPanel({workspace,initialBrandId,initialStoreId,onScopeChange,onOpenCampaign,onArchive}:{workspace:WorkspaceData;initialBrandId?:string;initialStoreId?:string;onScopeChange?:(brandId:string,storeId:string,replace:boolean)=>void;onOpenCampaign:(id:string)=>Promise<void>;onArchive:(id:string)=>void}){
 const [brandId,setBrandId]=useState(initialBrandId||'all'),[storeId,setStoreId]=useState(''),[data,setData]=useState<StoreData>(empty),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[tab,setTab]=useState('diagnosis');
 const [storeDialog,setStoreDialog]=useState<Store|'new'|null>(null),[channelDialog,setChannelDialog]=useState<string|null>(null),[experimentDialog,setExperimentDialog]=useState<Partial<StoreExperiment>|null>(null),[measurementDialog,setMeasurementDialog]=useState<{experiment:StoreExperiment;record?:StoreMeasurement}|null>(null),[closeDialog,setCloseDialog]=useState<StoreExperiment|null>(null),[taskDialog,setTaskDialog]=useState<{report:StoreReport;index:number;task?:StoreTask}|null>(null),[reportId,setReportId]=useState(''),[ledgerDialog,setLedgerDialog]=useState<{experiment:StoreExperiment;record?:StoreMeasurement}|null>(null);
 const request=useRef(0),wanted=useRef(initialStoreId||''),scope=useRef(onScopeChange);
 useEffect(()=>{scope.current=onScopeChange});
 const load=useCallback(async()=>{const seq=++request.current;const params=new URLSearchParams();if(brandId!=='all')params.set('brandId',brandId);if(storeId)params.set('storeId',storeId);try{const r=await fetch('/api/stores?'+params);const x=await r.json() as StoreData & {error?:string};if(!r.ok)throw new Error(x.error||'점포 정보를 불러오지 못했습니다.');if(seq!==request.current)return;setData(x);setError('');setLoading(false);if(!storeId){const open=x.stores.filter((s:Store)=>s.status==='active'),pick=open.find(s=>s.id===wanted.current)||open[0];if(pick)setStoreId(pick.id);if((pick?.id||'')!==wanted.current)scope.current?.(brandId,pick?.id||'',true);wanted.current=pick?.id||''}}catch(e){if(seq===request.current){setError((e as Error).message);setLoading(false)}}},[brandId,storeId]);
 const latestLoad=useRef(load);latestLoad.current=load;
 useEffect(()=>{setLoading(true);void load();return()=>{request.current++}},[load]);
 const store=data.stores.find(s=>s.id===storeId),active=data.research.find(researchActive),report=data.reports.find(r=>r.id===reportId)||data.reports[0];
 useEffect(()=>{if(!active)return;const timer=setInterval(()=>void load(),10000);return()=>clearInterval(timer)},[active?.id,load]);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await load()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
 async function startResearch(s:Store){const id=clientId();await api('start',{id,brandId:s.brandId,storeId:s.id,mode:'deep'},'/api/archive/research');toast.success('점포 조사를 접수했습니다. 조사 탭에서 진행을 확인할 수 있습니다.');}
 const reportUsable=!!report&&report.sourceIds.every(id=>data.sources.some(s=>s.id===id&&s.status!=='excluded'));
 const readiness=store?storeReadiness(store,data.channels):null;
 function selectStore(id:string){setStoreId(id);setData(d=>({...empty,stores:d.stores}));setReportId('');setTab('diagnosis')}
 // 뒤로가기·앞으로가기로 주소의 지점만 바뀌면(같은 브랜드) 그 지점을 연다. 브랜드가 바뀌면 워크스페이스가 key로 이 화면을 새로 그린다.
 const[addressStore,setAddressStore]=useState(initialStoreId);
 if(addressStore!==initialStoreId){setAddressStore(initialStoreId);if(initialStoreId&&initialStoreId!==storeId&&data.stores.some(s=>s.id===initialStoreId&&s.status==='active'))selectStore(initialStoreId)}
 return <section className="store-marketing">
  <div className="store-toolbar"><div className="store-selects"><Field label="브랜드"><NativeSelect value={brandId} onChange={e=>{setBrandId(e.target.value);setStoreId('');setData(empty);scope.current?.(e.target.value,'',false)}}><NativeSelectOption value="all">모든 브랜드</NativeSelectOption>{workspace.brands.map(b=><NativeSelectOption key={b.id} value={b.id}>{b.name}</NativeSelectOption>)}</NativeSelect></Field><Field label="지점"><NativeSelect value={storeId} onChange={e=>{wanted.current=e.target.value;selectStore(e.target.value);scope.current?.(brandId,e.target.value,false)}}><NativeSelectOption value="">지점 선택</NativeSelectOption>{data.stores.filter(s=>s.status==='active').map(s=><NativeSelectOption key={s.id} value={s.id}>{s.name}</NativeSelectOption>)}</NativeSelect></Field></div><Button onClick={()=>setStoreDialog('new')} disabled={!workspace.brands.length}><Plus/>지점 등록</Button></div>
  {error&&<div className="load-error" role="alert">{error}<Button variant="outline" onClick={()=>void load()}>다시 시도</Button></div>}
  {loading?<p className="loading-line"><LoaderCircle className="spin" size={16}/>지점 정보를 불러오고 있습니다.</p>:!store?<Blank><MapPin size={30}/><h2>첫 지점의 마케팅을 시작하세요</h2><p>브랜드 아래에 지점을 등록하면 상권·채널·실험·성과를 따로 관리할 수 있습니다.</p><Button onClick={()=>setStoreDialog('new')}><Plus/>지점 등록</Button></Blank>:<>
   <div className="store-identity"><div><span className="eyebrow">LOCAL MARKETING / {workspace.brands.find(b=>b.id===store.brandId)?.name}</span><h2>{store.name}</h2><p><MapPin size={15}/>{store.address}</p></div><div className="store-actions"><Button variant="outline" onClick={()=>setStoreDialog(store)}><Pencil/>지점 정보</Button><Button variant="ghost" onClick={()=>onArchive(store.brandId)}>브랜드 아카이브<ArrowUpRight/></Button></div></div>
   <div className="store-goal"><span>이번 지점의 목표</span><strong>{store.goal}</strong><p>{store.daypart||'집중 시간대 미정'} · {tradeAreas[store.tradeArea]}</p></div>
   <div className="store-summary"><article><span>기초 정보</span><strong>{7-(readiness?.missing.length||0)}<small> / 7</small></strong><p>{readiness?.missing.length?readiness.missing.slice(0,2).join(' · ')+' 필요':'고객·운영·수익 조건 입력됨'}</p></article><article><span>채널 점검</span><strong>{readiness?.checked}<small> / {readiness?.total}</small></strong><p>사용자가 근거와 함께 확인한 항목</p></article><article><span>진행 중인 실험</span><strong>{data.experiments.filter(e=>e.status==='running').length}</strong><p>한 번에 바꿀 변수를 명확하게</p></article><article><span>완료한 회고</span><strong>{data.experiments.filter(e=>e.status==='completed').length}</strong><p>같은 지점의 다음 기획에 반영</p></article></div>
   {active&&<div className="store-research-status" role="status"><div><b><LoaderCircle className="spin" size={16}/>점포 조사 {active.status==='uncertain'?'접수 확인 중':'진행 중'}</b><p>{researchStages[active.steps.find(s=>s.status!=='completed')?.stage||'store_diagnosis']} · {active.steps.filter(s=>s.status==='completed').length}/{active.steps.length}단계</p><small>{active.execution==='server'?'서버 작업자가 연결된 조사입니다. 작업자가 가동 중이면 화면을 닫아도 이어집니다.':'서버 작업자 연결 전에는 화면을 열어두어야 다음 단계가 진행됩니다.'}</small>{active.error&&<p className="form-error">{active.error}</p>}</div><Button variant="outline" disabled={busy} onClick={()=>void run(async()=>{await api('cancel',{id:active.id},'/api/archive/research')})}>조사 중지</Button></div>}
   <Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="store-tabs"><TabsTrigger value="diagnosis">진단·실행 과제</TabsTrigger><TabsTrigger value="ledger">주문 장부</TabsTrigger><TabsTrigger value="channels">채널 점검</TabsTrigger><TabsTrigger value="experiments">실험·성과</TabsTrigger><TabsTrigger value="research">조사 기록</TabsTrigger></TabsList>
    <TabsContent value="diagnosis"><StoreDiagnosticPanel key={store.id} store={store}/><div className="section-heading"><div><h3>방문 이유와 성장 과제</h3><p>상권·메뉴·방문 장벽·지역 채널을 조사합니다.</p></div><Button disabled={busy||!!active||!workspace.connection.configured||workspace.connection.provider!=='hermes'} onClick={()=>void run(()=>startResearch(store))}><Search/>점포 심층 조사</Button></div>
    {!workspace.connection.configured&&<p className="notice">연결 및 설정에서 HERMES를 연결하면 점포 조사를 시작할 수 있습니다. 지점·채널·실험은 지금 기록할 수 있습니다.</p>}
    {!report?<Blank><FileText size={28}/><h3>아직 점포 진단이 없습니다</h3><p>지도·메뉴·상권·주변 경쟁 매장을 확인한 뒤 수정할 채널과 첫 실험을 제안합니다.</p><Button variant="outline" onClick={()=>setTab('channels')}>채널부터 점검하기<ArrowUpRight/></Button></Blank>:<>
     {data.reports.length>1&&<Field label="진단 기록"><NativeSelect value={report.id} onChange={e=>setReportId(e.target.value)}>{data.reports.map(r=><NativeSelectOption key={r.id} value={r.id}>{new Date(r.createdAt).toLocaleString('ko-KR')} · 지점 정보 v{r.storeVersion}</NativeSelectOption>)}</NativeSelect></Field>}
     <div className="store-report"><div className="store-report-label">AI 조사 초안 · 원문 확인 필요{report.storeVersion!==store.version&&' · 지점 정보 변경됨'}{!reportUsable&&' · 근거 변경됨, 재조사 필요'}</div><h3>{report.summary}</h3><div className="store-report-grid"><div><span>우선 고객 · 방문 이유</span><p>{report.customer}</p></div><div><span>해결할 장벽</span><p>{report.bottleneck}</p></div><div><span>성과 측정 방법</span><p>{report.measurementPlan}</p></div></div><p className="notice">{report.limitations}</p>{!!report.questions.length&&<details><summary>추가로 확인할 질문 {report.questions.length}개</summary><ul>{report.questions.map((q,i)=><li key={i}>{q}</li>)}</ul></details>}</div>
     <div className="section-heading"><h3>채널별 수정 과제</h3></div><div className="store-task-list">{report.actions.map((a,i)=>{const task=data.tasks.find(t=>t.id===report.id+'-'+i);return <article key={i}><span className={'store-tag '+(task?.status==='done'?'done':'')}>{task?.status==='done'?'완료':a.priority==='first'?'먼저':'다음'}</span><div><small>{channelName(a.channel)}</small><h4>{a.action}</h4><p>{a.reason}</p>{task?.evidence&&<p>처리 근거: {task.evidence}</p>}</div><Button variant="outline" onClick={()=>setTaskDialog({report,index:i,task})}>{task?.status==='done'?'기록 수정':'처리 기록'}</Button></article>})}{!report.actions.length&&<p className="notice">실행 과제를 제안할 근거가 부족합니다. 추가 질문에 해당하는 자료를 준비하세요.</p>}</div>
     <div className="section-heading"><h3>첫 실험 제안</h3></div><div className="store-proposals">{report.proposals.map((p,i)=><article key={i}><span>{channelName(p.channel)}</span><h4>{p.title}</h4><p>{p.hypothesis}</p><p><b>비교:</b> {p.control}</p><p><b>변경:</b> {p.treatment}</p><Button variant="outline" disabled={report.storeVersion!==store.version||!reportUsable} onClick={()=>{setExperimentDialog({...p,reportId:report.id});setTab('experiments')}}>검토하여 실험 만들기<ArrowUpRight/></Button></article>)}</div>
     <details className="store-sources"><summary>진단 근거 {report.sourceIds.length}개</summary>{report.sourceIds.map(id=>{const source=data.sources.find(s=>s.id===id);return source?<div key={id}>{source.url?<a href={source.url} target="_blank" rel="noreferrer">{source.title}<ExternalLink size={13}/></a>:<b>{source.title}</b>}<p>{source.excerpt}</p><small>{source.scope} · {source.observedAt.slice(0,10)} · {source.status==='confirmed'?'사용자 확인':'검토 대기'}</small></div>:<p key={id}>자료를 찾을 수 없습니다. 브랜드 아카이브를 확인하세요.</p>})}</details>
    </>}</TabsContent>
    <TabsContent value="ledger"><StoreLedgerPanel key={store.id} store={store} experiments={data.experiments}/></TabsContent>
    <TabsContent value="channels"><div className="section-heading"><div><h3>채널별 준비 상태</h3><p>실제 확인한 내용과 날짜를 기록하세요. 계정 연결 상태와는 별개입니다.</p></div></div><div className="store-channel-grid">{channelCatalog.map(c=>{const record=data.channels.find(x=>x.key===c.key),done=Object.values(record?.checks||{}).filter(v=>v==='done').length,excluded=Object.values(record?.checks||{}).filter(v=>v==='excluded').length;return <article key={c.key}><div className="store-channel-title"><h3>{c.name}</h3><span>{done}/{c.checks.length-excluded}</span></div><small>{c.role}</small><p>{c.tip}</p><div className="store-channel-track"><span style={{width:(c.checks.length===excluded?0:done/(c.checks.length-excluded)*100)+'%'}}/></div><ul>{c.checks.map((label,i)=><li key={label}><span className={'check-state '+(record?.checks[i]||'unknown')}>{checkStates[record?.checks[i]||'unknown']}</span>{label}</li>)}</ul><footer><Button variant="outline" onClick={()=>setChannelDialog(c.key)}>점검·수정</Button>{record?.url&&<a href={record.url} target="_blank" rel="noreferrer">매장 페이지<ExternalLink size={13}/></a>}{c.url&&<a href={c.url} target="_blank" rel="noreferrer">공식 가이드<ExternalLink size={13}/></a>}</footer></article>})}</div></TabsContent>
    <TabsContent value="experiments"><div className="section-heading"><div><h3>실험과 실제 성과</h3><p>설계 → 실행 기록 → 성과 → 회고를 한 지점 안에서 이어갑니다.</p></div><Button onClick={()=>setExperimentDialog({})}><Plus/>실험 설계</Button></div>
     {!data.experiments.length&&<Blank><FlaskConical size={30}/><h3>작은 실험부터 시작하세요</h3><p>한 채널에서 바꿀 변수, 비교 조건, 실제 구매 측정 방법을 정합니다.</p></Blank>}
     <div className="store-experiments">{data.experiments.map(e=>{const records=data.measurements.filter(m=>m.experimentId===e.id).sort((a,b)=>b.periodEnd.localeCompare(a.periodEnd));return <article key={e.id}><div className="store-experiment-head"><div><span className="store-tag">{experimentStates[e.status]}</span><small>{channelName(e.channel)}</small><h3>{e.title}</h3></div><Button variant="ghost" disabled={busy} onClick={()=>void run(async()=>{const r=await post('create_campaign',{storeId:store.id,experimentId:e.id});await onOpenCampaign(r.id)})}>{e.campaignId?'연결 캠페인':'캠페인 만들기'}<ArrowUpRight/></Button></div><p>{e.hypothesis}</p>{e.parentExperimentId&&<p className="notice">이전 실험: {data.experiments.find(x=>x.id===e.parentExperimentId)?.title||'연결된 회고'}</p>}<div className="store-experiment-facts"><span>{e.startDate||'시작 미정'} ~ {e.endDate||'종료 미정'}</span><span>예산 {e.budget===null?'미정':money(e.budget)}</span><span>{storeMetricFields[e.primaryMetric]} 목표 {e.target??'미정'}</span></div><details><summary>설계·측정 조건</summary><p><b>비교 조건:</b> {e.control||'미정'}</p><p><b>변경 조건:</b> {e.treatment||'미정'}</p><p><b>제안·혜택:</b> {e.offer||'없음'}</p><p><b>측정:</b> {e.measurement||'미정'}</p><p><b>확대·중단:</b> {e.stopRule||'미정'}</p></details>
      {records.length>0&&<><div className="store-metric-label">최근 기록 · {records[0].periodStart} ~ {records[0].periodEnd} · {records[0].source}</div><div className="store-metrics">{storeMetrics(records[0]).map(m=><div key={m.label}><span>{m.label}</span><strong>{m.value===null?'미수집':m.value.toLocaleString('ko-KR',{maximumFractionDigits:1})}<small>{m.value===null?'':m.unit}</small></strong><p>{m.definition}</p></div>)}</div><details><summary>성과 기록 {records.length}건 · 출처·집계 조건</summary>{records.map(m=><div className="store-measurement-row" key={m.id}><b>{m.periodStart} ~ {m.periodEnd}</b><p>{m.source} · {m.method==='export'?'내보내기 자료':'직접 기록'}</p><p>{m.definition}</p>{m.ledgerSnapshot&&<p className="notice">장부 기록 시점: {new Date(m.ledgerSnapshot.capturedAt).toLocaleString('ko-KR')} · 이후 주문 수정은 자동 반영되지 않습니다.</p>}<p>재방문 관찰 기간 {m.cohortMatured?'종료 확인':'미확인'}</p><dl>{Object.entries(m.values).filter(([,v])=>v!==null).map(([k,v])=><div key={k}><dt>{storeMetricFields[k as keyof typeof storeMetricFields]}</dt><dd>{v?.toLocaleString('ko-KR')}</dd></div>)}</dl>{e.status==='running'&&<Button variant="outline" onClick={()=>m.ledgerSnapshot?setLedgerDialog({experiment:e,record:m}):setMeasurementDialog({experiment:e,record:m})}>{m.ledgerSnapshot?'장부 다시 가져오기':'기록 수정'}</Button>}</div>)}</details></>}
      <Button variant="ghost" onClick={()=>setExperimentDialog({...e,id:undefined,version:undefined,reportId:undefined,campaignId:undefined,parentExperimentId:e.status==='completed'?e.id:undefined,title:e.title+' · 후속 실험',startDate:'',endDate:''})}>이 설계로 후속 실험 만들기</Button>
      {e.status==='completed'?<div className="store-learning"><b>{e.decision?decisions[e.decision]:'회고'}</b><p>{e.learning}</p>{e.review&&<><p><b>다음 행동:</b> {e.review.nextAction}</p><p><b>적용 조건:</b> {e.review.conditions||'추가 확인 필요'}</p><p><b>다른 설명:</b> {e.review.confounders||'기록 없음'}</p></>}<small>사용자 판단입니다. 같은 지점의 다음 조사·캠페인 기획에 참고합니다.</small></div>:<div className="store-actions">{e.status==='draft'?<><Button variant="outline" disabled={!!e.campaignId} onClick={()=>setExperimentDialog(e)}>{e.campaignId?'캠페인 연결 · 설계 고정':'설계 수정'}</Button><Button disabled={busy} onClick={()=>void run(async()=>{await post('start_experiment',{storeId:store.id,experimentId:e.id,version:e.version});toast.success('실험 기록을 시작했습니다. 광고·게시 실행은 각 채널에서 진행하세요.')})}>실험 시작</Button></>:<><Button onClick={()=>setMeasurementDialog({experiment:e})}><Plus/>성과 기록</Button><Button variant="outline" onClick={()=>setLedgerDialog({experiment:e})}>장부에서 가져오기</Button><Button variant="outline" onClick={()=>setCloseDialog(e)}>회고·종료</Button></>}</div>}
     </article>})}</div><p className="subtle-note">빈칸은 미수집으로 유지합니다. 기록된 매출은 광고 순증 효과가 아니며, 채널별 도달·방문을 합산하지 않습니다.</p></TabsContent>
    <TabsContent value="research"><div className="section-heading"><h3>점포 조사 기록</h3><Button variant="outline" onClick={()=>void load()}><RefreshCw/>지금 상태 확인</Button></div>{!data.research.length&&<Blank>아직 점포 조사 기록이 없습니다.</Blank>}{data.research.map(r=><article className="store-research-record" key={r.id}><h3>{r.status==='completed'?'조사 결과 저장됨':r.status==='failed'?'조사 중단':r.status==='cancelled'?'사용자 중지':r.status==='uncertain'?'접수 확인 중':'조사 진행 중'}</h3><small>{new Date(r.createdAt).toLocaleString('ko-KR')} · {r.model}</small>{r.error&&<p className="form-error">{r.error}</p>}{r.steps.map(s=><details key={s.id}><summary>{researchStages[s.stage]} · {s.status==='completed'?'저장됨':s.status==='pending'?'대기':s.status==='failed'?'중단':'진행 확인'}</summary><p>{s.summary||'최종 응답을 기다리고 있습니다.'}</p>{s.limitations&&<p className="notice">{s.limitations}</p>}</details>)}</article>)}</TabsContent>
   </Tabs>
  </>}
  {storeDialog&&<StoreDialog brands={workspace.brands} initial={storeDialog==='new'?undefined:storeDialog} brandId={brandId==='all'?workspace.brands[0]?.id:brandId} canResearch={workspace.connection.configured&&workspace.connection.provider==='hermes'} onClose={()=>setStoreDialog(null)} onSaved={async(id,brand,research)=>{setStoreDialog(null);setBrandId(brand);selectStore(id);if(research)try{await api('start',{id:clientId(),brandId:brand,storeId:id,mode:'deep'},'/api/archive/research');toast.success('지점 등록과 조사 접수가 완료됐습니다.')}catch(e){toast.warning('지점은 저장됐습니다. 조사 접수: '+(e as Error).message)}if(research||storeDialog!=='new')await latestLoad.current();scope.current?.(brand,id,false)}}/>}
  {store&&channelDialog&&<ChannelDialog key={channelDialog} store={store} channelKey={channelDialog} initial={data.channels.find(c=>c.key===channelDialog)} onClose={()=>setChannelDialog(null)} onSaved={load}/>}
  {store&&experimentDialog&&<ExperimentDialog store={store} initial={experimentDialog} onClose={()=>setExperimentDialog(null)} onSaved={load}/>}
  {store&&ledgerDialog&&<LedgerMeasurementDialog store={store} {...ledgerDialog} onClose={()=>setLedgerDialog(null)} onSaved={load}/>}
  {store&&measurementDialog&&<MeasurementDialog store={store} {...measurementDialog} onClose={()=>setMeasurementDialog(null)} onSaved={load}/>}
  {store&&closeDialog&&<CloseDialog store={store} experiment={closeDialog} onClose={()=>setCloseDialog(null)} onSaved={load}/>}
  {store&&taskDialog&&<TaskDialog store={store} {...taskDialog} onClose={()=>setTaskDialog(null)} onSaved={load}/>}
 </section>;
}
function StoreDialog({brands,initial,brandId,canResearch,onClose,onSaved}:{brands:Brand[];initial?:Store;brandId:string;canResearch:boolean;onClose:()=>void;onSaved:(id:string,brand:string,research:boolean)=>Promise<void>}){
 const [brand,setBrand]=useState(initial?.brandId||brandId),[f,setF]=useState<Record<string,string>>({...Object.fromEntries(Object.keys(storeFields).map(k=>[k,initial?.[k as keyof typeof storeFields]||''])),tradeArea:initial?.tradeArea||'unknown'}),[research,setResearch]=useState(canResearch&&!initial),[busy,setBusy]=useState(false);
 return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>{initial?'지점 정보 수정':'지점 등록'}</DialogTitle><DialogDescription>필수 정보는 이름·주소·목표입니다. 모르는 운영 수치는 비워두세요.</DialogDescription></DialogHeader><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const r=await post('save_store',{brandId:brand,id:initial?.id,version:initial?.version,data:f});await onSaved(r.id,brand,research)}catch(err){toast.error((err as Error).message)}finally{setBusy(false)}}}><Field label="브랜드"><NativeSelect value={brand} disabled={!!initial} onChange={e=>setBrand(e.target.value)}>{brands.map(b=><NativeSelectOption key={b.id} value={b.id}>{b.name}</NativeSelectOption>)}</NativeSelect></Field><div className="form-two">{Object.entries(storeFields).map(([k,label])=><Field key={k} label={label+(['name','address','goal'].includes(k)?' *':'')}><Textarea rows={k==='name'?1:2} required={['name','address','goal'].includes(k)} maxLength={k==='name'?150:3000} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></Field>)}</div><Field label="상권 유형"><NativeSelect value={f.tradeArea} onChange={e=>setF({...f,tradeArea:e.target.value})}>{Object.entries(tradeAreas).map(([k,v])=><NativeSelectOption key={k} value={k}>{v}</NativeSelectOption>)}</NativeSelect></Field>{!initial&&<label className="store-checkbox"><input type="checkbox" checked={research} disabled={!canResearch} onChange={e=>setResearch(e.target.checked)}/>등록 후 점포 심층 조사 시작{!canResearch&&' · HERMES 연결 필요'}</label>}<Button disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Check/>}{initial?'변경 저장':'지점 등록'}</Button></form></DialogContent></Dialog>;
}
function ChannelDialog({store,channelKey,initial,onClose,onSaved}:{store:Store;channelKey:string;initial?:StoreChannel;onClose:()=>void;onSaved:()=>Promise<void>}){
 const catalog=channelCatalog.find(c=>c.key===channelKey)!,[checks,setChecks]=useState<Record<string,string>>(initial?.checks||{}),[url,setUrl]=useState(initial?.url||''),[evidence,setEvidence]=useState(initial?.evidence||''),[checkedAt,setCheckedAt]=useState(initial?.checkedAt||today()),[busy,setBusy]=useState(false);
 return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>{catalog.name} 점검</DialogTitle><DialogDescription>{catalog.tip}</DialogDescription></DialogHeader><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await post('save_channel',{storeId:store.id,version:initial?.version,data:{key:catalog.key,checks,url,evidence,checkedAt}});await onSaved();onClose()}catch(err){toast.error((err as Error).message)}finally{setBusy(false)}}}><Field label="지점·계정 페이지 URL"><Input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></Field>{catalog.checks.map((label,i)=><Field key={label} label={label}><NativeSelect value={checks[i]||'unknown'} onChange={e=>setChecks({...checks,[i]:e.target.value})}>{Object.entries(checkStates).map(([k,v])=><NativeSelectOption key={k} value={k}>{v}</NativeSelectOption>)}</NativeSelect></Field>)}<Field label="확인일"><Input type="date" max={today()} value={checkedAt} onChange={e=>setCheckedAt(e.target.value)}/></Field><Field label="실제로 확인한 내용 · 근거 · 남은 과제"><Textarea rows={4} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="예: 관리자 메뉴판과 실제 판매 가격 대조. 휴무 정보 수정 필요."/></Field><Button disabled={busy}>점검 저장</Button></form></DialogContent></Dialog>;
}
function ExperimentDialog({store,initial,onClose,onSaved}:{store:Store;initial:Partial<StoreExperiment>;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [f,setF]=useState({...initial,title:initial.title||'',channel:initial.channel||'naver_place',hypothesis:initial.hypothesis||'',offer:initial.offer||'',control:initial.control||'',treatment:initial.treatment||'',primaryMetric:initial.primaryMetric||'orders',target:initial.target??'',budget:initial.budget??'',startDate:initial.startDate||'',endDate:initial.endDate||'',measurement:initial.measurement||'',stopRule:initial.stopRule||''}),[busy,setBusy]=useState(false);
 const labels={title:'실험 이름 *',hypothesis:'검증할 가설 *',offer:'메뉴·혜택·방문 제안',control:'비교 조건 · 기준 기간',treatment:'바꿀 변수 · 적용 조건',measurement:'출처·집계·고객 연결 방법',stopRule:'확대·수정·중단 기준'};
 return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>{initial.id?'실험 설계 수정':'점포 실험 설계'}</DialogTitle><DialogDescription>시작 전 예산·목표·기간·비교·측정 조건을 확정합니다. 광고 집행은 각 채널에서 진행합니다.</DialogDescription></DialogHeader><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await post('save_experiment',{storeId:store.id,id:initial.id,version:initial.version,reportId:initial.reportId,parentExperimentId:initial.parentExperimentId,data:{...f,budget:f.budget===''?null:Number(f.budget),target:f.target===''?null:Number(f.target)}});await onSaved();onClose()}catch(err){toast.error((err as Error).message)}finally{setBusy(false)}}}><Field label="실험 채널"><NativeSelect value={f.channel} onChange={e=>setF({...f,channel:e.target.value as StoreExperiment['channel']})}>{channelCatalog.map(c=><NativeSelectOption key={c.key} value={c.key}>{c.name}</NativeSelectOption>)}</NativeSelect></Field>{Object.entries(labels).map(([k,label])=><Field key={k} label={label}><Textarea required={k==='title'||k==='hypothesis'} rows={k==='title'?1:2} maxLength={k==='title'?150:3000} value={String(f[k as keyof typeof f]||'')} onChange={e=>setF({...f,[k]:e.target.value})}/></Field>)}<div className="form-two"><Field label="핵심 성과지표"><NativeSelect value={f.primaryMetric} onChange={e=>setF({...f,primaryMetric:e.target.value as StoreExperiment['primaryMetric']})}>{Object.entries(storeMetricFields).map(([k,v])=><NativeSelectOption key={k} value={k}>{v}</NativeSelectOption>)}</NativeSelect></Field><Field label="목표값 · 선택 지표의 단위"><Input type="number" min="0" step="any" value={f.target} onChange={e=>setF({...f,target:e.target.value})} placeholder="미정"/></Field><Field label="전체 실험 예산 상한 (원)"><Input type="number" min="0" value={f.budget} onChange={e=>setF({...f,budget:e.target.value})} placeholder="미정 · 비용 없으면 0"/></Field><Field label="시작일"><Input type="date" value={f.startDate} onChange={e=>setF({...f,startDate:e.target.value})}/></Field><Field label="종료일"><Input type="date" min={f.startDate||undefined} value={f.endDate} onChange={e=>setF({...f,endDate:e.target.value})}/></Field></div><Button disabled={busy}>설계 저장</Button></form></DialogContent></Dialog>;
}
function MeasurementDialog({store,experiment,record,onClose,onSaved}:{store:Store;experiment:StoreExperiment;record?:StoreMeasurement;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [f,setF]=useState({periodStart:record?.periodStart||experiment.startDate,periodEnd:record?.periodEnd||(today()<experiment.endDate?today():experiment.endDate),source:record?.source||'',definition:record?.definition||'Asia/Seoul · ',method:record?.method||'manual',cohortMatured:record?.cohortMatured||false}),[values,setValues]=useState<Record<string,string>>(Object.fromEntries(Object.keys(storeMetricFields).map(k=>[k,record?.values[k as keyof typeof storeMetricFields]===null||record?.values[k as keyof typeof storeMetricFields]===undefined?'':String(record.values[k as keyof typeof storeMetricFields])]))),[busy,setBusy]=useState(false);
 return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>{experiment.title} · 성과 기록</DialogTitle><DialogDescription>확인한 수치만 입력하세요. 같은 실험의 기간이 겹치면 기존 기록을 수정합니다.</DialogDescription></DialogHeader><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await post('save_measurement',{storeId:store.id,experimentId:experiment.id,id:record?.id,version:record?.version,data:{...f,values:Object.fromEntries(Object.entries(values).map(([k,v])=>[k,v===''?null:Number(v)]))}});await onSaved();onClose()}catch(err){toast.error((err as Error).message)}finally{setBusy(false)}}}><div className="form-two"><Field label="측정 시작"><Input required type="date" min={experiment.startDate} max={experiment.endDate} value={f.periodStart} onChange={e=>setF({...f,periodStart:e.target.value})}/></Field><Field label="측정 종료"><Input required type="date" min={f.periodStart} max={today()<experiment.endDate?today():experiment.endDate} value={f.periodEnd} onChange={e=>setF({...f,periodEnd:e.target.value})}/></Field></div><Field label="수치 출처 *"><Input required value={f.source} onChange={e=>setF({...f,source:e.target.value})} placeholder="POS 내보내기 파일명·광고 관리자·쿠폰 사용 대장"/></Field><Field label="수집 방식"><NativeSelect value={f.method} onChange={e=>setF({...f,method:e.target.value as 'manual'|'export'})}><NativeSelectOption value="manual">직접 기록</NativeSelectOption><NativeSelectOption value="export">계정·POS 내보내기 자료</NativeSelectOption></NativeSelect></Field><Field label="집계 정의 · 시간대 · 고객군 · 비용 범위 *"><Textarea required rows={3} value={f.definition} onChange={e=>setF({...f,definition:e.target.value})} placeholder="매출 범위, 쿠폰·신규 고객 식별법, 재방문 관찰 기간 등을 기록"/></Field><div className="form-two">{Object.entries(storeMetricFields).map(([k,label])=><Field key={k} label={label}><Input type="number" min="0" step={['revenue','variableCosts','adSpend','productionCost'].includes(k)?'any':'1'} placeholder="미수집" value={values[k]} onChange={e=>setValues({...values,[k]:e.target.value})}/></Field>)}</div><label className="store-checkbox"><input type="checkbox" checked={f.cohortMatured} onChange={e=>setF({...f,cohortMatured:e.target.checked})}/>재구매 고객군의 관찰 기간이 모두 끝났음을 확인</label><p className="notice">길찾기·통화 클릭은 방문이 아닙니다. 할인액을 이미 매출에서 차감했다면 변동비에 중복 입력하지 마세요. 동일 쿠폰과 고객군으로 분모·분자를 맞추세요.</p><Button disabled={busy}>성과 저장</Button></form></DialogContent></Dialog>;
}
function CloseDialog({store,experiment,onClose,onSaved}:{store:Store;experiment:StoreExperiment;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [decision,setDecision]=useState('inconclusive'),[learning,setLearning]=useState(''),[review,setReview]=useState({evidenceLevel:'observation',failureType:'none',confounders:'',nextAction:'',conditions:''}),[busy,setBusy]=useState(false);
 return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent><DialogHeader><DialogTitle>실험 회고·종료</DialogTitle><DialogDescription>종료하면 설계와 성과 기록을 보존합니다. 결과·다른 설명·다음 실험을 함께 남기세요.</DialogDescription></DialogHeader><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await post('close_experiment',{storeId:store.id,experimentId:experiment.id,version:experiment.version,decision,learning,review});await onSaved();onClose()}catch(err){toast.error((err as Error).message)}finally{setBusy(false)}}}><Field label="판단"><NativeSelect value={decision} onChange={e=>setDecision(e.target.value)}>{Object.entries(decisions).map(([k,v])=><NativeSelectOption key={k} value={k}>{v}</NativeSelectOption>)}</NativeSelect></Field><Field label="근거 · 날씨·행사 등 다른 설명 · 다음 실험"><Textarea required rows={6} value={learning} onChange={e=>setLearning(e.target.value)}/></Field><Field label="근거 수준"><NativeSelect value={review.evidenceLevel} onChange={e=>setReview({...review,evidenceLevel:e.target.value})}><NativeSelectOption value="observation">관찰 결과 · 인과 판단 전</NativeSelectOption><NativeSelectOption value="comparison">비교 조건을 갖춘 결과</NativeSelectOption><NativeSelectOption value="repeated">반복 확인한 결과</NativeSelectOption></NativeSelect></Field><Field label="어디에서 막혔나요?"><NativeSelect value={review.failureType} onChange={e=>setReview({...review,failureType:e.target.value})}>{Object.entries({none:'해당 없음',collection:'자료 수집 실패',execution:'집행·운영 문제',measurement:'측정 불가',insufficient:'관찰 부족',economics:'경제성 부족',negative:'부정적 결과'}).map(([k,v])=><NativeSelectOption key={k} value={k}>{v}</NativeSelectOption>)}</NativeSelect></Field>{Object.entries({confounders:'날씨·행사·동시 변경 등 다른 설명',nextAction:'다음 행동 *',conditions:'다른 기간·지점에 적용할 조건'}).map(([k,v])=><Field key={k} label={v}><Textarea required={k==='nextAction'} maxLength={2000} rows={2} value={review[k as keyof typeof review]} onChange={e=>setReview({...review,[k]:e.target.value})}/></Field>)}<Button disabled={busy}>회고 저장·종료</Button></form></DialogContent></Dialog>;
}
function TaskDialog({store,report,index,task,onClose,onSaved}:{store:Store;report:StoreReport;index:number;task?:StoreTask;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [status,setStatus]=useState(task?.status||'open'),[evidence,setEvidence]=useState(task?.evidence||''),[busy,setBusy]=useState(false);
 return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent><DialogHeader><DialogTitle>실행 과제 처리 기록</DialogTitle><DialogDescription>{report.actions[index].action}</DialogDescription></DialogHeader><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await post('save_task',{storeId:store.id,reportId:report.id,index,version:task?.version,status,evidence});await onSaved();onClose()}catch(err){toast.error((err as Error).message)}finally{setBusy(false)}}}><Field label="상태"><NativeSelect value={status} onChange={e=>setStatus(e.target.value as 'open'|'done')}><NativeSelectOption value="open">진행 필요</NativeSelectOption><NativeSelectOption value="done">완료</NativeSelectOption></NativeSelect></Field><Field label="실제 처리 내용 · 확인 근거"><Textarea required={status==='done'} rows={5} value={evidence} onChange={e=>setEvidence(e.target.value)}/></Field><Button disabled={busy}>처리 기록 저장</Button></form></DialogContent></Dialog>;
}
