import {test,expect,type Page} from '@playwright/test';
const password='Test-only-password-2026!';
async function setup(page:Page,email:string){
 await page.getByLabel('이메일',{exact:true}).fill(email);
 await page.getByLabel('비밀번호',{exact:true}).fill(password);
 await page.getByLabel('비밀번호 확인',{exact:true}).fill(password);
 await page.getByRole('button',{name:'비밀번호 설정하고 시작'}).click();
 await expect(page.getByRole('button',{name:'로그아웃',exact:true})).toBeVisible();
}
test('이메일 로그인·초대·세션 유지·권한 제한·폐기',async({page,browser,baseURL})=>{
 const post=(path:string,data:object)=>page.request.post(path,{data,headers:{origin:baseURL!}});
 await page.goto('/');
 await expect(page.getByRole('heading',{name:'다시 만나 반갑습니다'})).toBeVisible();
 await page.screenshot({path:'e2e/artifacts/email-login-mobile.png',fullPage:true});
 expect((await page.request.get('/api/workspace',{headers:{'oai-authenticated-user-id':'e2e-email-owner'}})).status()).toBe(401);
 await page.goto('/#setup=e2e-only-bootstrap-token-do-not-use-in-production');
 await setup(page,'admin@example.test');
 expect(page.url()).not.toContain('#');
 const cookies=await page.context().cookies();
 expect(cookies.find(c=>c.name==='__Host-collective_session')).toMatchObject({secure:true,httpOnly:true,sameSite:'Lax'});
 await page.reload();
 await expect(page.getByRole('button',{name:'팀 계정 관리',exact:true})).toBeVisible();
 expect((await page.request.get('/api/workspace')).status()).toBe(200);
 await page.getByRole('button',{name:'팀 계정 관리',exact:true}).click();
 await page.getByLabel('초대할 이메일').fill('member@example.test');
 await page.getByRole('button',{name:'초대 링크 만들기'}).click();
 const invite=await page.getByLabel('초대·재설정 링크').inputValue();
 await expect(page.getByRole('button',{name:'초대 링크 재발급',exact:true})).toBeVisible();
 const token=new URLSearchParams(new URL(invite).hash.slice(1)).get('invite');
 const context=await browser.newContext({baseURL,ignoreHTTPSErrors:true,viewport:{width:390,height:844}});
 const member=await context.newPage();
 await member.goto(invite);await setup(member,'member@example.test');
 await expect(member.getByRole('button',{name:'팀 계정 관리',exact:true})).toHaveCount(0);
 expect((await member.request.get('/api/workspace')).status()).toBe(200);
 expect((await member.request.get('/api/accounts')).status()).toBe(403);
 expect((await member.request.post('/api/action',{headers:{origin:baseURL!},data:{action:'disconnect'}})).status()).toBe(403);
 expect((await member.request.post('/api/auth',{headers:{origin:baseURL!},data:{action:'accept',token,email:'member@example.test',password}})).status()).toBe(401);
 expect((await member.request.post('/api/action',{data:{action:'disconnect'}})).status()).toBe(403);
 await member.reload();await expect(member.getByRole('button',{name:'로그아웃',exact:true})).toBeVisible();
 const accounts=await (await page.request.get('/api/accounts')).json() as {accounts:{id:string;email:string}[]};
 const userId=accounts.accounts.find(a=>a.email==='member@example.test')!.id;
 const reset=await (await post('/api/accounts',{action:'reset',userId})).json() as {token:string};
 const other=await browser.newContext({baseURL,ignoreHTTPSErrors:true});
 expect((await other.request.post('/api/auth',{headers:{origin:baseURL!},data:{action:'accept',token:reset.token,email:'member@example.test',password}})).status()).toBe(200);
 expect((await member.request.get('/api/workspace')).status()).toBe(401);
 expect((await post('/api/accounts',{action:'disable',userId})).status()).toBe(200);
 expect((await other.request.get('/api/workspace')).status()).toBe(401);
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'로그아웃',exact:true}).click();
 await expect(page.getByRole('heading',{name:'다시 만나 반갑습니다'})).toBeVisible();
 await page.getByLabel('이메일',{exact:true}).fill('admin@example.test');
 await page.getByLabel('비밀번호',{exact:true}).fill(password);
 await page.getByRole('button',{name:'로그인',exact:true}).click();
 await expect(page.getByRole('button',{name:'팀 계정 관리',exact:true})).toBeVisible();
 await context.close();await other.close();
});
