import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';

// Real local D1/API/Chromium. Approved publication/Buffer result are explicit local fixtures.
// No approval, provider read, execute, or external network call is issued by this test.
function fixture(owner:string,kind:string,id:string,parent:string,data:unknown){
 const quote=(value:string)=>`'${value.replaceAll("'","''")}'`,folder=mkdtempSync(join(tmpdir(),'collective-publication-'));
 try{const path=join(folder,'fixture.sql');writeFileSync(path,`INSERT INTO records(id,owner,kind,parent_id,data,updated_at) VALUES(${[`${owner}:${kind}:${id}`,owner,kind,parent,JSON.stringify(data),new Date().toISOString()].map(quote).join(',')}) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at;`);execFileSync(process.execPath,['--import','./scripts/sites-env.mjs','./node_modules/wrangler/bin/wrangler.js','d1','execute','DB','--config','dist/server/wrangler.json','--local','--persist-to','e2e/.state','--file',path],{stdio:'pipe'});}finally{rmSync(folder,{recursive:true,force:true})}
}
test('자연유입 발행 연결·정확판 충돌·서버 상태 동기화와 예약 유지',async({browser},info)=>{
 const owner=`publication-${info.project.name}-${Date.now()}`,context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':owner}}),page=await context.newPage();
 try{
  const post=async(path:string,data:unknown)=>{const r=await page.request.post(path,{data});expect(r.status(),await r.text()).toBe(200);return r.json()};await page.request.get('/api/workspace');
  const before=new Date(Date.now()-86400000).toISOString(),after=new Date(Date.now()+30*86400000).toISOString(),day=after.slice(0,10);
  const {id:storeId}=await post('/api/stores',{action:'save_store',brandId:'ofd',data:{name:'발행 연결 합성 지점',address:'합성 주소',tradeArea:'residential',goal:'자연유입 발행 연결'}});
  const title=`자연유입 발행 ${info.project.name}`,{id:campaignId}=await post('/api/action',{action:'save_campaign',data:{brandId:'ofd',storeId,title,goal:'승인 발행 연결'}});
  const {id:factId}=await post('/api/brand-facts',{action:'save_fact',confirmed:true,data:{brandId:'ofd',key:'합성 상품',value:'테스트용 상품 근거',status:'confirmed',source:'합성 운영 확인',verifiedAt:before,validUntil:after}});
  const save=(action:string,id:string,input:unknown)=>post('/api/growth',{action,id,input,campaignId,campaignVersion:1,expectedVersion:0});
  await save('save_signal','pub-signal',{title:'시장 근거',sourceUrl:'https://example.com/market',observedAt:before,expiresAt:day,sourceType:'market',summary:'공개 관측',sampleSize:null});
  await save('save_need','pub-need',{title:'니즈 가설',situation:'상황',desiredOutcome:'준비 단축',alternative:'기존 대안',barrier:'배송',counterEvidence:'직접 조리',signalIds:['pub-signal'],deadline:day,nextAction:'확인',assignee:'검토 담당'});
  await save('save_catalog','pub-catalog',{sku:'PUBLICATION-SKU',title:'자연유입 상품',price:100,unitCost:20,variableCost:10,stock:0,stockUnit:'piece',currency:'KRW',taxBasis:'included',fulfillment:'배송 조건',refunds:'반품 조건',rightsConfirmed:true,factIds:[factId],validUntil:day});
  await save('save_offer','pub-offer',{title:'자연유입 오퍼',catalogId:'pub-catalog',catalogVersion:1,needId:'pub-need',price:100,quantity:2,landingUrl:'https://example.com/buy',purchaseReason:'준비 단축',priceApproved:true});
  await save('save_mission','pub-mission',{title:'자연유입 미션',offerId:'pub-offer',offerVersion:1,assignee:'판매 담당',deadline:day,nextAction:'판매 준비',channel:'organic',budget:0,lossLimit:0,stopRule:'한도 도달',fulfillmentOwner:'배송 담당'});
  const stock=await post('/api/growth/operations',{action:'create_inventory',campaignId,campaignVersion:1,input:{sku:'PUBLICATION-SKU',locationId:storeId,unit:'piece',onHand:10},observedAt:before,evidenceRef:'warehouse-opening'});
  await post('/api/growth',{action:'queue_mission',id:'pub-mission',campaignId,campaignVersion:1,expectedVersion:1});await post('/api/growth/authority',{action:'save_authority',id:'pub-authority',campaignId,campaignVersion:1,expectedVersion:0,sign:true,input:{accountId:'buffer-channel',channel:'organic',status:'active',maxTier:'T3',allowedActions:['publish','spend'],startsAt:before,expiresAt:after,periodStart:before,periodEnd:after,totalCap:1000,dayCap:1000,weekCap:1000,lossCap:1000}});
  const prepared=await post('/api/growth/execution',{action:'prepare_execution',campaignId,campaignVersion:1,input:{missionId:'pub-mission',missionVersion:2,authorityId:'pub-authority',authorityVersion:1,inventoryId:stock.inventory[0].id,inventoryVersion:stock.inventory[0].version,quantity:2,recoveryOwner:'결과 확인 담당',recoveryDueAt:after,evidenceRef:'publication-preparation'}}),intentId=prepared.intents[0].id;
  const publicationId='synthetic-approved-publication';let publication={id:publicationId,campaignId,campaignVersion:1,creativeId:'synthetic-creative',creativeVersion:1,pngHash:'a'.repeat(64),factRefs:[{id:factId,version:1}],caption:'자연유입 상품을 확인하세요',mediaUrl:'https://example.com/synthetic.png',mediaMode:'external',scheduledAt:new Date(Date.now()+86400000).toISOString(),plannedCostKRW:0,version:1,status:'approved',channelId:'buffer-channel',credentialVersion:1,limitsVersion:1,approvedLimits:{maxPublications:10,maxPlannedCostKRW:1000},approvedBy:owner,approvedAt:before,createdAt:before,providerId:undefined as string|undefined,attemptedAt:undefined as string|undefined};
  fixture(owner,'execution_creative','synthetic-creative',campaignId,{id:'synthetic-creative',campaignId,campaignVersion:1,brandId:'ofd',storeId,version:1,factRefs:[{id:factId,version:1}],caption:'합성 소재',pngHash:'a'.repeat(64),objectKey:'synthetic.png',createdAt:before});fixture(owner,'publisher_credential','ofd','ofd',{channelId:'buffer-channel',account:'합성 Buffer 계정',version:1});fixture(owner,'execution_publication',publicationId,campaignId,publication);
  const open=async()=>{await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기',exact:true}).click();await page.getByRole('tab',{name:'성장·판매',exact:true}).click();await page.locator('summary').filter({hasText:/^일반 판매 실행 준비·결과$/}).click();const panel=page.getByRole('region',{name:'자연유입 발행 연결',exact:true});await expect(panel).toBeVisible({timeout:5000});return panel};
  const read=async()=>{const r=await page.request.get(`/api/growth/publication?campaignId=${campaignId}`);expect(r.status(),await r.text()).toBe(200);return r.json()};
  const panel=await open();await panel.getByRole('combobox',{name:'예약된 자연유입 실행',exact:true}).selectOption(intentId);await panel.getByRole('combobox',{name:'승인된 미시도 발행',exact:true}).selectOption(publicationId);await panel.getByRole('textbox',{name:'내용·오퍼 일치 확인 근거',exact:true}).fill('content-offer-check');await panel.getByRole('checkbox').check();
  publication={...publication,version:2,caption:'자연유입 상품의 최신 승인 문구'};fixture(owner,'execution_publication',publicationId,campaignId,publication);await panel.getByRole('button',{name:'발행 연결 기록',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('입력은 보존했습니다.');await panel.getByRole('button',{name:'발행 연결 새로고침',exact:true}).click();await panel.getByRole('button',{name:'현재 입력 유지 · 최신 발행 판 사용',exact:true}).click();await expect(panel.getByRole('textbox',{name:'내용·오퍼 일치 확인 근거',exact:true})).toHaveValue('content-offer-check');await expect(panel.getByRole('checkbox')).not.toBeChecked();await panel.getByRole('checkbox').check();
  const attempts:string[]=[];let loseResponse=true,ackSync=true;await page.route('**/api/growth/publication',async route=>{const request=route.request();if(request.method()==='POST'&&request.postDataJSON().action==='link_publication'){attempts.push(request.postDataJSON().requestId);if(loseResponse){loseResponse=false;const response=await route.fetch();expect(response.status(),await response.text()).toBe(200);await route.abort('failed');return;}}if(request.method()==='POST'&&request.postDataJSON().action==='sync_publication'&&ackSync){ackSync=false;const response=await route.fetch();expect(response.status(),await response.text()).toBe(200);await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({recorded:true,viewUnavailable:true,resultLinkId:request.postDataJSON().id,duplicate:false,mayExecute:false})});return;}await route.continue();});
  await panel.getByRole('button',{name:'발행 연결 기록',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('입력은 보존했습니다.');await panel.getByRole('button',{name:'발행 연결 기록',exact:true}).click();await expect(panel.getByRole('status')).toContainText('발행을 연결했습니다.');expect(attempts).toHaveLength(2);expect(attempts[0]).toBe(attempts[1]);expect((await read()).links).toHaveLength(1);
  const execution=page.getByRole('region',{name:'일반 판매 실행 준비',exact:true});await execution.getByRole('complementary',{name:'판매 실행 기록',exact:true}).getByRole('button',{name:/자연유입 미션/}).click();await expect(execution.getByRole('button',{name:'실행 결과 기록',exact:true})).toBeDisabled();
  publication={...publication,version:3,status:'accepted',providerId:'synthetic-buffer-post',attemptedAt:new Date().toISOString()};fixture(owner,'execution_publication',publicationId,campaignId,publication);await panel.getByRole('button',{name:'발행 연결 새로고침',exact:true}).click();await panel.getByRole('button',{name:'저장된 발행 결과 동기화',exact:true}).click();await expect(panel.getByRole('status')).toContainText('발행 연결 기록 저장 완료 · 최신 목록 조회 불가');await expect(panel.getByRole('button',{name:'저장된 발행 결과 동기화',exact:true})).toBeDisabled();await panel.getByRole('button',{name:'발행 연결 새로고침',exact:true}).click();await expect(panel.getByRole('region',{name:'연결된 자연유입 발행',exact:true})).toContainText('접수·예약 확인 · 발행 전');let v=await(await page.request.get(`/api/growth/execution?campaignId=${campaignId}`)).json();expect(v.inventory[0].projection.reserved).toBe(2);expect(v.intents[0].state).toBe('unknown');
  publication={...publication,version:4,status:'published'};fixture(owner,'execution_publication',publicationId,campaignId,publication);await panel.getByRole('button',{name:'발행 연결 새로고침',exact:true}).click();await panel.getByRole('button',{name:'저장된 발행 결과 동기화',exact:true}).click();await expect(panel.getByRole('region',{name:'연결된 자연유입 발행',exact:true})).toContainText('발행 확인 · 판매 효과 미확인');
  const restored=await open();await expect(restored.getByRole('region',{name:'연결된 자연유입 발행',exact:true})).toContainText('발행 확인 · 판매 효과 미확인');v=await(await page.request.get(`/api/growth/execution?campaignId=${campaignId}`)).json();expect(v.inventory[0].projection.reserved).toBe(2);expect(await restored.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await restored.getByRole('heading',{name:'자연유입 발행 연결',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`e2e/artifacts/growth-publication-${info.project.name}.png`});
 }finally{await context.close().catch(()=>{})}
});
