import {test,expect} from '@playwright/test';

test('확정 Archive 시장자료 가져오기·판 충돌·응답 유실·중복 방지',async({browser},info)=>{
 const owner=`signal-source-${info.project.name}-${Date.now()}`,context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':owner}}),page=await context.newPage();
 try{
  const post=async(path:string,data:unknown)=>{const response=await page.request.post(path,{data});expect(response.status(),await response.text()).toBe(200);return response.json()};await page.request.get('/api/workspace');const title=`시장자료 연결 ${info.project.name}`,{id:campaignId}=await post('/api/action',{action:'save_campaign',data:{brandId:'ofd',title,goal:'확정 자료 재사용'}});
  const sourceTitle='공개 시장 관측',observedAt=new Date(Date.now()-86400000).toISOString(),expiresAt=new Date(Date.now()+30*86400000).toISOString().slice(0,10),{id:sourceId}=await post('/api/archive',{action:'add_source',brandId:'ofd',data:{title:sourceTitle,category:'market',url:'https://example.com/market',content:'공개 자료에서 간편 조리 선호를 관측했습니다.',scope:'공개 웹 자료',observedAt}});await post('/api/archive',{action:'review_source',brandId:'ofd',id:sourceId,version:1,status:'confirmed'});
  const {id:heldId}=await post('/api/archive',{action:'add_source',brandId:'ofd',data:{title:'기한 검토용 자료',category:'market',url:'https://example.com/other',content:'검토 대기 공개 관측',scope:'공개 웹 자료',observedAt}});
  const open=async()=>{await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기',exact:true}).click();await page.getByRole('tab',{name:'성장·판매',exact:true}).click();const panel=page.getByRole('region',{name:'확정 시장자료 가져오기',exact:true});await expect(panel).toBeVisible({timeout:5000});return panel};
  const panel=await open(),choice=panel.getByRole('combobox',{name:'Archive 자료 선택',exact:true}),expiry=panel.getByLabel('가져올 근거 유효기한',{exact:true});await choice.selectOption(sourceId);await expect(panel).toContainText('공개 자료에서 간편 조리 선호를 관측했습니다.');await expiry.fill(expiresAt);await choice.selectOption(heldId);await expect(expiry).toHaveValue('');await expect(panel.getByRole('button',{name:'시장 근거로 가져오기',exact:true})).toBeDisabled();await choice.selectOption(sourceId);await expiry.fill(expiresAt);
  await post('/api/archive',{action:'review_source',brandId:'ofd',id:sourceId,version:2,status:'confirmed'});await panel.getByRole('button',{name:'시장 근거로 가져오기',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('입력은 보존했습니다.');await panel.getByRole('button',{name:'자료 목록 새로고침',exact:true}).click();await expect(expiry).toHaveValue(expiresAt);await panel.getByRole('button',{name:'현재 기한 유지 · 최신 자료 판 사용',exact:true}).click();
  const attempts:string[]=[];let lose=true;await page.route('**/api/growth/signal-sources',async route=>{if(route.request().method()==='POST'){attempts.push(route.request().postDataJSON().requestId);if(lose){lose=false;const response=await route.fetch();expect(response.status(),await response.text()).toBe(200);await route.abort('failed');return;}}await route.continue();});await panel.getByRole('button',{name:'시장 근거로 가져오기',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('입력은 보존했습니다.');await panel.getByRole('button',{name:'시장 근거로 가져오기',exact:true}).click();await expect(panel.getByRole('status').filter({hasText:'시장 근거를 가져왔습니다.'})).toContainText('시장 근거를 가져왔습니다.');expect(attempts).toHaveLength(2);expect(attempts[0]).toBe(attempts[1]);await expect(panel.getByRole('button',{name:'시장 근거로 가져오기',exact:true})).toBeDisabled();await expect(page.getByRole('group',{name:'시장 근거 기록 목록',exact:true}).getByRole('button',{name:new RegExp(sourceTitle)})).toBeVisible();await page.getByRole('group',{name:'시장 근거 기록 목록',exact:true}).getByRole('button',{name:new RegExp(sourceTitle)}).click();await expect(page.getByLabel('근거 제목',{exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'시장 근거 저장',exact:true})).toBeDisabled();await expect(page.getByText('자료실에서 가져온 근거입니다. 원자료를 수정한 뒤 새 판을 가져오세요. 가져온 근거의 내용은 여기서 변경할 수 없습니다.',{exact:true})).toBeVisible();
  const response=await page.request.get(`/api/growth?campaignId=${campaignId}`),view=await response.json();expect(view.signals).toHaveLength(1);expect(view.signals[0].input.sampleSize).toBeNull();expect(view.signals[0].input.expiresAt).toBe(expiresAt);await post('/api/archive',{action:'review_source',brandId:'ofd',id:sourceId,version:3,status:'confirmed'});await panel.getByRole('button',{name:'자료 목록 새로고침',exact:true}).click();await panel.getByRole('button',{name:'현재 기한 유지 · 최신 자료 판 사용',exact:true}).click();await expect(expiry).toHaveValue(expiresAt);await expect(panel.getByRole('button',{name:'시장 근거로 가져오기',exact:true})).toBeEnabled();await panel.getByRole('button',{name:'시장 근거로 가져오기',exact:true}).click();await expect(panel.getByRole('status').filter({hasText:'시장 근거를 가져왔습니다.'})).toBeVisible();const revised=await(await page.request.get(`/api/growth?campaignId=${campaignId}`)).json();expect(revised.signals).toHaveLength(2);expect(revised.signals.find((row:{sourceProvenance?:{sourceVersion:number}})=>row.sourceProvenance?.sourceVersion===3)?.sourceReadiness.status).toBe('held');expect(revised.signals.find((row:{sourceProvenance?:{sourceVersion:number}})=>row.sourceProvenance?.sourceVersion===4)?.sourceReadiness.status).toBe('current');expect(attempts).toHaveLength(3);expect(attempts[2]).not.toBe(attempts[1]);const restored=await open();await restored.getByRole('combobox',{name:'Archive 자료 선택',exact:true}).selectOption(sourceId);await expect(restored).toContainText('이미 가져온 자료입니다.');await expect(restored.getByRole('button',{name:'시장 근거로 가져오기',exact:true})).toBeDisabled();expect(await restored.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await restored.getByRole('heading',{name:'확정 시장자료 가져오기',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`e2e/artifacts/growth-signal-source-${info.project.name}.png`});
 }finally{await context.close().catch(()=>{})}
});
