import {test,expect} from '@playwright/test';

test('기회별 오퍼 준비도·개별 일정·정확 기록 열기·미저장 입력 보호',async({browser},info)=>{
 const owner=`opportunity-${info.project.name}-${Date.now()}`,context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':owner}}),page=await context.newPage();
 try{
  const post=async(path:string,data:unknown)=>{const response=await page.request.post(path,{data});expect(response.status(),await response.text()).toBe(200);return response.json()};await page.request.get('/api/workspace');const title=`기회 보드 ${info.project.name}`,before=new Date(Date.now()-86400000).toISOString(),after=new Date(Date.now()+30*86400000).toISOString(),day=(offset:number)=>new Date(Date.now()+offset*86400000).toISOString().slice(0,10),needDay=day(10),missionDay=day(3);
  const {id:storeId}=await post('/api/stores',{action:'save_store',brandId:'ofd',data:{name:'기회보드 합성 지점',address:'합성 주소',tradeArea:'residential',goal:'기회 검토'}}),{id:campaignId}=await post('/api/action',{action:'save_campaign',data:{brandId:'ofd',storeId,title,goal:'연결 기회와 일정 조회'}}),{id:factId}=await post('/api/brand-facts',{action:'save_fact',confirmed:true,data:{brandId:'ofd',key:'합성 상품',value:'테스트용 상품 근거',status:'confirmed',source:'합성 운영 확인',verifiedAt:before,validUntil:after}});
  const save=(action:string,id:string,input:unknown)=>post('/api/growth',{action,id,input,campaignId,campaignVersion:1,expectedVersion:0});await save('save_signal','board-signal',{title:'시장 근거',sourceUrl:'https://example.com/market',observedAt:before,expiresAt:day(30),sourceType:'market',summary:'공개 시장 관측',sampleSize:null});
  await save('save_need','board-need',{title:'빠른 저녁 준비 기회',situation:'퇴근 후 시간 부족',desiredOutcome:'준비 단축',alternative:'배달 주문',barrier:'배송 시간',counterEvidence:'직접 조리 선호',signalIds:['board-signal'],deadline:needDay,nextAction:'구매 이유 검증',assignee:'기회 담당'});await save('save_need','board-empty',{title:'기한 미확인 기회',situation:'미확인',desiredOutcome:'',alternative:'',barrier:'',counterEvidence:'',signalIds:[],deadline:'',nextAction:'',assignee:''});
  await save('save_catalog','board-catalog',{sku:'BOARD-SKU',title:'기회 연결 상품',price:100,unitCost:20,variableCost:10,stock:0,stockUnit:'piece',currency:'KRW',taxBasis:'included',fulfillment:'배송 조건',refunds:'반품 조건',rightsConfirmed:true,factIds:[factId],validUntil:day(30)});await post('/api/growth/operations',{action:'create_inventory',campaignId,campaignVersion:1,input:{sku:'BOARD-SKU',locationId:storeId,unit:'piece',onHand:10},observedAt:before,evidenceRef:'board-stock'});
  const offer={catalogId:'board-catalog',catalogVersion:1,needId:'board-need',price:100,landingUrl:'https://example.com/buy',purchaseReason:'준비 시간을 줄이기 위해 구매',priceApproved:true};await save('save_offer','board-ready',{...offer,title:'준비 조건 확인 오퍼',quantity:2});await save('save_offer','board-held',{...offer,title:'재고 부족 오퍼',quantity:20});
  const mission={offerId:'board-ready',offerVersion:1,assignee:'운영 담당',deadline:missionDay,nextAction:'반응 확인',channel:'manual',budget:0,lossLimit:0,stopRule:'한도 도달',fulfillmentOwner:'배송 담당'};await save('save_mission','board-unknown',{...mission,title:'결과 미확인 미션'});await post('/api/growth',{action:'queue_mission',id:'board-unknown',campaignId,campaignVersion:1,expectedVersion:1});await post('/api/growth',{action:'record_receipt',id:'board-unknown',campaignId,campaignVersion:1,expectedVersion:2,input:{status:'unknown',reference:'board-review',note:'실제 외부 실행 없이 상태 검증'}});await save('save_mission','board-closed',{...mission,title:'취소된 미션',deadline:day(-1)});await post('/api/growth',{action:'cancel_mission',id:'board-closed',campaignId,campaignVersion:1,expectedVersion:1});await save('save_mission','board-orphan',{...mission,title:'연결 없는 미션',offerId:'',offerVersion:0,deadline:''});
  const open=async()=>{await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기',exact:true}).click();await page.getByRole('tab',{name:'성장·판매',exact:true}).click();await page.getByRole('navigation',{name:'성장 작업 단계',exact:true}).getByRole('button',{name:'고객·기회',exact:true}).click();const board=page.getByRole('region',{name:'기회·일정 보드',exact:true});await expect(board).toBeVisible({timeout:5000});return board};
  let board=await open();const card=board.getByRole('article',{name:'기회 빠른 저녁 준비 기회',exact:true});await expect(card).toContainText('검토 가능 오퍼 1 · 보류 오퍼 1');await expect(card).toContainText('결과 미확인 미션 있음');await expect(card).toContainText('취소됨');await expect(card).toContainText(needDay);await expect(board.getByRole('region',{name:'기한별 일정',exact:true})).toContainText(missionDay);await expect(board.getByRole('region',{name:'기한 미확인 일정',exact:true})).toContainText('연결 없는 미션');await expect(board).toContainText('매출 예측');
  await page.route('**/api/growth?campaignId=*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'합성 조회 실패'})}));await page.getByRole('region',{name:'판매 기본 기록',exact:true}).getByRole('button',{name:'새로고침',exact:true}).click();await expect(board).toContainText('이전 조회');await page.unroute('**/api/growth?campaignId=*');await page.getByRole('region',{name:'판매 기본 기록',exact:true}).getByRole('button',{name:'새로고침',exact:true}).click();await expect(board.getByText('이전 조회 결과입니다. 새로고침이 완료되기 전에는 현재 상태로 단정하지 마세요.',{exact:true})).toHaveCount(0);
  await card.getByRole('button',{name:'기회 기록 열기: 빠른 저녁 준비 기회',exact:true}).click();await expect(page.getByLabel('니즈 가설 제목',{exact:true})).toHaveValue('빠른 저녁 준비 기회');await page.getByRole('group',{name:'고객·기회 기록 목록',exact:true}).getByRole('button',{name:/기한 미확인 기회/}).click();await expect(page.getByLabel('니즈 가설 제목',{exact:true})).toHaveValue('기한 미확인 기회');await card.getByRole('button',{name:'기회 기록 열기: 빠른 저녁 준비 기회',exact:true}).click();await expect(page.getByLabel('니즈 가설 제목',{exact:true})).toHaveValue('빠른 저녁 준비 기회');await page.getByLabel('니즈 가설 제목',{exact:true}).fill('저장하지 않은 입력');await expect(board.getByRole('button',{name:'오퍼 기록 열기: 준비 조건 확인 오퍼',exact:true})).toBeDisabled();await expect(board).toContainText('저장하지 않은 입력');await expect(page.getByLabel('니즈 가설 제목',{exact:true})).toHaveValue('저장하지 않은 입력');
  await page.getByRole('button',{name:'저장 전 변경 취소',exact:true}).click();await expect(page.getByLabel('니즈 가설 제목',{exact:true})).toHaveValue('빠른 저녁 준비 기회');await expect(board.getByRole('button',{name:'오퍼 기록 열기: 준비 조건 확인 오퍼',exact:true})).toBeEnabled();board=await open();await board.getByRole('button',{name:'오퍼 기록 열기: 준비 조건 확인 오퍼',exact:true}).click();await expect(page.getByLabel('오퍼명',{exact:true})).toHaveValue('준비 조건 확인 오퍼');await page.getByRole('navigation',{name:'성장 작업 단계',exact:true}).getByRole('button',{name:'고객·기회',exact:true}).click();await board.getByRole('article',{name:'기회 빠른 저녁 준비 기회',exact:true}).getByRole('button',{name:'미션 기록 열기: 결과 미확인 미션',exact:true}).click();await expect(page.getByLabel('미션 제목',{exact:true})).toHaveValue('결과 미확인 미션');await page.getByRole('navigation',{name:'성장 작업 단계',exact:true}).getByRole('button',{name:'고객·기회',exact:true}).click();expect(await board.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await board.getByRole('heading',{name:'기회·일정 보드',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`e2e/artifacts/growth-opportunity-board-${info.project.name}.png`});
 }finally{await context.close().catch(()=>{})}
});
