import {test,expect} from '@playwright/test';
// Actual local D1/Chromium; only identity and one lost response are synthetic.
test('재발주 수요 가정·미확인과 0·판 고정 검토·충돌 입력 보존',async({browser},info)=>{
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':`reorder-${info.project.name}-${Date.now()}`}}),page=await context.newPage();
 try{
  await page.request.get('/api/workspace');const sr=await page.request.post('/api/stores',{data:{action:'save_store',brandId:'ofd',data:{name:'재발주 합성 지점',address:'합성 주소',tradeArea:'residential',goal:'재발주 가정 검토'}}});expect(sr.status()).toBe(200);const {id:storeId}=await sr.json();
  const title=`재발주 검토 ${info.project.name}`,cr=await page.request.post('/api/action',{data:{action:'save_campaign',data:{brandId:'ofd',storeId,title,goal:'수요 가정 검토'}}});expect(cr.status()).toBe(200);const {id:campaignId}=await cr.json();
  const future=new Date(Date.now()+30*86400000).toISOString().slice(0,10),today=new Date().toISOString().slice(0,10),catalogId='reorder-catalog',candidateId='reorder-candidate';
  const catalog=await page.request.post('/api/growth',{data:{action:'save_catalog',id:catalogId,expectedVersion:0,campaignId,campaignVersion:1,input:{sku:'REORDER-SKU',title:'재발주 합성 상품',taxBasis:'included',validUntil:future}}});expect(catalog.status(),await catalog.text()).toBe(200);
  const quote={catalogId,catalogVersion:1,supplierCode:'REORDER-SUPPLIER',currency:'KRW',unit:'piece',unitCost:100,moq:10,leadDays:3,shippingCost:0,extraCost:0,taxBasis:'included',validUntil:future,evidenceRef:'quote-reorder',note:''};
  const candidate=await page.request.post('/api/growth/sourcing',{data:{action:'save_candidate',id:candidateId,expectedVersion:0,campaignId,campaignVersion:1,requestId:crypto.randomUUID(),input:quote}});expect(candidate.status(),await candidate.text()).toBe(200);
  const stock=await page.request.post('/api/growth/operations',{data:{action:'create_inventory',campaignId,campaignVersion:1,input:{sku:'REORDER-SKU',locationId:storeId,unit:'piece',onHand:0},observedAt:new Date().toISOString(),evidenceRef:'reorder-stock'}});expect(stock.status(),await stock.text()).toBe(200);
  const open=async()=>{await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기',exact:true}).click();await page.getByRole('tab',{name:'성장·판매',exact:true}).click();await expect(page.locator('summary').filter({hasText:/^재발주 검토$/})).toBeVisible({timeout:5000});await page.locator('summary').filter({hasText:/^재발주 검토$/}).click();return page.getByRole('region',{name:'재발주 검토',exact:true})};
  const read=async()=>{const response=await page.request.get(`/api/growth/reorder?campaignId=${campaignId}`);expect(response.status()).toBe(200);return response.json()};
  const panel=await open(),editor=panel.getByRole('region',{name:'재발주 검토 작성',exact:true});await editor.getByRole('combobox',{name:'검토 상품 판',exact:true}).selectOption(`${catalogId}:1`);await editor.getByRole('combobox',{name:'소싱 후보 판',exact:true}).selectOption(`${candidateId}:1`);
  await editor.getByLabel('수요 가정 시작일',{exact:true}).fill(today);await editor.getByLabel('수요 가정 종료일',{exact:true}).fill(today);await editor.getByRole('textbox',{name:'수요 가정 증빙 참조',exact:true}).fill('demand-assumption');await editor.getByLabel('확보 기간 (일)',{exact:true}).fill('7');await editor.getByLabel('안전 수량',{exact:true}).fill('0');await editor.getByRole('button',{name:'재발주 검토 기록',exact:true}).click();await expect(panel.getByRole('status')).toContainText('재발주 검토를 기록했습니다.');
  let view=await read();expect(view.reviews).toHaveLength(1);expect(view.reviews[0].input.demand.quantity).toBeNull();expect(view.reviews[0].assessment.status).toBe('held');const original=view.reviews[0];
  await editor.getByLabel('기간 내 수요 가정 수량',{exact:true}).fill('0');await editor.getByRole('combobox',{name:'미입고 발주 확인',exact:true}).selectOption('confirmed_none');await editor.getByRole('textbox',{name:'미입고 발주 확인 시각(서울 시간)',exact:true}).fill(new Date(Date.now()-60000+9*3600000).toISOString().slice(0,16));await editor.getByRole('textbox',{name:'미입고 발주 확인 증빙',exact:true}).fill('no-open-orders');await editor.getByLabel('구매 비용 한도 (원)',{exact:true}).fill('0');await editor.getByRole('textbox',{name:'비용 한도 근거',exact:true}).fill('budget-zero');
  const attempts:string[]=[];let loseResponse=true;await page.route('**/api/growth/reorder',async route=>{const request=route.request();if(request.method()==='POST'){attempts.push(request.postDataJSON().requestId);if(loseResponse){loseResponse=false;const response=await route.fetch();expect(response.status(),await response.text()).toBe(200);await route.abort('failed');return;}}await route.continue();});
  await editor.getByRole('button',{name:'재발주 검토 기록',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('입력은 보존했습니다.');await editor.getByRole('button',{name:'재발주 검토 기록',exact:true}).click();await expect(panel.getByRole('status')).toContainText('재발주 검토를 기록했습니다.');expect(attempts).toHaveLength(2);expect(attempts[0]).toBe(attempts[1]);view=await read();expect(view.reviews).toHaveLength(2);expect(view.reviews.find((r:{input:{demand:{quantity:number|null}}})=>r.input.demand.quantity===0).assessment.purchaseQuantity).toBe(0);expect(view.reviews.find((r:{input:{demand:{quantity:number|null}}})=>r.input.demand.quantity===0).assessment.cashNeed).toBe(0);
  const revised=await page.request.post('/api/growth/sourcing',{data:{action:'save_candidate',id:candidateId,expectedVersion:1,campaignId,campaignVersion:1,requestId:crypto.randomUUID(),input:{...quote,unitCost:120}}});expect(revised.status(),await revised.text()).toBe(200);await editor.getByRole('textbox',{name:'재발주 검토 메모',exact:true}).fill('현재 검토 입력 보존');await editor.getByRole('button',{name:'재발주 검토 기록',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('입력은 보존했습니다.');await panel.getByRole('button',{name:'재발주 기록 새로고침',exact:true}).click();await editor.getByRole('button',{name:'현재 입력 유지하고 최신 후보 판 사용',exact:true}).click();await expect(editor.getByRole('textbox',{name:'재발주 검토 메모',exact:true})).toHaveValue('현재 검토 입력 보존');await editor.getByRole('button',{name:'재발주 검토 기록',exact:true}).click();await expect(panel.getByRole('status')).toContainText('재발주 검토를 기록했습니다.');
  view=await read();expect(view.reviews.find((r:{id:string})=>r.id===original.id).snapshotDigest).toBe(original.snapshotDigest);expect(view.reviews.find((r:{id:string})=>r.id===original.id).currentChanged).toBe(true);expect(view.mayOrder).toBe(false);
  const other=await page.request.post('/api/growth/sourcing',{data:{action:'save_candidate',id:'reorder-candidate-other',expectedVersion:0,campaignId,campaignVersion:1,requestId:crypto.randomUUID(),input:{...quote,supplierCode:'OTHER-SUPPLIER'}}});expect(other.status(),await other.text()).toBe(200);await panel.getByRole('button',{name:'재발주 기록 새로고침',exact:true}).click();await editor.getByRole('combobox',{name:'소싱 후보 판',exact:true}).selectOption('reorder-candidate-other:1');await expect(editor.getByRole('textbox',{name:'수요 가정 증빙 참조',exact:true})).toHaveValue('');await expect(editor.getByRole('textbox',{name:'미입고 발주 확인 증빙',exact:true})).toHaveValue('');await expect(editor.getByRole('textbox',{name:'재발주 검토 메모',exact:true})).toHaveValue('');
  const restored=await open();await expect(restored.getByRole('region',{name:'저장된 재발주 검토',exact:true})).toContainText('현재 근거 또는 유효 조건이 달라졌습니다.');expect(await restored.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await restored.getByRole('heading',{name:'재발주 검토',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`e2e/artifacts/growth-reorder-${info.project.name}.png`});
 }finally{await context.close().catch(()=>{})}
});
