import {test,expect} from '@playwright/test';
// Real local Chromium/D1, synthetic authentication; no external execution.
test('사업목표·30일 리뷰 불변 기록과 개정·충돌 입력 보존',async({browser},info)=>{
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':`targets-${info.project.name}-${Date.now()}`}}),page=await context.newPage();
 try{
  await page.request.get('/api/workspace');const store=await page.request.post('/api/stores',{data:{action:'save_store',brandId:'ofd',data:{name:'목표 합성 지점',address:'합성 주소',tradeArea:'residential',goal:'목표 검증'}}});expect(store.status()).toBe(200);const {id:storeId}=await store.json();const title=`목표 리뷰 ${info.project.name}`;
  const created=await page.request.post('/api/action',{data:{action:'save_campaign',data:{brandId:'ofd',storeId,title,goal:'합성 사업 목표 기록'}}});expect(created.status()).toBe(200);const {id:campaignId}=await created.json();
  const open=async()=>{await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기',exact:true}).click();await page.getByRole('tab',{name:'성장·판매',exact:true}).click();await page.locator('summary').filter({hasText:/^사업목표·30일 리뷰$/}).click();return page.getByRole('region',{name:'사업목표·30일 리뷰',exact:true})};
  const read=async()=>{const response=await page.request.get(`/api/growth/targets?campaignId=${campaignId}`);expect(response.status()).toBe(200);return response.json()};
  const panel=await open(),editor=panel.getByRole('region',{name:'사업목표 편집',exact:true});
  await editor.getByRole('textbox',{name:'목표 제목',exact:true}).fill('첫 기간 순매출 목표');await editor.getByLabel('목표값',{exact:true}).fill('0');
  const today=new Date().toISOString().slice(0,10),end=new Date(Date.now()+29*86400000).toISOString().slice(0,10);
  for(const [name,value] of [['관측 시작일',today],['관측 종료일',end],['실행 착수일',today],['중단 기준일',end],['다음 확정일',end]])await editor.getByLabel(name,{exact:true}).fill(value);
  for(const [name,value] of [['분모·집계 기준','결제 완료 주문'],['담당 역할','운영 책임자'],['자율 범위','내부 검토'],['최소 수익 조건','비용 확인 후 검토'],['필수 개선 지표','실현 순매출'],['중단 조건','손실 한도 도달'],['목표 개정 이유','최초 잠정 목표'],['미확정 사유','첫 기준선 수집 중']])await editor.getByLabel(name,{exact:true}).fill(value);
  await editor.getByLabel('최대 탐색 손실 (원)',{exact:true}).fill('0');await editor.getByRole('button',{name:'사업목표 저장',exact:true}).click();await expect(panel.getByRole('status')).toContainText('사업목표를 저장했습니다.');
  let v=await read();const targetId=v.targets[0].id;expect(v.targets[0].input.baseline).toBeNull();expect(v.targets[0].input.targetValue).toBe(0);
  const review=panel.getByRole('region',{name:'30일 리뷰 작성',exact:true});await review.getByRole('combobox',{name:'리뷰할 목표 판',exact:true}).selectOption(`${targetId}:1`);
  for(const [name,value] of [['투입 자원·비용 근거','비용 미확인'],['고객 질문·반품 원인','운영 관측 대기'],['대표 예외 처리','별도 예외 없음'],['다음 행동','비용 증빙 확인'],['다음 30일 계획','허용 범위 판매 관측']])await review.getByRole('textbox',{name,exact:true}).fill(value);
  await review.getByRole('button',{name:'30일 리뷰 기록',exact:true}).click();await expect(panel.getByRole('status')).toContainText('30일 리뷰를 기록했습니다.');await expect(panel.getByRole('region',{name:'저장된 30일 리뷰',exact:true})).toContainText('중간 리뷰');
  const initialReview=(await read()).reviews[0];const order=await page.request.post('/api/store-operations',{data:{action:'save_order',storeId,data:{source:'direct',orderNumber:'TARGET-ORDER',orderDate:today,mode:'delivery',status:'paid',paidAmount:1000,refundAmount:0,channel:'unknown',campaignId,attributionEvidence:'synthetic-campaign-proof'}}});expect(order.status(),await order.text()).toBe(200);
  await panel.getByRole('button',{name:'최신 장부와 대조',exact:true}).click();await expect(panel.getByLabel('최신 장부 대조 결과',{exact:true})).toContainText('최신 장부가 달라졌습니다.');expect((await read()).reviews[0].snapshotDigest).toBe(initialReview.snapshotDigest);
  await editor.getByRole('combobox',{name:'목표 상태',exact:true}).selectOption('confirmed');await editor.getByLabel('기준선',{exact:true}).fill('0');await editor.getByRole('textbox',{name:'목표 제목',exact:true}).fill('수정한 다음 목표');await editor.getByLabel('목표값',{exact:true}).fill('1000');await editor.getByRole('textbox',{name:'목표 개정 이유',exact:true}).fill('초기 관측 반영');await editor.getByRole('button',{name:'사업목표 저장',exact:true}).click();await expect(panel.getByRole('status')).toContainText('사업목표를 저장했습니다.');v=await read();expect(v.targets[0].version).toBe(2);expect(v.targets[0].input.status).toBe('confirmed');expect(v.targets[0].input.baseline).toBe(0);expect(v.reviews[0].targetVersion).toBe(1);await expect(panel.getByRole('region',{name:'저장된 30일 리뷰',exact:true})).toContainText('첫 기간 순매출 목표');
  const row=v.targets[0],remote=await page.request.post('/api/growth/targets',{data:{action:'save_target',requestId:crypto.randomUUID(),id:row.id,expectedVersion:row.version,campaignId,campaignVersion:v.campaignVersion,input:{...row.input,title:'다른 운영자의 목표',changeReason:'동시 변경 검증'}}});expect(remote.status(),await remote.text()).toBe(200);
  await editor.getByRole('textbox',{name:'목표 제목',exact:true}).fill('현재 목표 입력 보존');await editor.getByRole('button',{name:'사업목표 저장',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('입력은 보존했습니다.');await panel.getByRole('button',{name:'목표·리뷰 새로고침',exact:true}).click();await editor.getByRole('button',{name:'현재 입력을 유지하고 최신 목표 버전 사용',exact:true}).click();await expect(editor.getByRole('textbox',{name:'목표 제목',exact:true})).toHaveValue('현재 목표 입력 보존');await editor.getByRole('button',{name:'사업목표 저장',exact:true}).click();await expect(panel.getByRole('status')).toContainText('사업목표를 저장했습니다.');v=await read();expect(v.targets[0].version).toBe(4);expect(v.reviews[0].targetVersion).toBe(1);
  const box=await panel.boundingBox();expect(box!.x+box!.width).toBeLessThanOrEqual((page.viewportSize()?.width??1280)+1);expect(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await panel.getByRole('heading',{name:'사업목표·30일 리뷰',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`e2e/artifacts/growth-targets-${info.project.name}.png`});
 }finally{await context.close().catch(()=>{})}
});
