import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
// Real local D1/API/browser; stored provider observations are synthetic. No collection or provider calls.
function fixture(owner:string,kind:string,id:string,parent:string,data:unknown){
 const quote=(value:string)=>`'${value.replaceAll("'","''")}'`,folder=mkdtempSync(join(tmpdir(),'collective-observation-'));
 try{const path=join(folder,'fixture.sql');writeFileSync(path,`INSERT INTO records(id,owner,kind,parent_id,data,updated_at) VALUES(${[`${owner}:${kind}:${id}`,owner,kind,parent,JSON.stringify(data),new Date().toISOString()].map(quote).join(',')}) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at;`);execFileSync(process.execPath,['--import','./scripts/sites-env.mjs','./node_modules/wrangler/bin/wrangler.js','d1','execute','DB','--config','dist/server/wrangler.json','--local','--persist-to','e2e/.state','--file',path],{stdio:'pipe'});}finally{rmSync(folder,{recursive:true,force:true})}
}

test('발행 이후 저장 관측 조회·기간 유지·기존 화면 이동',async({browser},info)=>{
 const owner=`observation-${info.project.name}-${Date.now()}`,context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':owner}}),page=await context.newPage();
 try{
  await page.request.get('/api/workspace');const title=`발행 관측 ${info.project.name}`,response=await page.request.post('/api/action',{data:{action:'save_campaign',data:{brandId:'ofd',title,goal:'기존 관측 읽기'}}});expect(response.status(),await response.text()).toBe(200);const {id:campaignId}=await response.json();
  await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기',exact:true}).click();await page.getByRole('tab',{name:'성장·판매',exact:true}).click();await expect(page.locator('summary').filter({hasText:/^발행 이후 관측$/})).toBeVisible({timeout:5000});await page.locator('summary').filter({hasText:/^발행 이후 관측$/}).click();
  const panel=page.getByRole('region',{name:'발행 이후 관측',exact:true});await expect(panel.getByText('연결된 발행이 없습니다.')).toBeVisible();const from=panel.getByLabel('주문 조회 시작일',{exact:true}),to=panel.getByLabel('주문 조회 종료일',{exact:true});await expect(from).not.toHaveValue('');await expect(to).not.toHaveValue('');await from.fill('2026-01-01');await to.fill('2026-01-07');await panel.getByRole('button',{name:'저장된 관측 조회',exact:true}).click();await expect(panel.getByText('주문 조회 기간: 2026-01-01 ~ 2026-01-07',{exact:true})).toBeVisible();expect(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
  const stamp='2026-01-08T03:00:00.000Z',window={from:'2026-01-01',to:'2026-01-07'},source={id:'observation-e:control',experimentId:'observation-e',publicationId:'observation-p',channel:'instagram',arm:'control',target:'123',window,lastFetchedAt:stamp,lastError:null};
  fixture(owner,'campaign',campaignId,'',{id:campaignId,brandId:'ofd',storeId:'observation-store',version:1,status:'active',title,goal:'읽기 관측'});fixture(owner,'store','observation-store','ofd',{id:'observation-store',brandId:'ofd',name:'합성 지점'});
  fixture(owner,'growth_publication_link','observation-l',campaignId,{id:'observation-l',campaignId,brandId:'ofd',intentId:'observation-i',publicationId:'observation-p',version:1,status:'published',lastPublicationVersion:1,updatedAt:stamp,snapshot:{approvedPublicationVersion:1,confirmedBy:owner,confirmedAt:stamp,evidenceRef:'synthetic-observation',publication:{caption:'합성 관측 게시',scheduledAt:'2026-01-01T00:00:00Z',plannedCostKRW:0,creativeId:'observation-creative',creativeVersion:1}}});fixture(owner,'growth_action_intent','observation-i',campaignId,{id:'observation-i',campaignId,brandId:'ofd',storeId:'observation-store',version:1,state:'observed',input:{missionId:'observation-mission',quantity:1,recoveryOwner:'합성 확인자',recoveryDueAt:stamp},snapshot:{mission:{channel:'organic'}}});fixture(owner,'execution_publication','observation-p',campaignId,{id:'observation-p',campaignId,campaignVersion:1,creativeId:'observation-creative',creativeVersion:1,version:1,caption:'합성 관측 게시',factRefs:[],plannedCostKRW:0,createdAt:stamp,status:'published',experimentId:'observation-e',arm:'control',media:{mediaId:'123'},scheduledAt:'2026-01-01T00:00:00Z'});fixture(owner,'viral_experiment','observation-e',campaignId,{id:'observation-e',campaignId,brandId:'ofd',channel:'Instagram',metric:'share_rate',status:'running'});fixture(owner,'measurement_source',source.id,'observation-e',source);fixture(owner,'measurement_draft','observation-e',campaignId,{id:'observation-e',experimentId:'observation-e',channel:'instagram',arms:{control:{value:{denominator:0,numerator:0,source:'PRIVATE-RAW-SOURCE'},target:'123',credential:{level:'store',brandId:'ofd',storeId:'observation-store'},window,fetchedAt:stamp,definition:'PRIVATE-RAW-DEFINITION',limitations:[]}}});
  await panel.getByRole('button',{name:'저장된 관측 조회',exact:true}).click();const row=panel.getByRole('article',{name:'발행 관측 observation-p',exact:true});await expect(row.getByText('분모 관측값: 0 · 분자 관측값: 0',{exact:true})).toBeVisible();await expect(row).toContainText('귀속된 주문 기록이 없습니다');await expect(row).not.toContainText('PRIVATE-RAW');
  const order={id:'observation-order',storeId:'observation-store',campaignId,source:'pos',orderNumber:'SYNTHETIC-OBS',orderDate:'2026-01-03',mode:'pickup',status:'refunded',paidAmount:100,refundAmount:100,costs:{foodCost:0,packagingCost:0,fees:0,deliveryCost:0,benefitCost:0},channel:'instagram',experimentId:'observation-e',attributionEvidence:'합성 내부 귀속',note:'',version:1,createdAt:stamp,updatedAt:stamp,codeAttribution:{codeId:'observation-code',code:'OBS',publicationId:'observation-p',conflictCodeIds:[]}};fixture(owner,'store_order',order.id,'observation-store',order);fixture(owner,'store_order','other-order','observation-store',{...order,id:'other-order',status:'paid',paidAmount:9999,refundAmount:0,codeAttribution:undefined});await panel.getByRole('button',{name:'저장된 관측 조회',exact:true}).click();await expect(row.getByText('장부 기록: 1 · 주문: 0 · 신규 고객: 0',{exact:true})).toBeVisible();await expect(row).toContainText('순매출(장부 관측): 0원');await expect(row).not.toContainText('9,999');
  fixture(owner,'measurement_source',source.id,'observation-e',{...source,lastError:'PRIVATE-UPSTREAM-ERROR',errorCode:'reauth_required'});await panel.getByRole('button',{name:'저장된 관측 조회',exact:true}).click();await expect(row.getByText('분모 관측값: 미확인 · 분자 관측값: 미확인',{exact:true})).toBeVisible();await expect(row).toContainText('수집 실패');await expect(row).not.toContainText('PRIVATE-UPSTREAM');
  fixture(owner,'measurement_source',source.id,'observation-e',{...source,stopped:true,stoppedReason:'실험이 종료되어 수집을 멈췄습니다.',lastFetchedAt:'2026-01-09T00:00:00Z'});await panel.getByRole('button',{name:'저장된 관측 조회',exact:true}).click();await expect(row.getByRole('heading',{name:'수집 종료 · 과거 성공 관측',exact:true})).toBeVisible();await expect(row.getByText('분모 관측값: 0 · 분자 관측값: 0',{exact:true})).toBeVisible();
  await page.route('**/api/growth/publication-observation?**',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'PRIVATE-RAW-ERROR'})}));await from.fill('2026-01-02');await panel.getByRole('button',{name:'저장된 관측 조회',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('입력은 보존했습니다.');await expect(from).toHaveValue('2026-01-02');await expect(panel).not.toContainText('PRIVATE-RAW-ERROR');await expect(panel).toContainText('아래는 이전 조회 결과입니다.');await page.unroute('**/api/growth/publication-observation?**');await panel.getByRole('button',{name:'저장된 관측 조회',exact:true}).click();await expect(panel.getByRole('alert')).toHaveCount(0);expect(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await panel.getByRole('heading',{name:'발행 이후 관측',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`e2e/artifacts/growth-publication-observation-${info.project.name}.png`});
  await panel.getByRole('button',{name:'제작·발행 열기',exact:true}).click();await expect(page.getByRole('tab',{name:'제작·발행',exact:true})).toHaveAttribute('aria-selected','true');await page.getByRole('tab',{name:'성장·판매',exact:true}).click();const summary=page.locator('summary').filter({hasText:/^발행 이후 관측$/});if(!await summary.evaluate(el=>el.parentElement?.hasAttribute('open')))await summary.click();await page.getByRole('region',{name:'발행 이후 관측',exact:true}).getByRole('button',{name:'성과 열기',exact:true}).click();await expect(page.getByRole('tab',{name:'성과',exact:true})).toHaveAttribute('aria-selected','true');
 }finally{await context.close().catch(()=>{})}
});
