import {test,expect} from '@playwright/test';
// Local D1 and actual browser/API; synthetic owner header, no external dispatch.
test('수요 단계 순서·미확인 비용·재조회·동시 수정 입력 보존',async({browser},info)=>{
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':`demand-${info.project.name}-${Date.now()}`}}),page=await context.newPage();
 try{
  await page.request.get('/api/workspace');const title=`수요 계획 ${info.project.name}`;
  const created=await page.request.post('/api/action',{data:{action:'save_campaign',data:{brandId:'ofd',title,goal:'합성 수요 계획'}}});expect(created.status()).toBe(200);const {id:campaignId}=await created.json();
  const open=async()=>{await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기',exact:true}).click();await page.getByRole('tab',{name:'성장·판매',exact:true}).click();await page.locator('summary').filter({hasText:'수요 시퀀스·콘텐츠·협업'}).click();return page.getByRole('region',{name:'수요 시퀀스',exact:true})};
  const read=async()=>{const r=await page.request.get(`/api/growth/demand?campaignId=${campaignId}`);expect(r.status()).toBe(200);return r.json()};
  let panel=await open();await panel.getByLabel('시퀀스 제목',{exact:true}).fill('선물 구매 경로');await panel.getByRole('textbox',{name:'검증할 수요 가설·목표',exact:true}).fill('상황 설명 후 구매 이유 전달');
  await panel.getByRole('button',{name:'수요 단계 하나 더',exact:true}).click();let first=panel.getByRole('group',{name:'수요 단계 1',exact:true});
  await first.getByRole('textbox',{name:'전달 메시지',exact:true}).fill('먼저 사용 장면 소개');await first.getByRole('combobox',{name:'노출 방식',exact:true}).selectOption('creator');await expect(first.getByLabel('예상 비용 (원 · 미확인은 빈칸)',{exact:true})).toHaveValue('');
  await panel.getByRole('button',{name:'수요 단계 하나 더',exact:true}).click();const second=panel.getByRole('group',{name:'수요 단계 2',exact:true});await second.getByRole('textbox',{name:'전달 메시지',exact:true}).fill('이어서 구매 이유 소개');await second.getByRole('button',{name:'위로',exact:true}).click();
  await panel.getByRole('button',{name:'수요 시퀀스 저장',exact:true}).click();await expect(panel.getByRole('status')).toContainText('수요 시퀀스를 저장했습니다.');let v=await read();expect(v.sequences[0].input.steps[0].message).toBe('이어서 구매 이유 소개');expect(v.sequences[0].readiness.plannedCost).toBeNull();expect(v.mayExecute).toBe(false);
  await page.reload();panel=await open();await panel.getByRole('group',{name:'수요 시퀀스 목록'}).getByRole('button',{name:/선물 구매 경로/}).click();first=panel.getByRole('group',{name:'수요 단계 1',exact:true});await expect(first.getByRole('textbox',{name:'전달 메시지',exact:true})).toHaveValue('이어서 구매 이유 소개');
  for(let i=1;i<=2;i++)await panel.getByRole('group',{name:`수요 단계 ${i}`,exact:true}).getByLabel('예상 비용 (원 · 미확인은 빈칸)',{exact:true}).fill('0');await panel.getByRole('button',{name:'수요 시퀀스 저장',exact:true}).click();await expect(panel.getByLabel('수요 시퀀스 준비 상태',{exact:true})).toContainText('예상 비용 합계: 0원');await expect(panel.getByLabel('수요 시퀀스 준비 상태',{exact:true})).toContainText('권리');
  v=await read();const row=v.sequences[0];const changed=await page.request.post('/api/growth/demand',{data:{action:'save_sequence',campaignId,campaignVersion:v.campaignVersion,id:row.id,expectedVersion:row.version,input:{...row.input,title:'다른 운영자의 수정'}}});expect(changed.status()).toBe(200);
  await panel.getByLabel('시퀀스 제목',{exact:true}).fill('현재 입력 보존');await panel.getByRole('button',{name:'수요 시퀀스 저장',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('입력은 보존했습니다.');await expect(panel.getByLabel('시퀀스 제목',{exact:true})).toHaveValue('현재 입력 보존');
  await panel.getByRole('button',{name:'수요 기록 새로고침',exact:true}).click();await panel.getByRole('button',{name:'현재 입력 유지 · 최신 버전 기준 사용',exact:true}).click();await panel.getByRole('button',{name:'수요 시퀀스 저장',exact:true}).click();await expect(panel.getByRole('status')).toContainText('수요 시퀀스를 저장했습니다.');v=await read();expect(v.sequences[0].version).toBe(4);expect(v.sequences[0].input.title).toBe('현재 입력 보존');
  const box=await panel.boundingBox();expect(box!.x+box!.width).toBeLessThanOrEqual((page.viewportSize()?.width??1280)+1);expect(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await panel.getByRole('heading',{name:'수요 시퀀스',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`e2e/artifacts/growth-demand-${info.project.name}.png`});
 }finally{await context.close()}
});
