import {test,expect} from '@playwright/test';

// Real local browser/D1; synthetic owner authentication. No external dispatch.
test('판매 실비 대사·무집행 취소 원자 해제·재조회',async({browser},info)=>{
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':`reconciliation-${info.project.name}-${Date.now()}`}}),page=await context.newPage();
 try{
  const post=async(path:string,data:unknown)=>{const r=await page.request.post(path,{data});expect(r.status(),await r.text()).toBe(200);return r.json()};
  await page.request.get('/api/workspace');
  const before=new Date(Date.now()-86400000).toISOString(),after=new Date(Date.now()+30*86400000).toISOString(),day=after.slice(0,10);
  const {id:storeId}=await post('/api/stores',{action:'save_store',brandId:'ofd',data:{name:'예약 합성 지점',address:'합성 주소',tradeArea:'residential',goal:'판매 준비'}});
  const title=`판매 대사 ${info.project.name}`,{id:campaignId}=await post('/api/action',{action:'save_campaign',data:{brandId:'ofd',storeId,title,goal:'합성 예약 검증'}});
  const {id:factId}=await post('/api/brand-facts',{action:'save_fact',confirmed:true,data:{brandId:'ofd',key:'합성 상품',value:'테스트용 상품 근거',status:'confirmed',source:'합성 운영 확인',verifiedAt:before,validUntil:after}});
  const save=(action:string,id:string,input:unknown)=>post('/api/growth',{action,id,input,campaignId,campaignVersion:1,expectedVersion:0});
  await save('save_signal','exec-signal',{title:'시장 근거',sourceUrl:'https://example.com/market',observedAt:before,expiresAt:day,sourceType:'market',summary:'공개 관측',sampleSize:null});
  await save('save_need','exec-need',{title:'니즈 가설',situation:'상황',desiredOutcome:'준비 단축',alternative:'기존 대안',barrier:'배송',counterEvidence:'직접 조리',signalIds:['exec-signal'],deadline:day,nextAction:'확인',assignee:'검토 담당'});
  await save('save_catalog','exec-catalog',{sku:'EXEC-SKU',title:'예약 상품',price:100,unitCost:20,variableCost:10,stock:20,stockUnit:'piece',currency:'KRW',taxBasis:'included',fulfillment:'배송 조건',refunds:'반품 조건',rightsConfirmed:true,factIds:[factId],validUntil:day});
  await save('save_offer','exec-offer',{title:'예약 오퍼',catalogId:'exec-catalog',catalogVersion:1,needId:'exec-need',price:100,quantity:2,landingUrl:'https://example.com/buy',purchaseReason:'준비 단축',priceApproved:true});
  await save('save_mission','exec-mission',{title:'수동 판매 미션',offerId:'exec-offer',offerVersion:1,assignee:'판매 담당',deadline:day,nextAction:'판매 준비',channel:'manual',budget:100,lossLimit:20,stopRule:'한도 도달',fulfillmentOwner:'배송 담당'});
  await post('/api/growth/operations',{action:'create_inventory',campaignId,campaignVersion:1,input:{sku:'EXEC-SKU',locationId:storeId,unit:'piece',onHand:10},observedAt:before,evidenceRef:'warehouse-opening'});
  await post('/api/growth',{action:'queue_mission',id:'exec-mission',campaignId,campaignVersion:1,expectedVersion:1});
  await post('/api/growth/authority',{action:'save_authority',id:'exec-authority',campaignId,campaignVersion:1,expectedVersion:0,sign:true,input:{accountId:'manual-seller',channel:'manual',status:'active',maxTier:'T3',allowedActions:['publish','spend'],startsAt:before,expiresAt:after,periodStart:before,periodEnd:after,totalCap:1000,dayCap:1000,weekCap:1000,lossCap:1000}});
  const read=async()=>{const r=await page.request.get(`/api/growth/execution?campaignId=${campaignId}`);expect(r.status(),await r.text()).toBe(200);return r.json()};
  const open=async()=>{await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기',exact:true}).click();await page.getByRole('tab',{name:'성장·판매',exact:true}).click();await page.locator('summary').filter({hasText:/^일반 판매 실행 준비·결과$/}).click();return page.getByRole('region',{name:'일반 판매 실행 준비',exact:true})};
  let v=await read();
  await post('/api/growth/execution',{action:'prepare_execution',campaignId,campaignVersion:v.campaignVersion,input:{missionId:'exec-mission',missionVersion:2,authorityId:'exec-authority',authorityVersion:1,inventoryId:v.inventory[0].id,inventoryVersion:v.inventory[0].version,quantity:2,recoveryOwner:'대사 담당',recoveryDueAt:after,evidenceRef:'reconciliation-preparation'}});
  const panel=await open();await panel.getByRole('complementary',{name:'판매 실행 기록',exact:true}).getByRole('button',{name:/수동 판매 미션/}).click();
  const receipt=panel.getByRole('group',{name:'실행 결과 확인 기록',exact:true});await receipt.getByRole('combobox',{name:'확인 상태',exact:true}).selectOption('failed');await receipt.getByRole('textbox',{name:'결과 증빙 내부 ID',exact:true}).fill('failed-check');await receipt.getByRole('textbox',{name:'결과 확인 내용',exact:true}).fill('운영자가 실패 확인');await receipt.getByRole('button',{name:'실행 결과 기록',exact:true}).click();await expect(panel.getByRole('status')).toContainText('실행 결과를 기록했습니다.');
  v=await read();expect(v.inventory[0].projection.reserved).toBe(2);
  const reconciliation=panel.getByRole('region',{name:'실비·손실 대사',exact:true});await reconciliation.getByRole('button',{name:'현재 대사 입력 유지 · 최신 판 사용',exact:true}).click();await reconciliation.getByRole('combobox',{name:'대사 방식',exact:true}).selectOption('release');await expect(reconciliation.getByRole('spinbutton',{name:'확인한 실비 (원)',exact:true})).toHaveValue('');await expect(reconciliation.getByRole('button',{name:'대사 기록 저장',exact:true})).toBeDisabled();
  await reconciliation.getByRole('spinbutton',{name:'확인한 실비 (원)',exact:true}).fill('0');await reconciliation.getByRole('spinbutton',{name:'확인한 실손실 (원)',exact:true}).fill('0');await reconciliation.getByRole('textbox',{name:'대사 증빙 내부 ID',exact:true}).fill('cancel-proof');await reconciliation.getByRole('textbox',{name:'대사 확인 내용',exact:true}).fill('외부 접수 없음과 잔여 의무 없음 확인');await reconciliation.getByRole('checkbox',{name:'외부 접수·집행이 없었음을 확인했습니다',exact:true}).check();await reconciliation.getByRole('checkbox',{name:'잔여 지급·이행 의무가 없음을 확인했습니다',exact:true}).check();
  const intent=v.intents[0],commitment=v.commitments.find((row:{id:string})=>row.id===intent.commitmentId);await post('/api/growth/execution',{action:'reconcile_execution',campaignId,campaignVersion:v.campaignVersion,id:intent.id,expectedVersion:intent.version,commitmentVersion:commitment.version??1,missionVersion:intent.currentMissionVersion,inventoryVersion:v.inventory[0].version,requestId:crypto.randomUUID(),input:{mode:'partial',actualAmount:0,actualLoss:0,evidenceRef:'parallel-check',note:'동시 부분 확인',noExecution:false,noOutstandingObligations:false}});
  await reconciliation.getByRole('button',{name:'대사 기록 저장',exact:true}).click();await expect(reconciliation.getByRole('alert')).toContainText('입력은 보존했습니다.');await panel.getByRole('button',{name:'실행 준비 새로고침',exact:true}).click();await reconciliation.getByRole('button',{name:'현재 대사 입력 유지 · 최신 판 사용',exact:true}).click();await expect(reconciliation.getByRole('textbox',{name:'대사 증빙 내부 ID',exact:true})).toHaveValue('cancel-proof');
  let savedPayload:Record<string,unknown>|null=null;const releaseRequests:Record<string,unknown>[]=[];page.on('request',request=>{if(request.url().includes('/api/growth/execution')&&request.method()==='POST'){const body=request.postDataJSON();if(body.action==='reconcile_execution'&&body.input.mode==='release'){savedPayload=body;releaseRequests.push(body);}}});
  let loseResponse=true,ackResponse=true;await page.route('**/api/growth/execution',async route=>{const body=route.request().method()==='POST'?route.request().postDataJSON():null;if(body?.action==='reconcile_execution'&&body.input.mode==='release'&&(loseResponse||ackResponse)){const committed=await route.fetch();expect(committed.status()).toBe(200);if(loseResponse){loseResponse=false;await route.abort('failed');}else{ackResponse=false;await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({reconciled:true,viewUnavailable:true,duplicate:true,resultIntentId:body.id,mayExecute:false})});}}else await route.continue();});
  await reconciliation.getByRole('button',{name:'대사 기록 저장',exact:true}).click();await expect(reconciliation.getByRole('alert')).toContainText('입력은 보존했습니다.');await reconciliation.getByRole('button',{name:'대사 기록 저장',exact:true}).click();await expect(reconciliation.getByRole('status')).toContainText('대사 저장 완료 · 최신 목록 조회 불가');await expect(reconciliation.getByRole('button',{name:'대사 기록 저장',exact:true})).toBeDisabled();let failRead=true;await page.route('**/api/growth/execution?**',async route=>{if(failRead){failRead=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'합성 목록 조회 실패'})});}else await route.continue();});await panel.getByRole('button',{name:'실행 준비 새로고침',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('합성 목록 조회 실패');await expect(reconciliation.getByRole('status')).toContainText('대사 저장 완료');expect(releaseRequests).toHaveLength(2);expect(releaseRequests[0].requestId).toBe(releaseRequests[1].requestId);v=await read();expect(v.inventory[0].projection.reserved).toBe(0);expect(v.inventory[0].projection.available).toBe(10);expect(v.commitments[0].commitment.status).toBe('released');expect(v.commitments[0].commitment.actualAmount).toBe(0);expect(v.reconciliations).toHaveLength(2);expect(savedPayload).not.toBeNull();
  const duplicate=await post('/api/growth/execution',savedPayload);expect(duplicate.reconciliations).toHaveLength(2);expect(duplicate.inventory[0].projection.reserved).toBe(0);await panel.getByRole('button',{name:'실행 준비 새로고침',exact:true}).click();await expect(reconciliation.getByRole('region',{name:'실비 대사 이력',exact:true})).toContainText('cancel-proof');await expect(reconciliation.getByRole('status')).toContainText('최신 상태를 확인했습니다.');await expect(reconciliation.getByRole('button',{name:'대사 기록 저장',exact:true})).toBeDisabled();expect(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await reconciliation.getByRole('heading',{name:'실비·손실 대사',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`e2e/artifacts/growth-reconciliation-${info.project.name}.png`});

 }finally{await context.close().catch(()=>{})}
});
