import {test,expect} from '@playwright/test';
// Local browser and D1; synthetic owner identity, no external analytics or dispatch.
test('구매 병목 초안·전후 null/0·음수 이익·재조회·충돌 입력 보존',async({browser},info)=>{
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':`journey-${info.project.name}-${Date.now()}`}}),page=await context.newPage();
 try{
  await page.request.get('/api/workspace');const title=`병목 계획 ${info.project.name}`;
  const created=await page.request.post('/api/action',{data:{action:'save_campaign',data:{brandId:'ofd',title,goal:'합성 구매 병목 검토'}}});expect(created.status()).toBe(200);const {id:campaignId}=await created.json();
  const open=async()=>{await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기',exact:true}).click();await page.getByRole('tab',{name:'성장·판매',exact:true}).click();await page.locator('summary').filter({hasText:'구매 병목·개선 전후 관측'}).click();return page.getByRole('region',{name:'구매 병목',exact:true})};
  const read=async()=>{const r=await page.request.get(`/api/growth/journey?campaignId=${campaignId}`);expect(r.status()).toBe(200);return r.json()};
  let panel=await open();await panel.getByRole('textbox',{name:'병목 제목',exact:true}).fill('배송 조건 확인');await panel.getByRole('combobox',{name:'구매 단계',exact:true}).selectOption('checkout');await panel.getByRole('textbox',{name:'병목 가설',exact:true}).fill('배송 안내 이해 여부 확인');
  await panel.locator('summary').filter({hasText:'개선 전 관측'}).click();await panel.locator('summary').filter({hasText:'개선 후 관측'}).click();
  let before=panel.getByRole('group',{name:'개선 전 관측 입력',exact:true}),after=panel.getByRole('group',{name:'개선 후 관측 입력',exact:true});
  await expect(before.getByRole('spinbutton',{name:'분모 수',exact:true})).toHaveValue('');await after.getByRole('spinbutton',{name:'분모 수',exact:true}).fill('0');await before.getByRole('spinbutton',{name:'공헌이익 (원)',exact:true}).fill('-500');await after.getByRole('spinbutton',{name:'공헌이익 (원)',exact:true}).fill('0');
  await panel.getByRole('button',{name:'구매 병목 저장',exact:true}).click();await expect(panel.getByRole('status')).toContainText('구매 병목을 저장했습니다.');let v=await read();expect(v.blockers[0].input.before.denominator).toBeNull();expect(v.blockers[0].input.after.denominator).toBe(0);expect(v.blockers[0].input.before.contributionProfit).toBe(-500);expect(v.blockers[0].assessment.comparison.status).toBe('held');expect(v.blockers[0].assessment.comparison.profitDelta).toBeNull();expect(v.mayExecute).toBe(false);
  await page.reload();panel=await open();await panel.getByRole('group',{name:'구매 병목 목록'}).getByRole('button',{name:/배송 조건 확인/}).click();await panel.locator('summary').filter({hasText:'개선 전 관측'}).click();await panel.locator('summary').filter({hasText:'개선 후 관측'}).click();before=panel.getByRole('group',{name:'개선 전 관측 입력',exact:true});after=panel.getByRole('group',{name:'개선 후 관측 입력',exact:true});await expect(before.getByRole('spinbutton',{name:'분모 수',exact:true})).toHaveValue('');await expect(after.getByRole('spinbutton',{name:'분모 수',exact:true})).toHaveValue('0');await expect(before.getByRole('spinbutton',{name:'공헌이익 (원)',exact:true})).toHaveValue('-500');await expect(panel.getByLabel('구매 병목 평가',{exact:true})).toContainText('관측 차이이며 인과효과 미검증');
  v=await read();const row=v.blockers[0];const changed=await page.request.post('/api/growth/journey',{data:{action:'save_blocker',campaignId,campaignVersion:v.campaignVersion,id:row.id,expectedVersion:row.version,input:{...row.input,title:'다른 운영자의 병목 수정'}}});expect(changed.status()).toBe(200);
  await panel.getByRole('textbox',{name:'병목 제목',exact:true}).fill('현재 병목 입력 보존');await panel.getByRole('button',{name:'구매 병목 저장',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('입력은 보존했습니다.');await expect(panel.getByRole('textbox',{name:'병목 제목',exact:true})).toHaveValue('현재 병목 입력 보존');
  await panel.getByRole('button',{name:'병목 기록 새로고침',exact:true}).click();await panel.getByRole('button',{name:'현재 입력을 유지하고 최신 버전 기준 사용',exact:true}).click();await panel.getByRole('button',{name:'구매 병목 저장',exact:true}).click();await expect(panel.getByRole('status')).toContainText('구매 병목을 저장했습니다.');v=await read();expect(v.blockers[0].version).toBe(3);expect(v.blockers[0].input.title).toBe('현재 병목 입력 보존');
  const box=await panel.boundingBox();expect(box!.x+box!.width).toBeLessThanOrEqual((page.viewportSize()?.width??1280)+1);expect(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await panel.getByRole('heading',{name:'구매 병목',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`e2e/artifacts/growth-journey-${info.project.name}.png`});
 }finally{await context.close()}
});
