import {test,expect} from '@playwright/test';
// Real local Chromium/D1, synthetic authentication; no customer messages.
test('소비자 목적별 동의·주문 연결·재구매 후보·철회 영속성',async({browser},info)=>{
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':`consumer-${info.project.name}-${Date.now()}`}}),page=await context.newPage();
 try{
  await page.request.get('/api/workspace');
  const sr=await page.request.post('/api/stores',{data:{action:'save_store',brandId:'ofd',data:{name:'동의 합성 지점',address:'합성 주소',tradeArea:'residential',goal:'동의 분리 검증'}}});expect(sr.status()).toBe(200);const {id:storeId}=await sr.json();
  const title=`소비자 동의 ${info.project.name}`,cr=await page.request.post('/api/action',{data:{action:'save_campaign',data:{brandId:'ofd',storeId,title,goal:'합성 재구매 후보 검토'}}});expect(cr.status()).toBe(200);const {id:campaignId}=await cr.json();
  const order=await page.request.post('/api/store-operations',{data:{action:'save_order',storeId,data:{source:'direct',orderNumber:'CONSENT-ORDER',orderDate:new Date().toISOString().slice(0,10),mode:'delivery',status:'paid',paidAmount:10000,refundAmount:0,channel:'unknown'}}});expect(order.status()).toBe(200);const {ids:[orderId]}=await order.json();
  const open=async()=>{await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기',exact:true}).click();await page.getByRole('tab',{name:'성장·판매',exact:true}).click();await page.locator('summary').filter({hasText:/^소비자 동의·재구매 검토$/}).click();return page.getByRole('region',{name:'소비자 동의·재구매',exact:true})};
  let panel=await open();await panel.getByRole('button',{name:'새 가명 소비자 생성',exact:true}).click();await expect(panel.getByRole('status')).toContainText('가명 소비자를 생성했습니다.');
  const grant=async(purpose:string)=>{await panel.getByRole('combobox',{name:'동의 목적',exact:true}).selectOption(purpose);await panel.getByLabel('고지문 버전',{exact:true}).fill('notice-v1');await panel.getByLabel('동의 증빙 내부 ID',{exact:true}).fill('consent-proof');await panel.getByLabel('동의 확인 시각 (시간대 포함)',{exact:true}).fill(new Date(Date.now()-60_000).toISOString());await panel.getByLabel('동의 만료 시각 (시간대 포함)',{exact:true}).fill(new Date(Date.now()+86_400_000).toISOString());await panel.getByRole('button',{name:'선택 목적 동의 기록',exact:true}).click();await expect(panel.getByRole('status')).toContainText('목적별 동의를 기록했습니다.');};
  await grant('identity_link');await grant('marketing_reorder');await panel.getByRole('combobox',{name:'연결할 지점 주문',exact:true}).selectOption(orderId);await panel.getByLabel('동일인 연결 증빙 내부 ID',{exact:true}).fill('identity-proof');await panel.getByRole('button',{name:'운영자 확인으로 주문 연결',exact:true}).click();await expect(panel.getByRole('status')).toContainText('주문을 연결했습니다.');
  await panel.getByRole('spinbutton',{name:'재구매 검토 대기일',exact:true}).fill('0');await panel.getByRole('button',{name:'대기일 적용',exact:true}).click();await expect(panel.getByLabel('소비자 적격성',{exact:true})).toContainText('재구매 검토: 후보');await expect(panel.getByLabel('소비자 적격성',{exact:true})).toContainText('구매 후 관리: 보류');
  await panel.getByRole('button',{name:'마케팅·재구매 동의 철회',exact:true}).click();await expect(panel.getByRole('status')).toContainText('동의를 철회했습니다.');await expect(panel.getByLabel('소비자 적격성',{exact:true})).toContainText('재구매 검토: 보류');
  panel=await open();await panel.getByRole('complementary',{name:'가명 소비자 목록',exact:true}).getByRole('button').first().click();await expect(panel.getByLabel('마케팅·재구매 동의 상태',{exact:true})).toContainText('철회');await expect(panel.getByLabel('동일인 주문 연결 동의 상태',{exact:true})).toContainText('동의 기록');
  const currentResponse=await page.request.get(`/api/growth/consumer?campaignId=${campaignId}`),current=await currentResponse.json(),customer=current.customers[0];
  const remote=await page.request.post('/api/growth/consumer',{data:{action:'set_consent',campaignId,campaignVersion:current.campaignVersion,customerId:customer.id,expectedVersion:customer.version,requestId:crypto.randomUUID(),purpose:'post_purchase',state:'revoked'}});expect(remote.status()).toBe(200);
  await panel.getByLabel('고지문 버전',{exact:true}).fill('preserved-notice');await panel.getByLabel('동의 증빙 내부 ID',{exact:true}).fill('preserved-proof');await panel.getByLabel('동의 확인 시각 (시간대 포함)',{exact:true}).fill(new Date(Date.now()-60_000).toISOString());await panel.getByLabel('동의 만료 시각 (시간대 포함)',{exact:true}).fill(new Date(Date.now()+86_400_000).toISOString());await panel.getByRole('button',{name:'선택 목적 동의 기록',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('입력은 보존했습니다.');await panel.getByRole('button',{name:'소비자 동의 새로고침',exact:true}).click();await panel.getByRole('button',{name:'현재 입력 유지 · 최신 소비자 버전 사용',exact:true}).click();await expect(panel.getByLabel('고지문 버전',{exact:true})).toHaveValue('preserved-notice');await panel.getByRole('button',{name:'선택 목적 동의 기록',exact:true}).click();await expect(panel.getByRole('status')).toContainText('목적별 동의를 기록했습니다.');
  const box=await panel.boundingBox();expect(box!.x+box!.width).toBeLessThanOrEqual((page.viewportSize()?.width??1280)+1);expect(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await panel.getByRole('heading',{name:'소비자 동의·재구매',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`e2e/artifacts/growth-consumer-${info.project.name}.png`});
  const firstId=(await (await page.request.get(`/api/growth/consumer?campaignId=${campaignId}`)).json()).customers[0].id;
  await panel.getByRole('button',{name:'새 가명 소비자 생성',exact:true}).click();await expect(panel.getByRole('status')).toContainText('가명 소비자를 생성했습니다.');const switchView=await (await page.request.get(`/api/growth/consumer?campaignId=${campaignId}`)).json(),secondId=switchView.customers.find((row:{id:string})=>row.id!==firstId).id;
  await panel.getByRole('complementary',{name:'가명 소비자 목록',exact:true}).getByRole('button',{name:new RegExp(firstId.slice(0,12))}).click();await panel.getByLabel('동의 증빙 내부 ID',{exact:true}).fill('first-only-proof');await panel.getByLabel('동일인 연결 증빙 내부 ID',{exact:true}).fill('first-only-link');await panel.getByRole('combobox',{name:'연결할 지점 주문',exact:true}).selectOption(orderId);await panel.getByRole('combobox',{name:'동의 목적',exact:true}).selectOption('marketing_reorder');
  await panel.getByRole('complementary',{name:'가명 소비자 목록',exact:true}).getByRole('button',{name:new RegExp(secondId.slice(0,12))}).click();await expect(panel.getByLabel('동의 증빙 내부 ID',{exact:true})).toHaveValue('');await expect(panel.getByLabel('동일인 연결 증빙 내부 ID',{exact:true})).toHaveValue('');await expect(panel.getByRole('combobox',{name:'연결할 지점 주문',exact:true})).toHaveValue('');await expect(panel.getByRole('combobox',{name:'동의 목적',exact:true})).toHaveValue('identity_link');await panel.getByRole('complementary',{name:'가명 소비자 목록',exact:true}).getByRole('button',{name:new RegExp(firstId.slice(0,12))}).click();await expect(panel.getByLabel('동일인 주문 연결 동의 상태',{exact:true})).toContainText('preserved-proof');
  let failRead=true;await page.route('**/api/growth/consumer?**',async route=>{if(failRead){failRead=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'합성 조회 실패'})});}else await route.continue();});
  await panel.getByRole('button',{name:'동일인 주문 연결 동의 철회',exact:true}).click();await expect(panel.getByRole('status')).toContainText('최신 평가는 새로고침해 확인하세요.');await expect(panel.getByLabel('소비자 적격성',{exact:true})).toContainText('최근 구매일: 미확인');await expect(panel).toContainText('연결 주문 수: 0');await panel.getByRole('button',{name:'소비자 동의 새로고침',exact:true}).click();await expect(panel.getByLabel('동일인 주문 연결 동의 상태',{exact:true})).toContainText('철회');
  await panel.locator('summary').filter({hasText:/^가명 소비자 삭제$/}).click();await panel.getByRole('button',{name:'가명 소비자·연결 삭제',exact:true}).click();await expect(panel.getByRole('status')).toContainText('가명 소비자와 주문 연결을 삭제했습니다.');const after=await page.request.get(`/api/growth/consumer?campaignId=${campaignId}`),afterView=await after.json();expect(afterView.customers).toHaveLength(1);expect(afterView.customers[0].id).toBe(secondId);expect(afterView.orders).toHaveLength(1);

 }finally{await context.close()}
});
