import {test,expect} from '@playwright/test';
// Real local Chromium/D1, synthetic owner authentication. No external dispatch.
test('전역 중단·모든 캠페인 상태·CAS 입력 보존·재개 영속성',async({browser},info)=>{
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':`stop-${info.project.name}-${Date.now()}`}}),page=await context.newPage();
 try{
  await page.request.get('/api/workspace');
  const title=`전역 중단 ${info.project.name}`,created=await page.request.post('/api/action',{data:{action:'save_campaign',data:{brandId:'ofd',title,goal:'합성 전역 중단 검증'}}});expect(created.status()).toBe(200);
  const open=async()=>{await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기',exact:true}).click();await page.getByRole('tab',{name:'성장·판매',exact:true}).click();await page.goto('/?view=settings');return page.getByRole('region',{name:'전역 실행 중단',exact:true})};
  const panel=await open();await expect(panel.getByRole('heading',{name:'전역 실행 중단',exact:true})).toBeVisible();
  const read=async()=>{const r=await page.request.get('/api/growth/stop');expect(r.status()).toBe(200);return r.json()};
  await expect(panel.getByLabel('전역 중단 상태',{exact:true})).toContainText('중단 해제 상태');await panel.getByRole('textbox',{name:'중단·재개 사유',exact:true}).fill('외부 집행 경로 점검');await panel.getByRole('button',{name:'모든 신규 실행 중단',exact:true}).click();await expect(panel.getByRole('status')).toContainText('중단 요청을 기록했습니다.');let v=await read();expect(v.state.status).toBe('stopped');expect(v.state.version).toBe(1);expect(v.externalCancellationConfirmed).toBe(false);await panel.getByRole('heading',{name:'전역 실행 중단',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`e2e/artifacts/growth-stop-stopped-${info.project.name}.png`});
  const second=await page.request.post('/api/action',{data:{action:'save_campaign',data:{brandId:'mapdal',title:'같은 소유자의 다른 캠페인',goal:'중단 상태에서도 초안 보존'}}});expect(second.status()).toBe(200);const {id:secondCampaignId}=await second.json();const denied=await page.request.post('/api/growth/execution',{data:{action:'prepare_execution',campaignId:secondCampaignId,campaignVersion:1,input:{}}});expect(denied.status()).toBe(409);expect((await denied.json()).error).toContain('전역 중단');const recovery=await page.request.get(`/api/growth/execution?campaignId=${secondCampaignId}`);expect(recovery.status()).toBe(200);
  const order=await page.request.get('/api/growth/stop');expect((await order.json()).state.status).toBe('stopped');
  const changed=await page.request.post('/api/growth/stop',{data:{action:'stop',expectedVersion:v.state.version,requestId:crypto.randomUUID(),reason:'다른 운영자의 점검 사유'}});expect(changed.status()).toBe(200);await panel.getByRole('textbox',{name:'중단·재개 사유',exact:true}).fill('현재 재개 사유 입력 보존');await panel.getByRole('button',{name:'소유자로서 실행 재개',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('입력은 보존했습니다.');await panel.getByRole('button',{name:'중단 상태 새로고침',exact:true}).click();await panel.getByRole('button',{name:'현재 입력 유지 · 최신 중단 판 사용',exact:true}).click();await expect(panel.getByRole('textbox',{name:'중단·재개 사유',exact:true})).toHaveValue('현재 재개 사유 입력 보존');
  const requests:Record<string,unknown>[]=[];let lost=true;page.on('request',request=>{if(request.url().endsWith('/api/growth/stop')&&request.method()==='POST')requests.push(request.postDataJSON());});await page.route('**/api/growth/stop',async route=>{const body=route.request().method()==='POST'?route.request().postDataJSON():null;if(lost&&body?.action==='resume'){const r=await route.fetch();expect(r.status()).toBe(200);lost=false;await route.abort('failed');}else await route.continue();});
  await panel.getByRole('button',{name:'소유자로서 실행 재개',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('입력은 보존했습니다.');await panel.getByRole('button',{name:'소유자로서 실행 재개',exact:true}).click();await expect(panel.getByRole('status')).toContainText('재개 요청을 기록했습니다.');expect(requests).toHaveLength(2);expect(requests[0].requestId).toBe(requests[1].requestId);v=await read();expect(v.state.status).toBe('running');expect(v.state.version).toBe(3);expect(v.history).toHaveLength(3);
  const restored=await open();await expect(restored.getByLabel('전역 중단 상태',{exact:true})).toContainText('중단 해제 상태');await restored.locator('summary').filter({hasText:/전역 중단·재개 이력/}).click();await expect(restored).toContainText('다른 운영자의 점검 사유');await expect(restored).toContainText('현재 재개 사유 입력 보존');expect(await restored.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await restored.getByRole('heading',{name:'전역 실행 중단',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`e2e/artifacts/growth-stop-${info.project.name}.png`});
 }finally{await context.close().catch(()=>{})}
});
