import {test,expect} from '@playwright/test';
// Actual local D1 and Chromium. Synthetic authentication; no external execution.
test('수동 재고와 실제 원장 분리·상품 단위·공유 예약·충돌 입력 보존',async({browser},info)=>{
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':`stock-ready-${info.project.name}-${Date.now()}`}}),page=await context.newPage();
 try{
  const post=async(path:string,data:unknown)=>{const r=await page.request.post(path,{data});expect(r.status(),await r.text()).toBe(200);return r.json()};await page.request.get('/api/workspace');
  const before=new Date(Date.now()-86400000).toISOString(),future=new Date(Date.now()+30*86400000).toISOString(),day=future.slice(0,10);
  const {id:storeId}=await post('/api/stores',{action:'save_store',brandId:'ofd',data:{name:'원장 준비도 합성 지점',address:'합성 주소',tradeArea:'residential',goal:'공유 재고 확인'}});
  const title=`원장 준비도 ${info.project.name}`,{id:campaignId}=await post('/api/action',{action:'save_campaign',data:{brandId:'ofd',storeId,title,goal:'단위와 공유 재고'}});
  const {id:factId}=await post('/api/brand-facts',{action:'save_fact',confirmed:true,data:{brandId:'ofd',key:'합성 상품',value:'원장 검증용 근거',status:'confirmed',source:'합성 확인',verifiedAt:before,validUntil:future}});
  const catalogInput={sku:'SHARED-READY-SKU',title:'원장 준비 상품',price:100,unitCost:20,variableCost:10,stock:0,currency:'KRW',taxBasis:'included',fulfillment:'배송 조건',refunds:'반품 조건',rightsConfirmed:true,factIds:[factId],validUntil:day};
  async function seed(campaign:string,prefix:string,stockUnit?:string){const save=(action:string,id:string,input:unknown)=>post('/api/growth',{action,id,input,campaignId:campaign,campaignVersion:1,expectedVersion:0});await save('save_signal',`${prefix}-signal`,{title:'공개 관측',sourceUrl:'https://example.com/market',observedAt:before,expiresAt:day,sourceType:'market',summary:'수요 관측',sampleSize:null});await save('save_need',`${prefix}-need`,{title:'니즈 가설',situation:'상황',desiredOutcome:'준비 단축',alternative:'대안',barrier:'배송',counterEvidence:'직접 준비',signalIds:[`${prefix}-signal`],deadline:day,nextAction:'확인',assignee:'검토 담당'});await save('save_catalog',`${prefix}-catalog`,{...catalogInput,...stockUnit?{stockUnit}:{}});await save('save_offer',`${prefix}-offer`,{title:'원장 준비 오퍼',catalogId:`${prefix}-catalog`,catalogVersion:1,needId:`${prefix}-need`,price:100,quantity:2,landingUrl:'https://example.com/buy',purchaseReason:'준비 단축',priceApproved:true});await save('save_mission',`${prefix}-mission`,{title:'원장 준비 미션',offerId:`${prefix}-offer`,offerVersion:1,assignee:'판매 담당',deadline:day,nextAction:'판매 준비',channel:'manual',budget:100,lossLimit:20,stopRule:'한도 도달',fulfillmentOwner:'배송 담당'});}
  await seed(campaignId,'primary');const inventory=await post('/api/growth/operations',{action:'create_inventory',campaignId,campaignVersion:1,input:{sku:catalogInput.sku,locationId:storeId,unit:'piece',onHand:2},observedAt:before,evidenceRef:'stock-evidence'});const inventoryId=inventory.inventory[0].id;
  const read=async()=>{const r=await page.request.get(`/api/growth?campaignId=${campaignId}`);expect(r.status()).toBe(200);return r.json()};
  const open=async()=>{await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기',exact:true}).click();await page.getByRole('tab',{name:'성장·판매',exact:true}).click();return page.getByRole('region',{name:'판매 기본 기록',exact:true})};
  const panel=await open(),tabs=panel.getByRole('navigation',{name:'성장 작업 단계'});await tabs.getByRole('button',{name:'상품',exact:true}).click();await panel.getByRole('group',{name:'상품 기록 목록',exact:true}).getByRole('button',{name:/원장 준비 상품/}).click();await expect(panel.getByRole('combobox',{name:'상품 수량 단위',exact:true})).toBeVisible({timeout:5000});await expect(panel.getByRole('combobox',{name:'상품 수량 단위',exact:true})).toHaveValue('unknown');
  await panel.getByRole('combobox',{name:'상품 수량 단위',exact:true}).selectOption('piece');await panel.getByRole('button',{name:'상품 저장',exact:true}).click();await expect(panel.getByRole('status')).toContainText('서버에 저장했습니다.');let view=await read();expect(view.catalogs[0].input.stock).toBe(0);expect(view.catalogs[0].readiness.missing).toHaveLength(0);expect(view.catalogs[0].currentStock.available).toBe(2);await expect(panel.getByRole('region',{name:'현재 재고 원장',exact:true})).toContainText('장부 확인');
  await tabs.getByRole('button',{name:'판매 오퍼',exact:true}).click();await panel.getByRole('group',{name:'판매 오퍼 기록 목록',exact:true}).getByRole('button',{name:/원장 준비 오퍼/}).click();await expect(panel.getByText('연결한 상품 판이 현재 판과 다릅니다.',{exact:false})).toBeVisible();await panel.getByRole('button',{name:'최신 버전 연결 (v2)',exact:true}).click();await panel.getByRole('button',{name:'판매 오퍼 저장',exact:true}).click();await expect(panel.getByRole('status')).toContainText('서버에 저장했습니다.');
  await tabs.getByRole('button',{name:'판매 미션',exact:true}).click();await panel.getByRole('group',{name:'판매 미션 기록 목록',exact:true}).getByRole('button',{name:/원장 준비 미션/}).click();await panel.getByRole('button',{name:'최신 버전 연결 (v2)',exact:true}).click();await panel.getByRole('button',{name:'판매 미션 저장',exact:true}).click();await expect(panel.getByRole('status')).toContainText('서버에 저장했습니다.');view=await read();expect(view.missions[0].readiness.missing).toHaveLength(0);expect(view.missions[0].currentStock.available).toBe(2);
  const {id:otherId}=await post('/api/action',{action:'save_campaign',data:{brandId:'ofd',storeId,title:'다른 캠페인 예약',goal:'공유 재고'}});await seed(otherId,'other','piece');await post('/api/growth',{action:'queue_mission',id:'other-mission',campaignId:otherId,campaignVersion:1,expectedVersion:1});await post('/api/growth/operations',{action:'reserve_stock',id:'other-reservation',campaignId:otherId,campaignVersion:1,inventoryId,inventoryVersion:1,missionId:'other-mission',missionVersion:2,quantity:2,observedAt:new Date().toISOString(),evidenceRef:'other-reservation'});
  await panel.getByRole('button',{name:'새로고침',exact:true}).click();await expect(panel.getByRole('region',{name:'현재 재고 원장',exact:true})).toContainText('예약 2');view=await read();expect(view.catalogs[0].currentStock.available).toBe(0);expect(view.offers[0].readiness.missing.length).toBeGreaterThan(0);expect(view.missions[0].readiness.missing.length).toBeGreaterThan(0);
  await tabs.getByRole('button',{name:'상품',exact:true}).click();await panel.getByRole('group',{name:'상품 기록 목록',exact:true}).getByRole('button',{name:/원장 준비 상품/}).click();await panel.getByLabel('수동 재고 참고값 (원장 가용량 아님)',{exact:true}).fill('100');await panel.getByRole('button',{name:'상품 저장',exact:true}).click();await expect(panel.getByRole('status')).toContainText('서버에 저장했습니다.');view=await read();expect(view.catalogs[0].input.stock).toBe(100);expect(view.catalogs[0].readiness.missing.length).toBeGreaterThan(0);expect(view.catalogs[0].currentStock.available).toBe(0);
  const row=view.catalogs[0];await post('/api/growth',{action:'save_catalog',id:row.id,expectedVersion:row.version,campaignId,campaignVersion:1,input:{...row.input,title:'다른 운영자의 상품'}});await panel.getByRole('textbox',{name:'상품명',exact:true}).fill('보존할 상품 입력');await panel.getByRole('button',{name:'상품 저장',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('입력은 보존했습니다.');await panel.getByRole('button',{name:'새로고침',exact:true}).click();await panel.getByRole('button',{name:'현재 입력을 유지하고 최신 버전 기준 사용',exact:true}).click();await expect(panel.getByRole('textbox',{name:'상품명',exact:true})).toHaveValue('보존할 상품 입력');await expect(panel.getByLabel('수동 재고 참고값 (원장 가용량 아님)',{exact:true})).toHaveValue('100');await panel.getByRole('button',{name:'상품 저장',exact:true}).click();await expect(panel.getByRole('status')).toContainText('서버에 저장했습니다.');expect((await read()).catalogs[0].input.title).toBe('보존할 상품 입력');
  expect(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await panel.getByRole('region',{name:'현재 재고 원장',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`e2e/artifacts/growth-stock-readiness-${info.project.name}.png`});
 }finally{await context.close().catch(()=>{})}
});
