import {test,expect} from '@playwright/test';
// Real local D1 and Chromium. Identity is synthetic; no procurement is executed.
test('단일 SKU 소싱 후보·판 고정 비교·개정과 충돌 입력 보존',async({browser},info)=>{
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':`sourcing-${info.project.name}-${Date.now()}`}}),page=await context.newPage();
 try{
  await page.request.get('/api/workspace');const title=`소싱 비교 ${info.project.name}`;
  const created=await page.request.post('/api/action',{data:{action:'save_campaign',data:{brandId:'ofd',title,goal:'소싱 후보 비교'}}});expect(created.status()).toBe(200);const {id:campaignId}=await created.json();
  const future=new Date(Date.now()+30*86400000).toISOString().slice(0,10);
  const growth=await(await page.request.get(`/api/growth?campaignId=${campaignId}`)).json();
  const catalogResponse=await page.request.post('/api/growth',{data:{action:'save_catalog',id:crypto.randomUUID(),expectedVersion:0,campaignId,campaignVersion:growth.campaignVersion,input:{sku:'SOURCING-SKU',title:'합성 소싱 상품',price:3000,unitCost:1000,stock:100,fulfillment:'택배',taxBasis:'included',validUntil:future,factIds:[]}}});expect(catalogResponse.status(),await catalogResponse.text()).toBe(200);
  const open=async()=>{await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기',exact:true}).click();await page.getByRole('tab',{name:'성장·판매',exact:true}).click();await page.locator('summary').filter({hasText:/^상품 소싱 비교$/}).click();return page.getByRole('region',{name:'상품 소싱 비교',exact:true})};
  const read=async()=>{const res=await page.request.get(`/api/growth/sourcing?campaignId=${campaignId}`);expect(res.status()).toBe(200);return res.json()};
  const panel=await open(),editor=panel.getByRole('region',{name:'소싱 후보 편집',exact:true}),catalogId=(await read()).catalogs[0].id;
  async function saveCandidate(supplier:string,cost:string){await editor.getByRole('combobox',{name:'후보 상품 판',exact:true}).selectOption(`${catalogId}:1`);await editor.getByRole('textbox',{name:'공급 후보 내부 코드',exact:true}).fill(supplier);for(const [label,value]of [['단위원가 (원)',cost],['최소 주문 수량','10'],['납기 (일)','3'],['배송비 (원)','0'],['부대비 (원)','0']])await editor.getByLabel(label,{exact:true}).fill(value);await editor.getByRole('combobox',{name:'후보 수량 단위',exact:true}).selectOption('piece');await editor.getByRole('combobox',{name:'세금 기준',exact:true}).selectOption('included');await editor.getByLabel('견적 유효기한',{exact:true}).fill(future);await editor.getByRole('textbox',{name:'견적 증빙 내부 참조',exact:true}).fill(`quote-${supplier}`);await editor.getByRole('button',{name:'소싱 후보 저장',exact:true}).click();await expect(panel.getByRole('status')).toContainText('소싱 후보를 저장했습니다.');}
  await saveCandidate('SUPPLIER-A','100');await panel.getByRole('button',{name:'새 소싱 후보',exact:true}).click();await expect(editor.getByRole('textbox',{name:'견적 증빙 내부 참조',exact:true})).toHaveValue('');await saveCandidate('SUPPLIER-B','');
  let view=await read();expect(view.candidates.find((r:{input:{supplierCode:string}})=>r.input.supplierCode==='SUPPLIER-B').input.unitCost).toBeNull();
  const comparison=panel.getByRole('region',{name:'소싱 비교 작성',exact:true});await comparison.getByRole('combobox',{name:'비교 상품 판',exact:true}).selectOption(`${catalogId}:1`);await comparison.getByLabel('요청 수량',{exact:true}).fill('20');await comparison.getByRole('checkbox',{name:/SUPPLIER-A/}).check();await comparison.getByRole('checkbox',{name:/SUPPLIER-B/}).check();const attempts:string[]=[];let loseResponse=true;
  await page.route('**/api/growth/sourcing',async route=>{const request=route.request();if(request.method()==='POST'&&request.postDataJSON().action==='capture_comparison'){attempts.push(request.postDataJSON().requestId);if(loseResponse){loseResponse=false;const response=await route.fetch();expect(response.status(),await response.text()).toBe(200);await route.abort('failed');return;}}await route.continue();});
  await comparison.getByRole('button',{name:'소싱 비교 기록',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('입력은 보존했습니다.');await comparison.getByRole('button',{name:'소싱 비교 기록',exact:true}).click();await expect(panel.getByRole('status')).toContainText('소싱 비교를 기록했습니다.');expect(attempts).toHaveLength(2);expect(attempts[0]).toBe(attempts[1]);
  view=await read();expect(view.comparisons).toHaveLength(1);const original=view.comparisons[0];expect(original.assessment.mayOrder).toBe(false);expect(original.assessment.rows.find((r:{supplierCode:string})=>r.supplierCode==='SUPPLIER-A').totalCost).toBe(2000);expect(original.assessment.rows.find((r:{supplierCode:string})=>r.supplierCode==='SUPPLIER-B').status).toBe('held');
  const remote=view.candidates.find((r:{input:{supplierCode:string}})=>r.input.supplierCode==='SUPPLIER-B');const update=await page.request.post('/api/growth/sourcing',{data:{action:'save_candidate',id:remote.id,expectedVersion:remote.version,requestId:crypto.randomUUID(),campaignId,campaignVersion:view.campaignVersion,input:{...remote.input,unitCost:120}}});expect(update.status(),await update.text()).toBe(200);
  await editor.getByRole('textbox',{name:'후보 메모',exact:true}).fill('보존할 비교 근거');await editor.getByRole('button',{name:'소싱 후보 저장',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('입력은 보존했습니다.');await panel.getByRole('button',{name:'소싱 기록 새로고침',exact:true}).click();await editor.getByRole('button',{name:'현재 입력을 유지하고 최신 후보 판 사용',exact:true}).click();await expect(editor.getByRole('textbox',{name:'후보 메모',exact:true})).toHaveValue('보존할 비교 근거');await editor.getByRole('button',{name:'소싱 후보 저장',exact:true}).click();await expect(panel.getByRole('status')).toContainText('소싱 후보를 저장했습니다.');
  view=await read();expect(view.comparisons[0].snapshotDigest).toBe(original.snapshotDigest);expect(view.comparisons[0].currentChanged).toBe(true);
  const restored=await open();await expect(restored.getByRole('region',{name:'저장된 소싱 비교',exact:true})).toContainText('현재 상품·견적·재고 또는 유효 조건이 달라졌습니다.');await expect(restored).toContainText('자동 발주 권한 없음');expect(await restored.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await page.screenshot({path:`e2e/artifacts/growth-sourcing-${info.project.name}.png`});
 }finally{await context.close().catch(()=>{})}
});
