import {test,expect} from '@playwright/test';
// Local browser and D1; synthetic owner, no external execution or analytics.
test('일일 결정·실패 교훈 저장·근거 연결·재조회·충돌 입력 보존',async({browser},info)=>{
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':`decisions-${info.project.name}-${Date.now()}`}}),page=await context.newPage();
 try{
  await page.request.get('/api/workspace');const title=`결정 계획 ${info.project.name}`;
  const created=await page.request.post('/api/action',{data:{action:'save_campaign',data:{brandId:'ofd',title,goal:'합성 운영 학습 검토'}}});expect(created.status()).toBe(200);const {id:campaignId}=await created.json();
  const open=async()=>{await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기',exact:true}).click();await page.getByRole('tab',{name:'성장·판매',exact:true}).click();await page.locator('summary').filter({hasText:/^일일 결정·운영 교훈$/}).click();return page.getByRole('region',{name:'결정·운영 교훈',exact:true})};
  const read=async()=>{const response=await page.request.get(`/api/growth/decisions?campaignId=${campaignId}`);expect(response.status()).toBe(200);return response.json()};
  let panel=await open(),decision=panel.getByRole('region',{name:'일일 결정',exact:true});
  await decision.getByRole('textbox',{name:'결정 제목',exact:true}).fill('배송 안내 수정 결정');await decision.getByRole('combobox',{name:'결정 유형',exact:true}).selectOption('modify');await decision.getByRole('textbox',{name:'결정 이유',exact:true}).fill('안내 이해 여부를 다시 확인');await decision.getByRole('button',{name:'일일 결정 저장',exact:true}).click();await expect(decision.getByRole('status')).toContainText('일일 결정을 저장했습니다.');
  await panel.locator('summary').filter({hasText:/^운영 교훈 기록$/}).click();let lesson=panel.getByRole('region',{name:'운영 교훈',exact:true});await lesson.getByRole('textbox',{name:'교훈 제목',exact:true}).fill('실패한 안내 가설');await lesson.getByRole('combobox',{name:'근거 유형',exact:true}).selectOption('decision');let v=await read();await lesson.getByRole('combobox',{name:'근거 결정',exact:true}).selectOption(v.decisions[0].id);await lesson.getByRole('combobox',{name:'검증 결과',exact:true}).selectOption('failure');await expect(lesson.getByRole('spinbutton',{name:'손실 한도 (원, 빈칸은 미확인)',exact:true})).toHaveValue('');await lesson.getByRole('button',{name:'운영 교훈 저장',exact:true}).click();await expect(lesson.getByRole('status')).toContainText('운영 교훈을 저장했습니다.');v=await read();expect(v.lessons[0].input.lossLimit).toBeNull();expect(v.lessons[0].input.decisionVersion).toBe(1);expect(v.lessons[0].input.outcome).toBe('failure');expect(v.mayExecute).toBe(false);
  await lesson.getByRole('spinbutton',{name:'손실 한도 (원, 빈칸은 미확인)',exact:true}).fill('0');await lesson.getByRole('button',{name:'운영 교훈 저장',exact:true}).click();await expect(lesson.getByRole('status')).toContainText('운영 교훈을 저장했습니다.');v=await read();expect(v.lessons[0].input.lossLimit).toBe(0);
  panel=await open();decision=panel.getByRole('region',{name:'일일 결정',exact:true});await decision.getByRole('group',{name:'일일 결정 목록'}).getByRole('button',{name:/배송 안내 수정 결정/}).click();await expect(decision.getByRole('textbox',{name:'결정 이유',exact:true})).toHaveValue('안내 이해 여부를 다시 확인');await panel.locator('summary').filter({hasText:/^운영 교훈 기록$/}).click();lesson=panel.getByRole('region',{name:'운영 교훈',exact:true});await lesson.getByRole('group',{name:'운영 교훈 목록'}).getByRole('button',{name:/실패한 안내 가설/}).click();await expect(lesson.getByRole('spinbutton',{name:'손실 한도 (원, 빈칸은 미확인)',exact:true})).toHaveValue('0');await expect(lesson.getByLabel('운영 교훈 평가',{exact:true})).toContainText('자동 규칙 승격 없음');
  v=await read();const row=v.decisions[0];const changed=await page.request.post('/api/growth/decisions',{data:{action:'save_decision',campaignId,campaignVersion:v.campaignVersion,id:row.id,expectedVersion:row.version,input:{...row.input,title:'다른 운영자의 결정 수정'}}});expect(changed.status()).toBe(200);
  await decision.getByRole('textbox',{name:'결정 제목',exact:true}).fill('현재 결정 입력 보존');await decision.getByRole('button',{name:'일일 결정 저장',exact:true}).click();await expect(decision.getByRole('alert')).toContainText('입력은 보존했습니다.');await panel.getByRole('button',{name:'결정·교훈 새로고침',exact:true}).click();await decision.getByRole('button',{name:'현재 입력을 유지하고 최신 버전 기준 사용',exact:true}).click();await expect(decision.getByRole('textbox',{name:'결정 제목',exact:true})).toHaveValue('현재 결정 입력 보존');await decision.getByRole('button',{name:'일일 결정 저장',exact:true}).click();await expect(decision.getByRole('status')).toContainText('일일 결정을 저장했습니다.');v=await read();expect(v.decisions[0].version).toBe(3);
  const box=await panel.boundingBox();expect(box!.x+box!.width).toBeLessThanOrEqual((page.viewportSize()?.width??1280)+1);expect(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await panel.getByRole('heading',{name:'일일 결정·운영 교훈',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`e2e/artifacts/growth-decisions-${info.project.name}.png`});
 }finally{await context.close()}
});
