import {test,expect} from '@playwright/test';
test('Meta 보고에서 판단 기록 후 다시 확인',async({browser},info)=>{
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':`meta-learning-${info.project.name}-${Date.now()}`}}),page=await context.newPage();
 await page.request.get('/api/workspace');const title='다음 실험 '+info.project.name;
 const storeResponse=await page.request.post('/api/stores',{data:{action:'save_store',brandId:'ofd',data:{name:'합성 실험 지점',address:'합성 주소',tradeArea:'residential',goal:'실험 관측 검증'}}});expect(storeResponse.status()).toBe(200);const {id:storeId}=await storeResponse.json();
 const created=await page.request.post('/api/action',{data:{action:'save_campaign',data:{brandId:'ofd',storeId,title,goal:'합성 보고 판단'}}});expect(created.status()).toBe(200);const {id}=await created.json();
 const report=await page.request.get('/api/meta-ads/report?campaignId='+id+'&since=2026-09-01&until=2026-09-02');const v=await report.json();
 const frozen=await page.request.post('/api/meta-ads/report',{data:{action:'freeze',campaignId:id,since:'2026-09-01',until:'2026-09-02',expectedVersion:v.version,expectedDigest:v.report.basisDigest,confirmed:true}});expect(frozen.status()).toBe(200);
 await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기'}).click();await page.getByRole('tab',{name:'Meta 광고 준비',exact:true}).click();await page.getByRole('tab',{name:'다음 실험',exact:true}).click();
 const p=page.getByRole('region',{name:'Meta 다음 실험'});await expect(p.getByLabel('판단 근거')).toBeEnabled();await p.getByLabel('판단 근거').fill('실제 주문을 확인한 뒤 판단');await p.getByLabel('근거의 한계와 이번 판단을 확인했습니다',{exact:true}).check();await p.getByRole('button',{name:'판단 기록',exact:true}).click();await expect(p.getByRole('status')).toContainText('기록했습니다');await p.getByRole('button',{name:'다시 불러오기'}).click();await expect(p.getByRole('heading',{name:'보류 · 보고 v1'})).toBeVisible();expect(await p.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
 const prereg=p.getByRole('form',{name:'Meta 실험 사전등록'});await expect(prereg.getByRole('button',{name:'실험 사전등록',exact:true})).toBeDisabled();
 // Real local fact/Canvas/R2/decision records; synthetic data, no external calls.
 const factResponse=await page.request.post('/api/brand-facts',{data:{action:'save_fact',confirmed:true,data:{brandId:'ofd',key:'signature_menu',value:'합성 실험 상품',status:'confirmed',source:'E2E 합성 검증',verifiedAt:new Date(Date.now()-60000).toISOString(),validUntil:new Date(Date.now()+30*86400000).toISOString()}}});expect(factResponse.status()).toBe(200);const fact=await factResponse.json();
 const png=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1080;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#334455';ctx.fillRect(0,0,1080,1080);return canvas.toDataURL('image/png');});
 const creativeResponse=await page.request.post('/api/execution',{data:{action:'save_creative',campaignId:id,campaignVersion:1,factRefs:[{id:fact.id,version:fact.version}],title:'사전등록 합성 소재',png}});expect(creativeResponse.status()).toBe(200);const creative=await creativeResponse.json();
 const state=await(await page.request.get('/api/meta-ads/learning?campaignId='+id)).json(),snapshot=state.snapshots[0];
 const draft=await page.request.post('/api/meta-ads/learning',{data:{action:'record',campaignId:id,snapshotId:snapshot.id,expectedDigest:snapshot.digest,expectedVersion:state.version,decision:'retest',note:'합성 사전등록 검증',confirmed:true,candidate:{hypothesis:'상품 설명 비교',variable:'훅',control:'구성 중심',treatment:'사용 장면 중심',metric:'paid_orders',minSample:100,stopCondition:'기간 종료 후 검토',creativeId:creative.id,creativeVersion:creative.version,creativeHash:creative.pngHash}}});expect(draft.status()).toBe(200);
 await p.getByRole('button',{name:'다시 불러오기'}).click();await prereg.getByRole('combobox',{name:'등록할 실험 후보',exact:true}).selectOption({index:1});const local=(offset:number)=>new Date(Date.now()+offset+9*3600000).toISOString().slice(0,16);await prereg.getByLabel('실험 시작 · 한국 시간',{exact:true}).fill(local(86400000));await prereg.getByLabel('실험 종료 · 한국 시간',{exact:true}).fill(local(3*86400000));await prereg.getByLabel('고정 조건·배정 및 측정 계획',{exact:true}).fill('동일 예산·대상, 수동 배정과 기록');await prereg.getByRole('checkbox').check();await prereg.getByRole('button',{name:'실험 사전등록',exact:true}).click();await expect(prereg.getByRole('status')).toContainText('사전등록했습니다');await expect(p.getByRole('heading',{name:'사전등록 · 보고 v1'})).toBeVisible();await expect(prereg.getByRole('button',{name:'실험 사전등록',exact:true})).toBeDisabled();
 await p.getByRole('button',{name:'다시 불러오기'}).click();await expect(p.getByRole('heading',{name:'사전등록 · 보고 v1'})).toBeVisible();await expect(p.getByText('결과: 실험 관측 탭에서 배정·성숙 결과 확인',{exact:true})).toBeVisible();expect(await prereg.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
 await page.getByRole('tab',{name:'실험 관측',exact:true}).click();const observed=page.getByRole('region',{name:'Meta 실험 관측'});await observed.getByRole('combobox',{name:'연결할 사전등록',exact:true}).selectOption({index:1});await observed.getByLabel('배정·추적·비용 증빙과 이번 기록 내용을 확인했습니다',{exact:true}).check();await observed.getByRole('button',{name:'통계 설계 고정',exact:true}).click();await expect(observed.getByRole('status')).toContainText('기록했습니다');await observed.getByRole('button',{name:'다시 불러오기',exact:true}).click();await observed.getByRole('combobox',{name:'관측할 실험',exact:true}).selectOption({index:1});await expect(observed).toContainText('배정 0명 · 관측 0명 · 시작 전');await observed.getByLabel('비식별 방문자 키 해시',{exact:true}).fill('a'.repeat(64));await observed.getByLabel('배정·추적·비용 증빙과 이번 기록 내용을 확인했습니다',{exact:true}).check();await observed.getByRole('button',{name:'대조군·실험군 배정',exact:true}).click();await expect(observed.getByRole('alert')).toContainText('관측 기간');expect(await observed.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
 await page.getByRole('tab',{name:'예산 예약',exact:true}).click();await expect(page.getByRole('region',{name:'Meta 예산 예약'}).getByRole('button',{name:'계획 예산 예약',exact:true})).toBeDisabled();await context.close();
});
