// Real Chromium/local D1, mocked owner identity; no Meta calls or ad spend.
import {test,expect} from '@playwright/test';
test('Meta 준비 계획 저장·재조회와 집행 차단',async({browser},info)=>{
 const owner=`meta-e2e-${info.project.name}-${Date.now()}`;
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':owner}});
 const page=await context.newPage();await page.request.get('/api/workspace');
 const title='Meta 준비 '+info.project.name;
 const created=await page.request.post('/api/action',{data:{action:'save_campaign',data:{brandId:'ofd',title,goal:'구매 전환 준비',budget:0}}});expect(created.status()).toBe(200);
 await page.goto('/');
 if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();
 await page.getByRole('button',{name:'캠페인',exact:true}).click();
 if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');
 await page.getByRole('button',{name:title+' 열기'}).click();
 await page.getByRole('tab',{name:'Meta 광고 준비',exact:true}).click();
 const panel=page.getByRole('region',{name:'Meta 광고 준비'});
 await expect(panel.getByRole('navigation',{name:'광고 준비 단계'})).toBeVisible();
 await panel.getByRole('radio',{name:'콘텐츠 기반',exact:true}).check();
 await panel.getByLabel('목표',{exact:true}).selectOption('lead');
 await expect(panel).toContainText('매출 미검증');
 await panel.getByRole('button',{name:'2. 상품과 수익',exact:true}).click();
 await panel.getByLabel('상품·오퍼',{exact:true}).fill('합성 상품 1개');
 await panel.getByLabel('판매가 (원)',{exact:true}).fill('12000');
 await panel.getByLabel('상품 원가 (원)',{exact:true}).fill('4000');
 await panel.getByLabel('건당 변동비 (원)',{exact:true}).fill('2000');
 await expect(panel.getByTestId('meta-contribution')).toHaveText('6,000원');
 await panel.getByRole('button',{name:'3. 예산과 일정',exact:true}).click();
 await panel.getByLabel('총 광고 예산 (원)',{exact:true}).fill('60000');
 await panel.getByRole('button',{name:'1. 판매 목표',exact:true}).click();
 await panel.getByLabel('목표',{exact:true}).selectOption('purchase');
 await expect(panel.getByTestId('meta-breakeven')).toHaveText('10건');
 await panel.getByRole('button',{name:'4. 준비 점검',exact:true}).click();
 await panel.getByRole('checkbox',{name:'재고·제공 가능 수량 확인',exact:true}).check();
 await panel.getByRole('button',{name:'준비 계획 저장',exact:true}).click();
 await expect(panel.getByRole('status')).toContainText('준비 계획을 저장했습니다');
 await panel.getByRole('button',{name:'최신 계획 불러오기'}).click();
 await expect(panel.getByRole('checkbox',{name:'재고·제공 가능 수량 확인',exact:true})).toBeChecked();
 await expect(panel.getByRole('button',{name:'준비 계획 저장',exact:true})).toBeEnabled();
 await panel.getByRole('button',{name:'2. 상품과 수익',exact:true}).click();
 await expect(panel.getByLabel('상품·오퍼',{exact:true})).toHaveValue('합성 상품 1개');
 await expect(panel.getByLabel('판매가 (원)',{exact:true})).toHaveValue('12000');
 await expect(panel.getByTestId('meta-contribution')).toHaveText('6,000원');
 await expect(panel.getByRole('button',{name:/광고 집행/})).toHaveCount(0);
 await expect(panel).toContainText('계획 저장으로 광고가 시작되지 않습니다');
 expect(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
 await panel.screenshot({path:`e2e/artifacts/meta-workspace-${info.project.name}.png`});
 await page.getByRole('tab',{name:'광고 성과',exact:true}).click();
 const insights=page.getByRole('region',{name:'Meta 광고 성과'});
 await insights.getByLabel('광고 계정 ID',{exact:true}).fill('123');
 await insights.getByLabel('Meta 캠페인 ID',{exact:true}).fill('456');
 await insights.getByLabel('시작일',{exact:true}).fill('2026-09-01');
 await insights.getByLabel('종료일',{exact:true}).fill('2026-09-02');
 await insights.getByLabel('Meta 성과 CSV',{exact:true}).setInputFiles({name:'synthetic.csv',mimeType:'text/csv',buffer:Buffer.from('date,account_id,campaign_id,ad_id,spend,impressions,clicks,purchases,purchase_value\n2026-09-01,123,456,789,1200.25,100,5,,\n')});
 await insights.getByRole('button',{name:'가져올 내용 확인',exact:true}).click();
 await expect(insights).toContainText('광고비 1,200.25원');
 await insights.getByRole('button',{name:'확인한 성과 저장',exact:true}).click();
 await expect(insights.getByRole('status')).toContainText('성과를 저장했습니다');
 await expect(insights).toContainText('수동 입력 · Meta 검증 없음');
 await expect(insights.getByRole('cell',{name:'1,200.25원',exact:true})).toBeVisible();
 await insights.getByRole('button',{name:'새로고침',exact:true}).click();
 await expect(insights.getByRole('cell',{name:'1,200.25원',exact:true})).toBeVisible();
 expect(await insights.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
 await insights.screenshot({path:`e2e/artifacts/meta-insights-${info.project.name}.png`});
 await context.close();
});
