// Real local browser/D1 with synthetic identity and draft; no provider calls.
import {test,expect} from '@playwright/test';
test('Meta 소재 초안 유지·근거 미확인 검토 거부',async({browser},info)=>{
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':`meta-creative-${info.project.name}-${Date.now()}`}}),page=await context.newPage();await page.request.get('/api/workspace');
 const title='소재 검토 '+info.project.name,created=await page.request.post('/api/action',{data:{action:'save_campaign',data:{brandId:'ofd',title,goal:'근거와 소재 검토'}}});expect(created.status()).toBe(200);
 await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기'}).click();await page.getByRole('tab',{name:'Meta 광고 준비',exact:true}).click();await page.getByRole('tab',{name:'소재·실험',exact:true}).click();
 const panel=page.getByRole('region',{name:'소재와 실험 검토'});await panel.getByLabel('소재안 이름',{exact:true}).fill('합성 초안');await panel.getByLabel('첫 문장',{exact:true}).fill('상품 구성을 확인하세요');await panel.getByRole('button',{name:'초안 저장',exact:true}).click();await expect(panel.getByRole('status')).toContainText('소재안 초안을 저장했습니다');
 await panel.getByRole('button',{name:'다시 불러오기',exact:true}).click();await expect(panel.getByLabel('소재안 이름',{exact:true})).toHaveValue('합성 초안');await panel.getByRole('checkbox',{name:'자동 점검의 경고와 한계를 확인했습니다',exact:true}).check();await panel.getByRole('button',{name:'검토 기록 저장',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('소재');await expect(panel.getByLabel('첫 문장',{exact:true})).toHaveValue('상품 구성을 확인하세요');
 expect(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await panel.getByRole('heading',{name:'근거에서 광고 문구까지',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`e2e/artifacts/meta-creative-${info.project.name}.png`});await context.close();
});
