import {test,expect} from '@playwright/test';
test('Meta 비활성 단계 생성은 앞 단계 미확정 시 다음 단계와 재전송을 막는다',async({browser},info)=>{
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':'child-create-'+info.project.name+'-'+Date.now()}}),page=await context.newPage();await page.request.get('/api/workspace');
 const title='하위 생성 '+info.project.name;await page.request.post('/api/action',{data:{action:'save_campaign',data:{brandId:'ofd',title,goal:'합성 비활성 생성 UI'}}});
 let saved:Record<string,unknown>|null=null,posts=0;const initial=()=>({state:'prepared',externalId:null,verifiedAt:null});
 const view=()=>({saved,version:saved?1:0,campaignVersion:1,evidenceFingerprint:'a'.repeat(64),enabled:true,issues:[],parents:[{id:'b'.repeat(64),externalId:'123'}],images:[{id:'c'.repeat(64),metaImageHash:'d'.repeat(32)}],stale:false,canEdit:true,canActivate:false});
 await page.route('**/api/meta-ads/create**',async route=>{if(route.request().method()==='POST'){const b=route.request().postDataJSON();posts++;if(b.action==='prepare'){saved={input:b.input,steps:{adset:initial(),creative:initial(),ad:initial()}};return route.fulfill({json:view()})}expect(b.confirmed).toBe(true);expect(b.step).toBe('adset');saved={...saved,steps:{adset:{state:'unknown',externalId:null,verifiedAt:null},creative:initial(),ad:initial()}};return route.fulfill({status:502,json:{error:'생성 결과를 확정하지 못했습니다.'}})}return route.fulfill({json:view()})});
 await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기'}).click();await page.getByRole('tab',{name:'Meta 광고 준비',exact:true}).click();await page.getByRole('tab',{name:'광고 구성·생성',exact:true}).click();
 const panel=page.getByRole('region',{name:'Meta 비활성 광고 생성'});await panel.getByLabel('Facebook 페이지 ID',{exact:true}).fill('50');await panel.getByLabel('픽셀 ID',{exact:true}).fill('60');await panel.getByLabel('Graph 일 예산 원문 정수',{exact:true}).fill('100000');await panel.getByLabel('원화·Graph 예산 단위 대조 근거',{exact:true}).fill('합성 대조');await panel.getByRole('button',{name:'하위 광고 생성 준비',exact:true}).click();await expect(panel.getByRole('button',{name:'광고세트 비활성 생성',exact:true})).toBeDisabled();await panel.getByRole('checkbox').check();await expect(panel.getByRole('button',{name:'소재 비활성 생성',exact:true})).toBeDisabled();await panel.getByRole('button',{name:'광고세트 비활성 생성',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('확정하지 못했습니다');await expect(panel.getByRole('button',{name:'광고세트 비활성 생성',exact:true})).toHaveCount(0);await expect(panel.getByRole('button',{name:'소재 비활성 생성',exact:true})).toBeDisabled();await expect(panel.getByRole('button',{name:'하위 광고 생성 준비',exact:true})).toBeDisabled();expect(posts).toBe(2);await page.unrouteAll({behavior:'wait'});await context.close();
});
