import {test,expect} from '@playwright/test';
test('Meta 원본 업로드는 확인 후 전송하고 결과 미확인 재전송을 막는다',async({browser},info)=>{
 const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':'image-upload-'+info.project.name+'-'+Date.now()}}),page=await context.newPage();await page.request.get('/api/workspace');
 const title='원본 업로드 '+info.project.name;await page.request.post('/api/action',{data:{action:'save_campaign',data:{brandId:'ofd',title,goal:'합성 이미지 전송 UI'}}});
 let operations:Record<string,unknown>[]=[],posts=0;
 const view=()=>({campaignVersion:1,evidenceFingerprint:'a'.repeat(64),enabled:true,issues:[],creative:{id:'synthetic',version:1,pngHash:'b'.repeat(64)},accountId:'123',operations,canEdit:true});
 await page.route('**/api/meta-ads/assets**',async route=>{if(route.request().method()==='POST'){const b=route.request().postDataJSON();posts++;if(b.action==='prepare'){operations=[{id:'c'.repeat(64),version:1,state:'prepared',stale:false,receipt:null}];return route.fulfill({json:view()})}expect(b.confirmed).toBe(true);expect(b.expectedVersion).toBe(1);operations=[{...operations[0],version:2,state:'unknown'}];return route.fulfill({status:502,json:{error:'이미지 업로드 결과를 확정하지 못했습니다.'}})}return route.fulfill({json:view()})});
 await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기'}).click();await page.getByRole('tab',{name:'Meta 광고 준비',exact:true}).click();await page.getByRole('tab',{name:'소재·원본',exact:true}).click();
 const panel=page.getByRole('region',{name:'Meta 원본 이미지 업로드'});await panel.getByRole('button',{name:'원본 업로드 준비',exact:true}).click();await expect(panel.getByRole('button',{name:'Meta 이미지 업로드',exact:true})).toBeDisabled();await panel.getByRole('checkbox').check();await panel.getByRole('button',{name:'Meta 이미지 업로드',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('확정하지 못했습니다');await expect(panel.getByText('결과가 확정되지 않았습니다. 중복 업로드하지 말고 외부 계정에서 대조하세요.')).toBeVisible();await expect(panel.getByRole('button',{name:'Meta 이미지 업로드',exact:true})).toHaveCount(0);expect(posts).toBe(2);await page.unrouteAll({behavior:'wait'});await context.close();
});
