// Real local browser/D1; synthetic identity/orders, no store or Meta external calls.
import {createHmac} from 'node:crypto';
import {test,expect} from '@playwright/test';
test('자사몰 서명 수신 생성·자동 반영·중복·끄기',async({browser,request},info)=>{
 const owner=`webhook-e2e-${info.project.name}-${Date.now()}`,context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:info.project.use.viewport,extraHTTPHeaders:{'oai-authenticated-user-id':owner}}),page=await context.newPage();
 await page.request.get('/api/workspace');
 const savedStore=await page.request.post('/api/stores',{data:{action:'save_store',brandId:'ofd',data:{name:'자사몰 테스트 지점',address:'합성 주소',tradeArea:'residential',goal:'실제 주문 대조'}}});expect(savedStore.status()).toBe(200);const {id:storeId}=await savedStore.json();
 const title='자사몰 수신 '+info.project.name,created=await page.request.post('/api/action',{data:{action:'save_campaign',data:{brandId:'ofd',storeId,title,goal:'주문 대조'}}});expect(created.status()).toBe(200);
 await page.goto('/');if((page.viewportSize()?.width??1280)<768)await page.locator('[data-sidebar="trigger"]').first().click();await page.getByRole('button',{name:'캠페인',exact:true}).click();if((page.viewportSize()?.width??1280)<768)await page.keyboard.press('Escape');await page.getByRole('button',{name:title+' 열기'}).click();await page.getByRole('tab',{name:'Meta 광고 준비',exact:true}).click();await page.getByRole('tab',{name:'성과·대조',exact:true}).click();
 const panel=page.getByRole('region',{name:'자사몰 서명 수신 연결'});await panel.locator('summary').click();await panel.getByLabel('자동 수신 몰 식별자',{exact:true}).fill('browser-shop');const createdResponse=page.waitForResponse(r=>r.url().endsWith('/api/storefront-webhooks')&&r.request().method()==='POST');await panel.getByRole('button',{name:'꺼진 수신 연결 만들기',exact:true}).click();const result=await (await createdResponse).json();expect(result.connection.enabled).toBe(false);await panel.getByRole('button',{name:'키 저장 후 화면에서 숨기기',exact:true}).click();await expect(panel.getByText(result.signingSecret,{exact:true})).toHaveCount(0);await panel.getByRole('button',{name:'수신 켜기',exact:true}).click();await page.getByRole('alertdialog',{name:'이 연결로 서명된 주문·환불을 장부에 자동 반영할까요?'}).getByRole('button',{name:'켜기',exact:true}).click();await expect(panel.getByRole('button',{name:'수신 끄기',exact:true})).toBeVisible();const raw=JSON.stringify({orders:[{order_id:'BROWSER-WEBHOOK',revision:1,order_date:'2026-09-01',status:'paid',paid_amount:10000,refund_amount:0,mode:'delivery'}]}),timestamp=String(Math.floor(Date.now()/1000)),signature='sha256='+createHmac('sha256',result.signingSecret).update(timestamp+'.'+raw).digest('hex');const receive=()=>request.post(result.connection.path,{headers:{'content-type':'application/json','x-collective-timestamp':timestamp,'x-collective-signature':signature},data:raw});let received=await receive();expect(received.status()).toBe(200);expect((await received.json()).created).toBe(1);received=await receive();expect((await received.json()).duplicates).toBe(1);await panel.getByRole('button',{name:'수신 상태 새로고침',exact:true}).click();await expect(panel.getByText('새 주문 0 · 갱신 0 · 중복 1 · 이전 상태 0',{exact:true})).toBeVisible();await panel.getByRole('button',{name:'수신 끄기',exact:true}).click();await expect(panel.getByRole('button',{name:'수신 켜기',exact:true})).toBeVisible();expect((await receive()).status()).toBe(401);expect(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await panel.locator('summary').scrollIntoViewIfNeeded();await page.screenshot({path:`e2e/artifacts/storefront-webhook-${info.project.name}.png`});await context.close();
});
