import type {Campaign} from './agency';
import type {Publication,ExecutionCreative} from './execution';
import type {ExecutionIntent} from './growth-execution-server';
import type {GrowthCommitmentRecord,GrowthAuthorityRecord} from './growth-authority-server';
import type {GrowthRecord} from './growth-workspace-server';
import {growthView} from './growth-workspace-server';
import type {MissionInput} from './growth-mission';
import type {OfferInput,CatalogInput} from './growth-catalog';
import type {InventoryRow} from './growth-operations-server';
import {projectInventory,type InventoryEvent} from './growth-inventory';
import {evaluateAuthority} from './growth-authority';
import {confirmedFactContext} from './brand-facts-server';
import {requireGrowthRunning} from './growth-stop-server';
import {parsePublicationLink,publicationObservation,approvedPublicationBasis,type GrowthPublicationStatus} from './growth-publication';
import {executionId} from './growth-execution';
import {storefrontDigest} from './storefront-orders';
import {ApiError,database,readRecord,recordStatement,stamp,type Actor} from './server';
const kinds={link:'growth_publication_link',history:'growth_publication_history',request:'growth_publication_request'} as const;
type Scoped={brandId:string;campaignId:string};
type Publisher={channelId:string;account:string;version:number};
export type GrowthPublicationLink=Scoped&{id:string;version:number;campaignVersion:number;intentId:string;publicationId:string;status:GrowthPublicationStatus;lastPublicationVersion:number;currentIntentVersion:number;currentMissionVersion:number;releaseEvidence:'never_attempted_cancelled'|null;syncHeldReasons?:string[];snapshot:{approvedPublicationVersion:number;publication:ReturnType<typeof approvedPublicationBasis>;intentVersion:number;missionVersion:number;commitmentVersion:number;inventoryVersion:number;publisher:Publisher;evidenceRef:string;confirmedBy:string;confirmedAt:string};snapshotDigest:string;createdAt:string;updatedAt:string};
function scope<T extends Scoped>(row:T,c:Campaign){if(row.brandId!==c.brandId||row.campaignId!==c.id)throw new ApiError(404,'현재 브랜드·캠페인의 게시 연결이 아닙니다.');return row}
async function optional<T>(owner:string,kind:string,id:string){try{return await readRecord<T>(owner,kind,id)}catch(e){if(e instanceof ApiError&&e.status===404)return null;throw e}}
async function rows<T>(owner:string,kind:string,parent:string,limit:number){const result=await database().prepare('SELECT data FROM records WHERE owner=? AND kind=? AND parent_id=? LIMIT ?').bind(owner,kind,parent,limit+1).all<{data:string}>();if(result.results.length>limit)throw new ApiError(409,'게시 연결 근거 조회 한도를 넘었습니다.');return result.results.map(r=>JSON.parse(r.data) as T)}
function append(owner:string,kind:string,id:string,data:unknown,parent:string){return database().prepare('INSERT INTO records(id,owner,kind,parent_id,data,updated_at) VALUES(?,?,?,?,?,?)').bind(`${owner}:${kind}:${id}`,owner,kind,parent,JSON.stringify(data),stamp())}
async function room(owner:string,kind:string,c:Campaign,limit:number){const count=await database().prepare('SELECT COUNT(*) n FROM records WHERE owner=? AND kind=? AND parent_id=?').bind(owner,kind,c.id).first<{n:number}>();if((count?.n??0)>=limit)throw new ApiError(409,'게시 연결 기록 한도에 도달했습니다.')}
async function publication(owner:string,c:Campaign,id:string){const p=await readRecord<Publication>(owner,'execution_publication',id);if(p.campaignId!==c.id||p.id!==id)throw new ApiError(404,'현재 캠페인의 게시가 아닙니다.');return p}
async function publisher(owner:string,c:Campaign){const p=await optional<Publisher>(owner,'publisher_credential',c.brandId);return p?{channelId:p.channelId,account:p.account,version:p.version}:null}
export async function growthPublicationLinks(owner:string,c:Campaign){return (await rows<GrowthPublicationLink>(owner,kinds.link,c.id,200)).map(r=>scope(r,c))}
export async function growthPublicationView(who:Actor,c:Campaign){
 const [links,intents,pubs,credential,missions,offers]=await Promise.all([growthPublicationLinks(who.owner,c),rows<ExecutionIntent>(who.owner,'growth_action_intent',c.id,1000),rows<Publication>(who.owner,'execution_publication',c.id,1000),publisher(who.owner,c),rows<GrowthRecord<MissionInput>>(who.owner,'growth_mission',c.id,500),rows<GrowthRecord<OfferInput>>(who.owner,'growth_offer',c.id,500)]);
 return {links,intents:intents.map(i=>{scope(i,c);const m=missions.find(m=>m.id===i.input.missionId),o=offers.find(o=>o.id===m?.input.offerId);return {id:i.id,version:i.version,state:i.state,missionId:i.input.missionId,missionVersion:i.currentMissionVersion,channel:i.snapshot.mission.channel,missionTitle:m?.input.title??'',offerId:m?.input.offerId??'',offerTitle:o?.input.title??'',offerVersion:o?.version??null,offer:o?{title:o.input.title,price:o.input.price,quantity:o.input.quantity,landingUrl:o.input.landingUrl,purchaseReason:o.input.purchaseReason}:null}}),publications:pubs.filter(p=>p.campaignId===c.id).map(p=>({id:p.id,version:p.version,status:p.status,scheduledAt:p.scheduledAt,plannedCostKRW:p.plannedCostKRW,channelId:p.channelId,attemptedAt:p.attemptedAt,providerId:p.providerId,needsReview:!!p.needsReview,caption:p.caption,mediaUrl:p.mediaUrl,creativeId:p.creativeId,creativeVersion:p.creativeVersion,factRefs:p.factRefs,approvedAt:p.approvedAt})),publisher:credential?{connected:true as const,...credential}:{connected:false as const,channelId:undefined,account:undefined,version:undefined},campaignVersion:c.version,canLink:who.role!=='member'&&c.status!=='archived',canSync:who.role!=='member',mayExecute:false as const};
}
export type GrowthPublicationView=Awaited<ReturnType<typeof growthPublicationView>>;
async function savedResponse(who:Actor,c:Campaign,id:string,duplicate=false){try{return {...await growthPublicationView(who,c),resultLinkId:id,duplicate}}catch{return {recorded:true as const,viewUnavailable:true as const,resultLinkId:id,duplicate,mayExecute:false as const}}}

async function reservation(owner:string,c:Campaign,intent:ExecutionIntent){
 const item=await readRecord<InventoryRow>(owner,'growth_inventory_item',intent.input.inventoryId);if(item.brandId!==c.brandId||item.storeId!==c.storeId||intent.storeId!==c.storeId)throw new ApiError(409,'연결한 재고의 매장 범위가 변경되었습니다.');
 const events=await rows<InventoryEvent&{inventoryId:string;brandId:string;storeId:string}>(owner,'growth_stock_event',item.id,5000);if(events.some(e=>e.inventoryId!==item.id||e.brandId!==c.brandId||e.storeId!==c.storeId))throw new ApiError(409,'공유 재고 사건 범위를 확인하세요.');
 const projection=projectInventory(item.input,[...events].sort((a,b)=>a.version-b.version)),r=projection.reservations.find(r=>r.reservationId===intent.reservationId);
 if(projection.version!==item.version||projection.onHand===null||projection.shortage!==0||!r||r.missionId!==intent.input.missionId||r.quantity!==intent.input.quantity||r.held!==intent.input.quantity||r.allocated!==0||r.released!==0||projection.orders.some(o=>o.reservationId===intent.reservationId))throw new ApiError(409,'미배정된 전체 재고 예약을 다시 확인하세요.');
 return {item,reservation:r,projection};
}
async function currentContext(owner:string,c:Campaign,intent:ExecutionIntent,p:Publication,link?:GrowthPublicationLink){
 await requireGrowthRunning(owner);if(c.status==='archived'||c.version!==intent.campaignVersion||p.campaignVersion!==c.version||p.needsReview)throw new ApiError(409,'캠페인 또는 승인 게시의 현재 상태를 확인하세요.');
 const mission=scope(await readRecord<GrowthRecord<MissionInput>>(owner,'growth_mission',intent.input.missionId),c),grant=scope(await readRecord<GrowthAuthorityRecord>(owner,'growth_authority',intent.input.authorityId),c),commitment=scope(await readRecord<GrowthCommitmentRecord>(owner,'growth_commitment',intent.commitmentId),c),credential=await publisher(owner,c),stock=await reservation(owner,c,intent);
 if(intent.snapshot.mission.channel!=='organic'||mission.input.channel!=='organic'||grant.input.channel!=='organic'||mission.version!==intent.currentMissionVersion||mission.input.offerId!==intent.snapshot.mission.offerId||mission.input.offerVersion!==intent.snapshot.mission.offerVersion)throw new ApiError(409,'정확한 자연유입 미션 판을 확인하세요.');
 if(!credential||credential.channelId!==p.channelId||credential.version!==p.credentialVersion||grant.input.accountId!==credential.channelId||grant.version!==intent.input.authorityVersion||grant.campaignVersion!==c.version)throw new ApiError(409,'현재 Buffer 채널과 위임 계정·판이 일치하지 않습니다.');
 if(!Number.isSafeInteger(p.plannedCostKRW)||p.plannedCostKRW<0||!Number.isFinite(Date.parse(p.scheduledAt))||Date.parse(p.scheduledAt)<=Date.now()||Date.parse(p.scheduledAt)>Date.parse(grant.input.expiresAt)||Date.parse(p.scheduledAt)>Date.parse(grant.input.periodEnd))throw new ApiError(409,'예정 비용과 위임 유효기간 안의 예약 시각을 확인하세요.');
 if(!grant.input.allowedActions.includes('publish'))throw new ApiError(409,'현재 위임에 게시 권한이 명시되어 있어야 합니다.');
 const a=commitment.commitment.action;if(commitment.authorityId!==grant.id||commitment.authorityVersion!==grant.version||commitment.authorityApprovalId!==grant.input.ownerApprovalId||commitment.missionId!==mission.id||commitment.missionVersion!==intent.input.missionVersion||a.operationKey!==commitment.id||a.id!==mission.id||a.accountId!==credential.channelId||a.channel!=='organic'||commitment.commitment.status!=='reserved'||commitment.commitment.reservedAmount===null||p.plannedCostKRW>commitment.commitment.reservedAmount)throw new ApiError(409,'기존 예산 예약과 게시 비용의 정확한 범위를 확인하세요.');
 const ledger=await database().prepare('SELECT data FROM records WHERE owner=? AND kind=? LIMIT 10001').bind(owner,'growth_commitment').all<{data:string}>();if(ledger.results.length>10000)throw new ApiError(409,'완전한 예산 원장을 조회할 수 없습니다.');const decision=evaluateAuthority(grant.input,a,ledger.results.map(x=>(JSON.parse(x.data) as GrowthCommitmentRecord).commitment));if(!decision.allowed||!decision.duplicate)throw new ApiError(409,'현재 위임·누적 비용·손실 한도가 게시를 허용하지 않습니다.');
 const facts=await confirmedFactContext(owner,c.brandId,c.storeId);if(!p.factRefs.length||p.factRefs.some(ref=>!facts.some(f=>f.id===ref.id&&f.version===ref.version&&Date.parse(f.validUntil)>Date.parse(p.scheduledAt))))throw new ApiError(409,'승인 게시의 사실 근거가 변경되거나 만료되었습니다.');
 const creative=await readRecord<ExecutionCreative>(owner,'execution_creative',p.creativeId);if(creative.campaignId!==c.id||creative.version!==p.creativeVersion||creative.pngHash!==p.pngHash)throw new ApiError(409,'승인한 게시 소재 판이 변경되었습니다.');
 const offer=scope(await readRecord<GrowthRecord<OfferInput>>(owner,'growth_offer',mission.input.offerId),c),catalog=scope(await readRecord<GrowthRecord<CatalogInput>>(owner,'growth_catalog',offer.input.catalogId),c);if(offer.version!==mission.input.offerVersion||catalog.version!==offer.input.catalogVersion||catalog.input.sku!==stock.item.input.sku||catalog.input.stockUnit!==stock.item.input.unit)throw new ApiError(409,'현재 오퍼·상품·재고 단위가 준비 당시와 다릅니다.');
 const current=(await growthView(owner,c,true)).missions.find(m=>m.id===mission.id),stockMessages=['판매 가능한 공유 재고가 부족합니다.','오퍼 수량보다 공유 가용 재고가 부족합니다.'];if(!current||current.readiness.missing.some(reason=>!stockMessages.includes(reason))||stock.reservation.held<offer.input.quantity)throw new ApiError(409,'게시할 판매 오퍼의 근거와 보유 예약 수량을 재검토하세요.');
 if(link&&(link.campaignVersion!==c.version||intent.version!==link.currentIntentVersion||mission.version!==link.currentMissionVersion||stock.item.version!==link.snapshot.inventoryVersion||(commitment.version??1)!==link.snapshot.commitmentVersion||JSON.stringify(credential)!==JSON.stringify(link.snapshot.publisher)||await storefrontDigest(approvedPublicationBasis(p))!==await storefrontDigest(link.snapshot.publication)))throw new ApiError(409,'연결 뒤 게시 내용·계정·예산·재고 판이 변경되었습니다.');
 return {mission,grant,commitment,credential,stock};
}
function growthWrites(owner:string,c:Campaign,intent:ExecutionIntent,mission:GrowthRecord<MissionInput>,state:'unknown'|'observed'|'failed',reference:string,at:string){
 const nextMission={...mission,version:mission.version+1,status:state,receipt:{status:state,reference,note:'기존 게시 원장의 서버 결과 동기화',recordedAt:at,recordedBy:'publication-adapter'},updatedAt:at,updatedBy:'publication-adapter'},nextIntent={...intent,version:intent.version+1,state,currentMissionVersion:nextMission.version,updatedAt:at};
 const receipt={id:`${intent.id}:publication:${nextIntent.version}`,intentId:intent.id,intentVersion:nextIntent.version,campaignId:c.id,brandId:c.brandId,state,input:{status:state,reference,note:'기존 게시 원장의 서버 결과 동기화'},requestDigest:reference,source:'buffer_publication',recordedAt:at,recordedBy:'publication-adapter'};
 return {nextIntent,nextMission,writes:[recordStatement(owner,'growth_action_intent',intent.id,nextIntent,c.id),recordStatement(owner,'growth_mission',mission.id,nextMission,c.id),append(owner,'growth_action_receipt',receipt.id,receipt,c.id),append(owner,'growth_history',`mission:${mission.id}:${nextMission.version}`,{...nextMission,entity:'mission'},c.id)]};
}
export async function prepareGrowthPublicationSubmission(owner:string,c:Campaign,p:Publication,pending:Publication):Promise<{writes:D1PreparedStatement[]}>{
 const matches=(await growthPublicationLinks(owner,c)).filter(l=>l.publicationId===p.id);if(!matches.length)return {writes:[]};if(matches.length!==1)throw new ApiError(409,'게시 연결이 중복되었습니다.');const link=matches[0];
 if(link.status!=='linked'||link.lastPublicationVersion!==p.version||p.status!=='approved'||p.attemptedAt||pending.status!=='submitting'||pending.version!==p.version+1||!pending.attemptedAt||await storefrontDigest(approvedPublicationBasis(p))!==await storefrontDigest(approvedPublicationBasis(pending)))throw new ApiError(409,'승인한 미시도 게시 연결만 접수할 수 있습니다.');
 const intent=scope(await readRecord<ExecutionIntent>(owner,'growth_action_intent',link.intentId),c);if(intent.state!=='prepared')throw new ApiError(409,'이미 시도한 성장 미션을 재전송할 수 없습니다.');const context=await currentContext(owner,c,intent,p,link);await room(owner,kinds.history,c,2000);await room(owner,'growth_action_receipt',c,5000);
 const at=stamp(),growth=growthWrites(owner,c,intent,context.mission,'unknown',p.id,at),next:GrowthPublicationLink={...link,version:link.version+1,status:'submitting',lastPublicationVersion:pending.version,currentIntentVersion:growth.nextIntent.version,currentMissionVersion:growth.nextMission.version,updatedAt:at};
 return {writes:[...growth.writes,recordStatement(owner,kinds.link,link.id,next,c.id),append(owner,kinds.history,crypto.randomUUID(),next,c.id)]};
}
export async function assertGrowthPublicationDispatch(owner:string,c:Campaign,pending:Publication):Promise<void>{
 const matches=(await growthPublicationLinks(owner,c)).filter(l=>l.publicationId===pending.id);if(!matches.length)return;if(matches.length!==1)throw new ApiError(409,'게시 연결 중복');const link=matches[0],p=await publication(owner,c,pending.id);
 if(link.status!=='submitting'||link.lastPublicationVersion!==pending.version||p.version!==pending.version||p.status!=='submitting'||p.attemptedAt!==pending.attemptedAt)throw new ApiError(409,'접수 준비 판이 변경되었습니다.');const currentCampaign=await readRecord<Campaign>(owner,'campaign',c.id);if(currentCampaign.brandId!==c.brandId||currentCampaign.version!==c.version)throw new ApiError(409,'현재 캠페인 판이 변경되었습니다.');const intent=scope(await readRecord<ExecutionIntent>(owner,'growth_action_intent',link.intentId),c);if(intent.state!=='unknown')throw new ApiError(409,'접수 준비 상태가 변경되었습니다.');await currentContext(owner,currentCampaign,intent,p,link);
}
export async function assertGrowthPublicationManualReceipt(owner:string,c:Campaign,intent:ExecutionIntent){const link=await optional<GrowthPublicationLink>(owner,kinds.link,intent.id);if(link){scope(link,c);throw new ApiError(409,'연결한 게시 결과는 게시 원장 동기화로만 확인하세요.')}}
export async function assertGrowthPublicationRelease(owner:string,c:Campaign,intent:ExecutionIntent){const link=await optional<GrowthPublicationLink>(owner,kinds.link,intent.id);if(!link)return;scope(link,c);const p=await publication(owner,c,link.publicationId);if(link.releaseEvidence!=='never_attempted_cancelled'||p.status!=='cancelled'||p.attemptedAt||p.providerId||intent.state!=='failed')throw new ApiError(409,'게시 실패는 무집행 증거가 아닙니다. 미시도 취소를 서버 동기화한 경우만 해제할 수 있습니다.');}
export async function saveGrowthPublication(who:Actor,c:Campaign,b:Record<string,unknown>){
 if(b.campaignVersion!==c.version)throw new ApiError(409,'캠페인 판이 변경되었습니다.');if(!['link_publication','sync_publication'].includes(String(b.action)))throw new ApiError(400,'지원하지 않는 게시 연결 작업입니다.');if(typeof b.requestId!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(b.requestId))throw new ApiError(400,'요청 UUID를 확인하세요.');
 const requestId=b.requestId.toLowerCase(),digest=await storefrontDigest(b),previous=await optional<Scoped&{digest:string;resultLinkId:string}>(who.owner,kinds.request,requestId);if(previous){scope(previous,c);if(previous.digest!==digest)throw new ApiError(409,'같은 요청 ID의 내용이 변경되었습니다.');return savedResponse(who,c,previous.resultLinkId,true);}
 const view=b.action==='link_publication'?await growthPublicationView(who,c):null;await room(who.owner,kinds.request,c,5000);await room(who.owner,kinds.history,c,2000);const at=stamp();let next:GrowthPublicationLink;const writes:D1PreparedStatement[]=[];
 if(b.action==='link_publication'){
  await requireGrowthRunning(who.owner);if(c.status==='archived')throw new ApiError(409,'보관한 캠페인에는 연결할 수 없습니다.');const input=parsePublicationLink(b),intent=scope(await readRecord<ExecutionIntent>(who.owner,'growth_action_intent',input.intentId),c),p=await publication(who.owner,c,input.publicationId);
  if(b.expectedVersion!==0||await optional(who.owner,kinds.link,intent.id)||view!.links.some(l=>l.publicationId===p.id))throw new ApiError(409,'미션과 게시는 각각 한 번만 불변 연결할 수 있습니다.');if(intent.version!==input.intentVersion||intent.state!=='prepared'||p.version!==input.publicationVersion||p.status!=='approved'||p.attemptedAt||p.providerId)throw new ApiError(409,'준비된 미션과 승인된 미시도 게시의 정확한 판을 선택하세요.');if(view!.links.length>=200)throw new ApiError(409,'게시 연결 한도에 도달했습니다.');
  const context=await currentContext(who.owner,c,intent,p),snapshot={approvedPublicationVersion:p.version,publication:approvedPublicationBasis(p),intentVersion:intent.version,missionVersion:context.mission.version,commitmentVersion:context.commitment.version??1,inventoryVersion:context.stock.item.version,publisher:context.credential,evidenceRef:input.evidenceRef,confirmedBy:who.id,confirmedAt:at};
  next={id:intent.id,intentId:intent.id,publicationId:p.id,brandId:c.brandId,campaignId:c.id,campaignVersion:c.version,version:1,status:'linked',lastPublicationVersion:p.version,currentIntentVersion:intent.version,currentMissionVersion:context.mission.version,releaseEvidence:null,snapshot,snapshotDigest:await storefrontDigest(snapshot),createdAt:at,updatedAt:at};writes.push(append(who.owner,kinds.link,next.id,next,c.id));
 }else{
  const link=scope(await readRecord<GrowthPublicationLink>(who.owner,kinds.link,executionId(b.id)),c),p=await publication(who.owner,c,link.publicationId);if(b.expectedVersion!==link.version||b.publicationVersion!==p.version)throw new ApiError(409,'게시 연결·결과 판이 변경되었습니다.');const intent=scope(await readRecord<ExecutionIntent>(who.owner,'growth_action_intent',link.intentId),c),mission=scope(await readRecord<GrowthRecord<MissionInput>>(who.owner,'growth_mission',intent.input.missionId),c);if(mission.version!==intent.currentMissionVersion)throw new ApiError(409,'성장 미션 결과 판을 먼저 대사하세요.');const observed=publicationObservation(p);
  if(observed.releaseEvidence===null&&await storefrontDigest(approvedPublicationBasis(p))!==await storefrontDigest(link.snapshot.publication))throw new ApiError(409,'연결한 승인 게시 내용·계정·예약 조건이 변경되어 결과를 승격할 수 없습니다.');
  if(p.version===link.lastPublicationVersion){await database().batch([append(who.owner,kinds.request,requestId,{id:requestId,brandId:c.brandId,campaignId:c.id,digest,resultLinkId:link.id},c.id)]);return savedResponse(who,c,link.id,true);}
  const conflict=intent.state==='observed'&&observed.intentState!=='observed';
  next={...link,version:link.version+1,status:conflict?'unknown':observed.status,lastPublicationVersion:p.version,releaseEvidence:conflict?null:observed.releaseEvidence,syncHeldReasons:conflict?['이미 게시 확인된 미션과 최신 공급자 결과가 다릅니다. 이전 관측을 지우거나 무집행으로 해제하지 않습니다.']:[],updatedAt:at};
  if(observed.intentState!=='prepared'){await room(who.owner,'growth_action_receipt',c,5000);const state=intent.state==='observed'?'observed':observed.intentState,growth=growthWrites(who.owner,c,intent,mission,state,p.id,at);next={...next,currentIntentVersion:growth.nextIntent.version,currentMissionVersion:growth.nextMission.version};writes.push(...growth.writes);}
  writes.push(recordStatement(who.owner,kinds.link,next.id,next,c.id));
 }
 writes.push(append(who.owner,kinds.history,crypto.randomUUID(),next,c.id),append(who.owner,kinds.request,requestId,{id:requestId,brandId:c.brandId,campaignId:c.id,digest,resultLinkId:next.id},c.id));await database().batch(writes);
 return savedResponse(who,c,next.id);
}
