import type {AuthorityAction,AuthorityCommitment,AuthorityInput} from './growth-authority';
export const deliveryKinds={current:'growth_consumer_delivery',history:'growth_consumer_delivery_history',request:'growth_consumer_delivery_request'};
export type DeliveryInput={customerId:string;customerVersion:number;purpose:'post_purchase'|'marketing_reorder'|'service_reply';templateId:string;templateDigest:string;maxCostKrw:number;expiresAt:string;waitDays:number;authorityId:string;authorityVersion:number;serviceContext?:{ticketId:string;ticketVersion:number;sourceDigest:string}};
export type DeliveryScope={tenantId:string;providerStoreId:string;storeId:string;mode?:'cs'};
export type DeliveryPayload={requestId:string;recipientId:string;purpose:DeliveryInput['purpose'];templateId:string;templateDigest:string;maxCostKrw:number;expiresAt:string;consentDigest:string;serviceContext?:DeliveryInput['serviceContext']};
export type DeliveryReceipt={requestId:string;payloadDigest:string;status:'accepted'|'delivered'|'failed';costKrw:number|null;receiptId:string;at:string;code:null|'cancelled'|'rejected'|'expired'};
export type DeliveryRow={id:string;brandId:string;campaignId:string;campaignVersion:number;version:number;customerId:string|null;input:DeliveryInput|null;status:'queued'|'unknown'|'accepted'|'delivered'|'failed';approval:{snapshotDigest:string;approvedBy:string;approvedAt:string;autoDispatch?:boolean}|null;payload:DeliveryPayload|null;payloadDigest:string|null;providerScope:DeliveryScope|null;maxCostKrw:number;commitmentId:string|null;suppressed:boolean;cancelPending:boolean;cancelAttempts?:number;cancelRetryAt?:string;executionAttempts?:number;executionRetryAt?:string;executionHeld?:boolean;csResponseHeld?:boolean;receipt:DeliveryReceipt|null;createdAt:string;updatedAt:string};
export type DeliveryAuthority={id:string;version:number;brandId:string;campaignId:string;campaignVersion:number;input:AuthorityInput};
export type DeliveryCommitment={id:string;brandId:string;campaignId:string;authorityId:string;authorityVersion:number;authorityApprovalId:string;authoritySnapshot:AuthorityInput;missionId:string;missionVersion:number;commitment:AuthorityCommitment;createdAt:string;createdBy:string};
export class DeliveryInputError extends Error{}
export const deliveryUuid=(x:unknown):x is string=>typeof x==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x);
export function parseDeliveryInput(value:unknown):DeliveryInput{
 if(!value||typeof value!=='object'||Array.isArray(value))throw new DeliveryInputError('발송 입력을 확인하세요.');
 const x=value as DeliveryInput,keys=['customerId','customerVersion','purpose','templateId','templateDigest','maxCostKrw','expiresAt','waitDays','authorityId','authorityVersion',...(x.purpose==='service_reply'?['serviceContext']:[])];
 if(Object.keys(x).some(k=>!keys.includes(k))||!deliveryUuid(x.customerId)||!deliveryUuid(x.templateId)||!['post_purchase','marketing_reorder','service_reply'].includes(x.purpose)||typeof x.templateDigest!=='string'||!/^[a-f0-9]{64}$/.test(x.templateDigest)||!Number.isSafeInteger(x.customerVersion)||x.customerVersion<1||!Number.isSafeInteger(x.authorityVersion)||x.authorityVersion<1||!Number.isSafeInteger(x.maxCostKrw)||x.maxCostKrw<0||x.maxCostKrw>100000000||!Number.isSafeInteger(x.waitDays)||x.waitDays<0||x.waitDays>365||typeof x.authorityId!=='string'||!/^[A-Za-z0-9_-]{1,100}$/.test(x.authorityId)||typeof x.expiresAt!=='string'||!/^\d{4}-\d\d-\d\dT.*Z$/.test(x.expiresAt)||!Number.isFinite(Date.parse(x.expiresAt)))throw new DeliveryInputError('목적·UUID·템플릿 판·비용·만료일을 확인하세요. 연락처와 메시지 원문은 저장하지 않습니다.');
 if(x.purpose==='service_reply'){const r=x.serviceContext;if(!r||Object.keys(r).sort().join(',')!=='sourceDigest,ticketId,ticketVersion'||!deliveryUuid(r.ticketId)||!Number.isSafeInteger(r.ticketVersion)||r.ticketVersion<1||typeof r.sourceDigest!=='string'||!/^[a-f0-9]{64}$/.test(r.sourceDigest)||x.maxCostKrw!==0)throw new DeliveryInputError('현재 문의 판과 비용 0의 서비스 답변을 확인하세요.')}
 return {...x};
}
export function deliveryAction(row:Pick<DeliveryRow,'id'|'brandId'|'campaignId'>,input:DeliveryInput,scope:DeliveryScope):AuthorityAction{return {id:row.id,operationKey:`consumer-delivery-${row.id}`,brandId:row.brandId,campaignId:row.campaignId,accountId:scope.tenantId,channel:input.purpose==='service_reply'?'cs_service_reply':'consumer_delivery',operation:input.maxCostKrw===0?'publish':'spend',amount:input.maxCostKrw,loss:input.maxCostKrw,budget:'exploration',previousBudget:null,nextBudget:null,evidence:null}}

export const deliveryNeedsReceipt=(row:DeliveryRow)=>['unknown','accepted'].includes(row.status)||(!!row.commitmentId&&row.receipt?.costKrw===null);
