// Durable write journal. The paused route supplies owner authorization, current creative review and a distinct write credential.
import {ApiError,database,readRecord,stamp,str} from './server';
import type {Campaign} from './agency';
import {storefrontDigest} from './storefront-orders';
import {pausedCampaignDraft,preparedPausedReceipt,type PausedCampaignDraft,type PausedCampaignJournal,type PausedCampaignReceipt} from './meta-paused-campaign';
export type PausedCampaignOperation={id:string;campaignId:string;brandId:string;campaignVersion:number;evidenceFingerprint:string;draft:PausedCampaignDraft;receipt:PausedCampaignReceipt;version:number;createdAt:string;updatedAt:string;createdBy:string;updatedBy:string};
export async function preparePausedCampaignOperation(owner:string,input:{campaignId:string;campaignVersion:number;evidenceFingerprint:string;accountId:string;name:string;specialCategoryReview:string;createdBy:string}){
 const campaign=await readRecord<Campaign>(owner,'campaign',str(input.campaignId,'캠페인',100,true));if(campaign.status==='archived'||campaign.version!==input.campaignVersion)throw new ApiError(409,'현재 캠페인 기준으로 다시 준비하세요.');
 if(!/^[a-f0-9]{64}$/.test(input.evidenceFingerprint))throw new ApiError(400,'검토 근거의 식별자가 필요합니다.');
 const scope={campaignId:campaign.id,brandId:campaign.brandId,campaignVersion:campaign.version,evidenceFingerprint:input.evidenceFingerprint,accountId:input.accountId,name:str(input.name,'캠페인 이름',120,true),objective:'OUTCOME_SALES',specialCategoryReview:input.specialCategoryReview},id=await storefrontDigest(scope),draft=pausedCampaignDraft({accountId:scope.accountId,name:scope.name,objective:scope.objective,specialCategoryReview:scope.specialCategoryReview,operationKey:id}),now=stamp();
 const operation:PausedCampaignOperation={id,campaignId:campaign.id,brandId:campaign.brandId,campaignVersion:campaign.version,evidenceFingerprint:input.evidenceFingerprint,draft,receipt:preparedPausedReceipt(draft),version:1,createdAt:now,updatedAt:now,createdBy:str(input.createdBy,'행위자',100,true),updatedBy:input.createdBy};
 await database().prepare('INSERT OR IGNORE INTO records(id,owner,kind,parent_id,data,updated_at) VALUES(?,?,?,?,?,?)').bind(`${owner}:meta_ads_write_operation:${id}`,owner,'meta_ads_write_operation',campaign.id,JSON.stringify(operation),now).run();return readRecord<PausedCampaignOperation>(owner,'meta_ads_write_operation',id);
}
export function pausedCampaignJournal(owner:string,id:string,actorId:string):PausedCampaignJournal{
 const read=()=>readRecord<PausedCampaignOperation>(owner,'meta_ads_write_operation',id);
 async function swap(old:PausedCampaignOperation,receipt:PausedCampaignReceipt,guardCampaign=false){const now=stamp(),next={...old,receipt,version:old.version+1,updatedAt:now,updatedBy:str(actorId,'행위자',100,true)};return !!(await database().prepare("UPDATE records SET data=?,updated_at=? WHERE id=? AND owner=? AND kind=? AND data=?"+(guardCampaign?" AND EXISTS (SELECT 1 FROM records c WHERE c.id=? AND c.owner=? AND c.kind='campaign' AND json_extract(c.data,'$.version')=? AND json_extract(c.data,'$.brandId')=? AND json_extract(c.data,'$.status')<>'archived')":'')).bind(JSON.stringify(next),now,`${owner}:meta_ads_write_operation:${id}`,owner,'meta_ads_write_operation',JSON.stringify(old),...(guardCampaign?[`${owner}:campaign:${old.campaignId}`,owner,old.campaignVersion,old.brandId]:[])).run()).meta.changes}
 function scope(old:PausedCampaignOperation,r:PausedCampaignReceipt){if(r.operationKey!==id||r.accountId!==old.draft.accountId)throw new ApiError(409,'작업 식별자와 광고 계정이 다릅니다.');if(old.receipt.externalId&&r.externalId!==old.receipt.externalId)throw new ApiError(409,'확인한 외부 객체 식별자는 변경할 수 없습니다.');}
 return {async begin(receipt){const old=await read();if(old.receipt.state!=='prepared'||receipt.state!=='sending'||receipt.externalId!==null)return false;scope(old,receipt);const campaign=await readRecord<Campaign>(owner,'campaign',old.campaignId);if(campaign.version!==old.campaignVersion||campaign.brandId!==old.brandId||campaign.status==='archived')throw new ApiError(409,'캠페인이 변경되어 전송을 예약하지 않았습니다.');return swap(old,receipt,true)},async finish(receipt){const old=await read();scope(old,receipt);if(!(['sending','unknown'].includes(old.receipt.state)||old.receipt.state==='paused_verified'&&receipt.state==='paused_verified')||!['unknown','paused_verified'].includes(receipt.state)||receipt.state==='paused_verified'&&(!receipt.externalId||!receipt.verifiedAt))throw new ApiError(409,'작업 상태를 되돌리거나 임의로 확정할 수 없습니다.');if(!await swap(old,receipt))throw new ApiError(409,'작업 상태가 변경되었습니다. 다시 조회하세요.')}};
}
