import { env } from 'cloudflare:workers';
import { brandDefaults, type Campaign, type Brand, type Artifact, type Metric } from './agency';
export class ApiError extends Error {constructor(public status:number,message:string){super(message)}}
export const runtime=env as unknown as {DB?:D1Database;AGENCY_ENCRYPTION_KEY?:string;OPENAI_API_KEY?:string};
export function database(){if(!runtime.DB)throw new ApiError(503,'저장 공간에 연결하지 못했습니다. 잠시 후 다시 시도하세요.');return runtime.DB}
export function identity(request:Request){const id=request.headers.get('oai-authenticated-user-id');if(id)return id;if(process.env.NODE_ENV==='development')return 'local-preview';throw new ApiError(401,'로그인이 필요합니다. 페이지를 새로고침해 주세요.')}
export function secureMutation(request:Request){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new ApiError(403,'허용되지 않은 요청입니다.')}
export const stamp=()=>new Date().toISOString();
export const uid=()=>crypto.randomUUID();
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}
export function failure(e:unknown){if(e instanceof ApiError)return json({error:e.message},e.status);console.error('agency_request_failed',e instanceof Error?e.message:'unknown');return json({error:'처리하지 못했습니다. 입력한 내용을 유지한 채 다시 시도해 주세요.'},500)}
export async function body(req:Request){if(Number(req.headers.get('content-length')||0)>200000)throw new ApiError(413,'입력 내용이 너무 큽니다.');const s=await req.text();if(s.length>200000)throw new ApiError(413,'입력 내용이 너무 큽니다.');try{return JSON.parse(s)}catch{throw new ApiError(400,'입력 형식을 확인해 주세요.')}}
export function str(value:unknown,label:string,max=10000,required=false){if(typeof value!=='string'||value.length>max||(required&&!value.trim()))throw new ApiError(400,`${label} 입력을 확인해 주세요.`);return value.trim()}
export function num(value:unknown,label:string){if(typeof value!=='number'||!Number.isFinite(value)||value<0||value>1e12)throw new ApiError(400,`${label}은 0 이상의 숫자로 입력해 주세요.`);return value}
export function recordStatement(owner:string,kind:string,id:string,data:unknown,parentId=''){return database().prepare('INSERT INTO records(id,owner,kind,parent_id,data,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data, updated_at=excluded.updated_at WHERE records.owner=excluded.owner').bind(`${owner}:${kind}:${id}`,owner,kind,parentId,JSON.stringify(data),stamp())}
export async function readRecord<T>(owner:string,kind:string,id:string){const row=await database().prepare('SELECT data FROM records WHERE id=? AND owner=? AND kind=?').bind(`${owner}:${kind}:${id}`,owner,kind).first<{data:string}>();if(!row)throw new ApiError(404,'항목을 찾을 수 없습니다.');return JSON.parse(row.data) as T}
export async function listRecords<T>(owner:string,kind:string,parentId?:string){const q=parentId?database().prepare('SELECT data FROM records WHERE owner=? AND kind=? AND parent_id=? ORDER BY updated_at DESC').bind(owner,kind,parentId):database().prepare('SELECT data FROM records WHERE owner=? AND kind=? ORDER BY updated_at DESC').bind(owner,kind);const rows=await q.all<{data:string}>();return rows.results.map(r=>JSON.parse(r.data) as T)}
export function eventStatement(owner:string,campaignId:string,message:string){const id=uid();return recordStatement(owner,'event',id,{id,campaignId,message,createdAt:stamp()},campaignId)}
export async function seedBrands(owner:string){const initialCampaign:Campaign={id:'ofd-pilot-01',brandId:'ofd',title:'평일의 도넛 리추얼',goal:'올드페리도넛의 브랜드 매력을 유지하면서 평일 방문과 제품 구매를 늘리는 캠페인을 설계합니다. 상시 할인에 의존하지 않는 구매 이유를 검증합니다.',audience:'매장 인근 직장인과 평일 오후 디저트 고객 (검증할 가설)',channels:'Instagram, 매장 안내, 기존 고객 채널',stores:'파일럿 매장 선정 필요',products:'실제 판매 제품·가격 확인 필요',budget:0,startDate:'',endDate:'',constraints:'기존 로고·캐릭터·컬러 유지. 원가와 매장 운영 여력을 확인하고 실험 범위를 정하기.',sources:'초기 기획 제안 · 대표님과의 AI 마케팅 회사 설계 대화 기반. 실측 고객·매출 자료는 아직 연결되지 않았습니다.',status:'draft',version:1,createdAt:stamp(),updatedAt:stamp()};const rows=brandDefaults.map(b=>database().prepare('INSERT OR IGNORE INTO records(id,owner,kind,parent_id,data,updated_at) VALUES(?,?,?,?,?,?)').bind(`${owner}:brand:${b.id}`,owner,'brand','',JSON.stringify(b),stamp()));rows.push(database().prepare('INSERT OR IGNORE INTO records(id,owner,kind,parent_id,data,updated_at) VALUES(?,?,?,?,?,?)').bind(`${owner}:campaign:${initialCampaign.id}`,owner,'campaign','',JSON.stringify(initialCampaign),stamp()));await database().batch(rows)}
export function validateCampaign(v:Record<string,unknown>){const fields=['brandId','title','goal','audience','channels','stores','products','startDate','endDate','constraints','sources'] as const;const out={} as Record<string,string|number>;for(const key of fields)out[key]=str(v[key]??'',key==='title'?'캠페인 이름':key==='goal'?'목표':key,key==='sources'?20000:5000,['brandId','title','goal'].includes(key));if(!brandDefaults.some(b=>b.id===out.brandId))throw new ApiError(400,'브랜드를 선택해 주세요.');for(const date of [out.startDate,out.endDate])if(date&&(!/^\d{4}-\d{2}-\d{2}$/.test(String(date))||!Number.isFinite(Date.parse(String(date)))))throw new ApiError(400,'날짜를 확인해 주세요.');if(out.startDate&&out.endDate&&out.startDate>out.endDate)throw new ApiError(400,'종료일은 시작일 이후여야 합니다.');out.budget=num(v.budget??0,'예산');return out as unknown as Omit<Campaign,'id'|'status'|'version'|'createdAt'|'updatedAt'>}
async function cryptoKey(){if(!runtime.AGENCY_ENCRYPTION_KEY)throw new ApiError(503,'AI 연결 저장을 준비 중입니다. 관리자에게 문의해 주세요.');return crypto.subtle.importKey('raw',Uint8Array.from(atob(runtime.AGENCY_ENCRYPTION_KEY),c=>c.charCodeAt(0)),{name:'AES-GCM'},false,['encrypt','decrypt'])}
export async function encrypt(value:string){const iv=crypto.getRandomValues(new Uint8Array(12));const bytes=await crypto.subtle.encrypt({name:'AES-GCM',iv},await cryptoKey(),new TextEncoder().encode(value));return btoa(String.fromCharCode(...iv))+'.'+btoa(String.fromCharCode(...new Uint8Array(bytes)))}
export async function decrypt(value:string){const[iv,data]=value.split('.');const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:Uint8Array.from(atob(iv),c=>c.charCodeAt(0))},await cryptoKey(),Uint8Array.from(atob(data),c=>c.charCodeAt(0)));return new TextDecoder().decode(plain)}
export async function configuration(owner:string){return database().prepare('SELECT secret,model FROM settings WHERE owner=?').bind(owner).first<{secret:string|null;model:string}>()}
export async function connection(owner:string){const c=await configuration(owner);const key=c?.secret?await decrypt(c.secret):runtime.OPENAI_API_KEY;if(!key)throw new ApiError(409,'AI 연결이 필요합니다. 연결 및 설정에서 API 키를 등록해 주세요.');return {key,model:c?.model||'gpt-6-astra'}}

export async function acquireLock(owner:string){const token=uid();const r=await database().prepare('INSERT INTO mutation_locks(owner,token,expires_at) VALUES(?,?,?) ON CONFLICT(owner) DO UPDATE SET token=excluded.token,expires_at=excluded.expires_at WHERE mutation_locks.expires_at < ?').bind(owner,token,Date.now()+120000,Date.now()).run();if(!r.meta.changes)throw new ApiError(409,'다른 작업을 저장하고 있습니다. 잠시 후 다시 시도하세요.');return token}
export async function releaseLock(owner:string,token:string){await database().prepare('DELETE FROM mutation_locks WHERE owner=? AND token=?').bind(owner,token).run()}
export async function assertNoActiveJobs(owner:string){const r=await database().prepare("SELECT id FROM jobs WHERE owner=? AND status IN ('starting','queued','in_progress','uncertain') LIMIT 1").bind(owner).first();if(r)throw new ApiError(409,'AI 작업이 진행 중입니다. 결과를 확인하거나 연결된 작업을 취소한 후 변경해 주세요.')}
